### ISSUE TITLE
GUIDED_NOGPS can this mode be used and how to use it

### ISSUE THREAD

**Issue by ZDLLLL** [mavlink/qgroundcontrol#10000]
I tried to adjust the mode to GUIDED_NOGPS, but nothing changed. Can this mode really be switched over? Can anyone help me

**Comment by booo** [comment]
As far as I can see this is a supported mode for ardupilot copter. Please provide more information about your setup and/or use the forum to get help with the operation of your system.

If you think a feature is missing or you are encounter a bug please reopen the ticket.
