### ISSUE TITLE
QGroundControl unable to update SI1060 Radio

### ISSUE THREAD

**Issue by vincentpoont2** [mavlink/qgroundcontrol#10001]
## Expected Behavior
Sik1060 radio FW should upgrade.

## Current Behavior
Sik1060 radio would not upgrade.

## System Information
When posting bug reports, include the following information
- Window 10
- QGC Version 4.1.4
- QGC stable build

## Detailed Description
QGroundControl would not update Holybro SI1060 radio. Support for this radio was added here https://github.com/ArduPilot/SiK.

**Comment by booo** [comment]
Can you provide us with some logs? Otherwise this is quite hard to debug.

**Comment by DonLakeFlyer** [comment]
Also try a daily build and see if that crashes as well

**Comment by vincentpoont2** [comment]
I sent a pair to @DonLakeFlyer . I have ask PX4 developers to assist on finding the source of the FW (http://px4-travis.s3.amazonaws.com/SiK/stable/radio~hm_trp.ihx).

@dagar is helping us to look into this. I suspect that it might be from https://github.com/LorenzMeier/SiK and it need a sync with upstream. Support for this SI1060 Radio has been added to https://github.com/ArduPilot/SiK.

![DailyBuild QGC Ver](https://user-images.githubusercontent.com/46874772/141405434-cb3e38af-c490-4506-a679-f5b5dd77452f.jpg)
![DailyBuild QGC](https://user-images.githubusercontent.com/46874772/141405439-5ea5ddab-b3a7-427a-8531-8cda49b7ade6.jpg)

**Comment by DonLakeFlyer** [comment]
So from this report it's unclear if you were seeing a crash. Does it crash after you get the "did not respond to command mode" report?

For me the radio goes into command mode fine. The problem is that the board id returned for this radio is 80. Whereas all other SiK radios are 78. This cause the firmware for it to not be found. Why is this different if this is going to use the same firmware as other SiK radios?

**Comment by DonLakeFlyer** [comment]
I tried simulating a failure at the command mode step and I couldn't cause it to crash with that either.

**Comment by vincentpoont2** [comment]
So Sorry @DonLakeFlyer, I have updated the title, the "crash" only happened in Mission Planner and I got confused.
This radio uses a different chip, SI1060 vs SI1000 before, so the board_ID changed.

**Comment by vincentpoont2** [comment]
The support was added on here. https://github.com/ArduPilot/SiK. I am still trying to figure out where QGC pull this from via @mrpollo and how to get QGC to be able to perform upgrade for this radio.

**Comment by DonLakeFlyer** [comment]
> This radio uses a different chip, this new radio uses SI1060, the previous one uses SI1000, so the board_ID changed.

Ok, understood. I can add support for the new board id but I don't think that makes sense until this: http://px4-travis.s3.amazonaws.com/SiK/stable/radio~hm_trp.ihx get updated to support the new radio. Otherwise it's going to flash incorrect firmware. Is that correct?

**Comment by mrpollo** [comment]
@DonLakeFlyer here's the link to the new firmware https://px4-travis.s3.amazonaws.com/SiK/stable/radio~hb1060.ihx

**Comment by DonLakeFlyer** [comment]
@mrpollo Where was this built from? If this comes from the ArduPilot repo then it is incorrect with respect to PX4. The PX4 sik radio firmware has updates for mavlink 2 support detection which are not in the ArduPilot repo.

**Comment by vincentpoont2** [comment]
This was sent to me by Andrew Tridgell and I am assuming it is built from [https://github.com/ArduPilot/SiK](https://github.com/ArduPilot/SiK).

**Comment by DonLakeFlyer** [comment]
So that means it is only "sort of" correct. The PX4 version of Sik radio firmware has additional support for mavlink v2 protocol negotiation whereas the ardupilot version does not. So that feature will be lost. Not a show-stopper necessarily. But the PX4 version of the Sik radio firmware should be brought up to date with the ardupilot changes. And then QGC should switch to using that somewhat better version. For now I think we can live without that feature. Unless this can be taken care of quickly by PX4 folks before I push out a new stable.

**Comment by vincentpoont2** [comment]
@mrpollo do you know if this is something PX4 can assist with?

**Comment by vincentpoont2** [comment]
@DonLakeFlyer May you add it as it is, then we will check & test it via QGC Daily.

**Comment by DonLakeFlyer** [comment]
Yup. That's my plan.

**Comment by DonLakeFlyer** [comment]
@vincentpoont2 Would be helpful if you could verify things still working on both SI1000 and SI1060 boards.

**Comment by vincentpoont2** [comment]
Hi @DonLakeFlyer I just tried it on both SI1000 & SI1060 boards.

I am not sure why there was a couple instances it failed to upgrade, but at the end, I was able to upgrade on both pair of radios and the connection was successful. 

![image](https://user-images.githubusercontent.com/46874772/145242219-d4a0fa70-0097-4902-af0d-912ae651c6c8.png)
![image](https://user-images.githubusercontent.com/46874772/145242239-41626f3e-c598-4262-9017-ef31deb39cf8.png)
![image](https://user-images.githubusercontent.com/46874772/145242251-eb0fded5-b2ca-4a9e-b9ab-1e3688ef3f94.png)

**Comment by DonLakeFlyer** [comment]
@vincentpoont2  Thanks for testing. Those Sync problems are fairly common. Radios (not sure why) seem to be flaky with respect to getting them into bootloader mode. If you retry it will tend to work. I've looked at it in the past and never found anything I could do in QGC that would prevent it from happening.
