### ISSUE TITLE
High CPU rate Ubuntu 20

### ISSUE THREAD

**Issue by farhangnaderi** [mavlink/qgroundcontrol#10026]
## Expected Behavior
Normal param transfer after connecting the FCU. 

## Current Behavior
CPU load high error received and all params transfer stopped.  

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Open QGC (Fresh download)
2. Connect your FCU 
3. Wait for Param transfer

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 20.04
- QGC Version: Daily
- QGC build: daily
- Flight Controller: Pixhawk 4
- Autopilot (with version): PX4 1.12.3 and master

## Log Files and Screenshots
![Screenshot from 2021-11-17 20-58-43](https://user-images.githubusercontent.com/46557204/142268672-3972bdce-b1d7-4ab1-9ce6-09839480d2a3.png)
![Screenshot from 2021-11-17 20-59-00](https://user-images.githubusercontent.com/46557204/142268693-ba92ac20-317e-474d-a378-22a5bf0408a8.png)
![Screenshot from 2021-11-17 21-01-26](https://user-images.githubusercontent.com/46557204/142268709-f1507e1b-a850-466f-bdcf-c84ea986ef9e.png)

**Comment by farhangnaderi** [comment]
tried in another system, same CPU load high.

**Comment by booo** [comment]
Please use one issue to describe exactly one problem.

**Comment by farhangnaderi** [comment]
Thanks @booo , Corrected.

**Comment by dagar** [comment]
Which board is this and what's it running exactly?

**Comment by farhangnaderi** [comment]
v5x and Pixhawk4 both same. Running master and also tried with the stable.

**Comment by dagar** [comment]
> v5x and Pixhawk4 both same. Running master and also tried with the stable.

Can you get to a console and run `top`? Which airframe?

**Comment by farhangnaderi** [comment]
Hardware not at hand now. S500 Frame.

**Comment by mrpollo** [comment]
Tested on a VM under macOS using FMUv5X with PX4 master + QGC Daily and I couldn't reproduce, anything else you can share will help @farhangnaderi

**Comment by farhangnaderi** [comment]
I changed my Ubuntu (Fresh new one) and everything seems ok with Pixhawk4 and the latest QGC daily. Will open another issue if the problem reproduced.
