### ISSUE TITLE
Remove revision number from Blue Robotics Power Sense Module option in Power settings

### ISSUE THREAD

**Issue by dgudiel** [mavlink/qgroundcontrol#10027]
The revision number for the Blue Robotics power sense module in the Power sensor options it currently out of date for the latest R3 version. Removing the revision number will eliminate the need to update this each time the PSM is updated.

**Comment by booo** [comment]
Can you create a pull request for that?

You mean this line?

https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/APM/APMPowerComponent.qml#L344
