### ISSUE TITLE
maybe not a problem

### ISSUE THREAD

**Issue by GitTongZQ** [mavlink/qgroundcontrol#10024]
line 534 in QGCApplication.cc
mavlinkSingletonFactory return a QGCMAVLink object , but qmlRegisterSingletonType ShapeFileHelper at line 534 ?

I'm new for QGC and i don't sure if it's wrong.

**Comment by booo** [comment]
Please use a descriptive title for your issue. And please provide a link to the files and lines you mentioned on github.
