### ISSUE TITLE
Multi-Vehicle: Connect speed too slow

### ISSUE THREAD

**Issue by lwx0715** [mavlink/qgroundcontrol#10060]
## Current Behavior
When handle with more than 3 Vihicles, the connection between QGroundControl and px4 vihicles is very slow. When connecting 5 quadrotors, it takes about 10 minutes to complete the connection. And it sometimes happens that the parameter return is incomplete.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.Download QGroundControl source code
2.Build & Run the project from Qt Creator
3.connect 5 px4 vehicles like quadrotors

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04 LTS
- QGC Version: V3.5.6 Stable
- QGC build: self-built from source
- Flight Controller: Pixhawk 4
- Autopilot (with version): PX4 1.10.1

What should we do to speed up the connection?
Thank you

**Comment by HTRamsey** [comment]
Please reopen if this is still an issue on a recent version.
