### ISSUE TITLE
x track error is getting subtracted from altitude?

### ISSUE THREAD

**Issue by tstastny** [mavlink/qgroundcontrol#10061]
## Expected Behavior
The XTrackError fact should display the position controllers cross track error. 

## Current Behavior
Currently it always shows x track error + altitude setpoint.

## Detailed Description
The problem is here: [https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.cc#L999](https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.cc#L999)

I can make a one liner PR (remove the altitude setpoint from this calculation..), but thought I'd check quickly here to see if this was for some reason intended?

**Comment by tstastny** [comment]
@AndKe it looks like you were the one to implement this in #9699. Interested in your original intent, thanks!

**Comment by AndKe** [comment]
@tstastny   Nah, I have no excuse for that. most likely I just copied nearby line when I made it. Feel free to correct.  :)
Thanks
