### ISSUE TITLE
Gstreamer: internal data stream error

### ISSUE THREAD

**Issue by new-user-name** [mavlink/qgroundcontrol#10071]
## Expected Behavior
Test Gstreamer pattern should be visible

## Current Behavior
Test Gstreamer pattern is not visible on Android and visible on Windows

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior

1. Build QGC from master, no errors, Windows 10 and Android (armeabi-v7a).
2. Gstreamer test
 gst-launch-1.0 videotestsrc ! x264enc ! rtph264pay ! udpsink port=5000 host=127.255.255.255
for Windows build, OK
3. Gstreamer test
 gst-launch-1.0 videotestsrc ! x264enc ! rtph264pay ! udpsink port=5000 host=192.168.0.103
for Android build, GstVideoReceiver.cc:1305 - Gstreamer error: internal data stream error".

I tried Android builds on Windows and Ubuntu, the result is the same.
Beta form Playmarket gives the same error.

Android 6.0, ARM-V7.

**Comment by new-user-name** [comment]
Gstreamer warning level gives a lot of
`<h264parse0> broken/invalid nal Type`
both in Windows and Android,

**Comment by kressinluiz** [comment]
You can try to:
- enable low latency mode
- change the caps after x264enc to ! video/x-h264, stream-format=avc ! 
- set is-live property of videotestsrc to true

**Comment by new-user-name** [comment]
Low latency enabled already, no avail. I can't change Gstreamer test because my goal is to make Android work with exactly the same Gstreamer string as in Windows.

**Comment by new-user-name** [comment]
So I can change onlу receiver Gstreamer config.

**Comment by new-user-name** [comment]
God knows why, the thing works on Android 7. Maybe I can find additional logs somewhere?..

**Comment by kressinluiz** [comment]
Currently I see the qgroundcontrol pipeline as (udpsrc):
![image](https://user-images.githubusercontent.com/20712533/145716664-f6dcde4c-f6e4-4299-b514-53c028639032.png)
You can try this pipeline that imitates qgroundcontrol pipeline (udpsrc):
- gst-launch-1.0 --gst-debug 1 udpsrc address=localhost port=5600 ! application/x-rtp, media=video, clock-rate=90000, encoding-name=H264 ! parsebin ! tee name=t ! queue ! valve ! decodebin3 ! autovideosink t. ! queue ! valve ! matroskamux ! filesink location=teste05.mkv
(matroskamux can be changed for mp4mux or qtmux)
It is easier to debug from the command line. You can change the gstreamer debug level but it is hell to find any useful info.

If I try:
- gst-launch-1.0 videotestsrc ! x264enc ! rtph264pay ! udpsink port=5000 host=localhost
It doesn't work. It returns internal data stream error.  But I can make it work with:
- gst-launch-1.0 --gst-debug 1 videotestsrc pattern=ball is-live=true ! video/x-raw, format=I420, width=640, height=480, framerate=30/1 !  x264enc ! rtph264pay ! udpsink host=localhost port=5600

So I think if you look into the errors that popup when you remove is-live=true and video/x-raw caps, you can find what is missing from the receiver pipeline.

**Comment by new-user-name** [comment]
The second example works, you are right. Just change port=5000 to 5600 in first short example (the main point stays the same).

**Comment by new-user-name** [comment]
Test could be reduced to
gst-launch-1.0 --gst-debug 1 videotestsrc pattern=ball ! video/x-raw, format=I420 ! x264enc ! rtph264pay ! udpsink host=localhost port=5600
