### ISSUE TITLE
qgroundcontrol ntrip

### ISSUE THREAD

**Issue by syt011019** [mavlink/qgroundcontrol#10139]
I wonder if there is an ntrip function in current qgc and when it will be implemented in the future

**Comment by WTPENGUIN** [comment]
There is 'Add NTRIP' among pull requests. However, the main author not update this pull for a months. Someone instead may have to complete.

**Comment by WTPENGUIN** [comment]
@syt011019 https://github.com/mavlink/qgroundcontrol/pull/9493 check this.

**Comment by syt011019** [comment]
> Can you explain how to download it?

**Comment by WTPENGUIN** [comment]
@syt011019 https://dev.qgroundcontrol.com/master/en/getting_started/ read dev documents.

**Comment by syt011019** [comment]
Did you build and run this to confirm that Ntrip is working?

**Comment by WTPENGUIN** [comment]
@syt011019 No. I haven't checked if it works.
