### ISSUE TITLE
UI: Structure Scan module is not structured properly (labels/boxes above one another)

### ISSUE THREAD

**Issue by gromain** [mavlink/qgroundcontrol#10142]
![image](https://user-images.githubusercontent.com/2188885/151820967-43d2760b-db9c-4dd3-8940-0f61c45a54b7.png)
Screenshot is pretty self-explanatory.
Labels and modules are getting on top of one another and make thing unusable to setup the Structure Scan.

## Steps to Reproduce:
1. Open latest daily AppImage
2. Start a flight plan and add a structure scan
3. Add a polygon
4. Look at the right colum

## System Information
When posting bug reports, include the following information
- Operating System: Manjaro
- QGC Version: daily
- QGC build: daily Appimage and built from source

## Log Files and Screenshots
```
[D] at ../../qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:281 - "Settings location "/home/rbazile/.config/QGroundControl.org/QGroundControl Daily.ini" Is writable?: true"
[D] at ../../qgroundcontrol/qgroundcontrol/src/QGCLoggingCategory.cc:120 - "Filter rules "*Log.debug=false\nGStreamerAPILog.debug=true\nqt.qml.connections=false""
[D] at ../../qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:384 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en-US""
[E] at :0 - "Found no modules in speech-dispatcher. No text to speech possible."
[D] at ../../qgroundcontrol/qgroundcontrol/src/Vehicle/MAVLinkLogManager.cc:360 - "MAVLink logs directory: "/home/rbazile/Documents/QGroundControl Daily/Logs""
[D] at ../../qgroundcontrol/qgroundcontrol/src/QtLocationPlugin/QGCMapEngine.cpp:164 - "Map Cache in: "/home/rbazile/.cache/QGCMapCache300" / "qgcMapCache.db""
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2370 - "setCurrentPlanViewSeqNum"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2370 - "setCurrentPlanViewSeqNum"
[E] at ../../qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:284 - "Stop called on empty URI"
[E] at ../../qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:284 - "Stop called on empty URI"
[E] at qrc:/qml/PlanView.qml:798 - "qrc:/qml/PlanView.qml:798: TypeError: Cannot read property 'width' of null"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2370 - "setCurrentPlanViewSeqNum"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2370 - "setCurrentPlanViewSeqNum"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2370 - "setCurrentPlanViewSeqNum"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2471 - "Found"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:2479 - "Delayed split"
[D] at ../../qgroundcontrol/qgroundcontrol/src/MissionManager/MissionController.cc:1387 - "Update delayed split segment"
```

**Comment by gromain** [comment]
Any information on this, or where I should be looking to try and solve this?

**Comment by mrpollo** [comment]
thanks @gromain I can confirm this bug exists, the QML file that holds the editor pane for structure scan is called `StructureScanEditor.qml`

I also noticed there seems to be some values hidden in black font I'm not sure if that's intentional
<img width="1012" alt="Screen Shot 2022-02-08 at 9 17 35 AM" src="https://user-images.githubusercontent.com/317648/153040464-076105f1-2662-4837-af93-d4771f51197e.png">

Overlapping labels are there on macOS even on really big screen resolutions
![Screen Shot 2022-02-08 at 9 08 34 AM](https://user-images.githubusercontent.com/317648/153040218-8ed826b6-55ad-485c-b541-86d2e281f8f4.jpg)

**Comment by gromain** [comment]
Yes, there are definitely text fields here. I'll have a look at `StructureScanEditor.qml`, but I'm not familiar with Qt, so not sure I'll be able to help a lot!

**Comment by gromain** [comment]
It seems like there is an issue with the `CameraCalcGrid.qml` layout, in particular, the Column items should be ColumnLayout.
```
diff --git a/src/PlanView/CameraCalcGrid.qml b/src/PlanView/CameraCalcGrid.qml
index 495051237..537c2c68d 100644
--- a/src/PlanView/CameraCalcGrid.qml
+++ b/src/PlanView/CameraCalcGrid.qml
@@ -9,7 +9,7 @@ import QGroundControl.FactControls      1.0
 import QGroundControl.Palette           1.0
 
 // Camera calculator "Grid" section for mission item editors
-Column {
+ColumnLayout {
     spacing: _margin
 
     property var    cameraCalc
@@ -31,7 +31,7 @@ Column {
 
     QGCPalette { id: qgcPal; colorGroupEnabled: true }
 
-    Column {
+    ColumnLayout {
         anchors.left:   parent.left
         anchors.right:  parent.right
         spacing:        _margin
```

There is still a tiny issue for now:
![image](https://user-images.githubusercontent.com/2188885/153094796-73c3db46-d967-4797-a965-881f73824c16.png)

**Comment by gromain** [comment]
Looks like #10160 will do it! Thanks @holden-zenith !

**Comment by gromain** [comment]
Thanks a lot @mrpollo and @holden-zenith !
