### ISSUE TITLE
ADSB use server name not IP address

### ISSUE THREAD

**Issue by timtuxworth** [mavlink/qgroundcontrol#10172]
Tell us a bit about the feature:
- What problem does it solve?
Who knows IP addresses these days? 
- What does it do?
Allow the ADSB server to be addressed by name
- What flight stacks must it work with? (All, PX4, ArduPilot)
All
- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
All
- Are there other systems that have this feature?
Pretty much the whole internet
- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
adsb/dns

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
If a server changes the IP address of the dump1090 service could change. This might happen if a DHCP lease expires and a new IP is allocated, or if a server switches networks (e.g. if there is a failover network set up). If a domain name was used this would work dynamically. As it is, it will require manual intervention any time the server IP changes.

**Comment by booo** [comment]
The `connectToHost` function that we use internally supports hostnames too. Did you try setting the value to a hostname? 

Maybe its just a matter of changing the description in the GUI.

**Comment by timtuxworth** [comment]
> The `connectToHost` function that we use internally supports hostnames too. Did you try setting the value to a hostname?
> 
> Maybe its just a matter of changing the description in the GUI.

Yes I tried, the UI threw an error.

**Comment by booo** [comment]
> > The `connectToHost` function that we use internally supports hostnames too. Did you try setting the value to a hostname?
> > Maybe its just a matter of changing the description in the GUI.
> 
> Yes I tried, the UI threw an error. Maybe its just a question of changing the validation on the UI?

Changing the value to "localhost" did not throw an error her. Can you post the error?

**Comment by timtuxworth** [comment]
I was using raspberrypi.local and (I think) the RadarBox was down when I tried adding it. In fact the error wasn't thrown till I restarted QGC. I guess this means this Request is not required. 
![Screen Shot 2022-02-18 at 10 47 00 AM](https://user-images.githubusercontent.com/5266784/154744100-939d75d8-df32-49a3-91d8-9238b087a831.png)

**Comment by booo** [comment]
I'm not sure if hostnames work. If you tested successfully with active host it think we should change the label of the option.

**Comment by zdanek** [comment]
I've checked it and it works. I used my flightradar24 box host-name. 
I think it's important that no matter which addres will be used it must be resolvable to an IP. So `ping` this name and if it works it will work in QGC as well.

![image](https://user-images.githubusercontent.com/440614/154806399-eac32b4e-d572-45b6-8ce5-5f3dc1ae4502.png)

**Comment by timtuxworth** [comment]
I closed it. I think "Host address" is ok as the label @booo - it doesn't say "IP address" and if we changed it to say hostname, it might mislead folks into thinking IP address wasn't an option. Host Address can be read to mean hostname or IP address. A tool tip would probably be helpful, but that seems to be a more general UI issue, none of the fields seem to have tool tips.
