### ISSUE TITLE
Install drivers as non-administrator

### ISSUE THREAD

**Issue by 0431814** [mavlink/qgroundcontrol#10184]
Hello,
I was trying to install QGroundControl on a school laptop without administrator and was able to get the program itself installed, but noticed there were drivers that tried installing I had to cancel because it asked again for permissions. I noticed I'm able to reinstall them later with the "driver.exe" but was wondering if there was a way to install them without admin as well.

Quick edit, just wanted to ask if the drivers were necessary to start working with the Pixhawk 4 in case I'm not able to get them installed. I haven't been able to get access to it yet to test it out.

**Comment by booo** [comment]
It's normal that a driver needs admin rights to install. It's part of the OS and therefore you need special permission to install the driver. Normal user should not be able to install drivers for the whole system and its users.
