### ISSUE TITLE
Comm Links view doesn't show

### ISSUE THREAD

**Issue by mrpollo** [mavlink/qgroundcontrol#10180]
Using the daily version of QGC I get a blank page, and running with logging turned on shows me this:

```
qrc:/qml/LinkSettings.qml:140:13: Type MockLinkOptionsDlg unavailable
qrc:/qml/QGroundControl/Controls/MockLinkOptionsDlg.qml: No such file or directory
```

<img width="1253" alt="Screen Shot 2022-02-22 at 1 03 25 PM" src="https://user-images.githubusercontent.com/317648/155219230-55bd1ffd-dfc7-4d80-87d9-57184e717eb3.png">

**Comment by mrpollo** [comment]
Seems to be related to 670a12b361 @DonLakeFlyer

**Comment by DonLakeFlyer** [comment]
Yeah, most likely. I'll take a look.

**Comment by highfreq** [comment]
Hello, just compiled from master last sunday and i can't see comm links too, is there a solution to this?
Running it on Android 12.

**Comment by DonLakeFlyer** [comment]
Sorry lost track of this. I'll try to get to it today some time.

**Comment by highfreq** [comment]
Actually i pulled the repo and recompiled and now it is there

**Comment by DonLakeFlyer** [comment]
I verified it to be working fine on Ubuntu as well
