### ISSUE TITLE
The Info View isn't space efficient

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1018]
The text added to the Quick subtab of the Info View doesn't fill up to maximum when only 1 entry is there, as I would expect if there's more horizontal space. And when more items are added, all of the items shrink in size, even if there isn't space pressure yet. And finally, too many items can be added such that they overlap and become unreadable. I'm pretty certain that a proper fix can be found that solves all of these issues at once.

**Comment by LorenzMeier** [comment]
Will get / is removed.
