### ISSUE TITLE
Application Settings MAVLink shows error

### ISSUE THREAD

**Issue by mrpollo** [mavlink/qgroundcontrol#10181]
Using QGC Daily when navigating to the MAVLink settings page (see screenshot) with logging turned on, I get the following error.

```
qrc:/qml/MavlinkSettings.qml:753: ReferenceError: object is not defined
```
<img width="1258" alt="Screen Shot 2022-02-22 at 1 06 49 PM" src="https://user-images.githubusercontent.com/317648/155219583-f5d5e26f-c092-4454-9145-b8632cce3d6b.png">

**Comment by HTRamsey** [comment]
Considering the Application Settings have been rewritten, and that file no longer exists, this can probably be closed.
