### ISSUE TITLE
unable to find renderer plugin for opengl

### ISSUE THREAD

**Issue by ebesin** [mavlink/qgroundcontrol#10197]
I want to add a Scene3D item in QGC, but when I start QGroundControl, it givs the following error:
`unable to find renderer plugin for opengl`

-  operating system: Ubuntu 20.04
- QGroundControl: the latest version

I wonder how to solve this problem?

**Comment by ebesin** [comment]
This 3D scene works fine on other projects, but I had a problem porting to QGC, I don’t know how to fix it.  ╥﹏╥

**Comment by HTRamsey** [comment]
Not a problem in master anymore, but for older builds you need to copy the plugin. https://www.qtcentre.org/threads/71088-SOLVED-Deploying-Qt3D-application-Unable-to-find-renderer-plugin-for-opengl
