### ISSUE TITLE
PX4 Autotuning UI not displayed for Fixed Wing

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#10194]
Autotuning is supported on PX4 for MC, FW and VTOL vehicles, but the UI is not shown in QGC for fixed wing (you can still trigger it using `FW_AT_START` but that is undesirable.

The UI should be updated to allow the feature to be used.

**Comment by Jaeyoung-Lim** [comment]
Greatly appreciate @hamishwillee that this was clear from the docs.

Would you know who I would need to talk to in order to enable Auto tuning for fixed wings?
At least it would be great if the plots are shown so it can be used for manually hand tuning

**Comment by bkueng** [comment]
> I was struggling to understand why the PID tuning UI would not appear for fixed wing vehicles

It's all ready, I just never got a definitive list of plots from @RomanBapst.

> Is this a bug? or intentionally blocked to prevent it from being used?

I think it was just never added to the UI.

**Comment by Jaeyoung-Lim** [comment]
@bkueng Thanks! @RomanBapst Could we move this forward?

It is painful(or impossible) to tune the vehicle with mavlink inspector since the `VEHICLE_ATTITUDE` message is in quaternions and `VEHICLE_ATTITUDE_SETPOINT` is in euler angles

**Comment by hamishwillee** [comment]
> I think it was just never added to the UI.

Yes, this was an omission. Would be good if @RomanBapst could provide the required info!!!

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I ended up fixing it myself! https://github.com/mavlink/qgroundcontrol/pull/10384
