### ISSUE TITLE
android daily build stopped updating

### ISSUE THREAD

**Issue by tridge** [mavlink/qgroundcontrol#10207]
the android daily stopped updating on 17th Jan 2021. Anyone know how to track this down?

![image](https://user-images.githubusercontent.com/831867/157976459-27d7fea0-6f5e-4a70-b534-30288b579ce9.png)
https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrolbeta

**Comment by Davidsastresas** [comment]
Just to link the PR to this issue, so both can be closed when merged into master: #10208

I tested the PR locally and it works as expected

**Comment by holden-zenith** [comment]
This can be closed

**Comment by booo** [comment]
How does the playstore get updated?

Do we need to adopt the changes here https://github.com/mavlink/qgroundcontrol/pull/10208/files to the new github workflows?

**Comment by Davidsastresas** [comment]
That PR, as far as I remember, was addressing the issue of the artifacts not being updated to github in actions. The issue of updating the .apk to the appstore wasn't addressed on that PR.

Latest update to Playstore was on Jan 27 2021. This one issue is solved ( CI is working and android artifacts are being uploaded to github actions ), so I think we can close it and continue the play store discussion in #10529
