### ISSUE TITLE
Code of connecting and controlling the drone

### ISSUE THREAD

**Issue by Zxr1230** [mavlink/qgroundcontrol#10218]
I am building a simple Android app to control my own PX4 drone. I am facing problems with connecting and controlling the drone. I wonder where is the QGC code for connecting and controlling the drone. I could get some idea from it. Thank you!

**Comment by booo** [comment]
I think you should take a look at the `src/Vehicle/Vehicle.cc` code to get a first impression of how communication is handled. QGC uses mavlink to communicate with the drone. You should get familiar with mavlink too.
