### ISSUE TITLE
what's mean about Sea of Japan??

### ISSUE THREAD

**Issue by KrJoon** [mavlink/qgroundcontrol#10225]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

This is Wrong!
the Sea of Korea!!!
![bugs](https://user-images.githubusercontent.com/102334405/160030596-01552ac1-ba1c-4b87-8ed6-ddfbc66ce671.png)

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by MaEtUgR** [comment]
@KrJoon I assume this is realted to https://en.wikipedia.org/wiki/Sea_of_Japan_naming_dispute

In any case, QGroundcontrol uses unchanged content from the configured map provider by default Bing maps. If you have any complaints about the map content please reach the provider directly.

Google Maps seems to use the same names but with different label locations.
![image](https://user-images.githubusercontent.com/4668506/160365553-d4474a7d-13d7-4c06-aec1-7369ba9424dc.png)
