### ISSUE TITLE
Tried to change custom from px4 to ardupilot...

### ISSUE THREAD

**Issue by highfreq** [mavlink/qgroundcontrol#10257]
Tried to change custom from px4 to ardupilot. Chnged all the px4 calls and used APM, changed .h files. Everything compiles but i get a linker error on:

45: error: undefined reference to 'CustomFirmwarePlugin::CustomFirmwarePlugin()'

Don't understand, the class is defined and .h is included........

Any help would be HUGELY appreciated.

**Comment by HTRamsey** [comment]
If you still have questions, it is better to ask via the forums or discord.
