### ISSUE TITLE
No instructions for building for Airmap

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#10260]
The [build instructions for Linux](https://dev.qgroundcontrol.com/master/en/getting_started/) fail because they assume Airmap SDK is present, but there are no instructions for getting the Airmap dependencies. 

- How do we get and install the airmap dependencies? 
- Is there any cost to using them?
- What platform can it be used on?

These should be added to https://dev.qgroundcontrol.com/master/en/getting_started/#install-qt step 4 "Install Optional/OS-Specific Functionality"

I'd also argue that the define should be reversed - if Airmap is the exception then you should enable it using the define, not disable it.

**Comment by ckpradip** [comment]
@hamishwillee , do we have any updates regarding this ?
I created a file `user_config.pri` in project root directory and added this line - `DEFINES += DISABLE_AIRMAP`. But I am still seeing the same error. I am not sure if I am missing anything else !

**Comment by Kim-zhi-jiang** [comment]
echo "CONFIG = WarningsAsErrors" >> /home/xxx/qgroundcontrol/user_config.pri
echo "DEFINES = DISABLE_AIRMAP" >> /home/xxx/qgroundcontrol/user_config.pri
