### ISSUE TITLE
Is there a firmware for the board with ID 3?

### ISSUE THREAD

**Issue by UnRuly000** [mavlink/qgroundcontrol#10287]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

QGroundControl can upgrade the firmware on Pixhawk devices, SiK Radios and PX4 Flow Smart Cameras.
All QGroundControl connections to vehicles must be disconnected prior to firmware upgrade.
Please unplug your Pixhawk and/or Radio from USB.
Found device: PX4 FMU V2
Connected to bootloader:
Version: 5
Board ID: 3
Flash size: 1032192
Downloading firmware...
From: C:/Users/admin/Downloads/px4fmu-v2_default.px4
Download complete
Downloaded firmware board id does not match hardware board id: 9 != 3
Image load failed
Upgrade cancelled
------------------------------------------
If upgrade failed, make sure to connect directly to a powered USB port on your computer, not through a USB hub. Also make sure you are only powered via USB not battery.
Upgrade cancelled
------------------------------------------

Is there a firmware for the board with ID 3?

**Comment by WTPENGUIN** [comment]
Hardware board IDs are not determined by QGC. I know it is determined when building the PX4 firmware.
[Reference](https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v2/firmware.prototype)

you may to ask questions to the PX4 community.

**Comment by booo** [comment]
Question answered by fellow user.
