### ISSUE TITLE
I want to use the tcp/udp protocol to connect to QGC，How should I build a server？

### ISSUE THREAD

**Issue by zouzhe1** [mavlink/qgroundcontrol#10293]
I want to use a 4G serial port DTU module to connect this module to my server, and then the server will do some processing. Finally, QGC uses TCP or UDP to connect the server address and port to complete the connection of pixhawk.
I want to ask this DIY server, which software should be running on it? Is it a mavlink forwarding program? Or what other program can realize my function.
thanks

**Comment by WTPENGUIN** [comment]
Take a look at this.

[mavlink-router](https://github.com/mavlink-router/mavlink-router.git)

**Comment by booo** [comment]
Question was answered.
