### ISSUE TITLE
Android 10 and above,  video decoding using soft decoding?

### ISSUE THREAD

**Issue by zalebool** [mavlink/qgroundcontrol#10301]
It is found that when using Android 10 and above, the video decoding is all using soft decoding, not using hard decoding.  That Gstreamer uses decodebin3 element, Google launched Codec2.0 on Android Q, which was to replace ACodec and OpenMAX.  is it the problem of Gstreamer's support for codec2?

## Expected Behavior
Video decoding should use hw decoding first

## Current Behavior
Video decoding always use soft decoding

## System Information
- Operating System: [Android 11]
- QGC Version: [4.2.0]

## Detailed Description
it's Gstreamer problem?  I think  android  media use the codec2.0 , but Gstreamer not supports very good. Could you give me some ideas.

## Log Files and Screenshots

This is Gstreamer pipeline(pipeline-with-new-decoder-pad.dot) run android9, it use hw decoding.

![pipeline-with-new-decoder-pad](https://user-images.githubusercontent.com/10580026/170249253-9c3776e5-a83f-4a0f-ac81-7baaa9b36869.png)

zoom in
![Android9](https://user-images.githubusercontent.com/10580026/170251629-739a695e-8970-493c-88fb-e84bfef0fea8.png)

This is Gstreamer pipeline(pipeline-with-new-decoder-pad.dot) run android11,it use soft decoding.
![pipeline-with-new-decoder-pad (1)](https://user-images.githubusercontent.com/10580026/170251149-dff2a0d3-6919-40e0-8ed7-4e6654d33d0d.png)

zoom in
![Android11](https://user-images.githubusercontent.com/10580026/170251648-ce20d91a-c8f0-4785-b847-642015df7979.png)

**Comment by pasdVn** [comment]
I experimented a bit with gstreamer and different devices:
On one device running android 12 (galaxy s8), gstreamer also did not use the hardware decode by default ("amcviddec" or similar). For me it helped to implement the autoplug query function as described here: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/928

I don't know what this exactly does or why it is necessary on some devices (or android versions!?), but it did the job.
However I don't know if this is an device specific issue or if it is tied to the android version (I did not run another andoid version on this device).
