### ISSUE TITLE
Finding message reception code in the repo

### ISSUE THREAD

**Issue by MWaleedK** [mavlink/qgroundcontrol#10308]
I've been successful in sending messages from a script to the ground station. I would like to know as to where is the message acquisition/reconstruction module located in QGroundcontrol repository. I need to change the code a bit to suit my case. I would like to change the tts command there with a cv2.imshow command.

**Comment by booo** [comment]
Please check the codebase for mavlink messages. There are multiple places where interaction with the vehicle happens via mavlink messages.
