### ISSUE TITLE
Android tests fail creating build directory

### ISSUE THREAD

**Issue by mrpollo** [mavlink/qgroundcontrol#10311]
I just noticed Android builds successfully but then fail to try to create the `shadow_build_dir/package` directory, did anything change recently?

```
mkdir: cannot create directory ‘/home/runner/work/_temp/shadow_build_dir/package’: File exists
[7356](https://github.com/mavlink/qgroundcontrol/runs/6619470758?check_suite_focus=true#step:13:7356)
```

Source https://github.com/mavlink/qgroundcontrol/runs/6619470758?check_suite_focus=true

**Comment by booo** [comment]
Android builds seem to work now. See https://github.com/mavlink/qgroundcontrol/actions/runs/3035410034 for example.
