### ISSUE TITLE
Unknown command problem

### ISSUE THREAD

**Issue by ldm0330** [mavlink/qgroundcontrol#10329]
Hello, I would like to ask if I updated the latest version of QGC. When I click to create a waypoint during use, it will appear unknown: 84, unknown: 16 and display all parameters. How to solve this problem?

**Comment by 1chick** [comment]
# same issue.
- "add waypoint" button can not be clicked in planview.
![image](https://user-images.githubusercontent.com/20314338/179645819-7e75debf-1000-4221-86e1-bda46596b8ed.png)
- unknow waypoint ,command combox is blank 
![image](https://user-images.githubusercontent.com/20314338/179646678-7880159a-97d4-4cd4-bd20-980e1307aa3a.png)

# Enviroment:
1.QGC Release v4.2.3
2.win10/android os
3.ardupilot,Rover v4.2.2 firmware

**Comment by LnAYuTaK** [comment]
你好，我在version 4.2.0中也遇到这个问题，但是我尝试了上面的解决方法并没有解决这个问题，请问下还有其他需要修改的地方么

Hello, I also encountered this problem in version 4.2.0, but I tried the above solution and failed to solve the problem. Is there anything else that needs to be modified

**Comment by booo** [comment]
Could you check if the proposed change fixes your problem? You can find binaries for testing in the pull request and workflow runs: https://github.com/mavlink/qgroundcontrol/pull/10491

**Comment by booo** [comment]
Fix merged into master.
