### ISSUE TITLE
Connect to the UE through a different network

### ISSUE THREAD

**Issue by matbord** [mavlink/qgroundcontrol#10326]
Right now QGC is trying to connect to the UE only through WIFI. Now, I have attached to my laptop another radio, is it already possible to use it to send commands to the UE? How?

**Comment by booo** [comment]
I don't understand your problem/question.

You can connect to the vehicle with all radios that support serial communication. It is possible to connect via ethernet too.

Pleae reopen if you still have problems with your configuration.
