### ISSUE TITLE
Pixhawk 6C only work with Daily Build

### ISSUE THREAD

**Issue by vincentpoont2** [mavlink/qgroundcontrol#10338]
Pixhawk 6C was just released, but unfortunately it only works with the daily build, not the stable build.

I am curious to see if new QGC release is coming soon. If not, can we do a release soon for this?
PR that added the Pixhawk 6C: https://github.com/mavlink/qgroundcontrol/pull/10297/files 

Please let me know if this possible, we greatly appreciated.

**Comment by vincentpoont2** [comment]
@patrickelectric @mrpollo Greatly appreciated.

**Comment by BL12Z** [comment]
Sorry for being a total (github) noob here, but how do i get this daily build? 

I have the 6C and its not working. Im used to working with the pixhawk 4 and that always just worked when i plugged in the USB cable.

**Comment by vincentpoont2** [comment]
> Sorry for being a total (github) noob here, but how do i get this daily build?
> 
> I have the 6C and its not working. Im used to working with the pixhawk 4 and that always just worked when i plugged in the USB cable.
> 
> (trying to install on windows)

You can download it here.
https://docs.qgroundcontrol.com/master/en/getting_started/download_and_install.html#daily-builds

**Comment by BL12Z** [comment]
> You can download it here. https://docs.qgroundcontrol.com/master/en/getting_started/download_and_install.html#daily-builds

Thats just the official released version, it does not support 6C.
Or am i doing something else wrong?

When i plug in PixHawk 4 mini - works
When i plug in PixHawk 6X - works
When i plug in PixHawk 6C - Nothing, no connection, not working...

I recon its the problem of it only working on the "daily build" so im looking to get that installed

**Comment by patrickelectric** [comment]
Try using the artifacts here: https://github.com/mavlink/qgroundcontrol/actions?query=branch%3Amaster

**Comment by BL12Z** [comment]
Yesss thats what i was looking for, now i can get on with my new quadcopter beast. Thank you so much!!
