### ISSUE TITLE
Add Ukranian as a language

### ISSUE THREAD

**Issue by randev45** [mavlink/qgroundcontrol#10340]
Is it possible to add Ukrainian to the language options?

**Comment by zdanek** [comment]
Of course. Can you provide translations from English? All translations are to be put in bundle file then some testing - does it fit into widgets and we're good to go. Are you Ukrainian and can you help with translation?

**Comment by AndreySkyFoxSidorov** [comment]
> 
Do you have a CSV table (key/eng/uk_UA) ?
I want to help with Ukrainian localization, but the xml format is inconvenient,
Why are you using a table? Now it is very convenient to use formulas(=GoogleTranslate(A2, "en", "ua")) in Google sheets. Of course, the result needs to be checked. But this gives 60-80 percent of the correct translation.

**Comment by randev45** [comment]
Any updates on this? I too can help with the translation if it's added to crowdintel. Thanks.

**Comment by haltarkon** [comment]
Are there any news on this issue? I am also ready to engage in high-quality translation. Unfortunately, there is still no Ukrainian in crowdin.

**Comment by DonLakeFlyer** [comment]
@hamishwillee Do you know who the whole CrowdIn flow works? I haven't been in there in ages. Do I need to do something first on the QGC side, or can this start with some CrowdIn settings adjustments?

**Comment by DonLakeFlyer** [comment]
@haltarkon We'll get this figured out. Hopefully won't take long. Thanks for the help.

**Comment by DonLakeFlyer** [comment]
@HTRamsey Know anything about CrowdIn?

**Comment by DonLakeFlyer** [comment]
Guess I should have look at my own docs. Created these ages ago:
```
## Crowdin integration
Crowdin is configured to automatically sychronize the qgc.ts file once a day. So it will pick up any new changes automatically. Once it has processed those changes it will submit a pull request back with the translations.
```

**Comment by DonLakeFlyer** [comment]
Once my pull gets merged it will take a day to flow through CrowdIn. Then I'll let you know when Ukranian is ready to start translating.

**Comment by DonLakeFlyer** [comment]
Should be all there now

**Comment by DonLakeFlyer** [comment]
@haltarkon @randev45 So the way transitions work is that when they are below 40% translated they are not included new stable releases. The language is available in daily builds though for testing purposes.
