### ISSUE TITLE
Wrong joystick button events after d87e419239b3eb4468a757a8208d3dc7f001b2e8

### ISSUE THREAD

**Issue by svpcom** [mavlink/qgroundcontrol#10346]
## Expected Behavior
Joystick model: Sony DualShock 4 V2
Joystick has 15 buttons. Each button press is one event.

## Current Behavior
Joystick model: Sony DualShock 4 V2
Joystick has 17 buttons. Press button 11 generate events for 11 and 13, press button 12 generate events for 12 and 14

## Steps to Reproduce:
1. Run QGC
2. Open Vehicle setup
3. Open joystick tab

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04
- QGC Version: 4.2.3
- QGC build: from github releases
- Flight Controller: px4-sitl
- Autopilot (with version): px4-1.13
## Detailed Description
The problem was introduced in commit d87e419239b3eb4468a757a8208d3dc7f001b2e8 ( Fix Joystick Button Count )

## Log Files and Screenshots
![qgc-joystick-bug](https://user-images.githubusercontent.com/503830/179010225-06d36676-822b-4767-8ec4-a3cbb3a1f4fc.png)

**Comment by zdanek** [comment]
Hi.
Can you check and post output from command line call to `jstest`?
For example `jstest /dev/input/js0` or other if your Dualshock registers as different event file.
`jstest` is available via apt.

**Comment by svpcom** [comment]
`jstest` shows that single event was generated. Also there are two additional buttons that exists in jstest, but unavailable in QGC. It is L2 and R2 buttons (https://manuals.playstation.net/document/en/ps4/basic/pn_controller.html)

**Comment by holden-zenith** [comment]
Probably worthwhile waiting for the SDL database to be updated to see if it is fixed
