### ISSUE TITLE
Flow Control Settings Don't Save

### ISSUE THREAD

**Issue by ryanjAA** [mavlink/qgroundcontrol#10352]
This is on Daily and a Mac.

When adding a new Comm link if I hit advanced, enable flow control (it is enabled on the actual hardware) and select 1 stop bit and hit ok, the stop bit amount doesnt save. It just goes back to 2 if I open it back up.

![11](https://user-images.githubusercontent.com/31726584/180253724-72840242-5f0e-4021-9164-68a49d0a4503.gif)

**Comment by miasavelli** [comment]
I am also experiencing this issue. QGC seems to not recognize that advanced settings has been checked. However, it does take into account if parity is changed.
