### ISSUE TITLE
Sub: Navigator: Gimbal controls missing channels 15 and 16.

### ISSUE THREAD

**Issue by ES-Alexander** [mavlink/qgroundcontrol#10351]
## Expected Behavior
Navigator autopilot servo output channels 15 and 16 should be assignable to camera gimbal controls, via the "Camera Setup" page.

## Current Behavior
The "Camera Setup" page dropdowns only include channels 5 to 14 for assigning to gimbal functionalities.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Connect computer to Navigator autopilot
2. Open QGC
3. Go to "Camera Setup" page
4. Select "Output Channel" dropdown, and see that channels 15 and 16 are not available

## System Information
When posting bug reports, include the following information
- Operating System: All
- QGC Version: 4.2.3
- QGC build: stable
- Flight Controller: Navigator (Linux)
- Autopilot (with version): ArduSub 4.1.0 (stable)

## Detailed Description
The actual functionality works fine - e.g. if 
- a servo is connected to channel 16, and
- the `SERVO16_FUNCTION` parameter is set to `MountTilt`, and
- the `mount_tilt_*` joystick button functionalities are activated

then the servo will move as expected. The issue is purely that valid options are missing from the dropdown menu(s) of the "Camera Setup" page. The "Lights" page correctly shows channels 15 and 16 as available.

Issue was raised [in this forum post](https://discuss.bluerobotics.com/t/navigator-camera-tilt-servo/12527).

@Williangalvani I expect/hope this should be reasonably straightforward to fix? :-)

**Comment by Williangalvani** [comment]
this was done in https://github.com/mavlink/qgroundcontrol/pull/10261
