### ISSUE TITLE
RTK GPS with QGC

### ISSUE THREAD

**Issue by xindax2000** [mavlink/qgroundcontrol#10355]
I connected the RTK GNSS device to the Pixhawk thorugh the TELEM port. I use only one device. It works perfectly as a normal GPS.
I have an u-center ntrip caster. I send the RTCM messages from the ntrip caster by MASDK to the Pixhawk. The messaging works also perfectly. But the GNSS still don't turn into RTK. What needs to be configured in QGC?

**Comment by booo** [comment]
You can configure RTK in the application settings:

https://docs.qgroundcontrol.com/master/en/SettingsView/General.html

RTK tutorial from the internet:

https://bfdsystems.atlassian.net/wiki/spaces/BFWIK/pages/101482723/RTK+with+QGroundControl
