### ISSUE TITLE
QGC 4.2.3:  When runnig QGC for Linux,  The map is broken in WSL2 environment. 

### ISSUE THREAD

**Issue by Arccoma** [mavlink/qgroundcontrol#10350]
![97c2bbc9-cb58-4ff7-a553-fbbe87ef9bc5](https://user-images.githubusercontent.com/102889296/179714896-9e327daa-6b2e-4443-ac5a-b9f356e35e56.png)
< Figure1.  PX4 on SITL  simulatoin with Gazebo without QGC >

I am currently trying to simulate PX4 using Gazebo.
When "command takeoff" was entered without a connection to the QGC, the FailSafe was activated and the drone's prop stopped immediately and failed to take off.

After reding https://github.com/PX4/PX4-Autopilot/issues/19205#issuecomment-1046306704,
I downloaded the QGC daily version for Linux (v4.2.3) under [WSL2 environment](https://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html) following the instructions in the link below to connect the QGC to Gazebo to avoid FailSafe and succeed in Takeoff.
https://docs.qgroundcontrol.com/master/en/getting_started/download_and_install.html

However, when running QGroundContrl.AppImage, I encountered the following error.
![48d3b756-e07a-4bd5-8668-249ca1950914](https://user-images.githubusercontent.com/102889296/179715212-138d2b21-228b-49d6-b548-a6eca0a35328.png)
< Figure 2.  Fail to run QGroundContrl.AppImage >

> /tmp/.mount_QGrounXXXXXX/QGroundControl: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
(  'XXXXXX' keeps changing every time )

https://github.com/mavlink/qgroundcontrol/issues/10306 After seeing this help and doing 

> sudo apt-get install -y libpulse-dev

I was able to run QGC. 
But the QGC screen comes out like this.
![57e7bb9b-0a42-4232-937a-7b325084cc3c](https://user-images.githubusercontent.com/102889296/179734345-9e1bd6f3-5382-4ccf-90e0-b7c638017326.png)
< Figure 3.  Broken Map >

![image](https://user-images.githubusercontent.com/102889296/180700218-36996144-e9c8-4cb0-a471-92b02ff569f9.png)
< Figure 4. QGC test in 3 computers >

Besides the computer(Ryzen Desktop) that breaks the QGC map, I tested it on two other laptops, where the map doesn't break. I don't know why the map is broken or not. ( The map of QGC for Windows does not break in all three computers.)
I'd appreciate your help.

**Comment by Arccoma** [comment]
https://github.com/mavlink/qgroundcontrol/issues/10306
After seeing this help and doing 

> sudo apt install -y libpulse-dev

I was able to run QGC. 
But the QGC screen comes out like this.
![57e7bb9b-0a42-4232-937a-7b325084cc3c](https://user-images.githubusercontent.com/102889296/179734345-9e1bd6f3-5382-4ccf-90e0-b7c638017326.png)

**Comment by Arccoma** [comment]
![image](https://user-images.githubusercontent.com/102889296/180143005-3d85adf8-52b6-4d15-8abc-89e27b620c4d.png)

Besides the computer(Ryzen Desktop) that breaks the QGC map, I tested it on two other laptops, where the map doesn't break. I don't know why the map is broken or not.

**Comment by mnumanuyar** [comment]
this also happens in docker

**Comment by 1f-small-Xue-study-today** [comment]
So I want to run PX4 in docker, and I need to install QGC in my docker environment, how to solve this ?

**Comment by lars-nagel** [comment]
I fixed the broken map issue by installing the latest onboard GPU drivers for my AMD CPU.
