### ISSUE TITLE
how to create an auto-pilot application to control from QGC

### ISSUE THREAD

**Issue by patatessever** [mavlink/qgroundcontrol#10363]
This is not a bug or report this just a question and I am unable to find right platform to ask thus if you can help i will really appriciate it.

Hello everybody! I want to create a script to act as an Auto-pilot. The idea is I have an auto-pilot application which is not ardupilot nor PX4. I will create a wrapper between my autopilot and the autopilot script that I wrote. I want to send data from QGC to this script and wrapper will convert it to a data type whch my auto-pilot will understand. I am able to send heartbeat from auto-pilot script to QGC by using pymavlink yet I am not sure how to send all the data QGC needs to see my script as a drone. Do you guys have any idea about it?

**Comment by zdanek** [comment]
Read a lot about mavlink. All is there. Even implementing own autopilot should be based on proper understanding and using mavlink. This repo (QGC) has nothing to do with it. It's a part of infrastructure. Without QGC you should be also able to communicate autopilot with your drone. Good luck as you chose very long and  bumpy road.
