### ISSUE TITLE
bad video performance (udp) on android

### ISSUE THREAD

**Issue by pasdVn** [mavlink/qgroundcontrol#10377]
## Expected Behavior
Smooth video playback on android platform

## Current Behavior
Artifacts appear - even on low Bitrates and with hardware decoder used.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. connect some android device runing qgc via usb-tethering to your linux host machine
2.enable udp h264 video stream in QGC
3. run e.g. `gst-launch-1.0 -v ximagesrc ! "video/x-raw,framerate=30/1" ! videoconvert ! x264enc tune=zerolatency bitrate=5000 speed-preset=superfast ! "video/x-h264,profile=baseline" ! rtph264pay config-interval=10 ! udpsink host=192.168.42.129 port=5600` on your host (maybe you need to change the destination adress - I think it is not static anymore on recent andoid versions)
4. watch the video in QGC while moving a GUI/window around on your desktop machine

## System Information
When posting bug reports, include the following information
- android 9 (lineageos) on Samsung galaxy tab pro (SM-T320)
- QGC Version: 4.2.3 32bit
- QGC build: stable
- Flight Controller: -
- Autopilot (with version): -

## Detailed Description
I could reproduce the issue with a simple test app (gstreamer android tutorial 3, https://gitlab.freedesktop.org/gstreamer/gstreamer/-/tree/main/subprojects/gst-docs/examples/tutorials/android/android-tutorial-3) that rebuilds the pipeline used in QGC ({{udpsrc port=5600 caps="application/x-rtp" ! rtpjitterbuffer ! rtph264depay ! decodebin ! autovideosink sync=false}}).
Due to the wired connection I had no packet loss (checked with wireshark), however the rtpjitterbuffer always complained about lost packages, when the arifacts appeared on the screen:

`08-12 22:35:00.446 12018 12044 I GStreamer+rtpjitterbuffer: 0:00:23.819611606 0x8d790e60 ../gst/rtpmanager/gstrtpjitterbuffer.c:2619:gst_rtp_jitter_buffer_handle_missing_packets:<rtpjitterbuffer0> Add Lost timer for #12519, pts 0:00:18.222526489, duration 0:00:00.000000000, offset +0:00:00.200000000
08-12 22:35:01.060 12018 12044 I GStreamer+rtpjitterbuffer: 0:00:24.434241293 0x8d790e60 ../gst/rtpmanager/gstrtpjitterbuffer.c:2619:gst_rtp_jitter_buffer_handle_missing_packets:<rtpjitterbuffer0> Add Lost timer for #12669, pts 0:00:18.822390848, duration 0:00:00.000000000, offset +0:00:00.200000000`

I could reproduce the behaviour on different devices (Galaxy S5, Galaxy S8, Huawei P8) - no matter if they where using the hardware decode (amcviddec) or the software decocder (avdec_h264). I could not reproduce this issue when displayed the stream on a  windows/linux machine.

After several hours of try-and-error I found out, that increasing the socket buffer size of the udp socket eliminates this problem (I used `buffer-size=512000`, the default socket buffer size was 163840 at the SM T320).

So i would recommend to (probably hardcode!?) an increased socket buffer size for android builds (maybe I will provide a PR, but the the setup of the build environment scared me a bit :-P).

## Log Files and Screenshots
- see above

**Comment by HTRamsey** [comment]
If you still have issues on the latest build with the newer gstreamer, we can look into this again.
