### ISSUE TITLE
PX4 WIFI

### ISSUE THREAD

**Issue by xindax2000** [mavlink/qgroundcontrol#10371]
How to connect the PX4 to the qgroundcontrol via WIFI?
I have two PC.

- The PX4 is connected to the PC 1 with mavsdk. (Linux)
- The qgroundcontrol runs on the PC 2.

I would like to see PX4 in qgroundcontrol  on PC 2.

**Comment by booo** [comment]
Maybe you have to change the system ID. Take a look a the documentation: https://docs.qgroundcontrol.com/master/en/SettingsView/MAVLink.html

I think this is a configuration issues and not an issue with QGC. Please provide more information and reopen the ticket if your problems persist.
