### ISSUE TITLE
Descriptions for parameters added in ArduCopter 4.2 are not showing in the daily build

### ISSUE THREAD

**Issue by bnsgeyer** [mavlink/qgroundcontrol#10407]
The Heli page was updated for new parameters in ArduCopter 4.2 firmware.  I downloaded the latest build and the page appears to populate properly but there are no descriptions for the parameters.  Based on what I can see in the source code, it appears that the parameter metadata file (APMParameterFactMetaData.Copter.4.2.xml) has not been added.  

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: Latest daily build 22-09-07 11:51:14
- QGC build:  daily, stable
- Flight Controller: SITL
- Autopilot (with version): Ardupilot Copter 4.2.3

**Comment by booo** [comment]
I think you added new meta data here:

https://github.com/mavlink/qgroundcontrol/commit/7a00804956f607d5ac62d6cd152386bb73dad8fe
