### ISSUE TITLE
Add more baud rate options when creating a custom Comm Link

### ISSUE THREAD

**Issue by stevesdawg** [mavlink/qgroundcontrol#10400]
Tell us a bit about the feature:
- What problem does it solve?
Create custom Comm Links with telemetry radio devices that support faster baudrates than the current maximum of 921600.
- What does it do?
Add 1200000 and 3000000 to the baud rate dropdowns. Or remove the dropdown completely and allow someone to type in the baudrate.
- Are there other systems that have this feature?
RFD900 radios support up to 3000000 baud.

![image](https://user-images.githubusercontent.com/5642476/188949205-7e1f51e0-1bbe-49a0-9ece-2d998ec0a071.png)

**Comment by booo** [comment]
You can try changing the list of available baud rates here:

https://github.com/mavlink/qgroundcontrol/blob/master/src/comm/SerialLink.cc#L412

**Comment by tpwrules** [comment]
I need a baud rate of 1000000. On my system 921600 falls at a bad divisor and doesn't work properly.
