### ISSUE TITLE
I get "Waiting for Video" warning on the my daily QGC Android version.

### ISSUE THREAD

**Issue by kekemsu** [mavlink/qgroundcontrol#10415]
QGC version on the Google Store works normally for streaming the video. Then, I want to change some appearance widgets so, I download the 4.2.0. version through github and I install gstreamer for andorid. When i try to reach video stream I get "Waiting for Video" screen and i checked the console 
VIDEORECEİVERLOG: Unable to find sink pad of video sink "rtsp://192.x.x.x:xxxxx/H264Video"
warning i got.

I can reach the stream on the normal QGC release version 4.2.3. with same options but unfortunately I can not see the stream on my QGC version. 

## System Information
- Operating System: Windows 10
- QGC Version: 4.2.0
- QGC build: QT Creater Android Clang
- Java 11
- SDK 25 (Android 7.1)
- NDK r20b
- QT Creater 5.15.2
- Gstreamer for android 1.18.5

If you give a advice to me. I'll appreciate you. Thanks for advance :)

**Comment by randev45** [comment]
I found the same issue with the daily build.

**Comment by kekemsu** [comment]
Is there any solution about this problem

**Comment by fredowski** [comment]
Maybe this is due to the rtsp timeout problem or due to decodebin3 or both. Could you try the build results from here:

https://github.com/mavlink/qgroundcontrol/pull/10409

and from here

https://github.com/fredowski/qgroundcontrol/pull/8

?

**Comment by kekemsu** [comment]
> Maybe this is due to the rtsp timeout problem or due to decodebin3 or both. Could you try the build results from here:
> 
> #10409
> 
> and from here
> 
> [fredowski#8](https://github.com/fredowski/qgroundcontrol/pull/8)
> 
> ?

Then, why don't i get same problem on the release version (4.2.3 from google play)? I'm not sure about the your comment related to my issue. I have another interface for camera display and I can see the image on the qgc and other interface but I'm getting "Waiting for Video" warning on my qgc daily build version.
I'm also always getting some warning while finish the build. 
Warning: Qml import could not be resolved in any of the import paths: Qt.xxxxx 
and 
Warning: Mapping new ns schemas.android.com/sdk/android/repo/addon2/02 to old ns schemas.android.com/sdk/android/repo/addon2/01
I think I can ignore these warnings.

**Comment by fredowski** [comment]
Are you 100% sure that this problem is not due to your build setup? May I suggest to try a current android build from github to see if this problem is there also? For example: https://github.com/mavlink/qgroundcontrol/actions/runs/3050249871

**Comment by kekemsu** [comment]
> Are you 100% sure that this problem is not due to your build setup? May I suggest to try a current android build from github to see if this problem is there also? For example: https://github.com/mavlink/qgroundcontrol/actions/runs/3050249871

I'm not sure about my build setup is correct when i check the build steps in the link. My build steps are around 2000 steps. I put the my configuration versions. What do you think about the versions. Is there any looks wrong ?

**Comment by fredowski** [comment]
Can you maybe just try the build APKs from github?

**Comment by kekemsu** [comment]
> 

I already built the version from github. I just changed some user interface items. I need no once again same thing. And also does not download with the gstreamer. I'll download the gstreamer again and will not remain any sense cause to I'm getting the video problem. Thanks your advice :)

**Comment by fredowski** [comment]
Maybe this is a misunderstanding. I am not proposing to download the github source again but to run the build products from the github continuous integration build server. If you scroll here 

https://github.com/mavlink/qgroundcontrol/actions/runs/3050249871

further down you will find the  QGroundControl64.apk ready for installing and testing on your device.

**Comment by kekemsu** [comment]
> 

I'll try thanks. What is the difference the apk and google play version ?

> Maybe this is a misunderstanding. I am not proposing to download the github source again but to run the build products from the github continuous integration build server. If you scroll here
> 
> https://github.com/mavlink/qgroundcontrol/actions/runs/3050249871
> 
> further down you will find the QGroundControl64.apk ready for installing and testing on your device.

**Comment by fredowski** [comment]
You mean this version

https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrolbeta ?

which was updated January 2021? As far as I know the play store does not allow to upload APKs anymore - only the new format AAB is supported since August 2021. But the build setup on github does not build that at the moment. Can you also try the RTSP fix version here: https://github.com/mavlink/qgroundcontrol/actions/runs/3030082262 ?
