### ISSUE TITLE
Unable to set up the vehicle of pixhawk 6c in windows laptop.

### ISSUE THREAD

**Issue by sid99github** [mavlink/qgroundcontrol#10410]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
As I connected my laptop to pixhawk 6c flight controller. Q ground control is unable to read the pixhawk 6c flight controller.

## Current Behavior
When I used the Qground control in my mac. It is able to read the pixhawk 6c flight controller. I was able to do firmware and all the calibrations.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.
2.
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: Windows 8
- QGC Version: [e.g. 4.2.3]
- QGC build: 
- Flight Controller:  Pixhawk 6c
- Autopilot (with version): 

## Detailed Description
As I connected my laptop to pixhawk 6c flight controller. Q ground control is unable to read the pixhawk 6c flight controller. When I used the Qground control in my mac. It is able to read the pixhawk 6c flight controller. I was able to do firmware and all the calibrations.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.
![pixhawlk 6c error](https://user-images.githubusercontent.com/78077967/189655793-170afbf6-af9a-4620-a4ec-152e87abcaa7.PNG)

**Comment by HTRamsey** [comment]
You are most likely missing some drivers for Windows.
