### ISSUE TITLE
Can't read half of the lines in "Log Download"

### ISSUE THREAD

**Issue by dlech** [mavlink/qgroundcontrol#10449]
Black text on dark gray background is almost impossible to read in the Log Downloads page.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/963645/194389659-f479312d-f083-4c79-8bfb-164df17f2bd1.png">

As a workaround, you can select a dark line to read it.

It would be better if the text was white.

## System Information
When posting bug reports, include the following information
- Operating System: macOS 12.6
- QGC Version: v4.2.0
- QGC build: stable
- Flight Controller: N/A
- Autopilot (with version): N/A

**Comment by booo** [comment]
I can't reproduce this on Linux with latest master. Here everything is white. No alternation of the color.

Can you check a build from the master branch?

Maybe we use implicitly use some strange defaults from Qt on macOS?

**Comment by dlech** [comment]
> Maybe we use implicitly use some strange defaults from Qt on macOS?

According to the docs, the default should have alternating (background) colors: https://doc.qt.io/qt-5/qml-qtquick-controls-tableview.html#alternatingRowColors-prop

I've made a PR to fix the issue.

**Comment by booo** [comment]
Nice. Thanks for your contribution!
