### ISSUE TITLE
In the Firmware part the download address of ardupilot for pixhawk 4 is wrong.

### ISSUE THREAD

**Issue by FishDoggy** [mavlink/qgroundcontrol#10453]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

## Detailed Description
the right download address is supposed to be https://firmware.ardupilot.org/Copter/stable/Pixhawk4/arducopter.apj
however the app go to the https://firmware.ardupilot.org/Copter/stable/px4/arducopter.apj
which result to the unsuccess download.

**Comment by booo** [comment]
What version of QGC do you use. Please give us some context to reproduce the problem.

**Comment by FishDoggy** [comment]
Stable Release v3.5.6

**Comment by booo** [comment]
Could you please try newer versions of QGC from here: https://github.com/mavlink/qgroundcontrol/releases/tag/v4.2.4
