### ISSUE TITLE
Won't reopen a UDP (and maybe serial) connection on startup

### ISSUE THREAD

**Issue by crashmatt** [mavlink/qgroundcontrol#1045]
After setting a UDP localhost:14550 connection QGC won't automatically open it on startup.  I get The error message "Error connecting: Permission denied".  I can open the UDP port manually after I clear the error message.  

When this happens I get two rfcomm0 ports setup instead of a udp:14550 port.  rfcomm0 is defined in etc/bluetooth/rfcomm.conf on a device that is not running.  It is probably not a valid device.

Running on linux mint 17.
I have set the option in settings to reopen the ports previously open.
I get the same problem for udp:14551
If I don't clear the rfcomm0 comm settings then I get the same problem.

It looks like QGC is recording a udp connection as rfcomm connection.  I don't find any entry for the connection in QGroundControl.ini

The reopen setting is set in the settings menu.  I have not made sure that this setting is set after qgc restart.

The error message comes from SerialLink.cc here:
https://github.com/mavlink/qgroundcontrol/blob/c1e6f5735ddbd3f381e1071d55b6acc04a7e1c6b/src/comm/SerialLink.cc#L213

Don reports not being able to re-open any kind of connection.
I have yet to try re-opening a serial port

**Comment by LorenzMeier** [comment]
Reopen removed since its confusing from user perspective.
