### ISSUE TITLE
the compiler can't find the dylib in OSX while it is linking after I added the gstreamer into the project 

### ISSUE THREAD

**Issue by kevinuav** [mavlink/qgroundcontrol#10463]
## Current Behavior
I use OSX(11.6) Qt(5.15.2) and Xcode(13.2.1) to compile my QGC-daily.  It can't find the dylib while it is linking after that I added the gstreamer into the path just as the instruction said. And there is no a file named libgsttag-1.0.0.dylib even after that I have  installed the 2 pkgs :[gstreamer-1.0-devel-1.18.6-x86_64.pkg
                                                                gstreamer-1.0-1.18.6-x86_64.pkg)
<img width="1032" alt="截屏2022-10-25 下午11 24 42" src="https://user-images.githubusercontent.com/8048038/197817188-1743acd1-86af-45f4-84a7-818b8205d7bb.png">

this is the error:
```
linking QGroundControl.app/Contents/MacOS/QGroundControl
ld: file not found: @rpath/lib/libgsttag-1.0.0.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [QGroundControl.app/Contents/MacOS/QGroundControl] Error 1
```

**Comment by kevinuav** [comment]
The problem solved. I downloaded the 2PKGs again via VPN(the IP address is not in China mainland). Then it works. Seems like that the gstream's PKG in china is different from the rest of the world since Chinese government controls everything comes from the liberty world.

**Comment by palahmd** [comment]
Hi, could you solve this problem? I'm having the same problem.

**Comment by atesahmet0** [comment]
I'm currently having the same problem.
