### ISSUE TITLE
[MSVC] QGroundcontrol failed to build with msvc due to error C2666 on Windows with /c++latest compile option

### ISSUE THREAD

**Issue by Zhaojun-Liu** [mavlink/qgroundcontrol#10462]
<!The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----
-->

## Expected Behavior
Build with msvc successfully.

## Current Behavior
`F:\gitP\mavlink\qgroundcontrol\libs\libevents\libevents\libs\cpp\parse\parser.cpp(634): error C2666: 'nlohmann::detail::iter_impl<const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>>::operator !=': overloaded functions have similar conversions`

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. git clone https://github.com/mavlink/qgroundcontrol F:\gitP\mavlink\qgroundcontrol
2. git -C "F:\gitP\mavlink\qgroundcontrol" fetch --recurse-submodules=no --force
3. git -C "F:\gitP\mavlink\qgroundcontrol" reset --hard 9c77d15 (currently the latest commit)
4. git -C "F:\gitP\mavlink\qgroundcontrol" submodule sync
5. git -C "F:\gitP\mavlink\qgroundcontrol" submodule update --init --recursive
6. set _CL_= /std:c++latest
7. mkdir F:\gitP\mavlink\qgroundcontrol\build_amd64 and cd F:\gitP\mavlink\qgroundcontrol\build_amd64
8. set related Path (in my test environment like below):
   8.1 set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;F:\tools\jom_1_1_2;%PATH%
9. qmake -r ../qgroundcontrol.pro
10.  set _CL_=%_CL_% /wd5055 /D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
11. jom /U

## System Information
When posting bug reports, include the following information
- Operating System: Windows Server 2022 Datacenter 21H2
- VS version: VS2019 16.11.20

## Detailed Description
Recently, we updated the commit of Qgroundcontrol for MSVC RWC testing, it built failed due to error C2666 with compile option /c++latest like below:
`F:\gitP\mavlink\qgroundcontrol\libs\libevents\libevents\libs\cpp\parse\parser.cpp(634): error C2666: 'nlohmann::detail::iter_impl<const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>>::operator !=': overloaded functions have similar conversions`

## Log Files and Screenshots
detailed log files:
[build (3).log](https://github.com/mavlink/qgroundcontrol/files/9858913/build.3.log)

**Comment by Zhaojun-Liu** [comment]
Any updates of this issue? Thanks.

**Comment by HTRamsey** [comment]
You can compile without treating warnings as errors
