### ISSUE TITLE
QGC Custom Build Doesn't Work On Master Branch - When connecting with ArduSub

### ISSUE THREAD

**Issue by Nimrod-Ost** [mavlink/qgroundcontrol#10484]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

## Expected Behavior
Successful run of **QGC Custom Build** and connection to ArduSub SITL.

## Current Behavior
QGC runs but when connecting to the SITL- it crashes. If I manually connect to the SITL it crashes as well.
Maybe the custom build needs an update.

## Steps to Reproduce:
1. Run SITL Tools/autotest/sim_vehicle.py -v ArduSub
2. Build the custom QGC on master branch- as in the documentation
3. Run QGC - it will crash as soon as you connect to the ArduSub

## System Information
- Ubuntu 22.04
- QGC build: current master branch
- Ardupilot ArduSub-stable branch (V4.1.0)

## Log Files and Screenshots
Logs of command ./qgroundcontrol-start.sh --logging:full

PX4ParameterMetaDataLog: No metaData for  "RC_TH_USER" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SDLOG_EXT" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SDLOG_GPSTIME" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SDLOG_PRIO_BOOST" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SDLOG_RATE" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SYS_COMPANION" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SYS_LOGGER" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SYS_PARAM_VER" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "SYS_RESTART_TYPE" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "VT_NAV_FORCE_VT" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "VT_WV_LND_EN" using generic metadata
PX4ParameterMetaDataLog: No metaData for  "VT_WV_LTR_EN" using generic metadata
AirspaceManagementLog: Instatiating AirspaceVehicleManager
MissionControllerLog: start flyView true
MissionControllerLog: _addMissionSettings
GeoFenceControllerLog: start flyView true
GeoFenceControllerLog: start flyView true
PlanMasterControllerLog: _activeVehicleChanged Vehicle(0x564438d82460)
PlanMasterControllerLog: _activeVehicleChanged: Fly View - New active vehicle, loading new plan from manager vehicle
MissionControllerLog: showPlanFromManagerVehicle _flyView true
MissionControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
MissionControllerLog: _newMissionItemsAvailableFromVehicle flyView:count true 0
MissionControllerLog: loading from vehicle: count 0
MissionControllerLog: _addMissionSettings
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
MissionControllerLog: MissionController::_scanForAdditionalSettings count:scanIndex 1 0
GeoFenceControllerLog: showPlanFromManagerVehicle _flyView true
GeoFenceControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
RallyPointControllerLog: showPlanFromManagerVehicle _flyView true
RallyPointControllerLog: showPlanFromManagerVehicle: sync complete
MultiVehicleManagerLog: setActiveVehicle Vehicle(0x564438d82460)
VehicleLog: _mavlinkMessageReceived Link already running Mavlink v2. Setting _maxProtoVersion 200
MissionManagerLog: _updateMissionIndex currentIndex: 0
MissionManagerLog: _updateMissionIndex caching _lastCurrentIndex for possible update: 0
VehicleLog: "_handleCommandAck command(MAV_CMD_REQUEST_MESSAGE) result(MAV_RESULT_ACCEPTED)"
VehicleLog: _waitForMavlinkMessageMessageReceived message received 148
VehicleLog: _waitForMavlinkMessageClear
InitialConnectStateMachineLog: AUTOPILOT_VERSION received
FirmwarePluginLog: Downloading ""
downloadFile empty
VehicleLog: "Vehicle supports Mavlink 2.0"
VehicleLog: "Vehicle supports MISSION_ITEM_INT"
VehicleLog: "Vehicle does not support MISSION_COMMAND_INT"
VehicleLog: "Vehicle supports GeoFence"
VehicleLog: "Vehicle does not support RallyPoints"
VehicleLog: "Vehicle does not support Terrain"
InitialConnectStateMachineLog: Skipping REQUEST_MESSAGE:PROTOCOL_VERSION request due to Ardupilot firmware
InitialConnectStateMachineLog: _stateRequestCompInfo
ComponentInformationManagerLog: Requesting component metadata "COMP_METADATA_TYPE_GENERAL"
VehicleLog: _waitForMavlinkMessage msg:timeout 397 1000
VehicleLog: _sendMavCommandFromList command:tryCount "MAV_CMD_REQUEST_MESSAGE" 0
VehicleLog: "_handleCommandAck command(MAV_CMD_GET_HOME_POSITION) result(MAV_RESULT_FAILED)"
VehicleLog: _handleCommandAck Ack not in list "MAV_CMD_GET_HOME_POSITION"
MissionControllerLog: _recalcFlightPathSegments homePositionValid false
MultiVehicleManagerLog: _setActiveVehiclePhase2 _vehicleBeingSetActive Vehicle(0x564438d82460)
qml: _activeVehicle(1) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleWasFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode() _missionItemCount(0) roiSupported(0) orbitSupported(0) _missionActive(0) _hideROI(0) _hideOrbit(0)
qml: _activeVehicle(1) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleWasFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode(Custom:0x13) _missionItemCount(0) roiSupported(0) orbitSupported(0) _missionActive(0) _hideROI(0) _hideOrbit(0)
VideoManagerLog: No sense to restart video streaming, skipped 0
VideoManagerLog: Restart video streaming 1
PlanMasterControllerLog: _activeVehicleChanged Vehicle(0x564438d82460)
PlanMasterControllerLog: _activeVehicleChanged: Plan View - No previous plan, new active vehicle, loading from new manager vehicle
MissionControllerLog: showPlanFromManagerVehicle _flyView false
MissionControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
MissionControllerLog: _newMissionItemsAvailableFromVehicle flyView:count false 0
MissionControllerLog: loading from vehicle: count 0
MissionControllerLog: _addMissionSettings
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
MissionControllerLog: MissionController::_scanForAdditionalSettings count:scanIndex 1 0
MissionSettingsItemLog: MissionSettingsItem::scanForMissionSettings count:scanIndex 1 1
CameraSectionLog: CameraSection::scanForCameraSection visualItems->count():scanIndex; 1 1
setCurrentPlanViewSeqNum
setCurrentPlanViewSeqNum
GeoFenceControllerLog: showPlanFromManagerVehicle _flyView false
GeoFenceControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
RallyPointControllerLog: showPlanFromManagerVehicle _flyView false
RallyPointControllerLog: showPlanFromManagerVehicle: sync complete
PlanMasterControllerLog: _activeVehicleChanged Vehicle(0x564438d82460)
PlanMasterControllerLog: _activeVehicleChanged: Fly View - New active vehicle, loading new plan from manager vehicle
MissionControllerLog: showPlanFromManagerVehicle _flyView true
MissionControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
MissionControllerLog: _newMissionItemsAvailableFromVehicle flyView:count true 0
MissionControllerLog: loading from vehicle: count 0
MissionControllerLog: _addMissionSettings
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
LandingComplexItemLog: VTOLLandingComplexItem::scanForItem count 1
MissionControllerLog: MissionController::_scanForAdditionalSettings count:scanIndex 1 0
GeoFenceControllerLog: showPlanFromManagerVehicle _flyView true
GeoFenceControllerLog: showPlanFromManagerVehicle: sync complete simulate signal
RallyPointControllerLog: showPlanFromManagerVehicle _flyView true
RallyPointControllerLog: showPlanFromManagerVehicle: sync complete
MissionControllerLog: _recalcMissionFlightStatus
VehicleLog: "_handleCommandAck command(MAV_CMD_REQUEST_MESSAGE) result(MAV_RESULT_FAILED)"
VehicleLog: _waitForMavlinkMessageClear
ComponentInformationManagerLog: Requesting component information "COMP_METADATA_TYPE_GENERAL"
VehicleLog: _waitForMavlinkMessage msg:timeout 395 1000
VehicleLog: _sendMavCommandFromList command:tryCount "MAV_CMD_REQUEST_MESSAGE" 0
MissionControllerLog: _recalcFlightPathSegments homePositionValid false
MissionControllerLog: _recalcFlightPathSegments homePositionValid false
TerrainProfileLog: missionController min/max nan nan
TerrainProfileLog: "updatePaintNode counter:5 cFlightProfileSegments:0 cTerrainProfilePoints:0 cMissingTerrainSegments:0 cTerrainCollisionSegments:0 _minAMSLAlt:nan _maxAMSLAlt:nan maxTerrainHeight:nan"
MissionControllerLog: _recalcMissionFlightStatus
VehicleLog: "_handleCommandAck command(MAV_CMD_REQUEST_MESSAGE) result(MAV_RESULT_FAILED)"
VehicleLog: _waitForMavlinkMessageClear
ComponentInformationManagerLog: "MAV_CMD_REQUEST_MESSAGE COMPONENT_INFORMATION COMP_METADATA_TYPE_GENERAL error(MAV_RESULT_FAILED)"
ComponentInformationManagerLog: Skipping download. Component information not available for "00000000_00_0"
ComponentInformationManagerLog: RequestMetaDataTypeStateMachine::_stateRequestMetaDataJsonFallback: trying fallback download
ComponentInformationManagerLog: Skipping download. Component information not available for "00000000_00_0"
ComponentInformationManagerLog: Skipping download. Component information not available for ""
ComponentInformationManagerLog: _stateRequestCompInfoParam skipping, not supported
ComponentInformationManagerLog: _stateRequestCompInfoEvents skipping, not supported
ComponentInformationManagerLog: _stateRequestCompInfoActuators skipping, not supported
InitialConnectStateMachineLog: _stateRequestParameters
FTPManagerLog: download fromURI: "@PARAM/param.pck" to: "/tmp"
FTPManagerLog: _downloadState.fullPathOnVehicle:_downloadState.fileName "@PARAM/param.pck" "param.pck"
FTPManagerLog: _sendRequestExpectAck opcode: "Open File RO" seqNumber: 1
ParameterManagerLog: "V:1" Request to refresh all parameters for component ID: "MAV_COMP_ID_ALL"
MissionControllerLog: _recalcMissionFlightStatus
TerrainProfileLog: missionController min/max nan nan
TerrainProfileLog: "updatePaintNode counter:6 cFlightProfileSegments:0 cTerrainProfilePoints:0 cMissingTerrainSegments:0 cTerrainCollisionSegments:0 _minAMSLAlt:nan _maxAMSLAlt:nan maxTerrainHeight:nan"
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Open File RO" 2
FTPManagerLog: _openFileROAckOrNak: Ack  - sessionId:openFileLength 0 1048576
FTPManagerLog: _burstReadFileWorker: starting burst at offset:firstRequest:retryCount 0 true 0
FTPManagerLog: _sendRequestExpectAck opcode: "Burst Read File" seqNumber: 3
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 4
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(0) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.000227928
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 5
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(239) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.000455856
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 6
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(478) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.000683784
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 7
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(717) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.000911713
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 8
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(956) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00113964
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 9
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(1195) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00136757
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 10
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(1434) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0015955
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 11
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(1673) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00182343
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 12
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(1912) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00205135
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 13
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(2151) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00227928
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 14
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(2390) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00250721
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 15
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(2629) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00273514
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 16
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(2868) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00296307
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 17
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(3107) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00319099
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 18
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(3346) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00341892
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 19
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(3585) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00364685
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 20
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(3824) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00387478
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 21
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(4063) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00410271
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 22
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(4302) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00433064
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 23
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(4541) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00455856
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 24
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(4780) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00478649
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 25
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(5019) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00501442
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 26
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(5258) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00524235
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 27
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(5497) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00547028
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 28
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(5736) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0056982
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 29
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(5975) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00592613
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 30
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(6214) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00615406
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 31
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(6453) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00638199
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 32
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(6692) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00660992
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 33
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(6931) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00683784
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 34
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(7170) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00706577
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 35
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(7409) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0072937
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 36
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(7648) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00752163
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 37
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(7887) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00774956
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 38
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(8126) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00797749
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 39
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(8365) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00820541
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 40
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(8604) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00843334
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 41
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(8843) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00866127
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 42
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(9082) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0088892
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 43
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(9321) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00911713
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 44
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(9560) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00934505
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 45
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(9799) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00957298
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 46
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(10038) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.00980091
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 47
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(10277) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0100288
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 48
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(10516) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0102568
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 49
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(10755) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0104847
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 50
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(10994) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0107126
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 51
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(11233) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0109406
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 52
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(11472) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0111685
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 53
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(11711) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0113964
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 54
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(11950) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0116243
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 55
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(12189) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0118523
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 56
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(12428) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0120802
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 57
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(12667) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0123081
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 58
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(12906) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.012536
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 59
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(13145) size(239) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.012764
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Burst Read File" 60
FTPManagerLog: "_burstReadFileAckOrNak: Ack offset(13384) size(88) burstComplete(0)"
ParameterManagerVerbose1Log: ParameterManager::_ftpDownloadProgress:  0.0128479
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Nak" "Burst Read File" 61
FTPManagerLog: _burstReadFileAckOrNak EOF
FTPManagerLog: _sendRequestExpectAck opcode: "Reset Sessions" seqNumber: 62
FTPManagerLog: _mavlinkMessageReceived: hdr.opcode:hdr.req_opcode:seqNumber "Ack" "Reset Sessions" 63
FTPManagerLog: _resetSessionsAckOrNak: Ack
FTPManagerLog: "_downloadComplete: errorMsg()"
ParameterManagerLog: ParameterManager::_ftpDownloadComplete : Parameter file received: "/tmp/param.pck"
ParameterManagerLog: _parseParamFile:  "/tmp/param.pck"
ParameterManagerVerbose2Log: _parseParamFile: magic: 0x 671b
ParameterManagerVerbose2Log: _parseParamFile: num_params: 1253  total_params: 1253
ParameterManagerVerbose2Log: _parseParamFile: parameter "SURFACE_DEPTH" name_len 13 common_len 0 ptype 4 flags 0
ParameterManagerVerbose2Log: paramValue QVariant(float, -10)
ParameterManagerVerbose1Log: "V:1 C:1" Adding new fact "SURFACE_DEPTH"
Request for unknown firmware plugin factory 3
ASSERT failure in QList<T>::operator[]: "index out of range", file /home/u-dev-404/Qt/5.15.2/gcc_64/include/QtCore/qlist.h, line 579
Aborted (core dumped)

Thank You, Appreciate every help.

**Comment by highfreq** [comment]
Isn't that happening because custom build doesn't have ardupilot support but only px4?
