### ISSUE TITLE
Why doesn't iOS support serial port connection?

### ISSUE THREAD

**Issue by fanfans1** [mavlink/qgroundcontrol#10480]
What does iOS serial port connection need to support?

**Comment by booo** [comment]
Could you please add a bit more context to your request or bug report? Thanks a lot.

**Comment by fanfans1** [comment]
I use qgc code to run it on Android, which has the method of serial port connection, but when running it on iOS device, iOS device does not choose the way of serial port connection

**Comment by booo** [comment]
I think QSerialPort is [missing iOS support](https://wiki.qt.io/Qt_Serial_Port#QSerialPortl) and therefore serial communication does not work in QGC.

We disable serial stuff on iOS builds here:

https://github.com/mavlink/qgroundcontrol/blob/master/QGCCommon.pri#L120

I think this is a want-fix until someone implements QtSerialPort for iOS.

**Comment by booo** [comment]
I close this because I think we don't have the capacity to fix the underlying problem.
