### ISSUE TITLE
Project ERROR: Unsuported Linux toolchain, only GCC 32- or 64-bit is supported

### ISSUE THREAD

**Issue by 3026187875** [mavlink/qgroundcontrol#10498]
## Expected Behavior
Please tell us what should happen as detailed as possible.
Project MESSAGE: Qt version 5.15.2
Project ERROR: Unsuported Linux toolchain, only GCC 32- or 64-bit is supported
## Current Behavior
Please describe what happens instead of the expected behavior.
errror 
Project ERROR: Unsuported Linux toolchain, only GCC 32- or 64-bit is supportedv
## Steps to Reproduce:
after i run qmake ../
## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14] # ubuntu20.04(wsl2)
- QGC Version: [e.g. 3.4.4] # latest
- QGC build: [e.g., daily, stable, self-built from source, etc...] github code
could someone figure this issue?
thanks

**Comment by lvwenqi7** [comment]
Hello, I want to ask you have this problem solved? I had the same problem when I cross-compiled qgc in ubuntu20.04 and got "Project ERROR: Unsuported Linux toolchain, only GCC 32- or 64-bit is supported" in the qmake step.
