### ISSUE TITLE
undefined reference to 'AirspaceManager::connectStatusChanged()' in MissionManager/PlanMasterController.cc

### ISSUE THREAD

**Issue by weirdgyn** [mavlink/qgroundcontrol#10500]
I'm trying to compile qgroundcontrol from sources on linux ubuntu.
I followed qgroundcontrol user manual instruction to build from sources.

## Expected Behavior

Compilation success.

## Current Behavior

Build failed:

```
04:17:11: Starting: "/usr/bin/make" -j4
linking staging/QGroundControl
/qgroundcontrol/src/MissionManager/PlanMasterController.cc:104: error: undefined reference to 'AirspaceManager::connectStatusChanged()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2411: staging/QGroundControl] Error 1
04:17:34: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Desktop Qt 5.15.2 GCC 64bit)
When executing step "Make"
```

## System Information
- Operating System: Ubuntu 20.04 LTS
- QGC Version: 5.15.2

**Comment by weirdgyn** [comment]
Looks like has something to do with AIRMAP but I currently disabled it (as suggested in the online user manual).

**Comment by HTRamsey** [comment]
Airmap is removed now
