### ISSUE TITLE
Read PWM

### ISSUE THREAD

**Issue by highfreq** [mavlink/qgroundcontrol#10511]
I need to read a pwm value of a certain channel, how do i acces it?

If for example i want to know flight mode it is in:

QGroundControl.multiVehicleManager.activeVehicle.flightMode

Is there something similar to access for example channel 12 current pwm?

Maybe my question is stupid and is it harder than that, if only someone could put me on the right path thn i can study :)

thanks in advance.

**Comment by booo** [comment]
I guess you want to listen for rcChannelsChanged "events":

https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.h#L941

Maybe take a look at the Radio calibration GUI to get a better understanding on how to use the events.

**Comment by highfreq** [comment]
Is RadioComponent.qml the radio calibration gui you are referring to?

**Comment by booo** [comment]
`git grep Vehicle::rcChannelsChanged` is your friend.

**Comment by highfreq** [comment]
I took a look at the method, please a little more help, i am an old guy fighting to learn :)

If i want for example to show current pwm value of channel 3 on a label what would i have to write on label text

QGroundControl.multiVehicleManager.activeVehicle.rcChannelsChanged()

thanks in advance.

**Comment by highfreq** [comment]
Ahahahah, thanks.

**Comment by highfreq** [comment]
Why did you close it, maybe someone else will have time to help me out

**Comment by booo** [comment]
Because you got a pointer in the right direction from me and the developer team does not have time to answer questions and help in the development of proprietary code. If you have plans to contribute to QGC please publish your code and open a PR. We are more than happy to review contributions to QGC.

**Comment by highfreq** [comment]
Not only devs hang around here, maybe someone else would peek in and help me out. Anyway thank you.
