### ISSUE TITLE
Launching AppImage requires 'Fuse' package

### ISSUE THREAD

**Issue by junwoo091400** [mavlink/qgroundcontrol#10531]
## Description
When launching QGC's App Image downloaded from daily release on a fresh Ubuntu 22.04 OS, it doesn't run due due to following error:

```bash
junwoo@JW-XPS:~/Downloads$ ./QGroundControl_daily_230104.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
```

## Suggestion
This is not necessarily QGC's problem, but it could be nice to have a link to https://github.com/AppImage/AppImageKit/wiki/FUSE on the QGC's Documentation to inform users of this case.

For my case, it was solved via following the installation steps in the link above: `sudo apt install libfuse2`

**Comment by booo** [comment]
Do you have the time to contribute that to the documentation?
