### ISSUE TITLE
Qgroundcontrol failed to build with "error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function #__std_init_once_link_alternate_names_and_abort$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [mavlink/qgroundcontrol#10545]
Qgroundcontrol failed to build with "error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function #__std_init_once_link_alternate_names_and_abort$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Repro steps:**

1. Open a vs2019 x64 command prompt.
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/mavlink/qgroundcontrol F:\groundcontrol 
4. cd F:\groundcontrol 
5. git submodule update --init --recursive
6. mkdir build_arm64ecc && cd build_arm64ecc
7. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
8. cmake -G "Visual Studio 16 2019" -A  ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF ..
9. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release QGroundControl.sln /t:Rebuild

**Error info:**
95>compression.lib(QGCLZMA.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function #__std_init_once_link_alternate_names_and_abort$exit_thunk (EC Symbol) [F:\qgroundcontrol\build_arm64ecc\QGroundControl.vcxproj]
	Line 2915:     95>F:\qgroundcontrol\build_arm64ecc\Release\QGroundControl.exe : fatal error LNK1120: 1 unresolved externals [F:\qgroundcontrol\build_arm64ecc\QGroundControl.vcxproj]

**Error log:**
[Qgroundcontrol_msbuild.log](https://github.com/mavlink/qgroundcontrol/files/10432846/Qgroundcontrol_msbuild.log)

**Comment by ukb1** [comment]
https://github.com/mavlink/qgroundcontrol/issues/10530#issue-1517064582
