### ISSUE TITLE
GstVideoReceiver does not handle NV21/NV12/YUV420 RTSP Streams Corretly

### ISSUE THREAD

**Issue by mrawding** [mavlink/qgroundcontrol#10559]
Hi all, Seeking help/guidance to solve this issue on my own and submit a PR since I know the QGC developers are not Gstreamer developers. Please read below.

The Gstreamer pipeline is not handling nv21 streams from rtsp servers correctly.

The displayed image on the qtsink has the width/height flipped and cuts out the color.

The image should look like this:

 Running rtsph264 or rtsp265 server that encodes and outputs frames in YUV420 OR NV21 and viewing the stream with:

```ffplay rtsp://<ip_address>:8000/live```

yields the image below (verifies server is functional)

![Screenshot from 2023-02-03 15-01-26](https://user-images.githubusercontent.com/25692500/216700009-7ce82200-9dde-4005-8f2d-eb7bd034ddfe.png)

QGC shows this when displaying the stream

![Screenshot from 2023-02-03 15-00-48](https://user-images.githubusercontent.com/25692500/216700828-b076dcc7-30b8-4539-ad7b-2c65a65a222f.png)

I've tried adding a ```videoconvert``` gstElement in between ```_decoder``` and ```_videoSink``` in ```GstVideoReceiver.cc```

at function ```GstVideoReceiver::_addVideoSink()```

It was still functional, but did not produce the desired image. I tried adding an RGB capsfilter too after videoconvert, but that shutdown the pipeline. 

I have a decent knowledge in gstreamer and am happy to find a solution and create a PR. I just ask that I may be pointed in the right direction!

 Clearly all of the information is there since it is rescaling and transforming the image with height->width and width->height.

Since it is NV21 the stream's color is at the end of the buffer and is being dropped. 

I can confirm that this is a problem on LINUX, but iOS displays correctly at the moment.

**Comment by booo** [comment]
A few improvements to the GStreamer code were proposed here:

https://github.com/mavlink/qgroundcontrol/pull/10420

Maybe that helps somehow.

**Comment by mrawding811** [comment]
This issue is resolved by upgrading on Linux up upgrading gst-base-plugins to version release 1.22.10.

This was never an issue with QGroundcontrol, but instead with ```glcolorconverter``` plugin.  Can easily be resolved by taking the following steps:

```
sudo add-apt-repository ppa:savoury1/multimedia
sudo apt-get update
sudo apt-get dist-upgrade
```

**Comment by booo** [comment]
Thanks for the feedback!
