### ISSUE TITLE
Some cameras have rtsp error

### ISSUE THREAD

**Issue by DreamSky2023** [mavlink/qgroundcontrol#10553]
1.After the rtsp address is entered, the figure is not displayed.

I tried to pull the code to modify, get a solution.

I hope the team can be integrated into the project. The following is the code I 

[rtsp.zip](https://github.com/mavlink/qgroundcontrol/files/10555105/rtsp.zip)

**Comment by booo** [comment]
Please create a pull request with your changes. Thanks a lot.
