### ISSUE TITLE
Does QGC support other special referance systems for maps?

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#10570]
If a WMTS server delivers ESPG:25833 tiles  - should QGC be able to use those, or is EPSG:4326 mandatory?
- I see no place to specify this.

**Comment by booo** [comment]
I think you have to provide QGC with the right tile format.

**Comment by AndKe** [comment]
can it be that if those two functions did calculate for ESPG:25833  - it would work?   (adding an alternate calculation for given map)
https://github.com/mavlink/qgroundcontrol/blob/master/src/QtLocationPlugin/MapProvider.cpp#L80  https://github.com/mavlink/qgroundcontrol/blob/master/src/QtLocationPlugin/MapProvider.cpp#L85

**Comment by booo** [comment]
Sorry, I'm not familiar with this part of the codebase. Give it a try and let us know.

I'm not sure how the conversion from screen pixels to coordinates works and maybe you need to do some transformation there too?

**Comment by AndKe** [comment]
@booo I think that's too deep water for me, as you say - the displaying-part may get wonky too.
