### ISSUE TITLE
UDP/TCP Conection issue.

### ISSUE THREAD

**Issue by SebastianViollaz** [mavlink/qgroundcontrol#10573]
----
My So:

- Ubuntu 22.04
- The last one on QGround Repository (4.2.0)

Issue:

- I want to make an API that get data from QGC , battery status, gps, etc. I what QGC to send data via port to that API.
- I made a simple code in c++ that listen a port  and print in console the info that is in the buffer. Let say that this program is mi server and QGC mY client.
-In QGC i made this connection:
![image](https://user-images.githubusercontent.com/85691148/218757052-37fa1608-f78a-4279-bede-5cbb00ebb94e.png)
When i start the server it conect to the QGC port  that is in the picture. But in the server side the data is not showing.
-The server work properly ( i tried "telnet 127.0.0.1 port" and it works). 

 I read something about MAVSDK and MavLink Router, bu not sure if that whill help. I understand that this two software are from connecting Ground Stations to an UAV. I made my server without QT Frame work. Is that a problem? 

Server Code: 

#include <iostream>
#include <string>
#include <cstring>
#include <unistd.h>

#include <sys/socket.h>

#include <netinet/in.h>
#include <arpa/inet.h>

int main() {

    int PORT = 8080;

    int Server_socket,Client_socket;

    struct sockaddr_in Server_addr, Client_adrr;

    socklen_t Client_socket_len;

    //Creacion de el soket del servidor

    Server_socket = socket(AF_INET,SOCK_STREAM,0);

    if (Server_socket == -1){
        std :: cerr << "Error al crear el socket del servidor\n";
        return -1;
    }

    //Definir IP y puerto del servidor

    memset(&Server_addr,0,sizeof(Server_addr));
    memset(&Client_adrr,0,sizeof(Client_adrr));

    Server_addr.sin_family = AF_INET;
    Server_addr.sin_addr.s_addr = INADDR_ANY;
    Server_addr.sin_port = htons(PORT);
    
    //Conectar el socket del server a la direccion

    if (bind(Server_socket, (struct sockaddr *) &Server_addr, sizeof(Server_addr)) < 0) {
        std::cerr << "Error conectando socket\n";
        return -1;
    }

    /* SOlO CONEXIONES TCP*/
    if(listen(Server_socket,1)){
        std::cerr << "Error al preparar para recivir conexiones ";
    }

    Client_socket_len = sizeof(Client_socket);

    Client_socket = accept(Server_socket,(struct  sockaddr *) &Server_addr,&Client_socket_len);
    if (Client_socket == -1){
        std :: cout << "Error al aceptar conexion del cliente";
    }
    std :: cout << "Conexion recibida desde : " << inet_ntoa(Client_adrr.sin_addr)<< ":" << ntohs(Client_adrr.sin_port)<< "\n";
    
    
    char Buffer[100000];
    
    while (true)
    { 
        //memset(&Buffer,0,sizeof(Buffer));

        // TCP//
        int BytesRecividos = read(Client_socket,Buffer,sizeof(Buffer)); 

        std :: cout << Buffer; 

    }

 
    close(Client_socket);

    return 1;
}

I am missing something? How Could i fix this problem?

**Comment by booo** [comment]
Please use tcpdump or wireshark to check if your configuration actually tries to establish a connection to the server. Maybe try manual connection first.

**Comment by SebastianViollaz** [comment]
I tried manually connect to the server whit the telnet line command in ubuntu. 
Like this: 
![image](https://user-images.githubusercontent.com/85691148/219040175-92f29513-81dd-4fa0-8442-06b922c92b62.png)
I send data from the terminal, and the server prints it, when i connect to QGC the connection is recived. (I know because a message shows up when the connection is recived), but the data that QGC send doesn't show. 

If i establish the connection for like 4-5 minutes some data shows, then stops printing.:
![image](https://user-images.githubusercontent.com/85691148/219043859-2f4a5c5f-2a42-4067-a923-a252eb7d2107.png)
this is the showed data in the VSC terminal.

This isnt't the way that supposed to work, it sholud be printing data constantly.

NOTE: The data showed prints like unknown charaters, i read the source code and i thinks that is because it send data of type ,"QByteArray". This is the source code:

![image](https://user-images.githubusercontent.com/85691148/219046004-f5e47640-8310-4e6a-a506-3a4fd7df0e5f.png)

**Comment by booo** [comment]
Please follow my suggestion. Wireshark has even a mavlink parser to check the packets.

I don't think this is a problem related to QGC. It's more a problem of your server.

You can use netcat to create a server too. Maybe you should try that as well.

**Comment by DonLakeFlyer** [comment]
You are doing the wrong thing. A Comm Link is for communication to/from a vehicle. It is not to forward mavlink. To forward mavlink go to MAVLink page and turn on Enabled MAVLink forwarding and set your host.
