### ISSUE TITLE
ESP32 Unable to connect to QGC

### ISSUE THREAD

**Issue by DEADLYBBS** [mavlink/qgroundcontrol#10582]
## Expected Behavior
Connect PC to ESP32 running DroneBridge Firmware
https://learn.adafruit.com/adafruit-airlift-breakout
Above is the board I am using. What would be the Tx and Rx pin that needs to be set?

Is there any possibility that I can use the ESP32 as a station point and have it connect to a router instead of directly to my PC?

## Current Behavior
I am able to connect to dronebridge through my computer and alter it's parameters.

## Steps to Reproduce:
I followed the instructions to flash the above chip by erasing the firmware and then booting it.

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: Daily master:5c3099e21 2022-11-09 16:44:34 -0300
- QGC build: Daily
- Flight Controller: Holybro Kakute H7 V1.2 (This version was not working with the stable release, posted about it somewhere)
- Autopilot (with version): PX4 1.13.1

NuttShell (NSH) NuttX-10.2.0
nsh> ver all
HW arch: HOLYBRO_KAKUTEH7
FW git-hash: dc7f29e2ec7a47a3e425d960af1ee8070fc15ed9
FW version: Release 1.13.1 (17629695)
OS: NuttX
OS version: Release 10.2.0 (167903487)
OS git-hash: 91bece51afbe7da9db12e3695cdbb4f4bba4bc83
Build datetime: Oct 13 2022 15:41:49
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 00060000000039393834333951050044002a
MCU: STM32H7[4|5]xxx, rev. V

**Comment by Davidsastresas** [comment]
I don't think this is issue is within the scope of QGC. I think this belongs to a question in the forums of PX4 or dronebridge. I am closing it.
