### ISSUE TITLE
Can't connect Qgroundcontrol 4.2.4

### ISSUE THREAD

**Issue by ghost** [mavlink/qgroundcontrol#10587]
I'm currently working on an underwater drone that works with Pixhawk Cube Orange and Ardusub as it's flight controller. Ardusub communicates with the ground station with the Raspberry Pi 3B. Raspberry Pi 3B has Companion Software image v0.0.31 on it and on an Ethernet Network, it sends telemetry data to the port 14551 of the ground station. When I use QGroundcontrol 4.2.4 as ground station software, I was unable to connect to the vehicle but when I use the 4.2.1 and also Mission Planner 1.3.79 it connected successfully. What may cause this problem?

**Comment by HTRamsey** [comment]
If you still have issues, the forums or Discord would be a better place to ask.
