### ISSUE TITLE
Offline Maps: no elevation for northern Norway/Svalbard.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#10592]
## Expected Behavior
I would expect elevation data just as for the rest of the world.

## Current Behavior
They won't be downloaded.: 
![Screenshot from 2023-02-21 08-24-11](https://user-images.githubusercontent.com/1468842/220278979-dfe01ece-42cb-47e3-9536-eeb62f996599.png)

## Steps to Reproduce:
1. in planning, or maps caching - observe missing data.

## System Information
- QGC Version: current master

## Detailed Description
It's been like this for a long time

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by booo** [comment]
As far as I know there are areas of the world where the model does not provide elevation data. Could you please double check on that. Thanks a lot.

**Comment by AndKe** [comment]
@booo yes, I've tried random spots in Scandinavia, Europe (I think Germany or Poland) and USA and assumed this is a wide issue.  - Is there a debug-log flag for elevation-fetching?

**Comment by booo** [comment]
The elevation data download is broken for other spots of Europe too?

https://terrain.ardupilot.org/ here you can download terrain data manual for ardupilot.

Sorry, I'm not familiar with this part of the code. If there is no logging maybe you can add some in a PR?
