### ISSUE TITLE
Offline map export does not add proper filename extension

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#10591]
## Expected Behavior
exported maps should be saved as filename.qgctiledb

## Current Behavior
saved as filename

## Steps to Reproduce:
1.export map(s)  - specify filename, but dont type the extension

## System Information
- Operating System: ubuntu 22.10
- QGC Version: current master

**Comment by jnomikos** [comment]
I was able to recreate this on Ubuntu 22.04

**Comment by DonLakeFlyer** [comment]
@AndKe Thanks for the bug report
