### ISSUE TITLE
Offline maps: cosmetic issues.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#10593]
Tiles count does not fit:

![Screenshot from 2023-02-20 23-21-53](https://user-images.githubusercontent.com/1468842/220285309-46b8a3fc-39fb-4eaa-b223-eb02b9ccddae.png)

Apart from "default map" - only the last download gets a green dot - all other are red.  - the "green dot" - whitch I guess means "completed/fetched" is ...not stored.
![Screenshot from 2023-02-21 07-39-10](https://user-images.githubusercontent.com/1468842/220285362-55bb1871-c114-48db-a20d-72b3dd43e155.png)

There is tons of screen area, no need to use such a narrow column.
![Screenshot from 2023-02-21 07-50-45](https://user-images.githubusercontent.com/1468842/220285613-aeab6010-c472-47bb-90c0-a64a9ff23bc9.png)

**Comment by Davidsastresas** [comment]
This was addressed here: #10598 

It should fix the text overlapping. For the buttons going green or not, they will go green when the whole tileset is downloaded. From your screenshot it seems the tilesets labeled in red have not been completely downloaded, thus they are red.

On my screenshots on the PR you can see it worked nicely for me. Maybe you got bad connection or something and they were not able to complete.

Please report back and close the issue if the PR fixes it for you. Thanks for reporting!

**Comment by AndKe** [comment]
@Davidsastresas please let me show you:

[Screencast from 2023-02-22 23-08-20.webm](https://user-images.githubusercontent.com/1468842/220771163-bb2b0781-71c3-47d3-9972-be14a2f73a43.webm)

In other words: after download - they are green and fine, successfully completed. Then I restart QGC, and all are red - but eager to become green is "resumed" with 0 tiles.  Hence my idea about the "dot-status" not being stored.

**Comment by Davidsastresas** [comment]
Sorry, I didn't understood correctly. Just tested, it is working fine for me. It is funny because a couple of months back a partner of mine reported weird stuff happening on QGC and ubuntu 22. We took a look real quick, it wasn't making sense the time we were putting into it so he just rolled back to 20.04 in order to keep working. I just tested on my machine, ubuntu 20.04 and it is working as expected:

https://drive.google.com/file/d/1iwMxc4eBWqv_Oi_mb3pRkKxDXps-4soL/view?usp=sharing

So maybe there is something in ubuntu 22 that is conflicting with QGC some way.

**Comment by AndKe** [comment]
@Davidsastresas  I do believe you .. but we both know how extremely odd this sounds..  of millions of CPU cycles, some get to result in a different outcome?  :)   - this is bizarre ..and scary  :o

**Comment by AndKe** [comment]
Additional information: latest QGC .AppImage behaves the same way.
I am aware of some SSL issues on Ubuntu22.10 that only manifest themself on APMplanner2 and QGC, and in case of those, Appimage works fine.  (of course, I don't see how this simple thing could be SSL related) - the tiles are after all downloaded just fine.

**Comment by Davidsastresas** [comment]
It is extremely odd indeed. If more people get to confirm this, maybe we should close this issue for the cosmetic changes, and open a new issue with all the issues together related to ubuntu 22?

My machine is on ubuntu 20.04 now. I want to update to 22, but I don't think I will spare the time to do so on the short future, so I don't think I will be able to take a look at this on the following weeks.

**Comment by AndKe** [comment]
@Davidsastresas Where are my tiles /tile-db stored? - I should try to delete it in case this is a corrupted setup (I did export/import by tiles-db and synced across computers before - maybe I synced the error)
I can try to delete/move it for a test.
I would expect the tiles to be stored in one of those dirs:
"~/Documents/QGroundControl Daily"
"~/Documents/QGroundControl"
...but to my surprise ... they are not there.

**Comment by Davidsastresas** [comment]
In my Linux machine they are located here:

home/"user"/.cache/QGCMapCache300

Let me know if you advance on this. Thanks!

**Comment by AndKe** [comment]
@Davidsastresas 
I renamed ~/.cache/QGroundControl.org and ~/.cache/QGCMapCache300   - and the status dot behaves as expected.
if this is of any interest to fix this non-critical bug - I could pack up and share those directories. 

BTW: fetching elevation fails consistently every time :)  - is "airmap services" required to fetch elevation data ?

**Comment by booo** [comment]
I don't think "airmap services" are required to fetch elevation data.

I guess we don't catch an error at the right spot. Do you have time to dig in? Deleting the cache is fine but a proper solution would be robust code.

**Comment by AndKe** [comment]
I tried to look into it, but my Qt skills are insufficient for proper debugging.

**Comment by HTRamsey** [comment]
This part of the UI has largely been rewritten
