### ISSUE TITLE
Logs download in Analyze Tools but so much slow download rate.

### ISSUE THREAD

**Issue by RajanDhiman07** [mavlink/qgroundcontrol#10619]
The log downloading speed is too slow on android.

Current Behavior-
Approx 1 MB download take time more than 8 minute and 2-3 kb downloading rate. and also date is not showing in log file name.

System Information
When posting bug reports, include the following information
QGC build
Flight Controller: X7+
Ardupilot (with version):  master.

Screenshot-
![image](https://user-images.githubusercontent.com/107532424/224963997-40a589c0-1d97-4e96-8cf0-e7aa80d7bf63.png)

**Comment by booo** [comment]
What download speeds do you expect?

How are you connected to the FC? Please share details about your setup.

**Comment by RajanDhiman07** [comment]
we are connecting FC with the air unit and we are using RC-H16. and we expect the speed to be 1 MB download complete take time in approx 2 Minutes.

**Comment by booo** [comment]
I don't think your expectations are right. E.g. PixRacer + ESP never reaches speeds in the MegaBits/s range. Even with usb connection you don't get that.

Did you get other download speeds with other setups?

**Comment by RajanDhiman07** [comment]
Yes received, if I connect with a USB cable speed, is received 200kb per second but if connect with an air unit speed given is an average of 3 to 4 kb per second.

**Comment by HTRamsey** [comment]
This isn't QGC specific. Log downloads are just crazy slow over IP
