### ISSUE TITLE
Can't move forward AUV in QGroundControl with SITL

### ISSUE THREAD

**Issue by ghost** [mavlink/qgroundcontrol#10621]
Hello,
I have an underwater vehicle that communicates with the ground station via Mavlink. Also, I have been using a SITL Simulator to simulate and check my codes. I have been attempting to connect the vehicle to the SITL in order to make it move forward on QGroundControl vx.x.x using the provided code. However, even though I have successfully armed the vehicle and it has connected to the SITL, I am unable to make the AUV move forward. Here is the code I have been using: 

https://github.com/leone24/Autonomous/blob/main/13-03.py

What are some potential causes for this issue, and how can I troubleshoot it?

**Comment by Davidsastresas** [comment]
Hello @leone24 , it seems that is a non QGC specific question. You are trying to interact with your vehicle using mavlink, but QGC is not really behaving erratically here right? it is the vehicle on SITL itself. 

If the above is correct, you will have better luck asking in mavlink or in your vehicle's firmware specific github repos, or in their respective Discord channels. 

Please confirm the above so we can close this, or keep debugging if it is related to QGC in any way. Thanks!
