### ISSUE TITLE
Firmware upgrade: manifest download fails with SSL certificate issue

### ISSUE THREAD

**Issue by junwoo091400** [mavlink/qgroundcontrol#10659]
## Summary
I have noticed that the PX4 version string wasn't showing up in the QGC Firmware upgrade panel, and was just showing "PX4 Pro" when I connected flight controllers.

![image](https://user-images.githubusercontent.com/23277211/231967741-17a7d979-2aaf-4578-859f-a2e0b2fa4768.png)

After some debugging, an issue in SSL certificate was found through the console log as detailed below.

## Current Behavior
![image](https://user-images.githubusercontent.com/23277211/231967346-2ab3ca62-e040-4504-bc57-f3b4fede82e2.png)

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Set Logging in Console of QGC to include "FirmwareUpgradeLog"
2. Go to Firmware tab and connect any flight controller board
3. Wait few seconds, then go back to Console log
4. Check the error message in the log

## System Information
When posting bug reports, include the following information
- Operating System:Ubuntu 22.04
- QGC build: Daily, from 2022-12-30

**Comment by junwoo091400** [comment]
Note, even if the releases version JSON download isn't complete, downloading the beta release itself is working as the S3 bucket provides the necessary binary:

![image](https://user-images.githubusercontent.com/23277211/231968690-8f312b4e-80b5-4852-ae9f-e7ea148d23e6.png)

However, of course selecting the version is impossible.

**Comment by bkueng** [comment]
This works for me:
![image](https://github.com/mavlink/qgroundcontrol/assets/281593/1be8057c-19f8-4e57-8211-76fe555cccb3)
Do you have the openssl dev package installed?

**Comment by bkueng** [comment]
Fixed in https://github.com/mavlink/qgroundcontrol/pull/10784
