### ISSUE TITLE
Package Deploy on linux failed , files deleted on FTP.

### ISSUE THREAD

**Issue by Momiji-Hua** [mavlink/qgroundcontrol#10671]
## Current Behavior
1.Failed when running **create_linux_appimage.sh**
2.Can't find file that should be downloaded.
3.Can't find file on ftp server.

## System Information
- Operating System: Ubuntu 20.06 x86-amd64
- QGC Version:3.5.6
- QGC build:  self-built from source

## Detailed Description
wget -c --quiet http://ftp.us.debian.org/debian/pool/main/u/udev/udev_175-7.2_amd64.deb
_This file was totally deleted and on other version._

wget -c --quiet http://ftp.us.debian.org/debian/pool/main/s/speech-dispatcher/speech-dispatcher_0.8.8-1_amd64.deb
wget -c --quiet http://ftp.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.2%2bdfsg1-6_amd64.deb
wget -c --quiet http://ftp.us.debian.org/debian/pool/main/d/directfb/libdirectfb-1.2-9_1.2.10.0-5.1_amd64.deb
wget -c --quiet http://ftp.us.debian.org/debian/pool/main/t/tslib/libts-0.0-0_1.0-11_amd64.deb
_Those file was deleted but there has newer version_

What should I do to package QGC to appimage.

**Comment by HTRamsey** [comment]
app image is created differently now, but for older QGCs you can change the versions of those downloads so they work
