### ISSUE TITLE
Joystick Button -> Actuator under QGC... not very easy !

### ISSUE THREAD

**Issue by johnnybreizh** [mavlink/qgroundcontrol#10674]
Hi everyone,

I look for couple of days to configure a pixhawk 6X under QGC to control servo thanks to a UDP MAVLINK link.
It is very strange because i can't make a mapping between Joystick button and Actuator configuration... i don't found a way to do that.
Maybe be someone can explain to me how doing this thing ? Is it possible ? 

Thank to everyone who can explain to me or help me !

Have a great day .

JB

**Comment by HTRamsey** [comment]
All available assignable actions show up under settings->Joystick->Button Assignment when a joystick is connected
