### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'QGCMapEngine.obj'

### ISSUE THREAD

**Issue by AnaabTeam** [mavlink/qgroundcontrol#10675]
Error while building QGC

LINK : fatal error LNK1104: cannot open file 'QGCMapEngine.obj'
jom: C:\Users\User\CLionProjects\build-qgroundcontrol-Desktop_Qt_5_15_2_MSVC2019_64bit-Debug\Makefile [staging\QGroundControl.exe] Error 1104
11:15:05: The process "C:\Qt\Tools\QtCreator\bin\jom\jom.exe" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Desktop Qt 5.15.2 MSVC2019 64bit)
When executing step "Make"
11:15:05: Elapsed time: 05:16.

**Comment by nanmuxunxiang** [comment]
i have the same problem as you,please did you solve it ?

**Comment by HTRamsey** [comment]
For anyone else, 99% of times this shows up due to a space in the path.
