### ISSUE TITLE
error: LNK1104: 无法打开文件“QGCMapEngine.obj”

### ISSUE THREAD

**Issue by nanmuxunxiang** [mavlink/qgroundcontrol#10688]
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /VERSION:0.0 /MANIFEST:embed /OUT:staging\QGroundControl.exe @C:\Users\1\AppData\Local\Temp\QGroundControl.exe.5856.631078.jom
LINK : fatal error LNK1104: 无法打开文件“QGCMapEngine.obj”
jom: D:\Share files\build-qgroundcontrol-Desktop_Qt_5_15_2_MSVC2019_64bit-Debug\Makefile [staging\QGroundControl.exe] Error 1104
09:41:00: 进程"C:\Qt\Tools\QtCreator\bin\jom\jom.exe"退出，退出代码 2 。
Error while building/deploying project qgroundcontrol (kit: Desktop Qt 5.15.2 MSVC2019 64bit)
When executing step "Make"
09:41:00: Elapsed time: 10:48.

**Comment by booo** [comment]
Please provide proper description of your problem. Otherwise we can't help you.
