### ISSUE TITLE
Why Autoload PLan isn't supported anymore?

### ISSUE THREAD

**Issue by SebastianViollaz** [mavlink/qgroundcontrol#10685]
Is there any particular reason why Autoload Mission is no longer supported?
941e436 in this commit this feature was remove. Is it possible to make this feature supported again?

I made a modification to the source code. Just execution a few things in the plan. But i want this to be in the official releases. How can i do that? (if this feature was deleted for some reason let me known pls)

**Comment by HTRamsey** [comment]
#8854
