### ISSUE TITLE
Go to location disappears on v4.2.4/v4.2.0 with Ardupilot firmware

### ISSUE THREAD

**Issue by aaky** [mavlink/qgroundcontrol#10683]
## Expected Behavior
QGC should show "Go to location" as soon as vehicle is in air and reached takeoff altitude. I wasn't seeing "Go to location" option coming up on Android/Linux build of QGC v4.2.0 and v4.2.4 with Ardupilot firmware version v4.3.6. 
## Current Behavior
"Go to location" option not available even if vehicle was in air and on takeoff point.

## Steps to Reproduce:
Very hard to reproduce in SITL. Please find attached log and parameter file to analyze. 
I need more information on when "Go to location" is active or disapperas with Ardupilot firmware based vehicle.

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]
- QGC Version: 4.2.4 / 4.2.0
- QGC build: stable
- Flight Controller: Cube orange plus
- Autopilot (with version): Ardupilot Copter-v4.3.6

## Log Files and Screenshots
Please find attached logs and screenshot. Please help if anyone has seen this issue.

[https://drive.google.com/drive/folders/1OmTy7v0eJ25Gwgv2Scvr0GXFi9UdcHvq](url)

**Comment by HTRamsey** [comment]
This is based on the flying state from the Extended Sys State message. Most likely this wasn't being sent via mavlink
