### ISSUE TITLE
Help needed for take off!

### ISSUE THREAD

**Issue by LoreBene99** [mavlink/qgroundcontrol#10691]
Welcome to everybody. I'm new to this field and with my University collegues I'm trying to use rosettadrone as a mavlink wrapper and QGC to fly DJI drones for a project. I installed rosettadrone and QGC. I have already set-up everything and the connection between the devices is well-established. In fact, I accurately followed the guide on the rosettadrone repo on github, setting the port and the IP for the connection between the RC and the ground control station (my laptop., since I use QGC on the PC). Unfortunately I faced some problems.  Basically, when I try to take off the drone from QGC on my laptop and rosettadrone opened on my smartphone, nothing happen, even if the GPS is working and the drone is connected to the RC and QGC. Instead, if I manually take off the drone and then I press the "Land" action from QGC, it works properly (the safety mode on rosetta is disabled, of course).  Does anyone know how to fix this? Thank you in advance!

**Comment by kschoelpple** [comment]
Within "Application Settings" have you changed "Minimum Altitude" to 0?
