### ISSUE TITLE
mode change dangerous for some modes

### ISSUE THREAD

**Issue by tridge** [mavlink/qgroundcontrol#10707]
the current mode change drop down is potentially dangerous, with users sometimes choosing modes like ACRO which will result in an instant crash for users not prepared for them.
I don't think adding confirmation for all modes is the right answer, as sometimes you do need fast mode switching.
Maybe this?
 - have a way to disable some modes completely so they don't appear in the list
 - be able to mark some modes as requiring confirmation (eg. MANUAL mode or QSTABILIZE on a VTOL plane)

thanks to alex from ARACE for this image:
![image](https://github.com/mavlink/qgroundcontrol/assets/831867/57f94cf9-a255-4965-a803-5aa5364f8a2e)

**Comment by tridge** [comment]
another option is to have a list of "favourite" flight modes. Favourites would be in that drop down if favourites is non-empty (otherwise would have full list). Non-favourite modes would be via a separate menu with confirmation

**Comment by DonLakeFlyer** [comment]
FYI: I have favorite flight modes already implemented in a pull. I was waiting for a new stable to go out before I push it through. It basically sets some flight modes as advanced (including Acro for xeample). By default these advanced flight modes are not included in the dropdown by default. You can then edit the dropdown to add/remove what you want.

It's all sitting in here: https://github.com/mavlink/qgroundcontrol/pull/10618

**Comment by DonLakeFlyer** [comment]
I made all mode changes from the toolbar require confirmation. We'll see if that causes problems or not.
