### ISSUE TITLE
Compilation error: APMRemoteSupportComponent

### ISSUE THREAD

**Issue by flacomalone** [mavlink/qgroundcontrol#10736]
## Expected Behavior
It should compile without any issue, according to official documentation

## Current Behavior
Compilation fails in qgroundcontrol/src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc:158 

## Steps to Reproduce:
1. mkdir build
2. cd build
3. qmake ../
4. make

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 20.04
- QGC Version: 4.2.8

## Log Files and Screenshots
====================[ Build | all | Debug ]=====================================
/home/david/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/223.8214.51/bin/cmake/linux/bin/cmake --build /home/david/qgroundcontrol/build --target all -j 16
[1/1] Linking CXX executable QGroundControl
FAILED: QGroundControl 
: && /usr/bin/c++ -g  CMakeFiles/QGroundControl.dir/QGroundControl_autogen/mocs_compilation.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcimages.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgcresources.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_qgroundcontrol.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/RBUUZA67W2/qrc_InstrumentValueIcons.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/ZHQSJ6LXPM/qrc_APMResources.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/22EX5NVWOJ/qrc_PX4Resources.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/SCLPBLNWZG/qrc_qml.cpp.o CMakeFiles/QGroundControl.dir/QGroundControl_autogen/EWIEGA46WW/qrc_UnitTest.cpp.o -o QGroundControl  -Wl,-rpath,/home/david/qgroundcontrol/build/libs/shapelib:/home/david/Qt/5.15.2/gcc_64/lib:/home/david/qgroundcontrol/build/libs/qmlglsink:  src/libqgc.a  src/ADSB/libADSB.a  src/AnalyzeView/libAnalyzeView.a  src/api/libapi.a  src/Audio/libAudio.a  src/AutoPilotPlugins/libAutoPilotPlugins.a  src/Camera/libCamera.a  src/comm/libcomm.a  src/Compression/libcompression.a  src/FactSystem/libFactSystem.a  src/FirmwarePlugin/libFirmwarePlugin.a  src/FlightMap/libFlightMap.a  src/FollowMe/libFollowMe.a  src/Geo/libGeo.a  src/GPS/libgps.a  src/Joystick/libJoystick.a  src/MissionManager/libMissionManager.a  src/PositionManager/libPositionManager.a  src/QmlControls/libQmlControls.a  src/QtLocationPlugin/libQtLocationPlugin.a  src/Settings/libSettings.a  src/Terrain/libTerrain.a  src/uas/libuas.a  src/ui/libui.a  src/Vehicle/libVehicle.a  src/VehicleSetup/libVehicleSetup.a  src/VideoManager/libVideoManager.a  src/qgcunittest/libqgcunittest.a  src/FactSystem/FactControls/libFactControls.a  src/Vehicle/Actuators/libActuators.a  libs/libevents/liblibevents_parser.a  libs/libevents/liblibevents_health_and_arming_checks.a  src/VideoReceiver/libVideoReceiver.a  src/libqgc.a  src/ADSB/libADSB.a  src/AnalyzeView/libAnalyzeView.a  src/api/libapi.a  src/Audio/libAudio.a  src/AutoPilotPlugins/libAutoPilotPlugins.a  src/Camera/libCamera.a  src/comm/libcomm.a  src/Compression/libcompression.a  src/FactSystem/libFactSystem.a  src/FirmwarePlugin/libFirmwarePlugin.a  src/FlightMap/libFlightMap.a  src/FollowMe/libFollowMe.a  src/Geo/libGeo.a  src/GPS/libgps.a  src/Joystick/libJoystick.a  src/MissionManager/libMissionManager.a  src/PositionManager/libPositionManager.a  src/QmlControls/libQmlControls.a  src/QtLocationPlugin/libQtLocationPlugin.a  src/Settings/libSettings.a  src/Terrain/libTerrain.a  src/uas/libuas.a  src/ui/libui.a  src/Vehicle/libVehicle.a  src/VehicleSetup/libVehicleSetup.a  src/VideoManager/libVideoManager.a  src/qgcunittest/libqgcunittest.a  src/FactSystem/FactControls/libFactControls.a  src/Vehicle/Actuators/libActuators.a  libs/libevents/liblibevents_parser.a  libs/libevents/liblibevents_health_and_arming_checks.a  src/VideoReceiver/libVideoReceiver.a  libs/shapelib/libshp.so.1.5.0  -lm  /home/david/Qt/5.15.2/gcc_64/lib/libQt5QuickControls2.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5QuickWidgets.so.5.15.2  -lz  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Charts.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Test.so.5.15.2  libs/qmdnsengine/src/libqmdnsengine.a  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Svg.so.5.15.2  -lSDL2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Xml.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5SerialPort.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5TextToSpeech.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Concurrent.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Location.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5PositioningQuick.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Positioning.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Sql.so.5.15.2  libs/libevents/liblibevents_generated.a  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Quick.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5QmlModels.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Qml.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Multimedia.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Network.so.5.15.2  libs/qmlglsink/libqmlglsink.so  /home/david/Qt/5.15.2/gcc_64/lib/libQt5OpenGL.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Widgets.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5X11Extras.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Gui.so.5.15.2  /home/david/Qt/5.15.2/gcc_64/lib/libQt5Core.so.5.15.2  /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so  /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so  /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so  /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so  /usr/lib/x86_64-linux-gnu/libEGL.so && :
/usr/bin/ld: src/AutoPilotPlugins/libAutoPilotPlugins.a(APMAutoPilotPlugin.cc.o): in function `APMAutoPilotPlugin::vehicleComponents()':
/home/david/qgroundcontrol/src/AutoPilotPlugins/APM/APMAutoPilotPlugin.cc:158: undefined reference to `APMRemoteSupportComponent::APMRemoteSupportComponent(Vehicle*, AutoPilotPlugin*, QObject*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by woodoocrap** [comment]
this seems to fix it https://github.com/mavlink/qgroundcontrol/pull/10760
