### ISSUE TITLE
QGC terminates, while trying "Use Multi Channel Mode Selection

### ISSUE THREAD

**Issue by jstrebel** [mavlink/qgroundcontrol#10755]
## Current Behavior
QGC terminates without any log entry

## Steps to Reproduce:
Click at the Button

## System Information
- Operating System: tried with WIN, Android,OSX
- QGC Version: [e.g. 4.2.8]

- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]

## Log Files and Screenshots
No crash report is generated
![flight_modes_setup](https://github.com/mavlink/qgroundcontrol/assets/2244311/2070164e-6fff-45e9-bf01-d1a29a9b2d22)

**Comment by DonLakeFlyer** [comment]
Is this still supported by the firmware? It think it may have been removed.

**Comment by DonLakeFlyer** [comment]
This crashes on stable because this feature no longer exists on the firmware side. Daily builds will work fine, because it just not there!
