### ISSUE TITLE
QGC COMM LOST WITH RED BAND & Disconnect display

### ISSUE THREAD

**Issue by sibujacob** [mavlink/qgroundcontrol#10779]
**## Expected Behavior**
While rebooting fc after parameter changes under param ---》 Tools, QGC is expected to show a GREEN BAND with "Ready to Fly"  connect.

**## Current Behavior**
After reboot, QGC displays a RED band with communication lost & Disconnect message although the drone is pretty much in pre-arm state , ready to arm . This may become a safety issue for pilots .

**## Steps to Reproduce:**
Following video indicates the actual error
1.https://youtu.be/L6XJY4Rxcgw

**## System Information**
When posting bug reports, include the following information
- Operating System: Android 
- QGC Version: [ Custom QGC HERELINK VERSION ]
- QGC build:         [daily ]
- Flight Controller:     [ Pixhawk orange CUBE.]
- Autopilot (with version):     [PX4  v 1.12.3]

**Comment by DonLakeFlyer** [comment]
Not quite sure if this is fixable. The QGC states doesn't really relate to what the sticks may or may not do since the sticks are not managed by QGC.

**Comment by sibujacob** [comment]
OK...Anyway the issue was not seen with subsequent releases of the QGC v42.8

**Comment by DonLakeFlyer** [comment]
Closing then

**Comment by sibujacob** [comment]
Yes....thank you
