### ISSUE TITLE
Android build fails with error Cannot find android sources in ... 

### ISSUE THREAD

**Issue by arrevalk** [mavlink/qgroundcontrol#10801]
While building Android package from current master branch (bd897577076575a6200055e30484f4ca6094b9ad) i get an build error:
`Cannot find android sources in [redacted]/build-qgroundcontrol-Android_Qt_5_15_2_Clang_Multi_Abi-Debug/ANDROID_PACKAGE_SOURCE_DIR
10:17:57: Process "[redacted]\Qt\5.15.2\android\bin\androiddeployqt.exe" exited with code 11.
Error while building/deploying project (kit: Android Qt 5.15.2 Clang Multi-Abi)
When executing step "Deploy to Android device"
10:17:57: Elapsed time: 03:16.`

Android builds fine on commit: c7b40691c1acf63bd664cbb84962daac6b2dfe62
But starting from 4474702f4db466e7cef85ce82f803a5b8d075253 this error message shows up and build fails.

**Comment by HTRamsey** [comment]
There are several other issues with same problem and mentioned solutions, closing as duplicate. This is fixed via CMake version as well.
