### ISSUE TITLE
undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version Qt_5

### ISSUE THREAD

**Issue by mw66** [mavlink/qgroundcontrol#10807]
## Expected Behavior

I'm trying to build using Containers on Linux, after the build,

it should run successfully.

## Current Behavior
```
$ cd build/
$ ./staging/QGroundControl 
./staging/QGroundControl: symbol lookup error: ./staging/QGroundControl: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version Qt_5
```

## Steps to Reproduce:
I followed exact step on:

https://dev.qgroundcontrol.com/master/en/getting_started/container.html

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 22.04 LTS
- QGC Version: current git clone

**Comment by mw66** [comment]
related issue: https://github.com/mavlink/qgroundcontrol/issues/10578

**Comment by RoundPegInASquareHole** [comment]
for me, executing the file build/staging/QGroundControl with double click worked haha (i am using the version 4.2.9)

**Comment by Alex-Beh** [comment]
@RoundPegInASquareHole same for me also.
