### ISSUE TITLE
What is the key / the process to choose commits for stable version?

### ISSUE THREAD

**Issue by zdanek** [mavlink/qgroundcontrol#10809]
Hi.
This seems a question mostly for @patrickelectric 

I try to merge my custom changes with latest stable. I took it from Stable_V4.2
I tried to cherry-pick some necessary commits from master. But I found some problems with missing other code. This is not surprising. What surprised me was:
* commits on stable branch are in "random" order in regard of the date 
* the policy of choosing commits to be taken into stable is unknown for me
* why some old commits are still not available on stable

Regarding order of commits: on master, I see, they are also switched. Does it mean, git takes original commit date, not merge / rebase date?

Regarding "policy": how do you choose what to take? Is it like take everything from master up to particular day? Or picked by some key?

Regarding missing commits, this is most interesting.
_on stable_ When we open  `PlanView.qml`  there is no usage of `QGCSimpleMessageDialog`. And ofc no `QGCSimpleMessageDialog.qml` in this branch. `PlanView.qml` was not updated since 2021. 

_on master_ When we open `PlanView.qml`  there's an usage of  `QGCSimpleMessageDialog` declared in `QGCSimpleMessageDialog.qml`. `PlanView.qml` was updated several times, 5 times more in comparison to stable.

This rises a question, @patrickelectric how do you choose commits to be merged/rebased into Stable branch. This also seems like very hard work, to glue it together.

Thanks :)

**Comment by patrickelectric** [comment]
Hi @HTRamsey! Sorry for not replying it early, I usually merge what people ask to get merge vs what is feasible and safe to gets merged. Also PRs against the stable also help. It's hard to keep track of everything. Currently I'm a bit off the project. But I hope that it answer your question.

**Comment by HTRamsey** [comment]
Oh you're fine, I figured if @zdanek still had the question 6 months later he would just ask on Discord or something so I went ahead and closed it. I'm trying to help clean up the issues a little bit but it's much much worse than I thought haha
