### ISSUE TITLE
Richtext message display broken

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#10811]
It looks like https://github.com/mavlink/qgroundcontrol/pull/10603 broke rich text rendering:

![image](https://github.com/mavlink/qgroundcontrol/assets/281593/b14c1dd7-8f03-43ce-995d-7a98552fe35a)

![image](https://github.com/mavlink/qgroundcontrol/assets/281593/ca82e9ff-dcb5-4e00-86b3-756d9a86d0ab)

@DonLakeFlyer could you have a look?

**Comment by DonLakeFlyer** [comment]
Broken by this as well: https://github.com/mavlink/qgroundcontrol/pull/10533

**Comment by DonLakeFlyer** [comment]
To me using formatting in status text seems like a not so great idea. Not sure how you keep both text like this "foo < bar" which could be in any status text message and this "<b>foo</b>" working correctly.

**Comment by bkueng** [comment]
The above comes through the events interface: https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.cc#L1623.
And the escaping is missing there as well. Initially I just did it that way to fit into the existing UI elements but ideally we would do a bit more.

**Comment by DonLakeFlyer** [comment]
OK, so can you fix this then? The vehicle message stuff was never meant to understand how to do rich text from the vehicle itself. It only used rich text for internal QGC formatting usage.

You'll need to escape the regular text coming through the event stuff. And then I would hack UASMessageHandler for now to look for a "<br/>" in the message and skip the escaping there if so. And then add rich text format back to the critical message label in MainRootWindow. I started to hack it myself, but I'm not quite so sure about that event code to get it right. I also couldn't get the failsafe to generate an event to test it with.
