### ISSUE TITLE
libSDL2-2.0.so.0 not found by docker build

### ISSUE THREAD

**Issue by tarbaig** [mavlink/qgroundcontrol#10858]
## Expected Behavior
After building QGC inside the docker container according to instructions, QCG should find a libSDL2 version.

## Current Behavior
libSDL2-2.0.so is not found, and ( as far as I can tell ) not built.  Sources for SDL are present under the 'libs' directory.

'ldd ./build/staging/QGroundContro' gives : 
...
libSDL2-2.0.so.0 => not found
...

## Steps to Reproduce:
As per guide:
1. git clone --recursive -j8 https://github.com/mavlink/qgroundcontrol.git
2. git submodule update --recursive 
3. docker build --file ./deploy/docker/Dockerfile-build-linux -t qgc-linux-docker .
4. mkdir build
5. docker run --rm -v ${PWD}:/project/source -v ${PWD}/build:/project/build qgc-linux-docker

## System Information
When posting bug reports, include the following information
- Operating System: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
6.2.0-36-generic

- QGC Version: master commit 9b660f19fc79f8fef1ac80c0a40db12557c2707f

**Comment by HTRamsey** [comment]
Master automatically fetches and builds SDL now
