### ISSUE TITLE
How to load qgroundcontrol android repo on android stuido

### ISSUE THREAD

**Issue by Malikfarooq** [mavlink/qgroundcontrol#10885]
I want to load the android repo  of qgroundcontrol project into my Android studio but I am unable to load this its showing  like that 
![image](https://github.com/mavlink/qgroundcontrol/assets/32497675/07cce6c4-4c4b-4f9f-a268-f9d509b99406) 
 please help me where I am wrong

**Comment by DonLakeFlyer** [comment]
> please help me where I am wrong

You can't use android studio. You need to use Qt Creator.

**Comment by bhaskar-glitch** [comment]
> > please help me where I am wrong
> 
> You can't use android studio. You need to use Qt Creator.

We are willing to add some other functionality in the app. Like adding a dashboard to display udp data. Can we do that using QT creator?? and further will we able to export it as a application??

**Comment by DonLakeFlyer** [comment]
https://dev.qgroundcontrol.com/master/en/getting_started/
