### ISSUE TITLE
QGC Daily: Moved to Qt version 6.6.3 - Status

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#10887]
How you can help:
* Try out a daily build and report issues you find making sure to label the Issue with the "Qt6" label.
* Recommendation is to try your scenarios in SITL first before using QGC Daily on a real vehicle flight
* Join the discussion on the QGC discord channel for questions. Don't clutter GitHub Issues with questions.
* If you can help with QGC development ask on QGC discord channel what remaining work you could help out with. Simplest thing is to find a FIXME-QT6 marker (see below) and fix it. Or find a known issue and fix it.

Current status:
* Windows, Linux, Mac and Android builds are available from the normal Daily Build links on qgrouncontrol.com
* You are likely to run into quirkiness/bugs in the UI. It is going to take some time to find all the missing changes to the Qml UI code in QGC. 
* The required changes to Qml although mostly mechanical in nature are not 100% discoverable through just code inspection. It's going to take running all the parts of the ui and verifying it works correctly to find the remaining needed changes.
* The C++ code should be very close to 100% updated. Those issues show up at compile time as opposed to run time.
   * The largest changes were to the Map plugin which download tiles. So there may still be problems to wring out there. 
* The majority of the top level UI with respect to Vehicle Setup and flight of PX4 and ArduPilot vehicles has been tested to verify the basics are working correctly.
* Plan View has had less focus and is likely to be more flaky than the rest of QGC.

Known Issues:
* Linux 
  * You must manually install `sudo apt install libxcb-cursor0` yourself for the Appimage to boot. The AppImage generation script needs to be updated to fix this.
* Android
  * Joystick, support is not working
* Video is currently disabled in all OS types. Video support is still a WIP.
* Unsure where custom-example stands. Likely needs testing/updates.
* The code is also peppered with FIXME-QT6 comments which marks parts which still need work but at this point don't prevent QGC working at  high level.

Building from master:
* Docs are not yet updated. That will come in the future.
* Qt version you need is 6.6.1
* CI builds are still using qmake for build. So that is known to be in a working state. Transition to make for CI will start soonish.
* Here is a screen shot of the modules needed from Mac OSX. You should be able to figure what you need in your OS from here:
<img width="437" alt="Screenshot 2023-12-01 at 6 45 33 PM" src="https://github.com/mavlink/qgroundcontrol/assets/5876851/1a614e54-9484-4de8-9cc4-79bd5be5007c">

**Comment by zdanek** [comment]
@DonLakeFlyer Bluetooth is hidden in Connectivity

**Comment by DonLakeFlyer** [comment]
Add info on what needs to happen to get android build working

**Comment by jstrebel** [comment]
Link to daily build is broken

**Comment by XMoonRiverX** [comment]
I tried android build using windows but got error

![Capture1](https://github.com/mavlink/qgroundcontrol/assets/95236514/46d779ae-86e1-4a35-824d-a26501daad14)
![Capture2](https://github.com/mavlink/qgroundcontrol/assets/95236514/6bdfc055-6a67-45e0-bc2e-6f77f4d87c5c)

**Comment by DonLakeFlyer** [comment]
FYI: I'm working on getting the android build running now

**Comment by DonLakeFlyer** [comment]
Android is building now. Still needs more testing to find problems.

**Comment by julianoes** [comment]
Has there been a change how the unit tests can be run? If I add `--unittest` nothing happens.

**Comment by DonLakeFlyer** [comment]
Nope. It could be busted though. I'll look.

**Comment by DonLakeFlyer** [comment]
It's working fine for me on master

**Comment by julianoes** [comment]
Is there a build flag that I might be missing?

**Comment by DonLakeFlyer** [comment]
Only trigger for unit tests is debug build

**Comment by julianoes** [comment]
Aha, that might be the issue. Thanks.

**Comment by Kim-zhi-jiang** [comment]
Looking forward the map plugin run.
Qt6.6.1 so much change, this problem "qt.network.ssl: No functional TLS backend was found"  copy "stl" Qt ../plugins/stl  into project plugins then can be work

**Comment by julianoes** [comment]
@Kim-zhi-jiang 

> copy "stl" Qt ../plugins/stl into project plugins then can be work

Can you explain with more detail what we have to do? I don't quite understand. Are there docs about it somewhere?

**Comment by Kim-zhi-jiang** [comment]
> @Kim-zhi-jiang
> 
> > copy "stl" Qt ../plugins/stl into project plugins then can be work
> 
> Can you explain with more detail what we have to do? I don't quite understand. Are there docs about it somewhere?

[Xcb, X11, Xlib, Wayland](https://venam.net/blog/unix/2016/10/25/x11-blah-blah.html)
Map plugin not work (Ubuntu 22.04 Qt 6.6.1 X11)  
I'm a rookie, but I know it's really difficult to adapt to so much.

**Comment by Kim-zhi-jiang** [comment]
> @Kim-zhi-jiang
> 
> > copy "stl" Qt ../plugins/stl into project plugins then can be work
> 
> Can you explain with more detail what we have to do? I don't quite understand. Are there docs about it somewhere?

I try install openssl1.1.1 in to Ubuntu 22.04 but failed.
Hope to fix Qt 6.6. x in the next version 
[How to build Qt 5.15 Community with OpenSSL 3](https://gist.github.com/seyedmmousavi/b1f6681eb37f3edbe3dcabb6e89c5d43)

**Comment by julianoes** [comment]
My assumption was that Qt6 would come with OpenSSL 3 but does it still not?

**Comment by Kim-zhi-jiang** [comment]
> My assumption was that Qt6 would come with OpenSSL 3 but does it still not?

I also tried build the openssl 3 source code in the Qt6.6.1 tools.
The map is still blank .

**Comment by DonLakeFlyer** [comment]
I've run on Ubuntu 22 and the map worked fine. I haven't seen map problems on any OS.

**Comment by DonLakeFlyer** [comment]
New video support was just merge into daily builds. Woohoo!

**Comment by jinglebang** [comment]
why  I  build  master source code  in the Qt6.6.3   is  Daily version

**Comment by jinglebang** [comment]
![a](https://github.com/mavlink/qgroundcontrol/assets/54563807/cf7f841b-cf30-4651-a674-1bfd7a7f5d34)
![a](https://github.com/mavlink/qgroundcontrol/assets/54563807/cf7f841b-cf30-4651-a674-1bfd7a7f5d34)
