### ISSUE TITLE
Telemetry bar setting causes index out of range

### ISSUE THREAD

**Issue by ryanjAA** [mavlink/qgroundcontrol#10890]
If you set          column      = factValueGrid.columns()->value<QmlObjectListModel*>(2) to larger than 3 to have your own default telemetry bar settings in QGCCorePlugin.cc you get an ASSERT failure in QList<T>::operator[]: "index out of range" error on build. 

To replicate, comment out the if includeFW here:
https://github.com/mavlink/qgroundcontrol/blob/0082c19111265112016188716a74aaed50e85c25/src/api/QGCCorePlugin.cc#L339-L368

and just duplicate this a few times increasing the index. More than 3 and the error is thrown.
https://github.com/mavlink/qgroundcontrol/blob/0082c19111265112016188716a74aaed50e85c25/src/api/QGCCorePlugin.cc#L323-L336

Obviously this can work because you can do it manually after QGC is open but it isnt great that the amount of columns are limited.

**Comment by DonLakeFlyer** [comment]
You must have missed updating some other thing. Debug it.

**Comment by ryanjAA** [comment]
Nope, just pulled 4.3.0 and copy pasted. No changes and crashes on open.

**Comment by ryanjAA** [comment]
It's because of this line:

https://github.com/mavlink/qgroundcontrol/blob/0082c19111265112016188716a74aaed50e85c25/src/api/QGCCorePlugin.cc#L300-L302

If you want more, add mode here. Better solution would be previous plus one but hack is just increase add another line.
