### ISSUE TITLE
How can I solve the problem of receiving h265 video on my Herelink device?

### ISSUE THREAD

**Issue by rukiyeozsoy** [mavlink/qgroundcontrol#10953]
I want to receive h265 broadcast on my HX4-06211 Herelink Controller Unit, but I cannot receive it. I have no problems receiving my broadcast via h264. Does my device support h265 and if so, how can I receive broadcasts?

**Comment by DonLakeFlyer** [comment]
You should ask these questions on the Herelink forums to see if that is even supported by the AirUnit.

**Comment by rukiyeozsoy** [comment]
I asked, but unfortunately there was no response.

**Comment by DonLakeFlyer** [comment]
Try the PX4 discord channels. You could try in the QGC channel there. There are Herelink users there.

**Comment by rukiyeozsoy** [comment]
I joined the channel, thank you.
