### ISSUE TITLE
Action buttons disappeared in APK build from latest version 4.3.0

### ISSUE THREAD

**Issue by orca741** [mavlink/qgroundcontrol#10951]
After several attempts, I finally managed to build the latest version (4.3.0) for Android OS. In official  docs for developers, it is mentioned that version 5.12 must be used, but actually it must be 6.6 or more and really building the source for Android was very challenging. including the `not found` error for many `.qml` files and etc. anyway
The current problem is that the action buttons are not displayed in the `firstrunprompt`.
![223310](https://github.com/mavlink/qgroundcontrol/assets/58466440/720b8f14-8dda-4c8d-8859-2c1f8fd03b95)

**Comment by DonLakeFlyer** [comment]
That is on purpose. If the action button is only Ok or Close then they are no longer shown. You just click outside to close the dialog. Or Escape/Enter key. I may put them back if this seems too strange. But at this point this is working correctly.

**Comment by orca741** [comment]
Ok!
But this is android device and there is no escape/enter key. Also clicking outside not working in this prompt at least.
Please fix that!

**Comment by DonLakeFlyer** [comment]
Use a daily build downloaded from website. Verify that also doesn't work for you. It's woking fine for me. If daily build created from CI works, then there is something wrong with your own personal build.
