### ISSUE TITLE
Build Environment Setup air QGC android Issues

### ISSUE THREAD

**Issue by mjemv** [mavlink/qgroundcontrol#10952]
Hi,
I am using ubuntu and have setup
1. QT Creator Based on Qt 6.6.0 (GCC 10.3.1 20210422 (Red Hat 10.3.1-1), x86_64)
2. QT is 5.15.2
3. JDK which one to use ?
   with jdk 11 build works but  setup tools fail
5. with jdk 21, I get error
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

6. Which Android SDK / NDK version to use 
7. How to setup Deployment android device?
- I have downloaded emulator using SDK manager but which AVD image to user x86  / armvv8 / v7

Please advice.

**Comment by DonLakeFlyer** [comment]
This is all covered in the Qt docs for android. Have you look at those? Search for "Qt5.15 Android"
