### ISSUE TITLE
PID window scaling 5 inch screens

### ISSUE THREAD

**Issue by Siciro** [mavlink/qgroundcontrol#10986]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issue
## Expected Behavior
PID window scaling correctly with 5 inch screen

## Current Behavior
Window scaling sometimes to small or too big and x and y axis figures cut off. 

## Steps to Reproduce:
Refer to attached photod

## System Information
Siyi radio mk 15 with 5 inch screen

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
-
![ee388587-93a4-458a-92e5-59db79858005](https://github.com/mavlink/qgroundcontrol/assets/16576381/864f3297-530c-4bf9-b4b7-7d51b195e37b)

![d80847d7-9006-4ee5-bc46-c3ca34798303](https://github.com/mavlink/qgroundcontrol/assets/16576381/cb053b70-282c-42a9-bd91-83fd65023b27)
![Uploading 97e6d57b-1297-48e4-9e19-c3052030ab49.jpg…]()

**Comment by Siciro** [comment]
Found this error in the velocity window
![17058615079274580140369553375882](https://github.com/mavlink/qgroundcontrol/assets/16576381/a833d37d-a005-4fba-9783-9e98d4c5984c)
![17058615360919130328921091242941](https://github.com/mavlink/qgroundcontrol/assets/16576381/f8275ba3-03e1-47e3-9289-c504874412e1)

**Comment by DonLakeFlyer** [comment]
I believe that manual tuning which is popping those missing parameter error is only available on latest dev firmware

**Comment by Siciro** [comment]
Hello Don.

Will that be 1.15?
