### ISSUE TITLE
QGC on ubuntu cannot connect to the network

### ISSUE THREAD

**Issue by Bruch-wang** [mavlink/qgroundcontrol#10994]
## Expected Behavior
QGC can not connect the network the map cannot be loaded

## Current Behavior
----------------------------------------------------

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.QGC version:v4.3.0 ubuntu version:20.04
2.QGC can not connect the network the map cannot be loaded
3.we try the different QGC version such as v2.7.0 and so on but still have this problem
4.we suspect that the map api on ununtu has expired or is experiencing some issues that event changing the map source won't fix

## System Information
QGC v4.3.0   Ubuntu 20.04

## Detailed Description
--------------------------------------------------------

## Log Files and Screenshots
--------------------------------------------------------

**Comment by zdanek** [comment]
Did you try other map providers?
You can change it in settings.
Enable logs and see if there are errors.

**Comment by Bruch-wang** [comment]
Yes. I have tried different map sources before, such as Google and Bing map sources, but still can not load the map, and I noticed in the console log display is not connected to the Internet, I think maybe this is not the map source problem but QGC itself network connection problem, and this is the issue in ubuntu20.04, I'm running everything fine on Windows

**Comment by Bruch-wang** [comment]
![IMG_20240125_181428.jpg](https://github.com/mavlink/qgroundcontrol/assets/127390585/84fd8139-99bf-41b7-8819-6f9bbe9f70c1)

![IMG_20240125_181520.jpg](https://github.com/mavlink/qgroundcontrol/assets/127390585/1ebae4d9-0a5a-46b7-a854-a17837a76a88)

**Comment by Kim-zhi-jiang** [comment]
Internet problem!!! 
I also repeat this problem,  (I accidental touch  once can able to load  maps in short time,this time github no need tunnel )

**Comment by yang5757** [comment]
me too, The console log says Fetch tile error Connection closed.my system information is window11, the QGroundControl is 4.3.0
![console log](https://github.com/mavlink/qgroundcontrol/assets/84484776/72ed36e9-63c8-42e4-866d-f767d36c6020)
![flight view](https://github.com/mavlink/qgroundcontrol/assets/84484776/e6cb3376-7f17-4641-8940-61b8cc6614fc)
