### ISSUE TITLE
QGCS Custom Build Failed

### ISSUE THREAD

**Issue by Storch9120** [mavlink/qgroundcontrol#11013]
----
## Timeline
I’ve followed the latest instructions for a custom build i.e.

1. Fresh Build (completes)
2. Renamed custom-example to custom
3. Ran the python script updateqrc.py
4. Clean build
5. Rebuild (fails)
    and encountered the following errors (Re: Screenshot)
![Screenshot](https://github.com/mavlink/qgroundcontrol/assets/52457425/90b38a13-b836-4a99-9034-5b0a129d6134)

So I made these changes to the CustomFirmwarePlugin.cc at line 23 (inside if statement)
![Screenshot2](https://github.com/mavlink/qgroundcontrol/assets/52457425/e6b7cd37-a091-474f-9d7d-3ab519053164)

Now the build completes but on execution this is shown in Application Output:
![Screenshot3](https://github.com/mavlink/qgroundcontrol/assets/52457425/c8dd459a-3924-4f06-aa45-c9fdccf18171)

## System Information
- Operating System: Ubuntu 20.04
- QGC build: Daily 
- Qt Version 6.6.1

Please advise if I should revert those changes I made and what other changes I should make to diagnose these errors.

**Comment by DonLakeFlyer** [comment]
The custom build hasn't been updated to move to Qt6 yet. I'll try to get to it as soon as I can.

**Comment by ijulanday** [comment]
@Storch9120 hit the same issues! Fix for me was:
* make the same changes as you did to CustomFirmwarePlugin.cc 
* add `import Qt5Compat.GraphicalEffects` to CustomAttitudeWidget.qml (the last line of your final error message)
The application loads and I can switch between fly & plan view, all the buttons seem to work as expected. Not much rigorous testing I can do as I'm just getting into this stuff myself.

<img width="608" alt="Screenshot 2024-02-07 at 4 29 53 PM" src="https://github.com/mavlink/qgroundcontrol/assets/16965581/59aa01c3-7976-4ea3-a894-df3accf3fa9e">
<img width="899" alt="Screenshot 2024-02-07 at 4 40 57 PM" src="https://github.com/mavlink/qgroundcontrol/assets/16965581/37e3516f-8278-439c-91b3-79cce88befc5">

**Comment by TishSerg** [comment]
> The custom build hasn't been updated to move to Qt6 yet. I'll try to get to it as soon as I can.

Any update on this?

**Comment by HTRamsey** [comment]
#11013
