### ISSUE TITLE
Try to build QGC but i got this LNK1181: cannot open input file ‘QGCMapEngine.obj’

### ISSUE THREAD

**Issue by ryan354** [mavlink/qgroundcontrol#11029]
Hi, everyone.
I got this error while trying to build QGCV4.2 using QT Creator 5.15.2 with MSVC 2019 64bit “LNK1181: cannot open input file ‘QGCMapEngine.obj’”. hope anyone can help.
Thanks

**Comment by HTRamsey** [comment]
This is pretty much always due to a space in the path.

**Comment by uby56** [comment]
@HTRamsey i am having same issue can tell me a which path have the space and how to correct it
