### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by arunba1** [mavlink/qgroundcontrol#11037]
Hi Everyone. while building, I am facing an error, please help me out.

I had cloned the Qgrondcontrol repo using the following command "git clone --recursive -j8 https://github.com/mavlink/qgroundcontrol.git"

then proceeded with "git submodule update --recursive"
After that, while building with Qt, this error is coming

![WhatsApp Image 2024-02-09 at 00 57 15_3b4ab129](https://github.com/mavlink/qgroundcontrol/assets/55797482/49700ab8-37ed-4ffb-b3a9-4afe3619b044)

![WhatsApp Image 2024-02-09 at 01 01 54_c0c33eab](https://github.com/mavlink/qgroundcontrol/assets/55797482/3eab961d-6c18-4fe6-b0f8-381fd61aa91b)

Along with this please help me to add a new button at the toolbar section where can I find that, also please help on how to enlarge a toolbar section with a click and how to revert it back with a double click

**Comment by atesahmet0** [comment]
Seems like a common issue #10675 and #10688

Try using:
`git submodule update --init --recursive`

**Comment by arunba1** [comment]
> I had Tried using: `git submodule update --init --recursive`
Still it's giving the same error result. Actually I'm using Qt creator 6.6.1 and cloned this repo using git clone and then ran git module update command still result is same.  I'm using Windows11 as OS and compiler as MSVS 2019 64 bit.  please help me out.

Do we need to clone any specific stable version of repo or normal cloning is enough (git clone 'https ://github.com/mavlink/qgroundcontrol.git'

**Comment by arunba1** [comment]
Hi All!!
Please send Discord Server link or Forum link .

**Comment by DonLakeFlyer** [comment]
QGC: https://discord.com/channels/1022170275984457759/1022185820683255908

Delete your build directory and build again clean.

**Comment by uby56** [comment]
hi i am having the same issue can anyone tell me how to solve this problem
