### ISSUE TITLE
Pixhawk6X-RT firmware update process fails

### ISSUE THREAD

**Issue by dk7xe** [mavlink/qgroundcontrol#11039]
## Expected Behavior
When doing FW update for Pixhawk6X-RT via QGC the PX4 developer build (master) nightly snapshot should be fetched.

## Current Behavior
QGC is reporting "no board specific firmware can be found" in the FW update process

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Open QGC
2. Go to "Vehicle Setup" / "FirmwareT tab
3. Connect Pixhawk6X-RT via USB
4. FMU is detected as PX4 FMU V6-RT with board ID 35 in QGC (Device USB\VID_3643&PID_001D\0 in Windows device manager)
5. Set "Advanced setting" checkbox on "Firmware Setup" pop up window and select "Developer Build (master)" as FW to be installed.
6. Click "OK" on "Firmware Setup" pop up window
7. QGC reports "Unable to find specific firmware for board type" , "Upgrade cancelled"

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: v4.3.0
- QGC build: stable
- Flight Controller: Pixhawk6X-RT
- Autopilot (with version): PX4 developer build (master)

## Detailed Description
Process has been tested with several versions of FMUM-RT7 / Pixhawk 6X-RT
FMU is detected as Device USB\VID_3643&PID_001D\0

## Log Files and Screenshots
![grafik](https://github.com/mavlink/qgroundcontrol/assets/3907200/953ec69f-448d-43fb-97e0-501dfd3a487c)
![grafik](https://github.com/mavlink/qgroundcontrol/assets/3907200/bbf4db6d-38c8-46d7-8412-9a95413d2a0b)

**Comment by dk7xe** [comment]
https://github.com/mavlink/qgroundcontrol/pull/10846
https://github.com/mavlink/qgroundcontrol/pull/10921

**Comment by dk7xe** [comment]
@davids5 @mrpollo

**Comment by davids5** [comment]
@dk7xe See https://github.com/mavlink/qgroundcontrol/blame/master/src/VehicleSetup/FirmwareUpgradeController.cc#L65 is is set to 35. Are you using a daily or some old version of QGC?

**Comment by dk7xe** [comment]
> @dk7xe See https://github.com/mavlink/qgroundcontrol/blame/master/src/VehicleSetup/FirmwareUpgradeController.cc#L65 it is set to 35. Are you using a daily or some old version of QGC?

QGC Version: v4.3.0
QGC build: stable

That was the first stable with Pixhawk6X-RT support

**Comment by dk7xe** [comment]
With latest QGC daily it is working. Please provide a new stable QGC release.

**Comment by dk7xe** [comment]
@mrpollo when is the next QGC release planned that adds support for Pixhawk6X-RT?

**Comment by dk7xe** [comment]
Solved with QGC release 4.4.0
