### ISSUE TITLE
Unable to run daily .AppImage  (missing libQt6Quick3D.so.6)

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#11060]
## Current Behavior

```
$ ./QGroundControl.AppImage 
/tmp/.mount_QGroun9KlhNB/QGroundControl: error while loading shared libraries: libQt6Quick3D.so.6: cannot open shared object file: No such file or directory

```

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. download daily 
2.run

## System Information
Ubuntu 23.10

## Detailed Description
I've also read https://docs.qgroundcontrol.com/master/en/qgc-dev-guide/getting_started/index.html
The "Quick 3D" is not selectable for 6.6.1 as described:

![image](https://github.com/mavlink/qgroundcontrol/assets/1468842/2ca5f1d7-f534-4807-8778-338bff348420)

**Comment by AndKe** [comment]
@HTRamsey Oh, I know that .AppImage should have what it need, it is actually the other way around - I tried to build it from git first, then saw the message, and then tried .AppImage 

The reason I wanted to try your build is that when I built current HEAD, I did not get the elevation for a mission to work(the yellow line is just flat). - wished to try the new DEM source..

**Comment by AndKe** [comment]
@omid-esrafilian Thank you, I did not expect to find it in archive, and then using "filter" was super-counter intuitive, but it worked fine.
Please add this information to build-instructions.

**Comment by omid-esrafilian** [comment]
@AndKe 
Yes, indeed it is misleading. I have included this information in my latest pull request #11048.

**Comment by DonLakeFlyer** [comment]
AppImage should be fixed now as far as including the various missing quick3d libs. As are docs for building.

**Comment by AndKe** [comment]
Yes, thank you. AppImage is working fine now  (except for the https://github.com/mavlink/qgroundcontrol/issues/11084 issue)
