### ISSUE TITLE
Daily .AppImage  - unable to save log (complains about missing file name.)

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#11083]
## Steps to Reproduce:
1. Run Current Daily AppImage
2.
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 23.10

## Log Files and Screenshots
see screenrecording;
[Screencast from 2024-02-20 09-25-19.webm](https://github.com/mavlink/qgroundcontrol/assets/1468842/2d610331-b54f-4068-b60b-ffb9f3e7718f)

**Comment by DonLakeFlyer** [comment]
What kind of log? Screencast is just black for me.

**Comment by AndKe** [comment]
@DonLakeFlyer - that's strange, I can play the webm file in browser by clicking the link above, (chromium-based-browser) any modern player or VLC should handle that. 

Anyway: here is the main screenshot: 
![image](https://github.com/mavlink/qgroundcontrol/assets/1468842/83b50b79-31d0-4f7e-ac62-d6620116775e)
after clicking save, giving the file a name, the error says something about "missing file name".

**Comment by DonLakeFlyer** [comment]
Console, ok. That looks like a Qt file picker dialog which is another problem. It should be using the os dialog.

**Comment by DonLakeFlyer** [comment]
Hmm, working fine for me on OSX.

**Comment by afwilkin** [comment]
Same error on ubuntu 20.04

https://www.loom.com/share/947cf4c756314484aae91b935169f25e

**Comment by AndKe** [comment]
@DonLakeFlyer Yes, please use OS file picker, it will certainly look better.

**Comment by DonLakeFlyer** [comment]
This whole thing (save not working, strange file dialog) seems to be some Qt6 problem which I don't really have control over. I can workaround the save not working, but not the file picker. Every other OS shows OS file dialogs. I'll see if this is change in 6.6.2

**Comment by DonLakeFlyer** [comment]
The pull I just merged should fix the not saving part of this. Can someone else verify?

**Comment by DonLakeFlyer** [comment]
Yup, you need to install libcxb-cursor0 (there might be more than that, not sure yet). I'm working on AppImage and instructions now.

**Comment by Davidsastresas** [comment]
> The pull I just merged should fix the not saving part of this. Can someone else verify?

Just tested, it fixes the issue for me right away in Ubuntu 22.04. Thank you!
