### ISSUE TITLE
OpenSSLv3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11093]
Required for the linux AppImage to work correctly with various TLS issues
[Build from source](https://orcacore.com/install-openssl-3-ubuntu-20-04/)

**Comment by DonLakeFlyer** [comment]
Related to #11084?

**Comment by AndKe** [comment]
@DonLakeFlyer I am pretty sure this is the same issue, yes.
