### ISSUE TITLE
QGC cannot play rtsp video on windows10

### ISSUE THREAD

**Issue by xzxzhao** [mavlink/qgroundcontrol#11106]
I downloaded the QGC master source code, compiled it and run it, and found that it could not play rtsp videos. The console reported: VideoReceiverLog: GStreamer error: Could not initialize window system

**Comment by zdanek** [comment]
Yes. I'm aware of that problem. Still working to fix video on windows.

**Comment by DonLakeFlyer** [comment]
Dup of #11020
