### ISSUE TITLE
Build QGroundControl in container.

### ISSUE THREAD

**Issue by liyunfeng159** [mavlink/qgroundcontrol#11104]
I'm following the Developer's Guide of QGroundControl.

For the part of build using Containers.
I was able to make the docker image by the docker file in /deploy/docker/Dockerfile-build-linux.

but when I tried to build the android apk file with it. the error shows like:
![image](https://github.com/mavlink/qgroundcontrol/assets/121792676/0ea47a6c-6cb0-4868-81d8-7f47f18c4980)

I know QGC has been updated to QT 6.6, but the docker file seems like still install the QT 5.15.2.
Is that a bug? or building with docker has been deprecated?
how should I fix that?
Thank you.

**Comment by futurewebsites** [comment]
It will need updating in the dockerfile and the linux_qt_install shell script I would think

**Comment by DonLakeFlyer** [comment]
Dockerfile needs updating. Please submit a pull to fix it.
