### ISSUE TITLE
compilation-error-issues-Missing-qml-files-FactSystemTest.qml-and-MockLinkSettings.qml-notfound

### ISSUE THREAD

**Issue by SC001er** [mavlink/qgroundcontrol#11109]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]
- QGC Version: [e.g. 3.4.4]
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
compilation-error-issues-Missing-qml-files-FactSystemTest.qml-and-MockLinkSettings.qml-notfound

## Compilation error missing FactSystemTest.qml
- Error: dependent 'E:\QGroundControl\gitRepository\qgroundcontrol\src\FactSystem\FactSystemTest.qml' does not exist.
23:26:20: The process "C:\Qt\Tools\QtCreator\bin\jom\jom.exe" exited with code 2.
- Error while building/deploying project qgroundcontrol (kit: Desktop Qt 6.6.1 MSVC2019 64bit)
- When executing step "Make"

## Compilation error missing MockLinkSettings.qml
- Error: dependent 'E:\QGroundControl\QGroundControl-master\src\ui\preferences\MockLinkSettings.qml' does not exist.
23:57:21: The process "C:\Qt\Tools\QtCreator\bin\jom\jom.exe" exited with code 2.
- Error while building/deploying project qgroundcontrol (kit: Desktop Qt 6.6.1 MSVC2019 64bit)
- When executing step "Make"

**Comment by DonLakeFlyer** [comment]
It looks like you are running a stale makefile against new source files. These files have moved around. Do a fully clean build.
