### ISSUE TITLE
Determine ArduPilot default hidden flight modes

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#11118]
The daily build version of QGC has the ability to hide/show flight from the default flight mode dropdown:
<img width="587" alt="Screenshot 2024-02-25 at 12 33 23 PM" src="https://github.com/mavlink/qgroundcontrol/assets/5876851/c128a67b-584a-41a3-9251-d181be021e85">

The set of flight mode which are hidden are stored in a setting. That setting for hidden flight modes is currently default to an empty list. I would like help determining what the default for this should be. Or in other words which flight modes are infrequently used and because of that are just adding noise/confusion for most ArduPilot users.

For example in copter the list is massive when the user goes to change flight modes from the toolbar:
<img width="1027" alt="Screenshot 2024-02-25 at 12 35 36 PM" src="https://github.com/mavlink/qgroundcontrol/assets/5876851/9d22ebaf-a26a-4b91-bc5f-8b9295a7885b">

That makes it next to unusable. What should the default much shorter (I hope!) list be? Goal would be a nice short list of flight modes which are the ones which are used 99% of the time. Comment please...

**Comment by Davidsastresas** [comment]
I assigned this one to myself. Actually it's been in my to do list for weeks, but I want to first finish that gimbal PR, as it is taking forever.

Ardupilot implemented a parameter that manages precisely this at the AP level, rejecting the mode change if it is configured to do so using this parameter. So I think it would be great to read that parameter, in the newer firmwares that support it, and update automatically the flight mode list based on it. If we want to make it super neat, we could try to detect discordances between the QGC settings and AP parameter and warn the user and hopefully tidy all up for them.

I Think over the next month I will be able to go through this. In the meantime, If you want to leave by default just some flight modes, maybe I would say they should be:

- STABILIZE
- ALT HOLD
- LOITER
- POS HOLD
- GUIDED
- AUTO
- RTL
- LAND

I think the above are a good starting point. For Plane these would be good:

- FBW A
- LOITER
- GUIDED
- RTL
- TAKEOFF

and for VTOL, we should add these to the ones for plane:

- Q LOITER
- Q RTL
- Q HOVER

**Comment by DonLakeFlyer** [comment]
Thanks, that is helpful. It also reminds me that ArduPilot flight modes differ quite a bit with respect to vehicle type. I think I'm going to need to change the code to store hidden flight modes by vehicle type before I can make this all work well.

**Comment by Davidsastresas** [comment]
I think for Ardupilot we could do something based on that parameter functionality instead, so effectively relying on the vehicle, instead of QGC settings, to show those flight modes. I think we could contain this in APMFirmwarePlugin.

I assigned this to me, I think this month I could take a look at it. I will keep you updated about it, thanks!

**Comment by DonLakeFlyer** [comment]
This feature needs to be changed to be vehicle class specific.

**Comment by DonLakeFlyer** [comment]
@Davidsastresas I've updated to your feedback

**Comment by Davidsastresas** [comment]
Sorry @DonLakeFlyer, I missed this thread all this time and I just came back to it now. It looks great, thank you very much.
