### ISSUE TITLE
Can't add ROI

### ISSUE THREAD

**Issue by SebastianViollaz** [mavlink/qgroundcontrol#11159]
----

## Expected Behavior
Load a simple mission with ROI

## Current Behavior
Can't add  ROI: GIven alert:
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/af2f8400-f912-4b93-99f2-b69e29217541)
Al mission items:
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/a9a86035-b0ef-4c3c-ad83-45e66e6efe0a)
This is the mission:
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/6d640111-843f-42f6-823d-dc39f35d520e)

## Steps to Reproduce:

1. Add a mission with a roi and a cancel roi item
2. Load the mmission

## System Information

- Operating System: Linux Ubuntu 22.04LTS
- QGC Version: Last stable
- QGC build: daily build
- Flight Controller:Simulated ArduCopeter, and in a PIX4 Ardupilot Copter  (Last version)

**Comment by SebastianViollaz** [comment]
Sure, i can test it, are you merging to master?

**Comment by DonLakeFlyer** [comment]
> re you merging to master?

I'd rather have you give it a try first

**Comment by SebastianViollaz** [comment]
ok, i will test it, just let me known when it'd done

**Comment by SebastianViollaz** [comment]
I saw your PR and i downloaded the branch. This error is now given:
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/0acac823-1cf5-4f1b-b213-a05114528b93)


THis is the complete mission:
![Uploading image.png…]()

**Comment by DonLakeFlyer** [comment]
@SebastianViollaz What firmware type/version?

**Comment by SebastianViollaz** [comment]
I sorry, for the delay, i solve in the ardupilot
 STL updating to the master brach version. I will check de version in the uav but i think it's the last stable

**Comment by SebastianViollaz** [comment]
Now
 have the 4.4.4 ArduCopter firmware and now its working
