### ISSUE TITLE
Changing BatteryIndicator.qml to display only the first battery

### ISSUE THREAD

**Issue by andrefreitas97** [mavlink/qgroundcontrol#11194]
Hi everyone! 

I would like a suggestion from one of the developers (maybe @DonLakeFlyer ) on how to change the code in BatteryIndicator.qml file in order to display only the first battery info in the QGC toolbar.

I know the changes have to be made somewhere in the following lines. 

    Row {
        id:             batteryIndicatorRow
        anchors.top:    parent.top
        anchors.bottom: parent.bottom

        Repeater {
            model: _activeVehicle ? _activeVehicle.batteries : 0

            Loader {
                anchors.top:        parent.top
                anchors.bottom:     parent.bottom
                sourceComponent:    batteryVisual

                property var battery: object
            }
        }
    }

However, I cannot find a way to limit the repeater to one single battery because I start getting problems with the functions getBatteryColor() and getBatteryPercentageText() due to the fact that I can not find the correct way to set the battery variable in the line "property var battery: object".

Thanks

**Comment by HTRamsey** [comment]
Don't use a repeater and just get the first item of the QmlObjectListModel instead
