### ISSUE TITLE
QGCMenuItem: Does not support invisible

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#11200]
This is a Qt6 change.

**Comment by HTRamsey** [comment]
Oh this is how I've handled it in the past. Don't know if they've added a better way since around Qt6.4 though.
`height: visible ? implicitHeight : 0`

**Comment by DonLakeFlyer** [comment]
I'll try that again. I think that was the way I did in in Qt5, but ran into some problem with Qt6.

**Comment by DonLakeFlyer** [comment]
@HTRamsey That works, thanks
