### ISSUE TITLE
Pinch Zoom Broken

### ISSUE THREAD

**Issue by ben-draper-ascent** [mavlink/qgroundcontrol#11217]
@DonLakeFlyer Not sure what happened but now pinch zoom is broken on android. Could be related to e3b536fc317e1b816f9329d4b19d5771f0162c77 maybe?

**Comment by DonLakeFlyer** [comment]
One step forward one step back!

**Comment by ben-draper-ascent** [comment]
@DonLakeFlyer I think I fixed it. LMK what you think
https://github.com/mavlink/qgroundcontrol/pull/11250
