### ISSUE TITLE
Windows Flags Latest CI Build as a Virus

### ISSUE THREAD

**Issue by AlexKlimaj** [mavlink/qgroundcontrol#11236]
Looks like Windows daily downloaded from the Docs doesn't have video streaming or the mavlink console working.
But downloading the daily from CI gets flagged as a virus.

![image](https://github.com/mavlink/qgroundcontrol/assets/2019539/557ab6d8-5386-4693-97cb-329f3820f220)

**Comment by zdanek** [comment]
interesting, can you check what causes this to be marked as an virus?
IMO this is to be checked, but I see no info about your antivir software. Can you help?
Maybe some particular library, that's a part of an install file, is considered as "harmful"? I'd bet it's based on heuristics and it's a false positive, but let's know what are the reasons.

**Comment by AlexKlimaj** [comment]
Trojan:Script/Wacatac.B!ml

![image](https://github.com/mavlink/qgroundcontrol/assets/2019539/30638cfc-4e85-4cca-be6f-bbb6b9c38987)

**Comment by HTRamsey** [comment]
it's because it's a .exe.zip for some reason

**Comment by HTRamsey** [comment]
Yeah I just doubled checked and the exact same file downloaded as just a .exe from [here](https://docs.qgroundcontrol.com/master/en/qgc-user-guide/releases/daily_builds.html) is fine. so it is the extension

**Comment by AlexKlimaj** [comment]
Are you sure that's the same file? Installed from that file and it shows a build date of Feb 8 2024. Commit 01ccf028

![image](https://github.com/mavlink/qgroundcontrol/assets/2019539/ca66bd0d-726c-42c9-8c88-2f36fa2b309a)

**Comment by HTRamsey** [comment]
Oh I guess the dailys aren't being updated there or something. I have no idea how that is set up. But you can go back several months and download old CI releases and they all throw a virus warning, most likely because of the extension.

**Comment by DonLakeFlyer** [comment]
So this is the zips from CI artifacts right? Not much I can do about that. Does regular doc daily build download link work? That's a raw .EXE

**Comment by AlexKlimaj** [comment]
Yeah. However it looks like the latest builds from master are working again. Not sure why windows thought they were viruses for a while.
