### ISSUE TITLE
Segmentation fault while reading/setting onboard parameters

### ISSUE THREAD

**Issue by sebadavalle** [mavlink/qgroundcontrol#1126]
Operating System: Ubuntu 14.04
QT Version: 5.3.0
QGroundControl Version: master branch (6fdce352165a369a7010b10551eec12a105ef443)

Steps to reproduce:
The first time QGC crashed was when I added the onboard parameters widget to the Plan view. I got all of them (I'm sending 30 onboard param from the UAV) and when I tried to set a modified parameter QGC crashed. After that every time I open QGC and connect it to my UAV it has crashed.
If I modify my UAV code and disable all the onboard parameter, everything works fine.

Back trace of the core dumped

Core was generated by `./qgroundcontrol'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000007568af in SetupView::_parametersReady() ()
(gdb) bt
#0  0x00000000007568af in SetupView::_parametersReady() ()
#1  0x00000000007ac665 in SetupView::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#2  0x00007f69cb081681 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#3  0x000000000079c0ad in QGCUASParamManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#4  0x00007f69cb081681 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#5  0x0000000000712807 in UASParameterCommsMgr::updateSilenceTimer() ()
#6  0x000000000071681b in UASParameterCommsMgr::receivedParameterUpdate(int, int, int, int, QString, QVariant) ()
#7  0x00000000007a644d in UASParameterCommsMgr::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#8  0x00007f69cb081681 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#9  0x0000000000779891 in UASInterface::parameterChanged(int, int, int, int, QString, QVariant) ()
#10 0x000000000055d087 in UAS::processParamValueMsg(__mavlink_message&, QString const&, __mavlink_param_value_t const&, param_union&) ()
#11 0x0000000000560620 in UAS::receiveMessage(LinkInterface*, __mavlink_message) ()
#12 0x000000000077fc6a in UAS::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#13 0x00007f69cb081681 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#14 0x0000000000785d69 in MAVLinkProtocol::messageReceived(LinkInterface*, __mavlink_message) ()
#15 0x0000000000575be2 in MAVLinkProtocol::receiveBytes(LinkInterface*, QByteArray) ()
#16 0x000000000056cd6e in QtPrivate::QSlotObject<void (MAVLinkProtocol::*)(LinkInterface*, QByteArray), QtPrivate::List<LinkInterface*, QtPrivate::List<QByteArray, void> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#17 0x00007f69cb0837c6 in QObject::event(QEvent*) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#18 0x00007f69cc707764 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
---Type <return> to continue, or q <return> to quit---
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Widgets.so.5
#19 0x00007f69cc70ade6 in QApplication::notify(QObject*, QEvent*) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Widgets.so.5
#20 0x00007f69cb04fdd4 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#21 0x00007f69cb052958 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#22 0x00007f69cb0aa013 in ?? () from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#23 0x00007f69c7815e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f69c7816048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f69c78160ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f69cb0aa444 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#27 0x00007f69cb04dfeb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#28 0x00007f69cb052eb5 in QCoreApplication::exec() ()
   from /home/sebastian-davalle/Qt5.3.0/5.3/gcc_64/lib/libQt5Core.so.5
#29 0x0000000000452113 in main ()
(gdb)

**Comment by DonLakeFlyer** [comment]
Should be fixed now
