### ISSUE TITLE
Inconsistent Display of "Ready to Fly" and "Not Ready" Messages

### ISSUE THREAD

**Issue by Tsalla1q4** [mavlink/qgroundcontrol#11268]
----

## Expected Behavior
When using the application, the main screen should display the "Ready to Fly" message when the vehicle is ready for flight and the "Not Ready" message when the vehicle is not ready.

## Current Behavior
However, when attempting to display these messages on the main screen using the logic from MainStatusIndicator.qml, the messages are not being displayed.

## Steps to Reproduce:
1. Launch the application.
2. Navigate to the main screen.
3. Ensure the vehicle is in a ready or not ready state.
4. Observe that the "Ready to Fly" or "Not Ready" message is not displayed as expected.

## System Information
- Operating System: Windows 11
- QGC Version: 4.3.0
- QGC build: Daily

## Detailed Description
The issue arises when attempting to display the "Ready to Fly" and "Not Ready" messages on the main screen. Although the logic from MainStatusIndicator.qml is used, the messages are not appearing as expected.

## Log Files and Screenshots
- MainStatusIndicator.qml
- FlightMap.qml
![ss](https://github.com/mavlink/qgroundcontrol/assets/144650559/4d4c4a10-75d3-41d2-9803-e32df9fcbb75)

**Comment by DonLakeFlyer** [comment]
It sounds like you modified the code. Is that correct? If so, Issues are for reporting bugs in regular releases. If you write your own code all bets are off as to what could be wrong. You'll need to debug it yourself. You can also ask for help on the QGC discord channel, but you'll need to make sure you tried to figure out what is wrong on your own first.
