### ISSUE TITLE
QGC Can not detect VTOL frame for Plan VTOL Mission with Ardupilot code

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#11293]
Hi

I use fixed wing VTOL code of Ardupilot , but when drone is connected to software , QGC in Plan view can not detect that it is a VTOL drone Not Fixedwing Drone . So QGC Detect a Fixed wing and VTOL Take off and Landing Can not be choice and used.

**Comment by that2** [comment]
Same problem over here. Using Arduplane 4.4.4 With Q_Enable for VTOL capabilities but when connected to QGC it shows vehicle type as Fixed wing so no options for VTOL Tkoff and landing.

**Comment by that2** [comment]
@moreba1 try changing the Q_MAV_TYPE to 20, default is auto. That worked for me.

**Comment by moreba1** [comment]
> @moreba1 try changing the Q_MAV_TYPE to 20, default is auto. That worked for me.

Thanks , yes IT works. I had set Q_MAV_TYPE  to auto.

https://github.com/ArduPilot/ardupilot/issues/7137

**Comment by DonLakeFlyer** [comment]
Closing since this is resolved.
