### ISSUE TITLE
App Settings icons not colored correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#11298]
<img width="149" alt="Screenshot 2024-04-05 at 4 41 12 PM" src="https://github.com/mavlink/qgroundcontrol/assets/5876851/6c9374ab-b459-40ff-a95a-08ff82f05c52">

I'm guessing caused by recent changes to Qt5 Compat qml stuff and QGCColoredImage

**Comment by DonLakeFlyer** [comment]
@HTRamsey Could you look at this? Let me know if you need me to poke at it as well.

**Comment by DonLakeFlyer** [comment]
More examples:
<img width="118" alt="Screenshot 2024-04-05 at 4 44 20 PM" src="https://github.com/mavlink/qgroundcontrol/assets/5876851/28239c87-8bc2-41b7-8ac5-45f60a91b446">

The gear icon should be white.

**Comment by DonLakeFlyer** [comment]
This is on a Mac

**Comment by HTRamsey** [comment]
So this one is kinda stupid and I'm not sure why it has to be different than the old ColorOverlay: https://forum.qt.io/topic/144070/qt6-color-svg-using-multieffect/2

**Comment by s-lisovenko** [comment]
Unfortunately there is no simple way to replace ColorOverlay in Qt6. I think we should continue use Qt5Compat for this. 
https://github.com/mavlink/qgroundcontrol/pull/11310

**Comment by HTRamsey** [comment]
Yeah looks like you'd have to change the fill color of every SVG to white then color it in QML
