### ISSUE TITLE
how to view a single qml view?

### ISSUE THREAD

**Issue by shenshiqiSSQ** [mavlink/qgroundcontrol#11313]
Hello, may I ask how to view a single qml view? When I open the qml view through qtcreator, various errors will be reported, resulting in a failure to open QML

![QQ截图20240408182323](https://github.com/mavlink/qgroundcontrol/assets/74520938/23ce706d-0e19-43f9-bb35-eb463daa3e99)
![QQ截图20240408212806](https://github.com/mavlink/qgroundcontrol/assets/74520938/ef392df9-d2f5-4f17-8bef-04694776c45e)
![QQ截图20240408212812](https://github.com/mavlink/qgroundcontrol/assets/74520938/78bddf8c-e8b9-475a-8c1b-d16fb163193b)

**Comment by HTRamsey** [comment]
This is a question for Qt

**Comment by DonLakeFlyer** [comment]
You can't edit QGC Qml in the Qt Designer. You have to just use a text editor.
