### ISSUE TITLE
Fact dont work inside of the FlyDislpayView(Herelink)

### ISSUE THREAD

**Issue by JhonesYure** [mavlink/qgroundcontrol#11320]
I´m a problem with import FactSytem and FactControls to FlyDisplayView. I need control work parameters via FlyDisplayView, but i dont know why not work.
In top of the code are :
import QGroundControl.FactSystem 1.0
import QGroundControl.FactControls 1.0
and inside the Item have : FactPanelController { id: controller; }

But again, he not take the information of parameters or communication with parameters.

![image](https://github.com/mavlink/qgroundcontrol/assets/103959700/e5fd5e75-8e90-47a9-ac3c-cafc7a9d0225)

I created this item to show the value of the “RTL_ALT” parameters and it does not show

![image](https://github.com/mavlink/qgroundcontrol/assets/103959700/86e2450c-e62f-4395-86f0-a9a7785a6972)

**Comment by arnaudjuin** [comment]
```
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

import QGroundControl
import QGroundControl.Controls
import QGroundControl.Palette
import QGroundControl.ScreenTools

import Custom.Widgets

import QGroundControl
import QGroundControl.Vehicle
import QGroundControl.FactControls
import QGroundControl.SettingsManager
import QGroundControl.Controllers
import QGroundControl.FactSystem    1.0
import QGroundControl.FactControls  1.0
Item {
    property var _activeVehicle: QGroundControl.multiVehicleManager.activeVehicle
    property bool _initialDownloadComplete: _activeVehicle ? _activeVehicle.initialConnectComplete : true


    Loader {
        id: controllerLoader
        active: _initialDownloadComplete // This loader becomes active when _initialDownloadComplete is true
        sourceComponent: factPanelControllerComponent
    }

    Component {
        id: factPanelControllerComponent
        FactPanelController {
            // Initialize your FactPanelController here
        }
    }

    FactTextFieldSlider {
        id:factTravelHeight
        visible: false
        fact: controllerLoader.item.getParameterFact(-1, "SU_TRAVEL_ALT")
    }

```
That should help you !
