### ISSUE TITLE
Android Permissions

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11330]
Camera Permissions, etc.
W qt.bluetooth.android: : Permissions not authorized for a specified mode: QFlags<QBluetoothPermission::CommunicationMode>(Access)
W qt.bluetooth.android: : Local device initialize() failed due to missing permissions

**Comment by iamdeveloperpiyush** [comment]
import android.Manifest
import android.content.pm.PackageManager
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat

class MainActivity : AppCompatActivity() {

    private val CAMERA_PERMISSION_CODE = 100

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // Check camera permission
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA)
            != PackageManager.PERMISSION_GRANTED) {
            // Permission is not granted
            // Request the permission
            ActivityCompat.requestPermissions(this,
                arrayOf(Manifest.permission.CAMERA),
                CAMERA_PERMISSION_CODE)
        } else {
            // Permission has already been granted
            // You can proceed with using the camera
        }
    }

    // Handle the result of the permission request
    override fun onRequestPermissionsResult(requestCode: Int,
                                            permissions: Array<String>, grantResults: IntArray) {
        when (requestCode) {
            CAMERA_PERMISSION_CODE -> {
                // If request is cancelled, the result arrays are empty.
                if ((grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED)) {
                    // Permission granted
                    // You can proceed with using the camera
                } else {
                    // Permission denied
                    // You can handle this situation accordingly, for example, by showing a message to the user
                }
                return
            }
        }
    }
}
