### ISSUE TITLE
Issue with QGC guide (docs) webpage

### ISSUE THREAD

**Issue by omid-esrafilian** [mavlink/qgroundcontrol#11354]
@DonLakeFlyer 
It appears that there is an issue with the QGC guide (docs) webpage not loading correctly. 
Please check the link below:
https://docs.qgroundcontrol.com/master/en/qgc-user-guide/index.html

I have also provided a screenshot below:

![image](https://github.com/mavlink/qgroundcontrol/assets/115142498/97a94524-ab62-4ec2-bba2-97084f99e825)

**Comment by HTRamsey** [comment]
I think the docs workflow needs to be re-run after reverting my changes in #11348 which requires a new push. Or maybe we can change it such that manual runs cause the deploy job to be run too.

**Comment by HTRamsey** [comment]
Nevermind, it's not related to workflow. Maybe something with the docs changes in your PR I guess.

**Comment by omid-esrafilian** [comment]
@HTRamsey 
Thanks for the response. But it seems that the problem still persists.
I am not an expert in web development, but as an idea, shall we create a pull request with some minor changes in docs to find out what seems to be the problem, and if there are any compile errors pertaining to docs?

**Comment by HTRamsey** [comment]
I just built it locally on the latest master and it works fine, maybe something server side no idea

**Comment by omid-esrafilian** [comment]
@HTRamsey 
Great, thanks much.
