### ISSUE TITLE
The default cruise speed / flight speed for planning is way too high. Is it a way to config it?

### ISSUE THREAD

**Issue by changx03** [mavlink/qgroundcontrol#11378]
The default speed for planning is set to the maximum speed that is allowed to input (15 M/s or 54 KM/h). 
This is way too high at almost any scenarios. 
Is there a way to set the default flight speed permanently?  It can be from the setting menu or load from an external config file?
Which part of the code actually set this value?

Thanks.

**Comment by changx03** [comment]
I figured out where to set the default value.
It's in `./src/Settings/App.SettingsGroup.json` -> `offlineEditingCruiseSpeed`.
This is way hidden than I expected.

**Comment by changx03** [comment]
I figured out where to set the default value.
It's in `./src/Settings/App.SettingsGroup.json` -> `offlineEditingCruiseSpeed`.
This is way hidden than I expected.

**Comment by DonLakeFlyer** [comment]
offlineEditingCruiseSpeed has nothing to do with the created Plan. It is only used to caculate the length of time for a mission. The actual flight speed for a mission is controlled by the firmware. Unless you specifically change it with an additional Change Speed mission item.
