### ISSUE TITLE
member access into perameter type

### ISSUE THREAD

**Issue by zerocool-z1** [mavlink/qgroundcontrol#11414]
i was trying a clean build but i got an error saying 

/Users/anshadlakha/qgroundcontrol/custom/src/AutoPilotPlugin/CustomAutoPilotPlugin.cc:38: error: member access into incomplete type 'ParameterManager'
/Users/anshadlakha/qgroundcontrol/custom/src/AutoPilotPlugin/CustomAutoPilotPlugin.cc:38:45: error: member access into incomplete type 'ParameterManager'
            if (_vehicle->parameterManager()->parametersReady()) {
                                            ^
/Users/anshadlakha/qgroundcontrol/src/Vehicle/Actuators/Common.h:22:7: note: forward declaration of 'ParameterManager'
class ParameterManager;
      ^

**Comment by zerocool-z1** [comment]
/Users/anshadlakha/qgroundcontrol/custom/src/AutoPilotPlugin/CustomAutoPilotPlugin.cc:38: error: member access into incomplete type 'ParameterManager'
/Users/anshadlakha/qgroundcontrol/custom/src/AutoPilotPlugin/CustomAutoPilotPlugin.cc:38:45: error: member access into incomplete type 'ParameterManager'
            if (_vehicle->parameterManager()->parametersReady()) {
                                            ^
/Users/anshadlakha/qgroundcontrol/src/Vehicle/Actuators/Common.h:22:7: note: forward declaration of 'ParameterManager'
class ParameterManager;
      ^

**Comment by HTRamsey** [comment]
just include ParameterManager.h

**Comment by zerocool-z1** [comment]
it is already included

**Comment by HTRamsey** [comment]
in CustomAutoPilotPlugin.cc?
