### ISSUE TITLE
Debug cmake builds are popping the notification of newer version of QGC available

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#11424]
Looks like regular dev builds are not defaulting to a daily build.

**Comment by HTRamsey** [comment]
The check for it is
```
if (!_runningUnitTests)
```
so doesn't that mean debug builds can pop the version notification as long as they aren't built with testing enabled?

**Comment by DonLakeFlyer** [comment]
Hmm, that's odd. I thought it was daily versus stable build based. No idea what changes to start popping this up. Does it happen when you run a debug build? Maybe I fetched tags down or something.

I'll change to make it stable only.
