### ISSUE TITLE
Conflict between QGC's "Geo" and the origional `GeographicLib` library

### ISSUE THREAD

**Issue by changx03** [mavlink/qgroundcontrol#11474]
I need to use the utility functions in the `GeographicLib` library. I imported it as a static library on Windows.
However, the code from `src/Geo` reimplements part of the GeographicLib library with many changes, e.g, replacing `Math::real` as `double`, etc.
As a result, when I build it from Qt Creator, the complier reports errors like these:

```
LNK2005: "public: static int __cdecl GeographicLib::Math::digits10(void)" (?digits10@Math@GeographicLib@@SAHXZ) already defined in GeographicLib.lib(Math.obj)
```

There are many of similar errors in `Math.hpp`. All files under `src/Geo` use the namespace as `GeographicLib` but don't implement all the functions.

The class I want to use is `GeographicLib::Geodesic`.  Is it a way to get around this?

Thanks.

**Comment by DonLakeFlyer** [comment]
Are you using the latest daily build and cmake? You should be able to tell cmake what version of the Geo library you want if you want a newer one that QGC is currently using. You shouldn't need to import Geo again as a separate library.

**Comment by HTRamsey** [comment]
Yeah, the update I just added in #[11466](https://github.com/mavlink/qgroundcontrol/pull/11466) should let you use whatever version you want now, or use a previously installed version.

**Comment by changx03** [comment]
I forked Stable 4.2. I noticed the conflict exits even in the Stable 4.4 branch. Is this a future release? Thanks.

**Comment by HTRamsey** [comment]
Yeah it's in the current development branch that will end up being v5.0

**Comment by HTRamsey** [comment]
I'm going to close this since it is already handled in the development branch.
