### ISSUE TITLE
can't open Design Window from QML file

### ISSUE THREAD

**Issue by josephchan0122** [mavlink/qgroundcontrol#11484]
I am trying to open the QML file from design viewer, but the below error was occured
Is it impossible to edit qml file?
thanks for any help
![image](https://github.com/mavlink/qgroundcontrol/assets/115542777/b284bbbb-8f83-429c-a5f5-5d80acb195cc)

**Comment by josephchan0122** [comment]
![image](https://github.com/mavlink/qgroundcontrol/assets/115542777/3a89b1ff-24a2-4511-a2e5-8b8fce0572f1)
in the text editor of BluetoothSettings.qml (for example), QGroundControl.Controls module not found like red mark

**Comment by DonLakeFlyer** [comment]
Using the Qt Designer is not supported

**Comment by josephchan0122** [comment]
Thanks
