### ISSUE TITLE
Not all COM-ports are available in QGC 4.3.0

### ISSUE THREAD

**Issue by Olexandros** [mavlink/qgroundcontrol#11500]
## Expected Behavior
All COM-ports available in Device Manager in Windows used to be available in QGC as well when a new Comm Link configuration is added. 

## Current Behavior
However, in version 4.3.0 some COM-ports are missing and it's impossible to add them in the Comm Link configuration. For example, I have radio links with 2 COM-ports on a single physical USB port. Both COM-ports used to be available to add as a Comm Link, yet only one is shown in the QGC now.
When the previous QGC version 4.2.9 is installed, all COM-ports are available again.

![image](https://github.com/mavlink/qgroundcontrol/assets/157721921/5452ae49-e6c1-4466-93e8-cb743c41953a)
![image](https://github.com/mavlink/qgroundcontrol/assets/157721921/bb8e09de-68a1-4488-a6cb-d862e832e0c1)

**Comment by codeceptsDE** [comment]
I think this is implemented here (line 306 in particular):
https://github.com/mavlink/qgroundcontrol/blob/2ab9e1259e3a38bd3411d8e2e3465960029878fa/src/Comms/QGCSerialPortInfo.cc#L295-L322

I consider this feature undesirable/broken.
I have a CubeOrange+ where Windows returns the two ports it exposes in the "wrong" order - Mavlink comes second. I think this is even independent of the COM numbers, but something internal. Just disregarding seems to me like a bad policy.

I had to "uninstall" the second COM device of the CubeOrange+, then QGC connected.

My preferred solution would be listing all ports - i.e. removing duplicate port detection entirely - and just writing out the port descriptions after the COM number in the dropdown.
