### ISSUE TITLE
Build is broken again

### ISSUE THREAD

**Issue by TishSerg** [mavlink/qgroundcontrol#11516]
## Expected Behavior
Successful build

## Current Behavior
Build failed

## Steps to Reproduce:
1. `git checkout master` (085d33f at the moment)
2. Try rebuild
3. See failed build
4. `git checkout 8f6f4c6`
5. Try rebuild
6. See failed build
7. `git checkout 35f8864`
8. Try rebuild
9. See successful build

## System Information
When posting bug reports, include the following information
- Operating System: Windows 11 23H2
- QGC Version: master
- QGC build: daily, self-built from source

## Detailed Description
The 8f6f4c6 commit to master have broken build for me. Latest working commit is 35f8864.
@HTRamsey that yours.

**Comment by HTRamsey** [comment]
We don't have a CI build that checks qmake anymore. I would recommend using cmake to avoid this

**Comment by TishSerg** [comment]
> I would recommend using cmake to avoid this.

I set up build environment according to official instructions. That use qmake.
How to make transition to cmake?
