### ISSUE TITLE
Vehicle Setup view blank / black

### ISSUE THREAD

**Issue by thomasgubler** [mavlink/qgroundcontrol#1152]
If I compile on arch linux from current master the setup view is empty. There is no change when I connect to a system.

I made a try to run git bisect but I came to no conclusion because some commits did not compile. If @DonLakeFlyer does not know of a direct reason for the problem I can give it another try.

![screenshot from 2014-12-27 00 28 52](https://cloud.githubusercontent.com/assets/1419479/5559876/872bc7c6-8d5f-11e4-83b1-e87b7362a683.png)

Console output

```
libpng warning: iCCP: known incorrect sRGB profile
Changed Link to: "ttyS0"
HOME SET TO:  47.3783 8.53878 1199.99
Attempting connection to something unknown with description: ""
Attempting connection to something unknown with description: "X"
create SerialLink  "" 57600 false false 8 1
m_portName  "ttyACM0"
ADD LINK
Attempting connection to something unknown with description: "X"
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Orphaned log file count 0
```

**Comment by jgoppert** [comment]
Just confirming that Ubuntu 14.04 with Qt54 has this same issue.  14.04 with Qt53 from this ppa works : https://launchpad.net/~beineri/+archive/ubuntu/opt-qt532-trusty

This is helpful if you want to build qgroundcontrol and run ROS on ubuntu easily since ROS doesn't officially support 14.10 yet.

**Comment by DonLakeFlyer** [comment]
FYI: There is a pull request in the queue which fixes this. Waiting till I get back in town to merge. You can build with that yourself if you need something right away

**Comment by chzw517** [comment]
Any good news? I used ubuntu15.04 alpha2 came with the same issue...no icons, but can respond to clicking...

**Comment by DonLakeFlyer** [comment]
You need to use the pull that is sitting in the queue. I'll have that in master mid next week.

**Comment by DonLakeFlyer** [comment]
Pull request is through. New daily builds are posted here: http://www.qgroundcontrol.org/downloads

**Comment by bansiesta** [comment]
Tested, works! Thanks, I guess @thomasgubler go ahead and close this.

**Comment by thomasgubler** [comment]
fixed in #1159

**Comment by jgoppert** [comment]
Reopened this, doesn't work reliably on Ubuntu 14.04 using my laptop and any Qt version. Will show up as black after parameters are loaded.

**Comment by jgoppert** [comment]
Since I think this might be graphics card related, here are my specs:
laptop: https://system76.com/laptops/gazelle
graphics card: intel hd4600

**Comment by DonLakeFlyer** [comment]
This is a different issue that the original one. This is caused by the Fact object being null. Some sort of connect/disconnect issue not handled correctly leaving a stale vehicle summary page open while parameters are unavailable. Either that or something wrong with the Fact system missing parameters when it shouldn't.

**Comment by jgoppert** [comment]
OK, I'll close.
