### ISSUE TITLE
Add Confirmation to Changing Flight Mode

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11547]
An accidental flight mode switch code be dangerous

**Comment by HTRamsey** [comment]
@DonLakeFlyer I think this is a good usecase for the [DelayButton](https://doc.qt.io/qt-6/qml-qtquick-controls-delaybutton.html). I can make an attempt and see what you think

**Comment by DonLakeFlyer** [comment]
This should use the same confirmation sliders as everything else for consistency.

**Comment by HTRamsey** [comment]
Just realized this is a duplicate of #10707
