### ISSUE TITLE
Container build error: "fuse: device not found"

### ISSUE THREAD

**Issue by clydemcqueen** [mavlink/qgroundcontrol#11565]
## Expected Behavior
Container build should succeed.

## Current Behavior
Container build mostly succeeds, but fails when creating the AppImage:

~~~
...
-- Up-to-date: /project/build/AppDir/usr/share/metainfo/org.mavlink.qgroundcontrol.metainfo.xml
-- Creating AppImage
fuse: device not found, try 'modprobe fuse' first
open dir error: No such file or directory
~~~

## Steps to Reproduce:

I used the [container build instructions](https://docs.qgroundcontrol.com/master/en/qgc-dev-guide/getting_started/container.html), slightly modified to match the latest Dockerfile name.

1. Build the container: `docker build --file ./deploy/docker/Dockerfile-build-ubuntu -t qgc-ubuntu-docker .`
2. Build QGC in the container: `docker run --rm -v ${PWD}:/project/source -v ${PWD}/build:/project/build qgc-ubuntu-docker`

## System Information
- Operating System: Ubuntu 22.04
- QGC Version: master (2ab9e125)
- QGC build: build from source
- Flight Controller: n/a
- Autopilot (with version): n/a

**Comment by HTRamsey** [comment]
Oh I remember coming across this. I think I have the solution in a branch somewhere but you have to add something to the command for a permission that's required. One of the Qt libraries made it required maybe? I'll get back to you on this.
