### ISSUE TITLE
Problem Building QGC in Windows

### ISSUE THREAD

**Issue by droneCrow** [mavlink/qgroundcontrol#11560]
I got this error when build the QGC for android app. i follow the instructions those are give in developer guide . please tell me how to fix this.

```:-1: error: No rule to make target 'C:\Users\damin\Desktop\QT\droneApp1.0\qgroundcontrol2\build\Android_Qt_6_6_3_Clang_armeabi_v7a-Debug\ANDROID_PACKAGE_SOURCE_DIR\AndroidManifest.xml', needed by 'libQGroundControl_armeabi-v7a.so'.  Stop.```

![github](https://github.com/mavlink/qgroundcontrol/assets/170395529/2fbd7d90-c1ff-457b-a99d-c841035124db)

**Comment by HTRamsey** [comment]
Check out #11169
