### ISSUE TITLE
Unable to build custom qgc

### ISSUE THREAD

**Issue by zerocool-z1** [mavlink/qgroundcontrol#11587]
i am unable to build custom qgc even after following each and every step in qgc developer guide. even the folder doesn't show in the qt, after renaming it to custom. 
<img width="1131" alt="Screenshot 2024-06-02 at 9 37 34 AM" src="https://github.com/mavlink/qgroundcontrol/assets/127855282/f70baf67-3712-4c64-bfb6-b6584ae287dd">

whenever i am trying to build for debugging it is only building the main qgc, not the custom one please help

doesit have to anything Cmakelists.txt?

i even tried change the value in that file, but i am always getting Qgc daily build..

**Comment by HTRamsey** [comment]
Custom Builds are the last part that needs to be updated for CMake.
Check out #11436

**Comment by zerocool-z1** [comment]
@HTRamsey can you please help me out on a VC or anydesk for the same?

**Comment by zerocool-z1** [comment]
i tried to include custom build definations instead of daily build in cmakelists.txt but got the following error

<img width="1131" alt="Screenshot 2024-06-02 at 12 25 48 PM" src="https://github.com/mavlink/qgroundcontrol/assets/127855282/b517a142-ad70-42d5-ac52-494e085e5df3">

**Comment by HTRamsey** [comment]
It's not going to work at all right now. CMake doesn't even have the custom build stuff linked. You'd have to use older qmake build in order to use custom plugins, or just directly edit source.

**Comment by bhargavi-26robotics** [comment]
i was unable to connect tot he Ardupilot sitl ,in custom it is only showing PX4 how to add ardu also in it ?
