### ISSUE TITLE
Selecting 'MapBox' Map provider not displaying 3d buildings

### ISSUE THREAD

**Issue by ashokbugude** [mavlink/qgroundcontrol#11610]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Please tell us what should happen as detailed as possible.

MapBox map should display 3d buildings

## Current Behavior
Please describe what happens instead of the expected behavior.
MapBox map is not displaying 3d buildings

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Customize the following map settings
Provider - MapBox
Type - Custom
Tokens -> Mapbox - pk.eyJ1IjoiYXNob2tidWd1ZGUtY29kdm8iLCJhIjoiY2x4YWYyaGR3MDN3ZTJsczN5NHoyZmtseCJ9.uPg7ST-wx2BNTCRitmDEWg
Account - ashokbugude-codvo
Map Style - clxbmwl1o00r001qqe5mq352f
Map url - https://api.mapbox.com/styles/v1/ashokbugude-codvo/clxbmwl1o00r001qqe5mq352f.html?title=view&access_token=pk.eyJ1IjoiYXNob2tidWd1ZGUtY29kdm8iLCJhIjoiY2x4YWYyaGR3MDN3ZTJsczN5NHoyZmtseCJ9.uPg7ST-wx2BNTCRitmDEWg&zoomwheel=true&fresh=true#15.48/40.744096/-73.988742/2.6/55

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14] - Sonoma 14.5
- QGC Version: [e.g. 3.4.4] 
- QGC build: [e.g., daily, stable, self-built from source, etc...] stable - v4.4.0
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.] 
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1] 

## Detailed Description
Provide further details about your issue/bug.
MapBox map is not displaying 3d buildings

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
<img width="1182" alt="image" src="https://github.com/mavlink/qgroundcontrol/assets/10016848/d4062c9f-21a4-49d1-9fd1-fdcae0a6c04e">

- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

Current map in GQC
<img width="1256" alt="image" src="https://github.com/mavlink/qgroundcontrol/assets/10016848/bb35a519-961f-4f0e-a6c2-4778acc9532b">

**Comment by HTRamsey** [comment]
@bkueng this would be related to my stuff. Previously it showed Bing as a back up if the API key was not entered or incorrect which seemed kinda misleading to me. Should I re-add that?

**Comment by ashokbugude** [comment]
@HTRamsey @bkueng @DonLakeFlyer I request you to kindly let me the location/screenshot where I am supposed to add the mapbox key as I could not find it.

**Comment by bkueng** [comment]
> Also @bkueng @DonLakeFlyer this reminds me of something related to my recent QtLocationPlugin stuff. Previously only VWorld showed Bing as a back up if the API key was not entered or incorrect which seemed kinda misleading to me. Should I re-add that? Seems like there should either be no backup or a common one, otherwise the user has no idea what maps they are actually using.

Personally I would not add a backup with the argument that if the user wanted a custom map, it's confusing if some other map is shown. Or at least show an error message.

**Comment by ashokbugude** [comment]
Able to see after zooming in more
