### ISSUE TITLE
QGC crashes when pressing Firmware Update

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1162]
If the Firmware Update button is pressed in the Vehicle Setup screen with no links or systems setup/connected, then QGC crashes hard. This button should be only be usable when systems are connected and active.

**Comment by Susurrus** [comment]
Also I believe this is a NULL-pointer exception from the stack trace.

**Comment by DonLakeFlyer** [comment]
Fixed. Firmware Upgrade should now work when disconnected.
