### ISSUE TITLE
Serial COM-ports are not available on QGC Android

### ISSUE THREAD

**Issue by Olexandros** [mavlink/qgroundcontrol#11649]
## Expected Behavior
If a device with Serial COM-ports is connected to Android device, then they should be available in QGC. 

## Current Behavior
When I connect a telemetry link or even Matek flight controller via USB their COM-ports are not available. Only when I plug in FTDI (UART to USB adapter) does QGC see COM-port, however, it is impossible to connect to it.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Connect the Matek Flight controller (or any other) or Telemetry radio link to the Android tablet or smartphone.
2. Open QGC app > Application settings > COM links > Add > Select "Type: Serial"
3. Check the "Serial Port" drop-down option > It says "None Available"
4. Try to plug in another device/flight controller and repeat the steps from above > Same reaction

## System Information
- Operating System: Android 9, Android 13
- QGC Version: 4.4.0 x32/x64, 4.2.3.3 x32, 4.2.9 x64
- QGC build: Stable .apk
- Flight Controller: Matek H743, Telemetry Radio link with 2 COM-ports on USB Type-C

## Detailed Description
Why is this the bug of QGC? Well, Mission planner can recognize all COM-ports alright. When I plug in FTDI I'm able to connect as well. 
However, when I plugged in the following devices neither COM-ports was recognized by QGC:
1. Siyi mk32: QGC v4.2.3.3 х32;  QGC v4.4.0 х32, QGC v4.2.0 х32. Devices were connected via USB 2.0 and USB Type-C.
2. Nokia C32: QGC v4.4.0 х64 ; QGC v4.2.9 х64. Connected via USB Type-C.

## Screenshots
![20240703_114601](https://github.com/mavlink/qgroundcontrol/assets/157721921/2a2c7d55-b36d-492d-b57a-70b9f98cff89)
![20240703_123622](https://github.com/mavlink/qgroundcontrol/assets/157721921/4233a548-9e8f-4de9-b27f-fdf1a5724b61)

**Comment by HTRamsey** [comment]
#11536 will fix that. The current android serial driver is very old and doesn't recognize many devices
