### ISSUE TITLE
No visible output in the live graph

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1165]
Neither the light or dark themes display data in the Analyze view.

**Comment by thomasgubler** [comment]
What system are you using? Did you try the ground time check box?

Works fine on latest master with arch linux.

**Comment by Susurrus** [comment]
I didn't try the groundtime checkbox. This should be something that is automatically detected since it should be pretty easy. Though I'm uncertain what would cause this to work normally. Regular SYSTEM_TIME messages? A reasonable timestamp in the time_usec field?

**Comment by Susurrus** [comment]
Checking the groundtime box works. Though this should really be automatically detected, but that's another issue.
