### ISSUE TITLE
Internal error in LinkManager.cc with Holybro F9P on Android

### ISSUE THREAD

**Issue by AntsSymphonie** [mavlink/qgroundcontrol#11677]
I hope this is not a bug and I'm simply stupid.

Connecting the Holybro F9P RTK to an Android device leads produces an internal error in the LinkManager.
![Screenshot_20240712-205231](https://github.com/user-attachments/assets/7acbc2a1-aa65-4dff-b97d-6ee6bb7c4d10)

Tested this on Android based transmitter and my phone. 
Same receiver works with windows.
![2024-07-12 20_55_06-QGroundControl](https://github.com/user-attachments/assets/fcbe2934-294f-48e2-9b92-04b4727942da)

**Comment by HTRamsey** [comment]
Is this v4.3?

**Comment by AntsSymphonie** [comment]
4.4.0 32bit on my phone. On the transmitter it is 4.2 I believe, but that is a custom build, so not so easy to change that's why I tried on my phone.

**Comment by HTRamsey** [comment]
[RTK is disabled for android on v4.4.0 and before](https://github.com/mavlink/qgroundcontrol/blob/08d6c050c2c22f9dea15944afa86fa0fc93544fc/src/comm/LinkManager.cc#L635)
