### ISSUE TITLE
Daily Android Build Link Returns Access Denied

### ISSUE THREAD

**Issue by ericjohnson97** [mavlink/qgroundcontrol#11679]
I would like to install the daily build for android.  The link to the following link for the x64 is listed, but returns access denied. 

link: 
https://d176tv9ibo4jno.cloudfront.net/builds/master/QGroundControl64.apk

docs page: 
https://docs.qgroundcontrol.com/Stable_V4.3/en/qgc-user-guide/releases/daily_builds.html

**Comment by HTRamsey** [comment]
I don't think the daily on the play store has been updated in a while. Best to download from this repo

**Comment by ericjohnson97** [comment]
can you get daily builds from this repo, or only releases?

**Comment by ericjohnson97** [comment]
looks like you can get them from the latest android github action 

https://github.com/mavlink/qgroundcontrol/actions/runs/9929355840

**Comment by DonLakeFlyer** [comment]
@mrpollo Any ideas here? The APKs are up on S3 but they don't seem to be on cloud front which the website link refers to.

**Comment by mrpollo** [comment]
This isnt a CloudFront issue, file names changed and docs didnt get updated.

This is what we have in S3. The docs are linking to the wrong file for linux, and we no longer carry 32 vs 64 bit Android images.

This link should work for the android daily downloads
https://d176tv9ibo4jno.cloudfront.net/builds/master/QGroundControl.apk

![Screenshot 2024-07-19 at 11 44 42 AM](https://github.com/user-attachments/assets/13136990-f06b-48d9-a889-d24ee9784d22)

**Comment by HTRamsey** [comment]
Fixed by #11690
