### ISSUE TITLE
GimbalController uses vehicle compId instead of gimbal compId

### ISSUE THREAD

**Issue by FrankvVeelen** [mavlink/qgroundcontrol#11686]
## Expected Behavior
All gimbal communication should be with the gimbal manager, hence should use gimbal component id (154 for gimbal 1)

## Current Behavior
Currently _vehicle->compId is used. This results in messages such as acquire control getting lost if the gimbal manager is not on the autopilot.
https://github.com/mavlink/qgroundcontrol/blob/08d6c050c2c22f9dea15944afa86fa0fc93544fc/src/Gimbal/GimbalController.cc#L577-L594

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Attach gimbal with integrated manager
2. Try acquiring control via QGC
3. 
## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 22.04
- QGC Version: 4.4.0
- QGC build: Stable
- Flight Controller: -
- Autopilot (with version): PX4 1.14

**Comment by julianoes** [comment]
Thanks for the issue! I disagree that it should be the gimbal component 154 explicitly but you are correct that it could be any component and not necessarily the autopilot.

Do you already have a fix locally and want to contribute a PR? Otherwise, I'll try to look into this at some point, likely next week, and include it in v4.4.1.

**Comment by FrankvVeelen** [comment]
I have a local fix where I hardcoded id=154, but I agree that it shouldn't be hardcoded at all. Unfortunately my understanding of the QGC source code is not that deep, but I can take a look. How would you propose to decide the component ID to use? Base it on the heartbeat with MAV_TYPE_GIMBAL with a fallback to the autopilot?

**Comment by julianoes** [comment]
I'm working on a fix. I'll let you know when you can test it.

**Comment by julianoes** [comment]
@FrankvVeelen I gave this a try. It would be great if you could test https://github.com/mavlink/qgroundcontrol/pull/11706.

**Comment by FrankvVeelen** [comment]
Yep, that works for me! Thanks for the quick patch! I can not test if it still works for autopilot-controlled gimbal managers tho.

**Comment by julianoes** [comment]
Should be fixed with v4.4.1.
