### ISSUE TITLE
Feasibility of Migrating QGC to Kotlin Framework

### ISSUE THREAD

**Issue by enordco** [mavlink/qgroundcontrol#11684]
Hi,
I'm exploring the possibility of migrating the existing QGroundControl (QGC) framework to **Kotlin**. I would like to know if anyone has attempted this before and if there are any documented experiences or best practices available. Specifically, I'm interested in understanding the feasibility of such a migration, any known challenges or limitations, and what key considerations and potential pitfalls I should be aware of during development.

Any guidance, tips, or resources you could provide would be greatly appreciated. 
@DonLakeFlyer

**Comment by HTRamsey** [comment]
https://youtu.be/nmvurCcsWos?t=907
