### ISSUE TITLE
Virtual joystick extends beyond screen boundaries, preventing throttle maximization

### ISSUE THREAD

**Issue by demirciAhmet** [mavlink/qgroundcontrol#11687]
## Expected Behavior
The virtual joystick should remain within the screen boundaries at all times. Users should be able to maximize the throttle without the joystick extending beyond the screen.

## Current Behavior
When the virtual joystick is moved towards the edges of the screen, it extends beyond the screen boundaries. As a result, users are unable to maximize the throttle.

## System Information
- Operating System: Pop_OS! 22.04
- QGC build:  self-built from master

## Log Files and Screenshots
![Screenshot from 2024-07-19 11-35-15](https://github.com/user-attachments/assets/a074ded7-3adb-4653-b18c-8dc87c729095)

## Possible Fix
The joystick should not re-center when it reaches the edge of the screen. Instead, it should stop at the screen boundary, allowing users to maximize the throttle without losing control.

**Comment by HTRamsey** [comment]
@DieBorr Would you want to look at this? I think this is what I noticed in #11590

**Comment by DieBorr** [comment]
> @DieBorr Would you want to look at this? I think this is what I noticed in #11590

Okay, no problem, I Will take a look as soon as I can, probably on this Monday I can take some time for this Issue. 👍
