### ISSUE TITLE
The link connection on the toolbar and actual status get out of sync

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1169]
The link connection UI in the status bar at the top gets out of sync with the actual link status and the link settings window very quickly. When the "Connect/Disconnect" button says "Connect", it should be green. When it says "Disconnect", it should be orange. This isn't the case.

**Comment by Susurrus** [comment]
This also applies to the Communications Console widget.

**Comment by DonLakeFlyer** [comment]
Is it just the color that gets out of whack? Or does the text get screwed up as well.

**Comment by Susurrus** [comment]
The text. The color doesn't seem to change anymore. It used to be orange when it said disconnect.

**Comment by Susurrus** [comment]
No longer since the new toolbar merge.
