### ISSUE TITLE
QGC does not send required joystick state (physical or virtual) for arming

### ISSUE THREAD

**Issue by kraln** [mavlink/qgroundcontrol#11709]
## Expected Behavior
QGroundControl, with a joystick connected, calibrated, and enabled, should send the neccesary mavlink commands to satisfy PX4's pre-flight requirements. When COM_RC_IN_MODE=1 (Joystick only) and with no RC or GPS, some flight modes, such as Manual, Stabilized, Altitude, etc. should be available can can be armed.

## Current Behavior
QGroundControl displays red/"Not Ready". Under Arming Check Report, "No manual control input" is highlighted Orange, with the advise to connect and enable stick input, or use autonomous mode. 

This does not change when using a physical joystick or the virtual joystick. 

## Steps to Reproduce:
1. Remove GPS and RC from a drone
2. Connect (via serial or udp) to the flight controller
3. Set COM_RC_IN_MODE=1 and enable a joystick in QGC
4. Observe "No manual control input" highlighted orange in the Arming Check Report

## System Information
The behavior is the same across Linux, MacOS, and Windows, as well as with 4.4.0 and previous releases (4.2.6)

Flight controller is PX4 compiled from a recent git (1f33abb4e9) for linux-aarch64

## Log Files and Screenshots
```
Sending Arming/Health Report (num events: 8, can_arm: 0x80013b80, can_run: 0x80013b80)
   Event 0x01d31bb9: No valid local position estimate
   Event 0x0198c273: No valid global position estimate
   Event 0x0105c2d9: No valid mission available
   Event 0x012f1dc7: No offboard signal
   Event 0x01013630: Home position not set
   Event 0x0106ed29: No manual control input

pxh> commander check
INFO  [commander] Preflight check: FAILED
pxh> Sending Arming/Health Report (num events: 8, can_arm: 0x80013b80, can_run: 0x80013b80)
   Event 0x01d31bb9: No valid local position estimate
   Event 0x0198c273: No valid global position estimate
   Event 0x0105c2d9: No valid mission available
   Event 0x012f1dc7: No offboard signal
   Event 0x01013630: Home position not set
   Event 0x0106ed29: No manual control input
commander status
INFO  [commander] Disarmed
INFO  [commander] navigation mode: Stabilized
INFO  [commander] user intended navigation mode: Stabilized
INFO  [commander] in failsafe: no
commander: cycle: 149667 events, 7037056us elapsed, 47.02us avg, min 18us max 527us 32.958us rms
commander: preflight check: 14969 events, 1565043us elapsed, 104.55us avg, min 63us max 312us 12.187us rms

pxh> ekf2 status

ekf2:0 EKF dt: 0.0101s, attitude: 1, local position: 0, global position: 0
ekf2: EKF update: 156212 events, 21606949us elapsed, 138.32us avg, min 85us max 374us 42.725us rms
ekf2: IMU message missed: 0 events

pxh> sensors status
selected gyro: 2517001 (0)
validator: best: 0, prev best: 0, failsafe: NO (0 events)
sensor #0, prio: 75, state: OK
    val:  -0.0057, lp:  -0.0002 mean dev:   0.0000 RMS:   0.0040 conf:   1.0000
    val:  -0.0037, lp:  -0.0005 mean dev:  -0.0000 RMS:   0.0016 conf:   1.0000
    val:   0.0003, lp:   0.0003 mean dev:  -0.0000 RMS:   0.0034 conf:   1.0000

selected accel: 2517001 (0)
validator: best: 0, prev best: 0, failsafe: NO (0 events)
sensor #0, prio: 75, state: OK
    val:  -0.2676, lp:  -0.2528 mean dev:  -0.0000 RMS:   0.0220 conf:   1.0000
    val:  -1.5941, lp:  -1.5559 mean dev:  -0.0001 RMS:   0.0213 conf:   1.0000
    val:  -9.6813, lp:  -9.6835 mean dev:   0.0000 RMS:   0.0195 conf:   1.0000

[vehicle_magnetometer] selected MAG: 592905 (0)
validator: best: 0, prev best: 0, failsafe: NO (0 events)
sensor #0, prio: 75, state: OK
    val:   0.0254, lp:   0.0284 mean dev:  -0.0000 RMS:   0.0090 conf:   1.0000
    val:   0.0896, lp:   0.0858 mean dev:  -0.0000 RMS:   0.0090 conf:   1.0000
    val:  -0.5316, lp:  -0.5329 mean dev:   0.0000 RMS:   0.0083 conf:   1.0000
MAG 592905 EN: 1, offset: [0.153 -0.084 -0.169], scale: [1.029 1.029 0.928], Ext ROT: 0

[vehicle_air_data] selected BARO: 12018441 (0)
validator: best: 0, prev best: 0, failsafe: NO (0 events)
sensor #0, prio: 75, state: OK
    val: 100504.1875, lp: 100503.9453 mean dev:  -0.0155 RMS:   0.6993 conf:   1.0000
    val:  34.0379, lp:  34.0683 mean dev:   0.0020 RMS:   0.0443 conf:   1.0000
    val:  68.5629, lp:  68.5879 mean dev:  -0.0062 RMS:   0.0587 conf:   1.0000
BARO 12018441 EN: 1, offset: 0.000, Ext

Airspeed status:
    no data

[vehicle_acceleration] selected sensor: 2517001, rate: 199.3 Hz, estimated bias: [-0.0015 0.0137 -0.0075]
ACC 2517001 EN: 1, offset: [0.122 -0.043 -0.079], scale: [1.000 1.000 1.000], Ext ROT: 0

[vehicle_angular_velocity] selected sensor: 2517001, rate: 199.3 Hz FIFO, estimated bias: [-0.00159 0.00025 0.00027]
GYRO 2517001 EN: 1, offset: [0.004 -0.005 -0.004], Ext ROT: 0
vehicle_angular_velocity: gyro filter: 302079 events, 2929486us elapsed, 9.70us avg, min 1us max 317us 4.203us rms
vehicle_angular_velocity: gyro filter reset: 1 events
vehicle_angular_velocity: gyro selection changed: 1 events

[vehicle_gps_position] selected GPS: 0


[vehicle_imu] 0 - Accel: 2517001, interval: 5054.4 us (SD 518.8 us), Gyro: 2517001, interval: 5054.4 us (SD 518.8 us)
vehicle_imu: accel data gap: 1 events
vehicle_imu: gyro data gap: 1 events
ACC 2517001 EN: 1, offset: [0.122 -0.043 -0.079], scale: [1.000 1.000 1.000], Ext ROT: 0
GYRO 2517001 EN: 1, offset: [0.004 -0.005 -0.004], Ext ROT: 0

```

QGC 4.4.0 (stable)
![2a9eacbe-7fc7-4bda-85af-8bbf18360c83](https://github.com/user-attachments/assets/897297bf-5583-48ab-8a84-cb89d61eaed4)

QGC 4.2.6 (old, but before some joystick reworking)
![c63dad45-3243-4926-b0e7-0eff17f58e43](https://github.com/user-attachments/assets/b47fbb35-ecfc-48fd-b12c-b36d95e16e26)

**Comment by DonLakeFlyer** [comment]
Turn on JoystickValuesLog logging and see if joystick info is being sent. 

https://docs.qgroundcontrol.com/master/en/qgc-user-guide/settings_view/console_logging.html

**Comment by DonLakeFlyer** [comment]
I tried latest daily and it's sending joystick values for me

**Comment by DonLakeFlyer** [comment]
Is that from daily? The line numbers look incorrect. Anyway on Daily that error won't prevent values being sent. I get it as well. Looks like your joystick isn't really set up correctly for some reason. It isn't sending data.

I'll fix the Qml problem, but I don't think that will fix your problem. It just affects visual display of deadband values on the cal screen.

**Comment by DonLakeFlyer** [comment]
re-calibrating the joystick works fine? It would be strange for cal to work but values not being sent. It's a similar code path.

**Comment by DonLakeFlyer** [comment]
Turn on VehicleLog and try again

**Comment by DonLakeFlyer** [comment]
Also try turning on the rest of the Joystick log things. See if anything strange goes by.

**Comment by DonLakeFlyer** [comment]
No the vehicle side don't really control anything here. I think maybe the calibration is wrong.

Turn on just JoystickLog. Then do a boot/connect and send the log for that. That should log cal values.

**Comment by DonLakeFlyer** [comment]
This was with a joystick enabled and JoyStickLog on? Hmm, didn't get what I want. Do that again, but re-calibrate the joystick this time. Need to see the cal values being saved.


I might need to make you a custom version of QGC for debugging to track this down...
