### ISSUE TITLE
QGC decodes video stream with errors

### ISSUE THREAD

**Issue by kingofsen** [mavlink/qgroundcontrol#11730]
When using rtsp stream to broadcast QGC4.0 or above, there is a problem that it cannot be played. It seems to be related to the version of Gstreamer.
![875DD546-547B-4587-B6ED-D077601A8E04](https://github.com/user-attachments/assets/5a798582-f68b-4b48-963a-6b3ded8d63c6)
![4317A930-7460-4c06-94A4-6D8FB1819A0F](https://github.com/user-attachments/assets/a44142e8-6d5f-48c4-b1f9-b73484de8519)

**Comment by HTRamsey** [comment]
Closing this in favor of several other existing issues, hopefully it is fixed in daily though
