### ISSUE TITLE
Win32 Application Error

### ISSUE THREAD

**Issue by robhens** [mavlink/qgroundcontrol#1175]
I have tried several times to download and install onto Windows XP (2 different machines and both stable and daily builds), but I continually get the error "Not A Valid WIN32 Application".....any ideas ?

**Comment by DonLakeFlyer** [comment]
The windows version will not work on Windows XP, only Vista or above. I believe there is a way to get it to work on XP but you'll have to research how (some sort of Visual Studio issue) and build your own version.
