### ISSUE TITLE
why I can't open the software after I download it? (windows win 7)

### ISSUE THREAD

**Issue by ericwang721** [mavlink/qgroundcontrol#1176]
why I can't open the software after I download it?my system is win 7, I download it in china(I am an Chinese) I want to use it with my drone. The thing I saw after I download and install it, is a lot of file that I can't open in a folder.

**Comment by Susurrus** [comment]
Did you clone this repository? You need to follow the build instructions as this is just the source code for the program. If you want the binaries, you'll find them on the [main download page](http://www.qgroundcontrol.org/downloads).
