### ISSUE TITLE
Chinese Translation mark error  中文翻译符号错误

### ISSUE THREAD

**Issue by Toufupi** [mavlink/qgroundcontrol#11798]
由于中文翻译文件中使用的符号错误导致使用问题（航点无法设定）

解决方案：
1. 替换所有中文逗号，为英文逗号,
2. 根据报错提示，修改其余的符号错误即可

detailed description will update soon

what's more in order to fix this bug ,should I directly deliver a PR or through crowding?
----

## Expected Behavior
Please tell us what should happen as detailed as possible.

## Current Behavior
Please describe what happens instead of the expected behavior.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.
4.
5.
6.

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]
- QGC Version: [e.g. 3.4.4]
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by gillamkid** [comment]
Made a PR to fix this: https://github.com/mavlink/qgroundcontrol/pull/11936
