### ISSUE TITLE
Video streaming seems not work in android qt6 qgc

### ISSUE THREAD

**Issue by uby56** [mavlink/qgroundcontrol#11817]
Hi I trying to build a custom qqc build for android but video streaming is not giving any output 
![WhatsApp Image 2024-08-29 at 11 53 37 AM](https://github.com/user-attachments/assets/ff72941a-4963-4745-97d6-b5e70b9f7728)

And i have followed the instruction for android build [here](https://github.com/mavlink/qgroundcontrol/tree/master/src/VideoManager/VideoReceiver/GStreamer)

Is their any other steps i need for android build

**Comment by HTRamsey** [comment]
That happens if gstreamer isn't linked correctly. Can you verify gstreamer is being found by looking at the cmake output?

**Comment by uby56** [comment]
Hi @HTRamsey i have check the cmake output where i getting some warning in gstream

Warning: QML import could not be resolved in any of the import paths: org.freedesktop.gstreamer.GLVideoItem
Warning: QML import could not be resolved in any of the import paths: ACME.VideoItem
Warning: QML import could not be resolved in any of the import paths: org.freedesktop.gstreamer.Qt6GLVideoItem

and i check the vedioReciver.pri file and correct the gstream version but it still not working

**Comment by uby56** [comment]
yes i am using master branch how can i add the gstreamer pkg currently I am using 1.24.7 or should i download a specific version for the qgc master build

**Comment by HTRamsey** [comment]
It should be automatically downloaded during the configure step with cmake. You can look at the CI workflow to double check you are doing it correctly: https://github.com/mavlink/qgroundcontrol/blob/master/.github/workflows/android-linux.yml

**Comment by uby56** [comment]
Hi @HTRamsey  I am building the project in my local windows machine. I don't now which file to check is it okay to change the .yml file
![Screenshot 2024-08-31 123239](https://github.com/user-attachments/assets/826eb1fb-7113-49ec-b947-dbf3a7c35687)
