### ISSUE TITLE
VideoReceiverLog: GStreamer error: Could not initialize window system

### ISSUE THREAD

**Issue by nested-slk** [mavlink/qgroundcontrol#11815]
## Expected Behavior
The app doesn't open the video stream if I build the app. On the daily version, video stream works.
![Screenshot from 2024-08-28 10-49-00](https://github.com/user-attachments/assets/a5d73abd-a764-40ed-84f7-bd3eccf44f14)

## Current Behavior
`VideoReceiverLog: GStreamer error: Could not initialize window system`

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Build from sources
2. Run gstreamer `gst-launch-1.0 --verbose     videotestsrc !     x264enc !     h264parse !     rtph264pay         config-interval=10         pt=96 !     udpsink         host=127.0.0.1         port=5600`
3. Run qgroundcontrol  

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 22.04, **Wayland**
- QGC Version: v4.3.0-816-g7c80109e0
- QGC build: self-built from source

## Detailed Description
I used this guide https://docs.qgroundcontrol.com/master/en/qgc-dev-guide/getting_started/
I tried disabling x11 macros in CMake, but it didn't help
![Screenshot from 2024-08-28 10-46-46](https://github.com/user-attachments/assets/016bfe2f-ec18-4266-bfce-778d94286ada)

## Log Files and Screenshots
```
qgc.qgcapplication: Settings location "/home/sky/.config/QGroundControl.org/QGroundControl Daily.ini" Is writable?: true
Filter rules "*Log.debug=false\nqgc.*.debug=false\nGStreamerLog.debug=true\nGStreamerAPILog.debug=true\nGStreamerAPILog.debug=true\nqt.qml.connections=false"
GStreamerLog: Failed to change ranking of feature. Featuer does not exist: bcmdec
MAVLinkLogManagerLog: MAVLink logs directory: "/home/sky/Documents/QGroundControl Daily/Logs"
VideoReceiverLog: GStreamer error: Could not initialize window system
VideoReceiverLog: GStreamer error: Could not initialize window system
qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.AccessDenied" "Geolocation disabled for UID 1000"
qgc.positionmanager.positionmanager: QGCPositionManager::_setPositionSource(QGCPositionManager::QGCPositionSource)::<lambda(QGeoPositionInfoSource::Error)> QGeoPositionInfoSource::AccessError
VideoReceiverLog: GStreamer error: Could not initialize window system
```

**Comment by HTRamsey** [comment]
So you're saying daily works but not when you build it yourself?

**Comment by nested-slk** [comment]
> So you're saying daily works but not when you build it yourself?

Yes, you are right.

**Comment by doquangquan93** [comment]
I have same problem :(

**Comment by HTRamsey** [comment]
Hoping to resolve with #11806

**Comment by doquangquan93** [comment]
> Hoping to resolve with #11806

That's great. It works perfectly . Thank so much
