### ISSUE TITLE
I can't add a fence in the Daily build, but it works correctly in v428

### ISSUE THREAD

**Issue by Drone-Lab** [mavlink/qgroundcontrol#11825]
## Expected Behavior
When I connect QGC with PX4 jmavsim and  try to add a fence on QGC, I find the buttonis gray and I can't click it.

![1 (2)](https://github.com/user-attachments/assets/7e8061a3-6c96-4af5-971f-dd6887e915dc)

**Comment by HTRamsey** [comment]
I don't personally have this problem nor do I see any obvious changes related to it from the daily but maybe @DonLakeFlyer has an idea

**Comment by DonLakeFlyer** [comment]
This works fine for me with MockLink. I can't test jmavsim on OSX. The code is as follows:
```
bool GeoFenceController::supported(void) const
{
    return (_managerVehicle->capabilityBits() & MAV_PROTOCOL_CAPABILITY_MISSION_FENCE) && (_managerVehicle->maxProtoVersion() >= 200);
}
```

My guess is that jmavsim is not running mavlink v2.
