### ISSUE TITLE
Pixhawk Autoconnect Causes Extreme Lag

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11849]
open failed "Permission error while locking the device" QSerialPort::PermissionError "CubePilot on ttyACM0 (AutoConnect)" autconnect: true
open failed "Permission error while locking the device" QSerialPort::PermissionError "CubePilot on ttyACM1 (AutoConnect)" autconnect: true

However connecting them manually does not cause this problem

**Comment by DonLakeFlyer** [comment]
IS auto connect broken somehow in that it is trying to open more than once?

**Comment by HTRamsey** [comment]
Yeah, it was a small thing in Link Manager that I will have addressed in my Serial Link Signals/Slots PR
