### ISSUE TITLE
Remove *selectedFilter* argument from File Dialogs

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#1185]
Given that it's not used, removing it from the QGXFileDialog file (static) functions. If you need to know what file type was selected, you can always:

```c++
QFileInfo fi(filename);
QString fileExtension(fi.suffix());
if (fileExtension == QString("foo")) {
    // do something
}
```

**Comment by dogmaphobic** [comment]
Bah! Created an issue as a (hard to die) habit. This could have gone straight to a PR...

**Comment by Susurrus** [comment]
Please put the text from your comment in your git commit. It'd be nice to have that info logged in the git history.

**Comment by dogmaphobic** [comment]
> Please put the text from your comment in your git commit. It'd be nice to have that info logged in the git history.

Which one ? :smile:
