### ISSUE TITLE
Both RTK and GPS Status Indicators are exactly the same

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11859]
I think maybe there should be some kind of difference between the two, or maybe you transform the GPS indicator image into the RTK indicator image when the RTK is connected

![Screenshot from 2024-09-08 15-29-58](https://github.com/user-attachments/assets/6491ed57-c760-4499-905e-1f6facc468d5)

![Screenshot from 2024-09-08 15-30-12](https://github.com/user-attachments/assets/3ce62f35-235b-445f-800e-3fc9b1c19c93)

**Comment by DonLakeFlyer** [comment]
Ah, that was something I forgot to get back to!
