### ISSUE TITLE
Takeoff Altitude cannot be lower than 10m

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#11864]
When triggering a takeoff command a slider appears to select the takeoff altitude.

## Expected Behavior
Selectable range should be \<Minimum Altitude\> to \<Maximum Altitude\> from Application Settings-Guided Command Settings

## Current Behavior
Selectable range is 10 to 120m.

## Steps to Reproduce:
Trigger takeoff command

## System Information
Windows 10
- QGC Version: 4.4.2
- QGC build: stable
- Flight Controller: SITL
- Autopilot (with version): Ardupilot Copter 4.5.6

## Log Files and Screenshots
![image](https://github.com/user-attachments/assets/d94127a2-0a3d-4a15-abe1-e0a2c1b468f2)

![image](https://github.com/user-attachments/assets/1c1e56e8-3b31-4434-a5b1-14a2b57d5e90)

**Comment by DonLakeFlyer** [comment]
There were a bunch of bugs here related to this.You should try a daily build to see if this has already been fixed.

**Comment by twistedwings** [comment]
yes, it's fixed in the daily.

**Comment by federicociresola** [comment]
When will the fix of this bunch of bugs be released in a new stable version?
