### ISSUE TITLE
QGC is unable to find SYS_HAS_NUM_ASPD parameter on PX4 (1.14.3)

### ISSUE THREAD

**Issue by trileis** [mavlink/qgroundcontrol#11872]
## Expected Behavior
No error displayed after firmware upgrade

## Current Behavior
A `SYS_HAS_NUM_ASPD` missing parameter is thrown (see screenshot in reproducer)

## Steps to Reproduce:
1. Flash FC with latest firmware version (1.14.3): ![flash](https://github.com/user-attachments/assets/4ee7a388-0a5e-49f6-936c-feec7d8273b8)
2. Go back to summary and get a popup with the error: 
![error](https://github.com/user-attachments/assets/0f2a64fc-10e3-4ca8-85a5-92350207c166)

## System Information
- Operating System: Windows10
- QGC Version: 4.4.2/4.4.1
- QGC build: stable
- Flight Controller: Pixhawk 6X
- Autopilot (with version): PX4 1.14.3

## Detailed Description
Apparently the parameter SYS_HAS_NUM_ASPD is not present on the PX4 firmware but regarding the version (1.14.3), it should be there. This parameter has been introduce in this [commit](https://github.com/PX4/PX4-Autopilot/pull/22510). So it should be there. I can't find it neither in "Parameter" QGC screen:
![parameters](https://github.com/user-attachments/assets/184d9b42-8eda-4c40-9b67-5d5b15dc9a8b)
I get the same error on QGC version 4.4.1.

**Comment by DonLakeFlyer** [comment]
You need to use a daily build to get the fix for this
