### ISSUE TITLE
battery status not refreshed

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#11873]
## Expected Behavior
battery status refreshed regularly

## Current Behavior
battery status refreshed only sporadically

## Steps to Reproduce:
Compare battery status with MAVLink message

## System Information
- Operating System: Windows 10
- QGC Version: 4.4.2
- QGC build: stable
- Flight Controller: Matek F405-CTR
- Autopilot (with version): Ardupilot Copter 4.5.6

## Log Files and Screenshots
![status](https://github.com/user-attachments/assets/118fdbcb-9874-4ad4-b71e-fc73fc31511c)

Log File
[2024-09-13 13-42-03.zip](https://github.com/user-attachments/files/16995940/2024-09-13.13-42-03.zip)

**Comment by DonLakeFlyer** [comment]
Battery status comes from the BATTERY_STATUS message not SYS_STATUS. Running into problems replaying blog. Looking at this right now. Can you double-check BATTERY_STATUS is up to date?

**Comment by DonLakeFlyer** [comment]
I replayed the log although SYS_STATUS streams the values BATTERY_STATUS seems to stop streaming values to QGC at some point. So this is a vehicle side problem, not QGC as far as I can tell.

**Comment by twistedwings** [comment]
yes, you are right. The BATTERY_STATUS stopped streaming for whatever reason.

**Comment by DonLakeFlyer** [comment]
Closing since not much QGC can do if telemetry is not up to date. Re-open is there is some proof that this is a QGC side problem.
