### ISSUE TITLE
can anyone give me a little changes in this code ? 

### ISSUE THREAD

**Issue by MAli104** [mavlink/qgroundcontrol#11898]
Hi , i want to add a little change in Qgroundcontrol. i tried to modify but i couldn't.  Anyone can help me to add a little change in Qgroundcontrol. contact me at alip51748@gmail.com.

**Comment by mrpollo** [comment]
If you have an issue or need help you should post a question. If you are looking to hire someone please use a job board, such as this one https://discuss.px4.io/c/dronecode/looking-for-devs/29

**Comment by MAli104** [comment]
Can you help me on this issue?
