### ISSUE TITLE
Switch LinechartWidget to deal with proper CSV files

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1190]
Have it save its logs in a proper comma-separate values file (with extension `.csv`). If the LinechartWidget does any loading, it should still allow for the old .log format as well as .csv files with non-comma separators. The QGCDataPlot2D widget already does that flexible loading, so just use that code for the LineChart widget as well if necessary.

**Comment by LorenzMeier** [comment]
Closing as stale.
