### ISSUE TITLE
[ Android ] QGC Occurring common android source build error，but still having problem solving it ，despite with online raised solutions

### ISSUE THREAD

**Issue by dannynfs** [mavlink/qgroundcontrol#11944]
Occurring common android source build error，but still having problem solving it ，despite with online raised solutions
Im running qgc stable 4.4/qt 5.15.0,android build and having following error
![螢幕擷取畫面 2024-09-24 093048](https://github.com/user-attachments/assets/e2a8f8b7-36b6-41d7-b304-cdb7dc8deea2)
the following is my android env settings
![螢幕擷取畫面 2024-09-24 092917](https://github.com/user-attachments/assets/1f380de7-1354-4aa8-a52d-dca5e4bd1b89)
![螢幕擷取畫面 2024-09-24 092845](https://github.com/user-attachments/assets/134cdd43-2c2b-4121-aabe-06ccd6fb054d)
By researching online i found that it usually happened because of gradle version incompatible with jdk version ，so two common method solving it is by upgrading the projects gradle version or degrade java jdk into jdk11，where i came across issues on attempting both methods

1.Upgrading the projects gradle version:
By modifying both "gradle-wrapper.properties" and "build.gradle"s gradle specification 
![螢幕擷取畫面 2024-09-24 093144](https://github.com/user-attachments/assets/1345da47-d8a3-4fb2-86a9-36661ea99d96)
![螢幕擷取畫面 2024-09-24 093648](https://github.com/user-attachments/assets/f27f3c9a-8c95-4ec5-9235-66f50e4d46d9)
but after running the project，the changes i made both went back to the original settings which is 5.6.4 in gradle wrapper.properties and 3.6.0 in the latter，don't know if there's any other file included in qgc stable 4.4 does that

2.degrading java jdk into jdk11
By attempting it this occurs
![螢幕擷取畫面 2024-09-24 094851](https://github.com/user-attachments/assets/516ec0df-3d45-4141-851e-6500ff7d6e1c)
![螢幕擷取畫面 2024-09-24 094901](https://github.com/user-attachments/assets/0b42e746-1790-4ec3-b58a-4b99dade1592)
![螢幕擷取畫面 2024-09-24 094918](https://github.com/user-attachments/assets/520ea780-cf9a-4fcb-a0b3-b4010ba288c1)
simply cant degrade to jdk11 

both issues have been searching online but no obvious solution found 
maybe some mighty heros could help me here

**Comment by HTRamsey** [comment]
#11907

**Comment by aibietdau** [comment]
> #11907
i tried but the result is not as i expected, if i use another jdk for v4.4 is it ok
