### ISSUE TITLE
Run fails on Android QT

### ISSUE THREAD

**Issue by antonymarion** [mavlink/qgroundcontrol#11949]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/support/support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Android Build over QT and windows should run

## Current Behavior
Build (compilation) is OK but when launched it fails

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Open QT
2. Compile for android
3. Error logs on Qt

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: [e.g. 3.4.4]
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/settings_view/console_logging.html)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by antonymarion** [comment]
![20240924_185039.jpg](https://github.com/user-attachments/assets/4b913329-ab3c-4f8d-99a0-cf37a857aabf)

**Comment by HTRamsey** [comment]
Version?

**Comment by antonymarion** [comment]
Last version : 4.4.2

**Comment by HTRamsey** [comment]
4.4.2 doesn't use Qt6 and also is better with qmake than cmake

**Comment by antonymarion** [comment]
Well thks for the reply, to save time I will use github actions CI where build are configured with yaml ;)
