### ISSUE TITLE
Simplify hold logic in the Communications Console

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1196]
Right now, clicking the Hold button stops displaying new data, but the UI updates the Auto-hold button to be active. It's unclear to me from this whether Hold actually does a proper hold or just an Auto-hold. Really there are 3 options for displaying the data: Hold, Auto-hold, No-hold. If we want to keep all 3 options, I suggest a dropdown instead with these 3 options and removing the existing button + checkbox UI that is currently there.

**Comment by LorenzMeier** [comment]
Console is gone.
