### ISSUE TITLE
[Bug] QGC not showing external mode from PX4

### ISSUE THREAD

**Issue by junwoo091400** [mavlink/qgroundcontrol#11996]
## Expected Behavior
QGC should show the name of the external mode "CustomMode" (in this example) supported by PX4 via it's [ROS2 Control interface](https://docs.px4.io/main/en/ros2/px4_ros2_control_interface.html). This feature was added in https://github.com/mavlink/qgroundcontrol/pull/10788.

## Current Behavior
The mode name doesn't show up in flight modes supported.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Install [QGC v4.4.2](https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.2)
2. Start PX4 SITL `make px4_sitl_default gz_x500`
3. Start MicroXRCE-DDS Agent `MicroXRCEAgent udp4 -p 8888`
4. Start ROS2 script `ros2 run custom_mode custom_mode`
5. Check QGC's listed supported modes

## System Information
* OS: Ubuntu 22.04.3 LTS
* PX4: [commit 8070c70](https://github.com/PX4/PX4-Autopilot/commit/8070c70)
* ROS2 program from https://github.com/ARK-Electronics/px4_ros2_examples_ws?tab=readme-ov-file

## Log Files and Screenshots
![image](https://github.com/user-attachments/assets/5080fa35-d8f8-41ca-ac6a-c3af0b8fab9b)

![image](https://github.com/user-attachments/assets/50f6cb05-626c-466f-9e76-43c5b578428a)

With the "StandardModes" for QGC Console log enabled, it didn't show anything. Only irrelevant errors:
![image](https://github.com/user-attachments/assets/8e4a0bba-ce28-472d-8ad7-875abc9c9f28)

**Comment by patrikpordi** [comment]
I face the same issue!

**Comment by DonLakeFlyer** [comment]
Can you try a daily build as well?

**Comment by patrikpordi** [comment]
It works on the daily build but based on the https://github.com/mavlink/qgroundcontrol/pull/10788 I assume it should work on the main as well? Do we misunderstand it?

**Comment by hamishwillee** [comment]
This _should_ work by requesting [AVAILABLE_MODES](https://mavlink.io/en/messages/development.html#AVAILABLE_MODES)  and then populating the UI appropriately. That message is in development.xml - does QGC import this for both main and daily builds?

**Comment by DonLakeFlyer** [comment]
@bkueng I assume this is all through the new mavlink flight mode stuff Beat added? Sorry I don't know much about that. Should that be working in Stable?

**Comment by patrikpordi** [comment]
It only works in daily build at the moment. Are you planning on adding it to the main anytime soon?

**Comment by bkueng** [comment]
> Should that be working in Stable?

It's disabled for releases as the messages are in `development.xml` and thus should not end up in releases. I think making it a runtime option (disabled by default for releases) would also be a possibility.
I don't know if or how that changed with the switch to the cmake build.

**Comment by DonLakeFlyer** [comment]
Ah, ok Thanks for the info Beat. So this is working as expected.
