### ISSUE TITLE
ADSB_Simulator.py Script Not Generating Vehicles on the Map

### ISSUE THREAD

**Issue by Paschalis** [mavlink/qgroundcontrol#12002]
## Expected Behavior  
Should generate ADS-B messages for aircraft, allowing them to appear on the map in QGroundControl.

![Screenshot from 2024-10-13 01-19-52](https://github.com/user-attachments/assets/2f311b4b-fccb-4043-bb69-59a1e690f294)

## Current Behavior  
When running the default version of `qgroundcontrol/test/ADSB/ADSB_Simulator.py`, no vehicles appear on the map despite the server running.

## Steps to Reproduce:  
1. Clone the QGroundControl repository.
2. Navigate to `qgroundcontrol/test/ADSB/`.
3. Run the ADSB simulator with the command:  
    ```bash
    python3 ADSB_Simulator.py
    ```
5. Open QGroundControl and connect to the ADS-B feed (default host: localhost and port: 30003).
6. Observe that no vehicles are displayed on the map.

## System Information
- Operating System: Ubuntu 24.04.1 LTS
- QGC Version: Daily Version

**Comment by HTRamsey** [comment]
I was just using that script for some unit tests when working on ADSB, it doesn't actually send enough data to currently display anything in QGC

**Comment by Paschalis** [comment]
Hi @HTRamsey,

Thank you for your feedback! I understand that the original script didn't send enough data for effective testing in QGroundControl. In this update, I've enhanced the script to generate and send sufficient ADS-B messages, which allows vehicles to be displayed correctly on the map.

This improvement is especially useful for users who may not have access to SDR dongle hardware, as it provides a way to simulate ADS-B data without needing **physical equipment**. It should facilitate easier testing and development in QGC.

**Comment by HTRamsey** [comment]
Nice, thanks for doing that

**Comment by DonLakeFlyer** [comment]
MockLinks already support ADSB vehicles for testing without ADSB hardware.

**Comment by Paschalis** [comment]
Thank you for the feedback, @DonLakeFlyer!

After your suggestion, I revisited the [Mock Link documentation](https://docs.qgroundcontrol.com/master/en/qgc-dev-guide/tools/mock_link.html#mock-link) in the QGroundControl Developer Guide. While testing, I observed that adding a PX4 or Generic Vehicle through Mock Link only creates a single ADS-B plane on the map. However, the behavior of this plane appears unusual—it moves erratically, *jumping back and forth between random points without smooth transitions*. Additionally, the heading seems "frozen" and doesn’t consistently align with the flight course, making it difficult to simulate realistic scenarios.

This is why I believe the updated `ADSB_Simulator.py` script in [PR #12003](https://github.com/mavlink/qgroundcontrol/pull/12003) can be valuable. It can provide more consistent and realistic flight paths, making it useful for debugging and **feature testing**.

**Comment by DonLakeFlyer** [comment]
So fix the ADSB support in MockLink to be better  instead of creating something which duplicates already existing functionality.

**Comment by DonLakeFlyer** [comment]
@HTRamsey @Paschalis Is there a reason why an external script would be better than the internal MockLink support? Don't want to have to manage things in two places. We should pick one. In general MockLink is the place to add useful testing oriented things so you don't need any hardware/sitl.

**Comment by Paschalis** [comment]
@DonLakeFlyer  I understand your concern about avoiding duplicate functionality. I wasn't aware that MockLink already supported ADSB vehicles when I initially worked on the `ADSB_Simulator.py` script. My main goal was to investigate and address the issue of ground speed showing as NaN knots on ADSB vehicles, and using the script helped me simulate ADSB data without needing to rely on my SDR dongle and dump1090 setup.

I would definitely prefer to improve the existing MockLink ADSB support, especially now that I understand its potential for testing without requiring hardware. It might take me a bit of time to implement those improvements. In the meantime, if it makes sense, merging this script update could serve as a useful temporary solution for anyone looking to simulate more consistent and realistic ADSB behavior.

**Comment by HTRamsey** [comment]
Personally I have no preference, I just didn't want to risk messing up mocklink in any way when I just wanted a quick adsb test. That script actually just came from chatgpt anyways.

**Comment by DonLakeFlyer** [comment]
Ok, let's move the better adsb script support into MockLink then. as the long term solution. I'll merge the script updates for now.
