### ISSUE TITLE
Send stream from camera to RTMP/RTSP server

### ISSUE THREAD

**Issue by antonymarion** [mavlink/qgroundcontrol#12014]
Hello,

Does the QGC API/Classes provide a way to redistribute stream from UAV's camera to a RTMP/RTSP server?

Regards,

**Comment by tranhien1612** [comment]
@antonymarion Did you do this problem?

**Comment by antonymarion** [comment]
@tranhien1612 Yes.

If you need any assistance/support on this feature you can book a meeting on the bottom page of https://corner-stone.ai/ "Réserver un créneau dans notre agenda"

Regards
Antony

**Comment by tranhien1612** [comment]
@antonymarion can you show you this feature?

**Comment by antonymarion** [comment]
Yes.

Please book a meeting in my agenda

**Comment by tranhien1612** [comment]
@antonymarion i think i don't enjoy your metting. Did you try it in android system and what version of QT are you using?. If possible can I have your source code?

**Comment by antonymarion** [comment]
I can provide you support as a paid service; Unfortunately I won't provide source code for this feature.
