### ISSUE TITLE
no instructive graphics shown during accelerometer calibration

### ISSUE THREAD

**Issue by DeepSOIC** [mavlink/qgroundcontrol#12021]
## Expected Behavior
After pressing "Accelerometer" in Sensors, a grid of tiles with airplanes at different rotations should appear.

## Current Behavior
Nothing appeared. The drone was beeping, so the calibration sequence has definitely been launched.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. connect to the drone via SiK radio
2. Vehicle Setup -> Sensors
3. press Accelerometer

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: daily v4.3.0-984-g13031c3f6 64-bit
- Flight Controller: CubeOrange+
- Autopilot (with version): PX4 [v1.15.0](https://github.com/PX4/PX4-Autopilot/releases/tag/v1.15.0), built from source

## Log Files and Screenshots
- QGC Console Logs:

```
[E] at :0 - "Invalid max value, name: "VTQ_TELEM_IDS_1"  type: 5  max: "4294967295"  error: "Value must be within 0 and 2147483647""
[E] at :0 - "Invalid value for bitmask, bit: 31"
[E] at :0 - "Invalid max value, name: "VTQ_TELEM_IDS_1"  type: 5  max: "4294967295"  error: "Value must be within 0 and 2147483647""
[E] at :0 - "Invalid value for bitmask, bit: 31"
[E] at :0 - "Invalid max value, name: "VTQ_TELEM_IDS_1"  type: 5  max: "4294967295"  error: "Value must be within 0 and 2147483647""
[E] at :0 - "Invalid value for bitmask, bit: 31"
[E] at :0 - "QWindowsWindow::setGeometry: Unable to set geometry 759x450+831+546 (frame: 781x506+820+501) on MainRootWindow_QMLTYPE_477/"" on "GPD1001H". Resulting geometry: 900x450+831+546 (frame: 922x506+820+501) margins: 11, 45, 11, 11 minimum size: 600x300 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=922, y=506)))"
[E] at :0 - "Invalid max value, name: "VTQ_TELEM_IDS_1"  type: 5  max: "4294967295"  error: "Value must be within 0 and 2147483647""
[E] at :0 - "Invalid value for bitmask, bit: 31"
[E] at :0 - "Unable to parse version info from file "https://api.github.com/repos/PX4/Firmware/releases""
[E] at :0 - "Locale  "en_DE"  not found in json"
[E] at :0 - "Locale  "en_DE"  not found in json"
[I] at :0 - "Attemping load from cache"
[I] at :0 - "Parameters loaded from cache C:/Users/Invendelirium/AppData/Roaming/QGroundControl.org/ParamCache/1_1.v2"
[E] at :0 - "Retrying to obtain clipboard."
```

- Screenshots of QGC to help identify the current issue/bug behavior.
![image](https://github.com/user-attachments/assets/7499945c-e1b9-429e-b03c-849811216765)

same setup but with old QGC:
![image](https://github.com/user-attachments/assets/a7f156ca-6679-4d94-852e-9b19821a8c54)

**Comment by DonLakeFlyer** [comment]
Fixed by #11990 and friends. Not merged yet
