### ISSUE TITLE
MainToolBar.qml

### ISSUE THREAD

**Issue by WST-100** [mavlink/qgroundcontrol#12025]
Why can't I find the MainToolBar.qml file when I try to use Qt6.6.3 for secondary development? Not even in github. But I see the developer guide clearly instructs this file to be used with MainRootWindow.qml
![image](https://github.com/user-attachments/assets/a97798cf-de18-4443-b4af-f7a4fab28e59)

**Comment by HTRamsey** [comment]
I believe it got turned into FlyViewToolBar & FlyViewToolBarIndicators

**Comment by WST-100** [comment]
Thank you very much, I will try again
