### ISSUE TITLE
Main interface

### ISSUE THREAD

**Issue by WST-100** [mavlink/qgroundcontrol#12030]
I noticed in the latest developer‘s guide that if you use native builds, you need to use Qt6.6.3. Now I have successfully run the code on my own computer(Windows) and generated QGroundControl.exe. 

I would like to ask if I want to do secondary development on the main interface, which qml or c++ files should I focus on?

[https://github.com/mavlink/qgroundcontrol/issues/12025](url)  I have asked about MainToolBar.qml a few days ago. Thank you very much for your answer. However, I found that these two files cannot meet my needs for the main interface, such as the position of the instrument panel at the bottom and the current version does not display the attitude by default.
![image](https://github.com/user-attachments/assets/1ed3aec5-d4f5-43ec-a036-e89898df3960)
![image](https://github.com/user-attachments/assets/11a8ced1-ffb6-4b5e-915d-429ede8a4e4c)
Now by default there is only the compass, and it is aligned with the instrument panel in the lower right corner.

**Comment by DonLakeFlyer** [comment]
The developer guide has some additional info: https://docs.qgroundcontrol.com/master/en/qgc-dev-guide/index.html

Also the default instrument panel indicator does should attitude. They are shown as bars which slide up/down, left/right around the compass circle. If the vehicle is level you won't see much.
