### ISSUE TITLE
RC Calibration Issue

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#12045]
Sometimes the Roll left doesn't register, and something similar happens with the joystick calibration occasionally too.

**Comment by DonLakeFlyer** [comment]
Only thing I can think of is that the stick is not moving far enough for it to recognize it as being moved enough to move on to next step.

Another thing is if the values are moving around to much. It never sees the stick settle so doesn't complete.

Turn on RadioComponentControllerLog and you should be able to see what is going on. 

I've never seen this repro for me. @HTRamsey Hopefully you can get a repro while logging.

**Comment by JulianSchliessus** [comment]
Hi,

I am encountering a similar problem when calibrating:
During the calibration process, the max roll command to the left is not getting captured and therefore I cannot finalize the calibration.

Hardware / Software:
**Device:** Pixhawk 4 with FMU v5 \
**OS:** Ubuntu 24.04.1 LTS \
**QGroundControl:** 4.4.2 \
**RC:** GRAUPNER MZ-12 PRO

I’m completing the following steps, as displayed by the yellow dots in the calibration window:
* throttle up
* throttle down
* yaw right
* yaw left
* roll right
* roll left
The roll command to the left is displayed through the yellow dot, but the calibration never continues.

I've attached a log only in mode [RadioComponentControllerLog](https://github.com/user-attachments/files/17573956/QGC.log) and one in [full log](https://github.com/user-attachments/files/17573957/QGC_full.log) mode.

In the log you can see the `RadioComponentControllerVerboseLog: Raw value 0` and `RadioComponentControllerVerboseLog: Raw value 9` change wich are the channels assigned for the roll command.

The center position of the roll stick leads to the following values:
* Channel 0: 1447
* Channel 9: 1518

When moving the roll stick to the right, the following values are captured:
* Channel 0: 915
* Channel 9: 2113

After that, when moving the roll stick to the left, the following values are captured:
* Channel 0: 2046
* Channel 9: 918

Still, the calibration process is stuck on demanding a roll-stick command to the left.

**Comment by HTRamsey** [comment]
Great thanks, we should be able to figure it out now

**Comment by DonLakeFlyer** [comment]
I'm confused you have two radio channels which represent roll?

**Comment by JulianSchliessus** [comment]
Yes, because I would like to transmit a clean and a trimmed roll command

**Comment by JulianSchliessus** [comment]
Okay thanks for pointing this out, but then I do not understand why the roll command to the right is accepted in the first place during calibration. (why is it stuck at the left roll-command?)
Is there a way to manually select/map the channels for the corresponding command-axis?
In my case I would like to only pass on the trimmed roll command for QGC and later on, the pixhawk should receive both channels for my custom firmware.

**Comment by DonLakeFlyer** [comment]
None of this really has much to do with QGC. Radio calibration just sets parameters on the vehicle which are associated with the firmware and RC channel setup. The whole dance you do with sticks is just determining the values for those parameters. You can manually set those parameters yourself to whatever you want. Or just change your radio to single channel per stick when you do that calibration. Then put it back to multi-channel afterwards to do your special thing.

Closing this issue. If you can repro cal getting stuck when there is only a single rc channel mapped to a stick I'll look again.
