### ISSUE TITLE
How to fix the error when using Qt 5.15 with JDK 11.0.25?

### ISSUE THREAD

**Issue by aibietdau** [mavlink/qgroundcontrol#12088]
I am using Qt version 5.15, and when installing devices for Android, I encounter an error and cannot install it. I am using JDK version 11.0.25. I have tried to find a solution but have not been able to. Please help me.
![Screenshot 2024-11-12 112608](https://github.com/user-attachments/assets/51de5b36-f4aa-477a-9c72-7b121044e1c5)

**Comment by HTRamsey** [comment]
You have to use the current beta2 for QtCreator 15.0.0.
14.0.2 has some issues

**Comment by aibietdau** [comment]
> You have to use the current beta2 for QtCreator 15.0.0. 14.0.2 has some issues

Thanks for your support, but I tried installing version 15.0.0 beta2 but still can't fix this error, do you have any other solutions?

**Comment by HTRamsey** [comment]
So you are unable to install like Platform SDK 34 or something?

**Comment by aibietdau** [comment]
> Vậy là bạn không thể cài đặt Platform SDK 34 hay gì đó phải không?
yes with jdk 11 i cant install any sdk when i click on set up sdk

**Comment by aibietdau** [comment]
> #11907

i tried but the result is not as i expected, if i use another jdk for stable_v4.4 is it ok, for example jdk17 version

**Comment by aibietdau** [comment]
> Sure, whatever ends up working. But you may want to change your NDK version as you should be using NDK 25
i thank you for the suggestion to solve the problem before, but after fixing the above error, there is a problem, that is i want to build for 32 bit version but i can't find armeabi_v7a, arm64_v8, please give me a suggestion
![Screenshot 2024-11-14 113103](https://github.com/user-attachments/assets/d5999797-d712-4341-8e6d-7f3f20b70314)
![Screenshot 2024-11-14 113143](https://github.com/user-attachments/assets/bb6a2b4e-1a91-4b0a-832e-f4a8ff5309a9)

**Comment by HTRamsey** [comment]
Yes, that is correct for Qt 5.15. The v7 and v8 targets are in Qt 6
