### ISSUE TITLE
Not all COM-ports are available in QGC 4.4.x

### ISSUE THREAD

**Issue by maxfinbow** [mavlink/qgroundcontrol#12097]
Tested connecting PC via usb to ardupilot flight controller on windows version of QGC and the exact same behaviour occured as detailed in #11500 
https://github.com/mavlink/qgroundcontrol/issues/11500

 which was supposedly fixed by #11731 , however, the fix does not seem to be present in current QGC builds (tested on 4.4.0 and 4.4.2)

**Comment by HTRamsey** [comment]
It's fixed in the daily build and probably won't be back ported to the old stable builds
