### ISSUE TITLE
Local 3D View Doesn't Update on Master

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#1209]
Local 3D view was updating here: https://github.com/jgoppert/qgroundcontrol/tree/stable-fix 
Which was stable + my patch to fix the widget update. Now in master the view is updating correctly as per my patch, but the MAV local positin/ attitude data is not updating. It also doesn't show a 3d model of the vehicle.

**Comment by LorenzMeier** [comment]
Got removed.
