### ISSUE TITLE
Cannot save selected airframe type on QgroundControl 

### ISSUE THREAD

**Issue by insomnia24** [mavlink/qgroundcontrol#12102]
Hi there,
 
 I have a problem with setting up with my Pixhawk 2.4.8.
I installed Qgrouncontrol and installing firmware with this application. And after start to setup with airframe type slection. 
I am select fixed wing airframe and click save and reboot. After device device reboot no selected any airframe. 

But when i tried to select any multicopter type eveything is good. 

İ wonder what is problem with that fixed wings 🗡️ 

Thanks for answer...

**Comment by dakejahl** [comment]
sounds like your board doesn't have fixed wing support built in, probably due to flash constraints
