### ISSUE TITLE
error cannot connect to gstreamer when using for android

### ISSUE THREAD

**Issue by aibietdau** [mavlink/qgroundcontrol#12103]
I use qt 5.15.2 for android and stable_v4.4, after doing the linking steps as instructed to be able to connect them together but the build system still can't find it, I need a solution to handle this case

![image](https://github.com/user-attachments/assets/639bd44c-2c86-4ed0-945b-8ac6b35c3a6b)
![image](https://github.com/user-attachments/assets/2a039c94-32c4-4536-a14a-e9aae62117c1)

**Comment by HTRamsey** [comment]
It needs to be 1.18.6

**Comment by lequann** [comment]
build được chưa bạn ơi !!!

**Comment by aibietdau** [comment]
> build được chưa bạn ơi !!!

tôi buuil được rồi

**Comment by lequann** [comment]
tui đang build trên qt6 mãi vẫn bị lỗi
