### ISSUE TITLE
QGC cannot connect at 115200 baud

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1212]
Been wasting the last week trying to connect to my board, but it turns out QGC won't connect at any baud rate besides the default 57600. This also applies to the databits and stopbits settings.

**Comment by Susurrus** [comment]
It looks like SerialLink's setBaudRateString() function is never called when changing the UI. See SerialConfigurationWindow.cc:128.

**Comment by Susurrus** [comment]
Alright, got it fixed and submitting a new PR soon.

**Comment by dogmaphobic** [comment]
There's more to it. It doesn't matter what you set, it will get replaced by the last saved settings. I'm working on the whole link configuration setup. In the mean time, just reset the settings.
