### ISSUE TITLE
QT5.15 For mac

### ISSUE THREAD

**Issue by highfreq** [mavlink/qgroundcontrol#12136]
Anybody knows how to get QT5.15 for Mac?

The online installer only shows QT6.

Thanks.

**Comment by HTRamsey** [comment]
You have to check archive in the installer 
![image](https://github.com/user-attachments/assets/57902359-b717-4a0c-8e4b-9f10a4374311)

**Comment by highfreq** [comment]
I did but on Mac it shows only starting from early QT6 versions, no QT5

**Comment by HTRamsey** [comment]
Oh I have no idea then. I suspect as extended support for Qt5 is ending they may be removing it from their servers.

**Comment by highfreq** [comment]
I read a bit around and looks like windows machies can see it but not mac.........

**Comment by HTRamsey** [comment]
I think there's a way to add custom servers to the installer tool, maybe you can find one with the old downloads

**Comment by HTRamsey** [comment]
I'm gonna close this, but I'll let you know when I make some progress on the video stuff
