### ISSUE TITLE
gst_element_factory_make('tee') failed

### ISSUE THREAD

**Issue by 50ke** [mavlink/qgroundcontrol#12133]
- OS: Windows10 + msvc2019 64 bit
- gstreamer: 1.18.6
- QT: 6.7.2

- I can compile and run the QGC source code normally, but when I input the RTSP stream media address, I get an error: gst_element_factory_make('tee') failed.

![image](https://github.com/user-attachments/assets/c6eefdac-75fe-4b73-9d53-7b1ae867a6e3)

**Comment by HTRamsey** [comment]
If this is the daily, you need a newer gstreamer version like 1.22

**Comment by IDSAutopilot** [comment]
@50ke were able to resolve this issue, If yes can you share on how you were able to resolve it. I am getting the same error as you had got.
