### ISSUE TITLE
Cannot open "qgroundcontrol-Stable_V4.4\build\Android_Qt_5_15_2_Clang_Multi_Abi-Debug\android-build\AndroidManifest.xml" when i build by cmaklists.txt or qml and in qml this error :-1: error: [Makefile:2501: arm64-v8a/qrc_qgroundcontrol.obj] Error 127

### ISSUE THREAD

**Issue by abualiali** [mavlink/qgroundcontrol#12134]
Please only ask questions related to source code.
- For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources
- If your question still isn't answered, please check the forums: https://discuss.px4.io/c/qgroundcontrol/15.
- If it is about Qt or any QGC dependencies, please refer to them instead.

**Comment by HTRamsey** [comment]
This is a known problem and you can search the issues and find some solutions

**Comment by HTRamsey** [comment]
check out #11352
