### ISSUE TITLE
Build failed because of missing include qapplicationstatic.h in MAVLinkProtocol 

### ISSUE THREAD

**Issue by vryabokon1705** [mavlink/qgroundcontrol#12154]
## Expected Behavior
We must be able to build QGC from sources master branch without issues 

## Current Behavior
Build failed with an error: ‘_mavlinkProtocol’ has not been declared

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Download current sources
2. Build it

## System Information
When posting bug reports, include the following information
 - Ubuntu 24.04
 - gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4)
- Qt 6.8.0
- QGC self-built from source

## Detailed Description
After the last update I cannot build QGC because of missing include qapplicationstatic.h in the MAVLinkProtocol class. After adding missing include I a able to build it.

## Log Files and Screenshots
/home/vsevolod/CLionProjects/qgroundcontrol/src/Comms/MAVLinkProtocol.cc:27:39: error: ‘_mavlinkProtocol’ has not been declared
   27 | Q_APPLICATION_STATIC(MAVLinkProtocol, _mavlinkProtocol);
      |                                       ^~~~~~~~~~~~~~~~
/home/vsevolod/CLionProjects/qgroundcontrol/src/Comms/MAVLinkProtocol.cc:27:56: error: expected constructor, destructor, or type conversion before ‘;’ token
   27 | Q_APPLICATION_STATIC(MAVLinkProtocol, _mavlinkProtocol);
      |                                                        ^
/home/vsevolod/CLionProjects/qgroundcontrol/src/Comms/MAVLinkProtocol.cc: In static member function ‘static MAVLinkProtocol* MAVLinkProtocol::instance()’:
/home/vsevolod/CLionProjects/qgroundcontrol/src/Comms/MAVLinkProtocol.cc:52:12: error: ‘_mavlinkProtocol’ was not declared in this scope; did you mean ‘MAVLinkProtocol’?
   52 |     return _mavlinkProtocol();
      |            ^~~~~~~~~~~~~~~~
      |            MAVLinkProtocol
gmake[3]: *** [src/Comms/CMakeFiles/Comms.dir/build.make:191: src/Comms/CMakeFiles/Comms.dir/MAVLinkProtocol.cc.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/Makefile2:3213: src/Comms/CMakeFiles/Comms.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1986: CMakeFiles/QGroundControl.dir/rule] Error 2
gmake: *** [Makefile:199: QGroundControl] Error 2

![Screenshot from 2024-11-28 23-09-52](https://github.com/user-attachments/assets/42c901ed-b07c-497b-81df-c1593bbf3853)

**Comment by HTRamsey** [comment]
resolved in #12149
