### ISSUE TITLE
fatal error: 'QtCore/qiodevice.h' file not found #include <QtCore/qiodevice.h>

### ISSUE THREAD

**Issue by abualiali** [mavlink/qgroundcontrol#12153]
Please only ask questions related to source code.
- For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources
- If your question still isn't answered, please check the forums: https://discuss.px4.io/c/qgroundcontrol/15.
- If it is about Qt or any QGC dependencies, please refer to them instead.

**Comment by HTRamsey** [comment]
I need more info to help
