### ISSUE TITLE
Latest Version Checker is Out of Date

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#12160]
https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGC.version.txt still points to 4.3 instead of 4.4.2
@DonLakeFlyer @mrpollo Somebody else will have to fix this I imagine

**Comment by DonLakeFlyer** [comment]
Yeah, I had asked @julianoes who has been managing the new 4.4 about this.

**Comment by DonLakeFlyer** [comment]
Done

**Comment by julianoes** [comment]
While you're at it, it could now probably go to v4.4.3. I'll see if I can update it.
