### ISSUE TITLE
messy code, terminal, nsh

### ISSUE THREAD

**Issue by chzw517** [mavlink/qgroundcontrol#1217]
![screenshot from 2015-02-08 22 55 54](https://cloud.githubusercontent.com/assets/10514887/6125079/8b882366-b14d-11e4-88de-c9fa92707b7d.png)

when i press the connect button it print out endless messy code... are there any one confront the same issue? how to solve?

**Comment by dogmaphobic** [comment]
@DonLakeFlyer It reminds of a conversation about "Comm Terminal" visible to new users... :)

**Comment by DonLakeFlyer** [comment]
There is something going wrong with the terminal code in that it isn't switching over to the nsh shell. What  you are seeing are the mavlink messages going by. Terminal code should push out three carriage returns which should switch the link from mavlink to the shell.

**Comment by LorenzMeier** [comment]
The terminal and the communication console are duplicates of each other. I expect the console to be a bit more flexible and would suggest to keep it and remove the terminal. But its up to you.
