### ISSUE TITLE
Connection Lost alert when manually disconnected.

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#1219]
Creating an issue so it can be tracked.

Right now, when you manually hit the disconnect button, you get an audio warning about the link being lost and an ominous, red flashing warning message in the tool bar. If the connection was purposely closed (by hitting the *Disconnect* button), does it make sense have these dire warnings?

![screen shot 2015-02-10 at 2 24 08 pm](https://cloud.githubusercontent.com/assets/749243/6134609/9e3ac634-b130-11e4-9368-bf1911790d2b.png)

**Comment by DonLakeFlyer** [comment]
This is tied up in the whole auto connect/disconnect on bad link serial code as well. QGC can't distinguish between the user disconnecting or the serial link code disconnecting because of a bad link. Hence one of the reason I want to get rid of the auto reconnect thing.
