### ISSUE TITLE
Airspeed Sensor Not Detectable in QGC 4.4.3

### ISSUE THREAD

**Issue by Filipe-Cavalheiro** [mavlink/qgroundcontrol#12228]
## Expected Behavior
The airspeed sensor should appear under the Sensors tab in QGroundControl (QGC) and be available for calibration.

## Current Behavior
- In QGC version 4.4.3, the airspeed sensor does not appear under the Sensors tab.
- Error displayed: Missing Params: SYS_HAS_NUM_ASPD.

## Steps to Reproduce:
1. Install and launch QGC version 4.4.3 on Ubuntu 22.04.
2. Connect to a Generic Standard Plane setup.
3. Navigate to the Sensors tab.

## System Information
- Operating System: Ubuntu 22.04
- QGC Version:  4.4.3
- QGC build: stable
- Flight Controller: Pixhawk 6c mini
- Autopilot (with version): PX4 1.14.3
-  Airspeed Sensor: Mateksys MS4525DO

## Detailed Description
The airspeed sensor was functioning as expected in QGC version 4.4.0, upon upgrading to QGC 4.4.3, the airspeed sensor no longer appears under Sensors, and the error Missing Params: SYS_HAS_NUM_ASPD is shown, the sensor is connected via an I2C port.

**Comment by DonLakeFlyer** [comment]
Should be fixed in daily builds
