### ISSUE TITLE
Add GPLv3 license in COPYING file

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#123]
MAVLink already does this for their LGPL license, and the same should be done for QGC but with the GPLv3 license. It should also be specified in the developer documentation and the README that contributed code should be under this same license, which I didn't find.

**Comment by Susurrus** [comment]
@LorenzMeier This is actually a pretty big deal from a legal standpoint. Should I add a GPLv3 license to this project?

**Comment by LorenzMeier** [comment]
Yes please. I think we're safe from a legal point of view, but it makes it just so much easier if its in one file.

**Comment by Susurrus** [comment]
Oh, looks like there is a license.txt file, but it's not all-caps like they normally are so I didn't see it. I'm going to assume that's fine.
