### ISSUE TITLE
Remove inappropriate relative includes

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1236]
Follow-on to #1233 where a search for other instances of this (`grep "\"\.\." --exclude=*.ui src -r`) shows the problem in other files:

src/ui/map/MAV2DIcon.h:#include "../../libs/opmapcontrol/opmapcontrol.h"
src/ui/map/QGCMapWidget.h:#include "../../../libs/opmapcontrol/opmapcontrol.h"
src/ui/map3D/Pixhawk3DWidget.cc:#include "../MainWindow.h"
src/ui/XbeeConfigurationWindow.h:#include "../comm/HexSpinBox.h"

**Comment by DonLakeFlyer** [comment]
Fixed
