### ISSUE TITLE
System messages to users are not visible in a meaningful fashion

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1237]
Both PX4 and APM report status via MAVLink text messages to the user. The implementation is here:
https://github.com/mavlink/qgroundcontrol/blob/master/src/ui/uas/QGCMessageView.cc

It is displayed on Fly -> Info View -> Messages tab:
![schnappschuss 2015-02-14 21 40 46](https://cloud.githubusercontent.com/assets/1208119/6200967/28d240e2-b492-11e4-9ab9-244784ce8fd4.png)

These messages are really important in particular if the system configuration is off. It would be great to have this reworked - I wouldn't advise any modal dialogs, but very visible notifications e.g. in the status bar showing the last message and allowing to expand to see the full log.

**Comment by Susurrus** [comment]
They are shown in the top statusbar. What more were you thinking?
