### ISSUE TITLE
Correctly handle new CAL_MAG#_ROT parameters

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#1244]
If CAL_MAG#_ROT < 0 then it is either an internal mag or mag is no installed. Otherwise a rotation UI for that mag must be shown. If CAL_MAG0_ROT parameter does not exist, then fall back to a single SENS_MAG_ROT setting.

**Comment by LorenzMeier** [comment]
Fixed.
