### ISSUE TITLE
Rename "Connect" button on toolbar to "Open"

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1246]
The opposite would now be "Closed" instead of "Disconnect". These are both shorter words in English and also make more sense since the ManageLinks option is in the toolbar.

**Comment by DonLakeFlyer** [comment]
Connect and Disconnect still make more sense to me.

**Comment by DonLakeFlyer** [comment]
Gus is reworking toolbar for better real estate. No need to cut letters.
