### ISSUE TITLE
Deleting a UAS in the UASView after disconnecting crashes QGC

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1255]
Maybe remove the right-click "Delete" option should be removed? I know there has been some action to not allow removing UASes.

Setting this to important since it's a crasher, at least on x64 Linux.

**Comment by DonLakeFlyer** [comment]
This is more cross-thread object deleted signaling problems.

**Comment by DonLakeFlyer** [comment]
Fixed
