### ISSUE TITLE
cann't run in my computer

### ISSUE THREAD

**Issue by YuTingLiu** [mavlink/qgroundcontrol#1257]
issue:this is not a valiable win32 progress.

**Comment by YuTingLiu** [comment]
这不是个有效的WIN32程序

**Comment by DonLakeFlyer** [comment]
Are  you running Windows XP? The builds available through download will not run on Windows XP. I believe there is a way to build Windows XP versions yourself using VS 2013 but you'll have to research that yourself to find out how to do it. It is a VS 2013 issue.

**Comment by YuTingLiu** [comment]
Thanks,you are right,i will try your suggesion later.anyway,I will change my system.
