### ISSUE TITLE
QGCButton hover state doesn't always clear correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#1270]
If the button is right next to the edge of a QQuickWidget you can move the mouse out of the widget and hover will still be set. Also in Firmware Upgrade when you click Upgrade it gets stuck in hover even after you answer Yes/No to the warning dialog. Will need to implement some sort of timer check to fix this since Qt Hover support is so broken.

**Comment by LorenzMeier** [comment]
Fixed.
