### ISSUE TITLE
Safety config

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1273]
@dogmaphobic This feedback might be obsolete, but maybe it helps with the graphical config anyway (you got the tree icon via email?).

![2015-02-26 01 17 07 pm](https://cloud.githubusercontent.com/assets/1208119/6391802/5ed73afe-bdba-11e4-84db-2041279feadb.png)

**Comment by DonLakeFlyer** [comment]
Gus is grinding on toolbar. I have it on my list to add the new visuals. The checkbox disabling the entry field does work. There is a bug in the control visuals which are causing it to not gray out.

**Comment by DonLakeFlyer** [comment]
Fixed with new ui
