### ISSUE TITLE
Sensors config summary requires airspeed setup

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1274]
Airspeed is only needed on planes - I wasn't sure what the right architectural choice is to do this properly within the Fact System, so I decided to just provide feedback instead. This shows a multicopter config where airspeed is listed, but the multicopter doesn't have this sensor.

![2015-02-26 01 24 39 pm](https://cloud.githubusercontent.com/assets/1208119/6391855/18a33a8c-bdbb-11e4-8c14-4f5b7a5a4a5f.png)

**Comment by DonLakeFlyer** [comment]
Fixed
