### ISSUE TITLE
bad path in ubuntu trusty PPA

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1291]
W: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt541-trusty/ubuntu/dists/utopic/main/binary-amd64/Packages 404 Not Found

correct path is http://ppa.launchpad.net/beineri/opt-qt541-trusty/ubuntu/dists/trusty/main/binary-amd64/

**Comment by DonLakeFlyer** [comment]
Where are you seeing this as wrong. README lists ppa as just `ppa:beineri/opt-qt54-trusty`

**Comment by kd0aij** [comment]
I followed the Linux build instructions for Ubuntu;
sudo add-apt-repository ppa:beineri/opt-qt541-trusty
(ppa:beineri/opt-qt54-trusty didn't exist)

Then apt-get update returned a 404 error on a bad URL.
I was able to work around the problem by changing the distribution using
the Ubuntu GUI. Screenshot attached.


On Sun, Mar 1, 2015 at 10:30 AM, Don Gagne <notifications@github.com> wrote:

> Where are you seeing this as wrong. README lists ppa as just
> ppa:beineri/opt-qt54-trusty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/1291#issuecomment-76617292>
> .
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment]
BTW, the dist originally showed up as utopic instead of trusty


On Sun, Mar 1, 2015 at 11:09 AM, Mark Whitehorn <kd0aij@gmail.com> wrote:

> I followed the Linux build instructions for Ubuntu;
> sudo add-apt-repository ppa:beineri/opt-qt541-trusty
> (ppa:beineri/opt-qt54-trusty didn't exist)
>
> Then apt-get update returned a 404 error on a bad URL.
> I was able to work around the problem by changing the distribution using
> the Ubuntu GUI. Screenshot attached.
>
>
> On Sun, Mar 1, 2015 at 10:30 AM, Don Gagne <notifications@github.com>
> wrote:
>
>> Where are you seeing this as wrong. README lists ppa as just
>> ppa:beineri/opt-qt54-trusty
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mavlink/qgroundcontrol/issues/1291#issuecomment-76617292>
>> .
>>
>
>
>
> --
> Mark Whitehorn
> kd0aij@gmail.com
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by DonLakeFlyer** [comment]
Screenshots won't go through unless you put them in from GitHub.

**Comment by DonLakeFlyer** [comment]
Mark: I'm not much of a Linux person. I just kind of know enough to make myself dangerous. If you could update the README with instructions that work and put up a pull I sure would appreciate it.

**Comment by kd0aij** [comment]
created a PR
I know nothing about PPA's, but I'm sure the owner would know how to fix the URL :)

**Comment by DonLakeFlyer** [comment]
Hopefully fixed now
