### ISSUE TITLE
Link errors after Visual Studio 2013 Build

### ISSUE THREAD

**Issue by antman1p** [mavlink/qgroundcontrol#1298]
I am getting 25 errors when I build the solution in VS 2013.  Can someone help me figure out how to fix this?  The errors all look similar to this:  
error LNK2019: unresolved external symbol __imp_glDrawPixels referenced in function "public: virtual void __cdecl CameraView::paintGL(void)" (?paintGL@CameraView@@UEAAXXZ)	D:\Documents\GitHub\mavlink\qgroundcontrol\CameraView.obj	qgroundcontrol

**Comment by DonLakeFlyer** [comment]
Can you move this to the QGroundControl google group discussion? Issues are for bugs only.
