### ISSUE TITLE
Text instructions / label during calibration

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1300]
The new calibration dialogs are not any more prominently displaying the text instructions. Is the intent to make these obsolete (which isn't quite there yet) or should this be added back?

**Comment by DonLakeFlyer** [comment]
Obsolete from an end user perspective. Although if calibration fails you are shown the calibration log. When you say "isn't quite there yet" are you talking about mag and airspeed. Or are you talking about something missing from gyro and accel? All the text instructions for those are turning into visual cues.
