### ISSUE TITLE
[new toolbar] Downarrow for message list is shown even when no messages are there

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1311]
I didn't realize what was going on until I realized it had no messages to display. I suggest not showing the downarrow or showing just a simple list saying "No messages" to clarify this for the user.

**Comment by dogmaphobic** [comment]
If the message count is 0, the entire control should not be visible. Are you saying it is visible with 0 messages?

**Comment by Susurrus** [comment]
Yep. It just shows the loudspeaker icon and nothing else in that control and the Info View's Messages tab shows nothing (just the Connect Link button as per #1276).
