### ISSUE TITLE
[new toolbar] Vehicle summary panes are unreadable on the light theme

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1336]
The yellow on peach coloring is very low contrast and hard to read.

**Comment by DonLakeFlyer** [comment]
Light palette theme for Qml hasn't been completed yet.

**Comment by Susurrus** [comment]
Ahh, sorry. I thought this part had been completed.

**Comment by DonLakeFlyer** [comment]
Still good to track anyway. I need to ping the designers again for the palette.

**Comment by DonLakeFlyer** [comment]
Can you take a look to see what you think with the new master. Should be in a workable state now.
