### ISSUE TITLE
Radio config for SiK radios

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1338]
I'm starting to collect notes here. I don't think I'll have the bandwidth to do the full UI, but I will bring up the required Travis setup to provide binaries and I'm happy to help with the bootloader. The PX4 boot loaders and SiK bootloader are essentially the same implementation, so we should be able to get something together reasonably quick.

The configuration is even easier: Its just AT commands:
http://www.pixhawk.org/peripherals/radio-modems/start#dr_usb_radio

**Comment by yekailove** [comment]
Woo~How can I useing the 3DR Radio 915MHz communicate with QGroundControl?

**Comment by yekailove** [comment]
![tb12azugpxxxxb9xpxxxxxxxxxx_ 0-item_pic jpg_400x400](https://cloud.githubusercontent.com/assets/11613080/6820750/b2191b58-d30c-11e4-9c02-abb73665d870.jpg)
![tb2va2wbvxxxxxkxpxxxxxxxxxx_ 2228740069](https://cloud.githubusercontent.com/assets/11613080/6820752/b6a300c6-d30c-11e4-8d52-6da5580f7ae2.jpg)

**Comment by DonLakeFlyer** [comment]
Nothing special with QGC and the 3DR Radio. I’d go to the 3dr site and read up on how you use it with either mission planner or APM Planner. It’s pretty much the same in QGC. You’ll need to install the windows driver if you are using windows.

**Comment by nopeppermint** [comment]
@yekailove three sites about the 3DR Radio configuration:
- http://planner.ardupilot.com/wiki/other-project-and-common-topics/common-optional-hardware/common-telemetry-landingpage/common-3dr-radio-version-2/
- http://planner.ardupilot.com/wiki/other-project-and-common-topics/common-optional-hardware/common-telemetry-landingpage/common-3dr-radio-advanced-configuration-and-technical-information/
- http://planner.ardupilot.com/wiki/other-project-and-common-topics/common-optional-hardware/common-telemetry-landingpage/common-3dr-radio-v1/

**Comment by LorenzMeier** [comment]
Closing as stale.
