### ISSUE TITLE
If a serial device does not exist, more than one error can shown

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1343]
Should really only alert the user once.

To reproduce:
  1. Don't have your serial hardware device plugged in
  2. Hit "connect" on an existing connection
  3. QGC will throw two of the same errors, one right after the other

**Comment by Susurrus** [comment]
This actually only sometimes happens. Sometimes you'll get 1 message, but I've gotten up to 4. Very odd.

**Comment by DonLakeFlyer** [comment]
I believe this is gone now with the change to serial port connect failure code.
