### ISSUE TITLE
Map widget sometimes doesn't draw line segments between missions

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1351]
Usually fixing it requires me to repeatedly request the mission list on the "Edit Waypoints" tab of the "Mission Plan" widget.

**Comment by Susurrus** [comment]
Sometimes missions aren't displayed on the map view as well. I'm getting really odd behavior sometimes when switching from the map view to Analyze and back that sometimes waypoints and the track lines between them will go away.

**Comment by dogmaphobic** [comment]
Is this related to #1386?

**Comment by Susurrus** [comment]
I'm only using one UAS, so I don't believe so.
