### ISSUE TITLE
Make QGC less chatty during mode/state changes

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1353]
Right now when running QGC with audio, if the system goes through a bunch of state changes quickly, QGC will announce all of them, leaving the current state of the vessel unknown until all the speech has finished, which can be 10s of seconds later. I'd like to reduce the amount of things said to reduce the effective latency of knowing the current state. This is with the end goal of supporting an audio-only interface. Right now it'd be hard to exclusively use the audio to monitor the boat because of a) all of the messages and b) the latency in knowing the current state.

So to reduce the number of message, I'd like to propose that the last status/mode message sent be remembered and it only being transmit again if it's been >= 30s since the last time that message was sent. I've seen duplicate speech because while the mode or state changed, the actual output text didn't, so I'd get tons of the same message.

I originally had more plans for reducing the number of messages, but they would require large code changes which I don't have time to do right now. This is relatively straight-forward.

**Comment by LorenzMeier** [comment]
Closing as stale.
