### ISSUE TITLE
QGC doesn't shut down completely on Ubuntu 14.10

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1365]
After disconnecting from Pixhawk, canceling the save to logfile and File:Exit,
$ ps ax |grep qg
 5413 pts/1    Sl     0:35 /home/markw/git/kd0aij/qgroundcontrol/release/qgroundcontrol

Must kill that process manually.

**Comment by DonLakeFlyer** [comment]
Dup of Issue #1317
