### ISSUE TITLE
Can't add most message values to the Info View's Quick tab

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#1366]
This used to be possible, I think maybe adding the Fact system broke this? @DonLakeFlyer Can you confirm this?

I'd really like to show for example: crosstrack error, roll, and yaw and none of these are options. I know it *should* be possible.

**Comment by DonLakeFlyer** [comment]
No changes there that I know of.

**Comment by Susurrus** [comment]
I used to get a huge list of values, now I only see 2 different messages. Does this work for you?

**Comment by DonLakeFlyer** [comment]
Nope. List should come from mavlinkdecoder.

**Comment by dogmaphobic** [comment]
Is this what you're talking about?

![screen shot 2015-03-16 at 11 21 37 pm](https://cloud.githubusercontent.com/assets/749243/6680850/534253e0-cc33-11e4-8558-25cef896f2c1.png)

**Comment by DonLakeFlyer** [comment]
Yup. It should have values in there for each thing that mavlnkdecoder decodes and signals a value change on.

**Comment by Susurrus** [comment]
Exactly. I only see the HEARTBEAT and SYS_STATUS messages. I know this used to work.

**Comment by DonLakeFlyer** [comment]
Don't have GitHub right now. Can you mark this for stable v2.3? So it gets fixed before next stable

**Comment by dogmaphobic** [comment]
It's all there now (#1377)

**Comment by DonLakeFlyer** [comment]
Fixed
