### ISSUE TITLE
Small bug and a question in Core::run() of QMapwidget.

### ISSUE THREAD

**Issue by Nyaruko** [mavlink/qgroundcontrol#1383]
In the code of Core::run(),
if loaderLimit.tryAcquire(1, OPMaps::Instance()->Timeout) times out and return false.
then the tilesToload is never reduced after that.
Suggest to change it into something like:

		if (task.HasValue()) // What's the purpose of this if check???
			if (loaderLimit.tryAcquire(1, OPMaps::Instance()->Timeout))
                        {
                           ....
                        }
                        else
                        {
                                MtileToload.lock();
				--tilesToload;
				MtileToload.unlock();
				if (last)
				{
					OPMaps::Instance()->kiberCacheLock.lockForWrite();
					OPMaps::Instance()->TilesInMemory.RemoveMemoryOverload();
					OPMaps::Instance()->kiberCacheLock.unlock();

					MtileDrawingList.lock();
					{
						Matrix.ClearPointsNotIn(tileDrawingList);
					}
					MtileDrawingList.unlock();
					emit OnTileLoadComplete();
                        }

Furthermore, what's the purpose of the if check:if (task.HasValue()) ???

**Comment by DonLakeFlyer** [comment]
Just FYI: The map code actually comes from OpenPilot. So this was not written by QGC folks. For details of how it’s internals work OpenPilot would be a better place to ask. Although I”m sure the OP map code in QGC is way out of date with what they are running now.

**Comment by Nyaruko** [comment]
Thanks.
