### ISSUE TITLE
Check if the MIS_TAKEOFF_ALT is higher than waypoint alt

### ISSUE THREAD

**Issue by nimaaghli** [mavlink/qgroundcontrol#1385]
i just came back from test flight , MIS_TAKEOFF_ALT is 10 by default so when the way point is set lower than 10 things are going wrong drone goes hight to more than 20m (i just changed to manual it was going higher ) i think in such cases QGC shouldn’t run the mission , maybe that is why i was getting "takeoff to 10.00 meters above home" in red color

**Comment by DonLakeFlyer** [comment]
QGC doesn't validate missions. This is the firmwares job.
