### ISSUE TITLE
GUI changes while changing MAV in multi drone 

### ISSUE THREAD

**Issue by nimaaghli** [mavlink/qgroundcontrol#1386]
Hello, 
While having multi drone and clicking on them to control the GUI has some changes on menu the arrow shapes dissapear and show up again when mouse goes over them

**Comment by nimaaghli** [comment]
![screenshot from 2015-03-24 11 59 52](https://cloud.githubusercontent.com/assets/3833065/6806420/fd4c986e-d21e-11e4-9f5d-39183834adc0.png)
![screenshot from 2015-03-24 12 01 22](https://cloud.githubusercontent.com/assets/3833065/6806428/035c4c2c-d21f-11e4-80be-016c2ec13ac4.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Something for you Gus

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I was just talking about the toolbar button redraw problems for you to look at. Can you pull that out into a separate issue?

**Comment by dogmaphobic** [comment]
Duh... This entire time I was assuming it was an issue within the map view. It didn't even occur to me to look at the tool bar and see the chevron buttons are not there. It's the OpenGL Canvas issue (QtQuick inside a QWidget). I know how to get around it, I just need to be able to reproduce it. I will wait for your #1392 to get merged and I will take a look.
