### ISSUE TITLE
Crash in DebugConsole

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#1399]
Putting it down here before I forget.

To reproduce:

Start QGC and then plug in PX4 (USB). Click connect while the PX4 is booting. Nothing will happen as QGC is waiting for the bootloader to go away. Hit disconnect and then connect again. DebugConsole crashes in ```DebugConsole::updateTrafficMeasurements()``` as it tries to use a link pointer that is no longer valid.

That whole DebugConsole may need some rethinking as the UI is all broken and its functionality is dubious at best.

**Comment by LorenzMeier** [comment]
We need a text terminal for the system with basic VT100 capabilities. It's the main interface during development. The current implementation is indeed messed up, but it would be nice to get a proper console setup going.

**Comment by dogmaphobic** [comment]
I’m not dismissing the need, rather, the implementation. Not to mention the redundancy with the Terminal widget. It’s on my todo list...

g

**Comment by DonLakeFlyer** [comment]
We need one terminal to rule them all!

**Comment by DonLakeFlyer** [comment]
This is fixed now
