### ISSUE TITLE
Turn QT_FATAL_WARNINGS back on for OSX

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#1421]
Turned off due to this: http://www.qtcentre.org/threads/62133-QNetworkAccessManager-get-generates-SSL-qWarning-output-when-no-SSL-is-used?p=275327#post275327

**Comment by DonLakeFlyer** [comment]
From Qt 5.4.1 onwards you can disable the warning by e.g. setting
    QT_LOGGING_RULES=qt.network.ssl.warning=false
in the environment, or calling
    QLoggingCategory::setFilterRules("qt.network.ssl.warning=false");
in your main().

So need to wait or a bump to 5.4.1 to turn back on.

**Comment by DonLakeFlyer** [comment]
The above doesn't work.

**Comment by dagar** [comment]
travis-ci currently has QT_FATAL_WARNINGS=1 for osx debug builds

**Comment by DonLakeFlyer** [comment]
Thanks Daniel
