### ISSUE TITLE
Setup is refused even though only one system is connected

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1458]
This happens if only one system is connected. The issue is real, but I don't understand the mechanism behind it yet.

![airframe_choice_problem](https://cloud.githubusercontent.com/assets/1208119/7156047/da124654-e363-11e4-9b4e-3f78e6bcd7a5.png)

**Comment by LorenzMeier** [comment]
@tumbili For your reference.

**Comment by DonLakeFlyer** [comment]
It's even worse than that. Something recent is causing it to crash on OS X when you do this!

**Comment by DonLakeFlyer** [comment]
Looks like that crash is just when you are testing with MockLink. I can't repro on OSX. Have to try Ubuntu. Is this with a USB connection?

**Comment by tumbili** [comment]
@DonLakeFlyer Hi Don, yes this is with USB connection on Ubuntu 14.04. Even if I restart everything I always get the device files "ttyACM0" and "ttyACM1".

**Comment by DonLakeFlyer** [comment]
Fixed
