### ISSUE TITLE
Unable to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1469]
When I try to build from source I get the following error:
/usr/bin/ld: build-release/obj/QGCMAVLinkInspector.o(.text+0x8000000a903): reloc against `.LC252': error 2
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[1]: *** [release/qgroundcontrol] Error 1
make: *** [sub-QGCApplication-pro-make_first-ordered] Error 2

**Comment by tumbili** [comment]
I tried "make clean" and "git clean -dfx" but that didn't help

**Comment by DonLakeFlyer** [comment]
I don't think this is caused by QGC. Likely something on your box. A linux person may need to help you out. My Ubuntu builds are still working fine from master. Once just went through TeamCIty a few minutes ago.

**Comment by DonLakeFlyer** [comment]
What are you using for the qmake command line?

**Comment by dagar** [comment]
Current master is still building for me on Ubuntu 14.04 64bit with the qt54 ppa and gcc 4.8

/opt/qt54/bin/qmake
make -j4

**Comment by DonLakeFlyer** [comment]
You need to add -r to your qmake command line otherwise you may get incorrect makefiles.

**Comment by tumbili** [comment]
@DonLakeFlyer Thanks, it works with the "-r" option.
