### ISSUE TITLE
Waypoint planning for fixed wing - add descend/climb degree and distance

### ISSUE THREAD

**Issue by severinleuenberger** [mavlink/qgroundcontrol#1475]
When planning missions, one of the bigger issues, is the missing climb/descend degree and distance between waypoints. I was flying with 2 military pilots for their bachelor thesis and they had a lot of difficulties by planning while missing those 2 informations. 

Maybe even the AZ (heading) would be great. But Distance and degree up or down are a must on the long term

Best regards, 
Severin 

![image](https://cloud.githubusercontent.com/assets/9945167/7214296/b2fda600-e5a5-11e4-9288-d8bd66f6b800.png)

**Comment by severinleuenberger** [comment]
We just finished 80 flights on operating for autolanding with 2 swiss military pilots. 
It was very difficult do plan operations without having the distance and the degrees of climb/descend to plan our mission. Please do not forget this enhancement. Would be a very important one for mission planning.

**Comment by severinleuenberger** [comment]
...if you have time to build on QGC, this enhancement would be ery helpflul for the users who plan missions.

**Comment by DonLakeFlyer** [comment]
Distance and Azimuth between waypoints is now there. Still need to add climb.

**Comment by DonLakeFlyer** [comment]
You now have distance, azimuth and altitude change from previous waypoint.
