### ISSUE TITLE
Create RSSI indicator somewhere.

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#1483]
Putting this here so I won't forget.

Add RSSI indicator somewhere in the UI. ToolBar?

**Comment by Susurrus** [comment]
Why not in the UAS list widget? RSSI is per connection not per vehicle, and that widget displays the separate connections.

**Comment by dogmaphobic** [comment]
Because 99.9% of the time you are flying one thing at a time. The indicator could be shown only for when only one connection is active (to avoid confusion). These indicators are all optional any way.

**Comment by DonLakeFlyer** [comment]
I say toolbar as well. It's critical information and you ant it all the time even if you aren't using a widget.

**Comment by LorenzMeier** [comment]
Implemented, thanks!
