### ISSUE TITLE
Allow user to get access SD card through QGC software

### ISSUE THREAD

**Issue by FPVflyer** [mavlink/qgroundcontrol#1496]
Hi guys,
almost everyone of my drones PX4 equipped is quite hard to reach on the SD card port, would be very helpful to be able to manage the SD card without the need of remove it, would be possible to add a tool on the software to do that?

**Comment by DonLakeFlyer** [comment]
Onboard files widget allows you to download from the card as well as upload.

**Comment by severinleuenberger** [comment]
Fixed?

**Comment by DonLakeFlyer** [comment]
I'll need a little more detail if you want some sort of answer. Is something broken?

**Comment by severinleuenberger** [comment]
Ok, I see it is available but not completely fixed, 
Correct?
https://github.com/mavlink/qgroundcontrol/issues/1550#issuecomment-100682184

**Comment by DonLakeFlyer** [comment]
Still trying to nail down a repro.
