### ISSUE TITLE
Bad caption in setup summary

### ISSUE THREAD

**Issue by davidkraus13** [mavlink/qgroundcontrol#1499]
Hello
At QGC v2.3.0 stable, downloaded 2 days ago is bad caption at setup - summary - flight mode table. There is 2 times Position ctrl switch, second one should be Loiter.
![qgc_bad name](https://cloud.githubusercontent.com/assets/4030197/7314632/a667a790-ea66-11e4-93ea-578e791f495b.jpg)

**Comment by DonLakeFlyer** [comment]
Already fixed in daily builds
