### ISSUE TITLE
Toolbar: Need to show something sensible when no GPS is connected

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1500]
@dogmaphobic Right now the toolbar shows the raw -1 value when no GPS module is connected - standard aviation would be to cross out the GPS symbol if unavailable, not sure if that makes sense?

![schnappschuss 2015-04-25 09 19 13](https://cloud.githubusercontent.com/assets/1208119/7332026/50cd7352-eb2c-11e4-8719-7306df3deeec.png)

I'm referring to something like this, which is unambiguous:
![annotated_gps_symbol](https://cloud.githubusercontent.com/assets/1208119/7332029/859c326c-eb2c-11e4-8ecd-f8e895db0332.png)

**Comment by dogmaphobic** [comment]
It's a bug. It should be grey with no numbers next to it.
