### ISSUE TITLE
No setup options with worng io

### ISSUE THREAD

**Issue by boosfelm** [mavlink/qgroundcontrol#1528]
Hi
I tried to connect a new px4 firmware with a wrong io update to qgc. It is actually possible and in the fly tab I can even see the estimator running. However, it is impossible to see the full setup options and the hint to the parameter list is somewhat misleading.
Can I or @surberj help somehow?

![screen shot 2015-04-30 at 17 03 53](https://cloud.githubusercontent.com/assets/6023217/7415881/c4d5b98e-ef5b-11e4-8353-c16d5eb1f1f2.png)

**Comment by DonLakeFlyer** [comment]
There should be a progress indicator that shows up right below the toolbar when you connect to a vehicle. Did that start moving to the right and stop somewhere in the middle? Or did it never show up at all. Are you connecting over telemetry? The setup options will only show up after the full set of parameters is downloaded.

**Comment by boosfelm** [comment]
Hi @DonLakeFlyer 
The progress bar did not show up at all. I try telemetry and ftdi, both times the same behaviour. It really seems there is something wrong with the parameter, but I don't quiet get where it breaks.

**Comment by boosfelm** [comment]
I investigated a little further and it is really weird that all functionalities work except the setup tab. Any idea what is wrong?
![screen shot 2015-05-04 at 12 01 42](https://cloud.githubusercontent.com/assets/6023217/7451855/0ff6d496-f256-11e4-84d0-0b256eafaa19.png)
![screen shot 2015-05-04 at 12 01 56](https://cloud.githubusercontent.com/assets/6023217/7451856/12b066ca-f256-11e4-8ced-16c2a1dc249d.png)
![screen shot 2015-05-04 at 12 02 17](https://cloud.githubusercontent.com/assets/6023217/7451857/14ca5b46-f256-11e4-85bc-ba2194421df7.png)

**Comment by DonLakeFlyer** [comment]
> connect a new px4 firmware with a wrong io

Do you mean that the board is running the wrong firmware? If so what firmware is running?

**Comment by boosfelm** [comment]
I believe this was also due to a mess in the parameters, never happened again in the later qgc commit. Thanks for your help.
