### ISSUE TITLE
Export param list with comments from qgc

### ISSUE THREAD

**Issue by boosfelm** [mavlink/qgroundcontrol#1531]
It would be awesome if there would be a way to export param settings including the comments shown in qgc.

**Comment by DonLakeFlyer** [comment]
Interesting idea. Easy to do

**Comment by boosfelm** [comment]
can you point me to the place it should be implemented or are you just doing it?

**Comment by DonLakeFlyer** [comment]
src/FactSystem/ParameterLoader.cc - writeParameterToStream and readParametersFromSteam. You'll need to make sure you support both new and old formats. Also you'll need to strip carriage returns from fact->shortDescription(). Thanks for the help.

**Comment by LorenzMeier** [comment]
I presume you're familiar with this one?
https://pixhawk.org/firmware/parameters

**Comment by LorenzMeier** [comment]
Closing as stale.
