### ISSUE TITLE
More "direct" parameter editing

### ISSUE THREAD

**Issue by AndreasAntener** [mavlink/qgroundcontrol#1536]
Hey @DonLakeFlyer , the new parameter editor looks cool!

I have some suggestions as a heavy parameter changer:
- if I click on a parameter, it would be nice if the focus is already in the text field AND the text is selected. (the focus is there once you modified one parameter but is lost after doing other stuff)
- [ENTER] to save
- [ESC] to cancel

**Comment by DonLakeFlyer** [comment]
This is all different in the latest daily build. Try that out.

**Comment by AndreasAntener** [comment]
I just compiled it from master

**Comment by DonLakeFlyer** [comment]
Sorry I was thinking the wrong thing! I think this should all be doable.

**Comment by DonLakeFlyer** [comment]
Tried getting this to work but couldn't. I try again at some point.

**Comment by AndreasAntener** [comment]
Ok, thanks for fixing all the other issues :). I noticed that when I press ESC the window gets smaller and the info view disappears, strange..

**Comment by AndreasAntener** [comment]
@DonLakeFlyer Awesome! just saw in the user list that you were able to fix this :+1:
