### ISSUE TITLE
Cannot select airframe

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1543]
@DonLakeFlyer Maybe I'm just too stupid but I cannot select the airframes at the bottom because I cannot scroll down in the window. Have tried everything but I can't seem to manage.

**Comment by dogmaphobic** [comment]
Yes, I have the same issues on my tablet. Don is working on consolidating all those setup tools into one, consistent widget. Once that's done, you will be able to scroll down.

**Comment by tumbili** [comment]
@dogmaphobic Cool, sounds good.

**Comment by DonLakeFlyer** [comment]
Fixed

**Comment by tumbili** [comment]
@DonLakeFlyer Thanks Don, will try it tomorrow!
