### ISSUE TITLE
The selected parameter changes if you click somewhere in the info panel

### ISSUE THREAD

**Issue by AndreasAntener** [mavlink/qgroundcontrol#1544]
To clarify, if you select a parameter, the info panel opens. If you then click somewhere below or above the text field, it might select a different parameter. Seems that the click event is propagated to the list in the background.
It's actually cool that you can select a different parameter from the at this point greyed-out list ;), but if you miss the text field and don't notice it you might change the wrong parameter.

**Comment by DonLakeFlyer** [comment]
Fixed
