### ISSUE TITLE
Load custom widget file option no longer available

### ISSUE THREAD

**Issue by SimonWilks** [mavlink/qgroundcontrol#1546]
The custom widget loading menu item located before under ```Advanced / Tool Widgets / Load custom widget``` file seems to have been removed in the latest master (commit 277c1ae1cdf8d974598963ce14588e517d6efb3f). I'm running Ubuntu 14.10.

I'm assuming it has just gone on a brief vacation and will be back soon?

**Comment by LorenzMeier** [comment]
Its gone, but this one is here now:
https://github.com/mavlink/qgroundcontrol/pull/1524

The reason its gone is that it would be close to un-maintanable with the new technology, and the QML approach allows at the same time much better customisation options. It allows you to really build additional UI elements which blend into the main UI, and which can be contributed upstream.
