### ISSUE TITLE
(Mildly) Uncruft codebase before next stable / beta release

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1551]
I would propose to remove a few widgets which are fundamentally broken and continue to confuse users:

  * Info View: It never was properly finished and overlaying the same information on the map like @dogmaphobic did in the last iterations is much more useful. Classes to remove:   * https://github.com/mavlink/qgroundcontrol/blob/a5dc84680f871bcff37959819898930aa50e5c6f/src/ui/QGCTabbedInfoView.h
  * https://github.com/mavlink/qgroundcontrol/blob/a5dc84680f871bcff37959819898930aa50e5c6f/src/ui/uas/UASQuickView.h
  * https://github.com/mavlink/qgroundcontrol/blob/a4af4d4dd612d77dbb62d9f7c9af17388f946d80/src/ui/uas/UASMessageView.h

I have more of those, but this is the most visible one. Along with it we probably should hide the "Communication Console" widget. This one needs to be refactored to become a shell frontend using QML.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer In case you want to go ahead please feel free 8)

**Comment by DonLakeFlyer** [comment]
Should we toss both Communication Console and Terminal until we get a real "Terminal" widget? I don't think either of these are working correctly .

**Comment by LorenzMeier** [comment]
ok with me, yes.

**Comment by Susurrus** [comment]
The only nice thing about the Communication Console is that it shows the up and down stream bandwidth. Besides that, I've never either of them.

**Comment by severinleuenberger** [comment]
I have the communication console in my planning window per default. For me, the up/downstream are valuable and also to look up for error messages. Its easier than the drop down box in the list above. 
And no - there are not soo many bugs in it. I find it quite useful.

**Comment by DonLakeFlyer** [comment]
We should move the up/downstream stuff to somewhere else.

**Comment by DonLakeFlyer** [comment]
> And no - there are not soo many bugs in it. I find it quite useful.

You can communicate with nsh shell using it? That is what is is really meant for.

**Comment by severinleuenberger** [comment]
...nope. nsh commands doesnt work. Didnt know, that this should be possible. Would be great of course...

**Comment by DonLakeFlyer** [comment]
Done
