### ISSUE TITLE
Enable airspeed calibration for VTOL

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1556]
Not entirely sure if this is a QGroundControl or a Firmware problem.

**Comment by DonLakeFlyer** [comment]
Airspeed only shows up if vehicle is reported as MAV_TYPE_FIXED_WING. QGC doesn't understand VTOL as a fixed wing variant at this point. Needs to be fixed.

@LorenzMeier Seems like we need a better way to determine if airspeed cal should show up. Chasing changing MAV_TYPE's seems like a bad idea. Better to have some way to determine if an airspeed sensor is present.

**Comment by Susurrus** [comment]
Why not add it as a sensor to the `common.xml:MAV_SYS_STATUS_SENSOR` enum? Then you can just switch on whether that sensor is reported. It'd also be nice to make it generic, so it could also indicate if there's a waterspeed sensor for a boat. The `ABSOLUTE_PRESSURE` and `DIFFERENTIAL_PRESSURE` might also be useful here, but I don't know.

**Comment by LorenzMeier** [comment]
@Susurrus You have a really good point there. I need to think about how to do that properly.

**Comment by DonLakeFlyer** [comment]
For now I'll trigger off of the VTOL MAV_TYPE's. But still need a better way.

**Comment by DonLakeFlyer** [comment]
Done
