### ISSUE TITLE
Parameters should reset after cancellation

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1558]
If you change the value of a parameter but you  do not save and decide to cancel your operation it will appear like the parameter actually took the value. At the moment you have to press "get" to make the correct value appear again.

**Comment by DonLakeFlyer** [comment]
Can you give me exact steps using the latest daily? Working fine for me.

**Comment by tumbili** [comment]
@DonLakeFlyer Yes, will do, the issue was reported during the dev call. Will test tomorrow.

**Comment by tumbili** [comment]
@DonLakeFlyer You are right, I can't reproduce it, so closing.
