### ISSUE TITLE
add Auto WP similar to Mission Planner

### ISSUE THREAD

**Issue by nopeppermint** [mavlink/qgroundcontrol#1579]
Is it possible to add Auto WP to QGroundcontrol (specially drawing a circle with a given radius and a given number of waypoints) similar to Mission Planner?
![circle_waypoints](https://cloud.githubusercontent.com/assets/3403218/7665198/123d6958-fbad-11e4-8861-ff13e738f52c.PNG)

**Comment by LorenzMeier** [comment]
Closing as stale.
