### ISSUE TITLE
Unable to open and install Qgroundcontrol

### ISSUE THREAD

**Issue by mxgx12** [mavlink/qgroundcontrol#1580]
Trying to get Qgroundcontrol installed on my Windows 8 machine so I can bind a satellite receiver to PIxhawk. I keep getting " Windows can't open this file" ... "What program do you want to use to open?". I've done my best to read through previous issues but haven't found an answer. I'm completely new to this GCS so please forgive any ignorance. Any insight into getting the program installed and running will be awesome!

**Comment by dogmaphobic** [comment]
What exact file are you trying to open and where did you download it from?

**Comment by mxgx12** [comment]
I'm trying open the windows download file (v2.3.0) from Qgroundcontrol.org
 
Date: Sat, 16 May 2015 01:48:29 -0700

**Comment by dogmaphobic** [comment]
Hmmm... I downloaded it from here:

http://qgroundcontrol.s3.amazonaws.com/QGroundControl-Installer-Win32-Stable-V2.3.0.exe?dl=0

The installer run fine and installed it and when I launched it, it run just fine as well. Don't know what to say...

**Comment by mxgx12** [comment]
When I download the file, it is has a file type of "0[1] File". IS this normal? I believe this is what's causing problems.

**Comment by DonLakeFlyer** [comment]
> it is has a file type of "0[1] File"

Where are you seeing this?

**Comment by DonLakeFlyer** [comment]
The links on the wiki page were out of whack for Windows. Try it again and it should work.

**Comment by mxgx12** [comment]
Ok. Thanks. I got it to work. I appreciate your help. 

Matt McGowan
