### ISSUE TITLE
Display discharged mAh in flight perspective

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1581]
The discharged mAh is the best estimator for the remaining battery capacity. Since we don't know the full capacity we can't display percent reliably, but the user usually knows the battery size and can make use of the raw number very well.

The specs are here and you need PX4/Firmware master to get the info.
http://mavlink.org/messages/common#BATTERY_STATUS

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/commit/83fdb9931a0a9dd209566102bd873a274f4db6ed

**Comment by dogmaphobic** [comment]
First try in #1583
