### ISSUE TITLE
need Previous stable builds

### ISSUE THREAD

**Issue by birdiebertus** [mavlink/qgroundcontrol#1588]
hello please help i look for a Previous stable builds i want to instal it on windows 8 64 bit or on windows xp i try it whit version off website but do not work 
sorry for my bad engels
bertus from holland

**Comment by DonLakeFlyer** [comment]
There are no previous stable builds. If you detail why the current version doesn't work maybe we can fix it.

**Comment by birdiebertus** [comment]
Windows 8 whil not open the file

I don't no how to open the file

Gr Bertus

Verzonden van mijn HTC

----- Reply message -----
Van: "Don Gagne" <notifications@github.com>
Aan: "mavlink/qgroundcontrol" <qgroundcontrol@noreply.github.com>
CC: "bertus" <birdiebertus@hotmail.com>
Onderwerp: [qgroundcontrol] need Previous stable builds (#1588)
Datum: di, mei 19, 2015 18:10


There are no previous stable builds. If you detail why the current version doesn't work maybe we can fix it.

---

**Comment by DonLakeFlyer** [comment]
I can't help you if you don't provide me with any details! Details means:
- What exactly does windows say when you try to open the file?
- What is the name of the file you are trying to open?
- How are you trying to open the file? Command line? Double-click somewhere?

**Comment by birdiebertus** [comment]
Oké
THE file i try to open named qgroundcontrol-installer-win32-pixhawk


When i double click i get This
         
                                
 Sorry but my Engels is bad
Best bertus

**Comment by DonLakeFlyer** [comment]
I assume there was supposed to be an image there, but there is no image?

**Comment by birdiebertus** [comment]
Gr bertus

**Comment by birdiebertus** [comment]
I dont no why you dont get THE image 

Gr bertus

**Comment by birdiebertus** [comment]
Yello is it not posible to sent zip file whit instruktions i even want to pay for it 

Gr bertus

**Comment by DonLakeFlyer** [comment]
You can't attach files from an email. You need to do it directly from github. Below the comment section you'll see a link which you click on to attach an image.

**Comment by birdiebertus** [comment]
![image](https://cloud.githubusercontent.com/assets/12513690/7711014/216a81c8-fe68-11e4-96c8-861c9c5a4ed0.jpg)
![image](https://cloud.githubusercontent.com/assets/12513690/7711016/216b6d0e-fe68-11e4-835e-dd56c366b499.jpg)
![image](https://cloud.githubusercontent.com/assets/12513690/7711015/216afe78-fe68-11e4-98cd-6b44dde3441f.jpg)

**Comment by DonLakeFlyer** [comment]
Can you translate the message which is talking about SDL.DLL for me?

**Comment by LorenzMeier** [comment]
My dutch is a bit rusty, but its saying it can't find SDL.DLL and proposes to reinstall the software. Are you packaging that one? We're using it for joystick support (and our desire for joystick support is growing since we need it to make full use of the SITL capabilities - I will fix up that joystick PR).

**Comment by birdiebertus** [comment]
Program kan not be started it is misging SDL.DLL is missing from my computer system

**Comment by DonLakeFlyer** [comment]
SDL is supposed

**Comment by DonLakeFlyer** [comment]
AWS seems to have maybe changed something with how you link to downloads on Windows. The wiki links were out of whack. Can you try downloading a new version from the wiki? After it installs, if you still get the SDL.DLL error can you look in the c:\Program Files (x86)\qgroundcontrol directory and see if there is an SDL.DLL file in there?

**Comment by birdiebertus** [comment]
You meen download from qgroundcontrol site download section?

**Comment by DonLakeFlyer** [comment]
Yes

**Comment by birdiebertus** [comment]
It runs many thanks !!

**Comment by birdiebertus** [comment]
Hello I have a problem I try to install qgroundcontrol on xp olso it installs but when I try to open the program  I get this c:/program files/qgroundcontrol.exe is no vailid win32-application
I hope you want to help me


Gr Bertus

Verzonden van mijn HTC

----- Reply message -----
Van: "Don Gagne" <notifications@github.com>
Aan: "mavlink/qgroundcontrol" <qgroundcontrol@noreply.github.com>
CC: "bertus" <birdiebertus@hotmail.com>
Onderwerp: [qgroundcontrol] need Previous stable builds (#1588)
Datum: di, mei 19, 2015 18:10


Closed #1588.

---
Reply to this email directly or view it on GitHub:
https://github.com/mavlink/qgroundcontrol/issues/1588#event-308634095

**Comment by DonLakeFlyer** [comment]
QGC does not run on windows xp.

**Comment by birdiebertus** [comment]
Oke thanks

Gr Bertus

Verzonden van mijn HTC

----- Reply message -----
Van: "Don Gagne" <notifications@github.com>
Aan: "mavlink/qgroundcontrol" <qgroundcontrol@noreply.github.com>
CC: "bertus" <birdiebertus@hotmail.com>
Onderwerp: [qgroundcontrol] need Previous stable builds (#1588)
Datum: wo, mei 20, 2015 16:19


QGC does not run on windows xp.

> On May 20, 2015, at 12:43 AM, bertus <notifications@github.com> wrote:
>
>
> Hello I have a problem I try to install qgroundcontrol on xp olso it installs but when I try to open the program I get this c:/program files/qgroundcontrol.exe is no vailid win32-application
> I hope you want to help me
>
>
> Gr Bertus
>
> Verzonden van mijn HTC
>
> ----- Reply message -----
> Van: "Don Gagne" <notifications@github.com>
> Aan: "mavlink/qgroundcontrol" <qgroundcontrol@noreply.github.com>
> CC: "bertus" <birdiebertus@hotmail.com>
> Onderwerp: [qgroundcontrol] need Previous stable builds (#1588)
> Datum: di, mei 19, 2015 18:10
>
>
> Closed #1588.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mavlink/qgroundcontrol/issues/1588#event-308634095
> —
> Reply to this email directly or view it on GitHub <https://github.com/mavlink/qgroundcontrol/issues/1588#issuecomment-103797627>.
>



---
