### ISSUE TITLE
Onboard Files Critical error when indexing

### ISSUE THREAD

**Issue by Austriker** [mavlink/qgroundcontrol#1590]
I am trying to download files with onboard files widget. 
Got critical error with when trying to index files on the SD card because of hidden file from spolight.

![qgc](https://cloud.githubusercontent.com/assets/5080705/7722430/6101c238-fee0-11e4-9900-f619ef1552ed.png)

**Comment by LorenzMeier** [comment]
Is that with a QGC daily build? If not, try upgrading first.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer should we add a list configure or a list-all command so we can hide hidden files by default but still grant access if needed?

**Comment by Austriker** [comment]
It's a Daily Build from this morning.

**Comment by DonLakeFlyer** [comment]
The problem is that the list command never completes right? If so, the failure handling for failed opendir or readdir is likely not working correctly on the firmware side. Causing the QGC ftp state machine to get confused.

As far as showing  hidden files, seems like nuttx can't deal with them?

**Comment by DonLakeFlyer** [comment]
I see what's happening. It getting stuck in a loop. Not sure if FW or QGC at this point.

**Comment by Austriker** [comment]
Tested works fine still one error message but you can download files.
![capture d ecran 2015-05-25 a 14 42 36](https://cloud.githubusercontent.com/assets/5080705/7797430/542d7c72-02ec-11e5-9adf-8626bf760d3c.png)

**Comment by DonLakeFlyer** [comment]
You'll still get the errors since those are real. But you'll be able to list the files.
