### ISSUE TITLE
The OK button in the firmwre upgrade procedure isn't really necessary

### ISSUE THREAD

**Issue by AndreasAntener** [mavlink/qgroundcontrol#1604]
Latest master asks you to press OK when the board is plugged in. The upgrade starts anyway. Why not just leave the OK button part away? (just display the message that you can plug your board in now and hide the message once the upgrade starts). A cancel button could be there instead.

**Comment by kd0aij** [comment]
@DonLakeFlyer this sounds familiar :+1:

**Comment by DonLakeFlyer** [comment]
Yeah, I know. I'll get around to cleaning this up at some point. It was a quick and dirty conversion.
