### ISSUE TITLE
segfault on attempt to calibrate accelerometers with SENS_BOARD_ROT=27,28

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1624]
QGC 5/30 daily build, firmware branch release_v1.0.0

**Comment by DonLakeFlyer** [comment]
Can you install the new daily build and then follow these instructions: http://www.qgroundcontrol.org/bugreporting <http://www.qgroundcontrol.org/bugreporting>. 

It doesn’t have a bug fix in it, but I’m trying to create a repeatable mechanism to debug user crashes on Windows.

**Comment by kd0aij** [comment]
Ubuntu 14.10
QGC daily build 5/31
AUAV-X2 pixhawk derivative
PX4/Firmware branch release_v1.0.0
connect to pixhawk, go to Setup:Sensors, press Gyro, segfault with no error
messages

core dump https://copy.com/Yws6REf4rDkHSFON

On Sun, May 31, 2015 at 1:04 PM, Don Gagne <notifications@github.com> wrote:

> Can you install the new daily build and then follow these instructions:
> http://www.qgroundcontrol.org/bugreporting <
> http://www.qgroundcontrol.org/bugreporting>.
>
> It doesn’t have a bug fix in it, but I’m trying to create a repeatable
> mechanism to debug user crashes on Windows.
>
> > On May 31, 2015, at 10:29 AM, Mark Whitehorn <notifications@github.com>
> wrote:
> >
> > QGC 5/30 daily build, firmware branch release_v1.0.0
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/mavlink/qgroundcontrol/issues/1624>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/1624#issuecomment-107234124>
> .
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment]
further testing shows that pressing any button on the Sensors page results in a segfault (after pressing OK) with the above setup, regardless of the value of the rotation parameter.

**Comment by DonLakeFlyer** [comment]
Should be fixed in latest daily.

**Comment by LorenzMeier** [comment]
@kd0aij Fixed in latest daily?

**Comment by kd0aij** [comment]
OK on Ubuntu
