### ISSUE TITLE
Airframe config does not get applied successfully

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1630]
@DonLakeFlyer I don't have repro steps yet, but we have reports where the airframe config does not get applied. Maybe a settings saving delay thing? I need to work out how to repro first.

**Comment by DonLakeFlyer** [comment]
Could be. I just wait for some amount of time.So if things are really slow they might not get to the board.  I could wait for the params to come back across the wire before reboot.

**Comment by DonLakeFlyer** [comment]
Haven't heard anything recently
