### ISSUE TITLE
Add a RC Trim button

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1638]
Triggered on the Firmware side on: MAV_CMD_PREFLIGHT_CALIBRATION, and set param4 == 2. Further notes:

- It would be good if the RC calibration asks for all trims to be zeroed in the beginning.
- The button for setting the RC trims should also create first a right-hand dialog asking to set throttle to zero and center all sticks, and after sending the command should ask the user to now reset all trims to zero.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Would also be good to move the Spektrum pair button down in the UI during the process.

**Comment by DonLakeFlyer** [comment]
Copy Trim is done. I'll be going through an RC Cal UI re-work to clean up cluttered ui.
