### ISSUE TITLE
UI freezes during param download on Windows 

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1641]
@DonLakeFlyer When connecting to Pixhawk via USB (not radio) the UI freezes (and Windows complains about a crashed app sometimes) during param download. This is the case for two different setups running Windows 7 and Windows 8.

It seems this doesn't happen when connected via Radio, which is weird enough.

**Comment by DonLakeFlyer** [comment]
I've heard this multiple times but I can't repro it on my end. If you can get a crash following the crash reporting steps that would be great.

**Comment by LorenzMeier** [comment]
It doesn't crash, it just freezes with the app freeze mouse indicator.

**Comment by DonLakeFlyer** [comment]
That's worse since I can't debug from a stack trace. Can you break in and figure out where it is?

**Comment by LorenzMeier** [comment]
I don't have Windows, I only have Windows users - we would need a Windows dev to do that.

**Comment by DonLakeFlyer** [comment]
I need to expose the logging settings in the ui so you can turn things on/off. Then users could capture logs which would be better than nothing.

**Comment by DonLakeFlyer** [comment]
I can repro this now. Still no idea as to how to debug though.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Could our new Windows dev help there?

**Comment by DonLakeFlyer** [comment]
Who is that?
