### ISSUE TITLE
QGroundcontrol stable 2.4 linux, always crash if I close UDP connection to pixhawk

### ISSUE THREAD

**Issue by nopeppermint** [mavlink/qgroundcontrol#1642]
QGroundcontrol stable 2.4 linux, always crash if I close UDP connection to pixhawk
Linux Mint 17 32bit, kernel 3.13.04, qgroundcontrol/qt54 installed from ppa

I got the following error (in the terminal) before closing:
```
MAVLinkProtocolLog: _linkStatusChanged "cb3d4e0" false
Memory access error (translated from german)
``` 
udp connection was to 127.0.0.1:14555

**Comment by nopeppermint** [comment]
Two more last messages before crash:
```
MAVLinkProtocolLog: _linkStatusChanged "bed4330" false
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
Memory access error (translated from german)
```
```
MAVLinkProtocolLog: _linkStatusChanged "975ba10" false
Memory access error (translated from german)
```

**Comment by LorenzMeier** [comment]
Could  you please try the daily? This should have been fixed there.

**Comment by nopeppermint** [comment]
daily is only as x64 available :-(
I have x86, so I have to build on my own ?

**Comment by nopeppermint** [comment]
build successful on my own, error is gone.
But the udp connection is plotted twice
![qgroundcontrol_daily_udp](https://cloud.githubusercontent.com/assets/3403218/8003167/61ecdd4e-0b75-11e5-96c8-87c51131bddf.png)

**Comment by LorenzMeier** [comment]
That's because you created the connection twice. You need to remove one of them from your settings. Thanks for reporting!

**Comment by nopeppermint** [comment]
>Thanks for reporting!

will v2.4 stable get updated or will it rest with errors?
(especially the ppa) 
I am asking just to prevent other user to get the same experience with a "stable" released version ;-)

**Comment by DonLakeFlyer** [comment]
I'll be releasing a new Stable in a few days. Still no x86 though.

**Comment by LorenzMeier** [comment]
Don, can we do the stable now? People continue to run into the known crashes.

**Comment by DonLakeFlyer** [comment]
Probably by tonight. I'm headed out flying if you can believe that.
