### ISSUE TITLE
Flight mode config: If the acro switch is mapped it leads to an error message

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1645]
![screen shot 2015-06-04 at 18 39 35](https://cloud.githubusercontent.com/assets/1208119/8014637/a78688ac-0bd2-11e5-91f6-4c09bfd18355.png)

**Comment by DonLakeFlyer** [comment]
That's a hell of an error message!

**Comment by DonLakeFlyer** [comment]
Do you have time to tweak this? My repo is torn apart right now. Need to remove Acro switch from both attitude string arrays in FlightModesComponentController..c:

    // Make sure switches are not double-mapped
    
    QStringList attitudeParams, attitudeNames;
    
    attitudeParams << "RC_MAP_THROTTLE" << "RC_MAP_YAW" << "RC_MAP_PITCH" << "RC_MAP_ROLL" << "RC_MAP_FLAPS" << "RC_MAP_AUX1" << "RC_MAP_AUX2" << "RC_MAP_ACRO_SW";
    attitudeNames << "Throttle" << "Yaw" << "Pitch" << "Roll" << "Flaps" << "Aux1" << "Aux2" << "Acro";

Otherwise, will take me a little while to get to this.

**Comment by DonLakeFlyer** [comment]
in FlightModesComponentController::_validateConfiguration(void)

**Comment by LorenzMeier** [comment]
Ok, that hint is good enough. I will get onto this.

**Comment by LorenzMeier** [comment]
Closed via a7a36c02a60ba3b1bab961a7a012b3794c5da778
