### ISSUE TITLE
Setup - Flight Modes - Offboard Switch

### ISSUE THREAD

**Issue by Aperture-Laboratories** [mavlink/qgroundcontrol#1664]
When I applied the offboard switch to any channel (in my case, 7) I noticed that there's a spelling error in  on the display of "Offboard Switch", where it's spelled "offboad"

![screenshot from 2015-06-12 11 23 42](https://cloud.githubusercontent.com/assets/1240801/8133293/7ff2a9ba-10f5-11e5-8819-d14c43c5050d.png)

**Comment by dogmaphobic** [comment]
Fixed it in #1665
