### ISSUE TITLE
Ubuntu 14.04: Sometimes QGC still runs as a process although user has quit it.

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1668]
I was testing HIL for fw and pressed the simulation "stop button" in the HIL tab. QGC stopped responding and I had to force quit and restart it. After that I didn't get any GPS data from flightgear because there was still a QGC taks running in the background which I had apparently closed before.
This process seemed to block the UDP port in some way which lead to incomplete data transfer.

**Comment by LorenzMeier** [comment]
This should be fixed on master. Please report back if not.
