### ISSUE TITLE
Displaying simple 3D model of vehicle

### ISSUE THREAD

**Issue by boosfelm** [mavlink/qgroundcontrol#1682]
We discussed with @LorenzMeier and @tumbili that a widget displaying a simple 3D model of an airframe (maybe only quad, vtol, fixed-wing) + current attitude and attitude setpoint as coordinate frames would be super helpful to assess angle tracking at a first glance.

This would also partially solve the problem with displaying gimbal lock in the flight display for VTOL atm, because we could generate the coordinate frames from quaternions / dcm.
Waht do you think on that, where would that fit?

**Comment by DonLakeFlyer** [comment]
Don't understand how that differs from the HUD? What value does the 3d model add?

**Comment by DonLakeFlyer** [comment]
I think I should have dais Primary Flight display instead of HUD.

**Comment by boosfelm** [comment]
Hi Don
Sorry but now I don't get you completely, what does "dais" mean? For me the idea of the 3D model makes sense, because it displays all your three errors and thus you have a first intuition whether your angle tracking works well. It is quiet tough to include this in a HUD a suppose. 
@tumbili did a very basic visualization for himself.
![fc3b245a-141c-11e5-8d5c-8552d0d5b95d](https://cloud.githubusercontent.com/assets/6023217/8402572/a14ab914-1e3c-11e5-90a4-66a565b3ec34.png)

**Comment by dogmaphobic** [comment]
>I think I should have dais Primary Flight display instead of HUD.

Ultimate dyslexia? :)

I think he meant:

"I think I should have *said* Primary Flight display instead of HUD."

**Comment by DonLakeFlyer** [comment]
Ok. I get it now.

**Comment by LorenzMeier** [comment]
Closing as stale.
