### ISSUE TITLE
Mavlink FTP download of files fails

### ISSUE THREAD

**Issue by boosfelm** [mavlink/qgroundcontrol#1689]
With latest stable qgc (2.5.2) I cannot download logging data via mavlink ftp. In the onboard files widget I try to list files and it stops with an timeout error - any thoughts on that?
![screen shot 2015-06-30 at 17 53 35](https://cloud.githubusercontent.com/assets/6023217/8435449/87ad53b6-1f51-11e5-95fd-9c6d9b6b7729.png)

**Comment by DonLakeFlyer** [comment]
This is over USB? FTP doesn’t work over radio.

**Comment by boosfelm** [comment]
thanks for the quick reply. First trial was indeed via telemetry, but also via FTDI I can only download very small files (preflight / postflight) but no log file. It seems to have difficulties handling package loss.
![screen shot 2015-07-01 at 08 54 43](https://cloud.githubusercontent.com/assets/6023217/8449144/19c8f296-1fcf-11e5-9cde-5dd773cb978c.png)

**Comment by LorenzMeier** [comment]
@boosfelm I presume it works with a different QGC version? If yes, with which one?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer I'm not aware about recent FTP changes on the Firmware side.

**Comment by DonLakeFlyer** [comment]
Nothing has changed here that recently. 

Now you say it doesn’t work over FTDI. Does it work over USB?

**Comment by boosfelm** [comment]
Hi @DonLakeFlyer and @LorenzMeier 
Thanks for your reply. Today I have tried via usb and it works fine, although rather slow. I went for 921600 baud rate and got down to 11MB in 10 min.
I really like the idea of it, but I believe it is still somewhat cumbersome and thus only few people in the community use it. Connecting via usb is probably similar to removing the sd_card, which will be always much faster. @LorenzMeier Really looking forward to LTE integration ;)

<img width="273" alt="screen shot 2015-07-05 at 14 38 06" src="https://cloud.githubusercontent.com/assets/6023217/8511661/a302184c-2323-11e5-901c-5db8c0252b04.png">

**Comment by boosfelm** [comment]
it seems to me that you can only start mavlink on an usb port when usb connected. Thus the pixhawk has to be powered externally, connect usb cable and start mavlink via nsh and connect via qgc. Else the following error message occurs.
<img width="557" alt="screen shot 2015-07-05 at 15 00 25" src="https://cloud.githubusercontent.com/assets/6023217/8511804/b9c92e3c-2326-11e5-92d1-9c0c97648d11.png">

**Comment by DonLakeFlyer** [comment]
Working as well as it can over USB
