### ISSUE TITLE
Qt 5.5: FactTextField is showing way too many decimal values

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#1704]
Something got messed up with FactTextField, which is now showing way too many values after the decimal point, which in turn is messing up the formatting of the text field.

![screen shot 2015-07-04 at 11 57 12 am](https://cloud.githubusercontent.com/assets/749243/8508599/b501c8e2-2244-11e5-8fc2-c5f887049e54.png)

**Comment by dogmaphobic** [comment]
Hmm.. I didn't realized I was using Qt 5.5.0 for this build. This issue is only present in Qt 5.5.0. Nonetheless, we need to find out what is causing it.

**Comment by DonLakeFlyer** [comment]
Something changed with QVariant::toString on float value which is what valueString calls.

**Comment by LorenzMeier** [comment]
This is an official Qt 5.5 bug, scheduled to be fixed until mid September.
