### ISSUE TITLE
parameter change in custom widget

### ISSUE THREAD

**Issue by flyingk** [mavlink/qgroundcontrol#1713]
When trying to change a parameter on my own autpilot in the custom command widget by pressing enter or clicking the following error happens
qrc:///qml/QGroundControl/FactControls/FactTextField.qml:21: ReferenceError: qgcView is not defined

If I comment out the reference for qgcView in that file it works. Maybe this is a PX4 specific thing?

**Comment by DonLakeFlyer** [comment]
Can you provide your custom Qml? Also please send problems to the mailing list first before putting in a GitHub issue.

**Comment by DonLakeFlyer** [comment]
Never mind with sending the Qml. There's a problem with using a FactPanel as the outer control. Need to figure out how to fix it.

**Comment by DonLakeFlyer** [comment]
Add this to your FactPanel as a work around until I figure out real fix:

property var qgcView: null // Temporary hack for broken QGC parameter validation implementation

Example updated: http://www.qgroundcontrol.org/custom_command_qml_widgets

**Comment by DonLakeFlyer** [comment]
@flyingk Is this working for you now?

**Comment by flyingk** [comment]
Yes it works fine now. Thanks for the fix.

Kai

On 23/07/2015 3:55 am, Don Gagne wrote:
>
> @flyingk <https://github.com/flyingk> Is this working for you now?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mavlink/qgroundcontrol/issues/1713#issuecomment-123808345>.
>

-- 
Kai Lehmkuehler, BE (Aero, Hons 1)

Research Engineer
UAV Design Group

School of Aeronautical, Mechanical and Mechatronic Engineering
The University of Sydney

Phone: +61 (0) 412-533385
