### ISSUE TITLE
Parameter Editor, mavlink inspector, etc won't show up after connection

### ISSUE THREAD

**Issue by shengwen1997** [mavlink/qgroundcontrol#1714]
Environment: Elementary OS freya(based on Ubuntu 14.04)
Version: 2.5 stable and newest daily build
Control board: self-made

This is a pretty annoying problem for me.
Sometime when I connect my quadcopter  to the ground station,
the parameter editor, mavlink inspector and some component won't show up.

Just like this picture. Although the status bar show me the connection is well, the parameter editor just
said: "no vehicle connected", also, the attitude is still plot perfectly.
![bug](https://cloud.githubusercontent.com/assets/4500588/8633633/a1300d18-2804-11e5-8746-503bc1630eaa.png)

**Comment by LorenzMeier** [comment]
If you boot the system incompletely you may end up with this state. @DonLakeFlyer Can you think of a way to make the internal state more transparent so its easier to debug for flight code developers? I fixed the boot timing for good on beta and stable now.

**Comment by DonLakeFlyer** [comment]
Better reporting now complete.
