### ISSUE TITLE
Set RC to param popup is broken in daily build

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1721]
"Waiting for parameter refresh..." OK button disabled
On the plus side, parameter editing works properly and the UI is much more efficient now.

![setrcdialog](https://cloud.githubusercontent.com/assets/2300221/8764328/933bc60e-2d8e-11e5-9f05-2d5d7d13405f.png)

**Comment by LorenzMeier** [comment]
Fixed!
