### ISSUE TITLE
Mode switch view: RC channel count off by one

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1725]
The new mode switch view offers one RC channel less than detected, using the QGC-only Firmware parameter which is set during the RC calibration. E.g. when set to 8 I only can pick channels 5,6,7, if I set the param to 9 I can select channel 8 as well.

**Comment by DonLakeFlyer** [comment]
Are  you running latest master. I fixed this a few days ago I thought: https://github.com/mavlink/qgroundcontrol/pull/1719

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is this fixed?

**Comment by LorenzMeier** [comment]
Tested and fixed, closing.
