### ISSUE TITLE
Critical message text unreadable outdoors (red on black)

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1739]
The message text popup window displays a very small font in red on a black background in both indoor and outdoor view configurations. This is impossible to read outdoors on a 1920x1080 Chromebook. The Chromebook display is very bright; similar to a Nexus 7. Dark text on a light background would be OK.

The text in the Control widget text panel is also unreadable in outdoor  ("light") mode; appears to be black on black.

**Comment by DonLakeFlyer** [comment]
Different now

**Comment by kd0aij** [comment]
still dark red on black here:
![qgc_crit_msg](https://cloud.githubusercontent.com/assets/2300221/11608422/0ae8a2f8-9b26-11e5-9db6-96a1585ff4cf.png)

info view widget timestamp is now light grey on white, very low contrast:
![info_view_widget](https://cloud.githubusercontent.com/assets/2300221/11608442/5c18b6c2-9b26-11e5-9f10-d927ff88b6c7.png)

**Comment by LorenzMeier** [comment]
@kd0aij Your state is again quite outdated. Please update.

**Comment by dogmaphobic** [comment]
It may be outdated but a lot of those colors are still not optimal. I've been meaning to work on those palettes for a while but have not gotten around to it. The *Light* palette is specially hard to distinguish elements (buttons from background for example).

It will take some work as it's not just a matter of fixing the individual colors but also using the proper colors here and there. I will take a look at it soon...

**Comment by kd0aij** [comment]
oops, still haven't figured out how to do a "shadow build" correctly. Thought I had rebuilt latest master, but the second try is still disappointing. @LorenzMeier are you *not* seeing the same red on black?
![qgc_critical_msg](https://cloud.githubusercontent.com/assets/2300221/11609200/5836f5fc-9b3d-11e5-8d5f-204e6c881df5.png)

**Comment by DonLakeFlyer** [comment]
Thought this was different now. It doesn't seem to be using the palette for the background color which is incorrect as well. Same thing for the toolbar messages at the bottom.

**Comment by kd0aij** [comment]
#2356
