### ISSUE TITLE
After connecting to simulator for HIL, PX4 looses data links

### ISSUE THREAD

**Issue by AndreasAntener** [mavlink/qgroundcontrol#1749]
When I try to start HIL, as soon as I connect to X-Plane, PX4 reports "all data links lost". It seems that it doesn't get the heartbeats from QGC anymore.
When I connect QGC to Pixhawk via proxy (which itself emits heartbeats) it's working.

**Comment by LorenzMeier** [comment]
Fixed via #1754. Thanks!
