### ISSUE TITLE
Serial port threading broken

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1753]
When the wrong thread (I need to investigate which one) sends a MAVLink message through the serial link Qt emits this message and stops *completely* sending any data: QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread

From that point on USB doesn't receive any bytes, although the serial link API reports writing data successfully.

**Comment by DonLakeFlyer** [comment]
Writes need to be on the right thread. Needs to signal itself.

**Comment by LorenzMeier** [comment]
The problem is that when simulation gets activated the UI thread calls the UAS object. My first attempt at self-signalling failed, I'll have another stab.

**Comment by DonLakeFlyer** [comment]
Look in PX4FirmwareUpgradeThread.cc/h or LogReplayLink.cc/h for examples of signaling to get the call on the right thread. Methods are called *OnThread.
