### ISSUE TITLE
File system of autopilot is not refreshed.

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1764]
The file system e.g. /fs/microsd is not refreshed when connected to QGC. If e.g. a new log file is written to the SD card you first need to disconnect and reconnect the autopilot to see the file.
Can we have a refresh button?

**Comment by DonLakeFlyer** [comment]
The directory listing is not meant to be live updated. Click "List Files" again to refresh it. Is that not working?

**Comment by DonLakeFlyer** [comment]
@tumbili ?
