### ISSUE TITLE
Parameter UX usability catchall

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1766]
* Parameter reset: Implement a value for MAV_CMD_PREFLIGHT_STORAGE which resets the parameters. Start with cmd.param1 = 2. I have implemented this in Firmware already

**Comment by DonLakeFlyer** [comment]
The spec for this message is a little odd. For param1 and param2 there is not ignore option specified. I'm using -1 for now since I know that will work from looking at the firmware source. But that's strange as well since for param3 0=ignore.
