### ISSUE TITLE
No frame for 3Dr X8 octocopter.

### ISSUE THREAD

**Issue by rs1990** [mavlink/qgroundcontrol#1767]
Hello,

I tried to change the firmware of my x8 from APM to px4 but I cannot find the correct frame for my octocopter. Mine is the 3dr X8 octocopter.

Could you please help me figure out how to resolve this. I'm trying to get it working using mavros and need the right firmware.

Thanks.

**Comment by LorenzMeier** [comment]
Please download the latest QGroundControl stable (it should say 2.7 in the title bar), upgrade the Firmware on Pixhawk using it and then select the Generic Octo Coax config (first row, top right).
