### ISSUE TITLE
Allow the use of the HUD when video overlay is enabled

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1772]
@dogmaphobic It would be nice if I could choose between the block instruments and retaining the normal HUD / flight instrument when video background is enabled. It doesn't make sense for a gimbal, but its great for forward-looking fixed wing.

**Comment by dogmaphobic** [comment]
Yes, I thought about it too. I will see what I can do...

**Comment by dogmaphobic** [comment]
I assume this can be closed? #1777 dealt with it.

**Comment by DonLakeFlyer** [comment]
Assigning to me since I've changed this all around

**Comment by jaxxzer** [comment]
Is this still an issue?

**Comment by dogmaphobic** [comment]
I don't even remember what this was all about. With that said, being almost 2 years later, I would assume it is no longer valid as just about everything about the Fly view has changed since.

**Comment by LorenzMeier** [comment]
Closing as stale.
