### ISSUE TITLE
A improvement suggestion for QGC:  rotation sign is missing when calibrate compass sensors

### ISSUE THREAD

**Issue by wangsen1312** [mavlink/qgroundcontrol#1783]
Maybe someone can add the rotation sign when calibrate compass. Three of six directions rotation sign is missing for the newest version.

**Comment by DonLakeFlyer** [comment]
Instead of diving into my limited Gimp skills again. I'm going to to until we get the Qt 5.5.1 at which point these will turn into animated models.

**Comment by wangsen1312** [comment]
@DonLakeFlyer  Thank you for your reply. This is just an improvement

**Comment by LorenzMeier** [comment]
Closing as stale.
