### ISSUE TITLE
Cut over plotting to QML Charts

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1819]
@dogmaphobic @DonLakeFlyer I stumbled across this, which seemed intriguing:
http://doc.qt.io/QtCharts/qtcharts-qmloscilloscope-example.html

There is also this, but the official Qt solution might be preferable due to probably better rendering backends.

**Comment by dogmaphobic** [comment]
Hehe... I had found that a long time ago and I was salivating at the time. But if you scroll all the way down, you will notice that's only available for a *paid* license :)

**Comment by DonLakeFlyer** [comment]
Yup I saw that as well. I was looking at this: http://qcustomplot.com

**Comment by LorenzMeier** [comment]
I don't think it differs from the normal Qt license. I'm pretty confident its available the same way.

**Comment by DonLakeFlyer** [comment]
It's only in the paid license. You can get a 30 day free trial, then you have to pay. There's a chart somewhere that says what is in what. I can't seem to find it now.

**Comment by dogmaphobic** [comment]
> I can't seem to find it now.

Me either. I've seen it before too. Their normal paid license is $350/month. I wonder what kind of arrangement could be made for an open source project though...

**Comment by LorenzMeier** [comment]
If you follow the link at the bottom of the page it tells you that you can download for free.

**Comment by DonLakeFlyer** [comment]
This is what I see at the bottom:
![screen shot 2015-09-01 at 12 43 48 pm](https://cloud.githubusercontent.com/assets/5876851/9614522/2791f3ec-50a7-11e5-809a-92e45b5bf4f9.png)
Click that, and then you can see how you can get a 30 day free trial on the commercial license. Only Open Source is free, and it's not in that version.

**Comment by NaterGator** [comment]
The plotting interface is still a big sore point. What if we consider something like Chart.js integration:
https://github.com/jwintz/qchart.js

![image](https://cloud.githubusercontent.com/assets/2575/13088211/5ff955c2-d4b9-11e5-9167-8ab4405bddee.png)

**Comment by dogmaphobic** [comment]
> What if we consider something like Chart.js integration

I've looked at that and considered it. Qt Chart is now supposedly open source. Waiting to see how that goes before investing time with JavaScript.

**Comment by NaterGator** [comment]
Ah, missed that... the release is [here](http://blog.qt.io/blog/2016/01/13/new-agreement-with-the-kde-free-qt-foundation/)

It looks like it will be GPLv3, is that going preclude us from using it on mobile platforms?

**Comment by LorenzMeier** [comment]
No. It just means we need a proper license for the App Store build.

**Comment by LorenzMeier** [comment]
Closing as stale.
