### ISSUE TITLE
New mission view: Include altitude profile (for display but also for planning in other view)

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1820]
@DonLakeFlyer From my experience this would help users tremendously getting their mission planning right and predicting the distance and time (I can help building an API to query the configured travel speed) is also super helpful.

![2c7a4fd4-501c-11e5-80d0-d53ad34f60d4](https://cloud.githubusercontent.com/assets/1208119/9598937/f74fca40-508f-11e5-9565-285049762cc9.png)

**Comment by DonLakeFlyer** [comment]
This is already supported in Plan?

**Comment by thomasgubler** [comment]
I closed this one accidentally by clicking at the wrong button, that's why I just re-opened it. Up to you if this actually has to be closed.

**Comment by DonLakeFlyer** [comment]
Ah, ok
