### ISSUE TITLE
Controllers menu disapeared from Settings

### ISSUE THREAD

**Issue by jlbilou93** [mavlink/qgroundcontrol#1833]
hello I have just built version 41035462b9e764abb0d79293271139921db2b59a
and there is no controllers menu in the settings.
On 4415f32dff32558c14a897abb8fe67dd197a7d43 it seems ok.

**Comment by DonLakeFlyer** [comment]
Controllers menu? Can you be more specific? There never was a "Controllers" menu.

**Comment by DonLakeFlyer** [comment]
There is no such thing.

**Comment by jlbilou93** [comment]
In menu File -> Settings -> The tab Controllers between Comm Links and MAVLink disappeared.
How do we configure Joystick now?
On the binary version v2.7.1 I can see this tab.
On master of today 22nd of September don't see it anymore. Is it a special build option?
I am building on Ubuntu 15.04 with QT v5.5.0.

**Comment by LorenzMeier** [comment]
Just use the setup perspective like for the rest of the system. There is a new pane for the joystick there.

**Comment by jlbilou93** [comment]
Thx for your answer. Maybe my drone is not in the correct mode?
What are the drone requirements to access the Setup configuration?
- MAV_STATE_STANDBY MAV_MODE_*_DISARMED ? 
- MAV_MODE_FLAG_MANUAL_INPUT_ENABLED ?


What are the minimal mavlink messages I should send to qgroundcontrol ?
Currently I am sending:
HEARTBEAT
ATTITUDE
SYSTEM_STATUS
RAW_GPS
GLOBAL_POSITION_INT
MISSION_CURRENT

**Comment by DonLakeFlyer** [comment]
Joystick support if specific to the PX4 Flight Stack firmware implementation. It doesn’t require a specific mode to be in. It required a joystick to be connected before it will show up.

**Comment by jlbilou93** [comment]
That is too bad, on previous versions e.g 2.7.1, I could make my drone use joystick inputs with GENERIC autopilot.

**Comment by DonLakeFlyer** [comment]
Hmm. That should still be doable but it will take a little work.

**Comment by DonLakeFlyer** [comment]
What are you using for firmware? It doesn’t need any additional parameters set when you use a joystick?

**Comment by jlbilou93** [comment]
I am using a Parrot Bebop firmware.
On version 2.7.1 I didn't need additional parameters, because we could set the axis and the value were between -1000 and 1000.
