### ISSUE TITLE
No way to flash custom binary firmware for PX4Flow

### ISSUE THREAD

**Issue by jlian** [mavlink/qgroundcontrol#1837]
When I tried to flash the PX4Flow using QGroundControl 2.8.0 this is what I get

http://i.imgur.com/HqBks55.png

There's no place to flash custom firmware (a .px4 file). It looked like it was possible before (on 2.0.3) here: http://copter.ardupilot.com/wiki/common-px4flow-overview/.

**Comment by DonLakeFlyer** [comment]
Can you try this again in tomorrow' daily build?

**Comment by jlian** [comment]
Just tried it. It works now. Thanks, Don!
