### ISSUE TITLE
Create virtual on-screen joystick

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1859]
@DonLakeFlyer I ordered a tablet and I'm eager to get things going on mobile. It seems this is very high on our wish list:
http://kunalmaemo.blogspot.ch/2011/11/virtual-joystick-with-qml.html

I wouldn't want to disrupt your mission planning spree with it, but maybe after that? The wifi module in the Pixhawk 2 kit should allow you to fly a small quad just using Wifi then. @dogmaphobic does this feel interesting?

**Comment by dogmaphobic** [comment]
With a single *stick*? I'm not sure you could implement two simultaneous *sticks* though. We would have to come up with something clever to deal with it.

**Comment by LorenzMeier** [comment]
It looks like we're covered:
http://doc.qt.io/qt-5/qml-qtquick-multipointtoucharea.html

**Comment by LorenzMeier** [comment]
This looks like its a complete implementation:
https://github.com/mana/manamobile/blob/master/example/qml/main/Joystick.qml

It uses a touch point which has to be inside a multipointtoucharea. It also looks like they already added mouse support to ease testing.

**Comment by dogmaphobic** [comment]
Don has done this quite a while ago.
