### ISSUE TITLE
Program Crashes When Upgrading Firmware 

### ISSUE THREAD

**Issue by nimaaghli** [mavlink/qgroundcontrol#1877]
Hi,
The version 2.7.1 trying to upgrade firmware and program crashes for this reason :
qgroundcontrol crashed with sigsegv in QIODevice::write()
I have right permissions.
Ubuntu 14.04 64bit

**Comment by DonLakeFlyer** [comment]
Same thing with the latest daily build?

**Comment by DonLakeFlyer** [comment]
@nimaaghli Any updates?

**Comment by LorenzMeier** [comment]
Closing as stale.
