### ISSUE TITLE
Camera setup entry required in config menu

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1879]
We need to allow the user to configure the bottom and forward looking cameras. In particular for the Snapdragon flight.

**Comment by DonLakeFlyer** [comment]
I filled out the form to hopefully get one of these sent to me. Is there some info somewhere on what needs to be done?

**Comment by LorenzMeier** [comment]
I can implement it if you provide me with an empty menu entry for the cameras which has the QML for an image display widget. I just need to then copy the image from the UAS object to the widget.

**Comment by DonLakeFlyer** [comment]
Is this the mavlink based video thing which is needed for PX4 Flow as well? That disappeared somehow. I can bring it back.

**Comment by LorenzMeier** [comment]
Yes, thats the one we need.

**Comment by DonLakeFlyer** [comment]
Do you remember what that was called? I went back to 2013 and I can't seem to find it anywhere in mainwindow.

**Comment by DonLakeFlyer** [comment]
And of course I found it as soon as I typed that. I went back to far!

**Comment by DonLakeFlyer** [comment]
What should we call this thing so that it doesn't get confused with video streaming support?

**Comment by LorenzMeier** [comment]
I would call it camera configuration and stick it into the normal setup menus, *not* into the main UI. We then would add multiple QML image views there for the different cameras.

**Comment by DonLakeFlyer** [comment]
How will multiple images be requested to come across mavlink. I don't anything in data_transmission_handshake to specify one or more sources.

**Comment by LorenzMeier** [comment]
It will be replaced. We can start with one image view and we'll need a button which sets the video only mode on the flow sensor.

**Comment by DonLakeFlyer** [comment]
Can we set up a time tomorrow to talk through this? A little busy now, but want to clear some things up.

**Comment by LorenzMeier** [comment]
If you are around within the next hour yes, after that its difficult.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer More people in need of this now.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer New images are announced using this:
https://github.com/mavlink/qgroundcontrol/blob/master/src/uas/UAS.cc#L992

And you can fetch the image using this:
https://github.com/mavlink/qgroundcontrol/blob/master/src/uas/UAS.cc#L1352

this is a LOW RATE LINK! So no OpenGL needed. Just draw the QImage on a canvas and everybody will be happy. This should not take more than an hour.

**Comment by dogmaphobic** [comment]
Same as in #403. It's *experimentally* there. Let me know how it goes...

**Comment by DonLakeFlyer** [comment]
Do you need something other than the PX4 Flow config?

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is this done now?

**Comment by LorenzMeier** [comment]
Yes, all done.
