### ISSUE TITLE
Disappearing map tiles on Android 

### ISSUE THREAD

**Issue by mhkabir** [mavlink/qgroundcontrol#1891]
Map tiles load fine, but some tiles in the map background then disappear. Zooming in/out or moving the map around gets them back, but some other one disappears then.

![screenshot_2015-09-26-09-18-02](https://cloud.githubusercontent.com/assets/5557676/10115711/882b4f9a-6430-11e5-8e2c-d229f5209f03.png)

**Comment by DonLakeFlyer** [comment]
Can you upload the screen shot again. You need to wait until it's finished uploading before saving I think.

**Comment by mhkabir** [comment]
Done.

**Comment by dogmaphobic** [comment]
There is a lot of logging being set to the console during tile retrieval. It would help to see the logs to see what's going on.

**Comment by mhkabir** [comment]
@dogmaphobic Where can I find them?

**Comment by dogmaphobic** [comment]
On Android, it should be out to logcat. With that said, don't worry about it for the time being. I'm rewriting the caching mechanism, which deals with some of that.

**Comment by dogmaphobic** [comment]
Hmm, there seems to be an issue with Google Satellite maps. Some tiles are getting 404 responses. I've been wondering how far we could get on this free ride (google, in theory, does not like people doing what we're doing). Switch to some other map type and see if the error persists. I'm done with caching but this is a separate issue.

**Comment by DonLakeFlyer** [comment]
I've noticed that. It's only been happening recently. Used to work just fine. I don' think it's something we changed on our side. Likely a change on the google side. Does the old map pull satellite tiles without problem?

**Comment by dogmaphobic** [comment]
It's definitely a change on the Google side. I'm researching as we "speak". The issue seems to be isolated to google satellite maps. Everything else seems to still be working fine.

**Comment by mhkabir** [comment]
I don't quite think my issue is the same as yours. All the tiles on mine load fine, and then disappear after a few seconds. I'll try the other map engines meanwhile to see if it's any different

**Comment by dogmaphobic** [comment]
If they show up and then disappear, it's definitely something else. Once I get this done, I will do an Android build and see if I can find anything...

**Comment by dogmaphobic** [comment]
I just did an Android build and it's all working as it should. Not sure what you are seeing though. If the tiles disappear, it sounds more like an OpenGL/Texture paint issue. What device are you using?

**Comment by mhkabir** [comment]
Its a Nexus 7 2012 running 5.1.1 
This has been happening since I first started using QGC on Android, so it isn't something new. I'm inclined to believe that its a paint issue, because the thing looks like a glitch in a game ;)

**Comment by mhkabir** [comment]
Happens with all map providers.
![screenshot_2015-09-28-07-28-36](https://cloud.githubusercontent.com/assets/5557676/10126643/e6069bf4-65b3-11e5-81e2-3abafd76d4cd.png)

**Comment by mhkabir** [comment]
@dogmaphobic @DonLakeFlyer
Guys, this still happens, and is a lot worse nowadays (like 1/4th of the map is visible). I'm running Android 6 and the Play Store builds, and this is so bad that it is practically unflyable.

It'd be great if you could have a look into the rendering issue.

**Comment by LorenzMeier** [comment]
Closing as stale.
