### ISSUE TITLE
Mobile builds show have all widgets defaulted to off

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#1895]

**Comment by dogmaphobic** [comment]
Yep, the *Info View* is coming up by default and it's basically impossible to get rid of it because the **x** button is too small.

![screen](https://cloud.githubusercontent.com/assets/749243/10121173/20d4d366-64ad-11e5-86e7-b0b0120ebfa7.png)

**Comment by LorenzMeier** [comment]
I would default it to always off or remove it entirely. Altitude over home should be added prominently in the flight view.
