### ISSUE TITLE
Firmware upgrade sync error: "Invalid sync response: 0x21 0x20"

### ISSUE THREAD

**Issue by bradsedito** [mavlink/qgroundcontrol#1912]
I'm having an issue trying to upgrade the firmware on my Pixhawk..  I keep getting the following when trying to upgrade my board: 

"Error: Sync: Send Command: Invalid sync response: 0x21 0x20"

I saw there was a posted solution to a previous post about this same problem, but I can't seem to get any of said solutions to work. Any ideas? I'm losing sleep over this one.

**Comment by LorenzMeier** [comment]
You are on Linux, yes? Deinstall the modem manager in that case.

**Comment by bradsedito** [comment]
Mac OSX El Capitan

**Comment by bradsedito** [comment]
Should have probably mentioned that first. Haha. Sorry about that. How do I go about nixing the modem manager? Terminal maybe?

**Comment by DonLakeFlyer** [comment]
modemmanager is not needed on OSX. To help debug, run the latest daily build with the command line option —logging:FirmwareUpgradeLog. Capture the console output from a failed flash and send it to us.

**Comment by LorenzMeier** [comment]
Verified on Don's El Capitan install.

**Comment by DonLakeFlyer** [comment]
Firmware Upgrade is working fine for me on El Capitan. It's regular connect that is flaky. 75% of the time it just hangs QGC. @bradsedito Need to log output to debug this.

**Comment by DonLakeFlyer** [comment]
@bradsedito Can you provide a log as specified above?

**Comment by bradsedito** [comment]
Sorry for the delay guys, birthday weekend xD how do I obtain the log in QGC?

**Comment by DonLakeFlyer** [comment]
> To help debug, run the latest daily build with the command line option —logging:FirmwareUpgradeLog. Capture the console output from a failed flash and send it to us.

**Comment by bradsedito** [comment]
How exactly do I do that? My apologies, having a hard time figuring it out

**Comment by DonLakeFlyer** [comment]
What operating system are you using?

**Comment by bradsedito** [comment]
Mac OSX El Capitan, using built-in terminal

**Comment by DonLakeFlyer** [comment]
In terminal:
```
./Applications/QGroundControl.app/Contents/MacOS/qgroundground --logging:FirmwareUpgradeLog
```

**Comment by julianoes** [comment]
I don't see this error anymore in the latest daily.
