### ISSUE TITLE
Wrong log format

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#1922]
If you try to log via QGC the resulting log file cannot be opened by FlightPlot. (wrong format)

**Comment by LorenzMeier** [comment]
The resulting file is a CSV and is not designed for flight plot.

**Comment by tumbili** [comment]
@LorenzMeier And what is the .log file?

**Comment by LorenzMeier** [comment]
A MAVLink transmission log. Most recent FlightPlot might have support or not, pyMAVLink can plot it.
