### ISSUE TITLE
Master QGC doesn't upgrade firmware

### ISSUE THREAD

**Issue by FPVflyer** [mavlink/qgroundcontrol#1925]
Start bootload, then broke connection. 
<img width="1440" alt="schermata 2015-10-07 alle 22 03 12" src="https://cloud.githubusercontent.com/assets/12083623/10349582/823fc72e-6d3f-11e5-8269-04682c2b19b6.png">
see screenshot.

**Comment by LorenzMeier** [comment]
Is this Mac OS X El Capitan?

**Comment by FPVflyer** [comment]
Yes

Date: Wed, 7 Oct 2015 13:08:11 -0700

**Comment by DonLakeFlyer** [comment]
Can you try a firmware upgrade with --logging:FirmwareUpgradeLog on the command line. Capture the console output and post it here.

Those wacky chars in the setup page titles is an El Capitan thing as well. Great OS X release so far! Screwed up a pile of stuff. Thanks Apple (or maybe Qt).

**Comment by DonLakeFlyer** [comment]
> Can you try a firmware upgrade with --logging:FirmwareUpgradeLog on the command line. Capture the console output and post it here.

Hello?

**Comment by FPVflyer** [comment]
Hi Don,
Sorry have been very busy, I'll
Probably try tonight.

Sent with my phone
