### ISSUE TITLE
New simulation pane does not fully delete HIL control link when removed

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1959]
@DonLakeFlyer The new HIL control widget logic does not properly destroy the simulation link, requiring a QGC restart when you reboot the autopilot. @AndreasAntener will fix this, but for now just keep restarting QGC when you reconnect.

**Comment by DonLakeFlyer** [comment]
When you disconnect, the Vehicle should go away which should in turn stop the hil link:

```
UAS::~UAS()
{
#ifndef __mobile__
    stopHil();
    if (simulation) {
        // wait for the simulator to exit
        simulation->wait();
        simulation->deleteLater();
    }
#endif
    writeSettings();
}
```

If this is not working, not sure it has anything to do with the new widget code. That didn't really change any logic behind it.

**Comment by DonLakeFlyer** [comment]
Either way, just rebooting the vehicle would not have stopped the hil link. You would have had to disconnect. Rebooting the vehicle just results in a lost connection, which doesn't trigger anything.

**Comment by DonLakeFlyer** [comment]
Tested Start HIL and then Disconnect from toolbar. FlightGear was left running. So something is wrong there. Let me look. Start/Stop on widget multiples times works ok.

**Comment by DonLakeFlyer** [comment]
Looking at this more, FlightGear was never shut down in this case. The the link is stopped. So everything still seems the same to me. What are the exact repro steps that cause a problem.

I do see a possible problem on the firmware sid. When I do this:
- Connect
- Start from widget
- Wait for FlightGear to start up
- Stop from widget

I get an infinite stream of these from the firmware serial port:
WARN  53422229   timed out (file /home/travis/build/PX4/Firmware/src/modules/navigator/navigator_main.cpp line 340)

**Comment by LorenzMeier** [comment]
Closing as stale.
