### ISSUE TITLE
MAVLINK_MSG_ID_REQUEST_DATA_STREAM missing?

### ISSUE THREAD

**Issue by krzysztofkuczek** [mavlink/qgroundcontrol#1962]
Hi,
Years ago i used qground control to comunicate with my own FC, and there was option to request data streams, to setup streams frequency etc.
How cat I force 2.7 version to send such a message?
Or maybe i can download 1.x version from somewhere?
Best regards
Krzysiek

**Comment by DonLakeFlyer** [comment]
For a generic mavlink connection QGC now expects streams to be setup up automatically on the firmware side. There is no longer a UI to request them manually.

**Comment by krzysztofkuczek** [comment]
OK, Thanks for explanation.
Any chance to download older version for windows?

**Comment by DonLakeFlyer** [comment]
Don’t think anything we still have around has that in it.

**Comment by DonLakeFlyer** [comment]
Closing, since already covered in: Issue #1941
