### ISSUE TITLE
Waypoint reordering results in missing icons

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1991]
<img width="1005" alt="screen shot 2015-10-14 at 19 10 19" src="https://cloud.githubusercontent.com/assets/1208119/10499176/22912e4a-72cf-11e5-85f6-4731cd870f93.png">

The up / down controls seem to lead to issues on the map regarding the icons.

**Comment by DonLakeFlyer** [comment]
Yeah, I've seen that. It some deep dark bug in Qt. What do you think about Up/Down? Doesn't seem like critical functionality to me. I'd rather remove than dig into the bowels of Qt to fix.

**Comment by LorenzMeier** [comment]
Yeah, remove it. Making them movable is by far more relevant.

**Comment by LorenzMeier** [comment]
And I would not bring it back. Too confusing from a user perspective. Users move stuff on the map, not in the list.

**Comment by LorenzMeier** [comment]
Put the delete into an X icon in the list.

**Comment by DonLakeFlyer** [comment]
Yeah, that was the direction I was heading
