### ISSUE TITLE
Home is not a waypoint nor editable

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#1992]
The waypoint list has the home position as an editable item, which is conceptionally not part of the mission (and the waypoint 0 hackery in APM will go as well, there is a transition plan in place). If it would show without number and without editable coordinates it would be less confusing.

**Comment by DonLakeFlyer** [comment]
That's a bug. It should show as non-editable. It used to. Must ahve broken it.
