### ISSUE TITLE
Unknown module(s) in QT: location-private positioning-private

### ISSUE THREAD

**Issue by marbug** [mavlink/qgroundcontrol#1998]
Steps To Reproduce:
1) install everything on Fedora according to README.md
2) run building in Qt Creator or run "qmake ..." and "make"
3) see error.

Fixed by "yum install qt5-qtlocation-devel"

Please review:
https://github.com/mavlink/qgroundcontrol/pull/1997

**Comment by LorenzMeier** [comment]
Thanks for the fix, merged.
