### ISSUE TITLE
Singleton doesn't create the instance through instance

### ISSUE THREAD

**Issue by pritamghanghas** [mavlink/qgroundcontrol#2000]
QGC singletons have to be intiated with ::_createSingleton() otherwise instance() will just return a NULL. Also all singletons are created at application startup in  QGCApplication::_createSingletons(void). That method creates singletone of all firmware plugins in one go without regard to whether they will be required in future or not. Singleton pattern should create the instance when ::instance is called first time.

**Comment by DonLakeFlyer** [comment]
No more singletons
