### ISSUE TITLE
Tablet Usability

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2006]
This is a catch all Issue for capturing Tablet usability issues. We'll discuss below and then I'll pull up works items up here as we make decisions.

**Comment by DonLakeFlyer** [comment]
- I think we should create a single workable color palette for QGC. That means getting rid of the Light/Dark. They are nice, but trying to manage two that both work well is a real PITA.
- I think the Vehicle should just be an outline, with a see through middle. That way you can see waypoints that are under it. And probably some sort of dot for the center point.
- The Fly view widgets need work:
 - They need to be way smaller
 - Need ui changes to be visible over satellite map

![screenshot_2015-10-15-16-27-36](https://cloud.githubusercontent.com/assets/5876851/10530509/724ee236-735d-11e5-829b-9a6ef35b329f.png)

**Comment by LorenzMeier** [comment]
The light color theme is pointless because the maps are "dark" and the tablet screens are much brighter outdoors. Its also a design nightmare (looks horrible).

**Comment by LorenzMeier** [comment]
Don, can you try to start testing with PX4 SITL? The reason I ask is that this will expose the things that are an issue when running on the tablet, such as the odd connect step via UDP.

**Comment by LorenzMeier** [comment]
Fly view doesn't have lines between waypoints. I suggest to ditch its map handling completely. As the person operating the vehicle you want the same as on the plan view. You can make the plan view's sidebar into a ribbon that you can minimise and maximise. When it's maximised you can hide all the flight instruments except for a minimalistic HUD + altitude.

**Comment by LorenzMeier** [comment]
So here is my long wanted laundry list: The bottom line is that I'm blown away by the new UI. The logic next step to complete this is to consolidate map handling onto a single view and provide PiP for video.

<img width="1207" alt="screen shot 2015-10-18 at 14 08 26" src="https://cloud.githubusercontent.com/assets/1208119/10564079/c5475e60-75a5-11e5-9718-ed2e6a0c6f03.png">
<img width="1207" alt="screen shot 2015-10-18 at 14 08 17" src="https://cloud.githubusercontent.com/assets/1208119/10564080/c5769518-75a5-11e5-849c-399fe07f19c9.png">
<img width="1207" alt="screen shot 2015-10-18 at 14 08 35" src="https://cloud.githubusercontent.com/assets/1208119/10564081/c67284cc-75a5-11e5-8c85-e389d0843049.png">
