### ISSUE TITLE
Summary view text doesn't properly obey blocking

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#2011]
Text should not be allowed to overlap in the summary view widgets:
![image](https://cloud.githubusercontent.com/assets/2575/10550179/65f8c428-7413-11e5-8265-dd2d79f21aee.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I think you fixed this?

**Comment by dogmaphobic** [comment]
Yes, I completely redid the summary panel. It's now dynamic and adjusts itself to the screen size.
