### ISSUE TITLE
QGC Not Building in Qt 5.5.* on Mac OS X

### ISSUE THREAD

**Issue by dagoodma** [mavlink/qgroundcontrol#2019]
I just installed Qt 5.5.1 tonight on Mac OS X 10.7.5. I updated QGC to latest commit 92cc42a14756860334d4988fc99b1b86908e699a. When trying to build, I see this:

	:-1: error: No rule to make target '/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build/build-debug/obj/libQGeoServiceProviderFactoryQGC.a', needed by 'debug/qgroundcontrol.app/Contents/MacOS/qgroundcontrol'.  Stop.

I see that QGC developers are still trying to get it working with Qt 5.5.1. How can I help?

PS. Here is a link to the Makefile: http://m4l3.com/upload/Makefile.txt

Qt Creator 3.5.1 (opensource)
Based on Qt 5.5.1 (Clang 6.0 (Apple), 64 bit)
Built on Oct 13 2015 07:35:31
From revision e548635a24

**Comment by dogmaphobic** [comment]
I'm having no issues building on Mac OS, though I'm running 10.10.5. In fact, I was about to target 10.8 as minimum as I was having some other runtime issues. 10.7.5 is a bit on the old end of things. What version of Xcode are you running? What hardware?

**Comment by dogmaphobic** [comment]
Also, are you building from within Qt Creator or from Xcode? It doesn't appear you are running a ghost build. That looks like you are either running from Xcode or changed the default build in Qt Creator.

**Comment by dogmaphobic** [comment]
One more thing, did you rename your makefile to .txt when you uploaded? You should have 3 separate makefiles:
```
-rw-r--r--  1 gus  staff    41902 Oct 17 03:23 Makefile
-rw-r--r--  1 gus  staff  6784140 Oct 17 03:23 Makefile.QGCApplication
-rw-r--r--  1 gus  staff    94275 Oct 17 03:23 Makefile.QGCLocationPlugin
```

**Comment by dagoodma** [comment]
On Mac OS X 10.7.5 the latest version of Xcode I can use is 4.6.3, but it does provide the mac 10.8 sdk. So targetting 10.8 as a minimum works for me. My macbook is a 2008 with intel core 2 duo x64. I don't think many people run anything earlier than that.

I also tried Qt 5.5.0, and I see the same error after doing a clean build. I did change the default build in Qt Creator though. Currently I am using clang 64bit, with clang 4.2 (425.0.28 -- based on llvm32.svn) for target x86_64-apple-darwin11.4.2. Here's the qmake call from my build config:

    qmake /Users/dagoodma/Documents/qgroundcontrol/QGCApplication.pro -r -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug

I am building from Qt Creator:
Qt Creator 3.4.2 (opensource)
Based on Qt 5.5.0 (Clang 6.0 (Apple), 64 bit)
Built on Jun 29 2015 01:54:07
From revision b57ac109a2

I did rename the Makefile to .txt so that it could be read as a text file on the webserver. I do not see Makefiles ending with .QGCApplcation and .QGCLocationPlugin. I think that may be related to my issue. This is all I see in my build directory:
	-rw-r--r--   1 dagoodma  staff  5413631 Oct 17 01:48 Makefile
	drwxr-xr-x   6 dagoodma  staff      204 Oct 16 22:57 build-debug
	drwxr-xr-x   3 dagoodma  staff      102 Oct 16 22:57 debug

where build-debug is a directory with temporary build files, and debug holds qgroundcontrol.app/.

Here is the output when I run the qmake command listed above

	Project MESSAGE: Mac build
	Project MESSAGE: Debug flavor
	Project MESSAGE: BASEDIR /Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol DESTDIR /Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build/debug TARGET QGCApplication OUTPUT /Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build
	Project WARNING: No MAVLink dialect specified, only common messages supported.
	Project MESSAGE: Skipping support for XBee API (unsupported platform)
	Project MESSAGE: Skipping support for 3DConnexion mice (unsupported platform)
	Project MESSAGE: Skipping support for RT-LAB (unsupported platform)
	Project MESSAGE: Including support for speech output
	Project MESSAGE: Including support for Zeroconf (Bonjour)
	Project MESSAGE: Skipping support for video streaming (GStreamer libraries not installed)
	Project MESSAGE:   You can download it from http://gstreamer.freedesktop.org/data/pkg/osx/
	Project MESSAGE:   Select the devel package and install it (gstreamer-1.0-devel-1.x.x-x86_64.pkg)
	Project MESSAGE:   It will be installed in /Libraries/Frameworks

**Comment by dagoodma** [comment]
I also tried Qt 5.4.2, and I have the same issue. What am I doing wrong?

**Comment by dagoodma** [comment]
Turns out I had opened the QGCApplication.pro project, and was trying to build that instead of qgroundcontrol.pro. I also had to change **QMAKE_MAC_SDK** to *macosx10.8* in *QGCCommon.pri*.

**Comment by dagoodma** [comment]
Another issue.

    :-1: error: framework not found XCTest

I need to disable testing, because I don't have the XCTest.framework for my version of XCode, and I don't have the option of upgrading my XCode since Apple has dropped support for my model of macbook.

I am going to try compiling in Release mode to see if that disable unit testing.

**Comment by dagoodma** [comment]
Another issue. This one is strange.

    :-1: error: framework not found -Wl

For some reason my clang++ is not behaving as expected. Trying to figure this out still. Here is the full output:

    make VERBOSE=1
    ( test -e Makefile.QGCLocationPlugin || /usr/local/Qt5.5.1/5.5/clang_64/bin/qmake /Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/QGCLocationPlugin.pro -spec macx-clang CONFIG+=x86_64 -o Makefile.QGCLocationPlugin ) && make -f Makefile.QGCLocationPlugin
    make[1]: Entering directory '/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build-release'
    make[1]: Nothing to be done for 'first'.
    make[1]: Leaving directory '/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build-release'
    ( test -e Makefile.QGCApplication || /usr/local/Qt5.5.1/5.5/clang_64/bin/qmake /Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/QGCApplication.pro -spec macx-clang CONFIG+=x86_64 -o Makefile.QGCApplication ) && make -f Makefile.QGCApplication
    make[1]: Entering directory '/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build-release'
    echo "extern \"C\" { const char *git_version() { return \"v2.7.1-478-g92cc42a\"; } }" > git_version.cpp && clang++ -c -g git_version.cpp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -weak_framework -Wl,-rpath,/usr/local/Qt5.5.1/5.5/clang_64/lib -o release/qgroundcontrol.app/Contents/MacOS/qgroundcontrol build-release/obj/qextserialport.o build-release/obj/qextserialenumerator.o build-release/obj/qextserialport_unix.o build-release/obj/qextserialenumerator_osx.o build-release/obj/qwt_abstract_legend.o build-release/obj/qwt_abstract_scale.o build-release/obj/qwt_abstract_scale_draw.o build-release/obj/qwt_abstract_slider.o build-release/obj/qwt_analog_clock.o build-release/obj/qwt_arrow_button.o build-release/obj/qwt_clipper.o build-release/obj/qwt_color_map.o build-release/obj/qwt_compass.o build-release/obj/qwt_compass_rose.o build-release/obj/qwt_counter.o build-release/obj/qwt_curve_fitter.o build-release/obj/qwt_dial.o build-release/obj/qwt_dial_needle.o build-release/obj/qwt_dyngrid_layout.o build-release/obj/qwt_event_pattern.o build-release/obj/qwt_graphic.o build-release/obj/qwt_interval.o build-release/obj/qwt_knob.o build-release/obj/qwt_legend.o build-release/obj/qwt_legend_data.o build-release/obj/qwt_legend_label.o build-release/obj/qwt_magnifier.o build-release/obj/qwt_math.o build-release/obj/qwt_null_paintdevice.o build-release/obj/qwt_painter.o build-release/obj/qwt_painter_command.o build-release/obj/qwt_panner.o build-release/obj/qwt_picker.o build-release/obj/qwt_picker_machine.o build-release/obj/qwt_pixel_matrix.o build-release/obj/qwt_plot.o build-release/obj/qwt_plot_axis.o build-release/obj/qwt_plot_canvas.o build-release/obj/qwt_plot_curve.o build-release/obj/qwt_plot_dict.o build-release/obj/qwt_plot_grid.o build-release/obj/qwt_plot_item.o build-release/obj/qwt_plot_layout.o build-release/obj/qwt_plot_magnifier.o build-release/obj/qwt_plot_marker.o build-release/obj/qwt_plot_panner.o build-release/obj/qwt_plot_picker.o build-release/obj/qwt_plot_rasteritem.o build-release/obj/qwt_plot_scaleitem.o build-release/obj/qwt_plot_seriesitem.o build-release/obj/qwt_plot_spectrogram.o build-release/obj/qwt_plot_svgitem.o build-release/obj/qwt_plot_xml.o build-release/obj/qwt_plot_zoomer.o build-release/obj/qwt_point_mapper.o build-release/obj/qwt_point_data.o build-release/obj/qwt_raster_data.o build-release/obj/qwt_round_scale_draw.o build-release/obj/qwt_scale_div.o build-release/obj/qwt_scale_draw.o build-release/obj/qwt_scale_engine.o build-release/obj/qwt_scale_map.o build-release/obj/qwt_scale_widget.o build-release/obj/qwt_series_data.o build-release/obj/qwt_slider.o build-release/obj/qwt_spline.o build-release/obj/qwt_symbol.o build-release/obj/qwt_text.o build-release/obj/qwt_text_engine.o build-release/obj/qwt_text_label.o build-release/obj/qwt_thermo.o build-release/obj/qwt_transform.o build-release/obj/qwt_wheel.o build-release/obj/qwt_widget_overlay.o build-release/obj/QGCAudioWorker.o build-release/obj/CmdLineOptParser.o build-release/obj/LinkConfiguration.o build-release/obj/LinkManager.o build-release/obj/LogReplayLink.o build-release/obj/MAVLinkProtocol.o build-release/obj/MockLink.o build-release/obj/MockLinkFileServer.o build-release/obj/MockLinkMissionItemHandler.o build-release/obj/TCPLink.o build-release/obj/UDPLink.o build-release/obj/FlightDisplayWidget.o build-release/obj/FlightDisplayViewController.o build-release/obj/FlightMapSettings.o build-release/obj/GAudioOutput.o build-release/obj/HomePositionManager.o build-release/obj/Joystick.o build-release/obj/JoystickManager.o build-release/obj/LogCompressor.o build-release/obj/main.o build-release/obj/MissionEditorController.o build-release/obj/MissionManager.o build-release/obj/QGC.o build-release/obj/QGCApplication.o build-release/obj/QGCComboBox.o build-release/obj/QGCDockWidget.o build-release/obj/QGCFileDialog.o build-release/obj/QGCLoggingCategory.o build-release/obj/QGCPalette.o build-release/obj/QGCQmlWidgetHolder.o build-release/obj/QGCQuickWidget.o build-release/obj/QGCSingleton.o build-release/obj/QGCTemporaryFile.o build-release/obj/CoordinateVector.o build-release/obj/ParameterEditorController.o build-release/obj/ScreenToolsController.o build-release/obj/QGCQGeoCoordinate.o build-release/obj/QGroundControlQmlGlobal.o build-release/obj/QmlObjectListModel.o build-release/obj/FileManager.o build-release/obj/UAS.o build-release/obj/UASMessageHandler.o build-release/obj/LogReplayLinkConfigurationWidget.o build-release/obj/MainWindow.o build-release/obj/MAVLinkDecoder.o build-release/obj/MAVLinkSettingsWidget.o build-release/obj/QGCCommConfiguration.o build-release/obj/QGCLinkConfiguration.o build-release/obj/QGCMapRCToParamDialog.o build-release/obj/QGCMAVLinkLogPlayer.o build-release/obj/QGCPluginHost.o build-release/obj/QGCTCPLinkConfiguration.o build-release/obj/QGCUDPLinkConfiguration.o build-release/obj/SettingsDialog.o build-release/obj/MainToolBarController.o build-release/obj/QGCUnconnectedInfoWidget.o build-release/obj/UASMessageView.o build-release/obj/MissionItem.o build-release/obj/PX4AirframeLoader.o build-release/obj/SerialLink.o build-release/obj/SerialConfigurationWindow.o build-release/obj/QGCFlightGearLink.o build-release/obj/QGCJSBSimLink.o build-release/obj/QGCXPlaneLink.o build-release/obj/CameraView.o build-release/obj/HILDockWidget.o build-release/obj/ChartPlot.o build-release/obj/IncrementalPlot.o build-release/obj/LinechartPlot.o build-release/obj/Linecharts.o build-release/obj/LinechartWidget.o build-release/obj/Scrollbar.o build-release/obj/ScrollZoomer.o build-release/obj/MultiVehicleDockWidget.o build-release/obj/QGCDataPlot2D.o build-release/obj/QGCHilConfiguration.o build-release/obj/QGCHilFlightGearConfiguration.o build-release/obj/QGCHilJSBSimConfiguration.o build-release/obj/QGCHilXPlaneConfiguration.o build-release/obj/QGCMAVLinkInspector.o build-release/obj/QGCTabbedInfoView.o build-release/obj/QGCUASFileView.o build-release/obj/QGCUASFileViewMulti.o build-release/obj/UASInfoWidget.o build-release/obj/UASQuickView.o build-release/obj/UASQuickViewGaugeItem.o build-release/obj/UASQuickViewItem.o build-release/obj/UASQuickViewItemSelect.o build-release/obj/UASQuickViewTextItem.o build-release/obj/UASRawStatusView.o build-release/obj/JoystickConfigController.o build-release/obj/CustomCommandWidget.o build-release/obj/CustomCommandWidgetController.o build-release/obj/ViewWidgetController.o build-release/obj/AutoPilotPlugin.o build-release/obj/AutoPilotPluginManager.o build-release/obj/GenericAutoPilotPlugin.o build-release/obj/GenericParameterFacts.o build-release/obj/AirframeComponent.o build-release/obj/AirframeComponentAirframes.o build-release/obj/AirframeComponentController.o build-release/obj/FlightModesComponent.o build-release/obj/FlightModesComponentController.o build-release/obj/PowerComponent.o build-release/obj/PowerComponentController.o build-release/obj/PX4AutoPilotPlugin.o build-release/obj/PX4Component.o build-release/obj/PX4ParameterLoader.o build-release/obj/RadioComponent.o build-release/obj/RadioComponentController.o build-release/obj/SafetyComponent.o build-release/obj/SensorsComponent.o build-release/obj/SensorsComponentController.o build-release/obj/APMFirmwarePlugin.o build-release/obj/ArduCopterFirmwarePlugin.o build-release/obj/ArduPlaneFirmwarePlugin.o build-release/obj/ArduRoverFirmwarePlugin.o build-release/obj/FirmwarePluginManager.o build-release/obj/GenericFirmwarePlugin.o build-release/obj/PX4FirmwarePlugin.o build-release/obj/MultiVehicleManager.o build-release/obj/Vehicle.o build-release/obj/VehicleComponent.o build-release/obj/FirmwareUpgradeController.o build-release/obj/Bootloader.o build-release/obj/PX4FirmwareUpgradeThread.o build-release/obj/FirmwareImage.o build-release/obj/Fact.o build-release/obj/FactMetaData.o build-release/obj/FactSystem.o build-release/obj/FactValidator.o build-release/obj/ParameterLoader.o build-release/obj/FactPanelController.o build-release/obj/VideoItem.o build-release/obj/VideoReceiver.o build-release/obj/VideoStreaming.o build-release/obj/VideoSurface.o build-release/obj/qrc_qgroundcontrol.o build-release/obj/moc_qwt_abstract_legend.o build-release/obj/moc_qwt_abstract_scale.o build-release/obj/moc_qwt_abstract_slider.o build-release/obj/moc_qwt_analog_clock.o build-release/obj/moc_qwt_compass.o build-release/obj/moc_qwt_counter.o build-release/obj/moc_qwt_dial.o build-release/obj/moc_qwt_dyngrid_layout.o build-release/obj/moc_qwt_knob.o build-release/obj/moc_qwt_legend.o build-release/obj/moc_qwt_legend_label.o build-release/obj/moc_qwt_magnifier.o build-release/obj/moc_qwt_panner.o build-release/obj/moc_qwt_picker.o build-release/obj/moc_qwt_plot.o build-release/obj/moc_qwt_plot_canvas.o build-release/obj/moc_qwt_plot_magnifier.o build-release/obj/moc_qwt_plot_panner.o build-release/obj/moc_qwt_plot_picker.o build-release/obj/moc_qwt_plot_zoomer.o build-release/obj/moc_qwt_scale_widget.o build-release/obj/moc_qwt_slider.o build-release/obj/moc_qwt_text_label.o build-release/obj/moc_qwt_thermo.o build-release/obj/moc_qwt_wheel.o build-release/obj/moc_QGCAudioWorker.o build-release/obj/moc_LinkInterface.o build-release/obj/moc_LinkManager.o build-release/obj/moc_LogReplayLink.o build-release/obj/moc_MAVLinkProtocol.o build-release/obj/moc_MockLink.o build-release/obj/moc_MockLinkFileServer.o build-release/obj/moc_MockLinkMissionItemHandler.o build-release/obj/moc_ProtocolInterface.o build-release/obj/moc_TCPLink.o build-release/obj/moc_UDPLink.o build-release/obj/moc_FlightDisplayWidget.o build-release/obj/moc_FlightDisplayViewController.o build-release/obj/moc_FlightMapSettings.o build-release/obj/moc_GAudioOutput.o build-release/obj/moc_HomePositionManager.o build-release/obj/moc_Joystick.o build-release/obj/moc_JoystickManager.o build-release/obj/moc_LogCompressor.o build-release/obj/moc_MissionEditorController.o build-release/obj/moc_MissionManager.o build-release/obj/moc_QGCApplication.o build-release/obj/moc_QGCComboBox.o build-release/obj/moc_QGCDockWidget.o build-release/obj/moc_QGCPalette.o build-release/obj/moc_QGCQmlWidgetHolder.o build-release/obj/moc_QGCQuickWidget.o build-release/obj/moc_QGCSingleton.o build-release/obj/moc_QGCTemporaryFile.o build-release/obj/moc_CoordinateVector.o build-release/obj/moc_MavlinkQmlSingleton.o build-release/obj/moc_ParameterEditorController.o build-release/obj/moc_ScreenToolsController.o build-release/obj/moc_QGCQGeoCoordinate.o build-release/obj/moc_QGroundControlQmlGlobal.o build-release/obj/moc_QmlObjectListModel.o build-release/obj/moc_FileManager.o build-release/obj/moc_UAS.o build-release/obj/moc_UASInterface.o build-release/obj/moc_UASMessageHandler.o build-release/obj/moc_LogReplayLinkConfigurationWidget.o build-release/obj/moc_MainWindow.o build-release/obj/moc_MAVLinkDecoder.o build-release/obj/moc_MAVLinkSettingsWidget.o build-release/obj/moc_QGCCommConfiguration.o build-release/obj/moc_QGCLinkConfiguration.o build-release/obj/moc_QGCMapRCToParamDialog.o build-release/obj/moc_QGCMAVLinkLogPlayer.o build-release/obj/moc_QGCPluginHost.o build-release/obj/moc_QGCTCPLinkConfiguration.o build-release/obj/moc_QGCUDPLinkConfiguration.o build-release/obj/moc_SettingsDialog.o build-release/obj/moc_MainToolBarController.o build-release/obj/moc_QGCUnconnectedInfoWidget.o build-release/obj/moc_UASMessageView.o build-release/obj/moc_MissionItem.o build-release/obj/moc_PX4AirframeLoader.o build-release/obj/moc_SerialLink.o build-release/obj/moc_SerialConfigurationWindow.o build-release/obj/moc_QGCFlightGearLink.o build-release/obj/moc_QGCHilLink.o build-release/obj/moc_QGCJSBSimLink.o build-release/obj/moc_QGCXPlaneLink.o build-release/obj/moc_CameraView.o build-release/obj/moc_HILDockWidget.o build-release/obj/moc_ChartPlot.o build-release/obj/moc_IncrementalPlot.o build-release/obj/moc_LinechartPlot.o build-release/obj/moc_Linecharts.o build-release/obj/moc_LinechartWidget.o build-release/obj/moc_Scrollbar.o build-release/obj/moc_ScrollZoomer.o build-release/obj/moc_MultiVehicleDockWidget.o build-release/obj/moc_QGCDataPlot2D.o build-release/obj/moc_QGCHilConfiguration.o build-release/obj/moc_QGCHilFlightGearConfiguration.o build-release/obj/moc_QGCHilJSBSimConfiguration.o build-release/obj/moc_QGCHilXPlaneConfiguration.o build-release/obj/moc_QGCMAVLinkInspector.o build-release/obj/moc_QGCTabbedInfoView.o build-release/obj/moc_QGCUASFileView.o build-release/obj/moc_QGCUASFileViewMulti.o build-release/obj/moc_UASInfoWidget.o build-release/obj/moc_UASQuickView.o build-release/obj/moc_UASQuickViewItem.o build-release/obj/moc_UASQuickViewItemSelect.o build-release/obj/moc_UASRawStatusView.o build-release/obj/moc_JoystickConfigController.o build-release/obj/moc_CustomCommandWidget.o build-release/obj/moc_CustomCommandWidgetController.o build-release/obj/moc_ViewWidgetController.o build-release/obj/moc_AutoPilotPlugin.o build-release/obj/moc_AutoPilotPluginManager.o build-release/obj/moc_GenericAutoPilotPlugin.o build-release/obj/moc_GenericParameterFacts.o build-release/obj/moc_AirframeComponent.o build-release/obj/moc_AirframeComponentController.o build-release/obj/moc_FlightModesComponent.o build-release/obj/moc_FlightModesComponentController.o build-release/obj/moc_PowerComponent.o build-release/obj/moc_PowerComponentController.o build-release/obj/moc_PX4AutoPilotPlugin.o build-release/obj/moc_PX4Component.o build-release/obj/moc_PX4ParameterLoader.o build-release/obj/moc_RadioComponent.o build-release/obj/moc_RadioComponentController.o build-release/obj/moc_SafetyComponent.o build-release/obj/moc_SensorsComponent.o build-release/obj/moc_SensorsComponentController.o build-release/obj/moc_FirmwarePluginManager.o build-release/obj/moc_FirmwarePlugin.o build-release/obj/moc_APMFirmwarePlugin.o build-release/obj/moc_ArduCopterFirmwarePlugin.o build-release/obj/moc_ArduPlaneFirmwarePlugin.o build-release/obj/moc_ArduRoverFirmwarePlugin.o build-release/obj/moc_GenericFirmwarePlugin.o build-release/obj/moc_PX4FirmwarePlugin.o build-release/obj/moc_MultiVehicleManager.o build-release/obj/moc_Vehicle.o build-release/obj/moc_VehicleComponent.o build-release/obj/moc_FirmwareUpgradeController.o build-release/obj/moc_Bootloader.o build-release/obj/moc_PX4FirmwareUpgradeThread.o build-release/obj/moc_FirmwareImage.o build-release/obj/moc_Fact.o build-release/obj/moc_FactMetaData.o build-release/obj/moc_FactSystem.o build-release/obj/moc_FactValidator.o build-release/obj/moc_ParameterLoader.o build-release/obj/moc_FactPanelController.o build-release/obj/moc_VideoItem.o build-release/obj/moc_VideoReceiver.o build-release/obj/moc_VideoSurface.o   -F/usr/local/Qt5.5.1/5.5/clang_64/lib git_version.o -L/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build-release/build-release/obj -lQGeoServiceProviderFactoryQGC -framework IOKit -framework CoreFoundation -F/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/libs/lib/Frameworks -framework SDL -framework QtLocation -framework QtPositioning -framework QtCore -framework DiskArbitration -framework QtQuick -framework QtGui -framework QtQml -framework QtNetwork -framework QtQuickWidgets -framework QtWidgets -framework QtOpenGL -framework QtSvg -framework QtPrintSupport -framework QtConcurrent -framework QtSql -framework QtXml -framework QtSerialPort -framework QtTest -framework Security -framework ApplicationServices -framework Foundation -framework OpenGL -framework AGL
    ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks'
    ld: framework not found -Wl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Makefile.QGCApplication:1421: recipe for target 'release/qgroundcontrol.app/Contents/MacOS/qgroundcontrol' failed
    make[1]: *** [release/qgroundcontrol.app/Contents/MacOS/qgroundcontrol] Error 1
    make[1]: Leaving directory '/Users/dagoodma/Documents/ASL/dubins_area_coverage/qgroundcontrol/build-release'
    Makefile:70: recipe for target 'sub-QGCApplication-pro-make_first-ordered' failed
    make: *** [sub-QGCApplication-pro-make_first-ordered] Error 2

**Comment by dagoodma** [comment]
I compiled llvm 3.6.2 from source to upgrade my clang compiler, but I am still seeing the same issue when running make:

    ld: framework not found -Wl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is my clang version:

    clang version 3.8.0
    Target: x86_64-apple-darwin11.4.2

**Comment by DonLakeFlyer** [comment]
I'm going to close this. we'll try to help, but you are fundamentally doing something we don't support
