### ISSUE TITLE
QtCreator Shadow build support broken

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2020]
This is caused by the build directories inside the repo defines in the build files. Need to change this at some point.

**Comment by dogmaphobic** [comment]
I've been using it fine for Mac OS and Android. Strange...

**Comment by DonLakeFlyer** [comment]
Not working for me in 5.5.1 OS X. Works on Android 5.5.1.

**Comment by dogmaphobic** [comment]
What errors do you see?

**Comment by DonLakeFlyer** [comment]
It's not building qextserialport correctly. It's missing the moc, so that cpp won't compile

**Comment by DonLakeFlyer** [comment]
This isn't a probel on our side. Sometimes shadow build just blows up. Especially on windows.
