### ISSUE TITLE
Pinch gesture halfway working

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2031]
On Qt 5.5.1 the pinch gesture works on the edit view reasonably well, but doesn't work on the fly view.

**Comment by DonLakeFlyer** [comment]
Even on Qt 5.5.1 FlightDisplayView needs a bogus MouseArea workaround. I pulled the one out of FlightMap because I though it would all work on 5.5.1 (which of course was wrong) and I was getting strange results with all my MouseArea's in the Editor.

**Comment by dogmaphobic** [comment]
I will bet it's got something to do with QtQuickWidget. They've broken a whole lot of things in there in 5.5.x. Pinch zoom using the location samples now work just fine, without the hack. Those samples are regular QtQuick apps, not QtQuickWidget.

**Comment by LorenzMeier** [comment]
Closing as stale.
