### ISSUE TITLE
Dragging a waypoint resets its altitude

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2032]
Dragging resets to 0 m altitude. Potentially resets more fields which I'm not seeing.

**Comment by DonLakeFlyer** [comment]
It's only altitude. It's because I use the QGeoCoordinate from the map to reset position and the map QGeoCoordinate values have no altitude. Need to set lat/long individually to leave alt alone.

**Comment by DonLakeFlyer** [comment]
Fixed
