### ISSUE TITLE
Setting Wavepoints

### ISSUE THREAD

**Issue by zshn25** [mavlink/qgroundcontrol#2042]
I went to test my Quad. Its having px4 on a pixhawk with GPS.

I set wavepoints on qgroungcontrol and clicked SET. Then I verified on the onboard. Everything was fine.

First wavepoint: Global  NAV:Waveppoint  Lat Lon Alt, just to takeoff

Simularly I gave 5 more. To move 5 meters North, East, South and west, with same altitude. and last one to Land. I changed NAV:Land

But, the Quad did not follow my mission. It just Loiters above and does nothing else.

I tried changing Global/Abs to Mission but it didnt work

Any solution?

**Comment by DonLakeFlyer** [comment]
If you verified that the waypoints were on the vehiclle correctly, then QGroundControl is doing all that it can do. You are running into some sort of firmware issue or setup issue. You should ask on px4users.
