### ISSUE TITLE
QGC crashes while switching to plan screen with APM firmware on vehicle

### ISSUE THREAD

**Issue by pritamghanghas** [mavlink/qgroundcontrol#2045]
As soon as I click on plan button, it crashes with following messages

MissionManagerLog: writeMissionItems count: 0
MissionManagerLog: _handleMissionRequest sequenceNumber: 0
ASSERT failure in QList<T>::operator[]: "index out of range", file ../../Qt5.5.0/5.5/gcc_64/include/QtCore/qlist.h, line 518
The program has unexpectedly finished.

I am using Qt5.5.0 on Ubuntu 15.04 with AP 3.4-dev

**Comment by DonLakeFlyer** [comment]
I can't repro this. Do you think you could get me a stack trace?
