### ISSUE TITLE
Flight Mode - Channel Selection

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#2074]
When selecting a new Stabilized/Main channel, the automatic channel selection for Altitude Control and Mission do not adapt (see picture).
![screenshot from 2015-10-21 15 34 41](https://cloud.githubusercontent.com/assets/14769636/10659024/b674bc08-789c-11e5-9484-68cba617d8c6.png)

**Comment by DonLakeFlyer** [comment]
Thanks for the bug report

**Comment by DonLakeFlyer** [comment]
Fixed
