### ISSUE TITLE
Ubuntu package dependencies incomplete

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2075]
@dagar I assume the dependencies are imcomplete: We're missing (in theory their runtime equivalents, but I would fall back onto the dev libs for now):

* espeak
* libespeak-dev
* libudev-dev
* libsdl1.2-dev

And probably parts of Qt:
```
./qgroundcontrol: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory
```

**Comment by LorenzMeier** [comment]
@DonLakeFlyer FYI

**Comment by LorenzMeier** [comment]
PPA is also complaining: https://launchpad.net/~qgroundcontrol/+archive/ubuntu/ppa

**Comment by dagar** [comment]
Whoops. I'll separate runtime and development requirements. For running should we just skip the Qt installer (and PATH update that I missed) and throw the libs into the linux "package" (tar.bz2)?

**Comment by dagar** [comment]
I think we'll have to ignore the PPA until we can find a source for 5.5.1 packages.

**Comment by LorenzMeier** [comment]
The ppa got renamed to 5.4.2 and is still available.

I think we should add an installation test but probably run it only for the branch we create the installers on.

**Comment by DonLakeFlyer** [comment]
I'm tossing all the ppa stuff an moving everything to online installer. If folks want to get fancy they are on their one. Working on it now. See the new readme. Almost finished. Verifying that it all works on new windows install, and clean Ubuntu vm.
