### ISSUE TITLE
Mag calibration does not find additional mag

### ISSUE THREAD

**Issue by RomanBapst** [mavlink/qgroundcontrol#2089]

**Comment by DonLakeFlyer** [comment]
Are you talking about the rotation settings showing up? Did you check the parameters after you calibrated to verify they were set correctly? In order for rotation to show up this must be true:

```
    property bool showCompass0Rot: cal_mag0_id.value > 0 && cal_mag0_rot.value >= 0
    property bool showCompass1Rot: cal_mag1_id.value > 0 && cal_mag1_rot.value >= 0
    property bool showCompass2Rot: cal_mag2_id.value > 0 && cal_mag2_rot.value >= 0
```

**Comment by tumbili** [comment]
@LorenzMeier Could you explain what the problem is?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Yes, it didn't show. I need to repro again.

**Comment by DonLakeFlyer** [comment]
If those params don't came back from firmware they won't show. After calibration completes, QGC does a full param refresh, which should pull the new values across and in turn show the appropriate controls.

**Comment by LorenzMeier** [comment]
Could be a ripple of the param hashing, hmm.

**Comment by DonLakeFlyer** [comment]
@NaterGator When is the hash on the QGC side updated?

**Comment by DonLakeFlyer** [comment]
Still a problem? Need exact report steps.

**Comment by NaterGator** [comment]
@DonLakeFlyer sorry I just saw the comment from Oct 23. The hash is recomputed each time the magic parameter is requested.

**Comment by DonLakeFlyer** [comment]
@tumbli ?

**Comment by LorenzMeier** [comment]
Closing as stale.
