### ISSUE TITLE
Add rattitude flight mode support to Flight Modes config

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2138]
https://github.com/PX4/Firmware/pull/3038#issuecomment-151850066

**Comment by kd0aij** [comment]
@scott-eddy Is Rattitude mode broken in the firmware or just not displayed properly in QGC?
I'm setting up a dual-FC Spedix250 to compare CleanFlight/Naze32 with PixRacer. Should be interesting.

**Comment by scott-eddy** [comment]
@kd0aij rattitude is not broken in master, just not displayed properly in QGC

**Comment by kd0aij** [comment]
@scott-eddy Thanks. I thought Rattitude was showing up in QGC at one point too.

**Comment by LorenzMeier** [comment]
Closing as stale.
