### ISSUE TITLE
Crash of qGroundControl owing to the console.

### ISSUE THREAD

**Issue by AlexisTM** [mavlink/qgroundcontrol#2148]
Dear,

When we select something in the console (the log with errors and informations), then "grab" it to qGroundControl window, qGroundControl crash.

**Comment by DonLakeFlyer** [comment]
Sorry but I don't understand what you are saying is the problem. QGroundControl has not console build into it. Can you provide very specific details as to what you are doing and/or screen shots.

**Comment by AlexisTM** [comment]
Indeed, I do not know how to name it. I did a screenshot.

OS : Windows 10

Reproduce it : 
* Select the text (like in the image)
* Left click and hold on the text (drag)
* Drop the text anywhere : Crash

![Image](http://img11.hostingpics.net/pics/215455Capture.png)

**Comment by DonLakeFlyer** [comment]
This dropdown has been replaced.
