### ISSUE TITLE
doxygen

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#2152]
@DonLakeFlyer 

Verify doxygen config and output. Edit as necessary src/documentation.dox
https://s3-us-west-2.amazonaws.com/qgroundcontrol/doxygen/index.html

The generation and upload on travis is quite slow, but only happens once things are merged into master, so hopefully won't be a problem.

**Comment by dagar** [comment]
Still working and uploading every good master build.
https://s3-us-west-2.amazonaws.com/qgroundcontrol/doxygen/inherits.html

**Comment by DonLakeFlyer** [comment]
Yup thanks. I'll start linking to this stuff as part of teh dev guide int he new site.
