### ISSUE TITLE
Plan view does not load the mission the vehicle has currently loaded

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2162]
@DonLakeFlyer Waypoints are only displayed if you click on load, despite that the vehicle shows that they have been loaded on the connection on boot.

**Comment by DonLakeFlyer** [comment]
I can't repro this on very latest master. Maybe it is flaky somehow?

**Comment by LorenzMeier** [comment]
Retrying.

**Comment by LorenzMeier** [comment]
No, confirmed. It only displays once I manually click load. It loads the things before though, as I can see from the PX4 transfer log.

**Comment by LorenzMeier** [comment]
To repro:

1) Go to fly
2) Connect the vehicle
3) Go to plan

In a few cases there will be no mission in the plan view.

**Comment by DonLakeFlyer** [comment]
I tried it with my Iris and can't get a repro

**Comment by DonLakeFlyer** [comment]
At first I thought it wasn't working in the Fly view but my mission was just off screen.
