### ISSUE TITLE
PX4 Home / RTL config screen: Add COM_DISARM_LAND

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2171]
@DonLakeFlyer COM_DISARM_LAND sets the time after which the system automatically disarms after landing. It defaults to 0 = off. This will give you the desired landing behaviour.

**Comment by DonLakeFlyer** [comment]
I'll add to the Saftey screen. Wonder about default to off. That basically means it will not get used.

**Comment by LorenzMeier** [comment]
The default will change. But since disarm mid-air is pretty catastrophic, I want people initially to be able to choose to be a guinea pig.
