### ISSUE TITLE
Add follow-me mode

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2192]
This hopefully fixes the black screen issue. It also add Qt Positioning (GPS) for Android and iOS, which would allow follow-me.

**Comment by dogmaphobic** [comment]
> It also add Qt Positioning (GPS) for Android

This has been working for me with the code Don added a while back (all versions of Android I have and Qt 5.5.1)

**Comment by LorenzMeier** [comment]
I would be interested to experiment with follow-me with that. We should send this message with the GPS coordinates: http://mavlink.org/messages/common#GLOBAL_POSITION_INT

Once we have this I can add support in the Firmware to follow this on a leash. Should be trivial.

**Comment by dogmaphobic** [comment]
I'll wait for Don for that one. The current code gets the local coordinates just once to establish your starting position. It's trivial to get the coordinates continuously though. Get it down the pipe and out to the current vehicle is something Don could probably do a lot faster than I would.

**Comment by thedevleon** [comment]
Any updates on this? I would like to use follow me with QGroundControl :)

**Comment by DonLakeFlyer** [comment]
Because it not implemented: #4427

**Comment by LorenzMeier** [comment]
Closing as stale.
