### ISSUE TITLE
UAVCAN ESC Motor Index and Direction Assignment - Clarification

### ISSUE THREAD

**Issue by pkocmoud** [mavlink/qgroundcontrol#2209]
This should be a toggle button as it is not clear which mode it is in. I notice in NSH that when an ESC is assigned there is output to the console, I feel there needs to be something displayed on this QGC screen as well. There should probably have a timeout to switch from Start to Stop.

**Comment by proficnc** [comment]
agreed.

**Comment by DonLakeFlyer** [comment]
I'm going to need way more detail than that since I know very little about uavcan. QGC only has available to it parameters which it can change/show and information coming to it over mavlink. Can you relate this back to a certainly parameter of mavlink information.

**Comment by proficnc** [comment]
Sounds like we need to get you some Can devices :) 

Ping me or Phill K, I'm sure we can help out (Skype is best for me...
