### ISSUE TITLE
Limit zoom range to available map tiles

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2215]
@dogmaphobic Apparently users think they "deleted the map" when they see this:

https://groups.google.com/d/msg/qgroundcontrol/1-VRXDbI49Q/wiEfg1LWDgAJ

![qgc](https://cloud.githubusercontent.com/assets/1208119/11166147/998464ec-8b28-11e5-9ac4-d3043dd72bae.png)

**Comment by LorenzMeier** [comment]
Note: It looks the same on my devices. This is *not* user or OS specific.

**Comment by dogmaphobic** [comment]
There is no simple way to check and see if this is the case. Given that this only happens if you try to zoom all the way in while in the middle of the ocean, I would put it at a lower priority for the time being.
