### ISSUE TITLE
Implement waypoint with position and generic attributes

### ISSUE THREAD

**Issue by Fojtik** [mavlink/qgroundcontrol#2229]
> I don' t understand what you mean by "Other". There is no MAV_CMD for a mission item
> which is "Other". Did old QGC support this, if so what MAV_CMD was it sending?

Please have a look at the image attached.

For my vehicle it is best to provide several generic fields that are depicted
on the image.

The WAYPOINT has latitude, longitude, altitude, speed and several binary flags that can be
packed to some "free" field. I can do any translation for QGC, but the attributes
obtained from vehicle should be resent during update.

Everything worked fine with previous release. But it suddenly gets broken with new version and no replacement known.

> Ah interesting. I could add a similar thing that just exposes all item settings. The
> Cmd = 0 is very strange though since that isn't a supported MAV_CMD.

I really don't know which CMD to use. I have used something that proves to work.

 > @Fojtik Can you add a separate Issue for adding an Other or something like that item? And attach this image to that Issue?

![qgc_waypoint](https://cloud.githubusercontent.com/assets/2893993/11195503/8a235d56-8cb2-11e5-9774-2eb7585c5ff7.jpg)

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/2261

**Comment by DonLakeFlyer** [comment]
Full editing of all parameters is now supported in raw edit mode. Click the gear icon to get into raw edit. But you have to use one of the existing MAV_CMD ids from the mavlink headers. There is a separate issue on the mavlink side which says that there should be some _USER cmd ids you could use. But that change needs to happen in the mavlink repro.
