### ISSUE TITLE
Number formats not too user friendly

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#2240]
Some numbers are converted to not too friendly formats. For instance, if you enter 5200 (mA) for a battery, it gets converted to:
![screen shot 2015-11-18 at 9 45 25 pm](https://cloud.githubusercontent.com/assets/749243/11262420/003272e8-8e4d-11e5-920d-6ff387eb3c62.png)
Some other numbers are shown with way too many digits of precision:
![screen shot 2015-11-18 at 9 48 31 pm](https://cloud.githubusercontent.com/assets/749243/11262432/181fe318-8e4d-11e5-976e-6436df66cd28.png)
Longitude and Latitude are especially too complicated:
![screen shot 2015-11-18 at 11 39 05 pm](https://cloud.githubusercontent.com/assets/749243/11262476/afa62be8-8e4d-11e5-971e-0b500186ff0b.png)

**Comment by LorenzMeier** [comment]
I presume you're aware we introduced the decimal field in the param meta data for that, but its not propagated completely yet?

As for lat and lon: You're missing that this full precision is required. Any less than that and you start to raster by a couple dozen meters.

**Comment by dogmaphobic** [comment]
> I presume you're aware we introduced the decimal field in the param meta data for that, but its not propagated completely yet?

No, I was not.

> As for lat and lon: You're missing that this full precision is required. Any less than that and you start to raster by a couple dozen meters.

It's not a matter of precision. It's about human readability. A latitude of 64.154549 is a heck lot easier to understand than 641545490*1e7. The first is immediately obvious it is way the heck up north. The other could be either way up north or near the equator. I have to carefully count the digits and make the math to figure it out.

Especially confusing for battery mA. It's a lot simpler to understand 5200mA than 5.2+03mA. Might as well use 5.2A instead.

The default value above is obviously a floating point rounding error. In other words, where the need of precision is required, use straight decimals. Not exponents. When 4 decimal points of precision is enough, limit it to 4, etc.

It's all about minimizing the chances of user error.

**Comment by DonLakeFlyer** [comment]
BAT_CAPACITY is a format string problem in the FactSystem.
Default Value (and min/max) display should use the same float precision as the parameter value uses.
LAT/LON is working correctly and goes through no conversion. Parameter is specified as an int.

**Comment by DonLakeFlyer** [comment]
This is fixed. Lat/Lon is working correct per the parameter type. If you want something other than that it's a firmware change.
