### ISSUE TITLE
Command 245 not supported on Ardupilot 

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2244]
As discussed Command 245 is not recognized on latest build of Ardupilot (3.4dev)

QGroundControl 2.8.0 release on OS X

<img width="424" alt="screen shot 2015-11-19 at 17 34 24" src="https://cloud.githubusercontent.com/assets/3130363/11278755/b535211c-8ee4-11e5-813e-67c3f47ab13d.png">

**Comment by LorenzMeier** [comment]
Connecting QGC to PX4 also results in a bogus initial param save command.
