### ISSUE TITLE
Disconnecting one out of multiple vehicles is not quite right.

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#2252]
If I have two vehicles connected and then disconnect one (shut it down for instance), the UI doesn't recover from it.

If I disconnect the _Current Vehicle_ (the one showing in the tool bar), nothing happens. No messages, no errors, no UI changes. If I however, click the vehicle button and select the other one (the one still connected), the tool bar goes blank (the normal _disconnected_ state).

If I disconnect the _Other Vehicle_, the toolbar goes blank (the normal _disconnected_ state as above).

From that point, there is no return of the toolbar.

![screen shot 2015-11-20 at 12 43 22 am](https://cloud.githubusercontent.com/assets/749243/11292783/b8724b52-8f20-11e5-8828-2e1cf98ea664.png)

**Comment by DonLakeFlyer** [comment]
Is this on current master? If you are using the AutoConnect pull it was most likely broken by that.

**Comment by dogmaphobic** [comment]
It's using your ACWork branch. Let me try master.

**Comment by dogmaphobic** [comment]
Master has similar issues. Can't quite tell because the *Vehicle* button doesn't show up at all so there is no way to select the *other* vehicle.

If I disconnect any vehicle, the toolbar goes blank as well even though one of the vehicles is still connected.

**Comment by dogmaphobic** [comment]
This code makes the items in the toolbar visible or not:
```
Loader {
    source:             multiVehicleManager.activeVehicleAvailable ? "MainToolBarIndicators.qml" : ""
    anchors.left:       parent.left
    anchors.verticalCenter:   parent.verticalCenter
}
```
What exactly is ```multiVehicleManager.activeVehicleAvailable```? Is it asking if the *active* vehicle is available? Maybe the *disconnected* vehicle is still *active* but obviously not available.

I could dig further but I want to get the map caching code done :P

**Comment by DonLakeFlyer** [comment]
> What exactly is multiVehicleManager.activeVehicleAvailable

Basically does what is says. true: there is a vehicle available, false: no vehicle. Kind of the same as multiVehicleManager.activeVehicle == NULL or not. The active vehiclet transition is not working correctly.

**Comment by tfoote** [comment]
I've recently run into this using a recent version 3.0.2

When the actively selected vehicle goes away, the toolbar dissapears and the "Disconnect" button appears. The only way to get back to the toolbar is to click "Disconnect" but that will disconnect all the other vehicles still active on the same mavlink connection. 

![image](https://cloud.githubusercontent.com/assets/447804/20507953/1d8c1db0-b013-11e6-9258-aa99ff749060.png)

**Comment by DonLakeFlyer** [comment]
Retested and this is working correctly
