### ISSUE TITLE
Arducopter sinks into the ground till it hits -40~ft and crashes.

### ISSUE THREAD

**Issue by rahulraghu94** [mavlink/qgroundcontrol#2258]
The copter would bounce around like crazy. I read on another issue that removing the spring coefficient from the arducopter.xml file would resolve the issue. After removal however, the copter sinks into the ground and crashes at -40ft

**Comment by LorenzMeier** [comment]
We're not supporting HIL / SITL with Flightgear for that reason. All this has been stripped in the last release. Please use jMAVSIM as detailed in the PX4 documentation.
