### ISSUE TITLE
Hi-res icon for Android

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#2265]
We need a 512x512 icon for Android (and iOS?).
https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrol

Currently it's using the 256x256 icon scaled to 512x512.

@dogmaphobic can you help with this?

**Comment by LorenzMeier** [comment]
Iconman!

**Comment by dogmaphobic** [comment]
I don't have the original. I will try to come up with something...

**Comment by dogmaphobic** [comment]
I don't have the original art work. I would have to create something from scratch. Aren't we supposed to be getting a new icon? I would wait for that instead.

**Comment by dogmaphobic** [comment]
@dagar I've replaced all the logos throughout the app, including the 512x512 Google App Store one. It's in #3142. Closing...
