### ISSUE TITLE
Android listing new screenshots and description

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#2266]
https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrol

 - [x] tablet screenshot
 - [ ] ~~phone screenshot~~
 - [ ] description
 - [ ] video?

**Description**

http://qgroundcontrol.org/

Main Features
- Open-source MAVLink Micro Air Vehicle Communication Protocol with lightweight serialization functions for microcontrollers
- Windows / Linux / MacOS support
- 2/3D aerial maps (Google Earth support) with drag-and-drop waypoints
- In-flight manipulation of waypoints and onboard parameters (in EEPROM)
- Real-time plotting of sensor and telemetry data
- Logging and plotting of sensor logs
- Support for UDP, serial (radio modem) and mesh networks
- Supports multiple Autopilots (pxIMU, ArduPilotMega, SLUGS, MatrixPilot/UAVDevBoard, many more)
- MAVLink protocol supports up to 255 vehicles in parallel and project-specific custom messages can be added
- Head-up-display, support for digital video transmission/display
- Competition-proven at IMAV and EMAV competitions (QGroundControl was used in the EMAV 2009 1st place Indoor Autonomy entry)

Known Issues:
- Screen real estate issues on tablet's smaller than 7"

**Comment by DonLakeFlyer** [comment]
I think we need to make a call on minimum screen size that we say we currently support. Do we really want to say we support phones at this point?

**Comment by dogmaphobic** [comment]
I can handle the graphics, screen grabs, etc. I'm not going to be the first to volunteer for the copy :)

Regarding sizes, at least on iOS, I limited to iPad for the time being. It's not really usable on smaller screens (phones) until we come up with a reduced functionality UI for them.

**Comment by DonLakeFlyer** [comment]
U defaneatly don wont me for the copie!

**Comment by dagar** [comment]
@DonLakeFlyer do you have a milestone in mind for a wider android release (and this issue)?

**Comment by DonLakeFlyer** [comment]
I'm thinking we go Stable on Android after the 3.0 release. Hoping to get enough APM testers to wring android out some more.

For now I'll grab some more screenshots and clean the store listing up.

**Comment by dagar** [comment]
I've started flying tablet only so I can update the screenshots.

I'm somewhat concerned we're going to receive negative reviews from phone users. I wonder if we should limit distribution to only large phones + tablets. Thoughts?

**Comment by DonLakeFlyer** [comment]
> I wonder if we should limit distribution to only large phones + tablets. Thoughts?

I put in 7" and above in the text. Could you see if there is some way to set that up so that it rejects devices with smaller screens?

**Comment by DonLakeFlyer** [comment]
I just pushed a pile of new screenshots

**Comment by dagar** [comment]
New screenshots look good.

@DonLakeFlyer @LorenzMeier @dogmaphobic - I put the current description in my first comment, please edit it in place and I'll update the play store listing.

**Comment by DonLakeFlyer** [comment]
Let me look at the things like Tower or DJI description looks like for comparison.

**Comment by DonLakeFlyer** [comment]
I updated the description. This should get us far enough for 3.0 release.
------
QGroundControl provides full flight control and configuration for ArduPilot or PX4 powered vehicles. The goal for QGroundControl is improved ease of use for new users as well as high end feature support for experienced users. Support for ArduPilot vehicles is currently in Beta.

QGroundControl features:
- Full configuration support for ArduPilot and PX4 vehicles
- Mission planning for autonomous flight
- Flight map display showing vehicle position, flight track, waypoints and vehicle instruments
- Video streaming with instrument display overlays
- Flight support for any MAVLink capable vehicle
- Competition-proven at IMAV and EMAV competitions

http://qgroundcontrol.org
