### ISSUE TITLE
Waypoint altitude bug

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#2274]
The default altitude for the next waypoint should be taken from the previous one.
Right now the default altitude corresponds to the altitude of the first waypoint on the map.

**Comment by DonLakeFlyer** [comment]
The default altitude is fixed for all waypoints. It isn't pulled from the first waypoint.

**Comment by LorenzMeier** [comment]
It was the last waypoint altitude before, which was quite handy. Could we have that back?

**Comment by DonLakeFlyer** [comment]
Yup. Didn't realize that was there before. I'll add it back.
