### ISSUE TITLE
Mission restart button

### ISSUE THREAD

**Issue by RomanBapst** [mavlink/qgroundcontrol#2275]
What are the alternatives for restarting the mission at the moment?

**Comment by DonLakeFlyer** [comment]
Not currently supported. May a custom command widget and send you own command. Assuming there is a MAV_CMD that will restart mission, don't know.

**Comment by dagar** [comment]
What if in the fly view clicking a waypoint sends MISSION_SET_CURRENT?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @dagar Yes, QGC should send that command on clicking a waypoint.

**Comment by LorenzMeier** [comment]
Closing as stale.
