### ISSUE TITLE
Work out user model for normal and advanced mission editing

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2277]
We need to split these into user and advanced.

To me these are user:

  * MAV_CMD_NAV_WAYPOINT
  * MAV_CMD_NAV_LOITER_TIME
  * MAV_CMD_NAV_RETURN_TO_LAUNCH
  * MAV_CMD_NAV_LAND
  * MAV_CMD_NAV_TAKEOFF
  * MAV_CMD_DO_JUMP

These are advanced. A couple of them like digicam really need to have the planning / area management to really make sense. In that mode they should not be user facing, but the user does the polygon and configures the camera.

  * MAV_CMD_NAV_LOITER_UNLIM
  * MAV_CMD_NAV_LOITER_TURNS
  * MAV_CMD_NAV_GUIDED_ENABLE
  * MAV_CMD_DO_SET_ROI
  * MAV_CMD_DO_GUIDED_LIMITS
  * MAV_CMD_DO_JUMP
  * MAV_CMD_DO_CHANGE_SPEED
  * MAV_CMD_DO_SET_CAM_TRIGG_DIST
  * MAV_CMD_DO_SET_RELAY
  * MAV_CMD_DO_REPEAT_RELAY
  * MAV_CMD_DO_SET_SERVO
  * MAV_CMD_DO_REPEAT_SERVO
  * MAV_CMD_DO_DIGICAM_CONFIGURE
  * MAV_CMD_DO_DIGICAM_CONTROL
  * MAV_CMD_DO_MOUNT_CONTROL
  * MAV_CMD_CONDITION_DELAY
  * MAV_CMD_CONDITION_CHANGE_ALT
  * MAV_CMD_CONDITION_DISTANCE
  * MAV_CMD_CONDITION_YAW

**Comment by DonLakeFlyer** [comment]
Not quite done yet. Command list should change based on firmware type.
