### ISSUE TITLE
Indicate altitude per waypoint

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2278]
It would be nice to have the altitude above home on the map per waypoint. Something like +5, +25, etc. It seems like the best user model I could come up with and would de-confuse a lot about the current mission.

@DonLakeFlyer @dogmaphobic

**Comment by DonLakeFlyer** [comment]
I'm almost afraid to ask: Where? Edit/Fly/Both?

**Comment by LorenzMeier** [comment]
Both. Out of 3 coordinates we're only showing two so far.

**Comment by DonLakeFlyer** [comment]
> Out of 3 coordinates we're only showing two so far.

Huh?

**Comment by LorenzMeier** [comment]
2D position on the map. The altitude is unclear 8)
