### ISSUE TITLE
Bad formating of Latitude and or Longitude

### ISSUE THREAD

**Issue by Fojtik** [mavlink/qgroundcontrol#2280]
I have in LAT displayed a number 137190049871108. Please could you fix double number formating to the left edge.

When LAT contains 51.137190049871108, the number seen in editbox seems crazy.
![wpedit](https://cloud.githubusercontent.com/assets/2893993/11365810/78270ab0-92a9-11e5-90da-33362171bc05.jpg)

When editbox gets automatically scrolled left, you do not see the beginning of the number. It is better to display beginning and let less significant digits not to be displayed unless you scroll them.

**Comment by DonLakeFlyer** [comment]
This is a bug with decimal places. Lat/Lon/Alt should be limited to 7 decimals places. Which in turn prevents it from scrolling out of view.

**Comment by DonLakeFlyer** [comment]
Tried to repro. Decimal places seem to working correctly. This image looks to be from an older build. I think that was fixed after that. Can you try a new daily?

**Comment by Fojtik** [comment]
Where to find daily build?
I has been asked you by Email, but this Email has been dropped and unread.

The daily build is no longer available from here:
http://www.qgroundcontrol.org/downloads

**Comment by LorenzMeier** [comment]
Just look again. Its all there and has always been.

**Comment by Fojtik** [comment]
Yes, now it works again.

Before while the Windows download has been broken:
<Error><Code>AccessDenied</Code><Message>Access 
Denied</Message><RequestId>1004EAAA5C1A4035</RequestId><HostId>xIs24tYD5CuPFh7NV3V2E96SNCs
XlolYgP82Bn2yGIIZtaumeceq7Z6oNrLLvh+ULnxs0fxzjh4=</HostId></Error>

**Comment by LorenzMeier** [comment]
Is the number display fixed for you? Can we close this?

**Comment by Fojtik** [comment]
Yes, I do not notify this issue.
