### ISSUE TITLE
qgcvideo.pro in qgroundcontrol

### ISSUE THREAD

**Issue by jilinggui** [mavlink/qgroundcontrol#2319]
Hi，guys，can you tell me how qgcvideo.pro work in qgroundcontrol ,i really loss.
thanks!

**Comment by dogmaphobic** [comment]
As far as I can tell, that *project* is prehistoric and should be removed.

**Comment by jilinggui** [comment]
thanks again dogmaphobic.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Any reason to not toss this?

**Comment by DonLakeFlyer** [comment]
Removed
