### ISSUE TITLE
Autoconnect: QGC does not auto-connect after successful Firmware Upgrade

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2336]
As the title says. It just sits there and shows nothing, which is very confusing from an user perspective.

**Comment by LorenzMeier** [comment]
I also switched to the summary perspective if it was just locking on the firmware upgrade dialog. But even then I think it would be better to auto-connect and push the user to the summary screen, as he will not want to upgrade Firmware again.

**Comment by DonLakeFlyer** [comment]
Is this on latest master? Just tried it an it worked fine.

**Comment by LorenzMeier** [comment]
Yes, latest master the moment I reported it. I can re-test.

**Comment by DonLakeFlyer** [comment]
Maybe that was when auto connect was really slow? Don't quite understand. Can you retry again? If it doesn't work. Run with --logging:LinkManagerLog,MultiVehicleManagerLog so I can try to debug remotely.

**Comment by DonLakeFlyer** [comment]
I've hit this intermittently, but still not sure why.

**Comment by LorenzMeier** [comment]
Closing as stale.
