### ISSUE TITLE
iOS MessageDialog and Text Field issues

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#2338]
Putting here so it doesn't get lost:

The *MessageDialog* QML Item does not work on iOS.
The *TextField* (or our derived QGCTextField) does not bring up the keyboard for you to enter text.

Given that these seem to work on pure QML code, my only assumption is that it has something to do with QtQuick inside QtWidget.

These two are a show stopper for iOS.

**Comment by DonLakeFlyer** [comment]
> The TextField (or our derived QGCTextField) does not bring up the keyboard for you to enter text.

Most likely needs additional hinting like this:
https://github.com/mavlink/qgroundcontrol/blob/master/src/FactSystem/FactControls/FactTextField.qml#L21

**Comment by dogmaphobic** [comment]
I tried using TextField straight (not QGCTextField) with and without hints. It all works on Android. Just not on iOS.

**Comment by dogmaphobic** [comment]
The example code, which is a pure QML application, runs fine. It might look weird (not a system dialog) but it works. That's what makes me believe it's an issue with QtQuick inside QtWidgets. My guess is that we won't have a viable iOS app until we are fully away from QtWidgets.

![img_0093](https://cloud.githubusercontent.com/assets/749243/11569970/c42bc5fc-99c2-11e5-9e07-7629ec37b673.PNG)

![img_0094](https://cloud.githubusercontent.com/assets/749243/11569976/c878a7f6-99c2-11e5-9bce-295477535baf.PNG)

![img_0095](https://cloud.githubusercontent.com/assets/749243/11569982/cc673d64-99c2-11e5-86db-63d998886040.PNG)

**Comment by DonLakeFlyer** [comment]
I’d enter a bug. Maybe we can get a fix in next Qt. That may happen before we get rid of QQuickWidget.

**Comment by dogmaphobic** [comment]
Well, moving away from QtWidgets fixed it all :)
