### ISSUE TITLE
Should Mission Item use NAV_ACC_RAD/NAV_LOITER_RAW as default

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2344]
Instead of hardcoded values. Would require plugin support. Seems to make sense though.

**Comment by LorenzMeier** [comment]
I'm closing this as these are fallbacks when you set these to zero. It complicates things too much. Using zero to trigger the on-vehicle default seems like something we should officially document. The radius sets a "band" for the mission and allows the operator to weight accuracy over having to go back or go slower.
