### ISSUE TITLE
Map zoom level should go higher

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2368]
If you use Mission Planner or Tower you'll see that they allow you to zoom higher past the level where there are tiles available. They just blow up the last tile available to a larger size. This makes sense since the last zoom level available if too low for accurate positioning. Not sure exactly how high to go. Lorenz may have an idea of that in relationship to GPS accuracy.

**Comment by LorenzMeier** [comment]
The three related issues are closed, closing as done.
