### ISSUE TITLE
the focus doesn't move to value field when invoked and doesn't get removed on escape.

### ISSUE THREAD

**Issue by pritamghanghas** [mavlink/qgroundcontrol#2398]
when I press escape on the side dialogs. The whole window becomes small and even after I maximize it after that, the screen is unusable. I have to switch screen and come back to use it.

**Comment by pritamghanghas** [comment]
![escapes_leads_to_this](https://cloud.githubusercontent.com/assets/6928727/11790471/0aea5c4e-a2c2-11e5-964c-f2b8a92a8c84.png)
![maximizing after that leads to this](https://cloud.githubusercontent.com/assets/6928727/11790519/44981f12-a2c2-11e5-8761-3f03f00c6fbb.png)

**Comment by DonLakeFlyer** [comment]
Parameter editor dialog has Escape key handling:
```
            Keys.onReleased: {
                if (event.key == Qt.Key_Escape) {
                    reject()
                }
            }
```

Seems to work on OSX. Maybe an Ubuntu only problem.

**Comment by pritamghanghas** [comment]
ok, I will have a look why its not working on Ubuntu, being largely on
Ubuntu will make it easier for me.

On Tue, Dec 15, 2015 at 12:33 AM, Don Gagne <notifications@github.com>
wrote:

> Parameter editor dialog has Escape key handling:
>
>             Keys.onReleased: {
>                 if (event.key == Qt.Key_Escape) {
>                     reject()
>                 }
>             }
>
> Seems to work on OSX. Maybe an Ubuntu only problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/2398#issuecomment-164527449>
> .
>



-- 
Regards,
pritam

**Comment by pritamghanghas** [comment]
ok some debugging results. The text field never gets focus on its own. If I
click on it to give it focus and then press escape, it correctly goes away
but the window still minimizes but the screen remains usable. If I invoke
text field correctly gains focus. Does that trigger any ideas.

On Tue, Dec 15, 2015 at 12:38 AM, pritam.ghanghas@gmail.com <
pritam.ghanghas@gmail.com> wrote:

> ok, I will have a look why its not working on Ubuntu, being largely on
> Ubuntu will make it easier for me.
>
> On Tue, Dec 15, 2015 at 12:33 AM, Don Gagne <notifications@github.com>
> wrote:
>
>> Parameter editor dialog has Escape key handling:
>>
>>             Keys.onReleased: {
>>                 if (event.key == Qt.Key_Escape) {
>>                     reject()
>>                 }
>>             }
>>
>> Seems to work on OSX. Maybe an Ubuntu only problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mavlink/qgroundcontrol/issues/2398#issuecomment-164527449>
>> .
>>
>
>
>
> --
> Regards,
> pritam
>



-- 
Regards,
pritam

**Comment by DonLakeFlyer** [comment]
I pulled out moving the focus to the text field a while back because it was causing other problems. Likely the whole handling of Escape needs to be reworked. I'd just pull it out for now. And then add an issue which says to add Escape/Enter and focus support for dialogs. Then we can figure out the right way to do this.

**Comment by pritamghanghas** [comment]
I will dig at it for a while tomorrow before pulling it out. you pulled out
only forcing the focus there. The property focus: true is still there and
somehow it is getting focus correctly once I have clicked on it even if
invoked again. Something else going on.

On Tue, Dec 15, 2015 at 1:21 AM, Don Gagne <notifications@github.com> wrote:

> I pulled out moving the focus to the text field a while back because it
> was causing other problems. Likely the whole handling of Escape needs to be
> reworked. I'd just pull it out for now. And then add an issue which says to
> add Escape/Enter and focus support for dialogs. Then we can figure out the
> right way to do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/2398#issuecomment-164540551>
> .
>



-- 
Regards,
pritam

**Comment by pritamghanghas** [comment]
this is partly fixed by #2425. Changed the title accordingly.

**Comment by DonLakeFlyer** [comment]
I have this almost fixed now. Need to do some more testing as well as double check would Qml Dialog control is implemented.

**Comment by pritamghanghas** [comment]
great. I would love to see how did you fixed it. My knowledge of qml is not
even at beginner level. I read through docs but didn't really work.

On Sat, Dec 26, 2015 at 3:19 AM, Don Gagne <notifications@github.com> wrote:

> I have this almost fixed now. Need to do some more testing as well as
> double check would Qml Dialog control is implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/2398#issuecomment-167263906>
> .
>



-- 
Regards,
pritam
