### ISSUE TITLE
No prevention of flight plan loss

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#2408]
please add warning on application exit, or activity that could remove planned, but unsaved, mission.

**Comment by DonLakeFlyer** [comment]
Still need to fix:
1) Offline edit
2) Connect to Vehicle
3) Waypoints from Vehicle stomp offline edit waypoints

**Comment by DonLakeFlyer** [comment]
Also the prompt dialogs are incorrect. Still showing placeholder text.

**Comment by DonLakeFlyer** [comment]
Prompt dialogs are fixed

**Comment by DonLakeFlyer** [comment]
> Still need to fix:
> 1) Offline edit
> 2) Connect to Vehicle
> 3) Waypoints from Vehicle stomp offline edit waypoints

This sequence is already working correctly.
