### ISSUE TITLE
Manual control fixed point scaling off by a factor of 10.

### ISSUE THREAD

**Issue by FrauBluher** [mavlink/qgroundcontrol#2411]
Line 1603 of UAS.cc scales manual input by a factor of 1000, when fixed point scaling should be percentage in 10ths of a percent, i.e. -10000 to 10000, not -1000 to 1000.

Offending line:
1603	            const float axesScaling = 1.0 * 1000.0;

**Comment by DonLakeFlyer** [comment]
MANUAL_CONTROL message are in the range -1000 to 1000. See https://pixhawk.ethz.ch/mavlink/#MANUAL_CONTROL for spec. I don't see anything wrong here.
