### ISSUE TITLE
Request: example plugin for mavlink processing and visualization.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#2423]
Please make a plugin, that has easy access til all UAVparamters, and mavlink messages.
The plugin could have an example for a text box, changing color,  displaying and speaking a warning if/when a parameter og mavlink provided data  exceeds a certain limit.
It could have a gauge, displaying something, for example voltage.
Then a button that would toggle or change a parameter.

The idea is to simply demonstrate how to display some values and labels, and provide a way of interacting with parameters, reading them, or acting on change.  
- For parameters, it would be nice to have a template for a button/text box that could read and set a parameter.

Such "tinker on your own" plugin would be a great place to start for people who are new to GUI, and needs to customize or add functionality to fly safely with more complex UAVs.

For example, it would make it easy to customize monitor and provide warning about unusual flaps setting before takeoff or telemetry droprate.

**Comment by LorenzMeier** [comment]
We have this by now!
