### ISSUE TITLE
AutoConnect very flaky on APM Stack

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2447]

**Comment by DonLakeFlyer** [comment]
Need this change https://github.com/PX4/Firmware/issues/3420 in order to remove script start from QGC side.

**Comment by LorenzMeier** [comment]
This is fixed on PX4 master, you can go ahead here now.

**Comment by DonLakeFlyer** [comment]
Thanks Lorenz.
