### ISSUE TITLE
QGroundControl 2.8.0 crashes on start on Intel HD 3000 Video on Windows 7 64bit

### ISSUE THREAD

**Issue by suraqis** [mavlink/qgroundcontrol#2449]
I found a bug, but I can't tell for sure who's one it is: QGroundControl, Intel or Qt. When I started QGroundControl 2.8.0 daily or stable it permanently crashes. My system is 64bit Windows 7. I find that system leaves message in system log about crash:

Faulting application name: qgroundcontrol.exe, Version: 2.0.0.227, time stamp: 0x567c515e
Name the failed module: ig4icd32.dll, Version: 9.17.10.2884, timestamp 0x5127e6d9
Exception code: 0xc0000005
Offset error: 0x000011d9
The ID of the failed process: 0x17d4
Faulting application start time: 0x01d13e97af177b34
Faulting application path: C: \ Program Files (x86) \ qgroundcontrol \ qgroundcontrol.exe
The path of the failed module: C: \ Windows \ system32 \ ig4icd32.dll
Code Report: f18e58c3-aa8a-11e5-a0dd-9cb70ded38b3

 ig4icd32.dll - is Intel HD 3000 video driver library. I tried latest and older one and nothing changed. QGroundControl 2.7.1 runs without problems. When I switched to nVidia driver for application manually then QGroundControl started correctly.

**Comment by DonLakeFlyer** [comment]
The problem is with the Intel OpenGL driver. They are known to be crap. Stick with nVidia drivers.
