### ISSUE TITLE
QGroundControl 2.8 waypoint settings icon disappears

### ISSUE THREAD

**Issue by suraqis** [mavlink/qgroundcontrol#2450]
In flight plan mode waypoint settings icon (gearwheel) disappears when changing waypoint coordinate frame or checking out "autocontinue" checkbox.

**Comment by DonLakeFlyer** [comment]
This is correct behavior. There are two modes, "friendly edit" and "raw edit". Clicking the gear takes you to raw edit where you have access to all settings. If you change a setting which can not be represented by friendly edit the gear will go away and you can't go back.

**Comment by suraqis** [comment]
tricky as for me, but ok.

**Comment by DonLakeFlyer** [comment]
For usability there should probably be some way to get back to friendly edit or some indiacator as to what happened. I'll enter a separate issue for that.

**Comment by suraqis** [comment]
I think that hiding icon is not the best way to show changes. Maybe it's better to deactivate and dim it.

**Comment by DonLakeFlyer** [comment]
Issue #2453
