### ISSUE TITLE
QGroundControl 2.8 fullscreen mode menu bug

### ISSUE THREAD

**Issue by suraqis** [mavlink/qgroundcontrol#2452]
In QGroundControl 2.8 on Windows when switched to fullscreen application menus and other drop down menus are not dropping down. When out from fullscreen menu restores.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic This seems to ring a bell with someone you hit way back when. Is that correct?

**Comment by dogmaphobic** [comment]
Yeah, but that was iOS. I'll take a look at it.

**Comment by DonLakeFlyer** [comment]
I'm building it right now. I'm actually thinking of just tossing that fullscreen thing. Let the OS handle full screen if it supports it instead of GGC.

**Comment by DonLakeFlyer** [comment]
Actually it looks like Windows QtCreator on my laptop is hosed. So won't get to this till tomorrow.

**Comment by dogmaphobic** [comment]
Yep, I was able to reproduce it. It appears to be a Qt bug.
https://forum.qt.io/topic/56234/combobox-and-menu-doesn-t-work-in-full-screen-qml

**Comment by DonLakeFlyer** [comment]
I'd rip out fullscreen then.

**Comment by dogmaphobic** [comment]
On it...
