### ISSUE TITLE
Validate compass offsets for correctness

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2456]
In Copter-3.2.1 and later offsets are considered acceptable provided their combined “length” is less than 600 (i.e. sqrt(offset_x^2+offset_y^2+offset_Z^2) < 600)

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Any usefullness to do the same similar thing for PX4 Compass Cal on QGC side? To idenitify bad cal, or bad compass positioning? Not sure if firmware side already does such a thing.

**Comment by LorenzMeier** [comment]
Probably. The APM devs are always confused by assuming a zero offset is a good thing (which is meaningless). However, the measurement range is 1.4 gauss and the earth field strength is 0.6 gauss, so 0.6 + 0.6 = 1.2 is just below the maximum range the default sensor can handle.

**Comment by DonLakeFlyer** [comment]
So what you are saying is that this is an upper bound, but in fact there is a possible lower bound as well?

**Comment by LorenzMeier** [comment]
Not really, since length has no sign. So just checking for 0.6 gauss does the trick.

**Comment by DonLakeFlyer** [comment]
I don't quite understand all this stuff. So just to be clear. Is it ok to add the same:

sqrt(offset_x^2+offset_y^2+offset_Z^2) < 600

check to PX4 compass cal and warn if >= 600?

**Comment by LorenzMeier** [comment]
PX4 uses SI units, so it would be 0.6 gauss. I can handle that if you like - I would be more than happy to trade the implementation time for the tuning sliders.

Done: https://github.com/PX4/Firmware/commit/3bb733018beb033ff067861005ee8c5bcced34a0

If you are happy with the APM state you can close this one.

**Comment by DonLakeFlyer** [comment]
This hasn't been implemented yet in APM Compass Cal.

**Comment by DonLakeFlyer** [comment]
Implemented on APM side now
