### ISSUE TITLE
Broad adoption: Phone support and professional users

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2480]
@DonLakeFlyer @dogmaphobic Now that setup is largely worked out it would be good to understand what role phone support has for broader adoption. Given that Pixracer (and any other new autopilot) ship with Wifi, many users will prefer to use their phone in the field. The drone + laptop user base is melting away rapidly.

I see three tiers emerging:

  * DIY: FPV racing and simple missions, wants phone, has no laptop (or finds it cumbersome). Few have a tablet.
  * Professional: Want coverage planning, geofences, mapping missions. Have currently laptops but would love to move on to tablets
  * Setup & Developers: Use their laptop on the bench and in the field

My gut feeling is that adoption will depend on 1+2, not 3 because developers tend to eventually support what users want and use something else for their own use (down to using Python scripts). Right now we are not serving 1) or 2) effectively yet.

The main pain points are likely:

  * Mobile phone screen support (at least on a iPhone 6 size and upwards - not full-featured as on tablet, but enough to do things like flight mode selection, RTL or planning a basic mission)
  * Coverage planning for pro users

Of course it also raises the questions of the iOS app store presence, but thats a technicality in comparison to the others.

**Comment by dogmaphobic** [comment]
I think this has all been resolved by #3333?
