### ISSUE TITLE
Airframe configuration pictures - OS X QGC 2.8.0-346-g9ae456c (Development) build

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2491]
Need more variants and pics for airframe selection (copter) for APM

Current:

<img width="1316" alt="screen shot 2015-12-29 at 04 02 36" src="https://cloud.githubusercontent.com/assets/3130363/12029382/b3c7ca98-ade1-11e5-8107-f056b6927363.png">

Mission Planner 

<img width="509" alt="screen shot 2015-12-29 at 04 09 05" src="https://cloud.githubusercontent.com/assets/3130363/12029389/fb3aa0d0-ade1-11e5-9025-eb304f9f143f.png">

APM Planner

<img width="639" alt="screen shot 2015-12-29 at 04 10 31" src="https://cloud.githubusercontent.com/assets/3130363/12029400/2bda4c72-ade2-11e5-94c8-ce5311eb5e81.png">

**Comment by lvale** [comment]
Linked to #2440

**Comment by DonLakeFlyer** [comment]
The other issue here is that the frame types show up differently based on what firmware you are running.

**Comment by lvale** [comment]
I'm running Hexa so perhaps Hexa frames should come out ?

**Comment by DonLakeFlyer** [comment]
I"ve dumbed down the UI for now with no images. Coming at some point will be auto-generate images which include correct prop rotation, motor numbers and pixhawk wiring. Once we have that this will get nicer again.
