### ISSUE TITLE
Standard Params in MP vs OS X QGC 2.8.0-346-g9ae456c (Development) build

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2493]
Some discrepancy between what's on the Standard Params on MP and not exposed at the current interface on QGC. Some like Arming Checks and Auto Tune Bitmask are not IMHO "power user" material :)

**Comment by DonLakeFlyer** [comment]
Arming Checks and AutoTune are in. I'll wait for people to bitch to add any more.
