### ISSUE TITLE
Windows build release error!

### ISSUE THREAD

**Issue by CornerOfSkyline** [mavlink/qgroundcontrol#2494]
error: C2039: 'TypeMock' : is not a member of 'LinkConfiguration'
When i build the qgc in the windows use Qt Creator 3.5.1 . There is error when build the release , it seems the QT_DEBUG not worked in some files.

**Comment by DonLakeFlyer** [comment]
There is likely something wrong with your configuration. Your going to to have to track it down yourself most likely. Windows biulds are working fine as far as I can tell.

**Comment by CornerOfSkyline** [comment]
@DonLakeFlyer I try adding CONFIG-=debug_and_release to the qmake additional arguments, it's ok.
