### ISSUE TITLE
Need some mechanism to capture logging from Android builds

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2520]

**Comment by DonLakeFlyer** [comment]
Will consider for 3.0, but I think it's unlikely.

**Comment by dagar** [comment]
Which logging are you referring to?

We do get some crash information if the user chooses to submit.

https://play.google.com/apps/publish/?dev_acc=03583851360351630691#ErrorClusterDetailsPlace:p=org.mavlink.qgroundcontrol&et=CRASH&lr=LAST_6_MONTHS&ecn=Native+crash&tf=unknown&tc=unknown&tm=unknown&nid=57f3a59d758e6758&an&c&s=new_status_desc

**Comment by DonLakeFlyer** [comment]
QLoggingCategory logging.

**Comment by dogmaphobic** [comment]
It goes out to logcat. At runtime, you can run ```adb logcat``` and all logging (including QGC's) will be output. You can even capture it using WiFi if you don't have the device connected directly (USB).

logcat: http://developer.android.com/tools/help/logcat.html
adb: http://developer.android.com/tools/help/adb.html

**Comment by DonLakeFlyer** [comment]
> It goes out to logcat.

Not helpful on users machine. They won't have that installed. I'm talking about using logging to debug a problem a user is having.

**Comment by DonLakeFlyer** [comment]
I'd guess the logcat logs are sitting on the tablet somewhere. Wonder if there is a tablet app that you can run to look at them?

**Comment by DonLakeFlyer** [comment]
I'm planning to move this to 3.1 release. Speak up now if you disagree.

**Comment by DonLakeFlyer** [comment]
Build on Nate's stuff.

**Comment by DonLakeFlyer** [comment]
I think this is going to be needed for 3.0 in order to aid debuting android user problems
