### ISSUE TITLE
Integrate survey code

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2526]
From David Goodman:

I've released the code available here: http://dagoodma.github.io/dppl_code/. The QGC branch still needs to be merged and fixed up a little before a pull request, but it's available here: https://github.com/dagoodma/qgroundcontrol/tree/dpp_addon_dtspascpp.

**Comment by dagar** [comment]
I don't like the idea of pulling dppl in as a binary and passing around json. I'll try to get it building with qmake and then include it as a submodule.

**Comment by DonLakeFlyer** [comment]
It should just be in the main tree. Shouldn't be a submodule either. I plan to look at the code and re-work as needed to bring it in. I'll handle bringing this in after the 3.0 release goes out. Don't want it before then.

**Comment by DonLakeFlyer** [comment]
@dagar I'll ping you when I get to this for help.

**Comment by DonLakeFlyer** [comment]
Related to Issue #2507

**Comment by DonLakeFlyer** [comment]
Tracking in #2507
