### ISSUE TITLE
linux gstreamer exact dependencies

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#2540]
Document exact Ubuntu gstreamer dependencies and install them on travis-ci. Currently the documentation says to install everything which is probably excessive.

    sudo apt-get install gstreamer1.0*
    sudo apt-get install libgstreamer1.0*

**Comment by DonLakeFlyer** [comment]
@dagar Still something to do here?

**Comment by dagar** [comment]
I'll come back to this the next time I need to install gstreamer.
