### ISSUE TITLE
Mission Editor: When you scroll the waypoint list it also zooms the map below it

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2544]
Also scrolling by dragging with the mouse doesn't seem to work.

**Comment by DonLakeFlyer** [comment]
The MouseArea to catch clicks and add new items is interfering with drag movement.

**Comment by AndreasAntener** [comment]
What I just noticed is that dragging with my trackpad screws it up to the point where clicking and and dragging with the mouse also doesn't work anymore.

**Comment by DonLakeFlyer** [comment]
Yup. Was looking at that last night.
