### ISSUE TITLE
Mission Editor: Pan/Scroll gets stuck and then you can't click on any map buttons

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2548]
@AndreasAntener Are you running on a Mac and panning with a trackpad?

**Comment by AndreasAntener** [comment]
Yup

**Comment by DonLakeFlyer** [comment]
To get it unstuck, do some small two finger zoom things a couple time and eventually it will come back. Looks like Qt bug. Going to have to figure out a workaround.

**Comment by DonLakeFlyer** [comment]
This looks to be a problem when you use the Map control in our hybrid QQuickWidget setup. It doesn't happen in a native qml window. Sigh!

**Comment by DonLakeFlyer** [comment]
Yup, I verified it by hacking desktop to run as Native Qml.

**Comment by DonLakeFlyer** [comment]
This problem shows up on all Flickable/ScrollView/ListView containers scrolled using a Mac trackpad.

**Comment by DonLakeFlyer** [comment]
The fix for this is not going to make it into 3.0 release. Needs to wait for widget conversion to Qml.

**Comment by DonLakeFlyer** [comment]
Check if this is still there with 5.8

**Comment by DonLakeFlyer** [comment]
Still not working correctly in 5.8. We'll live without pinch on mac trackpad
