### ISSUE TITLE
APM: GCS failsafe option in safety screen

### ISSUE THREAD

**Issue by pritamghanghas** [mavlink/qgroundcontrol#2552]
screenshot of mission planner, helpful when vehicle is driven by GCS in autonomous or guided mode.
http://copter.ardupilot.com/wp-content/uploads/sites/2/2012/01/RadioFailsafe_MPSetup.png

**Comment by billbonney** [comment]
GCS Failsafe works in all mode in Plane, ie. when contact is lost the plane will trigger a failsafe. In Copter GCS_Failsafe only works in RC_OVERIDE mode.

**Comment by DonLakeFlyer** [comment]
Is there anything more than the FS_GCS_ENABL parameter for this?

**Comment by pritamghanghas** [comment]
Looking at APM code seems to suggest that it will be active for arducopter also in guided mode. 
https://github.com/diydrones/ardupilot/blob/master/ArduCopter/events.cpp#L174
