### ISSUE TITLE
Flaps for a quad ?? QGC (from master) on OSX

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2555]
While doing radio setup on PX4 do we really need to ignore the flaps setting up (i.e. Skip it)? As it is a quad the prompting for flaps is kind of unnecessary...imho :)

<img width="1435" alt="screen shot 2016-01-08 at 16 35 01" src="https://cloud.githubusercontent.com/assets/3130363/12205694/0cb6cdfc-b634-11e5-822a-885595fe539e.png">

<img width="646" alt="screen shot 2016-01-08 at 17 18 38" src="https://cloud.githubusercontent.com/assets/3130363/12204583/e4668ef2-b62c-11e5-9fb7-604a08f9b1b8.png">

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Which MAV_TYPE's are Flaps valid?
