### ISSUE TITLE
PX4 - QGC setting quad - Power tab

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2556]
Setting up a Quad using PX4 master on the power tab there is no place to set up the battery capacity, that has to be set on the Parameters screen. I believe it makes sense to have the Battery capacity on the Power Tab.

<img width="993" alt="screen shot 2016-01-08 at 16 59 52" src="https://cloud.githubusercontent.com/assets/3130363/12205663/e9fb7696-b633-11e5-8c14-b06a8b804e83.png">

<img width="1074" alt="screen shot 2016-01-08 at 17 00 07" src="https://cloud.githubusercontent.com/assets/3130363/12205677/f3f34ca0-b633-11e5-9c6a-68db5c7330a1.png">

**Comment by DonLakeFlyer** [comment]
Although there is a BAT_CAPACITY parameter I'm not sure anything triggers off of that value? Hence, setting it does nothing interesting.

**Comment by lvale** [comment]
Theoretically if the "reserve capacity" is reached then Failsafe gets active. And the reserve is calculated by Design capacity - consumption (mAh)= remainder > reserve cap


<img width="276" alt="screen shot 2016-01-11 at 00 04 02" src="https://cloud.githubusercontent.com/assets/3130363/12224983/05142f6c-b7f7-11e5-88ac-189b3b18f739.png">

**Comment by lvale** [comment]
Just checked the code and it's being verified here:

https://github.com/diydrones/ardupilot/blob/8fdbb36827ca489df157984c4a8b444a7300a6e4/libraries/AP_BattMonitor/AP_BattMonitor.cpp#L274

**Comment by lvale** [comment]
Sorry. Wrong fw. I was thinking APM.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is the bat capacity (maH) used anywhere on PX4 stack? Seems like I remember it wasn't yet.
