### ISSUE TITLE
QGC default map location

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2560]
I believe that the default location shown on the map could be saved on the last location received by a vehicle instead of just jumping back to SF.

Example: I disconnected the vehicle while in Europe, and as soon I disconnected the location map just jumped back to the pic.....

Also, some display of coordinates would be useful. Perhaps a crosshair in the middle of the view, and the location would be of the crosshair position.

<img width="1440" alt="screen shot 2016-01-09 at 13 47 28" src="https://cloud.githubusercontent.com/assets/3130363/12216410/253a70f0-b6d8-11e5-9f34-3a768cecff0a.png">

**Comment by lvale** [comment]
@DonLakeFlyer 
Sorted, thanks.
But :)

Vehicle had GPS lock and then was disconnected and this screen is correct, i.e. remained at the last known GPS Pos.

<img width="1436" alt="screen shot 2016-01-15 at 01 01 27" src="https://cloud.githubusercontent.com/assets/3130363/12342606/dbb00e0e-bb23-11e5-92d0-9d92455f6ada.png">


but if I move to the planning tab it goes back to SF

Shouldn't it inherit the GPS pos ??

<img width="1438" alt="screen shot 2016-01-15 at 01 01 38" src="https://cloud.githubusercontent.com/assets/3130363/12342615/ffdef04c-bb23-11e5-93cf-b6b586f4d10e.png">

**Comment by DonLakeFlyer** [comment]
I can make it do that.

**Comment by DonLakeFlyer** [comment]
It's doesn't inherit the GPS position, because that ui is only created when you click the tab. If you never clicked the tab, then it never saw the gps position go by because it wasn't running.

**Comment by lvale** [comment]
I believe it makes sense to "inherit" the last known good position, in this case from the Fly tab.

**Comment by DonLakeFlyer** [comment]
This is going to require some restructuring of the Fly View. The Map and Video items need to be persistent and just switch size and z-order. Otherwise you can't depend on the Fly view being around. By re-loading the items, the Fly view also also loses state like position I think, and re-creating all the mission and flight lines is expensive on the switch.

Other option is to leave things along and just push the map position out of the inner Map control up to the parent. This is doable as well. Likely easier, but still not sure if it's better the re-structure map/video setup.

@dogmaphobic Did you happen to try this structuring first and run into problems? Not sure yet if it's worth the effort to restructure map/video switching mechanism.

**Comment by dogmaphobic** [comment]
> Did you happen to try this structuring first and run into problems? Not sure yet if it's worth the effort to restructure map/video switching mechanism.

I'm not even sure I understand what you are asking :)

The whole Map view UI code has changed so much since I first created, I can't barely recognize it. What is it that it is desired and it's not working?

**Comment by DonLakeFlyer** [comment]
Currently the PIP and Map change positions by reloading themselves into loaders. So they are desrtroyed/re-created on the swap. There is a main view loader and a PIP loader. I'm wondering if instead it would be better to just have the two items always in existence and just change size/position/z-order when you want to swap. That would you have a persisten connection to the Fly view that you can use for other things. Which is what I need to be able to carry over Fly view map position into Plan view map.

**Comment by dogmaphobic** [comment]
Tricky but should be doable. I will take a stab at it. I want to get *Over The Air* firmware update done first though...

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Sending to you for the Fly View change, then back to me the fix Plan view.

**Comment by dogmaphobic** [comment]
Working on it...
