### ISSUE TITLE
Wrong VDOP displayed

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2561]
When connected to APM 3.3.2 copter this value is wrong (I'll have to check but I think is not sent by APM)

<img width="398" alt="screen shot 2016-01-09 at 13 31 27" src="https://cloud.githubusercontent.com/assets/3130363/12216450/9df78086-b6d9-11e5-8165-c0fe531a0c73.png">

**Comment by dogmaphobic** [comment]
That means the value was not present. The receiving code initializes the value to 1e10f (an absurd value) to indicate it's not present. The dialog missed that and it's displaying it any way. It should just say "N/A" (or something along those lines).

**Comment by dogmaphobic** [comment]
@lvale Can you please check and see if this indeed resolved the issue?
Thanks!

**Comment by lvale** [comment]
It's ok now. But spotted another issue. I'll open it

<img width="737" alt="screen shot 2016-01-10 at 13 17 30" src="https://cloud.githubusercontent.com/assets/3130363/12221706/2f0ef972-b79e-11e5-85ca-1e720a35211c.png">
