### ISSUE TITLE
QGC connected to 3DR radio beachballs on exit

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2569]
When I have it connected to a 3DR radio (and not to USB) it goes into an endless loop on exit. I have to kill the app manually.

**Comment by LorenzMeier** [comment]
This is on Mac OS X 10.10

**Comment by DonLakeFlyer** [comment]
I tried repro'ing by doing the following:
- Radio connected to desktop, boot QGC, boot Vehicle, turn off Vehicle
- Radio connected to desktop, boot QGC, boot Vehicle, shutdown QGC
- Radio connected to desktop, boot QGC, boot Vehicle, pull desktop USB radio plug

All worked fine.

**Comment by LorenzMeier** [comment]
This was with two radio pairs on the same frequency. Maybe it triggered a freak condition inside QGC. Closing for now.
