### ISSUE TITLE
Airframe Config Icons

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2599]
First let's list out the needed icons and  consistent filenaming:
* Helicopter
  * Single rotor - Helicopter
  * Coaxial rotor - HelicopterCoaxial
* Flying Wing
  * Simple version (no rotors) - FlyingWing
  * VTOL Duo Tailsitter - VTOLDuoRotorTailSitter
  * VTOL Quad Tailsitter - VTOLQuadRotorTailSitter
* VTOL tiltrotor - VTOLTiltRotor
* Multi Rotor
  * Quad Rotor
    * Plus - QuadRotorPlus
    * X - QuadRotorX
    * V-Tail - QuadRotorVTail
    * A-Tail - QuadRotorATail
    * Wide - QuadRotorWide
  * Quad Rotor H Frame - QuadRotorH
  * Hexa Rotor
    * Plus - HexaRotorPlus
    * X - HexaRotorX
  * Octo Rotor
    * Plus - OctoRotorPlus
    * X - OctoRotorX
    * Coaxial Plus - OctoRotorPlusCoaxial
    * Coaxial X - OctoRotorXCoaxial
  * Tri Copter
    * Plus - YPlus
    * Minus - YMinus
    * Y6A - Y6A
    * Y6B - Y6B
* Rover - Rover
* Boat - Boat
* Plane
  * Standard - Plane
  * Inverted V Tail - PlaneATail
  * VTOL - VTOLPlane
* Simulation - AirframeSimulation
* Unknown - AirframeUnknown

The concept here is that the top most level of bullets specifiy a base "chassis" visual for the icon. This creates a consistent base visual. Then the sub-bullets vary that base chassis by adding rotors. I assume the extension for all is .svg.

We'll also use these names as the available set for airframe meta data xml image field. I'll include back-compat for old names in old meta data files. Note that for Aiframe MetaData image field use there is no file extension.

**Comment by cfelipesouza** [comment]
Great @DonLakeFlyer! Just to clarify, I split into two sets just to organize myself and the file I sent you. I totally agree that both should use the same icons. :)

**Comment by DonLakeFlyer** [comment]
Issues with current set:
- There is only one set of airframe icons for QGC that encompass both PX4 and APM. No need to split them out into two sets. A QuadRotor Plus icon for example is the same for both PX4 and APM.
- I think the Helicopter should use the same color circle rotor visualization as the others (instead of showing individual blades).
![screen shot 2016-01-13 at 11 06 08 am](https://cloud.githubusercontent.com/assets/5876851/12304696/bf7006a2-b9e5-11e5-8e21-b4365a9304b0.png)

**Comment by DonLakeFlyer** [comment]
@cfelipesouza First set of comments are good to go. I'm working to integrate the current set into the codebase now.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier For the Coaxial setups do those have Plus and X variants?

**Comment by LorenzMeier** [comment]
We have Coaxial in + and x layout, yes. Although I think the + layout is not flown by anyone any more these days.

a foo coaxial has foo / 2 rotors on top and bottom each. So a coaxial octorotor has 8 rotors.

**Comment by DonLakeFlyer** [comment]
Ok, so we need Coaxial Icons in both style. I'll update the icon list.

**Comment by dogmaphobic** [comment]
> Ok, so we need Coaxial Icons in both style. I'll update the icon list.

I assume only for Octos, not Hexa (Y config)?

**Comment by DonLakeFlyer** [comment]
Removed Hexa Coxial from list since these are Y6A and Y6B variations.

**Comment by DonLakeFlyer** [comment]
Changed TriCopter naming to YPlus/YMinus to match Y6A/Y6B naming.

**Comment by dogmaphobic** [comment]
Isn’t a tri Copter one where the tail has a servo to tilt it? In that case, Y6A/Y6B are Hexa Coaxials, right?

**Comment by DonLakeFlyer** [comment]
TriCopter is three blade Y configuration (PX4/APM seem to use this naming) and Y6* for Hexa Coaxial.

For a Hexa Coaxial in PX4 terminology, which one is it:
![screen shot 2016-01-13 at 1 17 25 pm](https://cloud.githubusercontent.com/assets/5876851/12308091/0ee9ffe6-b9f8-11e5-820d-a9e038457c2f.png)
![screen shot 2016-01-13 at 1 17 37 pm](https://cloud.githubusercontent.com/assets/5876851/12308092/0f17000e-b9f8-11e5-98a0-5659b6034c4e.png)

**Comment by DonLakeFlyer** [comment]
Drawing bug, Heli is png, Flying Wing is svg:
![screen shot 2016-01-13 at 1 22 08 pm](https://cloud.githubusercontent.com/assets/5876851/12308204/bb24e0be-b9f8-11e5-8205-a13934399bb3.png)

**Comment by cfelipesouza** [comment]
Here is the new icon set. Waiting for comments before export. :)

![qcg_icons](https://cloud.githubusercontent.com/assets/7512740/12357375/a233260a-bb8e-11e5-9c67-5d6208b7f109.png)

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is this one correct (it's not supposed to be coaxial):
![screen shot 2016-01-15 at 10 07 30 am](https://cloud.githubusercontent.com/assets/5876851/12360942/db5dac4e-bb6f-11e5-8886-67aeb3de9c86.png)

**Comment by DonLakeFlyer** [comment]
Oops, Also does one work in Light theme?
![screen shot 2016-01-15 at 10 09 28 am](https://cloud.githubusercontent.com/assets/5876851/12360983/20d5f308-bb70-11e5-97a5-b2332863bbea.png)

**Comment by cfelipesouza** [comment]
For sure.
Light Theme color background is #d9d9d9

![qcg_icons_light](https://cloud.githubusercontent.com/assets/7512740/12361055/ea3ac89a-bba2-11e5-8997-bb6d7e67f320.png)

**Comment by LorenzMeier** [comment]
@DonLakeFlyer The quad tailsitter is ok.

**Comment by DonLakeFlyer** [comment]
Awesome we're good to fo then. Thanks @cfelipesouza

**Comment by DonLakeFlyer** [comment]
Ok, just tested this and we can close this now. Thanks everyone.

Found two bugs:
-  #2686
- https://github.com/PX4/Firmware/issues/3562
