### ISSUE TITLE
Do not allow people to start QGC with sudo

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2608]
Too many stupid people run QGC with sudo to work around not having configured their system properly. Here is one way to work out if someone is running with root: http://stackoverflow.com/questions/26552517/get-system-username-in-qt

**Comment by DonLakeFlyer** [comment]
Do you mean that the username will come back as "root" in these cases?

**Comment by LorenzMeier** [comment]
I haven't tested it, but that was my thinking.

**Comment by dogmaphobic** [comment]
Hmm, not sure about that. For Linux/Mac you would use uid. It returns 0 for root. This is irrelevant for Windows any way.

**Comment by dogmaphobic** [comment]
You want to call ```getuid()```. If it returns 0, it's root (or sudo).
http://linux.die.net/man/2/getuid
