### ISSUE TITLE
Usability, scrolling lists

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2614]
On APM parameters, the scrolling list of parameters when too long and scrolled to the bottom, when changing to a smaller list does not appear.

Example:
Check this:
<img width="1440" alt="screen shot 2016-01-15 at 00 46 56" src="https://cloud.githubusercontent.com/assets/3130363/12342872/8d168fb8-bb26-11e5-8ebd-f14d217d1ebe.png">

scroll down to the bottom of this list:

<img width="1440" alt="screen shot 2016-01-15 at 00 47 08" src="https://cloud.githubusercontent.com/assets/3130363/12342879/9dc7d6b4-bb26-11e5-9f5b-dd8e92379211.png">

now move to a smaller list of parameters like LAND, and the list is apparently empty

<img width="1439" alt="screen shot 2016-01-15 at 00 47 18" src="https://cloud.githubusercontent.com/assets/3130363/12342888/c293eb54-bb26-11e5-9dd6-e50d24dd329c.png">

but no, it's hidden at the top....

<img width="1438" alt="screen shot 2016-01-15 at 00 47 30" src="https://cloud.githubusercontent.com/assets/3130363/12342903/d4c1082a-bb26-11e5-94f1-f009ecff5254.png">

Also there is no user feedback if the list is greater than one screen, so you'll have to try to scroll it to see if something is there, either up or down.

**Comment by DonLakeFlyer** [comment]
Related to #2469 which I just moved to 3.0.

**Comment by DonLakeFlyer** [comment]
Tracking scroll feedback in #2649

**Comment by lvale** [comment]
@DonLakeFlyer In this case it might be something else. I believe that when a new item is selected on the left list it should "reinitialize" the position of the list to be at the top, so that when one changes from category at the left, the list is always "painted" from the beginning.

**Comment by DonLakeFlyer** [comment]
I know. I fixed that in #2618
