### ISSUE TITLE
QGC not dispalying params < e-3

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#2620]
I was looking a the ekf2 parameters in QGC and noticed that e.g. 5e-4 is not displayed anymore but just appears as zero.  It looks like QGC has a hard limit of three on the decimal places.
I think the best solution would be to write them in the format 'xe-y' in that case.

**Comment by LorenzMeier** [comment]
Those params are missing the decimals meta field on the PX4 side

**Comment by tumbili** [comment]
Thanks, closing then!
