### ISSUE TITLE
Cannot connect more than one vehicle on current master.

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#2630]
The output shows QGC connecting but the UI does not reflect multiple connections.

```
LinkManagerLog: New heartbeat on link:vehicleId:vehicleMavlinkVersion:vehicleFirmwareType:vehicleType  "/dev/cu.usbmodem1" 1 3 12 1
LinkManagerLog: New heartbeat on link:vehicleId:vehicleMavlinkVersion:vehicleFirmwareType:vehicleType  "Default UDP Link" 1 3 12 2
```

The UI only shows the USB link. There is no way to see the one connected on UDP.

**Comment by DonLakeFlyer** [comment]
Are you sure your vehicles don't have the same id?

**Comment by dogmaphobic** [comment]
Crap. I changed the wrong ID on all 3 vehicles. I changed Comp ID instead of Sys ID. Tired...
