### ISSUE TITLE
Joystick: Connect button to generic COMMAND_LONG

### ISSUE THREAD

**Issue by rjehangir** [mavlink/qgroundcontrol#2644]
Allow mapping of joystick to generic COMMAND_LONG messages, primarily to support custom APM stacks, payloads, etc.

Requested to support ArduSub: https://github.com/bluerobotics/ardupilot

**Comment by DonLakeFlyer** [comment]
This could use the same Mission Item mini-editors which are basically just COMMAND_LONG editors. This would give nice access to all existing COMMAND_LONG as well as custom COMMAND_LONGs. Not to mention making it very easy to implement.

Depends a bit on this: https://github.com/mavlink/mavlink/pull/480 to get known user commands into mavlink.

**Comment by rjehangir** [comment]
We no longer need this feature.
