### ISSUE TITLE
Mission: Allow mission map to be disabled for non-autonomous vehicles

### ISSUE THREAD

**Issue by rjehangir** [mavlink/qgroundcontrol#2646]
Allow the mission map to be disabled (possibly via a MAVLink message) to support the ease-of-use goal for vehicles that are not autonomous. This supports FPV setups and custom stacks.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Another MAV_PROTOCOL_CAPABILITY add? In this case it should be a negative, no mission support bit I think.

**Comment by rjehangir** [comment]
No longer needed for us.
