### ISSUE TITLE
Log Download for APM

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2649]
Some more options would be nice for APM vehicle Log download:

Currently it seems that we have to do it one at a time and there is no feedback. 

<img width="462" alt="screen shot 2016-01-16 at 20 51 19" src="https://cloud.githubusercontent.com/assets/3130363/12374442/768f80f6-bc93-11e5-8082-a692d6b08f9d.png">

I would suggest something more like what APM Planner has:

<img width="605" alt="screen shot 2016-01-16 at 20 56 55" src="https://cloud.githubusercontent.com/assets/3130363/12374447/c67d43aa-bc93-11e5-912a-36f1489d6621.png">

<img width="758" alt="screen shot 2016-01-16 at 20 57 12" src="https://cloud.githubusercontent.com/assets/3130363/12374449/d27a3780-bc93-11e5-8e37-93a12e268a72.png">

**Comment by DonLakeFlyer** [comment]
Makes sense

**Comment by dogmaphobic** [comment]
It's all there. Expand the window to see the other fields and select any number of files for download (Command-A for everything).

P.S. It must *rain* a lot in **W**estern **E**uropean **T**ime :P

![screen shot 2016-01-16 at 4 23 35 pm](https://cloud.githubusercontent.com/assets/749243/12374588/dd4cb190-bc6d-11e5-9e65-c3d0b041d1fe.png)

**Comment by lvale** [comment]
Thanks @dogmaphobic. Usable but no intuitive. I didn't think of resizing the dialog box, and the multiple selection is obvious AFTER we know about it :)

https://www.youtube.com/watch?v=gL0CzPQ0pAQ

Now those disconnects and reconnects kill me :)

**Comment by dogmaphobic** [comment]
Those voice messages are basically useless and extremely annoying! As to the link lost/regained, how are you connecting?

**Comment by dogmaphobic** [comment]
Closing as the issue itself is not valid. The crazy link connect/disconnect should be a new issue.

**Comment by lvale** [comment]
Please consider resizing the widget on first time it opens.

**Comment by dogmaphobic** [comment]
> Please consider resizing the widget on first time it opens.

It should have a sensible default. Obviously that's not working. Let me reopen and deal with that then.

**Comment by lvale** [comment]
If I may suggest to have the column Status as First column and the ID either don't show it or have it as last column.

**Comment by dogmaphobic** [comment]
If you don't have GPS, the dates are all the same. The index is all you have to go by.

**Comment by LorenzMeier** [comment]
I don't think it makes sense to spend a lot of time on the widget, as we still don't have it on tablets then - shouldn't a fix maybe be done straight in QML?

**Comment by dogmaphobic** [comment]
It's all QML. Just the *container* is a widget.

**Comment by DonLakeFlyer** [comment]
> It's all QML. Just the container is a widget.

Ooh, that might be a problem if I try to do the Native QMl thing on desktop. In that case I think the only Qml can be main window. Hmm.

**Comment by dogmaphobic** [comment]
#2654 takes care of the connection loss.

**Comment by lvale** [comment]
Thanks @dogmaphobic
