### ISSUE TITLE
Screen goes off on Android tablet

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2650]
Latest beta on Android tablet.

Screen goes off. I would suggest an option to force screen on settings.

Also no widgets on Android (I was trying to download logs from vehicle)

**Comment by DonLakeFlyer** [comment]
Widgets on Android is going to take some time. Do you think Log Download is critical on tablet? You won't be able to do anything other than pull it off the tablet to a desktop.

**Comment by lvale** [comment]
No hurry for the widgets. The log download is important while you're configuring a vehicle and we must examine the log, like to set the value to TH_MID. Although I still use the Mac on the field :)

The screen turning off is more annoying.

**Comment by DonLakeFlyer** [comment]
V3.0 for screen going Off. 3.1 for the rest.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you take a look at this. Also not sure if WAKE_LOCK is correct: http://stackoverflow.com/questions/4195682/android-disable-screen-timeout-while-app-is-running

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Maybe one more stab at this for Android and iOS, then give up till 3.1? Android more important that iOS since it will move to Stable with 3.0.

**Comment by dogmaphobic** [comment]
iOS is working (has been for quite a while). I could not find a way to make it work on Android.

**Comment by DonLakeFlyer** [comment]
Moving to 3.1 then
