### ISSUE TITLE
Configuration UI does not get re-evaluated on parameter write

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2655]
@DonLakeFlyer To repro:

(this is not PX4 specific, but I have a test case to repro)

1) Reset the PX4 config
2) Set COM_RC_IN_MODE = 1
3) The RC calibration UI / check should now turn OK (instead of red) since it got disabled. But it only does once you read back the params from the vehicle completely, not when the write of the param is confirmed

I think the UI is triggered off the wrong param callback - it should refresh when the local list is confirmed to be good (changed and no retries left), not just when the remote list is requested.

**Comment by DonLakeFlyer** [comment]
The param trigger list is missing fromthe component.
