### ISSUE TITLE
Plan View: Altitude map shows NaN

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2665]
On Plan Screen the first time we enter on that screen, usually a NaN is displayed at the bottom:

<img width="1169" alt="screen shot 2016-01-18 at 12 10 03" src="https://cloud.githubusercontent.com/assets/3130363/12391088/2307968a-bddd-11e5-94af-bc1d2242a5a3.png">

**Comment by DonLakeFlyer** [comment]
I ended up having to pull the altitude values off the altitude map since there just wasn't room for the values. So at this point the map just shows you relative visual differences for all itemes.
