### ISSUE TITLE
QGC - OS X Location services

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2666]
Hi,

Again on the maps position :).

Considering that the OS has location services (at least OS X, IOS and Android have), couldn't QGC query the base OS for location and display the map if the OS reports a valid location, perhaps using a option for "Use current location for Map Center" to enable that, similar to the Center Map on Vehicle option.

**Comment by DonLakeFlyer** [comment]
If the OS supports map location then that is what happens now. Location is only support nu Qt in Android and iOS at this point.

**Comment by lvale** [comment]
ok, although that's why I haven't seen any requests by QGC to OS X location services:

<img width="665" alt="screen shot 2016-01-18 at 23 27 12" src="https://cloud.githubusercontent.com/assets/3130363/12405351/366becc2-be3b-11e5-9dc1-8f5cc5915dc9.png">

**Comment by DonLakeFlyer** [comment]
Closing this for now, since QGC already supports this. Boot up android tablet with no vehicle and map will move ot tablet location.
