### ISSUE TITLE
Crashing on startup on Windows 7 and 10 (2.8)

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#2671]
A user has [reported](http://discuss.px4.io/t/qgrountcontroll-neuste-stabile-versiob/95/5) that his QGC crashes on startup on Win7 and Win10 and only works in the XP compatibility mode. 

![screenshot](https://photos-5.dropbox.com/t/2/AADCh-SDO-oILt-CdZTx2I6QPuYCI6-9XVmYFxQ5jF0hXg/12/219123245/jpeg/32x32/3/1453161600/0/2/Qg.jpg/EOav6qQBGLuEASACKAI/FvuVbTdePrs0UOS6rrcvBn8TgRJfY3DF3r9e8rbX27I?size_mode=5&size=32x32)

**Comment by NaterGator** [comment]
Can you get more information about the machine it is crashing on? CPU, GPU, etc?

**Comment by DonLakeFlyer** [comment]
Can you get a crash dump: http://www.qgroundcontrol.org/bugreporting?

**Comment by DonLakeFlyer** [comment]
Also check the graphics driver. Intel graphics drivers are known to crash in OpenGl.

**Comment by julianoes** [comment]
No more information was provided by the user, closing.
