### ISSUE TITLE
Bug in the vehicle selector

### ISSUE THREAD

**Issue by marianobianchi** [mavlink/qgroundcontrol#2681]
I'm having problems connecting two UAVs with QGC. When i start QGC and connect both UAVs, they show in the map correctly. But when i try to select one of them to, for example, set a new mission, i can only select one of them, as showed in the next picture:

![initial_menu](https://cloud.githubusercontent.com/assets/1700075/12482023/fc5fa864-c02b-11e5-8ff4-aeb09104535a.png)

When i select the only option that appears in the vehicle selector it looks like this:

![screenshot_menu_after_selection](https://cloud.githubusercontent.com/assets/1700075/12482074/4e4b5f4c-c02c-11e5-8587-3b3a65e077e6.png)

Although this issue, both vehicles are connected to the QGC and sending messages without problem. I took a screenshot of the mavlink inspector:

![screenshot_mavlink_inspector](https://cloud.githubusercontent.com/assets/1700075/12482099/81574806-c02c-11e5-9498-95d8fd800d39.png)

I'm starting a project that will use QGC to control multiple UAVs. So i started using two SITL to understand how QGC works. I could make that both UAVs start their mission and QGC show them correctly besides it only allowed me to control one of them using it. I add a screenshot of both UAVs moving:

![selector_not_working](https://cloud.githubusercontent.com/assets/1700075/12482335/c92af1f4-c02d-11e5-8f78-892dd4bbc22e.png)

**Comment by DonLakeFlyer** [comment]
Fixed by #2677
