### ISSUE TITLE
Rework Firmware Upgrade with a real user interface

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2692]
Instead of the logging style UI it has now. Logging style doesn't allow for enough UI to prevent confusion around un-plugging, plugging in at the right times.

**Comment by DonLakeFlyer** [comment]
If this still is a major issue when we take on new users with APM Beta I'll move this up to 3.0 release.

**Comment by HTRamsey** [comment]
I'm assuming this is irrelevant now, considering the extensive UI changes since
