### ISSUE TITLE
Unreliable SD Card detection

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2704]
Hi.

This new feature is giving me the absent SD when I plugin the PixHawk on APM 3.4dev, although it can reach the card to retrieve logs....

I tested in several ways.

PixHawk off: Plugin USB cable - warning appears almost immediately (less than 5 seconds)

PixHawk powered via Power module and already ready (boot process complete verified by the leds): Same thing

PixHawk off: QGC not launched, Plugin USB cable wait for boot to complete, Launch QGC, eventually detects the PixHawk and the SD warning appears almost immediately.

<img width="1433" alt="screen shot 2016-01-23 at 21 44 28" src="https://cloud.githubusercontent.com/assets/3130363/12533809/3bfdcd56-c235-11e5-90f6-7430260a4871.png">

**Comment by DonLakeFlyer** [comment]
It takes way longer to get the first heartbeart from the ArduPiliot stack than the PX4 Stack. The timeout is too short. You can disregard the error though and everything will be fine.

**Comment by DonLakeFlyer** [comment]
Thanks for the report @lvale
