### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2706]
Hi

For the sake of consistency and easy readability is it possible to format the number of bytes downloaded with the commas like the total on the left:
<img width="939" alt="screen shot 2016-01-23 at 22 00 43" src="https://cloud.githubusercontent.com/assets/3130363/12539090/b4acd3ca-c2e2-11e5-8f31-cf46ab1b2bcc.png">

**Comment by dogmaphobic** [comment]
Done in #2732.
