### ISSUE TITLE
Px4FMU_v1 Firmware upgrade pointing to dead link?

### ISSUE THREAD

**Issue by KadynCBR** [mavlink/qgroundcontrol#2720]
When upgrading firmware for PX4FMU, it points to 
px4-travis.s3.amazonaws.com/Firmware/latest/px4fmu-v1_default.px4
which appears to be a bad link and does not return a px4 file

I don't know if it should point to...
px4-travis.s3.amazonaws.com/Firmware/stable/px4fmu-v1_default.px4
which seemed to work out for me downloading and selecting it as a custom file.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is this supposed to be "stable" instead of "latest"?

**Comment by LorenzMeier** [comment]
We have /stable, /beta and /master, never latest. So the link is definitely wrong, fix depends on context.
