### ISSUE TITLE
Parameter editor: Show defaults in tooltip or column so comparison between current value and meta default is possible

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2721]
@DonLakeFlyer Users like to compare current value vs. default value without the need to reset them. Not sure about the user model for touchscreen though.

**Comment by DonLakeFlyer** [comment]
Default value is shown when you edit a value isn't it?

**Comment by DonLakeFlyer** [comment]
Closing this instead of adding new ui. Default value is shown if you click the row to edit value. You can compare from there.
