### ISSUE TITLE
MAV_CMD_DO_VTOL_TRANSITION read back sets wrong frame

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#2725]
When reading a mission from the vehicle the MAV_CMD_DO_VTOL_TRANSITION is read with MAV_FRAME_GLOBAL_RELATIVE_ALT and not identified as a VTOL transition command. It should  be read as MAV_FRAME_MISSION.

**Comment by LorenzMeier** [comment]
This sounds like its modified on the vehicle side then.

**Comment by sanderux** [comment]
https://github.com/PX4/Firmware/issues/3658
