### ISSUE TITLE
Ardupilot firmware flashing from QGC master disabled

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#2735]
Hi. Any reason why flashing with QGC of Ardupilot firmware has been disabled ?? Just followed all the steps with Wireshark active and I don’t see any attempt of QGC to query any servers, while trying to flash PX4 runs ok from amazonaws ?
running latest qgc from master on OS X

https://youtu.be/2LvQlmq12Tc

**Comment by dogmaphobic** [comment]
You were trying to load APM Quad V1. I don't see any *V1* for APM in the list:
https://github.com/mavlink/qgroundcontrol/blob/master/src/VehicleSetup/FirmwareUpgradeController.cc#L206-L282
