### ISSUE TITLE
qgc on tablet: Video stream lagging

### ISSUE THREAD

**Issue by fkaiser** [mavlink/qgroundcontrol#2739]
I am currently trying to stream a video into QGC by using a logitech C920 camera that is connected to a Odroid C1 that redirects the video stream via WiFi to the QGC on a Samsung tablet computer. The video starts to lag after 4 to 6 seconds. However, if I stream the video to a desktop computer that runs QGC, the videostream looks good and does not lag.

**Comment by dogmaphobic** [comment]
I have not had any issues using a Nexus 9 or a Nexus 7. I use 720P at 25fps. Have you tried a lower resolution and/or fps?

**Comment by dogmaphobic** [comment]
Ancient history
