### ISSUE TITLE
Add support for MAV_CMD_NAV_VTOL_TAKEOFF and MAV_CMD_NAV_VTOL_LAND

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#2749]
Please add support for VTOL takeoff and land commands as specified here: https://github.com/mavlink/mavlink/pull/487/files

PX4 reference: https://github.com/PX4/Firmware/pull/3699

**Comment by DonLakeFlyer** [comment]
From looking at the firmware source I think these assumptions are correct:
- [ArduPilot:PX4] Supports coordinate for both takeoff and land
- [PX4] Support heading for takeoff and land
- [ArduPilot] Does NOT support heading for takeoff and land

@sanderux Can you very this is correct?

**Comment by DonLakeFlyer** [comment]
Also:
[PX4] - Support VTOL_TRANSITION
[ArduPilot] - Does NOT support VTOL_TRANSITION

**Comment by sanderux** [comment]
@DonLakeFlyer as far as i can tell APM indeed does not support VTOL_TRANSITION yet. @tridge ?
