### ISSUE TITLE
Fly: Map/Video switching issues

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2802]
- Video box is showing up on my Android bulid even though I don't have the GStreamer stuff installed
- When you switch to Video the Map instruments stay up and don't switch to Video widgets

**Comment by dogmaphobic** [comment]
I'm now hiding the PIP control but I could not exactly reproduce what you describe above. Please, check #3044 and see if that was it.

**Comment by DonLakeFlyer** [comment]
I'll take a look again

**Comment by DonLakeFlyer** [comment]
Looks good now
