### ISSUE TITLE
QGC send param save to vehicle too often

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#2807]
Scenario: 
1) Fly without GCS
2) Remove SD card, copy logfiles
3) Power up via USB
4) Connect QGC via wifi
5) discover that SYS_AUTOSTART is now zero, as are all sensor cal params
6) look for means to restore parameters from last flight log;

**Comment by DonLakeFlyer** [comment]
What exactly is QGC doing wrong here, and how is it changing parameters?

**Comment by LorenzMeier** [comment]
Its sending a param save command as part of the sync process, even during the first sync where no params are changed (since ages). That save could, given the right timing, trash the params if the user shuts down the board right then.

**Comment by DonLakeFlyer** [comment]
Not sure why a param save when QGC has changed no params would cause a problem. That would seem to be a firmware problem to me. Anyway, I'll look at making these saves not as stupid.

**Comment by LorenzMeier** [comment]
Found the mistake on the PX4 side. Fix going to master.

**Comment by DonLakeFlyer** [comment]
Re-opening since i think it still makes sense to at least try to make QGC a little smarter about these uneeded saves.
