### ISSUE TITLE
Major work items for 3.1 release

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2819]
- Survey support
- Switch to fully/completely/all-the-way/really-I-mean-it-this-time native Qml
- Translation support (#3961)
- Mavlink 2.0
- Full direct command support: Takeoff, Go Here, Land, Follow Me
- Parrot support

**Comment by NaterGator** [comment]
Can we take a swipe at optimization here too (#2638)? Optimizing the QML side can/will be a bit tricky but it is probably best to learn and implement best-practices as we go whole-hog on QML.

**Comment by DonLakeFlyer** [comment]
Sure, sounds good.

**Comment by jcooper21** [comment]
On the land function for APM Plane support is it possible to get the do_start_land command so planes can autoland with APM?

**Comment by DonLakeFlyer** [comment]
> s it possible to get the do_start_land command

I added that a few days ago.

**Comment by jcooper21** [comment]
Awesome keep up the great work.  The only other main features I see missing that have not been said is vibe monitoring, EKF monitoring, second GPS sat info, Wind speed & direction

**Comment by DonLakeFlyer** [comment]
> The only other main features I see missing that have not been said is vibe monitoring, EKF monitoring, second GPS sat info, Wind speed & direction

Can you move those to a new issue and we'll continue discussion there?

**Comment by jcooper21** [comment]
Done

**Comment by jcooper21** [comment]
I would like to add Orbit to this list

**Comment by DonLakeFlyer** [comment]
> I would like to add Orbit to this list

Do you mean like Circle in ArduPilot. QGC already supports it on ArduPilot. Needs to be added to PX4 firmware before QGC can support it then it's a trivial non-major change on the QGC side.

**Comment by jcooper21** [comment]
Yes i was reffering to circle. That sounds good.

**Comment by dagar** [comment]
How about calibration rotation images or animated models https://github.com/mavlink/qgroundcontrol/issues/1783?

**Comment by DonLakeFlyer** [comment]
Closing this out since 3.1 is wrapping up
