### ISSUE TITLE
QuadRanger airframe sets wrong autostart

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#2823]
When selecting QuadRanger (13008) from standard VTOL, SYS_AUTOSTART is set to 13005

**Comment by DonLakeFlyer** [comment]
Can flash again and let me know. I think that was fixed on the firmware side. Built in xml meta data is 13008 but you may still have a flash cached version which is incorrect.

**Comment by sanderux** [comment]
This was not through flashing, it was flashed through make and then selecting a different airframe. is that behavior different?

**Comment by DonLakeFlyer** [comment]
Nope looks like a QGC bug, not a meta data bug.

**Comment by DonLakeFlyer** [comment]
Can you try flashing master using QGC. Quit QGC. Reboot QGC and then try setting the airframe again?

**Comment by DonLakeFlyer** [comment]
@sanderux Any update on this?

**Comment by sanderux** [comment]
Not yet, will set it up this week

**Comment by DonLakeFlyer** [comment]
@sanderux Any update?

**Comment by DonLakeFlyer** [comment]
@sanderux ???

**Comment by sanderux** [comment]
I just tried to reproduce but failed.
Not sure what happened. I'll let you know if it happens again.
