### ISSUE TITLE
Flight modes tab PWM indicator ignores ArduPlane FLIGHTMODE_CH parameter

### ISSUE THREAD

**Issue by cosmonate** [mavlink/qgroundcontrol#2824]
On APM:Plane you can change the RC channel flight modes are on. The flight modes tab ignores this parameter and just highlights the PWM value range of whatever channel 5 is, not the actual flight modes channel.

**Comment by DonLakeFlyer** [comment]
Ah, missed that quirk of Plane versus Copter!
