### ISSUE TITLE
problem connecting PixRacer when USB and wifi are both active

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#2831]
appears to start loading parameters over wifi (slower than USB) and fails to complete
Must disconnect from wifi and restart QGC.
@pkocmoud can you reproduce this?

**Comment by pkocmoud** [comment]
When did this start?

**Comment by DonLakeFlyer** [comment]
Can get logging out from connection logs: http://www.qgroundcontrol.org/logging. Then we can see what order things are connecting.

**Comment by kd0aij** [comment]
[qgc.log.zip](https://github.com/mavlink/qgroundcontrol/files/134855/qgc.log.zip)

**Comment by DonLakeFlyer** [comment]
This has full logging which makes it near impossible to pull anything out.. I need the connection logging only. Need --logging:LogManagerLog,MultiVehicleManagerLog. Also the log doesn't look like it starts from boot.

**Comment by kd0aij** [comment]
./qgroundcontrol --logging:full 2>&1 qgc.log | tee qgc.log
Is that wrong?

**Comment by DonLakeFlyer** [comment]
./qgroundcontrol --logging:LogManagerLog,MultiVehicleManagerLog

Not sure why it doesn't seem to get the beginning of the log.

**Comment by kd0aij** [comment]
[qgc.log.zip](https://github.com/mavlink/qgroundcontrol/files/134870/qgc.log.zip)

**Comment by DonLakeFlyer** [comment]
The problem is that the WiFi connection comes up before the USB connection does. This in turn causes problems with the parameter protocol with respect to multi-link support. Lorenz, Gus and I just finished discussing the solution for this:
- Have QGC mark that it has seen a bootloader on a USB port
- Then even though it sees the WiFi connection first, it knows that a USB connection is about to come it.
- So it does not connect via WiFi and instead connects via USB only.

What this means: 
- You can only change WiFi module params when "NOT" connected via USB

**Comment by DonLakeFlyer** [comment]
@kd0aij Can you try the latest daily build?

**Comment by kd0aij** [comment]
parameters load successfully now, thanks. But the artificial horizon doesn't work.
"Comm links" shows only one connection, "default udp link"
Clicking "disconnect" results in a new "default udp link" button and immediate reconnection.
I don't suppose that is the intended behavior?

**Comment by pkocmoud** [comment]
> Comm links" shows only one connection, "default udp link"
Clicking "disconnect" results in a new "default udp link" button and immediate reconnection.
I don't suppose that is the intended behavior?

I have noted this for a while using the daily builds. IE it is not recent.

**Comment by DonLakeFlyer** [comment]
Don't expect to make any sense out of auto-connected links by going to comm links. There is already an issue in on that. If you want to turn off auto-connect for UDP you need to do that from the General page.

Can you use the mavlink inspector to see what sort of mavlink messages you are getting?

**Comment by kd0aij** [comment]
attitude at 94Hz, highres_imu at 50Hz, vfr_hud at 20Hz

**Comment by kd0aij** [comment]
numeric roll and pitch display OK

**Comment by kd0aij** [comment]
with both "Pixhawk" and "UDP" autoconnect disabled, I can connect properly using either USB or wifi 
So things are much better now.

**Comment by DonLakeFlyer** [comment]
Does that fix the attitude indicator? Not sure what you mean by "I can connect properly using either USB or wifi". Why do you need to do that?

**Comment by kd0aij** [comment]
artificial horizon still dead.
Regarding "Why do you need to do that?" *somebody* needs to do testing :)
