### ISSUE TITLE
New altitude indication feature creep on Desktop ;)

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2832]
@DonLakeFlyer The usability of the altitude indication is terrible. A clear step back. Don't let the feature creep get you!

<img width="1392" alt="screen shot 2016-02-17 at 16 49 19" src="https://cloud.githubusercontent.com/assets/1208119/13118557/034396b6-d5a5-11e5-9783-069b4bfa247b.png">

**Comment by kd0aij** [comment]
I assume there's something obviously wrong with that display. Is it the intended meaning of "home" or the presence of units?

**Comment by DonLakeFlyer** [comment]
You can't glance at a tablet sized screen and see the Altitude value easily which is an important value. All fixed now.

**Comment by kd0aij** [comment]
does "home" mean "relative to home"? I guess "AGL" was deemed more ambiguous?

**Comment by DonLakeFlyer** [comment]
Yes
