### ISSUE TITLE
Waypoint display issue

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#2848]
Using a Microsoft surface pro 4 or probably any Windows touch screen I can't scroll down on the screen with my finger out pen. This means once there are enough waypoints to fill up the right side of the screen any additional waypoints cannot be accessed.

**Comment by DonLakeFlyer** [comment]
Does the mouse/trackpad work?

**Comment by jcooper21** [comment]
I am not sure I would assume so. I don't have the Microsoft keyboard/track pad. Just the pen and my finger.

**Comment by DonLakeFlyer** [comment]
Does other scrolling work like parameter list work?

**Comment by jcooper21** [comment]
Yes that all works good. I have to press and hold the furthest left menu button. Other than that everything else is good.

**Comment by jcooper21** [comment]
This is only in touch screen laptops and 2 in 1s not in tablet mode in windows 10

**Comment by DonLakeFlyer** [comment]
I'll find some time to get you some private build to try various changes to figure out what it going on here. Stay tuned.

**Comment by DonLakeFlyer** [comment]
@jcooper21 Can you replace your qgroundcontrol.exe with this one: https://www.dropbox.com/s/osbob2k8j6fatg5/qgroundcontrol.exe.zip?dl=0. Keep your old one so you can put it back. 

Then try scrolling the waypoint list with thie new .exe

**Comment by jcooper21** [comment]
Don, I am unable to test this week. Will try next week

**Comment by jcooper21** [comment]
i just tested it and it seems good

**Comment by DonLakeFlyer** [comment]
Great, thanks for helping out
