### ISSUE TITLE
Potentially add SiLaps VID / PID

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2862]
@DonLakeFlyer Some chinese vendors use the SiLabs default VID / PID. Should we still add it?
USB\VID_10C4&PID_EA60

**Comment by DonLakeFlyer** [comment]
Does the description matching fallback of "FT231X USB UART" not work for these? A bit paranoid about auto-connecting to additional stuff. Do we know if this VID/PID pair is only used for Radios?
