### ISSUE TITLE
Provide AUX and FLAPS assignment UI

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2893]
@DonLakeFlyer We're missing a screen with drop-downs for the AUX1-3 and FLAPS functions for PX4. I can finalise the param meta data on master so all it would take would be some formatting and four drop-downs for these channels for starters.

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/issues/3855

**Comment by DonLakeFlyer** [comment]
You do that during Radio Cal

**Comment by LorenzMeier** [comment]
Yes, and its confusing like hell and you can't change it after having calibrated the radio. We need to change this, every user is confused.

**Comment by DonLakeFlyer** [comment]
Fixed by new simple flight mode config
