### ISSUE TITLE
Android: If app was in background, switching to foreground is needed to make it connect

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2894]
@DonLakeFlyer @dogmaphobic We have a weird background / foreground dependency:

1) If you start QGC fresh, Wifi connects fine
2) If QGC was running and Wifi connects, it will not show anything
3) If you then hit the home button and it moves to the background and you bring it back with the app button, it connects.

**Comment by DonLakeFlyer** [comment]
I just:
- Started QGC
- Battery to PixRacer

Connected fine first time!

**Comment by DonLakeFlyer** [comment]
I wonder if the app is sleeping when it goes to background.

**Comment by DonLakeFlyer** [comment]
I haven't been having problems with this recently. Still working strangely for you?

**Comment by DonLakeFlyer** [comment]
Closing. Re-open is still happeing. Haven't seen it in ages.
