### ISSUE TITLE
Battery Voltage Warning with 2S battery

### ISSUE THREAD

**Issue by nkhoit** [mavlink/qgroundcontrol#2901]
QGC complains about a low battery voltage even though the cell count is set to 2S in the power setup menu.
There are no critical messages from the vehicle about this error.
With a 2S battery, QGC complains about a low battery while the battery voltage is read out as 7.8V.

**Comment by DonLakeFlyer** [comment]
The code in UAS assumes a 3s battery which is wrong. Will need to switch this over to the other battery mavlink message which includes cell count in it to fix this.
