### ISSUE TITLE
Plan: Mission with takeoff command won't takeoff

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2904]

**Comment by DonLakeFlyer** [comment]
This may be an ArduCopter thing.

**Comment by jcooper21** [comment]
It works good on APM plane the take take off command.

**Comment by DonLakeFlyer** [comment]
Try adding throttle to start mission

**Comment by DonLakeFlyer** [comment]
Not a bug. Just need correct ArduPilot SITL throttle up sequence:
arm throttle
mode auto
rc 3 1500
