### ISSUE TITLE
Integrate AppImage for Linux releases

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#2913]
Linus' subsurface project uses AppImage and it seems to have his seal of approval. This should help greatly simplify getting users up and running in Linux without worrying about dependencies. 

http://appimage.org

**Comment by dagar** [comment]
I can't believe I haven't heard of this.

**Comment by probonopd** [comment]
Have a look at the AppImage build scripts ("recipes") of other Qt based applications:
 * https://github.com/probonopd/AppImages/blob/master/recipes/subsurface/Recipe
 * https://github.com/probonopd/AppImages/blob/master/recipes/scribus/Recipe
 * https://github.com/probonopd/AppImages/blob/master/recipes/krita/Recipe

By building on a CentOS 6 build host, the resulting binaries are known to run on most modern desktop Linux distributions.

**Comment by probonopd** [comment]
How do I build this on a CentOS 6 build host?

**Comment by dagar** [comment]
@probonopd are you asking how to build qgroundcontrol on centos 6, or how to get AppImage working?

**Comment by probonopd** [comment]
I am asking how to build qgroundcontrol on CentOS 6.

**Comment by probonopd** [comment]
Here is the Recipe that can be used to generate the AppImage for 64-bit Linux.
https://github.com/probonopd/AppImages/blob/master/recipes/qgroundcontrol/Recipe

**Comment by probonopd** [comment]
And here is the resulting AppImage:
https://bintray.com/probono/AppImages/QGroundControl/view#files

**Comment by dagar** [comment]
Nice! It works on my Ubuntu 14.04 machine.

The problem is we'd need to find a continuous integration service that offers CentOS 6. We could build on Ubuntu 12.04, but we had to upgrade because of udev issues.

If you could document how to create the AppImage I'll add it to the builds with s3 and github deployment ASAP.

**Comment by probonopd** [comment]
@dagar the [recipe](https://github.com/mavlink/qgroundcontrol/issues/2913#issuecomment-204751337) above shows how to do it.

For other packages I am using CentOS 6.7 Docker images that I run on Travis-CI. This way, I can build on CentOS while still using Travis-CI. But maybe it is OK as it is, as long as you get no complaints from users.

**Comment by dagar** [comment]
Ok perfect. I see the script grabs an AppImageAssistant binary. I was thinking we might need to build or install it on travis-ci. Do you mind if we pull your script into the deploy directory and modify it work with the output of a freshly built release? We also need to fix the icon.

**Comment by probonopd** [comment]
Feel free to go ahead. If you like you can of course build AppImageKit on travis, but you don't have to.

**Comment by dagar** [comment]
It should be tested, but the is AppImage is now created in the builds and uploaded to s3. http://qgroundcontrol.s3.amazonaws.com/master/qgroundcontrol.AppImage?dl=0
Tagged releases will be auto added to GitHub releases

Thanks again @probonopd

**Comment by probonopd** [comment]
On Ubuntu 16.04:
```
me@host:~$ '/home/me/Downloads/qgroundcontrol.AppImage' 
/tmp/.mount_W7Kwcs/qgroundcontrol: error while loading shared libraries: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
```
Please see https://github.com/probonopd/AppImages/blob/master/recipes/qgroundcontrol/Recipe#L11-L24 for how to solve this.

**Comment by dagar** [comment]
I'm pulling the debs just like your original script. I'm not sure what's wrong with it at the moment.
https://github.com/mavlink/qgroundcontrol/blob/master/deploy/create_linux_appimage.sh#L17

For development builds we're trying to only store and link to the latest good binary for each branch. Is there some reason it's important to have the version in the name for AppImage? We could do it for proper releases.

**Comment by probonopd** [comment]
Sorry, I forgot to mention that the AppRun script also needs to set `LD_LIBRARY_PATH` accordingly so that libraries are also picked up from `usr/lib/x86_64-linux-gnu`, e.g.,
```
export LD_LIBRARY_PATH="${HERE}/usr/lib/x86_64-linux-gnu":"${HERE}/Qt/libs":$LD_LIBRARY_PATH
```

**Comment by dagar** [comment]
@probonopd can you try http://qgroundcontrol.s3.amazonaws.com/master/qgroundcontrol.AppImage?dl=0 again?

Do you know if it's possible to have an icon in Ubuntu unity for an AppImage?

![screenshot from 2016-04-05 14 09 15](https://cloud.githubusercontent.com/assets/84712/14292910/2569bf50-fb38-11e5-9351-a5c8e3e6fa0b.png)

**Comment by probonopd** [comment]
You added usr/lib to $LD_LIBRARY_PATH but the library is in usr/lib/x86_64-linux-gnu so it does not find SDL yet...

**Comment by dagar** [comment]
Ah, I just copied your recipe. Thanks
Trying again...

**Comment by probonopd** [comment]
Yes, it was a bug in mine... updating the recipe

**Comment by dagar** [comment]
Any ideas for the launcher icon?

**Comment by probonopd** [comment]
Regarding the icon I am not entirely sure how this works for Unity, it does show icons for most AppImages. Can you attach an icon to your main window in Qt and would that change it?

**Comment by dagar** [comment]
I think it was just missing the extension in the desktop entry. 
https://github.com/mavlink/qgroundcontrol/commit/1cde874bfd5af71e090f0e35576731c8baf7989e

**Comment by probonopd** [comment]
Does this result in the icon being displayed?

**Comment by dagar** [comment]
Travis-ci builds are especially slow during the day. We'll know shortly.
