### ISSUE TITLE
support APM firmware to fly routes

### ISSUE THREAD

**Issue by jilinggui** [mavlink/qgroundcontrol#2919]
Hello , someone told me that currently qgroundcontrol already support APM firmware , but I have tested the latest version of Qgroundcontrol, there are still many problems , such as the inability to fly routes , I use APM arducopter 3.3, I ask that branch can be completely support APM firmware,or it is on the way.

**Comment by DonLakeFlyer** [comment]
If you have give us the details of the many problems we can help you out and/or fix the problems.
