### ISSUE TITLE
PX4 Tuning should all go the same way

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2928]
![screen shot 2016-03-03 at 8 47 58 pm](https://cloud.githubusercontent.com/assets/5876851/13518319/4e0f738a-e181-11e5-8c9a-6f4863df2baa.png)
Notice how top two are slide to the right for less twitchy and next two are slide to the left for less twitchy.

**Comment by DonLakeFlyer** [comment]
While I'm in there #2889

**Comment by tubeme** [comment]
Very Nice!

**Comment by DonLakeFlyer** [comment]
Give the connection to param meta data there isn't really a way for QGC to know the directions on these.
