### ISSUE TITLE
Figure out iOS build for CI

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2938]

**Comment by jcooper21** [comment]
Is QGC going to be available on iPad minis? That would be awesome

**Comment by DonLakeFlyer** [comment]
Yes. In fact if you have the ability to build QGC yourself, you can run there right now.

**Comment by jcooper21** [comment]
That is great except I definitely to not have the skills to do that.

**Comment by DonLakeFlyer** [comment]
```
        # Install handcrafted Qt ios version
        wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.5.1-ios.tar.bz2
        mkdir -p ~/qt-ios
        tar jxf Qt5.5.1-ios.tar.bz2 -C ~/qt-ios
        export PATH=~/qt-ios/ios/bin:$PATH
```

```

**Comment by jcooper21** [comment]
Is there any chance of the iOS builds showing up in the apple flight test app for beta software?  If there is I am happy to test it for you.

**Comment by DonLakeFlyer** [comment]
https://www.objc.io/issues/6-build-tools/travis-ci/

**Comment by booo** [comment]
As far as I can tell we build iOS apps of QGC.

**Comment by DonLakeFlyer** [comment]
> As far as I can tell we build iOS apps of QGC.

That's not the case. The iOS build in the store is years out of date. It was all built by hand by Gus and pushed to the stored manually. Since Gus isn't around any more it hasn't been happening.
