### ISSUE TITLE
Remove FLAPS and AUX mappings from PX4 RC calibration

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2949]
@DonLakeFlyer The flaps and AUX channels would probably make most sense to have as parameter driven drop-downs in the RC calibration screen. They should not be part of the initial mapping procedure because its confusing users.

**Comment by DonLakeFlyer** [comment]
They are on the simple mode screen. They should likely be added to Advanced as well. Instead of adding as separate element to RC Cal. This keeps RC cal clean for just setting stick assignment. Agree?

**Comment by LorenzMeier** [comment]
These are linear channels, not switches and not related to flight modes. It doesn't seem to make sense to have them in the flight mode UI. They are like RPYT.

**Comment by DonLakeFlyer** [comment]
So this is wrong? They should move from here to RC Cal? Leaving only Return and Kill here?
![screen shot 2016-03-05 at 1 45 46 pm](https://cloud.githubusercontent.com/assets/5876851/13556333/c857593a-e38b-11e5-9b3d-f7b2def3f12b.png)

**Comment by LorenzMeier** [comment]
I'm not sure I would call it wrong, but in hindsight it occurred to me that we're mixing switches with just "output channels". Would you agree that it might be more intuitive to have these in the radio tab?

**Comment by DonLakeFlyer** [comment]
I kind of agree with you. But Radio Cal is already really busy ui-wise. Let me think about it.
