### ISSUE TITLE
unable to connect to pixracer via USB

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#2961]
1) multiple reboots of pixracer and restarts of QGC did not help
2) no hung processes starting with "q"
3) rebooting (Ubuntu 15.10) solved the problem
4) need less drastic remedy :)

**Comment by DonLakeFlyer** [comment]
Without any sort of logging information there is going to be now way for me to figure out what happened here.

**Comment by DonLakeFlyer** [comment]
Whever you get connection issues. Capture a log using 
```
--logging:LinkManagerLog,MultiVehicleManagerLog
```

**Comment by kd0aij** [comment]
will do that next time I run into problems. I assumed this was a known issue with an existing workaround.

**Comment by DonLakeFlyer** [comment]
If you have to reboot the entire OS to clear, then it more likely the port is hung up with the OS than a QGC issue.

**Comment by dagar** [comment]
Have you experienced this problem again in the last 3 months @kd0aij?

**Comment by kd0aij** [comment]
I don't think so.
