### ISSUE TITLE
heading displays 359, 360, 0, 1

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#2971]

**Comment by DonLakeFlyer** [comment]
I'm going to need a little more information than that if you want something changed!

**Comment by LorenzMeier** [comment]
360 and 0 are the same heading. I can only guess that 359.6 is 360 and 0.5 is 0. But they really should both report 0.

**Comment by kd0aij** [comment]
based on observation of behavior, the display is magnetic heading until a gps lock is acquired.
After GPS lock, the display is true heading (corrected for declination). The declination value appears to persist thereafter even if the gps fix is lost.
