### ISSUE TITLE
Severity adjustment doesn't seem to be working correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2973]
Calibration spits out as error messages.

**Comment by lucasdemarchi** [comment]
what's the relationship with #2974 ?

**Comment by DonLakeFlyer** [comment]
Nothing. This relates to older versions of ArduPilot firmware having the mavlink severitys reversed. Hence QGC warns about all sorts of stuff it shouldn't.

**Comment by DonLakeFlyer** [comment]
It may just be bad individual severity marking on the ArduPilot side.

**Comment by DonLakeFlyer** [comment]
Fix in latest ArduPilot firmware
