### ISSUE TITLE
Should support command (COMMAND_LONG) confirmation and resend

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#2975]

**Comment by dagar** [comment]
Can we do this with mavlink as is?

**Comment by DonLakeFlyer** [comment]
Yes, as long as there are not multiple of the same command one the wire.

**Comment by NaterGator** [comment]
Store a hash table based on command and only retry the latest?

**Comment by DonLakeFlyer** [comment]
That's not quite the issue. Here it is:
1) User says to arm
2) Before ack comes back, user says to disarm
3) Ack comes back on arm/disarm command

Which one is the ack for?

**Comment by NaterGator** [comment]
Sorry I have been kinda tied up in other things, does the spec not implement a sequence number included in the acknowledge? Storing the expected sequence in the hash would make it completely unambiguous if the disarm was being acknowledged or the old arm command was.

**Comment by DonLakeFlyer** [comment]
Nope.

**Comment by DonLakeFlyer** [comment]
Also need to replace sendMultiple with a guaranteed delivery mechanism. Right now we end up getting autopilot_version response back three times due to sendMultiple.
