### ISSUE TITLE
MC_PITCHRATE_I is missing a digit

### ISSUE THREAD

**Issue by sn0west** [mavlink/qgroundcontrol#2978]
MC_PITCHRATE_I has only 3 digit x.xx instead of 4 like MC_ROLLRATE_I x.xxx. 
Could you please fix that, so I can have a better scaling for MC_PITCHRATE_I.

![bildschirmfoto 2016-03-09 um 12 48 13](https://cloud.githubusercontent.com/assets/9918649/13654303/b93968a2-e657-11e5-9bd1-0d97ca3f7d5b.png)

QGC 2.9.4 Daily Build that I downloaded the 29.02.16

**Comment by DonLakeFlyer** [comment]
The number of decimal places is controlled by the firmware parameter meta data. This is a firmware problem.
