### ISSUE TITLE
Update Android device filter to only include devices we actually support

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2990]
Users will get asked if they want to launch QGC else even though we're not supporting the devices.
https://github.com/mavlink/qgroundcontrol/blob/master/android/res/xml/device_filter.xml

**Comment by DonLakeFlyer** [comment]
@dogmaphobic So leave just:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Everything -->
    <usb-device />
    <!-- 0x26AC / 0x11: PX4 FMU Pixhawk -->
    <!--
    <usb-device vendor-id="9900" product-id="17" />
    -->

    <!-- 0x0403 / 0x6001: FTDI FT232R UART -->
    <!--
    <usb-device vendor-id="1027" product-id="24577" />
    -->

    <!-- 0x0403 / 0x6015: FTDI FT231X -->
    <!--
    <usb-device vendor-id="1027" product-id="24597" />
    -->
</resources>
```

**Comment by LorenzMeier** [comment]
No, you would need to add the 3DR Radio as well.

**Comment by DonLakeFlyer** [comment]
Oh, I see it's all commented out. I'm not sure we want to filter though? We don't really know the IDs and we probably don't have string matching fallback. @dogmaphobic will have to comment on how this stuff works.

**Comment by DonLakeFlyer** [comment]
Wonder what the 3DR services thing does.

**Comment by dogmaphobic** [comment]
> Wonder what the 3DR services thing does.

That's where I got it from :)

**Comment by dogmaphobic** [comment]
Come to think of it, it wasn't Tower. It was something else that was using a Java wrapper to c++. Tower is pure Java:

https://github.com/dronekit/dronekit-android/tree/develop/ServiceApp/src/org/droidplanner/services/android/communication/connection/usb

**Comment by DonLakeFlyer** [comment]
Right but what about the manifest settings?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Moving this over to you to see if you want to change anything here. I'm a bit paranoid about changing things here.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier, @dogmaphobic I think we should move this to 3.0. I'd rather be overly inclusive instead of getting things wrong for 3.0 by being too specific.

**Comment by DonLakeFlyer** [comment]
I don't think I'm going to change this. Overly inclusive is better especially with new usb code. Less inclusive caused problems with all the different radio devices out there.
