### ISSUE TITLE
Config option for autoconnect

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#2991]
For developers the autoconnect function can be really annoying, for instance by grabbing any serial port that is used for debugging. It would therefore be good to have an option to turn the autoconnect off manually.

**Comment by DonLakeFlyer** [comment]
![screen shot 2016-03-11 at 8 50 13 am](https://cloud.githubusercontent.com/assets/5876851/13708981/5655d42c-e766-11e5-98f5-d2a6c1bbc040.png)

**Comment by julianoes** [comment]
@DonLakeFlyer Awesome, thanks for that. Let me update :)

**Comment by DonLakeFlyer** [comment]
No need to update. That been in there since auto-connect first came in.

**Comment by julianoes** [comment]
Aha, found it.
