### ISSUE TITLE
Arm / disarm controls missing from title bar

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3010]
@DonLakeFlyer Current master:

![screen shot 2016-03-13 at 15 50 14](https://cloud.githubusercontent.com/assets/1208119/13729360/92d3ac16-e933-11e5-8239-5b19c3e2e1f3.png)

**Comment by DonLakeFlyer** [comment]
They're at the bottom of the screen in the guided bar.
