### ISSUE TITLE
Support web based download of meta data

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3013]
Tablet users need a mechanism to update meta data other than firmware flash.

**Comment by DonLakeFlyer** [comment]
The follow file would be downloaded from a location which is provided by the FirmwarePlugin:
```
{
    "fileVersion": 1,

    "parameterMetaData": [
        {
            "majorVersion": ## ,
            "minorVersion": ## ,
            "uri": uri,
        },
        ...
    ],

    "airframeMetaData": [
        {
            "majorVersion": ## ,
            "minorVersion": ## ,
            "uri": uri,
        },
        ...
    ]
}
```

* majorVersion/minorVersion - Matches values which are inside the file
* parameterMetaData.majorVerson - Matches parameter set version as specified by ArduPilot:SYSID_SW_MREV, PX4:SYS_PARAM_VER
* parameterMetaData.minorVersion - Indicates newer meta data for non-breaking change

I think the major version of airframe and parameter meta data should be tied together. Or in other words, if there is a breaking change in either airframe or param meta data it is indicated by a bump in parameter set version parameter.

**Comment by DonLakeFlyer** [comment]
Would be fanstastic if we could start doing flight modes this way as well.

**Comment by LorenzMeier** [comment]
Looking good. Should include a branch or git tag (so GCS can grab the right meta file based on git hash in http://mavlink.org/messages/common#AUTOPILOT_VERSION).

@dagar Might be willing to help you with uploading the airframe and parameters.xml file to AWS for each commit and updating this registry file.

**Comment by DonLakeFlyer** [comment]
* If breaking change is made to parameter or airframe meta data you bump majorVersion (both in files and SYS_PARAM_VER )
* If you want newer non-breaking meta data to override older meta data at same major version level you bump minorVersion.

Semantics are not based on git hash. There is no concept of meta data set keyed to each build.

**Comment by DonLakeFlyer** [comment]
Just realizing for ArduPilot this is going to need MAV_TYPE as well since parameter set version may differ between vehicle types. Which also means ArduPilot meta data needs to be broken out by vehicle type, which is not currently how it works.

Example updated

**Comment by dagar** [comment]
Yes, I think he's willing.

**Comment by LorenzMeier** [comment]
I have put a stopgap in Travis which pulls latest meta online before building. That will at least fix Android.

**Comment by DonLakeFlyer** [comment]
Meta data and flight mode now come through mavlink with component metadata
