### ISSUE TITLE
Emergency stop is the wrong wording for "Cut power"

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3020]
It would be good to have more direct language that explains in a layman language what will happen. I would propose "cut power" or "emergency crash".

Current language sounds like it could be a good idea in an emergency, it doesn't actually say anything about last resort.

**Comment by DonLakeFlyer** [comment]
Emergency motor stop?

**Comment by DonLakeFlyer** [comment]
Pull #3026

Left, wording as "Emergency stop" since I need short wording there. But the confirmation text now say "Slide to STOP ALL MOTORS!".
