### ISSUE TITLE
On screen emergency  button

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3024]
It would be nice if there was an emergency button on screen where if something went bad you could hit it and the flight would pause and go into loiter mode for both copter and plane.

**Comment by DonLakeFlyer** [comment]
This is already all implemented for Copter. Just not Plan yet.

**Comment by jcooper21** [comment]
Oh right on. Once it's in there for apm plane I will test it out

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/2979

**Comment by jcooper21** [comment]
For the interm is it possible to just put a pause button in QGC that makes plane loiter?

**Comment by DonLakeFlyer** [comment]
Just pick Loiter from the flight mode toolbar dropdown for now.

**Comment by jcooper21** [comment]
Will do. Keep up he great work.

**Comment by jcooper21** [comment]
Don, I just tested the pause on today's build and it kicks the plane into loiter perfectly.

**Comment by jcooper21** [comment]
With the emergency stop. Is this a setting I can disable if I want. Training people I definitely do not want them to panic and accidentally hit emergency stop instead of pause since the buttons are so close.

**Comment by DonLakeFlyer** [comment]
No you cannot. You have to confirm it to make it work. So you can’t really do it by accident.

**Comment by jcooper21** [comment]
Perfect

**Comment by jcooper21** [comment]
Should the emergency buttons be red in color since there emergency?
