### ISSUE TITLE
Crash on telemetry log replay

### ISSUE THREAD

**Issue by lucasdemarchi** [mavlink/qgroundcontrol#3025]
I can easily reproduce crashes on QGC when I try to replay/analyze the [(crash) log](http://pub.politreco.com/crash.tlog). Whenever I try to set the position to the end of the log QGC crashes.

**Comment by DonLakeFlyer** [comment]
And I of course can't make it happen. Can you detail out all steps from app boot?

**Comment by DonLakeFlyer** [comment]
@lucasdemarchi Any more details?

**Comment by lucasdemarchi** [comment]
I can't reproduce anymore. At the time it was sufficient to either let the replay to finish or move the slider while playing.  It doesn't crash anymore, so I'm closing.  If it starts crashing again I'll open another issue with more details. thanks.
