### ISSUE TITLE
Wind direction issue

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3033]
I don't think the wind direction in QGC is displaying correct data. It does not seem to be actual wind direction.

**Comment by jcooper21** [comment]
@DonLakeFlyer 

PX4 never displays wind direction and speed but APM does. Is this a bug?

**Comment by DonLakeFlyer** [comment]
As far as I know PX4 stack doesn't support wind direction yet. Is APM showing incorrect value?

**Comment by jcooper21** [comment]
I have not tested APM recently so I'm not sure if it's working on the new version. Does px4 support wind speed because that does not show up in QGC either

**Comment by DonLakeFlyer** [comment]
No wind information aat all in PX4 stack,

**Comment by dagar** [comment]
We'd need to implement WIND_COV  (http://mavlink.org/messages/common#WIND_COV) on the PX4 side. Internally the PX4 estimators publish a wind estimate (https://github.com/PX4/Firmware/blob/master/msg/wind_estimate.msg).

**Comment by dagar** [comment]
I'll implement the PX4 side - https://github.com/PX4/Firmware/issues/4678

**Comment by DonLakeFlyer** [comment]
QGC usess MAVLINK_MSG_ID_WIND

**Comment by dagar** [comment]
I saw that, but common only has WIND_COV.

http://mavlink.org/messages/ardupilotmega#WIND

**Comment by DonLakeFlyer** [comment]
Yeah, just realized that as well. Looks like WIND_COV is a superset of ardupilot WIND message. I can convert ardupilot WIND message to WIND_COV in the plugin and keep central QGC to WIND_COV. WIND_COV will need spec changed to allow nan in missing fields though since WIND is subset.

**Comment by jcooper21** [comment]
@dagar @DonLakeFlyer  was this supposed to be in today's beta update of PX4?  I just tested the latest beta and nothing published to QGC in Android.

**Comment by dagar** [comment]
You should be able to see WIND_COV in the mavlink inspector, but the rest of the QGC support hasn't been done yet.

**Comment by jcooper21** [comment]
OK thanks. I was looking in the instrument panel for a reading.

**Comment by booo** [comment]
As far as I can see this is implemented.
