### ISSUE TITLE
COMMUNICATION LOST when triyng calibrate the device using QGroundControl

### ISSUE THREAD

**Issue by IncognitoBA** [mavlink/qgroundcontrol#3036]
I have the pixhawk for QGroundControl, and when I try to calibrate the sensors, it shows "COMMUNICATION LOST". Using Mission Planner then calibration succesful.
I found the same problem #933, but there is no solution.
Help me please!
OS Windows 8.1; Vehicle 3DR Iris+

**Comment by jgoppert** [comment]
I can confirm this on windows. It is really annoying for mag calibration. When it doesn't confirm at the end the only way to set the external mag rotation is manually through the parameters.

**Comment by IncognitoBA** [comment]
jgoppert, thanks for your reply. I have only one step is completed, the next shows the "CONNECTION LOST". Does it work on Ubuntu Linux?

**Comment by DonLakeFlyer** [comment]
Make sure you are using latest master firmware. There was a fix made a little while back that fixed the no confirmation problem.

**Comment by IncognitoBA** [comment]
@DonLakeFlyer, I tried master firmvare, but the problem remained.

**Comment by DonLakeFlyer** [comment]
What problem? Communication Lost or no confirmation after calibration is complete. The change in master fixes confirmation after calibration is complete.

If you are using ArduPilot firmware the communication lost problem is not actually a real problem. It’s quirk of how ardupilot does calibration. I thought I had handled that, but I missed it for one of the calibration types. Which type of calibration are you doing? Calibration should still complete even though you get that message. Once calibration is done it should go away.

**Comment by IncognitoBA** [comment]
I use PixHawk firmware. My problem is that when I turn on the RC, it shows "CONNECTION LOST" and continue the calibration impossible. Almost the same thing happens when calibrating the accelerometer and other sensors. I forgot to clarify, I'm using Windows x64.

**Comment by IncognitoBA** [comment]
@DonLakeFlyer, I tried to do it on Ubuntu Linux 14.04 x64. It is the same problem.

**Comment by IncognitoBA** [comment]
Solved a problem! Although the message "COMMUNICATION LOST" is necessary to continue the calibration. Alerts vehicle prompt, when the step is completed. Thank you all for the help!
P. S. and sorry for my bad English :(
