### ISSUE TITLE
Migrate to Qt 5.6

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3040]
Qt 5.6 has been released (Qt's first LTS release): http://blog.qt.io/blog/2016/03/16/qt-5-6-released/

**Comment by NaterGator** [comment]
Upstream for appveyor: https://github.com/appveyor/ci/issues/698
WIP pull: https://github.com/mavlink/qgroundcontrol/pull/3043

**Comment by dagar** [comment]
We're jumping straight to 5.7 right?

**Comment by dogmaphobic** [comment]
Given that it's scheduled for next week, sure!

**Comment by dogmaphobic** [comment]
Running Qt's Online Updater today I noticed that 5.6.1 is available as well as 5.7RC. I will see if I find the time tomorrow to install and test it.
