### ISSUE TITLE
Slide to arm cancel indicator confusing

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3042]

**Comment by LorenzMeier** [comment]
https://cloud.githubusercontent.com/assets/749243/13810301/84a545b4-eb45-11e5-9689-f4c87e0850d6.png

In this image the cancel indicator seems to be part of the slider. I would prefer a separate circle for the cancel button, which has the proper affordable of being clicked. The current UI is extremely confusing, as you slide the arming button "onto" the abort button. That makes no sense.

**Comment by LorenzMeier** [comment]
Just power off your iPhone and look how they did it. That should say it all what went wrong here.

**Comment by dogmaphobic** [comment]
I dealt with this in #3037 yesterday. I too found it confusing to have the arrow pointing to a "cancel".

**Comment by DonLakeFlyer** [comment]
Yeah it's kind of out of whack. Just a quick hack to get around the button problem. I still think it needs a visible cancel somewhere but I'll deal with that later

**Comment by NaterGator** [comment]
Could also go the Android dialer route:
![image](https://cloud.githubusercontent.com/assets/2575/13860467/ddcf2c1c-ec5e-11e5-8d31-38f159416d47.png)

Slide left to cancel, right to confirm.

**Comment by LorenzMeier** [comment]
The slide accordance of iOS is significantly better. The lack of clear indication how long / far you have to slide is terrible with Android.

**Comment by LorenzMeier** [comment]
I meant affordance.
