### ISSUE TITLE
Unable to run latest build QGC

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3045]
Pon today build of QGC it will not run and shows the error message Qt5Core.dll is missing.  I had to completely uninstall QGC and reinstall it to work.

**Comment by NaterGator** [comment]
Confirmed. I think this is an NSIS race condition. Should have it fixed shortly.

**Comment by NaterGator** [comment]
@jcooper21 can you confirm the latest release fixes the problem for you?

**Comment by jcooper21** [comment]
That seems to have fixed the issue. Is there any way to keep my instrument panel setting and comm setting when updating to the newest daily builds?

**Comment by NaterGator** [comment]
It is a fair point and I created a ticket for it: #3047
