### ISSUE TITLE
Check direct connect of PX4Flow to QGC

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3055]
Reports of issues

**Comment by proficnc** [comment]
![qgc_1](https://cloud.githubusercontent.com/assets/4628419/14004916/07b717c6-f1b2-11e5-930d-e45ac5d3dbfe.jpg)
![qgc_2](https://cloud.githubusercontent.com/assets/4628419/14004915/07b530f0-f1b2-11e5-9e09-9d928af2e828.jpg)
![qgc_3](https://cloud.githubusercontent.com/assets/4628419/14004914/07b4d376-f1b2-11e5-95e3-2bfee3018bac.jpg)
![qgc_4](https://cloud.githubusercontent.com/assets/4628419/14004917/07bc3972-f1b2-11e5-827e-31785d38bf45.jpg)

When using firmware version.... which is reccomended for ardupilot.
http://firmware.ardupilot.org/downloads/wiki/advanced_user_tools/px4flow-klt-06Dec2014.zip

**Comment by DonLakeFlyer** [comment]
That firmware is reporting itself as MAV_AUTOPILOT_PX4 which is the id for PX4 Firmware. This causes QGC to think it's a Pixhawk running PX4 Firmware. Which then in turn causes all sorts of strangeness. Since there isn't a specific entry for FLOW firmware in the MAV_AUTOPILOT enum it should be reporting itself as MAV_AUTOPILOT_GENERIC not MAV_AUTOPILOT_PX4. The standard flow firmware which QGC installs comes from here: http://px4-travis.s3.amazonaws.com/Flow/master/px4flow.px4. It works correctly with respect to reporting MAV_AUTOPILOT enum values.

**Comment by LorenzMeier** [comment]
The flow binary you're referring to is stale and should not be used.
