### ISSUE TITLE
Look into auto-disconnect when link goes away

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3072]
Need to figure out how to deal with flaky UDP connections as well as OS differences on usb cable pull signalling across OS.

**Comment by DonLakeFlyer** [comment]
Some discussion here as well: #3056

**Comment by NaterGator** [comment]
@DonLakeFlyer on Windows QSerialPort::linkError is emitted with ResourceError: http://code.qt.io/cgit/qt/qtserialport.git/tree/src/serialport/qserialport_win.cpp?h=v5.5.1#n740

**Comment by DonLakeFlyer** [comment]
If I remember correctly the issue is that the signalling differs between OS. OSX sends aboutToClose whereas Windows does not. It was a while ago I looked at this though. Maybe OSX signals that as well.

**Comment by DonLakeFlyer** [comment]
Still not quite sure what to do with UDP though. WiFi connections come and go quite easily.

**Comment by DonLakeFlyer** [comment]
But in thinking about it communication lost is just missing heartbeat, whereas these are device level signals. So I can distinguish between the two: plug pull, lost communication.

**Comment by NaterGator** [comment]
Correct, semantically and in terms of user experience they are different things. Unreliable Wifi / network drops is just an indication of unreliable link. USB cord pulled (or OS level IO failure) is a more severe indication of a link fault that will definitely not resolve itself without user intervention. 

My OS X-fu is a little weak but I believe it returns ENXIO if the character device disappears, in which case the same error code will fire: http://code.qt.io/cgit/qt/qtserialport.git/tree/src/serialport/qserialport_unix.cpp?h=v5.5.1#n869

I'd say you're on the right track.
