### ISSUE TITLE
Camera test button

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3075]
It would be nice if there was a test came button or a way to do that from the ground station easily. Mission planner handles this by clicking the second mouse button on the map and selecting trigger camera now.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Starting a camera control UI element might make sense which displays current trigger mode and has start / stop recording for video (FPV).  We need that for Snapdragon as well.

**Comment by DonLakeFlyer** [comment]
Moving this to 3.1 to sync up with Survey work

**Comment by DonLakeFlyer** [comment]
Implemented
