### ISSUE TITLE
APM plane always displaying armed

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3082]
When i connect to APM plane QGC always displays that it is armed even if its unarmed.

**Comment by DonLakeFlyer** [comment]
I tried this with QGC master against ArduPilot master SITL and ArduPlane V3.5.1 on a board and in both cases it worked fine. Where are you seeing the armed indicator?

**Comment by jcooper21** [comment]
At the bottom of the screen it always says its armed. I can neither disarm or arm and it verbally says the plane is armed when it first starts up. I am on APM 3.5.1. It always says its armed even when it's not.

**Comment by jcooper21** [comment]
Could this be due to the arm switch?  I don't see a software arm parameter in APM.

**Comment by DonLakeFlyer** [comment]
Can you give me a screenshot like this from the mavlink inspector widget?

![screen shot 2016-03-25 at 8 22 15 pm](https://cloud.githubusercontent.com/assets/5876851/14057773/6562b7f2-f2c7-11e5-92b8-287bd1467537.png)

**Comment by jcooper21** [comment]
Sure. Give me 10 min

**Comment by jcooper21** [comment]
![capture](https://cloud.githubusercontent.com/assets/14355782/14057819/2542d008-f2d1-11e5-9491-8e047c11adb0.PNG)

**Comment by DonLakeFlyer** [comment]
I need the HEARTBEAT entry expanded out so I can see values.

**Comment by jcooper21** [comment]
![capture](https://cloud.githubusercontent.com/assets/14355782/14057839/dbcc8b52-f2d1-11e5-944f-7c41ee7decd0.PNG)

**Comment by DonLakeFlyer** [comment]
According to the value of base_mode the vehicle is armed. That is what the vehicle is reporting. So QGC is showing you the righ thing. Does APM Plane not have armed/disarmed concept?

**Comment by jcooper21** [comment]
To arm I hold down the safety switch and hold it down again to disarm. The plane was disarmed in those screenshots. I would prefer to eliminate the switch and do a software arm on a tablet but not sure how with a plane.

**Comment by jcooper21** [comment]
This also causes an issue for changing parameters as I have to go to mission planner since some parameters cannot be changed while armed.

**Comment by DonLakeFlyer** [comment]
Hmm, seems to be some strange usage of the armed bits going on with ArduPlane. I have the safety switch pulled off my board. Let me put on back on and see what happens with my testing.

**Comment by DonLakeFlyer** [comment]
I can't repro this with just my board. Let me get my fixed wing cut over to ArduPlane and I'll give that try.

**Comment by jcooper21** [comment]
I'll disconnect my arm switch and try

**Comment by DonLakeFlyer** [comment]
I tried it with a safety switch and it was still working correctly for me.

**Comment by jcooper21** [comment]
I just disconnected my switch and tried again same result. I am using an HK32 pilot with rfd900 radios

**Comment by jcooper21** [comment]
I tried a changing a bunch of arming parameters and couldn't get it to change. Mission planner does handle it correctly if that's any help.

**Comment by DonLakeFlyer** [comment]
> Mission planner does handle it correctly if that's any help.

In what way?

**Comment by jcooper21** [comment]
It displays disarmed and armed correctly and says safe when I hold the arm switch down.

**Comment by DonLakeFlyer** [comment]
I was just running through a fixed wing setup on ArduPilot. It looks like a number of things are out of whack beyond just arming. I'm going to have to do a full run through of setup to find all the problems.

**Comment by jcooper21** [comment]
In items in particular you found that I can check?

**Comment by DonLakeFlyer** [comment]
RC Cal seems to be pretty out of whack. No need to check I need to debug it.

**Comment by jcooper21** [comment]
Ya I think it is. It also likes to throw up a bunch of error messages when flying pre planned missions that were created in mission planner.  I just ignore it all at this stage.

**Comment by DonLakeFlyer** [comment]
The RCMAP_* settings don't seem to work correctly which is odd since that's a firmware thing.

**Comment by DonLakeFlyer** [comment]
Do you get these messages just connecting to the vehicle. Or do they come out when you are actively trying to arm/disarm the vehicle.

**Comment by jcooper21** [comment]
That's connecting th vehicle.

**Comment by DonLakeFlyer** [comment]
@jcooper21 Can you attach a zipped parameter set for your plane so I can repro your setup?

**Comment by jcooper21** [comment]
Don please see parameters zip
[tuffwing parameters 3.zip](https://github.com/mavlink/qgroundcontrol/files/217636/tuffwing.parameters.3.zip)

**Comment by jcooper21** [comment]
I found the issue its when the Arm_required parameter is set to 0 and the safety switch is only used to arm the plane QGC always says armed. If the value is set to 1 or 2 then QGC works correctly.

**Comment by DonLakeFlyer** [comment]
If ARM_REQUIRED=0 then according to the parameter description the plane is armed immediately. So QGC is correctly stating that the plane is armed. Also with this set to 0 you can't disarm the plane either. So although a bit strange QGC is doing the right thing according to how you are parameters set.

**Comment by jcooper21** [comment]
Interesting. With the safety switch mission planner says "safe" until the switch is pressed, so it's in a disarmed state which QGC does not.

**Comment by DonLakeFlyer** [comment]
Hmm. Still might be something out of whack here then. QGC doesn't really look for the "safe" state. Might need to be added.
