### ISSUE TITLE
Enhancement: Mission Time Estimation

### ISSUE THREAD

**Issue by tops4u** [mavlink/qgroundcontrol#3097]
I think it would be convenient to display an estimation about the expected Mission duration under normal conditions. The Max resp. Cruise Speed of the Vehicle is known by the new CRUISE Parameter, as well as any speed changes induced by the Mission itself. Thus it would be possible to display a estimation about the Flight Time needed to execute the Mission. Especially when starting using the Survey Function this would help Pilots to see if the Mission Time is in the Range of the Flying Time of the Aircraft.

**Comment by DonLakeFlyer** [comment]
Dup of #2906
