### ISSUE TITLE
Add gstreamer to all travis builds

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3108]

**Comment by dagar** [comment]
Missing Windows, OSX, iOS?

**Comment by DonLakeFlyer** [comment]
Yup. YOu want to handle this?

**Comment by DonLakeFlyer** [comment]
@dagar Do you think you could finish this one up?

**Comment by dagar** [comment]
I can do appveyor. Someone with a Mac should probably take care of OSX and iOS.

**Comment by DonLakeFlyer** [comment]
Only thing left is Windows

**Comment by DonLakeFlyer** [comment]
Wait: OSX not done yet. Need to figure out how to copy framework into dropped build.

**Comment by dagar** [comment]
Same situation for windows.

**Comment by DonLakeFlyer** [comment]
OS X is done now. @dagar Is windows done?

**Comment by dagar** [comment]
Yep
