### ISSUE TITLE
Log output covers vehicle

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#3115]
It is a bit unfortunate that the log window (which I heavily rely on) is covering the vehicle on the map. If there was some way to move either of the two, so that they don't overlap, that would be better.

**Comment by DonLakeFlyer** [comment]
Not sure what log window you are talking about. Screenshot?

**Comment by julianoes** [comment]
Sorry, I wasn't very clear. I mean the window with the status text messages.

**Comment by DonLakeFlyer** [comment]
Are you talking about the Info View widget?

**Comment by julianoes** [comment]
The one that displays mavlink statustexts, the one that folds down.

**Comment by julianoes** [comment]
I guess it is fine. I don't see where else the window could be placed.
