### ISSUE TITLE
Altitude not loaded from file for takeoff and vtol_takeoff command

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#3117]
It reverts to the default 25m when loading a mission file from QGC
It seems it did save the altitude to file (see attached)

[VTOL_TAKEOFF mission.mission.zip](https://github.com/mavlink/qgroundcontrol/files/194326/VTOL_TAKEOFF.mission.mission.zip)

**Comment by DonLakeFlyer** [comment]
@sanderux Can you give this a test one it goes through.
