### ISSUE TITLE
Analyze window too small

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#3118]
The "Analyze" window is way to slow when you open it. Also it would be convenient if it stored its size its size once you've changed it. 

![analyze_window_too_small](https://cloud.githubusercontent.com/assets/1419688/14134936/84319cde-f65a-11e5-8886-8695d378e137.png)

**Comment by DonLakeFlyer** [comment]
All of this widget stuff is going away. The window saving was turned off because it was causing other more serious problems. So for now, you're stuck with having to resize widgets each time.
