### ISSUE TITLE
remove windows cmd prompt

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3121]
Can we get rid of launching with the cmd prompt?

![screenshot 2016-03-31 09 46 56](https://cloud.githubusercontent.com/assets/84712/14177752/c3d82e2c-f725-11e5-9db6-85804acd4827.png)

**Comment by DonLakeFlyer** [comment]
If we can figure out some other way to get logging information when needed

**Comment by NaterGator** [comment]
This drives me crazy. I'll happily fix it.

**Comment by DonLakeFlyer** [comment]
Thanks Nate.
