### ISSUE TITLE
clear mavlink log

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3127]
Can we get a button to clear the mavlink messages?

![screenshot 2016-04-01 17 53 41](https://cloud.githubusercontent.com/assets/84712/14221189/f40a3b40-f832-11e5-8f67-03b9ecfe3718.png)

**Comment by NaterGator** [comment]
@DonLakeFlyer I find the whole singleton UASMessageHandler architecture a bit contrived. Do you mind if I pick this up and move UASMessages into a model stored on Vehicle? We can then switch this message console to a model-view based architecture that makes more sense.

**Comment by dogmaphobic** [comment]
Yes,  I agree. That code is some ancient left over from before any of the QtQuick UI was ever in place.

**Comment by dogmaphobic** [comment]
> Do you mind if I pick this up and move UASMessages into a model stored on Vehicle? We can then switch this message console to a model-view based architecture that makes more sense.

It makes it weird because it's still used by a Qt Widget *Widget*. If we get rid of that, it can be made a lot simpler. I had to hack some formatting (#3344) so it could be used in both places.

**Comment by dagar** [comment]
Thanks @dogmaphobic!

**Comment by DonLakeFlyer** [comment]
Toss the qt widget support
