### ISSUE TITLE
Fix Androind handling of connection with no WiFi

### ISSUE THREAD

**Issue by dzett** [mavlink/qgroundcontrol#3128]
Hi there,

I am running the current beta of QGC (2.9.4-280-g38090bf) on two Android devices: A Nexus 5 phone and an older Tablet connected via Wifi to a Pixracer with the current beta build of PX4. 

On the Phone, I get periodic error messages "Vehicle did not respond to request for parameters, retrying" although the map/instrument view is updated fine. The settings/parameters page is not accessible.

![screenshot_20160401-223843](https://cloud.githubusercontent.com/assets/9444774/14221233/9e885688-f865-11e5-8dd1-97da104934e2.png)
![screenshot_20160401-223900](https://cloud.githubusercontent.com/assets/9444774/14221239/ad4dc90a-f865-11e5-9757-013fe5f52aea.png)

On the Tablet, the issue does not happen (exactly same version). Daily build of the QGC Linux version on a PC connected via USB also is happy.
I have: Deleted all App data and re-installed the apps on both devices but it does not change.

The issue also happened with earlier master builds of PX4 and also with earlier beta versions of QGC, but there was some QGC version in between in the last three weeks where it did work correctly also on the phone.

Any clue? Is there a way I can support analysis by providing a log of some kind?

Thanks,
Daniel

**Comment by DonLakeFlyer** [comment]
Ok, so it is connected and getting heartbeats. But the vehicle is not responding to parameter requests. This is most likely an issue on the firmware side. 

@LorenzMeier Can you determine how the vechile is getting/responding to the param requests from teh sd logs?

**Comment by dzett** [comment]
Nevermind, I found out the cause:

It seems to be related to how Android 6 handles Wifi connections without internet connectivity.

Behavior is reproducible: After deleting the Pixracer Wifi network in Android and re-adding it, Android will show a "Wifi-Question-Mark" icon / message informing about missing internet connectivity. 
_So far, I would so far just swipe it away to disappear._ - not a good idea.
When opening it, a dialog is shown that asks (sorry, screenshot German only):

![screenshot_20160402-204718](https://cloud.githubusercontent.com/assets/9444774/14228593/dad35d54-f919-11e5-9223-fe1cb61b6d28.png)

"This network does not have internet access. Do you want to keep the connection?". If you answer "Yes" and tick "Don't as again", QGC immediately shows the progress bar and has data.
I guess swiping the dialog away keeps it in some odd "neither-yes-nor-no" state, where it doesn't disconnect (and accepts incoming UDP traffic?) but doesn't allow outbound connections.

This is on an Android 6.0.1 device. My older tablet (Android 4.1.1) doesn't have a similar dialog and just connects straight through (it shows the Wifi "grey" as there is not internet, but not questions or nagging...).

So, this is "solved" for me and not really a QGC issue. As briefly mentioned on gitter, maybe it would be possible to add a check to QGC (heartbeat ok but parameter request fails) and show a hint like "please re-add the FC Wifi network and accept it for connections" (not an easy one to word though). What do you think?

**Comment by DonLakeFlyer** [comment]
Maybe this: http://developer.android.com/reference/android/net/wifi/WifiManager.html#enableNetwork%28int,%20boolean%29

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Does any of this make sense to you?

**Comment by DonLakeFlyer** [comment]
Need to research this some more to figure out if there is some setting we need to change.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do we need to fix some wifi without internet thing for 3.0? Or move to 3.1? Or is there even a problem here?

**Comment by dogmaphobic** [comment]
I assume there is some (Java) interface to tell Android to buzz off and let the app use WiFi even though it's not connected to the "Internet". I won't have the time to deal with Android before 3.1.

**Comment by DonLakeFlyer** [comment]
Moving to 3.1

**Comment by dogmaphobic** [comment]
Could someone test this once #4380 makes it in?

**Comment by DonLakeFlyer** [comment]
If this is still broken in 3.2 we live with it. Moving to fixing in first phase of 3.3

**Comment by DonLakeFlyer** [comment]
Hoping it's fixed now
