### ISSUE TITLE
Camera trigger indicator feature request

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3156]
I have been planning my survey missions in mission planner and executing them in QGC. It would be really nice if QGC dropped an indicator on the flight line every time the camera triggers during flight. It could be something as simple as a dot on the flight line on each trigger so it confirms the camera is working and the survey mission is executing correctly.

**Comment by NaterGator** [comment]
This is captured in #2726

**Comment by jcooper21** [comment]
Ok

**Comment by DonLakeFlyer** [comment]
Not sure a message comes back for that from the Vehicle?

**Comment by jcooper21** [comment]
@DonLakeFlyer there is a big discussion going on with it for mission planner I found here. 

https://github.com/ArduPilot/MissionPlanner/issues/1210
