### ISSUE TITLE
Logging console improvements

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3160]
- Use a QSortFilterProxyModel to allow hiding different categories or severity-levels of messages. 
- Set row background color based on message severity 
- Fix file picker dialog on android (non-native)

**Comment by dagar** [comment]
Does severity map to mavlink info, critical, emergency?

**Comment by DonLakeFlyer** [comment]
No, it's Qt QCategoryLogging severity.
