### ISSUE TITLE
Improve visual cues for qml elements that can be interacted with

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3162]
For example it is not intuitive or obvious that waypoints can be changed to different types in the plan view by clicking on the descriptive text: 

![image](https://cloud.githubusercontent.com/assets/2575/14362702/badd913c-fcce-11e5-9df2-f80d1820c987.png)

The hamburger indicator wraps insert/delete/show all; I don't know if it is less confusing to combine the hamburger with the point type configuration (or something else) but I do find this confusing. Maybe this is just the placement of the button causing it to appear as a header? 

I'll try to document other areas where interaction / configuration is hidden behind something non-intuitive.

**Comment by DonLakeFlyer** [comment]
Yeah, this is a pretty bad one.

**Comment by DonLakeFlyer** [comment]
You can re-open if you have more places to change.
