### ISSUE TITLE
Calibration UI doesn't actually tell user when the side has already been done

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3167]
@DonLakeFlyer This is a pretty significant usability issue, as it just "doesn't do anything". I think in this case showing the text message overlay would be fair.

**Comment by DonLakeFlyer** [comment]
"side already completed" message from firmware is in incorrect format.

**Comment by DonLakeFlyer** [comment]
Waiting on: https://github.com/PX4/Firmware/pull/4200

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Its in!
