### ISSUE TITLE
Implement auto-connect for RTK GPS

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3184]
Considering a manual hack path for RTK connect since adding it to auto-connect is too extensive of a change this close to 3.0. Idea is to add a new Settings panel for this.

@bkueng FYI

**Comment by DonLakeFlyer** [comment]
Auto-connect is working, but disconnect is not. Also manual connect is not supported

**Comment by DonLakeFlyer** [comment]
Good enough for 3.0

**Comment by vmishra9** [comment]
Drotek RTK does not auto-connect to QGC via USB

**Comment by DonLakeFlyer** [comment]
@bkueng Should this be working?

**Comment by mhkabir** [comment]
Works for me.

**Comment by bkueng** [comment]
> @bkueng Should this be working?

Yes everything that uses the u-blox M8P should work.

**Comment by klopezal** [comment]
Could it be that you are using u-blox VCP drivers? Have you tried [Standard drivers](https://www.u-blox.com/sites/default/files/products/tools/UBX-GNSS-CDC-ACM-windows_Driver_%28UBX-drv-v1.2.0.8%29.exe.zip)?

**Comment by vmishra9** [comment]
@mhkabir Which version of QGC are you using? Was it plug and play?

**Comment by vmishra9** [comment]
@bkueng Can you please point out what could be the issue in my case?

**Comment by DonLakeFlyer** [comment]
* Can you follow the instructions here: https://docs.qgroundcontrol.com/en/Support/Support.html to turn on LinkManagerLog.
* Start QGC
* Connect RTK
* Save the Console log and paste here

**Comment by vmishra9** [comment]
@DonLakeFlyer I am getting the following block of logs repeatedly after connecting RTK:

LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM0"
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed

**Comment by bkueng** [comment]
I'm seeing this on master:
```
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: RTK GPS auto-connected
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
LinkManagerLog: Waiting for next autoconnect pass "/dev/ttyACM1"
```

And the RTK icon correctly shows up.
@vmishra9 which OS do you use?

**Comment by vmishra9** [comment]
@bkueng I didn't get "LinkManagerLog: RTK GPS auto-connected"

I am using ubuntu 16.04 LTS

**Comment by bkueng** [comment]
What does `lsusb` output when the GPS is connected? There should be a line like:
```
Bus 003 Device 021: ID 1546:01a8 U-Blox AG
```
And do you have a vehicle connected before connecting the RTK?

**Comment by vmishra9** [comment]
@bkueng I am getting the following output for lsusb

Bus 001 Device 011: ID 1546:01a8 U-Blox AG 

I do not have a vehicle connected to QGroundControl at the time of connecting the RTK using USB. Should I connect a vehicle before connecting the RTK? If yes, should I connect the vehicle using USB or Telemetry?

**Comment by bkueng** [comment]
> Bus 001 Device 011: ID 1546:01a8 U-Blox AG

That looks correct

> I do not have a vehicle connected to QGroundControl at the time of connecting the RTK using USB. Should I connect a vehicle before connecting the RTK? If yes, should I connect the vehicle using USB or Telemetry?

Yes, connect the vehicle first. It does not matter if it's USB or Telemetry, but the RTK icon will only show if a vehicle is connected (the user experience still needs to be improved here).

**Comment by myeVivek** [comment]
@bkueng It worked! Thanks for the help.

**Comment by DonLakeFlyer** [comment]
Auto-disconnect works now as well
