### ISSUE TITLE
Make OS X installer with GStreamer doesn't work

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3193]
Framework is not correctly rebound to new location inside package. To replicate:
- Install GStreamer packers
- Build installer
- Delete GStreamer packages from /Library/Frameworks
- Install QGC from .dmg
- Boot

Won't boot due to framework reference to /Library/Frameworks

**Comment by dogmaphobic** [comment]
It seems the relocation tool is no longer working. Looking into it...

**Comment by dogmaphobic** [comment]
Fixed in #3206
