### ISSUE TITLE
Total Mission Distance problem.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#3198]
Hi everybody,

I don't seem to find a way to have info on the total mission distance during my mission planning.

Any Ideas how to see it?

Thanks

**Comment by DonLakeFlyer** [comment]
It's not supported yet.

**Comment by tubeme** [comment]
It is important info, because we know how long the plane is capable of flying and we know its speed thus we have to take in to account what is the total millage of the mission in order to have the plane return safely.

**Comment by tubeme** [comment]
Not a bad idea if we have the timing info as well on another overlay. We know the cruise speed, we know the distance so we could interpolate the average time of the mission. Of course it will be estimate because there are dynamic conditions that can change the performance. But it could be a good info prior flight. We know how long our machines could fly given their bat or fuel depending on the case.

**Comment by DonLakeFlyer** [comment]
Time and distance are implemented now
