### ISSUE TITLE
RC Cal: Do not automatically update reverse for Throttle

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3200]
This is for multi-rotor only.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier This came up as needed during and ArduPIilot dev call. The reason being that it could be dangerous to have throttle reversed since a high PWM value will be interpreted as throttle. This could then confuse things like motor test which may not take reverse into account. Wondering about ESC cal as well with a reversed throttle. Plan was to warn if throttle is reversed, fail calibration and ask user to reverse throttle on the trasmitter. Questions is whether this should be for all firmwares or just ArduPilot?

**Comment by DonLakeFlyer** [comment]
I would think that the firmware should in fact handle this correctly, but I guess with ArduPilot it doesn't or there is an additional level of paranoia about getting this wrong.

**Comment by LorenzMeier** [comment]
PX4 doesn't link input and output as APM does. We do not suffer from this issue because input and output are separated properly.

**Comment by LorenzMeier** [comment]
So if you change it, do *not* change anything for PX4. Throttle should invert automatically.

**Comment by DonLakeFlyer** [comment]
Got it, thanks Lorenz.
