### ISSUE TITLE
appveyor install nsis from s3

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3204]
A large portion of appveyor failures seem to be sourceforge hosting problems. Stop installing nsis with  chocolatey (sourceforge) and just put the proper version on s3.

**Comment by DonLakeFlyer** [comment]
S3 download to the rescue!

**Comment by NaterGator** [comment]
Just for fun I'll put in a ticket with AppVeyor and see if they can install it as part of the build image. They already have NSIS 2.5.

**Comment by NaterGator** [comment]
Upstream issue is here https://github.com/appveyor/ci/issues/743#issuecomment-208987916
