### ISSUE TITLE
USB Serial Driver detection broken on Windows 10

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3210]
Maybe down as far as Windows 8? Windows 10 changed some of the registry layout so the current NSIS script fails to detect previous installs of the USB serial drivers.

Will need to spin up a Windows 7 VM to make sure I don't break things there when I fix for Win10.

**Comment by DonLakeFlyer** [comment]
@NaterGator Any help with this?

**Comment by DonLakeFlyer** [comment]
@NaterGator Back from vacation?

**Comment by DonLakeFlyer** [comment]
Moving to 3.1

**Comment by DonLakeFlyer** [comment]
@NaterGator Could you look at this for 3.1?

**Comment by DonLakeFlyer** [comment]
@NaterGator I'm working towards wrapping up a new Stable could you look into this one?

**Comment by NaterGator** [comment]
Yup, apologies that this slipped. When do you intend to have 3.1 wrapped?

**Comment by DonLakeFlyer** [comment]
On the order of weeks, not months and certainly not days yet.

**Comment by NaterGator** [comment]
Ok great, going out flying today but I will have a PR for this by the weekend.

**Comment by DonLakeFlyer** [comment]
@NaterGator I tried to figure this out myself but windows 10 seems to be radically different here
