### ISSUE TITLE
HIL broken on QGC daily (v2.9.4-398-gb16f091)

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3226]
HIL tested on PX4 stable + QGC 2.9.4 + X-Plane 10
Changed only QGC from v2.9.4 -> v2.9.4-398-gb16f091 and it won't connect to X-Plane.

Log
https://gist.github.com/dagar/13383afba0457791192ea359ee4579e4

**Comment by NaterGator** [comment]
It was broken by this commit.

https://github.com/mavlink/qgroundcontrol/commit/33edc72574274dbbc3badac6bc6d6e6929358cdd

**Comment by NaterGator** [comment]
@dagar reopen if XPlane doesn't work, but verified w/ flightgear.
