### ISSUE TITLE
Is that ok adding Multilanguage support for QGC?

### ISSUE THREAD

**Issue by bys1123** [mavlink/qgroundcontrol#3233]
Hello, We are chinese translators, we translated ArduPilot wiki, Mission Planner, DroidPlanner.
Is that ok add multilanguage support for QGC?
We'd like make a pull request for chinese language in few days.

**Comment by DonLakeFlyer** [comment]
QGC is not ready for translation. The strings are not yet fully marked correctly, although we have started working on it. Also the build process is not setup for translations. We have that slated for the 3.1 release.

**Comment by bys1123** [comment]
Thanks for you guys.

**Comment by DonLakeFlyer** [comment]
We'll get back in touch with you once we start working on 3.1.

**Comment by haigithub** [comment]
@bys1123 That's great. I would join into the translation group.

**Comment by bys1123** [comment]
@haigithub Welcome, please add my QQ 76006963

**Comment by dagar** [comment]
We're starting to think about adding support for other languages. See https://github.com/mavlink/qgroundcontrol/issues/3961

**Comment by haigithub** [comment]
OK, I get it.

2016-08-20 22:45 GMT+08:00 Daniel Agar <notifications@github.com>:

**Comment by bys1123** [comment]
Should we close this now?

**Comment by DonLakeFlyer** [comment]
Yup
