### ISSUE TITLE
qml file not found 

### ISSUE THREAD

**Issue by ivand58** [mavlink/qgroundcontrol#3237]
When tuning button is pressed it reports "qrc:/qml/PX4TuningComponentVTOL.qml: File not found".
The qgroundcontrol version is 2.9.4

**Comment by DonLakeFlyer** [comment]
Tuning config isn't supported for VTOL. Button no longer shows up

**Comment by LorenzMeier** [comment]
Tuning config is supported for VTOL. Where did the file go?

**Comment by DonLakeFlyer** [comment]
Tuning config has never been supported for VTOL. The file never existed.

**Comment by LorenzMeier** [comment]
Well, you're mistaken:
https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/PX4TuningComponentVTOL.qml

**Comment by DonLakeFlyer** [comment]
Fixed now
