### ISSUE TITLE
Screen corruption when using older APM versions

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#3243]
Was showing a friend that is running APM board running 3.2.1 using the latest QGC and noticed some screen corruptions, that I attach:

<img width="1106" alt="25f1ab5417293ec24cb8dadf3e7160b3519b7e83c4c56da568 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/3130363/14602485/1fb571c6-0560-11e6-8489-735699ed6c4d.png">

<img width="1274" alt="b5f002006030d96c4a9f9cbe7b5e592a56f62b1c8f153c600b pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/3130363/14602462/f8ad5f44-055f-11e6-82de-4c57eed59168.png">
<img width="1169" alt="21f5acad7ed90fa12be1d182176129e882eebac1be8b152513 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/3130363/14602466/f8b6f09a-055f-11e6-9085-466b235d978e.png">
<img width="1051" alt="c2de1772e9b2a4b4db9d09164e3c037759ce2c091b43756ee5 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/3130363/14602463/f8af65f0-055f-11e6-9ded-e80abb16aaca.png">

<img width="951" alt="24a81c903889a22597572752adf16423196cf4074f7eb08163 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/3130363/14602465/f8b49a8e-055f-11e6-8414-9f8357974df0.png">

**Comment by DonLakeFlyer** [comment]
That's a bad implementation of 3.2 support. QGC is not handling parameter differences correctly. The text is showing the mission parameter references.

**Comment by DonLakeFlyer** [comment]
Looks like APM boards have different parameter set from Pixhawk board on same rev 3.2 firmware? Does that make sense? I haven't really put any support into QGC for anything other than Pixhawk family boards. Not sure if it's worth the effort to fix this. I'm sure there are lots of other problems as well.

**Comment by lvale** [comment]
@DonLakeFlyer 
Just tested with a PixHawk running same 3.2.1 version and nothing strange happens.
Also had a chat with Tridge and there are in fact more parameters on PixHawk vs APM, so that might be a reason, but would require further investigation, and I don't have APM, and I believe there's not much interest for QGC to support APM boards ?
So if you wanna close this, go ahead :)

btw: Hope you're enjoying the desert ;)

**Comment by DonLakeFlyer** [comment]
I'm going to close this.
