### ISSUE TITLE
Include scale on map

### ISSUE THREAD

**Issue by cfelipesouza** [mavlink/qgroundcontrol#3258]
Scale on map refers to the relationship between distance on a map and the corresponding distance on the ground. 

It's an useful information that helps to plan the mission and also the flight, to understand the size of your mission and to guarantee that you are planning and flying with security. This would make the information more complete and make users more confident. 

Most online maps show this information, as below.

**Bing**
![screen shot 2016-04-22 at 9 54 32 am](https://cloud.githubusercontent.com/assets/7512740/14742446/a35e0442-0872-11e6-8f48-b630813d7b72.png)

**Yahoo**
![screen shot 2016-04-22 at 9 54 46 am](https://cloud.githubusercontent.com/assets/7512740/14742453/b03ce638-0872-11e6-9816-cb439de68368.png)

**Google**
![screen shot 2016-04-22 at 9 55 27 am](https://cloud.githubusercontent.com/assets/7512740/14742463/bec12b60-0872-11e6-9555-19db18906804.png)

We can bring this information in the same way, on lower side of Plan and Flight tabs.

@tcanabrava @anselmolsm @biapalmeiro

**Comment by dogmaphobic** [comment]
The scale doesn't come from Google (or whoever else we get the map from). It must be computed. It used to be there when I first wrote the new QtLocation plugin. Got lost in the cracks somewhere.

**Comment by cfelipesouza** [comment]
Totally understand, @dogmaphobic . And this information is important for the user. Can we bring it back? Are you going to label this issue as UX or maintain as an other?

**Comment by dogmaphobic** [comment]
I'm tagging as UX primarily because we need to figure out where to put it on an already crowded UI. Otherwise, it falls more into a "feature wanted" category.

**Comment by dagar** [comment]
Fixed in https://github.com/mavlink/qgroundcontrol/pull/3281
