### ISSUE TITLE
The battery is showed as it is 100% even it is not

### ISSUE THREAD

**Issue by cfelipesouza** [mavlink/qgroundcontrol#3259]
On the Usability Tests, we noticed that battery percentage is inconsistent. 

For example, the first time we connect the vehicle, it shows 100%, and decrease normal when using and planning the flight, indoor.

![screen shot 2016-04-22 at 11 38 31 am](https://cloud.githubusercontent.com/assets/7512740/14746365/9cf823d6-0885-11e6-9ba4-ec6f457c13ef.png)

So, we disconnected the vehicle to go outside...

![screen shot 2016-04-22 at 11 38 44 am](https://cloud.githubusercontent.com/assets/7512740/14745884/8f7e53bc-0883-11e6-8693-9e21c747dcc4.png)

... and connected again. The battery shows the same 100% as on the begin.

![screen-shot-2016-04-22-at-11 41 46-am](https://cloud.githubusercontent.com/assets/7512740/14746422/f44a3840-0885-11e6-9758-cf184c1c7ccc.png)

Is that a bug? How can we show the correct battery information? Is that possible to show the correct status? This kind of updated information is very important for user evaluate if he can fly properly, before take off, for example.

Version verified: v2.9.4-232-g26a9470 (Development), Linux.

@tcanabrava @biapalmeiro @anselmolsm

**Comment by dogmaphobic** [comment]
This is a guess. @LorenzMeier would be able to answer better. The percentage is based on the voltage reading. When you reconnected the vehicle outside, the battery had a chance to "rest" and the voltage went up a little. Enough to show 100%. Another factor that could be in place is temperature. I assume when you were indoors, you had air conditioning. Once outside, the temperature was higher, which also affects the battery voltage.

**Comment by cfelipesouza** [comment]
I got it. So, let's help us to understand how it works and then we can bring a good solution! :)

**Comment by jcooper21** [comment]
I just tested the battery percentage a bunch of times and I found there can be up to 10% variance. I did the test without calibrating the power module

**Comment by DonLakeFlyer** [comment]
There isn't much we can do here. This is how LiPo batteries work in some cases. When there is current draw against them they will drop. Then when the draw goes away they will go back up.

**Comment by booo** [comment]
A proper explanation was give. Closing this one therefore.
