### ISSUE TITLE
UI improvement suggestion

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3266]
I have been using a Microsoft surface and I have fat fingers so when I use the ground station to quickly switch flight modes I often hit the wrong one by accident. It would be nice if either the buttons were bigger or there was on confirmation pop up confirming the mode.

**Comment by booo** [comment]
@jcooper21 Is this still an issue for you? If not please close this ticket.

**Comment by booo** [comment]
Closing because of missing feedback.
