### ISSUE TITLE
HIL can't configure flight modes

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3274]
![screenshot 2016-04-25 11 22 46](https://cloud.githubusercontent.com/assets/84712/14788939/33084988-0ad8-11e6-8bde-ded88fb1eef6.png)

**Comment by DonLakeFlyer** [comment]
Shouldn't a HIL setup report back all sensors configured instead of making QGC special case this?

**Comment by dagar** [comment]
If it was SYS_STATUS sensor health or something similar I'd agree, but in this case I believe it's QGC just checking if the CAL params are set.
