### ISSUE TITLE
UDP Client support

### ISSUE THREAD

**Issue by fnoop** [mavlink/qgroundcontrol#3275]
Other GCS like APM Planner and Mission Planner support 'UDPCI' - UDP Client, where the GCS can specify the remote IP and UDP port to connect to, rather than the 'listen' udp mode where the GCS sits and waits for UDP incoming 'connection'.
This is invaluable when connecting through proxy/NAT etc, would be great if qgroundcontrol can do the same.

**Comment by fnoop** [comment]
It already exists, ignore me!

**Comment by dogmaphobic** [comment]
Ok, closing this then.
