### ISSUE TITLE
Android Error takes up screen - "...modified firmware.."

### ISSUE THREAD

**Issue by DanDon** [mavlink/qgroundcontrol#3277]
Each time I try to use QGroundControl on my android device it shows an error that obscures most of the screen and says something about modified firmware?? You can not get rid of this error or close the dialog box to continue. It just blocks the whole screen and makes the app not useable.

![screenshot_20160425-192643](https://cloud.githubusercontent.com/assets/595525/14794487/4b18f664-0b1c-11e6-8bcb-2e5794402601.png)
![screenshot_20160425-192655](https://cloud.githubusercontent.com/assets/595525/14794488/4b1d8a94-0b1c-11e6-948f-d24141b26194.png)
![screenshot_20160425-192931](https://cloud.githubusercontent.com/assets/595525/14794489/4b1db50a-0b1c-11e6-946a-a9fc92bc9b4a.png)

**Comment by DonLakeFlyer** [comment]
Related to #3255

**Comment by dogmaphobic** [comment]
This device seems just way too small to be usable. I thought we were blocking really tiny Android devices?

There are a few issues above besides error dialogs that take over the screen. Things just won't fit. Period. That error dialog seen above is meant to be a tiny window at the bottom of the screen. I will load QGC on something small tomorrow (Nexus 4) and see what can be done. I stopped testing small screens a long time ago with the assumption they were being blocked.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic This needs to be fixed along with a whole rework of the bottom popup error thing. The solution for that needs to take into account small screens.

**Comment by dagar** [comment]
The screenshots are 2560x1440. This is a device with a 5"-6" screen.

**Comment by dogmaphobic** [comment]
>The screenshots are 2560x1440. This is a device with a 5"-6" screen.

Ha! Good catch. That means the font scaling trick is failing miserably on that device. What is it?

**Comment by DanDon** [comment]
It is a Samsung Galaxy S7 and everything on the app works fine and it is very usable on a 5.1" display with 2K resolution.  It's only that dialog box that causes problems

**Comment by dogmaphobic** [comment]
The code used internally (within QGC) to compute UI scaling is not working at all on your phone. The UI doesn't look right. Here is what it's supposed to look on something around that size:

![img_2545](https://cloud.githubusercontent.com/assets/749243/14979858/f69ee1b6-10f2-11e6-8241-5e320cd3bb98.PNG)

What I would need is a screen shot of the debug window, which only exists on debug builds. If you are able to build QGC, that would help a lot. 

![img_2546](https://cloud.githubusercontent.com/assets/749243/14979873/18fa3cb0-10f3-11e6-96c8-c94ba50bb88a.PNG)

That will tell me the screen density advertised by the S7, which must be something completely off.

**Comment by DanDon** [comment]
I can run a debug build of the software to give you what you need if you can point me in the right direction. Not sure how to build an Android version. Or supply me with an APK that is already a debug build.

**Comment by dogmaphobic** [comment]
I found an old Nexus 4 and I could replicate the problem there. I have an intermediary fix in (#3326). Once it's merged, please let me know if it's better. It's not the final fix but it should at least make it usable.

**Comment by DanDon** [comment]
Latest android build release from Google Play works a treat. DPI settings now work fine and the user interface and warning dialog boxes are close-able :grinning:

**Comment by dogmaphobic** [comment]
Fixed by #3333
