### ISSUE TITLE
Plan tab freezes

### ISSUE THREAD

**Issue by biapalmeiro** [mavlink/qgroundcontrol#3282]
Text field doesn't accept special characters, neither letters. When it is typed after press < enter >, the current tab freezes.
![comma](https://cloud.githubusercontent.com/assets/5597786/14822672/ec71c250-0ba5-11e6-9330-131d34061ed2.png)

![screen shot 2016-04-26 at 11 25 28 am 2](https://cloud.githubusercontent.com/assets/5597786/14822706/015752b6-0ba6-11e6-8e02-ec8985061d4f.png)

Version verified: v2.9.4-524-g7ace9cd (Development), Mac OS X El Capitan v.11.10.14

@tcanabrava @anselmolsm @cfelipesouza

**Comment by dogmaphobic** [comment]
Some of the problems have been fixed in #3283 (position of the dialog). The *Freeze* part is something @tcanabrava added. I've commented it off for the time being so he can have a chance to fix it.

**Comment by biapalmeiro** [comment]
It is happening at these boxes also:
![screen shot 2016-04-26 at 3 06 12 pm](https://cloud.githubusercontent.com/assets/5597786/14829172/8b2b3cea-0bc0-11e6-8d70-2a1587e287c8.png)

**Comment by tcanabrava** [comment]
I already fixed, just sending a patch.

**Comment by DonLakeFlyer** [comment]
What is causing the text input to not work any more? Can someone point me at the change?

**Comment by dogmaphobic** [comment]
@tcanabrava would know better. It was his PR (#3196), which **this** PR fixes.

Also, out of curiosity, I don't know how my earlier PR (#3282) got in. Lorenz merged it. It's there but I don't see the actual *merge* in the logs. It just magically popped up in the list :)

![screen shot 2016-04-26 at 10 25 24 pm](https://cloud.githubusercontent.com/assets/749243/14840039/1cf5f2e0-0bfe-11e6-9460-ae51f926a339.png)

**Comment by LorenzMeier** [comment]
Fixed. @dogmaphobic That's the squash option GH offers today. Good idea to avoid tons of merge commits.

**Comment by biapalmeiro** [comment]
@LorenzMeier @tcanabrava @dogmaphobic Besides it isn't freezing anymore, the text field is accepting comma what opens the sidebar. Once the sidebar is open, it is not clear how to close that. It is necessary:

1. check force save (not recommended and dangerous as said on UI)
2. delete the comma

Should I open another ticket or we can reopen this one?

**Comment by tcanabrava** [comment]
On Wed, Apr 27, 2016 at 10:56 AM, Beatriz Palmeiro <notifications@github.com
> wrote:

> @LorenzMeier <https://github.com/LorenzMeier> @tcanabrava
> <https://github.com/tcanabrava> @dogmaphobic
> <https://github.com/dogmaphobic> Besides it isn't freezing anymore, the
> text field is accepting comma what opens the sidebar. Once the sidebar is
> open, it is not clear how to close that. It is necessary:
>
>    1. check force save (not recommended and dangerous as said on UI)
>    2. delete the comma
>
> Should I open another ticket or we can reopen this one?
>

I'm working on it (the best thing would to only accept valid GPS
coordinates, via a regular expression or something, I know that someone is
already working on this)
