### ISSUE TITLE
Parameter search box should be always visible

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3288]
@DonLakeFlyer The current parameter search tool is useless / non-existent because nobody finds it.

**Comment by devbharat** [comment]
In my view a search feature like in the analysis widget for plotting where typing the start of the parameter brings up all the parameters with that starting string, its way quicker that way at least for people with keyboards and not touch.

**Comment by sn0west** [comment]
If I may bring a small input here, by clicking the search button it would be nice that the cursor jump automatically in the text field. 
Thanks

**Comment by sn0west** [comment]
It maybe related to this topic. The reset all parameters should have at least one pop up that ask if this is really intended to be reset. I accidentally hit it and all was reset in a second. All sensor calibration, rc calibration, airframe and allvalues in the parameters.  Can you change that as well?
![image](https://cloud.githubusercontent.com/assets/9918649/14998262/6c74e5f8-1183-11e6-9781-6e4754f53eeb.png)

**Comment by DonLakeFlyer** [comment]
Both problems fixed:
- Search on top level UI
- Reset all prompts before resetting
