### ISSUE TITLE
Custom Airframe Config warning buttons are both "Reset"

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3295]
I guess there's only one way out of this...
![image](https://cloud.githubusercontent.com/assets/2575/14895848/c41bb8f2-0d48-11e6-9350-7b60b3c6b7db.png)

**Comment by dogmaphobic** [comment]
Well, you have the "subtle" reset and the "real" reset :P

**Comment by DonLakeFlyer** [comment]
Reset damnit!

**Comment by DonLakeFlyer** [comment]
Reject in QGCView is used as both an accept and reject action button. Waiting for parameter search pull to go through before I clean this up since that uses Reject in a strange way.
