### ISSUE TITLE
Mission transfer buggy when talking to PX4, but autopilot log looks correct

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3300]
The transfer actually succeeds, but shows this error message:

<img width="1241" alt="screen shot 2016-04-30 at 09 46 07" src="https://cloud.githubusercontent.com/assets/1208119/14934673/9590b84a-0eb8-11e6-85c6-d9544affdbcd.png">

```
mavlink_rcv_if2: WPM: MISSION_COUNT 5 from ID 255, changing state to MAVLINK_WPM_STATE_GETLIST
mavlink_rcv_if2: WPM: Send MISSION_REQUEST seq 0 to ID 255
mavlink_rcv_if2: WPM: MISSION_ITEM seq 0 received
mavlink_rcv_if2: WPM: Send MISSION_REQUEST seq 1 to ID 255
mavlink_rcv_if2: WPM: MISSION_ITEM seq 1 received
mavlink_rcv_if2: WPM: Send MISSION_REQUEST seq 2 to ID 255
mavlink_rcv_if2: WPM: MISSION_ITEM seq 2 received
mavlink_rcv_if2: WPM: Send MISSION_REQUEST seq 3 to ID 255
mavlink_rcv_if2: WPM: MISSION_ITEM seq 3 received
mavlink_rcv_if2: WPM: Send MISSION_REQUEST seq 4 to ID 255
mavlink_rcv_if2: WPM: MISSION_ITEM seq 4 received
mavlink_rcv_if2: WPM: MISSION_ITEM got all 5 items, current_seq=0, changing state to MAVLINK_WPM_STATE_IDLE
mavlink_rcv_if2: WPM: Send MISSION_ACK type 0 to ID 255
```

**Comment by LorenzMeier** [comment]
@DonLakeFlyer This is blocking the 1.3.0 release for PX4 as it makes us look buggy. I'm not yet sure what's going on here.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer I can only repro this when I have USB and the wireless link connected at the same time. The firmware is not sending mission replies via wireless though, so its probably something related to QGC's internal multi-link handling which is going wrong here.

**Comment by DonLakeFlyer** [comment]
Can you get a QGC MissionManagerLog for this as well?

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Still a problem?

**Comment by LorenzMeier** [comment]
Fixed.
