### ISSUE TITLE
ESC Calibration issue

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3303]
The ESC Calibration has issues when the ESC is calibrated it does a makes the chime sound while calibrating but once finished it verbally says calibration failed.  On the computer screen the slider says calibration complete and everything looks good.  I am calibrating a Turnigy plush 40 ESC.

**Comment by DonLakeFlyer** [comment]
Do you have a screen shot of what QGC looks like when ESC cal completes?

**Comment by jcooper21** [comment]
No I do not. Thetab on the right hand side pops up and says calibration complete. I assumed it was a voice issue or it would say calibration failed in writing

**Comment by DonLakeFlyer** [comment]
Ok, didn't realize you go the finished dialog. 

@LorenzMeier, @dogmaphobic  I don't have anything I can ESC cal with right now. So if either if you can take a look that would be great. Otherwise it's still a while before I get back home.
