### ISSUE TITLE
Collect licensing for all included libraries

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3310]
This is for Apple Store support. Since iOS has limited support only the following external libs are used:

eigen - GPL and LGPL https://github.com/mavlink/qgroundcontrol/tree/master/libs/eigen

**Comment by DonLakeFlyer** [comment]
@LorenzMeier You had wanted this.

**Comment by LorenzMeier** [comment]
Eigen is mostly MPLv2 which is in fact compatible. Fixed with https://github.com/mavlink/qgroundcontrol/pull/3368
