### ISSUE TITLE
"cmdid 11 command failed" shows while switch to Autotune/Flip/OF Loiter/Position mode

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3319]
Test Environment
Windows: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Windows 8.1 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Linux: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Ubuntu 14.04 LTS 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Purpose:
Check if the flight mode is able to switch.
Step:
1. Open QGroundControl
2. Connect to device
3. Try to switch flight mode to Autotune, Flip, OF Loiter and position mode.
Excepted result:
The flight modes should be able to switched, or if the flight mode doesn't support, the item should show gray, and prevent user switch to the mode.
Actual result:
"cmdid 11 command failed" shows

**Comment by DonLakeFlyer** [comment]
There is no way for QGC (or any ground station) to know whether a flight mode is currently available to be switched to or not. QGC only knows the full list of available flight modes. The firmware can fail a flight mode switch at any time, in which case it should send some user friendly error back to ground station to let the user know why the switch failed. In this case, the error message is bad. The Issue should be on the firmware side to provide a better error message as to why the flight mode could not be changed.
