### ISSUE TITLE
Multiple UDP connections causes vehicle confusion

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3321]
Test Environment
Windows: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Windows 8.1 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Linux: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Ubuntu 14.04 LTS 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Purpose:
Check if support Multiple UDP connections
Step:
1. Open QGroundcontrol
2. Add one vechile by UDP
3. Add other one by UDP again
4. Change the mode
Excepted result:
Only show one vehicle, but user can select which one vehicle to control
Actual result:
Two vehicles status are shown at the same time, which causes vehicle shows confusion

**Comment by dogmaphobic** [comment]
Make sure each vehicle has an unique ID. If the both have the same ID, the behavior is as you describe.

With that said, a cleaner solution would be for QGC to notice that these "same" vehicles are connecting from different IP addresses so it could, in theory, handle them separately.

**Comment by DonLakeFlyer** [comment]
@glody Does each vehicle have a unique ID?

**Comment by glody** [comment]
I don't know how to check vehicle ID. @DonLakeFlyer Where can I set unique ID for each vehicle?

**Comment by NaterGator** [comment]
It is under Parameters -> MAVLink -> MAV_SYS_ID

**Comment by glody** [comment]
@NaterGator , I didn't find the parameter.
![mav_id_01](https://cloud.githubusercontent.com/assets/1768868/15996133/01c7f2a6-3157-11e6-9500-9be0589740d2.JPG)
![mav_id_02](https://cloud.githubusercontent.com/assets/1768868/15996136/08f05b90-3157-11e6-89d3-265d9b51b9ce.JPG)

**Comment by DonLakeFlyer** [comment]
On ArduPilot the parameter is SYSID_THISMAV

**Comment by glody** [comment]
The Default SYSID_THISMAV is same. If change the SYSID_THISMAV manually, this issue is fixed. Is there any method to assign unique ID automatically?

**Comment by DonLakeFlyer** [comment]
Nope you have to do it manually for each vehicle.
