### ISSUE TITLE
Compass and barometer don't show in sensor list

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3322]
Test Environment
Windows: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Windows 8.1 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Linux: QGroundControl(Daily Build: v2.9.4.431- g6ab27c1) on Ubuntu 14.04 LTS 64 Bit Laptop + SITL(0d9b943) on Ubuntu 14.04 64Bit
Purpose:
Check if sensor list shows all sensors
Step:
1. Open QGroundcontrol
2. Check items and info on the summary page
Excepted result:
Compass and barometer show in sensor list 
Actual result:
Compass and barometer don't show in sensor list

**Comment by DonLakeFlyer** [comment]
Can you include a screen shot of what the Summary page looks like?

**Comment by DonLakeFlyer** [comment]
I checked the Vehicle Summary page in both PX4 and ArduPilot stacks and they are showing correct sensors.
