### ISSUE TITLE
Bettery Status always shows 0.00V while IRIS+ device connected

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3328]
Test Environment
Windows: QGroundControl(Daily Build: v2.9.4.449- gf7ad369) on Windows 8.1 64 Bit Laptop  + ArduCopter v3.3.3 on iris+
Purpose:
Check if power status shows normally
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Check power status on status bar
Excepted result:
Real poser status should be shown
Actual result:
Bettery Status always shows 0.00V

**Comment by LorenzMeier** [comment]
This is a firmware issue.
