### ISSUE TITLE
QGC ignores voltage check before Arming

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3330]
Test Environment
QGroundControl: Daily Build: v2.9.4.449- gc6fd7bb
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Drone Device: ArduCopter v3.3.3 3DR Iris+ 
Purpose:
Check if Arming Checks works well
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Open Safety item in settings page
4. Check in "Voltage" on Arming Checks tab
5. Try to arm the device
Excepted result:
Because QGC unable to detect the device's voltage(#3328), the device should can not to arm.
Actual result:
The device is able to arm while the voltage shows 0.00V

**Comment by DonLakeFlyer** [comment]
QGC isn't really responsible for determining if Arm should fail or not based on specific conditions. The vehicle firmware is responsible for that and should fail the arm.
