### ISSUE TITLE
Param filter field does not respond to enter

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3337]
@DonLakeFlyer Usability from hell 8). You have to click the button on the left, which looks like a label because its on the left. Buttons for text fields are *always* to the right of the field.

**Comment by LorenzMeier** [comment]
Also, the common english term is "Search", not "Filter by:"

**Comment by dagar** [comment]
Related: https://github.com/mavlink/qgroundcontrol/issues/3229

**Comment by DonLakeFlyer** [comment]
I can see our users flinging themselves off cliffs due to this! Heehee.

**Comment by DonLakeFlyer** [comment]
I moved the enter key support to #3229
