### ISSUE TITLE
Map interaction painful / confusing

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3339]
This here is an user report, but my experience is similar:

For me on the MacBook it is almost impossible to use Mission Planing. Due to:
Still eratic two finger gesture if zooming, panning or trying a right mouse click!
I tried hard about 5mins to delete all my mission Items by selecting one-by-one and deleting them. I gave up after this worked out for about 2 out of 5. Please have a function which deletes a whole Mission.

**Comment by dogmaphobic** [comment]
This is Don's domain, but as he's out reenacting *Deliverance*, here is one way to do it:

![screen shot 2016-05-05 at 6 23 49 pm](https://cloud.githubusercontent.com/assets/749243/15059200/ec7d86da-12ee-11e6-98c9-e226157c206b.png)

**Comment by DonLakeFlyer** [comment]
Mac trackpad support is completely out of whack in Qt is you use map inside QQuickWidget. Issue already in on this.

**Comment by DonLakeFlyer** [comment]
I had remove all on the hamburger menu as well before. I moved it to sync. Maybe having it broth places would be better.

**Comment by LorenzMeier** [comment]
Yes, both would definitely help. People don't expect it under sync.

**Comment by DonLakeFlyer** [comment]
I turned off two finger pinch on Mac due to Qt bug. Two finger drag scroll still works to zoom in/out.
