### ISSUE TITLE
OS X 10.11 serial port pain

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3340]
@DonLakeFlyer It would be good to know if this is really an OS issue or our usage. It completely ruins the experience for OS X users. I will try to see if I can connect fine with other tools and then try to work out if this requires a QGC level or NuttX level fix.

**Comment by DonLakeFlyer** [comment]
I think there is already an issue open on this. Try Mavproxy  to see if it works. Last check APM Planner 2 had same hang problem

**Comment by LorenzMeier** [comment]
Closing as duplicate of #3225.
