### ISSUE TITLE
MAVLink param names can be 16 chars wide in editor, but get cropped

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3345]
To repro run the PX4 fixed wing config (SYS_AUTOSTART set to 3033). These params are 16 chars long and get cropped on a 13" screen:

<img width="1241" alt="screen shot 2016-05-08 at 11 24 56" src="https://cloud.githubusercontent.com/assets/1208119/15097033/958c8d3a-150f-11e6-80be-7477591778ab.png">

**Comment by DonLakeFlyer** [comment]
This doesn't look to be from a latest build. It doesn't have the search thing on the top. Maybe it's missing some of Gus' changes? The column width is set to 20 char widths which would seem to work fine. But I can't test on Android.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Can you retry this with latest builds?

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Retest?

**Comment by DonLakeFlyer** [comment]
I tried latest build on my 13" and my 9". Fine on both.
