### ISSUE TITLE
Users confuse autopilot and mag orientation setting in mag dialog

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3348]
We need icons or some other visually clear differentiation between autopilot and mag. Users keep confusing the two, in particular since the mag calibration asks in the first step for the *AUTOPILOT* orientation, but the user's mental model is all about the mag (and so in user tests a lot of them select the mag's orientation).

<img width="1241" alt="screen shot 2016-05-08 at 23 57 55" src="https://cloud.githubusercontent.com/assets/1208119/15100671/156628d6-1579-11e6-9118-e6aa0bb3dce9.png">

**Comment by DonLakeFlyer** [comment]
The ArduPilot screen looks like this
![screen shot 2016-05-23 at 2 25 11 pm](https://cloud.githubusercontent.com/assets/5876851/15485095/33fd781a-20f2-11e6-8c6a-bf6e1eb14318.png)

Is that better?

**Comment by LorenzMeier** [comment]
Much better. Way too much text on the PX4 side and the description is not really user-parseable.

**Comment by LorenzMeier** [comment]
Also the mag cal pops a right dialog for the autopilot orientation. I would not do that. Better approach would be to pop the autopilot orientation dialog for ACCEL cal only and to condition the mag cal button click ability on accel being finished.
