### ISSUE TITLE
Button sizes on Android 10" (Galaxy Tab 4) very small in flight view

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3349]
@DonLakeFlyer @dogmaphobic The buttons are small and almost impossible to activate. The slider is much bigger and ok to use, but could be still bigger (still finicky).

**Comment by dogmaphobic** [comment]
Hopefully it's all fixed in #3354. Tested on Nexus (4, 7 and 9), iPhone and iPad (in addition to make sure nothing changed on non mobile platforms).

**Comment by LorenzMeier** [comment]
Will report back once my tablet updates.

**Comment by LorenzMeier** [comment]
Fixed.
