### ISSUE TITLE
QML QGCButton with Menu rendering incorrectly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3352]
<img width="495" alt="screen shot 2016-05-08 at 7 17 27 pm" src="https://cloud.githubusercontent.com/assets/5876851/15100998/929d80ba-1551-11e6-9d46-e0508cace873.png">

Probably some bug in there all along exacerbated by the recent font sizing changes.

**Comment by dogmaphobic** [comment]
Fixed in #3354
