### ISSUE TITLE
Current mission is loaded on initial connect in fly view, but not in edit view

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3355]
@DonLakeFlyer If you connect to a vehicle which already has a mission loaded the mission will be loaded and displayed in flight view, but not in the edit view. If you hit sync in the edit view the mission shows up.

From a user perspective we clearly want both views to load the existing mission if the user didn't edit his own in the editing view.

**Comment by DonLakeFlyer** [comment]
I disconnected this a while back because it was causing all sort of problems. I'll try to figure out how to get it working again.
