### ISSUE TITLE
Map caching: Default to Provider which is used for the map, don't let user choose by default

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3358]
@dogmaphobic The wide array of caching choices is nice, but nobody knows which provider is actually used in the background. It would be better to not let the user choose the provider by default, but just select what is currently used in the flight view.

That said we should also link the map providers of the edit and flight view for the same reasons.

**Comment by dogmaphobic** [comment]
Mapping management between the Plan View/Flight View and Map Tile Caching would have to be consolidated. Don made some changes to the original code to make it simpler (less options). You now need to go to *General Settings* to select the map provider for either of those views. When I put the caching code together, I added even more providers, which cannot be easily added back to the main views as those are now hardcoded. 

> but just select what is currently used in the flight view.

That would mean restricting to only the two, hard coded providers set in flight view.

This is going to be a bit involved. Let me see what it would take...
