### ISSUE TITLE
Andriod build error 

### ISSUE THREAD

**Issue by sadmzyy** [mavlink/qgroundcontrol#3366]
linking debug\libqgroundcontrol.so 
d:/android/android-ndk-r11/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.exe: error: cannot find -lQt5Netork
C:\Qt\Qt5.5.1\5.5\android_armv7\include\QtNetwork/qnetworkreply.h:103: error: undefined reference to 'QNetworkReply::staticMetaObject'

**Comment by DonLakeFlyer** [comment]
Android is building fine. So this is a setup problem somewhere on your machine. Please move this discussion to the google group and we can try to help there.
