### ISSUE TITLE
Feature Request visualize geofence radius

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3373]
It would be great if QGC visualized the geofence highlighting a circle around the home point so we know if we are planning a mission outside of the geofence.

**Comment by dagar** [comment]
While we're at it we should also show the loiter radius.

**Comment by jcooper21** [comment]
@DonLakeFlyer should this have the label surveying since we need to see the geofence to ensure we are planning the survey inside the area?

**Comment by DonLakeFlyer** [comment]
Implemented
