### ISSUE TITLE
Virtual Joystick can't control PX4 flight stack.

### ISSUE THREAD

**Issue by SamChenzx** [mavlink/qgroundcontrol#3378]
I'm using Qgroundcontrol 2.9.7b as my ground station and I want to use the virtual joystick without a real RC or joystick radio by setting COM_RC_IN_MODE to 0(Joystick/No RC Checks). I can arm motors by command line. The problem is when I attempt to takeoff my quadrotor in manual flight mode which runs PX4 flight code, no matter how I move the virtual joystick, the PWM output seems always be 0, I want to know that do I need extra setup before using virtual joystick, or virtual joystick can not control a real quadrotor?

**Comment by dagar** [comment]
Try COM_RC_IN_MODE 1

**Comment by SamChenzx** [comment]
When I change COM_RC_IN_MODE to 1, as I don't have a real RC radio
connected to quadrotor, QGC warns that:
Detected 0 radio channels. To operate PX4, you need at least 5channels.
And the Radio menu turn into red color. Does it works?

**Comment by andrejpan** [comment]
Hey,

I set up pixracer and QGC 2.9.7 with psp3 gamepad. COM_RC_IN_MODE has settings Joystick/No RC Checks (I do not see any number with this parameter any more). There is also settings for a joystick, QGC should recognize type of gamepad and calibration should be also made. 
![gamepad_settings](https://cloud.githubusercontent.com/assets/1015265/15367618/3e770e62-1d2a-11e6-85a1-4dcbc45e6c81.png)

And I think this is it. In few days I will also try QGC 2.9.7beta and I can report if gamepad control still works.

**Comment by LorenzMeier** [comment]
@SamChenzx You need to arm via QGC to control the system. You cannot arm it with the virtual joysticks. It sounds like you're trying to do that.

**Comment by andrejpan** [comment]
Currently I am arming/disarming motors with virtual joystick with no problem, should we make another issue?

**Comment by SamChenzx** [comment]
@LorenzMeier Yes, that's the problem, I can't arm it with the virtual joysticks. Besides, seems can't arm it via QGC, as in the screen shot, QGC just start with a white circle with no arm/disarm option.
<img width="1440" alt="screen shot 2016-05-18 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/10758544/15373016/2f7d4e9e-1cf8-11e6-88f9-fdcdd1987940.png">

**Comment by LorenzMeier** [comment]
QGC does only allow you to arm if you have GPS. The reason is that flying the system reliably without any position input is very hard for untrained pilots. We only recommend to fly the system in POSCTL mode with thumb sticks.

**Comment by SamChenzx** [comment]
With a GPS lock, it't much reliable to control vehicle. But how about the indoor application, we are not so easy to acquire GPS information in a hermetic room.

**Comment by SamChenzx** [comment]
Other issues here are as follows:
Firstly, QGC sometimes can't arm quadrotor even with GPS locked, as using virtual joystick, QGC warns that:Arming DENIED. Manual throttle non-zero. At this situation, my virtual joystick's two thumb pads are both at zero point actually. Does it mean I should pull the left thumb pad down to make throttle to zero?
<img width="1440" alt="screen shot 2016-05-19 at 8 51 11 am" src="https://cloud.githubusercontent.com/assets/10758544/15408190/b5ca5e76-1dc3-11e6-8b3e-2213594c1081.png">
Secondly, when I arm it via command line, the output PWM signals seems always have one motor or two at a high duty cycle, but which motor can be high duty varies from time to time(shows in the below screen shots, can be motor 2 or sometimes motor 4), though I still leave thumb pads at zero point and keep my quadrotor horizontal and stable on the ground. I have no idea it's an issue of QGC or PX4 flight code.
<img width="1440" alt="screen shot 2016-05-19 at 8 39 32 am" src="https://cloud.githubusercontent.com/assets/10758544/15408543/93e15c40-1dc5-11e6-8293-5d7d4120e6b2.png">


<img width="1440" alt="screen shot 2016-05-19 at 8 47 16 am" src="https://cloud.githubusercontent.com/assets/10758544/15408553/a430560a-1dc5-11e6-9406-fbaaa1ccd559.png">

**Comment by MathiasGilson** [comment]
Found it ! You need to disable the safety switch from the parameters: put the param **CBRK_IO_SAFETY from 0 to 22027**. This will simulate that the safety switch is always on and you will be able to arm it ;)

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Shouldn't firmware send better error to ground station about failure to arm if it's the safety switch. Otherwise user has no idea what the problem is?

**Comment by dagar** [comment]
I still find arming and mode change rejection errors bewildering.
https://github.com/PX4/Firmware/issues/4663

**Comment by sneiman** [comment]
I have this problem. cf2 running px4. QGC 3.0.1 on ubuntu 16.04. flight mode set to stabilized, CBRK_IO_SAFETY = 22027. using taranis 9d plus as joystick. cfbridge to QGC to MAVLink to Crazyradio PA. Can only arm using flight screen ARM button. Can fly once I do this. Its a problem for my specific development - working on swarms of cf2s and a custom 130 for both controlled and preplanned follow flight - REALLY need to make things happen from controller. Am I missing something? thanks

**Comment by DonLakeFlyer** [comment]
Do you get no response from the Vehicle. Or does it send back that it rejected the arm?

**Comment by sneiman** [comment]
I get nothing - no messages on flight screen,  or in console, or in status bar. Am I correct in trying to arm with throttle at 0, and yaw/rudder extreme right for 5 seconds?

On a minor note, when using a joystick with 0 throttle at extreme bottom, system calibrates properly but requires the throttle stick to be moved each time QGC is started to show correct stick position/value. Just fyi.

**Comment by DonLakeFlyer** [comment]
What version of QGC are you using?

**Comment by sneiman** [comment]
3.0.1 on Ubuntu 16.04.

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by metinburak** [comment]
Hi, when we arm and takeoff via QGC, then use virtual joystick in POSCTRL mode, QGC sends the manual control mavlink messages to Pixhawk through the telemetry 1. When we use the telemetry 2 port of Pixhawk (in POSCTRL mode) with a companion computer on the drone and send the same mavlink messages to Pixhawk as what the virtual joystick sends, we can not control the drone. Does the POSCTRL mode only accept the manual control messages from Telemetry 1?

**Comment by SamChenzx** [comment]
Hi, Burak

If use companion computer, you can try offboard mode to control the drone.

**Comment by DonLakeFlyer** [comment]
> QGC sends the manual control mavlink messages to Pixhawk through the telemetry 1. When we use the telemetry 2 port of Pixhawk (in POSCTRL mode) with a companion computer on the drone and send the same mavlink messages to Pixhawk as what the virtual joystick sends, we can not control the drone.

@metinburak You are going to have to ask the firmware folks about that. Not really a QGC question.

**Comment by Mocart96** [comment]
hello @metinburak
I know topic is old but did you find an answer on Telemetry2 port issue? 
Could you explain me little more what means "we can not control the drone"?

**Comment by sneiman** [comment]
sorry - not much help from me. i stopped using this setup some time ago before fully resolving this issue. good luck

Sent from mobile device - sorry for typos and brevity.

This entire message is confidential. If it isn't intended for you, you may not use it - so please throw it away and forget about it.

On May 1, 2018, at 10:05 AM, Adam <notifications@github.com<mailto:notifications@github.com>> wrote:


hello @metinburak<https://github.com/metinburak>
I know topic is old but did you find an answer on Telemetry2 port issue?
Could you explain me little more what means "we can not control the drone"?

**Comment by apurvadey** [comment]
Hey have you been able to to use the virtual joystick without a real RC or joystick radio by using COM_RC_IN_MODE ??
