### ISSUE TITLE
logs - no time assigned

### ISSUE THREAD

**Issue by andrejpan** [mavlink/qgroundcontrol#3380]
I am using Ubuntu 14.4 and QGC v2.9.7b Release and when I am seeing logs there no information about time data.
![logs_date](https://cloud.githubusercontent.com/assets/1015265/15370647/2cbff2f2-1d38-11e6-9860-9bfd2ba322dc.png)

![no_date](https://cloud.githubusercontent.com/assets/1015265/15370958/8bc57f3c-1d39-11e6-9d0f-bebfc834fa8c.png)

**Comment by LorenzMeier** [comment]
You can see in your screenshot that the time is actually a default time and has no meaning. So the time is actually correctly unknown. You need to use the system time sync via MAVROS or connect a GPS module to get a correct time indication.
