### ISSUE TITLE
Suggest QGC's virtual joystick, especially the throttle stick can keep still when lose hold of it. 

### ISSUE THREAD

**Issue by SamChenzx** [mavlink/qgroundcontrol#3385]
I find it's quite difficult to control PX4 flight use virtual joysticks, especially on Linux side, users can't pull throttle down and slide to arm at the same time, on android devices this can be done due to multi touch support. I find a simple GCS shown in the below, which is much easier for users to control PX4 flight via virtual joystick as it will keep still when I lose my hand on throttle stick. The cross-stick is much simple and easy to operate. I think it will be much better if the virtual joystick is easier to operate.
![screenshot1](https://cloud.githubusercontent.com/assets/10758544/15451264/bcc76bae-1f6e-11e6-8e21-4b0ce55006b5.png)
![screenshot](https://cloud.githubusercontent.com/assets/10758544/15451266/c0e7aa96-1f6e-11e6-9591-951650f6f564.png)

**Comment by LorenzMeier** [comment]
I don't understand the core issue - what part is not responsive?

**Comment by SamChenzx** [comment]
@LorenzMeier Sorry for the unclear description. The core issue is when I start up QGC, both left and right virtual joysticks will keep at the center, and if I let go of the joysticks, they will return to center. It's good for the right virtual joystick.
However, if the left joystick's vertical direction is used for controlling throttle, I think it will be better to start at the lowest position, shown in the below picture:

<img width="320" alt="screen shot 2016-05-23 at 1 07 20 pm" src="https://cloud.githubusercontent.com/assets/10758544/15482986/5ff79460-20e7-11e6-8e12-327911f00bd3.png">

Besides, when let of it don't automatically return to center but keep the vertical position where it is, as the referred GCS or a real joystick do. If both virtual joysticks start up at center,  users who use virtual joysticks can't arm vehicles by  sliding arm button in QGC, as the initial throttle not at the zero point. Please check it, thanks!

**Comment by DonLakeFlyer** [comment]
Virtual joysticks are mainly meant to be use with a non-manual flight mode such as Position Control. In this case centering makes more sense. I would suggest arming using the Arm button instead of the virtual sticks.

**Comment by SamChenzx** [comment]
@DonLakeFlyer  Those days we have tested snapdragon flight runs PX4 outdoor and with GSP locked. The issue is that I can switch between Manual, Acro, Stabilized, Rattitude and Altitude Control, while Position Control and other flight mode can't be used, don't know why but QGC warns "Set mode command temporarily rejected".

**Comment by DonLakeFlyer** [comment]
The comes from the Vehicle so you need to ask on the Firmware side
