### ISSUE TITLE
Arm button loses if the vehicle doesn't GPS lock

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3389]
Test Environment
QGroundControl: Daily Build: v2.9.7b-13-g06d3078
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the vehicle is able to arm while no GPS locks.
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Switch stabilize flight mode and try to arm under No GPS Lock
Excepted result:
The Arm button show on the bottom of the screen even on GPS lock for vehicle.
Actual result:
Arm button loses, I can arming the vehicle by RC Transmitter.
Git bisect result:
commit 4cfd5a1d04dce6c62e8691e3b8bc821bf93fc0ed
Author: Lorenz Meier <lm@inf.ethz.ch>
Date: Tue May 10 12:39:51 2016 +0200
Flight display: Fix visuals, hide states that should not be operated, make sliders safer and allow to reduce altitude
![unable to arm](https://cloud.githubusercontent.com/assets/1768868/15458743/6ec696ba-20d0-11e6-8790-ca586e4669ed.JPG)

**Comment by DonLakeFlyer** [comment]
Closing top use #3391 instead
