### ISSUE TITLE
Connecting to Pixracer through /dev/ttyACM0

### ISSUE THREAD

**Issue by andrejpan** [mavlink/qgroundcontrol#3395]
I am using QGC 2.9.7b and PX4 flight stack (standard version and I just updated the firmware). Unfortunately I did not find a way how to check which version of RTOS is running  currently on Pixracer from QCG. I am trying to connect via serial port with these two commands:
```{r, engine='bash', count_lines}
minicom -D /dev/ttyACM0 
```
or
```{r, engine='bash', count_lines}
screen /dev/ttyACM0 57600 8N1
```
After that I just see gibberish stuff
![minicom_problem](https://cloud.githubusercontent.com/assets/1015265/15504546/c6738a68-21bf-11e6-847e-ffe0a75e19c2.png)

Am I missing something or this could be a bug?

**Comment by DonLakeFlyer** [comment]
You should ask this question on either the PX4 firmware google group or gitter channel. This doesn't have anything to do with QGC.
