### ISSUE TITLE
Look into using Native file dialog again

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3398]
OSX file dialogs seems to be working ok now

**Comment by NaterGator** [comment]
Qt's file dialogs from QML land on Android are an abomination.

**Comment by DonLakeFlyer** [comment]
> Qt's file dialogs from QML land on Android are an abomination.

I didn't think they were implemented yet. Did they show up in 5.6? On Android I use my own file thing.

**Comment by NaterGator** [comment]
![screenshot_20160525-001012](https://cloud.githubusercontent.com/assets/2575/15527943/38d1f232-220d-11e6-9101-561b75b27d52.png)

**Comment by DonLakeFlyer** [comment]
Moving to 3.1
