### ISSUE TITLE
qgroundcontrol the waypoints are not drawn on the map

### ISSUE THREAD

**Issue by philippelecoq** [mavlink/qgroundcontrol#3409]
Ubuntu 16.06
last build May 2016 : 
qgroundcontrol  Video streaming is OK but the waypoints are not drawn on the map

**Comment by DonLakeFlyer** [comment]
What build are you using: Stable, Daily or built yourself. If you build yourself you must use Qt 5.5 not 5.6.

**Comment by philippelecoq** [comment]
I use the version on github (README.md process)

**Comment by DonLakeFlyer** [comment]
The README is out of date. You need to be using Qt 5.5 not Qt 5.6.

**Comment by philippelecoq** [comment]
/opt/Qt5.5.1/Tools/QtCreator/bin/qtcreator.sh
Segmentation fault (core dumped)
