### ISSUE TITLE
Update README to specify Qt 5.5 only, not Qt 5.6+ support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3410]

**Comment by philippelecoq** [comment]
Hello,
With Qt 5.5 there is this message (not with qt 5.6) : 
Could not find qmake configuration file default.
Error while parsing file /root/qgroundcontrol/qgroundcontrol.pro. Giving up.

**Comment by DonLakeFlyer** [comment]
Something is wrong with your installation. Most likely you kit is not set up correctly.

**Comment by dogmaphobic** [comment]
First, make sure it's Qt 5.5.1. Second, are you really running it as root?

**Comment by philippelecoq** [comment]
as root : 
/opt/Qt5.5.1/Tools/QtCreator/bin/qtcreator.sh
Segmentation fault (core dumped)

id
uid=0(root) gid=0(root) groups=0(root)

**Comment by philippelecoq** [comment]
under Ubuntu 16.04 LTS kernel 4.4.6

**Comment by DonLakeFlyer** [comment]
Updated README to specify 5.5
