### ISSUE TITLE
Param handling stuck with old vehicle instance

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3418]
If you connect SITL, then stop SITL, then connect a drone via USB the params are still those of SITL and you can neither write them (has no effect, no error message) nor refresh them.

**Comment by DonLakeFlyer** [comment]
The unique id change should close this whole but still should take a look as to why thing don't work correctly.

**Comment by DonLakeFlyer** [comment]
This is the same problem as #3342
