### ISSUE TITLE
El Capitan: Remaining serial issues

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3420]
* If booting QGC first, then connecting USB link connection always succeeds
  * If connecting USB link first, then connecting QGC connection is established for 5 secs, then looses connection
  * A manual test with screen is successful before

Based on this I believe this is a race during QGC setup / boot which can make it leave a link in a bad state. El Capitan has been super flaky in general before, but the latest beta led for me to this deterministic pattern and screen giving me 100% success.

![screen shot 2016-05-27 at 21 01 58](https://cloud.githubusercontent.com/assets/1208119/15618496/af49683a-244e-11e6-93d2-d071438983c6.png)

**Comment by DonLakeFlyer** [comment]
Closing for #3407
