### ISSUE TITLE
Param refresh should refresh param hash

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3422]
The refresh action doesn't seem to refresh params in all cases. This is either related to https://github.com/mavlink/qgroundcontrol/issues/3418 or an independent issue.

@DonLakeFlyer The way to validate is to have the MAVLink inspector open and validate that the PARAM_VALUE message comes in with the hash each time a param refresh is triggered.

We don't need to reload the whole list, hash is sufficient.

**Comment by DonLakeFlyer** [comment]
This is caused by 3418.
