### ISSUE TITLE
PX4 safety config shows MC after configured for FW

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3423]
Starting with a wiped pixhawk
 - flash PX4 stable through QGC over USB
 - auto connect over USB and then select a fixed wing configuration
 - pixhawk reboots, auto reconnects, and safety screen show MC icons and settings

 - if manually disconnect and reconnect it shows the proper FW safety settings

**Comment by DonLakeFlyer** [comment]
Cause by: https://github.com/PX4/Firmware/issues/4660
