### ISSUE TITLE
libdirectfb-1.2.so.9 is missing in AppImage

### ISSUE THREAD

**Issue by probonopd** [mavlink/qgroundcontrol#3424]
When trying the AppImage on Ubuntu 16.04, then I get

```
/tmp/.mount_r5K53X/qgroundcontrol: error while loading shared libraries: libdirectfb-1.2.so.9: cannot open shared object file: No such file or directory
```
and it does not launch. Possibly this could be remedied by copying `libdirectfb-1.2.so.9` into `./usr/lib` inside the AppImage at AppImage creation time.

**Comment by dagar** [comment]
This was auto closed by the commit. Can you test it @probonopd? I'm not on 16.04 yet.

**Comment by probonopd** [comment]
Happy to test, where can I download the build @dagar?

**Comment by dagar** [comment]
https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/builds/QGroundControl.AppImage

**Comment by probonopd** [comment]
On Ubuntu 16.04 LTS:
```
me@host:~$ Downloads/QGroundControl.AppImage 
/tmp/.mount_ZHI2uw/qgroundcontrol: error while loading shared libraries: libfusion-1.2.so.9: cannot open shared object file: No such file or directory
```

**Comment by dagar** [comment]
@probonopd how about this one?
https://s3-us-west-2.amazonaws.com/qgroundcontrol/appimage/QGroundControl.AppImage

**Comment by probonopd** [comment]
```
/tmp/.mount_K1E9qT/qgroundcontrol: error while loading shared libraries: libts-0.0.so.0: cannot open shared object file: No such file or directory
```

Did you know that you can test easily with [testappimage](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/testappimage)?

Like this: `sudo testappimage some-ubuntu-live.iso Your.AppImage`

**Comment by dagar** [comment]
Thanks @probonopd. You've got some cool scripts.

The fixed version will be on s3 shortly.
https://s3-us-west-2.amazonaws.com/qgroundcontrol/master/QGroundControl.AppImage

**Comment by probonopd** [comment]
Excellent, runs fine now.
