### ISSUE TITLE
Something wrong with COM_LOW_BAT_ACT

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3440]
Shows up in Safety Summary panel as well. Not sure if it's meta data or what.

![screen shot 2016-05-29 at 1 36 34 pm](https://cloud.githubusercontent.com/assets/5876851/15635907/7cc1d384-25a2-11e6-8df8-67a7d4d1abaf.png)

**Comment by DonLakeFlyer** [comment]
This was from a new flash.

**Comment by dogmaphobic** [comment]
Weird... That's a `FactComboBox` using `COM_LOW_BAT_ACT` as a source.

**Comment by dogmaphobic** [comment]
I can't reproduce this. Master QGC and master PX4:

![screen shot 2016-05-29 at 5 57 28 pm](https://cloud.githubusercontent.com/assets/749243/15636259/f90c4554-25c6-11e6-8b54-79b3d611133b.png)

See what your `PX4ParameterFactMetaData.xml` looks like.

**Comment by dogmaphobic** [comment]
Same thing in with the safety panel. @DonLakeFlyer, can you check your `PX4ParameterFactMetaData.xml` file?

![screen shot 2016-05-29 at 8 47 10 pm](https://cloud.githubusercontent.com/assets/749243/15637071/b314fe20-25de-11e6-9bee-8ced5aad1624.png)

**Comment by DonLakeFlyer** [comment]
All working now. Must have been some bad meta data that went through in the past.
