### ISSUE TITLE
Send to vehicle causes connection lost sometimes	

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3446]
Test Environment
QGroundControl: Daily Build: v2.9.7b-46-g4af5756
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the mission is able to send to vehicle 
Step:
1. Lanuch QGC
2. Connect to SITL
3. Set waypoints in mission page
4. Click "Send To Vehicle" 
Excepted result:
The mission is able to send to vehicle without error
Actual result:
Connection lost
![send mission causes commucation lost](https://cloud.githubusercontent.com/assets/1768868/15645530/95a1080e-268b-11e6-9465-17ba90b39dff.JPG)

**Comment by DonLakeFlyer** [comment]
My guess is at this point SITL has crashed. When this happens can you shut down QGC. Restart it and see if it connects. If it doesn't then SITL has crashed or hung.

**Comment by glody** [comment]
Yes, you are right. Restart QGC unable reconnect to SITL. It should be SITL issue. thanks.
