### ISSUE TITLE
Groud station failsafe doesn't work

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3448]
Test Environment
QGroundControl: Daily Build: v2.9.7b-46-g4af5756
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the failsafe able to work
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Set Ground Station failsafe to "Enabled always RTL"
4. Arm IRIS+ and takeoff in Stabilize mode
5. Disconnect to IRIS+ 
Excepted result:
Ground station failsafe should be triggered and flight mode should change to RTL 
Actual result:
Nothing happened

**Comment by DonLakeFlyer** [comment]
The Vehicle is responsible for this so this is a firmware issue
