### ISSUE TITLE
Battery failsafe doesn't work

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3450]
Test Environment
QGroundControl: Daily Build: v2.9.7b-46-g4af5756
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the failsafe able to work
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Set Battery failsafe to "Land"
4. Set voltage threshold acordingly
4. Let the voltage lower than setting value
Excepted result:
Battery failsafe should be triggered and flight mode should change to Land 
Actual result:
IRIS+ alarming while the voltage lower than setting value, but flight mode doesn't change to Land

**Comment by DonLakeFlyer** [comment]
What firmware is on the Vehicle? The actual handling of this is on the Vehicle so this is a firmware problem. Issue should go there.
