### ISSUE TITLE
Tile fetch error 

### ISSUE THREAD

**Issue by mmindia** [mavlink/qgroundcontrol#3451]
Test Environment
QGroundControl: Daily Build: v2.9.7b also observed on v2.9.4
OS: Ubuntu 14.04 32 Bit and 64 bit

Hi,
I get the following errors while using google satellite maps in qgroundcontrol. While zooming in and out of a region (even slowly) i see many tile fetch errors. I am facing the same problem for other regions too. 

Fetch tile error: "Error downloading http://khm2.google.com/kh/v=194&hl=en-US&x=11724&y=7595&z=14&s=Galileo - server replied: Not Found

I copied the link on to a web browser and google says "Error 404(not found)!!" In the url I changed v=194 to v=200 and I could view the tile.

So I changed 
_versionGoogleSatellite      = "200";
In  QGCMapUrlEngine.cpp and recompiled QGroundControl. I was able to view the tiles properly in QGroundControl. 

That was yesterday.

But today I am facing the same problem. I had to change v=200 to v=300 and rebuild the code. It works. But I am not sure for how long this would work. I ended up rebuilding the code.

I found this problem in QGC 2.9.4 upwards.

Versions 2.9.3 and before do not have this problem. I am able to view tiles of the same region in qgroundcontrol.

On Bing maps I do get "tile fetch errors" but I noticed that they are due to timeout. Given some time the tiles get downloaded. The errors when using Bing maps are far less compared to Google.
Fetch tile error: "Error downloading http://ecn.t0.tiles.virtualearth.net/tiles/a1312.jpeg?g=563&mkt=en-US - server replied: Request Time-out"

Here are the list of google map errors:

Fetch tile error: "Error downloading http://khm2.google.com/kh/v=200&hl=en-US&x=11724&y=7595&z=14&s=Galileo - server replied: Not Found"
Fetch tile error: "Error downloading http://khm0.google.com/kh/v=200&hl=en-US&x=11724&y=7596&z=14&s= - server replied: Not Found"
Fetch tile error: "Error downloading http://khm1.google.com/kh/v=200&hl=en-US&x=11721&y=7596&z=14&s=Galileo - server replied: Not Found"
Fetch tile error: "Error downloading http://khm0.google.com/kh/v=200&hl=en-US&x=11720&y=7596&z=14&s=Gali - server replied: Not Found"
Fetch tile error: "Error downloading http://khm0.google.com/kh/v=200&hl=en-US&x=11724&y=7594&z=14&s=Galile - server replied: Not Found"
Fetch tile error: "Error downloading http://khm2.google.com/kh/v=200&hl=en-US&x=11720&y=7597&z=14&s=Galil - server replied: Not Found"
Fetch tile error: "Error downloading http://khm1.google.com/kh/v=200&hl=en-US&x=11725&y=7594&z=14&s=G - server replied: Not Found"
Fetch tile error: "Error downloading http://khm1.google.com/kh/v=200&hl=en-US&x=11725&y=7596&z=14&s=Gal - server replied: Not Found"
Fetch tile error: "Error downloading http://khm3.google.com/kh/v=200&hl=en-US&x=11721&y=7597&z=14&s= - server replied: Not Found"
Fetch tile error: "Error downloading http://khm3.google.com/kh/v=200&hl=en-US&x=11725&y=7595&z=14&s=Ga - server replied: Not Found"

**Comment by dogmaphobic** [comment]
Fixed in #3492
