### ISSUE TITLE
Changing wifi channel 

### ISSUE THREAD

**Issue by andrejpan** [mavlink/qgroundcontrol#3453]
I am using QCG 2.9.7b. At wifi settings menu I can not change wifi channel.
![wifi_no_go](https://cloud.githubusercontent.com/assets/1015265/15669745/1a84173c-2722-11e6-9304-a23ffdf028f4.png)
At parameter menu I can change it with no problem
![wifi_go](https://cloud.githubusercontent.com/assets/1015265/15669767/4182c5c2-2722-11e6-8ac7-c3ac50fe3b61.png)

**Comment by dogmaphobic** [comment]
You must be running an old version of the ESP8266 Firmware. The UI prevents changing the channel if you have the unit setup in *Station Mode*. With that said, the UI should detect that and not just block you if you are running an old version.

The current version is 1.0.11 (you can check it on the summary page)

**Comment by dogmaphobic** [comment]
Done!
