### ISSUE TITLE
Param file github json download failed: % 1

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3465]
Test Environment
QGroundControl: Daily Build: v2.9.7b-125-gce7035b
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the common parameters about the ariframe you select is able to load
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Select "X Style, Y6A Style: Quad, Hexa, Qcto, X8, Tri, Y6A" in Airframe item Setting page
4. Click "Load common parameters" and select "3DR QUAD X4 RTF"
Excepted result:
The common parameters is able to load
Actual result:
Param file github json download failed: % 1
![failed to download params](https://cloud.githubusercontent.com/assets/1768868/15771664/edae854c-299e-11e6-9acd-0d499ba2c22d.JPG)

**Comment by NaterGator** [comment]
Is the issue you are reporting the broken argument in the error string or the fact that the JSON file download actually failed?

**Comment by DonLakeFlyer** [comment]
Both problems are bugs

**Comment by NaterGator** [comment]
There is another string bug [here](https://github.com/mavlink/qgroundcontrol/blob/0669604a14994bccde04f1dc96b4cdd870c0dd58/src/AutoPilotPlugins/APM/APMAirframeComponentController.cc#L247)

**Comment by DonLakeFlyer** [comment]
I can't repro the download failure with latest daily. I re-wrote this code last week which should have fixed a bunch of things up.

**Comment by DonLakeFlyer** [comment]
@glody Can you retry this with latest daily?

**Comment by glody** [comment]
Retry on daily build below:
Windows/OS X:v2.9.7b-221-gd3df08b
Linux:v2.9.7b-220-g13bf81a
Android:v2.9.7b-233-g91fd6ae

All platforms work well except Windows. I created another issue to track windows issue #3550

**Comment by DonLakeFlyer** [comment]
Should be fixed now
