### ISSUE TITLE
Help menu lost

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3466]
Test Environment
QGroundControl: Daily Build: v2.9.7b-125-gce7035b
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check title bar
Step:
1. Lanuch QGC
2. Check title bar
Excepted result:
The help menu should shows in title bar
Actual result:
Help menu lost from title bar
![help menu](https://cloud.githubusercontent.com/assets/1768868/15771709/29963974-299f-11e6-957a-d1b519b58b57.JPG)

**Comment by DonLakeFlyer** [comment]
Help menu was removed since it didn't link to anything.
