### ISSUE TITLE
Delete "Default Tile Set" causes all sets lost

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3467]
Test Environment
QGroundControl: Daily Build: v2.9.7b-125-gce7035b
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if offline maps work correctly
Step:
1. Lanuch QGC
2. Add some new sets in Offline Maps item preferences page
3. Click "Default Tile Set" and delete it
Excepted result:
Only default tile set deleted 
Actual result:
All sets deleted

**Comment by dogmaphobic** [comment]
What we need is a better label for this. *Default Tile Set* is too ambiguous. When you delete the "Default Tile Set", you are deleting every tile cached as it is the root of all tiles. The confirmation dialog tells you as much but it obviously is not good enough.

![screen shot 2016-06-03 at 12 28 37 pm](https://cloud.githubusercontent.com/assets/749243/15786803/9fabf620-298c-11e6-9568-f696956374c7.png)

**Comment by DonLakeFlyer** [comment]
I'd leave alone for 3.0 and figure out a rework for 3.1

**Comment by DonLakeFlyer** [comment]
Text is now: "This will delete all tiles INCLUDING the tile sets you have created yourself.\n\nIs this really what you want?".

I think that's good enough.
