### ISSUE TITLE
Unable to set default tile set

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3468]
Test Environment
QGroundControl: Daily Build: v2.9.7b-125-gce7035b
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if offline maps work correctly
Step:
1. Lanuch QGC
2. Add some new sets in Offline Maps item preferences page
3. Try to change another set as default
Excepted result:
Default tile set is able to change
Actual result:
No method to change default tile set

**Comment by DonLakeFlyer** [comment]
All tile sets are active all the time. There is no need to change the default tile set.
