### ISSUE TITLE
Arming check parameter does not save

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#3470]
No matter what ARMING_CHECK is set to, the value always remains 'Enabled'. Changing other parameters behaves as expected.

This appears to be an issue with qgc. Parameter changes are retained appropriately except for arming_check. This behavior is observed running Copter 3.3.3 (flashed via qgc). Tested on qgc version 2.8.0 and 2.9.7b.

Setting arming check via mavproxy works correctly.

**Comment by DonLakeFlyer** [comment]
@jaxxzer FYI for workaround. Setting arming check from Safety page works.
