### ISSUE TITLE
Comms loss with one vehicle locks out control of other vehicles which are still communicating

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#3471]
I have set up one pixhawk (sysid = 1, compid = 1) with two arduinos (2,1) and (3,1) connected to pixhawk uarts with configured with SERIAL_PROTOCOL = GCS Mavlink. The systems 2 and 3 are sending HEARTBEAT and SYS_STATUS messages at 1Hz, all picked up by qgc, and visible in mavlink inspector. The dropdown menu for vehicles acts as expected, showing different voltage levels reported by SYS_STATUS messages on each individual vehicle.

When vehicle 1 (pixhawk) is selected in the dropdown menu, and one of the arduinos is disconnected from the pixhawk, 'vehicle x communication lost' is reported by audio appropriately, and all of the tabs for settings on pixhawk continue to function. If vehicle y (still connected) arduino is selected from the dropdown list, everything works fine as before. If vehicle x (disconnected) arduino is selected from the dropdown, all of the view tabs disappear, and the disconnect button appears.

At this point, clicking 'Disconnect' does not appear to do anything. Then, after clicking x button to exit application, the message window pops up stating that there are still active connections to vehicles and asks to close them.

In the same manner, if vehicle 3 is selected, and vehicle 3 is disconnected from the pixhawk, the other vehicles 1 and 2 which are still communicating cannot be accessed.

**Comment by DonLakeFlyer** [comment]
The single link with multiple vehicles on it communication lost path is quite busted. This is going to have to wait until 3.1.
