### ISSUE TITLE
Cannot arm when running SITL with virtual joystick

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#3480]
If I run SITL (using iOS) with the virtual joystick enabled, I cannot arm. When I try to arm (using the button/slide to arm at the bottom of the screen), it complains the throttle is not zero.

![screen shot 2016-06-05 at 2 49 02 pm](https://cloud.githubusercontent.com/assets/749243/15807454/b50ceb86-2b2c-11e6-8270-ac42f8e87f33.png)

**Comment by dagar** [comment]
I think this makes sense. Going straight into manual mode at 50% throttle would be bad. Can you set the throttle mode to be 0 at center or go into altitude control mode before arming?

**Comment by DonLakeFlyer** [comment]
Fixed
