### ISSUE TITLE
What do we do with tiny screens?

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#3483]
As is, all but the Fly View is pretty much not usable on very small screens. At least on iOS, there is no way to limit beyond iPhone/iPad. If you say you support iPhone, you are required to support everything starting with the iPhone 4s.

Plan View (with home set some 9,367km away):

![simulator screen shot jun 5 2016 5 59 59 pm](https://cloud.githubusercontent.com/assets/749243/15808545/b9cf02ce-2b47-11e6-9860-91a7cd1cc28e.png)

Radio setup:

![simulator screen shot jun 5 2016 6 02 20 pm](https://cloud.githubusercontent.com/assets/749243/15808546/c8c708a8-2b47-11e6-8e27-0ad5c50d9b64.png)

Some screens, especially under settings allow flicking left and right but it makes for a very awkward user experience.

**Comment by dogmaphobic** [comment]
iPhone 6 everything is quite fine:

![simulator screen shot jun 5 2016 6 10 52 pm](https://cloud.githubusercontent.com/assets/749243/15808590/e68668a6-2b48-11e6-8a28-60bf202c13c5.png)

![simulator screen shot jun 5 2016 6 11 31 pm](https://cloud.githubusercontent.com/assets/749243/15808594/f508ab50-2b48-11e6-93ef-3db733ffbb7e.png)

**Comment by DonLakeFlyer** [comment]
From the 4S emulator:

![screen shot 2016-06-05 at 3 20 39 pm](https://cloud.githubusercontent.com/assets/5876851/15808630/1d27fd10-2b31-11e6-85cc-a868ffecae69.png)

![screen shot 2016-06-05 at 3 21 13 pm](https://cloud.githubusercontent.com/assets/5876851/15808633/2b581c94-2b31-11e6-9077-fd66e36e4a4f.png)

![screen shot 2016-06-05 at 3 21 41 pm](https://cloud.githubusercontent.com/assets/5876851/15808638/3e5f0fa0-2b31-11e6-94bc-d9f48d199b27.png)
Can't to be able to scroll horizontally

![screen shot 2016-06-05 at 3 22 16 pm](https://cloud.githubusercontent.com/assets/5876851/15808639/540ba6ba-2b31-11e6-9ee1-10556bb481c6.png)

![screen shot 2016-06-05 at 3 22 52 pm](https://cloud.githubusercontent.com/assets/5876851/15808643/67a6f198-2b31-11e6-90d0-d090fa0a644c.png)

**Comment by dogmaphobic** [comment]
Screen density for the 4s is very different (in addition to the narrower width). If you switch the base font size to 9 points (instead of the default 11), things fit fine. I don't have an actual iPhone 4s to test how usable that is though:

![simulator screen shot jun 5 2016 7 54 27 pm](https://cloud.githubusercontent.com/assets/749243/15809135/993d6964-2b57-11e6-9759-5a658c97d2bc.png)


![simulator screen shot jun 5 2016 7 57 50 pm](https://cloud.githubusercontent.com/assets/749243/15809145/d05ebec0-2b57-11e6-9d41-068b21196583.png)

**Comment by DonLakeFlyer** [comment]
All I can say is that on a real iPhone 5 the default font is pretty small. Slightly smaller than the standard system font.

**Comment by dogmaphobic** [comment]
Should we close this now?

**Comment by DonLakeFlyer** [comment]
I'll close it when I'm done running through everything. PX4 stack is almost done. Now I need to go through ArduPilot setup.
