### ISSUE TITLE
Mission command list doesn't appear to be a QGCFlickable

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3489]
Doesn't show disappearing scroll bar thingy:
![screen shot 2016-06-05 at 9 33 40 pm](https://cloud.githubusercontent.com/assets/5876851/15812059/415835c2-2b65-11e6-92b9-8d8830d77640.png)

**Comment by DonLakeFlyer** [comment]
It's a ListView so scrolling will work. But in reality a QGCFlickable would be better since you get scroll indicators.

**Comment by NaterGator** [comment]
ListViews are descendants of flickables; you could just create QGCListView which applies the same properties as QGCFlickable but retains the view architecture goodness of ListView.

**Comment by DonLakeFlyer** [comment]
Yeah I was trying to do it cheaply. I'll make a QGCListView sometime in 3.1
