### ISSUE TITLE
"CONNECTION LOST" after several seconds in PX4 SITL mode

### ISSUE THREAD

**Issue by nrodichenko** [mavlink/qgroundcontrol#3507]
Only manifests with QT 5.5.0, but works well after updating to 5.5.1. This is a known bug in QT 5.5.0 (https://bugreports.qt.io/browse/QTBUG-46552), but QGC stil allows for this older version. Such problems were already discussed previously in https://github.com/mavlink/qgroundcontrol/issues/3159#issuecomment-206659421

As a fix QGC could require at least QT 5.5.1 to build - to save time for new SITL developers.

Tested on QGC master, commit 7b8f0a14685d223837f03d398d65b3d1a4427c72

**Comment by DonLakeFlyer** [comment]
QGC requires Qt 5.5.1 as stated in the README. The build system does not enforce a specific Qt version itself.
