### ISSUE TITLE
The map unable to zoom in/out while downloading offline map

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3551]
Test Environment
QGroundControl: Windows:v2.9.7b-221-gd3df08b
Linux:v2.9.7b-220-g13bf81a
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
Purpose:
Check if the offline map is able to download
Step:
1. Lanuch QGC
2. Click "Add New Set" in Offline Maps item, Preference page
3. Try to drag Min Zoom/Max Zoom
Excepted result:
The sliders are able to drag
Actual result:
The Sliders unable to drag on Windows and Linux, it works well on OS X and Android
![unable zoom in or zoom out the map while downloading offline map](https://cloud.githubusercontent.com/assets/1768868/15996016/976770b8-3155-11e6-8ecd-e9479bc14790.JPG)

**Comment by DonLakeFlyer** [comment]
Dup of #3548
