### ISSUE TITLE
Scale unit doesn't change while changing distance units

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3552]
Test Environment
QGroundControl: Windows/OS X:v2.9.7b-221-gd3df08b
Linux:v2.9.7b-220-g13bf81a
Android:v2.9.7b-233-g91fd6ae
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the scale unit changes following the distance units changes
Step:
1. Launch QGC
2. Change Distance units to 'Feet' in General item, preferences page
3. Re-launch QGC
4. Check the scale unit in mission page or flight page
Excepted result:
The scale unit changes to 'ft' at the same time
Actual result:
The scale unit is still 'm'
![scale unit unable to change](https://cloud.githubusercontent.com/assets/1768868/15996027/bcd5b59e-3155-11e6-8169-1402d32be6e1.JPG)

**Comment by DonLakeFlyer** [comment]
Dup of #3514
