### ISSUE TITLE
Only half characters shows on dashboard in flight page on Android

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3553]
Test Environment
QGroundControl: Android:v2.9.7b-233-g91fd6ae
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the dashboard shows correctly
Step:
1. Launch QGC
2. Connect to IRIS+
3. Check the display on dashboard in flight page
Excepted result:
All characters are shown correctly and completely
Actual result:
Only half shows about bottom characters. please check the snapshot for details.
![screenshot_2016-06-12-19-26-42](https://cloud.githubusercontent.com/assets/1768868/15996041/ed8e76bc-3155-11e6-8ffc-26f9fce807bb.png)

**Comment by DonLakeFlyer** [comment]
@glody An additional piece of information is what firmware you are using. ArduPilot or PX4. Are you mainly testing on ArduPilot or both?

**Comment by glody** [comment]
@DonLakeFlyer I mainly test ArduPilot. Just use PX4 as reference.

**Comment by DonLakeFlyer** [comment]
@glody Have you modified the value list for the first page on the instrument panel? Could you show me what that looks like?

**Comment by glody** [comment]
Sorry for slow response. Please check the snapshot below.
![screenshot_2016-07-25-19-27-07](https://cloud.githubusercontent.com/assets/1768868/17126803/00726a00-5333-11e6-86d6-4b5a4b0bc6ca.png)
![screenshot_2016-07-25-19-27-13](https://cloud.githubusercontent.com/assets/1768868/17126804/00b829be-5333-11e6-8c95-846187663824.png)

**Comment by DonLakeFlyer** [comment]
This was reworked. I think it's fixed now
