### ISSUE TITLE
ESC calibration with ArduPilot

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#3561]
Currently there's no way to perform a ESC calibration with ArduPilot (there's a way to do it with PX4)

The process is simple:

Set this parameter ESC_CALIBRATION to an appropriate value (would suggest 1)

http://ardupilot.org/copter/docs/parameters.html?highlight=parameters#esc-calibration-esc-calibration

Power off system

Set Throttle high on RC radio

Power ON system

Press the safety switch to enable PWM sent to ESC's

Wait for ESC's tones

Set throttle low on the RC Radio

Wait for confirmation tones from the ESC's

Power off system.

Process complete.

**Comment by DonLakeFlyer** [comment]
There isn' really any firmware support for this in ArduPilot. It's all a manual process. In PX4 there is an ESC Cal firmware code which QGC communicates with to move from one step to another. Other than putting this param somewhere in Power say and then showing the user the instructions there isn't much QGC can do with respect to hand holding.
