### ISSUE TITLE
GPS Lock for two vehicles not working correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3569]
Okay So I have two drones and they are connected to the same QGC. Drone one is called Vehivle #1 and and drone 2 is called Vehicle #2. What I did is I connected both of them to the same QGC and on my MAVLink inspector in widgets I can see the mavlink messages of Vehicle #1 and Vehicle #2 which means that the yare connected to QGC. Next is if the GPS data of both the Vehicles in communicated to the QGC via mavlink or not ? So I observed that inside my mavlink inspector I can see GPS data of both the vehicles. Problem I am having is I can onlu see gps lock of one vehicle like it shows 8 satellites. But when I go to the flight view of vehicle #2 on the same QGC I can not see any gps lock. It says no GPS lock even though the mavlink messages are being communicated successfully from the Vehicle to the QGC.

**Comment by DonLakeFlyer** [comment]
@musclesinwood I moved your issue here so we don't lose it

**Comment by DonLakeFlyer** [comment]
I tried to repro this and it all worked correctlyf or two vehicles. Can you double check you message traffic? if it all still looks good. Save a telemetry log me for the session and attach.

Removing milestone until I can get a repro.

**Comment by musclesinwood** [comment]
Dear Don,
Thank You. Appreciate it. You meant check my Mavlink inspector ?

**Comment by DonLakeFlyer** [comment]
Just using mavlink inspector you won't be able to tell if a 3d fix is coming across from both Vehicles. So that's not a valid suggestion. I'll need a telemetry log to go any further with determining what is going on.

**Comment by musclesinwood** [comment]
Al right. So,you need the telemetry log of both of the Vehicles ( Vehicle 1 & Vehicle 2 )? And where can I find the log file ? Is it on the QGC ? Can you please point me to the right place where those log fiels are located ?

**Comment by DonLakeFlyer** [comment]
QGC should prompt you to save a log file when you disconnect the last vehicle.

**Comment by DonLakeFlyer** [comment]
If it doesn't turn on "Prompt to save Flight Log data after each flight" in settings

**Comment by DonLakeFlyer** [comment]
Re-open of there are log files to reproduce
