### ISSUE TITLE
Feature request: INAV compatibility (and Cleanflight) after MAVLink is merged

### ISSUE THREAD

**Issue by skaman82** [mavlink/qgroundcontrol#3573]
There is currently no solution for GCS and mission planing for OSX for the INAV firmware (Cleanflight branch). MAVLink will be soon included and it would be awesome if qgroundcontrol could support mission monitoring and mission planing.

See: https://github.com/iNavFlight/inav/pull/186

**Comment by DonLakeFlyer** [comment]
QGC already works with any Vehicle which supports MAVLink.

**Comment by skaman82** [comment]
Good to know, thank you

**Comment by DonLakeFlyer** [comment]
I you use it and run into problems let us know.
