### ISSUE TITLE
Confusing compass calibration

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3575]
I calibrated my compass on today's build and when it's finished the right side of the screen has the header set compass rotation and the drop down below it is the autopilot rotation not the compass.

**Comment by DonLakeFlyer** [comment]
Which firmware?

**Comment by jcooper21** [comment]
Current beta

**Comment by DonLakeFlyer** [comment]
PX4 or ArduPilot?

**Comment by jcooper21** [comment]
Px4

**Comment by DonLakeFlyer** [comment]
ArdiPilot has same problem

**Comment by DonLakeFlyer** [comment]
ArduPilot is fine. You set orientations before you calibrate.
