### ISSUE TITLE
Migrate to Qt 5.7

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3581]
This also includes support for Qt Charts via GPL3... huzzah!

http://blog.qt.io/blog/2016/06/16/qt-5-7-released/

**Comment by dagar** [comment]
I'm going to try a minimal docker image for Linux and Android builds.

**Comment by pritamghanghas** [comment]
possibly only thing blocking this update is being fixed here. Hopefully this will make it to 5.7 release.

**Comment by NaterGator** [comment]
5.7.0 is already out the door. :grimacing:  Based on Qt's previous releases 5.7.1 will be timed about 3 months from now.

**Comment by pritamghanghas** [comment]
I wasn't aware that is unfortunate.

On Tue, Jun 21, 2016 at 7:36 PM, Nate Weibley <notifications@github.com>
wrote:

> 5.7.0 is already out the door. 😬 Based on Qt's previous releases 5.7.1
> will be timed about 3 months from now.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/3581#issuecomment-227450433>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGm5V36rpYUI0anJS9Krv16ttPnOWSRUks5qN-_mgaJpZM4I3esy>
> .
>



-- 
Regards,
pritam

**Comment by pritamghanghas** [comment]
This has been fixed and will be cherry picked for 5.7.1. If someone is working on charts and can't wait. Just pick this one https://codereview.qt-project.org/#/c/161978/ and build 5.7 locally and good to go.

**Comment by DonLakeFlyer** [comment]
Good news. We can move to 5.7 before we toss analyze

**Comment by DonLakeFlyer** [comment]
We are going to move to 5.6.2 instead since it's an LTS version.

**Comment by DonLakeFlyer** [comment]
This is all done now
