### ISSUE TITLE
wget Qt5.5.1 dependency returns error 403

### ISSUE THREAD

**Issue by lutherling12** [mavlink/qgroundcontrol#3586]
Upon provisioning 'dev', an error is returned stating that Qt5.5.1-linux.tar.bz2 doesn't exist.

After looking in the Vagrant file, line 31 seems to perform wget to retrieve this dependency:
su - vagrant -c 'wget --continue -q %{deps_url}/%{qt_deps_tarball}'

Checking the variables in .vagrantconfig.yml, the two parts of the url are:
'deps_url': 'https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies'
'qt_deps_tarball': '/vagrant/Qt5.5.1-linux.tar.bz2'

If I perform the wget on my host machine with the expanded url, it returns a 403 Forbidden error. Is anyone else having this issue? Is there anything that can be done about it?

**Comment by dagar** [comment]
As far as I know none of the regular developers or build system use vagrant so it's not surprising that it broke.
The correct URL is: https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.5.1-linux.tar.bz2

Could you fix the vagrant config, verify it actually works, and submit a pull request?

**Comment by lutherling12** [comment]
I don't mind, but I'm not sure where to find this Qt5.5.1-linux.tar.bz2 file that's bundled with qGroundControl. Is there anything special about it that's different from the official Qt5.5.1 release?

**Comment by lutherling12** [comment]
I'll get right on it. Thank you.

**Comment by dagar** [comment]
We've been hosting our own Qt because so far it's been quite a pain to automate the install. I'd like to stop doing it if possible.

**Comment by lutherling12** [comment]
readme states that it **must** be Qt5.5.1. Is this because the official installer is a pain to automate and makes it hard to install the latest version? If not, and the dependency is strictly for that version, why not host a box that already has Qt5.5.1 on Atlas?

**Comment by dagar** [comment]
There are a few issues. Typically we see little bugs between different versions of Qt and just don't have the resources to test and maintain compatibility with multiple versions.

For testing we use the free/open source tier of travis-ci which needs to install the build dependencies every single build.

What's Atlas?

**Comment by lutherling12** [comment]
Atlas is the platform Hashicorp uses to host vagrant boxes.
atlas.hashicorp.com

**Comment by DonLakeFlyer** [comment]
@dagar Is this fixed now?

**Comment by dagar** [comment]
I haven't personally tested it, but #3598 should have fixed it.
