### ISSUE TITLE
Plane: Takeoff item on ArduPilot is out of whack

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3588]

**Comment by DonLakeFlyer** [comment]
This issue is different. It ths actual positioning of the item. Not the abbreviation. It may have been a home position problem though. Still looking.

**Comment by NaterGator** [comment]
@DonLakeFlyer the offline data for ardupilot is definitely incorrectly loading the data for MAV_CMD_NAV_TAKEOFF:

![image](https://cloud.githubusercontent.com/assets/2575/16160339/879a8948-3495-11e6-99e1-f7a57e9d7294.png)

Note that _specifiesCoordinate is false.

**Comment by NaterGator** [comment]
Here ya go: 
https://github.com/mavlink/qgroundcontrol/blame/fdb13156c0caa95a587775f9c60e4173e13b7a27/src/FirmwarePlugin/APM/MavCmdInfoCommon.json#L10

**Comment by DonLakeFlyer** [comment]
ArduPilot doesn't support coordinate for takeoff. This was just a an issue with a bad planned home position which took the takeoff item along with it. Not really a bug. User error

**Comment by NaterGator** [comment]
The mission controller [does this](https://github.com/mavlink/qgroundcontrol/blob/fdb13156c0caa95a587775f9c60e4173e13b7a27/src/MissionManager/MissionController.cc#L171) automagically when planning the 2nd point in a mission. If it is desired behavior that is fine, just FYI.

**Comment by DonLakeFlyer** [comment]
The assumption is that most missions start from the ground. Hence first thing you want is takeoff. If it's annoying people it can be removed.
