### ISSUE TITLE
No method to exit from "Replay Flight Data" mode

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3600]
Test Environment
QGroundControl: Daily Build:v2.9.7b-282-g033f52b
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if user is able to exit from "Replay Flight Data" mode
Step:
1. Download tlog from here http://autotest.ardupilot.org/ArduCopter-test.tlog
2. Click "Replay Flight Data" on status bar
3. Select the tlog file to replay.
4. Try to exit replay mode
Excepted result:
Here should have a button to exit replay mode.
Actual result:
No way to exit replay mode except re-launch QGC

**Comment by DonLakeFlyer** [comment]
The user model is horrible, but here is how you do it:
- Pause the replay
- You should get a communication lost, then click disconnect

This is all going to get reworked in 3.1 so I'm not putting much effort in here excepty for something that is completely broken.
