### ISSUE TITLE
Add compassmot support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3608]

**Comment by DonLakeFlyer** [comment]
http://ardupilot.org/copter/docs/common-compass-setup-advanced.html

**Comment by davidbitton** [comment]
Is there a terminal mode in QGC where I could just call the command?

**Comment by DonLakeFlyer** [comment]
@davidbitton I should have compassmot support done by tomorrow. When I put that in, would you be able to test it?

<img width="1011" alt="screen shot 2016-06-23 at 8 05 11 pm" src="https://cloud.githubusercontent.com/assets/5876851/16326714/e6d2d040-397d-11e6-8a1e-e9f17816c16c.png">
<img width="1014" alt="screen shot 2016-06-23 at 8 05 20 pm" src="https://cloud.githubusercontent.com/assets/5876851/16326715/e6f1c9dc-397d-11e6-83dc-f694d4bde3c0.png">
<img width="1014" alt="screen shot 2016-06-23 at 8 05 28 pm" src="https://cloud.githubusercontent.com/assets/5876851/16326716/e6f1d22e-397d-11e6-8108-5880fcda9192.png">

**Comment by davidbitton** [comment]
Sure.

On Thu, Jun 23, 2016 at 11:06 PM Don Gagne <notifications@github.com> wrote:

> @davidbitton <https://github.com/davidbitton> I should have compassmot
> support done by tomorrow. When I put that in, would you be able to test it?
>
> [image: screen shot 2016-06-23 at 8 05 11 pm]
> <https://cloud.githubusercontent.com/assets/5876851/16326714/e6d2d040-397d-11e6-8a1e-e9f17816c16c.png>
> [image: screen shot 2016-06-23 at 8 05 20 pm]
> <https://cloud.githubusercontent.com/assets/5876851/16326715/e6f1c9dc-397d-11e6-83dc-f694d4bde3c0.png>
> [image: screen shot 2016-06-23 at 8 05 28 pm]
> <https://cloud.githubusercontent.com/assets/5876851/16326716/e6f1d22e-397d-11e6-8108-5880fcda9192.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/3608#issuecomment-228247343>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQ61wtdaNkNS7CX0Ndm1w_TWSfbZ3J9ks5qO0m3gaJpZM4I6_Wm>
> .
>
-- 
David B. Bitton
Code No Evil, LLC
Code Made Fresh Daily

**Comment by DonLakeFlyer** [comment]
@davidbitton Latest QGC daily has this in now. Can you give it a try?

**Comment by davidbitton** [comment]
will do. i'm having an issue with calibrating my FVT 30A BLHeli ESCs.
Basically they won't. Baby steps.

On Sat, Jun 25, 2016 at 1:31 PM Don Gagne <notifications@github.com> wrote:

> @davidbitton <https://github.com/davidbitton> Latest QGC daily has this
> in now. Can you give it a try?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/3608#issuecomment-228560856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQ6151saXAFSR4FVUvuUiKeuUtkE-9Kks5qPWXVgaJpZM4I6_Wm>
> .
>
-- 
David B. Bitton
Code No Evil, LLC
Code Made Fresh Daily

**Comment by davidbitton** [comment]
I keep getting "Check compass" and "Calibration command temporarily rejected". Could this be because I have only the external compass enabled? I cannot enable the internal or I receive inconsistent compasses.

**Comment by DonLakeFlyer** [comment]
Possibly because compass mot is mostly used for internal compass. You'd have to ask the ardupilot firmware folks. Is this on a PixRacer? I haven't ever been able to get all compasses set up with ArduPilot. PX4 stack is happy with them though.

**Comment by davidbitton** [comment]
Yes, it is in fact a PixRacer.

**Comment by DonLakeFlyer** [comment]
I've never quite been able to get my PixRacer to be fully happy with ArduCopter. I fight with it every once in a while but then just don't have enough time to fight any more. Then I give up and go back to PX4 stack on it. And move back to my Iris for ArduCopter testing.

**Comment by davidbitton** [comment]
are you compiling PX4 master?

On Sun, Jun 26, 2016 at 9:09 PM Don Gagne <notifications@github.com> wrote:

> I've never quite been able to get my PixRacer to be fully happy with
> ArduCopter. I fight with it every once in a while but then just don't have
> enough time to fight any more. Then I give up and go back to PX4 stack on
> it. And move back to my Iris for ArduCopter testing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/3608#issuecomment-228635303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQ614zS4eH5jVthi8b0FWrg_QSHkll-ks5qPyK2gaJpZM4I6_Wm>
> .
>
-- 
David B. Bitton
Code No Evil, LLC
Code Made Fresh Daily

**Comment by DonLakeFlyer** [comment]
I normally use master when I'm test flying. Most of the time flashed with QGC. Sometime I'll build my own and flash from command line.

**Comment by DonLakeFlyer** [comment]
Working now
