### ISSUE TITLE
AppImage 2.9.7b does not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by sgstreet** [mavlink/qgroundcontrol#3615]
See issue #3424 for details.  The problem was fixed on master in pull request  #3531 by @dagar .  

To allow users to use the current stable release, these fixes should be back ported to the 2.9.x stable releases. A new branch from tag v2.9.7b could be created for the 2.9.x stable releases to allow hot-fixes.  A hot-fix pull request could be merged and a tagged 2.9.8 release cut.

**Comment by sgstreet** [comment]
See pull request #3616

**Comment by DonLakeFlyer** [comment]
@dagar We are very close to releasing 3.0. Not sure it's worth the effort to do another 2.9 release.

**Comment by dagar** [comment]
That's what I was thinking.
Can you use a daily for now @sgstreet <https://github.com/sgstreet>?

http://qgroundcontrol.s3.amazonaws.com/builds/master/QGroundControl.AppImage

DonLakeFlyer Can we get the appimage link on the site?

**Comment by sgstreet** [comment]
No worries! I tested the matching pull request on a local build which I can use until the 3.0 release.  

But.... and being a newbie to the community, IMHO QGroundControl should adopt a GIT branching strategy which allows hot-fixes on a stable branch and automates the release process.  Gitflow, GitHub Flow or master/beta/stable anyone?

**Comment by dagar** [comment]
Yes that could make sense. So far there just haven't been many situations where we wanted to backport fixes. The vast majority of the development is currently done by 1-2 so things have been kept pretty simple.
I like the simple master/beta/stable (same as PX4/Firmware), but I might have to rethink using git describe for versioning development builds.
