### ISSUE TITLE
Camera controls plumbing in flight view

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3627]
@DonLakeFlyer @dogmaphobic It would be great to have a camera controls panel in the flight view which includes a photo and a video button plus a cogwheel for settings. You can make it experimental like survey initially if you like to.

I'm currently playing with a Sony QX1 for triggering and would need that to get started.

**Comment by DonLakeFlyer** [comment]
Going to have to wait until 3.1. Full up getting 3.0 out the door.

**Comment by DonLakeFlyer** [comment]
Until then you should be able to create a custom command widget for ui

**Comment by DonLakeFlyer** [comment]
Photo trigger is there now. But not video

**Comment by DonLakeFlyer** [comment]
I think Gus has this in now.
