### ISSUE TITLE
Spektrum bind function doesn't work

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#3634]
Setting parameter RC_DSM_BIND to 0 at the NSH console trigger a bind operation, but using the button on the Radio Calibration panel has no effect.

**Comment by DonLakeFlyer** [comment]
What firmware version. I just did this a few days ago without problems.

**Comment by kd0aij** [comment]
2.9.7b
Which mode did you select? I note that QGC offers only 2 modes, while the
firmware supports 3.

**Comment by DonLakeFlyer** [comment]
I meant firmware version. I'm binding DSMX 8 channels or more. What mode is missing?

**Comment by DonLakeFlyer** [comment]
Tested with QGC daily. Firmware bug:
- Flash PX4 master, doesn't work
- Flash ArduPilot Copter 3,3, works

QGC really has little involvement here other than to send a command to the vehicle.

**Comment by kd0aij** [comment]
So is this a regression on PX4 master? If so, what was the last version that was tested?
Parameter RC_DSM_BIND can take values 0,1,2
PR https://github.com/PX4/Firmware/pull/4891 would reduce that to a single (universal) choice.

**Comment by kd0aij** [comment]
@DonLakeFlyer Is QGC issuing an NSH shell command (like "px4io bind ..." to trigger the bind?
fmu-v4 isn't running the px4io module, so that would explain why it doesn't work on Pixracer.
Which hardware did you test on?

**Comment by kd0aij** [comment]
@LorenzMeier Is this function the only one that differs between fmu-v2 and v4? 
Both v2 and v4 need to use the same method to trigger binding, and since there's no px4io app running on v4, that should probably be the one-shot parameter change method.

**Comment by LorenzMeier** [comment]
The proper approach would be the command. The parameter change is extremely hacky and should go. Parameters have not been designed to be abused to handle actions :)

**Comment by kd0aij** [comment]
OK, I'm not sure where that method came from, but it's also recently been suggested for the WIFI reset function. Should the same command work for v2 and v4 binding? and should it move out of px4io?

**Comment by DonLakeFlyer** [comment]
QGC uses MAV_CMD_START_RX_PAIR. I tested on a regular Pixhawk and it didn't work.

**Comment by kd0aij** [comment]
https://github.com/PX4/Firmware/issues/4901
Works for me on Pixhawk (fmu-v2)
