### ISSUE TITLE
iOS: QGC icon corner bevel is stronger than Apple's, leading to a black artifact

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3639]
We should make our icon either with the right radius or completely square and let Apple crop it.

**Comment by dogmaphobic** [comment]
I fixed this in #3512, which was a couple of weeks ago. Where are you seeing this?

**Comment by LorenzMeier** [comment]
I had an old copy on the device, fixed, thanks.
