### ISSUE TITLE
Flight modes setup not available if no airspeed sensor

### ISSUE THREAD

**Issue by noah95** [mavlink/qgroundcontrol#3669]
Flight modes setup is not available if no airspeed sensor is connected and circuit breaker is set to ignore airspeed sensor

**Comment by DonLakeFlyer** [comment]
Are you running a Daily Build? If not, try that. This was changed somewhat recently. Looking at the current code, it's not quite right and might need a QGC reboot if you turn on the circuit breaker.

**Comment by DonLakeFlyer** [comment]
If latest Daily Build doesn't work for you this pull #3672 should fix it.
