### ISSUE TITLE
No Channel Option for Channel 6

### ISSUE THREAD

**Issue by Rudi3** [mavlink/qgroundcontrol#3671]
[**APM Filght Stack**!!]

In the current stable release I cant choose a channel option(In flight modes) for channel 6. It could be intentional for some reason, im not sure, but I'm missing it as I'm losing a flight mode switch. (But its there for gimbal control). And it really looks like there is something missing: 5, ?, 7, 8, 9,...

![bildschirmfoto vom 2016-06-27 01-23-43](https://cloud.githubusercontent.com/assets/5439317/16365612/e45f48f4-3c05-11e6-921c-0d5e9a2f525d.png)

**Comment by DonLakeFlyer** [comment]
There is no such thing as a channel 6 option. It's reserved for gimbal I think.

**Comment by Rudi3** [comment]
http://ardupilot.org/copter/docs/ac_rollpitchtuning.html Actually there is a channel 6 option and why should you reserve a channel for gimbal? You can freely pick the gimbal channels.

**Comment by DonLakeFlyer** [comment]
QGC doesn't support channel 6 tuning yet. We'll add it as some point.

**Comment by Rudi3** [comment]
Oh ok nice :smile:

**Comment by DonLakeFlyer** [comment]
#3675
