### ISSUE TITLE
ArduPilot Parameters Descriptions and Values not being used 

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#3677]
When editing values on full parameter list the right dialog is not being populated with the Description and Default Values and Reboot required 

example

<img width="784" alt="screen shot 2016-06-28 at 05 21 10" src="https://cloud.githubusercontent.com/assets/3130363/16403737/2e5d97e0-3cf0-11e6-8069-7072a9f99f13.png">
  

  // @Param: PWM_COUNT
    // @DisplayName: Auxiliary pin config
    // @Description: Control assigning of FMU pins to PWM output, timer capture and GPIO. All unassigned pins can be used for GPIO
    // @Values: 0:No PWMs,2:Two PWMs,4:Four PWMs,6:Six PWMs,7:Three PWMs and One Capture
    // @RebootRequired: True

**Comment by DonLakeFlyer** [comment]
Need to know what firmware type Copter/Plane and what version 3.3/3.4/etc?

**Comment by DonLakeFlyer** [comment]
Also ArduPilot does not have default value support.

**Comment by lvale** [comment]
@DonLakeFlyer I believe this is across all variants, The example above is taken from Copter 3.4RC1 but it's not relevant, because other params have similar behavior.

**Comment by DonLakeFlyer** [comment]
Amazing that the long description has been busted forever!

**Comment by lvale** [comment]
Mea culpa, mea culpa....It's a matter of looking and not seeing ;)
