### ISSUE TITLE
Android instrument panel freezing

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3696]
On android 6 on a nexus 6 the instrument panel freezes after about 10 minutes of flight and app had to be restarted and the 915 MHz telemetry disconnected and reconnected.

**Comment by DonLakeFlyer** [comment]
Were you running a mission?

**Comment by jcooper21** [comment]
I was flying in altitude control mode and stabalize but used auto take off.

**Comment by DonLakeFlyer** [comment]
Ok, thanks.

**Comment by DonLakeFlyer** [comment]
Likely related to #3698

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you know how an ANR is reported by the user. Do they get prompted to send info up to developer. There are no ANRs reported at all against QGC Android builds.

**Comment by dogmaphobic** [comment]
I had to Google it to find out what an ANR was, let alone knowing what it does :)

Based on this:

https://developer.android.com/training/articles/perf-anr.html

It seems it simply asks the user if they want to shut down the app.

**Comment by DonLakeFlyer** [comment]
@jcooper21 Did you get a dialog that asked you about reporting the hang? If you do make sure the send it up. Then I can get a stack trace from your device.

**Comment by DonLakeFlyer** [comment]
Can you also try latest Daily Build. Map flight trails were chewing memory. That should be fixed now. If we're lucky this may fix your problem.

**Comment by jcooper21** [comment]
I won't be able to test for a couple weeks I'm on vacation in Mexico.

**Comment by DonLakeFlyer** [comment]
I ran Android against SITL on a looping mission for over an hour without seeing a hang or any memory leaking.

**Comment by DonLakeFlyer** [comment]
@jcooper21 Are you still seeing this?

**Comment by jcooper21** [comment]
I have not seen it lately.
