### ISSUE TITLE
Joystick Setup Issues

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#3719]
Joystick setup layout needs some work:
You can no longer flick the screen, therefore I'm not able to reach all the buttons.
Button monitor boxes end at 15 and does not show all buttons. Layout is a bit all bunched up too making boxes with more than one digit too small for the text it holds.

![screen shot 2016-07-01 at 9 31 46 pm](https://cloud.githubusercontent.com/assets/749243/16537560/c6f7fb86-3fd3-11e6-9c7c-d7c1088ba053.png)

**Comment by DonLakeFlyer** [comment]
Of course Gus has a joystick with 72 buttons on it!

**Comment by dogmaphobic** [comment]
It's a flight simulator "Joystick". As is, it provides 38 buttons and 6 axis. I didn't plug in the rudder pedals, which would make it even worse 8P

**Comment by DonLakeFlyer** [comment]
I fixed this a while back. All setup pages are now in a QGCFlickable and the button monitor is a Flow.
