### ISSUE TITLE
Power config does not get flagged red if not set up correctly.

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3720]
@DonLakeFlyer The summary screen shows an issue, but the sidebar doesn't get flagged red.

To reproduce, set ```param set BAT_N_CELLS 0``` in SITL (it will be reset to 3 on reboot, so set it before connecting QGC).

<img width="1120" alt="screen shot 2016-07-02 at 12 39 20" src="https://cloud.githubusercontent.com/assets/1208119/16539934/96b1a650-4052-11e6-8165-f362108274d9.png">
<img width="1120" alt="screen shot 2016-07-02 at 12 38 23" src="https://cloud.githubusercontent.com/assets/1208119/16539936/abb92802-4052-11e6-8921-637c40f35c04.png">

**Comment by DonLakeFlyer** [comment]
Fixed
