### ISSUE TITLE
the default voltage threshold parameter about Iris+ is too high

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3726]
Test Environment
QGroundControl: Daily Build: v2.9.7b-379-g2e9d112
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the default parameter values are correct
Step:
1. Lanuch QGC
2. Connect to Iris+
3. Load params on Airframe item setting page
4. Check the voltage threshold in safety item setting page
Excepted result:
The value should fit for the real battery
Actual result:
The voltage about real battery is 11.1V, the voltage threshold value is 14.0V. Even the battery is full, still tragger low battery failsafe. 

![default voltage threshold parameter about iris is too high](https://cloud.githubusercontent.com/assets/1768868/16572472/8553618c-429b-11e6-8557-0c758ba7c978.jpg)

**Comment by DonLakeFlyer** [comment]
This is because the params aren't refreshed. The correct param is on the Vehicle.
