### ISSUE TITLE
hide VTOL waypoints if not a VTOL

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#3735]

**Comment by DonLakeFlyer** [comment]
Do you mean there are some MAV_CMDs which are specific to VTOL?

**Comment by dagar** [comment]
![screenshot from 2016-07-06 22-52-21](https://cloud.githubusercontent.com/assets/84712/16641266/d55e5894-43cc-11e6-8ec9-c38e642ff7ab.png)

Yes, I just want to try and keep the selection as simple as possible.

**Comment by DonLakeFlyer** [comment]
FirmwarePlugin::supportedMissionCommands should adjust based on vehicle type

**Comment by dagar** [comment]
I just took a look and now it looks like all the commands are visible (including vtol).

**Comment by DonLakeFlyer** [comment]
Turns out that due to the internal architecture this ends up being really hard to do.

**Comment by DonLakeFlyer** [comment]
Done
