### ISSUE TITLE
UX review for 3.1

### ISSUE THREAD

**Issue by biapalmeiro** [mavlink/qgroundcontrol#3740]
@dogmaphobic Moving your suggestions to this new issue:

Eventually, we may need to rethink the UX a bit. Some ideas:
- Maybe vehicle setup should be a category of _Preferences_. In that case, the "dot dot dot" button would turn into _Settings_, which would give you _Application Settings_ and _Vehicle Settings_.
- The current _Plan View_ should be the _Settings_ of a _Mission_ type mode (below). In that case, there would be only one view, which is the _Fly View_.
- From the _Fly View_ you would have choices (drop down, menu or some other form of selection). The choices would be:
  - User Controlled Flight -- The user is controlling the vehicle (in any of its supported modes such as Manual, Position Control, etc.) and the UI is simply a glorified OSD.
  - Autonomous Flight -- The flight is autonomous, following the settings and choices provided by the user. Here is where you would select _Mission_, _Orbit_, _Follow Me_, etc. As each _Autonomous Mode_ is selected, the interface would adapt to that mode (such as showing the current _Plan View_ when you select _Mission_).

My thoughts here were to make a clear distinction between when you are flying the vehicle and when the vehicle is doing something on its own. If you think there is a way to make it all one, better.

> If your tweaking the mission or tuning an airframe your constantly switching views. Although this might lead to a completely different discussion about what dev-users need, e.g. a view with everything like we had ages ago, which I'm not going to start now.

As I suggested above, _Mission_ should be a mode of the _Fly View_ (the one and only view).
Tuning an airframe as well as "_a view with everything like we had ages ago_" are advanced uses. You would basically need two, very different UIs to handle "Normal" and "Advanced". The "_view with everything_" would never fit a mobile platform either. It's a valid point but short of having two separate UIs, I don't know how you could reconcile both needs.

**Comment by dogmaphobic** [comment]
I should probably further classify *Autonomous* as *Fully Autonomous* such as the case with *Mission*, *Survey*, etc. and *Controllable Autonomous* such as *Orbit*, which allows you to use the sticks to control radius, direction, velocity and altitude.
