### ISSUE TITLE
QGroundControl only runs once

### ISSUE THREAD

**Issue by Ender1618** [mavlink/qgroundcontrol#3754]
I have successful built QGroundControl (with video stream support enabled) on Ubuntu 14.04, the first time I run it, it seems to work fine.  If I exit from the program (say using menu->exit) then try to run it again I get this error:

`
ryanv@narsil:~/src/qgroundcontrol/build/release$ ./qgroundcontrol 
Settings location "/home/ryanv/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"
Map Cache in: "/home/ryanv/.cache/QGCMapCache100" / "qgcMapCache.db"
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed
Orphaned log file count 0
Segmentation fault (core dumped)
`

Any suggestions?

**Comment by DonLakeFlyer** [comment]
Did you run qgc using sudo at some point? The permissions on that directory are incorrect.
