### ISSUE TITLE
Log Download: Refresh never shows list

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3763]
Log entries come through but are never processed because _requestingLogEntries is false at this point:
https://github.com/mavlink/qgroundcontrol/blob/master/src/ViewWidgets/LogDownloadController.cc#L151

**Comment by DonLakeFlyer** [comment]
Looking at this a little more it looks like the timer fires, which then leads to this call tree.
0	LogDownloadController::_receivedAllEntries()	LogDownloadController.cc	236	0x10028f880	
1	LogDownloadController::_findMissingEntries()	LogDownloadController.cc	289	0x10028e698	
2	LogDownloadController::_processDownload()	LogDownloadController.cc	122	0x10028e3ca	

This happens before the first log entry comes back so the list is empty and _receivedAllEntries marks the request as complete.

**Comment by dogmaphobic** [comment]
Odd, I wonder how it worked until now. I'll take a look in the morning.

**Comment by DonLakeFlyer** [comment]
Timing thing? Timer goes off before first entry comes back. I have a PixRacer with a pile of logs on it. Maybe the big list causes the initial delay of the first entry.

**Comment by DonLakeFlyer** [comment]
Tomorrow I'll try on a different board with fewer logs.

**Comment by DonLakeFlyer** [comment]
I works fine with smaller log counts.

**Comment by DonLakeFlyer** [comment]
When I do an Erase All it erases all the files in the log directory but it does not erase the msg_*.txt files. These pile up as well for each run and could fill the SD card causing the vehicle to crap out.
