### ISSUE TITLE
Request: Parameter search while typing

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#3768]
Please search in parameters while typing - (not wait till enter is pressed)

**Comment by DonLakeFlyer** [comment]
Yeah, we took a stab at that with 3.0. But it was too slow on mobile devices. Needs a re-write of param list code to work.

**Comment by AndKe** [comment]
ok, please consider making it require fewer clicks. Maybe do the way AP2
does it ? - that works really well.

**Comment by DonLakeFlyer** [comment]
We are going to implement typedown search like you want. Just had to wait for 3.1 since it was more involved.
