### ISSUE TITLE
Add polygon geofence support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3769]

**Comment by dagar** [comment]
I'd like to add a way to do this for PX4.

It looks like APM just sends FENCE_POINT - http://mavlink.org/messages/ardupilotmega#FENCE_POINT

**Comment by lvale** [comment]
https://github.com/ArduPilot/MissionPlanner/issues/1307

basic support is in MP

https://github.com/ArduPilot/MissionPlanner/issues/1308

**Comment by DonLakeFlyer** [comment]
ArduPilot is done. Px4 still not done.
