### ISSUE TITLE
Request: better mission info. 

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#3772]
![screenshot from 2016-07-10 21-50-27](https://cloud.githubusercontent.com/assets/1468842/16715781/01a75fd4-46ea-11e6-90fd-e1f7e10a97d2.png)

please observe attached mockup.
While planning , Flightpath should display the total flightpath.
Speed is where user enter/scroll expected speed.
Max distance would indicate maximum telemetry range needed.
Estimated flighhttime is simply minutes from flightpath/speed

These tools make it easier to plan, and split missions into reasonable parts based on RPAS endurance, and to select takeoff/landing place that can be used for multiple parts of a mission, yet be within radio range.

Also, during flight- radio (RSSI) information, could very well display current distance to home.

**Comment by DonLakeFlyer** [comment]
Implemented
