### ISSUE TITLE
Please save/restore map position on exit/load.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#3773]
Yes, I do recognize the park near the golden gate bridge where I hired bicycle to go over the bridge :)  - still, I usually plan missions in northern Norway, and it's much better not to need to pan across the world every time just because the park is a nice place :)

**Comment by DonLakeFlyer** [comment]
The map will go back to the last vehicle home position that it got. If you've never connected a vehicle it will default to SF. Does that make sense?

**Comment by AndKe** [comment]
Ok, I understand how it works.
Still , please save/restore last position.
I would like to add maps for Norway/nordic countries. (very useful, topographic and detailed maps)
If such maps were enabled, and application started, showing USA as usual, the map would be empty.
Also, it's very konveniens to spawn the map of the area where you live/plan/fly missions, instead of half-a-globe away :)

**Comment by DonLakeFlyer** [comment]
I'm going to revisit all of this in 3.2

**Comment by DonLakeFlyer** [comment]
All reworked now
