### ISSUE TITLE
The orientation of RTL mode is incorrect

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3775]
Test Environment
QGroundControl: Daily Build: v2.9.7b-411-g0fefa4f
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the orientation of RTL mode is correct
Step:
1. Lanuch QGC
2. Connect to SITL
3. Enable Circle GeoFence
4. Set some waypoints out of the GeoFence range
5. Takeoff and change to Auto mode
6. Check the vehicle's orientation while RTL mode triggered.
Excepted result:
The orientation should point to Home
Actual result:
The orientation doesn't change while RTL mode triggered.
![orientation during rtl](https://cloud.githubusercontent.com/assets/1768868/16724626/35ed8b32-4786-11e6-9ed7-557b57928061.JPG)

**Comment by DonLakeFlyer** [comment]
QGC isn't in control of this. That firmware decides how to RTL.
