### ISSUE TITLE
Some offline map size is 0

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3778]
Test Environment
QGroundControl: Daily Build: v2.9.7b-411-g0fefa4f
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the offline map size is correct
Step:
1. Lanuch QGC
2. Click "Add new set" in Offline Maps item Settings page
3. Download the set
Excepted result:
The map size should not 0
Actual result:
Some offline map size is 0
![map size is 0](https://cloud.githubusercontent.com/assets/1768868/16724716/b6b2a19e-4786-11e6-862b-db69bb0e3d68.JPG)
![map size is 0_02](https://cloud.githubusercontent.com/assets/1768868/16724725/baab63da-4786-11e6-9ef0-8d113f47ab9a.JPG)

**Comment by dogmaphobic** [comment]
I not only was able to reproduce this, I also found a few other oddities with the display of sizes and download status. Not sure what happened as this was all working at some point. Looking...

**Comment by glody** [comment]
Checked on daily build HEAD:e6e0429 2016-07-20 18:58:20 -0400, this issue unable to reproduce. close it. thanks.
