### ISSUE TITLE
Surveying parameter from camera parameters

### ISSUE THREAD

**Issue by birchera** [mavlink/qgroundcontrol#3779]
We would like to implement the direct computation of surveying parameters (altitude, grid spacing) from camera parameters (sensor size, focal length, ...). Additional required inputs are ground sampling distance (GSD) and overlaps in both directions.

For the camera parameters we propose to add fields to the camera settings tab like this:

![camera_settings](https://cloud.githubusercontent.com/assets/2298059/16733848/7e45aab6-4783-11e6-802c-949990d42d84.png)

We have thought of three different ways to include this functionality in the survey widget.
* Adding a button to the widget and select GSD and overlaps in a pop-up window and then overwriting altitude and grid spacing.
![survey_setting2](https://cloud.githubusercontent.com/assets/2298059/16734216/ffd1224e-4784-11e6-8b8f-49bc8c6b9186.png)
* Checkbox in widget, when checked reveals the fields for GSD and overlaps.
<div class="nav3" style="height:705px;">
<img src="https://cloud.githubusercontent.com/assets/2298059/16734067/7147c5b4-4784-11e6-9222-7370abee26fd.png" width="200">
<img src="https://cloud.githubusercontent.com/assets/2298059/16734066/71460882-4784-11e6-9e83-b5f01b2e9f54.png" width="200">
</div>
* Adding GSD and overlaps to the camera settings tab and give computed values as defaults when creating the survey item.

@DonLakeFlyer does this feature fit your plans for the surveying and do you have a preference for one or the other?

**Comment by DonLakeFlyer** [comment]
The first step is to add support for the base functionality and then figure out the right UI for it later. So for now that means all the tweakable values just go into the Survey item editor.  So the first step is to list out the changeable values that you want. The best place for that is in the main Survey discussion issue: https://github.com/mavlink/qgroundcontrol/issues/2507. Then we can home some discussion around those. If there aren't any issues and I easily add to Survery editor and then the implementation can begin.

**Comment by birchera** [comment]
This has been adressed in https://github.com/mavlink/qgroundcontrol/pull/3981.
