### ISSUE TITLE
Cannot switch between vehicles with multiple vehicles if active vehicle disconnects

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#3784]
As the title says; I've got 2 vehicles coming in over UDP.. one is SITL simulator. When I shut down the simulator the vehicle selection combobox is hidden is "COMMUNICATION LOST" is displayed. I can't get to the other (still active) vehicle.

**Comment by DonLakeFlyer** [comment]
I think this may be a dupe

**Comment by NaterGator** [comment]
Yup, dupe of #3086
