### ISSUE TITLE
Can't download latest QGC for linux

### ISSUE THREAD

**Issue by CarlOlsson** [mavlink/qgroundcontrol#3788]
If I press **Linux tar download** on http://qgroundcontrol.org/downloads I get redirected to:

![selection_080](https://cloud.githubusercontent.com/assets/7795133/16760034/430dfac4-481a-11e6-979f-f62310d208e8.png)

**Comment by dagar** [comment]
In qmake the app was renamed qgroundcontrol -> QGroundControl (to fix android naming), which also updated the installer ouput.

https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.AppImage
https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.tar.bz2

I'll get the wiki updated. Thanks for reporting.

**Comment by dagar** [comment]
It looks like I don't even need to update the wiki. Downloads is taking me to the new gitbook which has the proper links.
https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html
