### ISSUE TITLE
Survey Phase 1 Implementation

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3797]
This is the discussion area for Phase 1 Implementation: **Flight Path**

**The first feedback should be on how I'm trying to structure the survey discussion and work using this issue. Then the question is what features are we missing for Phase 1? Within the features I've listed below there is much detail missing which needs to be filled in and/or correction/additions to the initial information I've entered.**

**My hope is that this provides not only a framework for discussion but also the framework for the creation and dispersal of a detailed set of work items to individual devs.**

We need to start with the basics, so Phase 1 Implementation will not be very sexy and will deal solely with the flight path of the vehicle. We will also not worry too much about overly pretty ui at first. If the base capability is architected correctly, we can put whatever ui we want on it. I want to take things one step at a time to focus the discussion and implementation.

An example of base flight path functionality for phase 1 versus something which will be dealt with during future phase work:
Phase 1 will include support to specify the distance between parallel lines of the grid (grid spacing). Phase 1 will not include such things as image overlap or camera sensor information. Although image overlap and camera information affects grid distance, they are simply survey meta data to simplify the process of setting the grid distance (amoung other things). The base capability needed to support them is still just grid spacing.

The process will be that the discussion here leads to updates/adds to the feature list and feature details as well as set of individual works items.

Flight Path feature set (details for each below):
- Polygonal area which defines the survey area
- Survey is treated as a single entity within the overall mission plan
- Ability to have multiple survey areas in a single mission
- Ability to re-edit survey after save/re-load from file
- Values needed to generate a simple grid flight pattern over the polygon
- Values needed to fly a correct turnaround to the next grid line
- Ability to modify the above values at any time and have the flight path dynamically update
- Conversion of above information into a set of waypoints
- Load/Save to file of a mission which includes a survey
- Mission stats: Flight time, battery usage, etc.
- Ability for user to specify information which determines entry into survey area

**Comment by DonLakeFlyer** [comment]
* Polygonal area which defines the survey area

**Comment by DonLakeFlyer** [comment]
* Ability to have multiple survey areas in a single mission

**Comment by DonLakeFlyer** [comment]
* Ability to re-edit survey after save/re-load from file (doesn't degenerate into big pile of waypoints)

**Comment by DonLakeFlyer** [comment]
Values needed to generate a simple grid flight pattern over the polygon

**Comment by DonLakeFlyer** [comment]
Values needed to fly a correct turnaround to the next grid line

**Comment by DonLakeFlyer** [comment]
Conversion of above information into a set of waypoints

**Comment by DonLakeFlyer** [comment]
Load/Save to file of a mission which includes a survey

**Comment by DonLakeFlyer** [comment]
**Feature: Survey is treated as a single entity of the overall mission plan**

**Comment by WickedShell** [comment]
If like to have a discussion about that JSON format. I'm looking to support it as well, however there are a couple of really weird aspects to it last time I looked at the output that if like to discuss changing before everyone has locked into it. Would that be held here or maybe on the drone code discourse instead?

**Comment by WickedShell** [comment]
If like to have a discussion about that JSON format. I'm looking to support it as well, however there are a couple of really weird aspects to it last time I looked at the output that if like to discuss changing before everyone has locked into it. Would that be held here or maybe on the drone code discourse instead?

**Comment by WickedShell** [comment]
Sorry for duplicate comments, web interface on a phone is apparently poor and I can't delete it..

**Comment by DonLakeFlyer** [comment]
> If like to have a discussion about that JSON format.

Yup. I'm going to break that out into a separate discussion and bring in Bill and Michael as well. I'll get that organized hopefully by tomorrow.

**Comment by DonLakeFlyer** [comment]
Also if your looking at an example saved mission file with a survey in it on daily builds that format is wrong. It doesn't write out all the raw waypoints.

**Comment by DonLakeFlyer** [comment]
Added separate discussion for JSON file format: #3800

**Comment by birchera** [comment]
We have been testing the surveying feature for a while now and have had some good experiences with it. 
The features listed here address most of the concerns we had with surveying so far and it's great to hear that you plan to work on them in the near future.
Being able to resize / move the survey area by moving existing polygon points, better/more customized handling of turnarounds and having the survey item with the corresponding meta data and all the individual waypoints in the mission file, would make using the surveying feature much easier for us.

An additional helpful feature would be to output the total flight distance/time of the survey, but this might already fall into a later phase.

We are happy to test any of the new features.

**Comment by DonLakeFlyer** [comment]
Added separate discussion for turn-around: #3801

**Comment by DonLakeFlyer** [comment]
Feature: Mission stats

This feature is to calculate a set of information associated with the mission and display to the user. For example total flight time and distance, battery usage and so forth.

* Stats discussion is here: #3802

**Comment by DonLakeFlyer** [comment]
Added new feature "Mission Stats" to Phase 1 and separate discussion #3802 for it.

**Comment by DonLakeFlyer** [comment]
Adjustment of existing survey polygon now supported.

**Comment by DonLakeFlyer** [comment]
**Feature: Ability for user to specify information which determines entry into survey area**

This feature allows the user to determine how and where the vehicle enters the survey grid.

* Discussion here: #3864

**Comment by DonLakeFlyer** [comment]
Added bug #3866

**Comment by DonLakeFlyer** [comment]
Add camera discussion: #3963

**Comment by DonLakeFlyer** [comment]
This is mostly all done now

**Comment by SpandanKumarSahu** [comment]
@DonLakeFlyer, I am new to QGroundControl. I was trying to figure out, if along with storing the survey, we can have an option of storing the generated waypoints too?

**Comment by DonLakeFlyer** [comment]
At some point I'll do that, but the real question is why? Even if they were there you would not be able to modify them. The only reason to do it is for other ground stations to be able to read the format. If you want to get the waypoints for a survey you can just round trip the plan through the vehicle:
* Upload
* Download - It will denegenerate into individual waypoints
* Save

**Comment by SpandanKumarSahu** [comment]
Yeah, I understand it that might not be a very relevant feature. Thanks for the reply, anyway.
