### ISSUE TITLE
Fix grid generation line bug

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3798]
You can see in the image the bad line which is not parallel. Not quite sure what polygon shape cause it to happen:
![screen shot 2016-07-12 at 3 40 11 pm](https://cloud.githubusercontent.com/assets/5876851/16786069/ffb98144-4846-11e6-9563-d772154cc1ea.png)

**Comment by NaterGator** [comment]
@DonLakeFlyer it is because the short segment running to the west fell outside  of the polygon clip region.

**Comment by DonLakeFlyer** [comment]
I sort of get what you are saying but I of course can get it to repro any more. Should have saved the mission!

**Comment by DonLakeFlyer** [comment]
Here is a mission that shows the bug: https://gist.github.com/DonLakeFlyer/dd4e2f5923732d493e3d957f91ff6668
