### ISSUE TITLE
Survey: Simple grid visualization

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3799]
Screen shot shows the simple grid display as well as entry exit point display:
![screen shot 2016-07-12 at 3 42 41 pm](https://cloud.githubusercontent.com/assets/5876851/16786125/5911a276-4847-11e6-8325-db0361449fdc.png)

**Comment by DonLakeFlyer** [comment]
I wonder if the grid angle should automatically set itself to set up the grid lines such that they are following the longest path.

**Comment by kellysteich** [comment]
It would be great to have the option of automatically aligning the grid lines such that they are following the longest path.
You would most likely still need to give the user the option of aligning the grid lines with the wind direction, though. Either also have an option of doing this automatically or still leave the option of setting the grid angle manually.

**Comment by DonLakeFlyer** [comment]
I think this is good as it is
