### ISSUE TITLE
Mission: JSON file format

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3800]
The goal of the new JSON file format for missions is to create a format which is both more human readable as well as a format which allows for easier placement of additional metadata. The additional meta data will allow storage for higher level concepts than just waypoints such as Survey or Structure Scan information.

Following is the structure of the JSON.

```
{
    "MAV_AUTOPILOT": 12,
    "complexItems": [ { complex mission item }, { complex mission item } ],
    "groundStation": "QGroundControl",
    "items": [ { mission item }, { mission item } ],
    "plannedHomePosition": { mission item }, 
    "version": "1.0"
}
```
- **MAV_AUTOPILOT** - This field holds the MAV_AUTOPILOT value for the firmware (MAV_AUTOPILOT_PX4=Px4 Pro, MAV_AUTOPILOT_ARDUPILOTMEGA=ArduPilot) this mission file was created for. The reason it is here is that there are differences in implementations of MAV_CMDs between the two firmwares. So we record it to be able to handle any inconsistencies in the right way.
- **complexItems** - This field is meant to hold complex mission items such as survey or structure scan. We'll discuss this more in a separate post.
- **groundStation** - This field specifies the ground station which wrote this file. The reason for this is that although the simple mission items are interchangeable between ground stations. The specification of complex mission items are specific to a ground station.
- **items** - The items field holds the full list of all mission item objects. It contains all mission items including any items which may be references by a higher level complex mission item. This way all ground stations can interchange at a minimum the full list of mission items. The ids which indicate sequence are 1-based.
- **plannedHomePosition** - This is required since the PX4 Pro and ArduPilot firmware handle mission item 0 as sent to a vehicle differently. For ArduPilot this item is sent as item 0. For PX4 Pro this item is not sent to the vehicle. Ground stations can use this value to show a planned home position. The planned home position should be a waypoint item.
- **version** - The version field is the version number for the file format.

A single mission item within the file looks like this:

```
{
    "autoContinue": true,
    "command": 16,
    "coordinate": [ 47.633425920000001, -122.08828776999999, 25 ],
    "frame": 3,
    "id": 2,
    "param1": 0,
    "param2": 0,
    "param3": 0,
    "param4": 0,
    "type": "missionItem"
},
```

The fields should be pretty self-explanatory. The match the values in the mavlink MISSION_ITEM message. 
- **coordinate** - latitude, longitude, altitude
- **id** - The id field correlates to MISSION_ITEM.seq. It is not exactly the same as the sequence field since the ids must be adjusted based on whether a fake home position is sent on sequence 0 to the vehicle. Because of this ids may need to be adjusted when converted to MISSION_ITEM.seq before sending to a vehicle.
- **type** - This is a remnant of WIP survey code in QGC. It can likely be removed. But not sure yet until complex mission item is fully defined.
- The MISSION_ITEM.current field is not included since that is only needed while actually running a mission.

**Comment by DonLakeFlyer** [comment]
**The complexItems field**

The concept behind the **complexItems** field is to provide a location to store the meta data associated with a complex mission items. You can have multiple complex mission items within a single mission. Examples of complex mission items are Survey and Structure Scan. A single complex mission item stores meta data associated with the item. It references a range of mission items from the main **items** list.  The mission items associated with a complex mission item are not stored within the complex mission item. This storage structure allows for two things:
1) Round tripping a re-editable complex mission item through a file.
2) Ground stations which don't understand complex mission items still have access to the full raw set of mission items.

**Comment by WickedShell** [comment]
In an airport at the moment will have to review again later but the first comment that comes to mind is this looks difficult to reinsert the complex items into the simple items (ie a mission of take off then survey then some manually planned waypoints)

Why not put all items in a single list, and require that a complex item also provide a list of all it's generated simple items that everything can parse? On first pass this sounds slightly easier to load fort the gcs that can interpret the complex items.

**Comment by WickedShell** [comment]
Version of the file format is valuable but I could definitely see wanting to support logging the gcs version as well for compatibility reasons

**Comment by WickedShell** [comment]
A comment on the camera metadata for survey is that any non trivial/professional  gcs will be needing to store the camera parameters rather then the offsets of the lines in meters. But maybe it doesn't make sense to do a common variant of this complex item even though it would be nice

**Comment by DonLakeFlyer** [comment]
> Why not put all items in a single list, and require that a complex item also provide a list of all it's generated simple items that everything can parse? On first pass this sounds slightly easier to load fort the gcs that can interpret the complex items.

I've kind of gone back and forth on that exact thing. It all got so complicated to code, current QGC doesn't even write out the complex item mission items to the file anywhere because it got crazy trying to manage the referencing. I don't think add the items to the complex item as well will make things easier. The reason is that you still have to handle the items coming back and forth from the simple items to complex items and back to simple items. So you still need to code to skip over items in the main item list. In reality not quite sure. Need to think about it a little.

**Comment by WickedShell** [comment]
I guess what I want sure is I didn't see how to slot the complex item back
into the simple list correctly... ie waypoints 5-100 are all from complex
item one but I couldn't see how to cut that back in.

Particularly if you are loading a file where the number of generated
waypoints for the complex item is now different due to either but fixing
bugs or new attributes that weren't present before causing a change in the
number of waypoints.

**Comment by DonLakeFlyer** [comment]
> any non trivial/professional gcs will be needing to store the camera parameters rather then the offsets of the lines in meters.

This is the current level of survey support in QGC showing through somewhat. It doesn't currently support any camera information, so all you have is grid distance. In the long run the camera information, plus overlap and so forth in turn sets the grid distance. A question is whether it ends up being an either or thing. If you have camera information you have just that. But if you don't you can still create a simple grid using just grid distance without needing to know anything about camera stuff. Use case which comes to mine happens to my RC field quite a bit. Send out a drone to go look for a lost plant. The person that does that probably doesn't know anything about the details of camera or more likely video camera they have on their drone. Just just set up a simple grid by distance.

**Comment by WickedShell** [comment]
From the professional mapping perspective the camera information and
handling is mandatory, and if the user can't get the camera info then they
have no chance of guaranteeing good data anyways. But as you observed for
now this could be unique to each gcs.

**Comment by DonLakeFlyer** [comment]
> I guess what I want sure is I didn't see how to slot the complex item back
> into the simple list correctly.

The complex item should have meta data something like this:
"startId": #
"endId": #

Which would indicate the range of ids from the main list which are for the complex item. I would expect the GCS that supports the complex item to simply skip loading these from the main list and regenerate them from the meta data. That is how QGC currently works (especially since it doesn't even write the complex items!).

**Comment by WickedShell** [comment]
It just seems like a slightly weird load process to me add you have to scan
the complex before filling the gaps from the simple. Seems like just
iterating through a combined list and loading a simple subset for any
complex you don't understand is easier. But that's just my thoughts without
having sat down to implement it yet.

**Comment by DonLakeFlyer** [comment]
I think the issue is that no matter how you structure it, if you want to make downlevel gcs loading support feasible/simple, then you move the pain to the up level gcs that understands complex items. Maybe some completely different structure or additional side structure is possible to simplify things. I'll think some more about it in the next couple days. But I know exactly what you are talking about since I already ran head first into it with current QGC code.

**Comment by NaterGator** [comment]
@DonLakeFlyer maybe in a JSON format you have both? Insert the complex and simple items, but tag the simple items with an ignored field that lower feature tier GCS software will ignore (like: "ephemeral": true) but high tiered knows to interpret. I guess the trick is tagging in the complex items so that it doesn't trip up lower tiered GCS packages, but I think there are clean ways around that.

**Comment by billbonney** [comment]
This was the example I wrote before https://gist.github.com/billbonney/8d8b8798ba5bb7a50fa8

Where you would have support for mission_items, and then in sequence, mission_area, that defined a  polygon area with properties. those properties could be as simple as grid discretion, and spacing, or camera properties etc... 

I think having complexItems and missionItems as separate lists makes the format much harder to read and parse. 

We can add new complex items like initiate_landing take_off etc.. whatever, but we should try and document these and make them 'generic' for all gcs implementation to support.

Having the meta data about the program that writes the file may help resolve problems, but it shouldn't be required at all. If QGC has different complexItems vs. Mission Planner or Tower. It kind of defeats the purpose.

I know the main problem of implementing this currently in APM Planner 2.0 and MAVPilot is that the internal structure represents a mission_item in MAVLink, when really it should be an object list that represents the waypoints and behaviour on the screen. Only when it 'externalizes' to the autopilot does it get converted into mission_items. (And don't forget that there is also the case where the son could be uploaded to a onboard computer and it just guides the autopilot in real-time, point by point.)

Anyway, i'm glad this is being discussed 👍

**Comment by DonLakeFlyer** [comment]
> I think having complexItems and missionItems as separate lists makes the format much harder to read and parse.

I think Bill hits the nail on the head. I was trying too hard to preserve a very simple format for downstream groundstations which don't understand a complex item. But since those gcs need to implement new JSON parse anyway it can be at least a little more structured. I like Bill's single list way of doing it much better. It's still easy for a gcs which does not support complex to read the raw items. I'll update the proposal at the top for that style format instead and we can take a look at it.

**Comment by WickedShell** [comment]
I think I'm missing something but with Bills version where does a GCS that doesn't understand how to generate that survey grid get a list of waypoints? Expecting multiple GCS's to generate the same way points seems extremely unlikely/farfetched, as well as there being a lot of value in maintaining the information for a non compatible GCS to still extract and upload the data.

**Comment by billbonney** [comment]
@WickedShell I wasn't looking at that use case. There could be an 'absolute waypoint only export'  feature that the GCS could implement. Or you could create an embedded abs waypoints array in the JSON file for interoperability.

see https://gist.github.com/billbonney/8d8b8798ba5bb7a50fa8

**Comment by DonLakeFlyer** [comment]
> I think I'm missing something but with Bills version where does a GCS that doesn't understand how to generate that survey grid get a list of waypoints?

I'll make an example tonight. But basically what Bill showed.

**Comment by DonLakeFlyer** [comment]
Here is a possible way to flatten out the top level structure and simplify reading for both gcs that support complex items and those that do not. This creates a linear read sequence for both only simple items and a read that supports both simple and complex.

The top level format is the same except that all items both simple and complex are in the **items** array.
```
{
    "MAV_AUTOPILOT": 12,
    "groundStation": "QGroundControl",
    "items": [ { simple or complex item }, { simple or complex item } ],
    "plannedHomePosition": { mission item }, 
    "version": "1.0"
}
```

The simple item pretty much stays the same as above, but the **type** field is now required.
```
{
    "type": "simpleItem",
    ...
}
```

The complex item is mostly the same as well except for **type** and the **items** array which contains the simple items associated with the complex item.
```
{
    "type": "complexItem",
    "items": [ { simple item }, { simple item } ],
    ...
}
```

So a downlevel gcs reads items linearly. When it see a complexItem it just reads the simple items from the complex item and pops back up to continue reading in the main **items** array. A gcs that support complex items just reads the complex item meta data and regenerates the simple items using its own algorithms.

**Comment by WickedShell** [comment]
@DonLakeFlyer I prefer that a lot more over the two list approach! Seems much more straightforward for reading :)

How about adding rallypoints to a file as well? Would they just go under a seperate rally-items list? I know not all missions have support for them and that some will treat them differently, but it would be nice to be able to include this as part of a mission, without having to be a GCS specific bit.

**Comment by DonLakeFlyer** [comment]
Current state of Mission/Survey file format is documented in dev guide: https://donlakeflyer.gitbooks.io/qgroundcontrol-developers-guide/content/MissionFileFormat.html

Rally Points/GeoFence are currently separate files. Further down the road I have the concept of a "Plan" file which could include mission, rally and geo-fence.

Also: Survey still doesn't output internal waypoints for downstream client use. Although the new V2 mission file format with respect to how it deals with complex items is now set up to support that.

**Comment by DonLakeFlyer** [comment]
At this pint I'm not going to worry about downstream client reading
