### ISSUE TITLE
Survey: Mission stats

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3802]
Although not solely a feature for Survey generating a set of stats associated with the mission such as flight time and distance, battery usage and so forth is important. Let's use this issue to discuss what information should be collected about a mission.

**Comment by DonLakeFlyer** [comment]
I'm in the process of collecting up the information from the various issues already entered on this...

**Comment by birchera** [comment]
Related to https://github.com/mavlink/qgroundcontrol/issues/3772

In my experience the values that are interesting to know when planning missions are:
* Total flight distance
* Total time
* Max telemetry distance

For VTOLs:
* Splits hover/cruise distance
* Splits hover/cruise time

For Survey missions:
* Number of images that will be taken
* Covered area

@kellysteich FYI

**Comment by DonLakeFlyer** [comment]
@andke In #3772 You have a speed value which I don't quite understand. Can you explain more?

**Comment by DonLakeFlyer** [comment]
FYI to folks looking: @birchera and friends are actively working on support for this.

**Comment by tubeme** [comment]
Another important parameter set is the Altitude information:

Higest altitude
Lowest altitude
Avarage altitude
Cumulative ascent
Cumulative descent

This could orient the pilot about the performance needed for the mission in terms of energy requirements.

**Comment by DonLakeFlyer** [comment]
This is in a good state for 3.2
