### ISSUE TITLE
Vagrantfile Issues

### ISSUE THREAD

**Issue by lutherling12** [mavlink/qgroundcontrol#3805]
With the qt package that's installed on the Vagrantbox, qtCreator isn't bundled with it. Since there was a .pro file in the repository, I tried `qmake --makefile`

It yielded the message:
```
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
```
`dpkg -l | grep qmake` doesn't list qmake; It doesn't seem like qmake is installed.

**Comment by lutherling12** [comment]
mkdir -p ${HOME}/.config/qtchooser
printf '%{qt_deps_bin_dir}' > ${HOME}/.config/qtchooser/default
printf '%{qt_deps_lib_dir}' >> ${HOME}/.config/qtchooser/default

**Comment by dagar** [comment]
I believe this is resolved.
