### ISSUE TITLE
Off-Topic: Unable to download daily builds from AWS

### ISSUE THREAD

**Issue by shadow1runner** [mavlink/qgroundcontrol#3806]
I know that's not related to code, but I hope that that's not the completely wrong place for this.
Anyway, downloading [the latest Win build](https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/qgroundcontrol-installer.exe) gives the following error:
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>55D863879D9C3CC2</RequestId>
<HostId>
G9Z6ZSoRXv91sgpWO7zycWK7JpiJg2aZ7VJEShfaEDU5KDSU91LygxmnO3tXIqfAkkLAGFkaqmY=
</HostId>
</Error>
```

**Comment by NaterGator** [comment]
The new download links are at http://qgroundcontrol.io/downloads/

What page were you linked from?

**Comment by shadow1runner** [comment]
Ou, I see.
I took the first google result which was [http://qgroundcontrol.org/downloads](http://qgroundcontrol.org/downloads)

**Comment by DonLakeFlyer** [comment]
That page is old. It's not longer connected to anything. But I'll update it anyway since search engines may take a while to catch up.

**Comment by shadow1runner** [comment]
Thanks Don,
if the page got completely obsoleted by qgroundcontrol.io maybe a static redirect would help both users and web crawlers.

**Comment by DonLakeFlyer** [comment]
I've updated the old page to point to the new one.
