### ISSUE TITLE
Support for VTOL transition switch

### ISSUE THREAD

**Issue by tumbili** [mavlink/qgroundcontrol#3825]
VTOL transition switch is now implemented on the firmware side here https://github.com/PX4/Firmware/pull/5101/files
We need the corresponding changes for QGC.
@DonLakeFlyer FYI

**Comment by tumbili** [comment]
@DonLakeFlyer Sorry, I forgot that I opened this issue, that's why I pinged you again on the firmware side.

**Comment by DonLakeFlyer** [comment]
This is on the Flight Modes screen now
