### ISSUE TITLE
when supported vs2015?

### ISSUE THREAD

**Issue by MrChang0** [mavlink/qgroundcontrol#3835]
when supported vs2015?

**Comment by DonLakeFlyer** [comment]
No timeframe for it yet. Will consider for 3.1.

**Comment by NaterGator** [comment]
It is already supported. Nothing breaks with the appropriate version of Qt and VS2015, I build in that configuration all the time.

**Comment by DonLakeFlyer** [comment]
Closing this to replaced by #3878
