### ISSUE TITLE
The unit in safety item doesn't change while changing the units

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3851]
Test Environment
QGroundControl: Daily Build: HEAD:e6e0429 2016-07-20 18:58:20 -0400
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Purpose:
Check if the units in safety item is correct
Step:
1. Lanuch QGC
2. Change the units and relaunch QGC
3. Check the unit in safety item, setup page.
Excepted result:
The unit should change accordingly
Actual result:
The unit is still meter and centimeter
![units_01](https://cloud.githubusercontent.com/assets/1768868/17095404/d9e10fe2-5286-11e6-8795-2e1934406cfc.JPG)
![units_02](https://cloud.githubusercontent.com/assets/1768868/17095405/dd345672-5286-11e6-903a-802c1498f2ae.JPG)
![units_03](https://cloud.githubusercontent.com/assets/1768868/17095410/e05115ca-5286-11e6-97ee-3442199a1e1b.JPG)

**Comment by DonLakeFlyer** [comment]
Need to look a this for 3.0

**Comment by DonLakeFlyer** [comment]
I thought this was plumbed through to parameters already but it isn't in 3.0. Just mission items get translation.

**Comment by DonLakeFlyer** [comment]
Fixed now
