### ISSUE TITLE
Polygon adjustment bug

### ISSUE THREAD

**Issue by birchera** [mavlink/qgroundcontrol#3853]
When I move the map during adjustment of the polygon for surveying, the computed path is wrong. Waypoints seem to be computed way out of the polygon.

Before moving the map:
![screenshot from 2016-07-25 17 09 27](https://cloud.githubusercontent.com/assets/2298059/17106255/f5ab91da-528a-11e6-9523-d7a19e52e4a7.png)

After moving the map:
![screenshot from 2016-07-25 17 09 43](https://cloud.githubusercontent.com/assets/2298059/17106262/fb0d66da-528a-11e6-8057-3294822c49b2.png)

**Comment by DonLakeFlyer** [comment]
I'll try to repro this. But if you can save a mission file for both of these images it would save me time trying to repro. The first image also shows the grid generation where you have a non-parallel line in there. I've been having a hard time reproing that as well.

**Comment by DonLakeFlyer** [comment]
This may be related to #3856.

**Comment by birchera** [comment]
[initialMission.txt](https://github.com/mavlink/qgroundcontrol/files/383194/initialMission.txt)
[brokenMission.txt](https://github.com/mavlink/qgroundcontrol/files/383193/brokenMission.txt)

I found that the problem is the list of polygonPoints that goes into ComplexMissionItem::_gridGenerator(). Some of the points are Nan, causing the grid lines to be wrong.

Looking into why this is the case.

**Comment by DonLakeFlyer** [comment]
Not related to #3856. For this bug the mission files don't help unfortunately since brokenMission.txt is trashed as well with a bad polyon area definition. The issue is a bad update while moving the map. But moving the map should not affect affect polygon coordinate values, only physical x,y position information. Hmm.

**Comment by DonLakeFlyer** [comment]
It happens if a drag handle goes off the edge of the map. Could be a bad problem which means you can't really implement your own map positioning items in Qml.

**Comment by DonLakeFlyer** [comment]
Looks like a Qt bug. Just installed Qt 5.7 and doesn't look to be fixed there unfortunately.

**Comment by DonLakeFlyer** [comment]
I was wrong. This works fine in Qt 5.7. The issue is that Map.toCoordinate/fromCoordinate in 5.5 alwas clips to the viewport. Hence once the drag handles go outside the viewport they blow up. In 5.7 that is optional and should work correctly.

**Comment by DonLakeFlyer** [comment]
Working correctly with switch to Qt 5.8
