### ISSUE TITLE
The RSSI status always 0%

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3857]
Test Environment
QGroundControl: Daily Build: HEAD:e6e0429 2016-07-20 18:58:20 -0400
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Purpose:
Check if the RC RSSI status is correct
Step:
1. Lanuch QGC
2. Open RC sumitter and IRIS+
3. Connect to IRIS+
4. Check the RC RSSI status in status bar
Excepted result:
the RC RSSI status is correct
Actual result:
The RC RSSI status always 0%
![rc rssi always 0](https://cloud.githubusercontent.com/assets/1768868/17122859/b4289ad2-5311-11e6-9f88-808b94a7435e.jpg)

**Comment by DonLakeFlyer** [comment]
RC rssi information comes straight from the vehicle. So if it's not working it's either a vehicle setup problem or firmware side problem.
