### ISSUE TITLE
"prompt to save log normally even if vehicle was not armed" can't take effect without app restart

### ISSUE THREAD

**Issue by weakchicken** [mavlink/qgroundcontrol#3859]
Test Environment
 QGroundControl: Daily Build: HEAD:e6e0429 2016-07-20 18:58:20 -0400
 Windows: Windows 8.1 64 Bit Laptop
 Linux: Ubuntu 14.04 64 Bit Laptop
 OS X: OS X 10.11.2 MacBook Pro
 Purpose:
 Check prompt to save log normally even if vehicle was not armed
 Step:
1. Launch QGC(not to arm the vehicle during this test)
2. Checked "Prompt to save Flight Data Log after each flight"
3. Checked "Prompt to save Flight Data Log even if vehicle was not armed"
4. Close the QGC by clicking "X" in UI

Excepted result:
 the UI will pop a log saving dailog after you clicking "X". The function should take effect immediately.

Actual result:
 The log saving dailog is not popped in this time. Relaunch QGC and close it, then log saving dailog will be popped.

**Comment by DonLakeFlyer** [comment]
I think this may not be possible without restart, I'll look. Either way there is a problem.
