### ISSUE TITLE
Launching Qgroundcontrol in Ubuntu

### ISSUE THREAD

**Issue by anthonydnguyen** [mavlink/qgroundcontrol#3860]
Hello guys,
I am new to robotics and linux. I am trying to learn.

I tried to launch Qgroundcontrol with ~/qgroundcontrol/deploy/qgroundcontrol-start.sh

![issue](https://cloud.githubusercontent.com/assets/20654678/17128259/3d843716-52c0-11e6-81bd-3749193ea288.png)

Can someone help me?

**Comment by DonLakeFlyer** [comment]
You are in the wrong directory. You need to be in your build output directory. Wherever the built executable ended up.

**Comment by anthonydnguyen** [comment]
I follow the instruction from http://qgroundcontrol.io/installing-qgroundcontrol/. After decomppressing Qgroundcontrol, they didn't mention about building it. How can i build the package?

**Comment by DonLakeFlyer** [comment]
Ah, sorry. Thought you were building it yourself. You don't clone the repository you download the tar.bz2 and expand.
