### ISSUE TITLE
Clarify VTOL takeoff/land waypoints

### ISSUE THREAD

**Issue by AndreasAntener** [mavlink/qgroundcontrol#3861]
@sanderux we realized the VTOL takeoff/land are not clear next to the VTOL transition waypoint (for a new user). We should change the title and description:

**VTOL takeoff and transition**
Takeoff from ground using VTOL mode and transition to forwards flight.

**VTOL transition and land**
Transition to VTOL mode and land.

Thoughts? Suggestions?

**Comment by sanderux** [comment]
I agree on the land text, for takeoff we should add that the vehicle will takeoff and transition, then fly to the position.

So: Takeoff in VTOL mode, then transition to forward flight and fly to this location.

**Comment by AndreasAntener** [comment]
Sounds good
