### ISSUE TITLE
The Autopilot Orientation can't be set effectively

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3862]
Test Environment
QGroundControl: Daily Build: HEAD:e6e0429 2016-07-20 18:58:20 -0400
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Purpose:
Check if the orientations can be set and effect normally 
Step:
1. Lanuch QGC
2. Connect to SITL
3. Setup -> Sensors -> Sensor Settings -> Autopilot Orientation
4. Select different values
Excepted result:
The vechile's orientation been changed normally, showed in Attitude Indicator and Heading Indicator.
Actual result:
Only the Heading Indicator will show some different. However the changed angle can't match the setting.
More Detail:
one case:
Original angle show in the indicator: 24
Only modify yaw:
yaw angle 
45 299
90 213
135 118
180 24
Only modify roll:
roll angle
90 352
180 26
270 351
Only modify pitch:
pitch angle
90 150
180 24
270 179
In addition:
The items in the drop-down menu are out of order.
![none](https://cloud.githubusercontent.com/assets/1768868/17130577/ce3fda5e-534b-11e6-947e-f21bf8c19bd3.jpg)
![outoforder](https://cloud.githubusercontent.com/assets/1768868/17130579/ce496c4a-534b-11e6-8146-306e11c6626d.jpg)
![pitch90](https://cloud.githubusercontent.com/assets/1768868/17130578/ce467724-534b-11e6-981b-19692bfd6752.jpg)
![roll90](https://cloud.githubusercontent.com/assets/1768868/17130581/ce4d9a0e-534b-11e6-9186-04750e30289d.jpg)
![yaw90](https://cloud.githubusercontent.com/assets/1768868/17130580/ce4b3714-534b-11e6-8f7b-b020b048df41.jpg)

**Comment by DonLakeFlyer** [comment]
QGC has no control over any of this. This is all controlled by the firmware. QGC just sets a single parameter. If changing the parameter persists (AHRS_ORIENTATION), then that is all that QGC is responsible for. Even the list of items (and order) comes from the firmware meta data and QGC is not in control of it.

So if there are any issues here they should reporting on the firmware github.
