### ISSUE TITLE
Survey: Survey area vehicle entry

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3864]
![screen shot 2016-07-26 at 10 28 39 am](https://cloud.githubusercontent.com/assets/5876851/17148373/c6fa45e8-531b-11e6-9ece-19da60f487b6.png)

Currently QGC generates the entry point solely base on the polygon point order. This can lead to the above survey entry point which most likely is incorrect since it leads to a longer initial flight path to enter the area.

The questions:
- What are the rules that determine the survey grid entry point?
- What control does the user have over this?

**Comment by birchera** [comment]
Some thoughts:

Candidate criteria could be
* Minimal mission distance
* Wind direction
* No-fly zones next to polygon (matters for vehicles with nonholonomic constraints)

Only the user has certain pieces of information, e.g. wind direction. This suggests that either we create inputs for all these parameters or give the user full control.

**Comment by DonLakeFlyer** [comment]
For full controls I can see two options:
1) Flip entry/exit points into grid (in the example the vehicle would start the grid from the lower right "S" point)
2) Reverse the direction of the flight lines (in the example this would lead to the flight path of the first parallel line being from North to South instead of South to North)

Anything else?

**Comment by DonLakeFlyer** [comment]
This can be controlled manually now. So good enough for now.
