### ISSUE TITLE
Tell users that changing their airframe resets all parameters except RC config

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#3899]
The params get reset as a different airframe will have different offsets and tuning. We should tell the user that they get reset.

If we already do this then the remaining text needs to be removed as users are apparently not reading it.

**Comment by DonLakeFlyer** [comment]
So say something about calibration values and PID tuning is reset? Anything else?

**Comment by LorenzMeier** [comment]
Just say everything but the RC calibration will be reset to defaults suitable for the new selected frame.
