### ISSUE TITLE
Roll and pitch is not updated on iOS

### ISSUE THREAD

**Issue by staroselskii** [mavlink/qgroundcontrol#3918]
Setup:
- iPhone 5S with iOS 9.3.2
- QGC Version 3.0.0 (2985)
- ArduCopter 3.4-rc1 on Navio 2 (```./arducopter -A udp:<ip>:<port>```)

Screenshots:

![img_5681](https://cloud.githubusercontent.com/assets/4541230/17434410/ef1a4858-5b12-11e6-9ebf-82ae51c98c1c.PNG)
![img_5682](https://cloud.githubusercontent.com/assets/4541230/17434411/f244d2aa-5b12-11e6-8361-480105eb2970.PNG)

As you can see the rotation gets updated. Roll and Pitch axis don't seem to be getting any updates in the HUD whatsoever. Yaw axis is updated as you can see in the pictures below.
I turned all the logging I could find in Console but I don't see anything suspicious.
I guess the data is, of course, delivered to QGC, because yaw is updated.

Anyways, cool work! This is awesome that other than that it works so smooth.

**Comment by DonLakeFlyer** [comment]
Only happens on short screens which use the alternate instrument panel.
