### ISSUE TITLE
The characters in some pages is unclear by default font size

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3923]
Test Environment
QGroundControl: Daily Build: HEAD:2a610ae 2016-08-02 12:05:50 -0700
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the display in every pages are show normally
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Check the charachters in some setup pages
Excepted result:
The characters in every pages all show normally
Actual result:
The characters in some pages is unclear, change the font size bigger, the characters will clear.
![firmware_font](https://cloud.githubusercontent.com/assets/1768868/17470122/5ace53ea-5d6c-11e6-8c32-e5cfb5bc3cdc.JPG)
![power_font](https://cloud.githubusercontent.com/assets/1768868/17470123/5ad4c4aa-5d6c-11e6-8f8c-66148fc8f8be.JPG)
![safety_font](https://cloud.githubusercontent.com/assets/1768868/17470124/5ad69bea-5d6c-11e6-9a5a-18dd98f3d826.JPG)
![sensors_font](https://cloud.githubusercontent.com/assets/1768868/17470125/5adc8816-5d6c-11e6-8877-487586d1eb45.JPG)

**Comment by DonLakeFlyer** [comment]
More windows font weirdness. @NaterGator Hadn't you figure this out when it was out of whack in Airframe?

**Comment by DonLakeFlyer** [comment]
@NaterGator Didn't you fix something like this ages ago on Windows? Don't remember what the fix was.

**Comment by DonLakeFlyer** [comment]
This is the windows positioning problem. Nate has most of this fixed. Full 100% fix scheduled for 3.2 on separate issue.
