### ISSUE TITLE
The information in 'Status Details' is incorrect

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3924]
Test Environment
QGroundControl: Daily Build: HEAD:2a610ae 2016-08-02 12:05:50 -0700
Windows: Windows 8.1 64 Bit Laptop
Purpose:
Check if the status details shows correctly
Step:
1. Lanuch QGC
2. Connect to IRIS+
3. Check the 'Status Dateils' by click widgets drop-down menu
Excepted result:
The information in 'Status Details' should shows according the device data
Actual result:
All data are 0.00
![status details](https://cloud.githubusercontent.com/assets/1768868/17470142/8684974c-5d6c-11e6-8db5-fb178d0aa72e.png)

**Comment by DonLakeFlyer** [comment]
I'll take a look, but that whole widget is going to go away in 3.1. So may just toss it all instead of fix.

**Comment by DonLakeFlyer** [comment]
I pulled this out
