### ISSUE TITLE
Attitude / Heading indicator not functioning

### ISSUE THREAD

**Issue by edigotlieb** [mavlink/qgroundcontrol#3931]
- Setup Mavproxy on my pc to link my RF receiver to my iphone (via wifi) running the App.
- for some reason the  Attitude / Heading indicator isn't working (not responding).
- on my pc running QGC as well its working fine (mavproxy forwarding to loopback and iphone)

**Comment by DonLakeFlyer** [comment]
This is a small screen bug which has been fixed. Hasn't rolled out to new iOS build yet though.
