### ISSUE TITLE
Feature Request: Param search box

### ISSUE THREAD

**Issue by devbharat** [mavlink/qgroundcontrol#3933]
It'd really speed up the parameter search feature if the search box supported 'search as you type' feature (like we have in the search box of analyze widget), or at least execute search when we hit 'ENTER', rather than waiting to click search.

![image](https://cloud.githubusercontent.com/assets/3105122/17619236/49e76196-6084-11e6-9f99-7932d021751a.png)

**Comment by DonLakeFlyer** [comment]
Already implemented in daily builds.
