### ISSUE TITLE
support for OpenLRSng

### ISSUE THREAD

**Issue by gregd72002** [mavlink/qgroundcontrol#3939]
Hi,

Is there currently any support for PPM output, or any support planned in the near future?
To be used in a scenario with manual control over mavlink.

Are we able to plug an OpenLRSng transmitter through a Serial device and pass manual control requests through PPM as opposed to mavlink?

If not, one way of doing it would be through an auxiliary Arudino Micro which serves as a proxy between QGroundControl serial output and OpenLRSng device. Whenever an RC request arrives it would convert it into PPM while proxying all the other messages from QGC to OpenLRSng.

**Comment by DonLakeFlyer** [comment]
Seems like a pretty special case usage pattern as opposed to the standard MANUAL_CONTROL mavlink mechanism.

**Comment by gregd72002** [comment]
Maybe it is. But how do you currently do long range flights with Joystick plugged to QGC?

Isn't the standard long range telemetry radio too slow to send all MANUAL_CONTROL messages?

**Comment by DonLakeFlyer** [comment]
Don't now. Not sure anyone is doing long range stuff via joystick. Seems like at some point it all gets so complicated to setup you might as well just use a regular radio.
