### ISSUE TITLE
Loading params from file does not restore sensor calib params

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#3945]
Current px4 master does not reload all calib params from an exported param file.
Not sure if this is qgc or px4.

Especially tedious in combination with https://github.com/PX4/Firmware/issues/5276

**Comment by DonLakeFlyer** [comment]
Nothing QGC can do about this. This is the firmware preventing this. I believe the optional param stuff comes into play here as well. I think you might be able to work around it by loading the param file multiple times.
