### ISSUE TITLE
Survey: Camera support discussion

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3971]
Current implementation is show below:
![screen shot 2016-08-20 at 12 39 41 pm](https://cloud.githubusercontent.com/assets/5876851/17903518/a2c4b1d4-6920-11e6-8b2f-82c498726f8a.png)
The camera fields are basically a caluclator which calculates a new grid spacing and camera trigger distance each time you change a camera field.

Let use this item to discuss any further feature work here.

**Comment by kellysteich** [comment]
We have some additional features that would enhance the camera survey proposed in #3981 .

One feature is being able to choose between several predefined camera models.
At the moment those are hardcoded, but for the future as a more long term solution, we would image that the user should be able to more easily add new camera models, f.ex by defining them in json files, which are then loaded automatically.
For the moment, it would be great to know what camera models others are using, then we could add them to the hardcoded list.

**Comment by jcooper21** [comment]
Here is some cameras we are using some with IR triggers and some USB.  Nex 5 (PWM IR trigger), Sony A5000, Sony WX500, Sony  Sony A6300, Ricoh GR2

**Comment by Otusbubo** [comment]
We're using the Ricoh GR II and MicaSense RedEdge.  Happy to provide specs on those.

**Comment by DonLakeFlyer** [comment]
@Otusbubo If you can provide specs (all the values in custom camera setup) I can add them as standard cameras. Create a separate issue and put the specs in there.
