### ISSUE TITLE
Cross compiler problem

### ISSUE THREAD

**Issue by x923386210** [mavlink/qgroundcontrol#3972]
I want to cross compile QGC to ARM development board and run. Who has tried it?  I used cross compilation, an error occurred:

Project MESSAGE: Qt version 5.5.1
Project MESSAGE: Linux Imx6 build
fatal: no tag exactly matches '70d225be28330e3123a9e8460bb962f5b32e9735'
Project MESSAGE: QGroundControl version 3.0.0.164 describe Development master:70d225b 2016-08-19 19:10:23 -0700
Project MESSAGE: Release flavor
Project MESSAGE: Using Local QtLocation headers for Qt 5.5.1
Project MESSAGE: Using MAVLink dialect 'ardupilotmega'.
Project WARNING: Skipping support for XBee API (missing libraries, see README)
Project MESSAGE: Skipping support for RT-LAB (unsupported platform)
Project MESSAGE: Including support for speech output
Project MESSAGE: Skipping support for Zeroconf (unsupported platform)
Project MESSAGE: Including support for video streaming
Project ERROR: sdl development package not found

**Comment by DonLakeFlyer** [comment]
This isn't the place to ask questions: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/Support/Support.html
