### ISSUE TITLE
Artificial horizon is half black when in vertical climb or dive

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#3974]
![art_horiz_90](https://cloud.githubusercontent.com/assets/2300221/17916971/3dd05a08-6975-11e6-91f3-267d985dbdaf.png)

**Comment by DonLakeFlyer** [comment]
Mark, thinking about what this should show is making my head hurt a little. The black part should be blue right?

**Comment by NaterGator** [comment]
It should be whatever color the other half is. If you're (unfortunately) pointed straight at the ground the two hemispheres in your view are both ground.

**Comment by DonLakeFlyer** [comment]
Ah, yeah that's it thanks. Couldn't wrap my head around it as I watched it spin around :)

**Comment by kd0aij** [comment]
yes, it's as though you're at the center of a globe with the top hemisphere
blue, and the bottom one green.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Took a quick look at code. But I bet you could fix this in about a minute, whereas it would take me a while to figure out how the code works.
