### ISSUE TITLE
Log Download not downloading large files correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#3977]
I was pulling ArduPilot log files from the Solo from some Survey test runs. When I loaded them in APM2 to look for the camera messages they weren't there. Couldn't figure out why. Then I redownloaded the log using APM2 and suddenly the camera log entries showed up. Have a feeling there is a problem with the log download code somewhere which is corrupting the file somehow. Will need to do some for side by side testing/downloads/compares to validate.

**Comment by NaterGator** [comment]
I just pulled a 400MB log off through log downloader and verified integrity with a SHA256 hash. That is usually how I test the log downloader code; put a large file with a known SHA256 hash on microsd and download it. 

Any chance you kept the original (corrupt) file?

**Comment by DonLakeFlyer** [comment]
I have both versions of the downloaded files. How can I generate the hash for each one?

**Comment by NaterGator** [comment]
I use [hashcheck](http://code.kliu.org/hashcheck/) on windows. If you can pull the microsd and get ground truth that is ideal. It would be useful to know if a whole chunk was skipped, just a bin, etc.

**Comment by DonLakeFlyer** [comment]
Files are different md5 hash doesn't match.

**Comment by NaterGator** [comment]
I was able to repro. A single log_data packet was just missing and all data was shifted to the left by lod_data_payload_len bytes. Looking into cause.

**Comment by DonLakeFlyer** [comment]
I'll be hammering on the unit test as well. I want to be able to get the UT to hit the problem before it gets fixed.

**Comment by DonLakeFlyer** [comment]
What I have for simulated errors:
* No response to request
* Stream stops before all data sent
* Lost packet in middle of stream
* Corrupted packet

And then the file comparer can determine:
* Missing packet
* Corrupt packet

@NaterGator I wouldn't spend a ton of time debugging this manually. My hope is to figure this out automatically with a good unit test.

**Comment by DonLakeFlyer** [comment]
* Dropping random packets doesn't hit the problem
* No response to first chunk request just hangs download (bug needs fixing, but not the corruption problem)

**Comment by DonLakeFlyer** [comment]
> I was able to repro. A single log_data packet was just missing and all data was shifted to the left by lod_data_payload_len bytes. Looking into cause.

@NaterGator Do you still have the corrupted file? How does the position of the shift relate to intra-chunk positioning? Looking for a possible boundary case against position within chunk.

**Comment by DonLakeFlyer** [comment]
Also in which chunk? First, last, middle?

**Comment by DonLakeFlyer** [comment]
In my corrupted file at the point where the files differ from there on out the file contents are all 0's.

**Comment by DonLakeFlyer** [comment]
I can't get a repro of this any more, sigh...

**Comment by NaterGator** [comment]
@DonLakeFlyer it is on the boundary of a LOG_DATA payload number of bytes, but not an even multiple  of chunksize bytes (somewhere in the early-middle of a chunk).

The chunk was around the 150MB mark of the file (out of ~190MB).

**Comment by DonLakeFlyer** [comment]
I can't repro this any more. Moving to 3.2 for some further checking.

**Comment by booo** [comment]
We downloaded several GB of logs in the past. Download works in newer versions.
