### ISSUE TITLE
Stop sending MANUAL_CONTROL messages when joystick is unplugged.

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#3980]
When the joystick is enabled, if the joystick is unplugged, qgc continues to send manual control messages with the last input received before the joystick was unplugged.

Joystick input does not pick up again when the joystick is plugged back in. The only way to regain control of the vehicle after the joystick is unplugged is to restart qgc.

**Comment by DonLakeFlyer** [comment]
@rjehangir Something that will get better with SDL v2?

**Comment by rjehangir** [comment]
Yes. Currently SDL1.2 is used on QGC and cannot detect when a device is removed, so there's no good way to do this.

**Comment by DonLakeFlyer** [comment]
@rjehangir Fixable now?

**Comment by rjehangir** [comment]
@DonLakeFlyer Yes, it should be fixable. This will be taken care of when the hotplugging feature is used. I've got branch I'm working on for that.
