### ISSUE TITLE
QGC - Video stream recorder option

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#3988]
A great addition on the video stream would be to have the possibility of recording the video stream, preferably with a Data overlay (like a OSD, but on QGC)

**Comment by dogmaphobic** [comment]
Repeating here as I had not noticed you had opened an issue for it:

Record the stream is not simple but not impossible either. Recording the composite (video and overlay) is not simple at all. On desktop, you're better off using QuickTime or something like it. On mobile, no clue. I like the idea though...

**Comment by lvale** [comment]
@dogmaphobic Thanks. The Quicktime option, which I use extensively, I believe is only available on Macs. Lazy me that I didn't check recently, but I believe there's an option on gstreamer to save a stream to file, but I don't know how it is now.

**Comment by QuiGon2** [comment]
Hi all,

I have been using 3rd party windows apps for recording the video, so I'm so happy for having this option in QGC. Is it possible to choose other formats for the output video (.avi, .mp4...)? Windows player does not play the output mkv I got this morning... I thing it is also necessary to overlay the navigation data (voltage, depth (ArduSub), and so)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you know about this with the new record video stuff?

**Comment by DonLakeFlyer** [comment]
Available now
