### ISSUE TITLE
Can't creat bluetooth communication to android6.0 device.

### ISSUE THREAD

**Issue by xn365** [mavlink/qgroundcontrol#3990]
bluetooth module baud rate :115200
paired with android6.0 smart phone.
This is console log:
[E]at:0-“Falling back to workaround.”
[E]at:0-"Using found rfcomm channel0."
[E]at:0-"Invoke Resulted with error."
[E]at:0-"Bluetooth error
QBluetoothSocket:ServiceNotFoundError"
[E]at:0-"Workaround failed"

**Comment by DonLakeFlyer** [comment]
Dup of #3583
