### ISSUE TITLE
Feet to metric no round tripping correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4008]
Type in 100 ft to GF_MAX_HOR_DIST and it will roundtrip back to 98.4521... feet!

**Comment by dogmaphobic** [comment]
Imperial feet went up the Matterhorn and got frostbitten...

**Comment by NaterGator** [comment]
This again?! Is something in the path bypassing the fact translators?

**Comment by NaterGator** [comment]
Oh. Here's why:
https://github.com/mavlink/qgroundcontrol/blob/801fdde8e57a04a4b344621cf3809c7b968166af/src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml#L2216

100 feet to meters = 30.48m
((int)30.48) meters to feet = 98.4521ft

**Comment by DonLakeFlyer** [comment]
Whoopsie

**Comment by DonLakeFlyer** [comment]
There is still a problem with the translators not converting back to int for these params.

**Comment by DonLakeFlyer** [comment]
This is fixed now. Translators are only installed in facts which are real numbers.
