### ISSUE TITLE
Arrows to indicate flight direction in mission planning mode

### ISSUE THREAD

**Issue by kellysteich** [mavlink/qgroundcontrol#4011]
We are currently working on a feature that adds direction arrows to the lines connecting the way points in the mission planning mode in order to better visualize the flight direction.
It look like this right now:
![screenshot from 2016-09-02 11-31-12](https://cloud.githubusercontent.com/assets/5629242/18199543/09e9e108-7101-11e6-837a-46890d541984.png)
The plan is to add the same arrow indicators to the survey grid.

We were wondering if there is any interest in us pushing this upstream for the rest of the community?

Also currently we are loading the image of an arrow and adding this to the waypoint lines,does anybody maybe know of a better way of doing this, f.ex something more along the line of a qml object like the MapPolyline used for the waypoint lines?

**Comment by DonLakeFlyer** [comment]
Using an image is probably fine. Other way would be to create your own custom control using Qml Canvas and then managing the positioning yourself.

**Comment by Antiheavy** [comment]
+1 for direction arrows in Upstream

**Comment by booo** [comment]
Direction arrows are implemented.
