### ISSUE TITLE
waypoint labels not displayed

### ISSUE THREAD

**Issue by yota-code** [mavlink/qgroundcontrol#4028]
On my as "fresh-as-possible" compilation of qgroundcontrol, i can see no display (small circles and lines) of my waypoints. Nor the current position of the uav (when there is one)...

![screenshot from 2016-09-07 16-43-34](https://cloud.githubusercontent.com/assets/20285309/18316570/714943de-751b-11e6-8658-723f2b6c7636.png)

How could I help you to solve this if it's an issue,
How could you help me to correct this if it's a mistake :)

ubuntu 16.04
Qt version 5.7.0 for Desktop (64 bits gcc)

**Comment by dogmaphobic** [comment]
Look at the build instructions:
https://github.com/mavlink/qgroundcontrol
Especially the part that says Qt 5.7 does not work:
 * Make sure to install Qt version **5.5.1** NOT 5.4.x, 5.6.x, 5.7.x, etc.
