### ISSUE TITLE
crashing qgroundcontrol

### ISSUE THREAD

**Issue by robert-b** [mavlink/qgroundcontrol#4029]
a simple:
- not sending param request read request (the param list is clickable)
- stop sending hartbeats
  causes to crash qgroundcontrol.

**Comment by DonLakeFlyer** [comment]
Can you please add some more detail to this? Also what version of QGC are you using and on what OS?

**Comment by robert-b** [comment]
windows 8.1 and the development head from the 1st of september.

**Comment by DonLakeFlyer** [comment]
@robert-b Ok, so that's the build you are using. But I need exact steps to reproduce the problem. Like this:
* Boot QGC
* Connect to this type of vehicel running this type of firmware
* Click this in QGC
* Crash

**Comment by DonLakeFlyer** [comment]
Closing until I can get more detail.
