### ISSUE TITLE
Video Downlink doesn't show video from px4flow (config branch).

### ISSUE THREAD

**Issue by akistanov** [mavlink/qgroundcontrol#403]
Video Downlink shows nothing when connected to px4flow with usb. QGC is built from config branch. Old QGC (1.1.0 beta) shows video correctly for the same px4flow.

**Comment by smiron** [comment]
Why was this bug closed? I can still reproduce the bug ...

**Comment by DonLakeFlyer** [comment]
That code has been removed from the product. It will be completely rewritten at some point

**Comment by dogmaphobic** [comment]
I've added some experimental code to display the images. It's now in master. I haven't fully tested as I don't have the hardware for it.
