### ISSUE TITLE
LOG files Time Stamp.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#4037]
It could be great if QGC can take the Time zone offset + Summer Winter time offset from its host system and syncs it to SDLOG_UTC_OFFSET when connected to the UAV.

**Comment by DonLakeFlyer** [comment]
Interesting option

**Comment by tubeme** [comment]
Related to this one: https://github.com/PX4/Firmware/issues/5483

**Comment by DonLakeFlyer** [comment]
All different nwo with automatic save

**Comment by tubeme** [comment]
:) Perfect!
