### ISSUE TITLE
Map: Current master is not centering map on mission when commanded.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4048]
please see: https://youtu.be/Q6rEuC9HRHI
there is no GPS fix, only a test pixhawk with a mission is connected. - map will center to "home"  - but not "mission"

**Comment by DonLakeFlyer** [comment]
@AndKe Can you attach that mission file? I can't seem to repro.

**Comment by AndKe** [comment]
[WP Håkøya test.txt](https://github.com/mavlink/qgroundcontrol/files/500117/WP.Hakoya.test.txt)

Thanks for looking into it..

**Comment by DonLakeFlyer** [comment]
Took a look. First check seems like Qt bug unfortunately. Now to look for workaround. Also going to try 6.2 to see if it make a difference.

**Comment by DonLakeFlyer** [comment]
Found workaround for Qt bug. Need to report bug to Qt.

**Comment by DonLakeFlyer** [comment]
5.8 fixes the bug

**Comment by DonLakeFlyer** [comment]
Working now
