### ISSUE TITLE
No application icon (Linux)

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4073]
There is no application icon, so the generic gray question mark shows up instead.

**Comment by dagar** [comment]
Can you try the AppImage?
https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html

**Comment by probonopd** [comment]
In Qt, do you set an icon for the main window? If you don't, try doing it using `QApplication::setWindowIcon()`.

**Comment by dagar** [comment]
Thanks @probonopd
