### ISSUE TITLE
Tailsitter transition , aileron, elevator, throtttle not responding

### ISSUE THREAD

**Issue by glassfox1981** [mavlink/qgroundcontrol#4079]
dear fellows,
I am using Pixhawk with qgroundcontrol to fly a dual motor tailsitter delta wing.
everything is fine except aileron, elevator and throtttle are not responding to my control.
only if I wait for a moment and somehow the control is regained.
there is no problem to control all the servo without motor running.
I disabled the airspeed. and tried every parameter I could.
as I didn't put the pixhawk 100% levelly in the cockpit,
if I switch from the tailsitter vertical to delta wing levelled ,the VTOL will just roll in the air and crash.
please help
thank you

**Comment by DonLakeFlyer** [comment]
You should be asking these questions to the firmware folks: http://discuss.px4.io. This is not an issue/bug with QGC.
