### ISSUE TITLE
ReferenceError: shortcuts is not defined

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#4084]
QGC master crashes with

```
qrc:qml/QGroundControl/Controls/AppMessages.qml:116: ReferenceError: shortcuts is not defined
```

when trying to open the Settings -> Console view.

**Comment by yzzir** [comment]
Also have this exact error with 3 different versions (AppImage, Compressed Archive, git clone build)

**Comment by dogmaphobic** [comment]
What OS?

**Comment by yzzir** [comment]
Sorry forgot to mention that.  Kubuntu 16.04

**Comment by dogmaphobic** [comment]
I will try with Ubuntu and see if I can see anything weird. Strange that it would "crash" by just defining a hint for which directory to open the file picker.

**Comment by yzzir** [comment]
One thing to mention, I install Qt using the opensource binaries from the Qt website, not from ubuntu's package management repos.

**Comment by dogmaphobic** [comment]
I tried it on Ubuntu 16.04 and could not reproduce the problem. The file picker came up just fine pointing to my "home" directory as it should. Needless to say, Mac OS runs fine too.

Is there anything weird with your "user" account or your "home" directory?

**Comment by bkueng** [comment]
I'm on Fedora, also KDE. It seems to be a bug in Qt, if I use the system's Qt (5.6.2), it works, but fails with Qt 5.5.1.

**Comment by yzzir** [comment]
I was thinking that might be the case, as I am using Qt5.5.1 binary from qt.io on my Kubuntu 16.04 laptop which doesn't work, but it works on my Ubuntu 16.04 desktop when using system qt

**Comment by DonLakeFlyer** [comment]
Likely some missing package on the version of Qt you are using. Hence the readme pushing folks to not use the built-in version but to install a Qt using the online installer. Looks like there are more reason than just what the README says:

```
You need to install Qt as described below instead of using pre-built packages from say, a Linux distribution because QGroundControl needs access to private Qt headers.
```

If you follow the README instructions do things work correctly?
