### ISSUE TITLE
Unknown module(s) in QT: svg multimedia serialport

### ISSUE THREAD

**Issue by RickBlacker** [mavlink/qgroundcontrol#4088]
Hi all.

I downloaded the source. I already had QT installed. Opened up the project, tried to build. I'm getting the error 
**Unknown module(s) in QT: svg multimedia serialport**
Was hoping someone might be able to help me out here.  I searched the net but didn't find anything that was specific to this error.

Thanks for any help.
Rick

**Comment by DonLakeFlyer** [comment]
From the README:

You need to install Qt as described below instead of using pre-built packages from say, a Linux distribution because QGroundControl needs access to private Qt headers.

I'll re-open if it's a real problem.

**Comment by RickBlacker** [comment]
So we can ONLY use QT 5.5.1?

**Comment by DonLakeFlyer** [comment]
At the moment that is correct.
