### ISSUE TITLE
Survey: mission text and droplist box size/text crop

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4093]
Now all mission items are trimmed like this: (tested on two Ubuntu systems)
![screenshot from 2016-10-01 19-32-57](https://cloud.githubusercontent.com/assets/1468842/19015919/eec6c64c-880d-11e6-8abc-af94d93f334d.png)

this anomaly is not seen in QGC settings, parameters, or any other place than mission items.
All text boxes and droplist boxes(camera list) are affected. 
In the waypoint view, when changing a waypoint type -using the "category" droplist is ok. (the droplist with items like "basic, camera, advanced")

This issue seems to be introduced with https://github.com/mavlink/qgroundcontrol/issues/4087

**Comment by AndKe** [comment]
If anyone has any clue as to what causes this, (a property of box or group?)  - I'll be happy to try.

**Comment by DonLakeFlyer** [comment]
Is this on Windows?

**Comment by DonLakeFlyer** [comment]
Oops, sorry. On Ubunut. Hmm.

**Comment by DonLakeFlyer** [comment]
The strange combo box font thing seems to happen more on Windows.

**Comment by AndKe** [comment]
It's important to mention it's not application-wide problem - but limited to "mission items" only.

**Comment by AndKe** [comment]
another clue: something is different between mission&fence vs rally points: 
![screenshot from 2016-11-15 20-20-37](https://cloud.githubusercontent.com/assets/1468842/20320136/1be65e40-ab71-11e6-8963-f85574f497d6.png)
![screenshot from 2016-11-15 20-20-46](https://cloud.githubusercontent.com/assets/1468842/20320140/21c7ed4c-ab71-11e6-940d-30c32391dbfa.png)

**Comment by DonLakeFlyer** [comment]
@AndKe Can you try this again on a daily build and see if it is still there?

**Comment by AndKe** [comment]
It's fine now.  - which commit fixed it ?

**Comment by DonLakeFlyer** [comment]
#4310

**Comment by AndKe** [comment]
@DonLakeFlyer 
Please apply thesame fix(es) to current master, 

![screenshot from 2019-01-07 23-35-16](https://user-images.githubusercontent.com/1468842/50797529-68608200-12d5-11e9-8fa6-8584331c383c.png)

"mission start" item has this issue
"set servo" , "control mount" , and many others, as well as some fields of waypoint.
![screenshot from 2019-01-07 23-41-32](https://user-images.githubusercontent.com/1468842/50797666-ce4d0980-12d5-11e9-8235-c7b984b487cf.png)
