### ISSUE TITLE
Compass Calibration Long Stating Issue

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#4095]
With PX4 and a Zubax GPS it is impossible to have the flight control yawed and the compass facing straight.  If the fllight controller is yawed the compass has to be yawed in the same direction for a proper calibration and flight.

**Comment by DonLakeFlyer** [comment]
Not sure what QGC is supposed to do about this?

**Comment by jcooper21** [comment]
Isnt it a QGC calibration setup issue?

**Comment by DonLakeFlyer** [comment]
Supported orientations come from the firmware. You can set orientations for both the main board and any external compasses (parameters).  All sensor calibration is implemented in the firmware. Not sure how QGC is in control of any of this?

**Comment by jcooper21** [comment]
So this would be a PX4 issue then. ill open an issue there.

**Comment by DonLakeFlyer** [comment]
I think so. Is there a missing orientation you need?

**Comment by jcooper21** [comment]
No thats all good
