### ISSUE TITLE
Icon Man: Icons for Analyze View

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4103]
Both the toolbar button and the buttons inside the view:
<img width="1088" alt="screen shot 2016-10-04 at 5 47 53 pm" src="https://cloud.githubusercontent.com/assets/5876851/19097621/fb0404c0-8a5a-11e6-8d42-fe94271ee8b8.png">

Icons available to mod when this pull goes through: https://github.com/mavlink/qgroundcontrol/pull/4102

src/ui/toolbar/Images/Analyze.svg - Analyze toolbar button
src/AnalyzeView/LogDownloadIcon.png - Log Download button icon
src/AnalyzeView/GeoTagIcon.png - GeoTag button icon

**Comment by dogmaphobic** [comment]
Done in #4183
