### ISSUE TITLE
QGC is not opening 

### ISSUE THREAD

**Issue by anujkumargupta** [mavlink/qgroundcontrol#4105]
Hi i am working ubuntu 14.04 64 bit system i downloaded the daily buid of qgc from its site and isntalled it and also install the additional packages given in github site. But the problem is whenever i start my QGc application is starts with full white background 
![screenshot from 2016-10-04 12 39 31](https://cloud.githubusercontent.com/assets/22234294/19065191/ad18e15c-8a2f-11e6-852a-30d6648373d4.png)

**Comment by narendrakc-path** [comment]
The error log is 

anuj@anuj-vm:~$ cd Downloads/qgroundcontrol/
anuj@anuj-vm:~/Downloads/qgroundcontrol$ ./qgroundcontrol-start.sh 
Settings location "/home/anuj/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"

(gst-plugin-scanner:2431): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsteglglessink.so': /usr/lib/x86_64-linux-gnu/libgstegl-1.0.so.0: undefined symbol: eglDestroyImageKHR
Map Cache in: "/home/anuj/.cache/QGCMapCache300" / "qgcMapCache.db"
qrc:qml/MainWindowInner.qml:311:5: Type FlightDisplayView unavailable
qrc:///qml/QGroundControl/FlightDisplay/FlightDisplayView.qml:17:1: plugin cannot be loaded for module "QtMultimedia": Cannot load library /home/anuj/Downloads/qgroundcontrol/Qt/qml/QtMultimedia/libdeclarative_multimedia.so: (libQt5MultimediaQuick_p.so.5: cannot open shared object file: No such file or directory)
Orphaned log file count 0


Thanks

**Comment by DonLakeFlyer** [comment]
@dagar Any ideas?

**Comment by dagar** [comment]
I guess libQt5MultimediaQuick_p.so.5 is a new dependency.

**Comment by anujkumargupta** [comment]
Hi I tried to clone the code and build using qt5.5.1 and now it works properly 
Thanks

**Comment by dagar** [comment]
I'll still fix this for the Linux users that don't want to compile.

**Comment by CarlOlsson** [comment]
Hi I have the same problem on Ubuntu 14.04, if I download the daily build it doesn't start but if I build from source it works.
![white_qgc](https://cloud.githubusercontent.com/assets/7795133/19220043/8787c2ca-8e24-11e6-8e97-b3f7f235c39a.png)

**Comment by DonLakeFlyer** [comment]
@dagar Any update on the fix for this?

**Comment by dagar** [comment]
Working on a fix.

**Comment by sanderux** [comment]
@DonLakeFlyer is this mergeable?

**Comment by DonLakeFlyer** [comment]
@dagar Should be able to merge when he's ready. Not sure.

**Comment by anujkumargupta** [comment]
Hi 
today i downloaded the latest build but again it asking for some shared library
/home/anuj/Downloads/qgroundcontrol/QGroundControl: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
I tried to locate it also but its not there in my pc
Thanks

**Comment by dagar** [comment]
Ah, new problem already. New issue here - https://github.com/mavlink/qgroundcontrol/issues/4148
I should really add something in the builds to test running the AppImage.

**Comment by misoragod** [comment]
Hi.
I have the similar problem on Ubuntu 14.0.4 when I built from source to use Qt Creator.
I used Qt 5.5.1 and Qt Creator 4.2
<img src="https://gist.githubusercontent.com/misoragod/3e1be74a3142d6e375a639ec8403cc85/raw/ffdf126fa63e2b5d3baefcd6e62ad54716bc07d8/capture2.png" >

**Comment by DonLakeFlyer** [comment]
Use Qt 5.7.1

**Comment by misoragod** [comment]
Hi.
I tried it to use Qt 5.7.1 and then I could solve this problem.
Thanks.
