### ISSUE TITLE
Add Level Horizon calibration to ArduPilot

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4115]
http://ardupilot.org/copter/docs/common-accelerometer-calibration.html

**Comment by DonLakeFlyer** [comment]
@lvale Do you know anything about the cryptic Warning that is on the above doc page?

```Do not perform the press the Calibrate Level button. This function will overwrite your calibration values.```

**Comment by lvale** [comment]
Perhaps this line ?
https://github.com/ArduPilot/MissionPlanner/blob/70fbd9ec075d3b08fd79c78acab9cf0725b7590f/GCSViews/ConfigurationView/ConfigAccelerometerCalibration.cs#L123

**Comment by lvale** [comment]
@DonLakeFlyer Warning removed :)

https://github.com/ArduPilot/ardupilot_wiki/pull/610
