### ISSUE TITLE
QGC not detecting the Snapdragon FC

### ISSUE THREAD

**Issue by anujkumargupta** [mavlink/qgroundcontrol#4120]
Hi i am using snapdragon FC when i connect this board via USB then QGc does not detect it. i installed the toolchain for linux and flsh the ADSP filmware and build my 1st code also using the dev guide of px4.
Is there anything else which i have to do in order to connect the board with QGC.
Earlier i i woked with pixhawk board and there everything works well but now there is a problem with snapdragon board.
Thanks
Your valuable replies will be very helpful for me.

**Comment by DonLakeFlyer** [comment]
I'd ask this question on the Firmware forum: http://discuss.px4.io. 

If you can show it isn't a hardware setup problem we can re-open this. But Issues should not be used for discussion. Just for bugs.
