### ISSUE TITLE
Please could you display correctly custom commands

### ISSUE THREAD

**Issue by Fojtik** [mavlink/qgroundcontrol#4124]
Custom commands are not displayed correctly in the version 3.0.1.

Please see this:
[https://github.com/mavlink/mavlink/issues/525](https://github.com/mavlink/mavlink/issues/525)

**Comment by DonLakeFlyer** [comment]
Working on it. Turned out to be more difficult than I thought it would be. Was hoping to get it done today.

**Comment by Fojtik** [comment]
Perfect, thank you very much for this feature. I can test it, when it will be finished.

**Comment by Fojtik** [comment]
I do not know whether you finished it:
![customwaypoints](https://cloud.githubusercontent.com/assets/2893993/19367567/180287c0-919c-11e6-8df2-c72fe0db9bc5.jpg) Unfortunatelly circle position is not driven by Latitude and Longitude.
Is it possible to fix it.

**Comment by DonLakeFlyer** [comment]
Going to have to wait till 3.2 since it's a large change now. Sorry for taking so long.

**Comment by Fojtik** [comment]
OK, thank you very much for your interest. Please let me know when these points will work - I can test it.

**Comment by DonLakeFlyer** [comment]
I screwed this up again in thinking it was easy change but turned out it was not. And then it got lost until too late for 3.2. I have a new system for marking fixes which needs to go in at the start of a new release so this won't happen again. The Issue tracking this is #3116
