### ISSUE TITLE
futaba sbus not working and detected in qgroundcontrol pixracer flight control

### ISSUE THREAD

**Issue by rezafarokhian** [mavlink/qgroundcontrol#4140]
hi. please help me. my futaba 8fg does not connecting s.bus to pixracer no channel detected in qgroundcontrol

**Comment by DonLakeFlyer** [comment]
This is a vehicle setup problem not a qgroundcontrol problem. You should ask vehicle/firmware questions here: https://gitter.im/PX4/Firmware or here: http://discuss.px4.io
