### ISSUE TITLE
Wrong Firmware Version

### ISSUE THREAD

**Issue by nanthony21** [mavlink/qgroundcontrol#4141]
I'm not sure if this is a QGC problem or a firmware problem. When using QGC to flash the default stable PX4 firmware it says that it will use version 1.4.4 but the vehicle summary page shows that 1.4.1dev is installed.

**Comment by dagar** [comment]
I'm not sure if this is a problem on the PX4 or QGC side, but I'll look into it.

**Comment by dagar** [comment]
It's a problem with the current PX4 stable build. Not sure what yet.

**Comment by dagar** [comment]
Seems like more of a PX4 build system issue.

**Comment by dagar** [comment]
Check stable again once this build finishes - https://travis-ci.org/PX4/Firmware/builds/169102480

**Comment by dagar** [comment]
It's partially fixed now, but displays 1.4.4dev because I added a commit after 1.4.4 to fix it. The next stable release will be correct.
