### ISSUE TITLE
Latest AppImage for linux needs libsdl2-dev

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#4148]
On Ubuntu 16.04, the latest daily AppImage (2015-10-18) gave the following error: 

```
/tmp/.mount_F2ihi7/QGroundControl: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

This fixed it:
```
sudo apt install libsdl2-dev
```

I think this should be fixed in the guide here: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html

**Comment by dagar** [comment]
@julianoes @anujkumargupta - can you try the latest master? http://qgroundcontrol.s3.amazonaws.com/builds/master/QGroundControl.AppImage

**Comment by julianoes** [comment]
Yes, seems to work without again, thanks.
