### ISSUE TITLE
Mavlink inspector: many messages not recognised/displayed.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4149]
Please notice that the 180 (camera feedback) does not even appear.
many more are unrecognised. 

Also, displaying us as exponent is .... less than optimal.

![screenshot from 2016-10-18 10-21-44](https://cloud.githubusercontent.com/assets/1468842/19474665/da1af24c-9530-11e6-97ff-d3cfdb8ed9e5.png)

here is how it's expected to look
![screenshot from 2016-10-18 12-43-33](https://cloud.githubusercontent.com/assets/1468842/19474666/da1e9906-9530-11e6-9e6a-26629d3b9efe.png)

**Comment by DonLakeFlyer** [comment]
There is a bug in the mavlink 2 headers which prevents QGC from getting access to ardupilot message info. Once that is fixed I can pull new mavlink headers and this will start working again.

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/mavlink/issues/639

**Comment by DonLakeFlyer** [comment]
Correct headers are in now
