### ISSUE TITLE
Issue on the parameter missing problem with Copter 3.2.1 firmware.

### ISSUE THREAD

**Issue by bestpest** [mavlink/qgroundcontrol#4151]
After connecting qgc to copter I see warning pop-up that parameters missing from firmware.

**Comment by bestpest** [comment]
![screenshot_2016-10-19-06-09-06](https://cloud.githubusercontent.com/assets/22308951/19501371/2c6f3672-95cf-11e6-920b-7ef8b9878381.png)

**Comment by DonLakeFlyer** [comment]
There is another bug here as well. The ArduPilot branding logo should not show up if it overlaps the toolbar items.

**Comment by DonLakeFlyer** [comment]
Installed Copter 3.2 and the COMPASS_DEV_ID parameters were there.

@bestpest Thought you said you were running Copter 3.2.1? Can you look on the Setup/Summary screen and check firmware version there?

**Comment by bestpest** [comment]
![screenshot_2016-10-21-06-24-30](https://cloud.githubusercontent.com/assets/22308951/19582870/4ae028fc-9762-11e6-9143-8b520327c937.png)
![screenshot_2016-10-21-06-28-42](https://cloud.githubusercontent.com/assets/22308951/19582874/55f097b8-9762-11e6-89ec-af45b23442a9.png)
![screenshot_2016-10-21-06-26-46](https://cloud.githubusercontent.com/assets/22308951/19582873/55ec8eca-9762-11e6-88b2-9de3b2a90e35.png)
![screenshot_2016-10-21-06-26-01](https://cloud.githubusercontent.com/assets/22308951/19582875/55f20058-9762-11e6-93b5-e97d9a50c9c8.png)

**Comment by DonLakeFlyer** [comment]
I think I just fixed this. ArduPilot was sending to fake parameter back with an index of 65536. This was causing some retry times to get out of whack.

**Comment by bikashranjanyadav** [comment]
I have two apm2.8 with two neo7m gps.
in both compass_dev_id  value is zero.( tried both copter 3.2.1 & beta version USING APM PLANNER 2.0)
when connected to qcgroundcontrol says compass_dev_id parameter missing
also, my compass heading is wrong after many attempts

WHY MY COMpASS IS NOT GETTING DETECTED pLZ HELp

**Comment by DonLakeFlyer** [comment]
QGC no longer supports version 3.2. It's too old.
