### ISSUE TITLE
Please remove prompts from QGC shutdown

### ISSUE THREAD

**Issue by clovett** [mavlink/qgroundcontrol#4158]
When I close an app I want it to just fricken close.  Can you stop prompting "There are still active connections to vehicles... blah blah blah" and can you also stop prompting for mavlink log file names.  Just save the mavlink log in a log directory that we an set through a settings dialog.  Hard drives are enormous, no one will mind if you "just do it".  Thanks.

**Comment by DonLakeFlyer** [comment]
There is already an issue in on automatically saving log files without prompting. I don't think closing QGC with an active connection and not warning the user is a good idea. You could be dropping the connection to an active vehicle by mistage. No plans on changing that.
