### ISSUE TITLE
ArduPilot Copter 3.4RC6 repeated landing on Mavlink

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4162]
Latest QGC from master, when opening the Mavlink widget we get this  repeated landing target
<img width="1400" alt="screen shot 2016-10-20 at 21 36 56" src="https://cloud.githubusercontent.com/assets/3130363/19578115/280a2c38-9712-11e6-8ffe-d9ba9557d91d.png">

**Comment by lvale** [comment]
Tridge just told me that it should be solved shortly, so closing :)

**Comment by DonLakeFlyer** [comment]
Not sure about that.
