### ISSUE TITLE
Unknown module(s) in QT: location positioning serialport location-private positioning-private

### ISSUE THREAD

**Issue by RickBlacker** [mavlink/qgroundcontrol#4164]
I know that QGC requires a specific version of QT. The version I have is
Qt Creator 3.5.1
Based on QT 5.5.1 (GCC 5.2.1 20151129, 64 bit)

I don't recall off the top of my head exactly where and how I got it. I don't recall if I got it off the QGC install instructions or not. 

The reason I'm bringing this up is because when I searched for this error, i seen that someone else had been instructed to ensure they were using this version of QT and if so everything should be fine.  However, I'm still getting this error.

**Comment by dogmaphobic** [comment]
I'm assuming you are using a system installed Qt and not the Qt Online Installer as described in the readme file. You need to use that and select (in addition to the regular modules) the source modules as well.

From the readme:
```
You need to install Qt as described below instead of using pre-built packages from say,
a Linux distribution because QGroundControl needs access to private Qt headers.
```

https://github.com/mavlink/qgroundcontrol

Also, if you do have a system installed Qt, make sure to use the Qt Creator from the installer above, and not one from /usr/somewhere.
