### ISSUE TITLE
Rally should be optional via firmware plugin

### ISSUE THREAD

**Issue by rjehangir** [mavlink/qgroundcontrol#4166]
Rally points are currently an optional feature in the Ardu\* firmware, but is not auto detected in the QGC firmware plugin, which can result in error messages if there are missing parameters.

**Comment by DonLakeFlyer** [comment]
Can you tell me what the missing parameters are that are reported? Then I can trigger off of that.

**Comment by rjehangir** [comment]
Hey Don, it's just RALLY_TOTAL.

**Comment by DonLakeFlyer** [comment]
@rjehangir Can you test with this?

**Comment by rjehangir** [comment]
@DonLakeFlyer Yes, this is working! Nice.
