### ISSUE TITLE
MAVLink 2.0 detection doesn't work

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#4178]
QGC should look at the capabilities bitmap in this message: http://mavlink.org/messages/common#AUTOPILOT_VERSION

and switch to 2.0 once it reads MAV_PROTOCOL_CAPABILITY_MAVLINK2

**Comment by dogmaphobic** [comment]
Done. It will come when I push my ULog download code.

**Comment by dogmaphobic** [comment]
Fixed in #4180
