### ISSUE TITLE
The plot interface does not work well when plotting a logfile

### ISSUE THREAD

**Issue by pwbecker** [mavlink/qgroundcontrol#418]
When playing a logfile, the plot interface is shakey:
- When changing playback speed, the scroll rate gets confused, and the data lines disappear off the left
- Its difficult to go to a specific point in the log and plot data in the region of that point
- The Y axis scale sometimes gets confused when turning various data points on and off, resulting in some lines permanently off the top of the chart
- Multiple plots with very different ranges don't play nicely together at all
- Sometimes a single plot jumps around the x-axis, resulting in a criss-crossed mess.  This could occur when adjusting window sizes and rate when playing a log file and switching 'ground time' on and off.

It would be great to be able to see an overview, for e.g. to find a place where the altitude dropped suddenly, and then analyse attitude, throttle etc around that point by switching plots on and off and zooming in and out,  Multiple Y-axis scales are also required - one way is (as per performance analysers) to have multiple horizontal bands in the plot area, echo with its own plot and y scale; another approach is using colour codes to draw multiple y axis scales.

PS: I am using 2.0.0 build 12 for Win 7.

**Comment by DonLakeFlyer** [comment]
This is all going to end up being re-written in Qml
