### ISSUE TITLE
ATT_W_EXT_HDG showing as integer not float

### ISSUE THREAD

**Issue by garethdicker** [mavlink/qgroundcontrol#4181]
The parameter ATT_W_EXT_HDG under Attitude Q estimator shows only 0 or 1 whereas it should show as a float in v2.9.5.

Please change this!

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/blob/4453e4201b7a245cff52beeb38a293161aea4c48/src/modules/attitude_estimator_q/attitude_estimator_q_params.c#L71

It just needs additional metadata like @decimal.

**Comment by DonLakeFlyer** [comment]
This requires a firmware side change not a change on the QGC side.
