### ISSUE TITLE
Missing Mission Parameter for fixed YAW Setting

### ISSUE THREAD

**Issue by tops4u** [mavlink/qgroundcontrol#4185]
It should be possible to enter a fixed YAW Heading for Mission Waypoints. Especially it would be convenient to have a fixed YAW Heading for Survey. I know Survey is in BETA Stage... 

Source of this Request is: 
http://discuss.px4.io/t/heading-fixed-flight-path-for-multicopters/1591/12

**Comment by tops4u** [comment]
@DonLakeFlyer do you think this could be included in future Versions? Especially for Pilots flying missions it would be good to be able to have a fixed (or configurable) Yaw Heading for the Mission Points.

**Comment by DonLakeFlyer** [comment]
This is there now
