### ISSUE TITLE
Master broken: sdl2 development package not found

### ISSUE THREAD

**Issue by birchera** [mavlink/qgroundcontrol#4187]
I can't compile master. I get the message "Project ERROR: sdl2 development package not found"

I assume this has to do with https://github.com/mavlink/qgroundcontrol/pull/4110, but don't know how to solve it.

This is on both Ubuntu 14.04 and 16.04.

**Comment by dagar** [comment]
Try installing libsdl2-dev?

**Comment by birchera** [comment]
That solved it, thanks for the hint!

**Comment by Evanhahaha** [comment]
I also get this message and sdl2 is in installed already. This is on Mac pro

**Comment by Evanhahaha** [comment]
> Try installing libsdl2-dev?

I also get this message and sdl2 is installed already. This is on Mac pro

**Comment by DonLakeFlyer** [comment]
libsld2-dev has nothing to do with OSX. That is just for Ubuntu. OSX builds use an SDL framework which is part of the repo.
