### ISSUE TITLE
px4's simulation

### ISSUE THREAD

**Issue by waterflyfish** [mavlink/qgroundcontrol#4190]
I want to set up a simulator to simulate the px4's flight situation in QGC . Is there anybody working for this and how to do this?

**Comment by nanthony21** [comment]
You have a few options. They all take a little work to set up but they should provide all the functionality that you need. http://dev.px4.io/simulation-sitl.html

**Comment by DonLakeFlyer** [comment]
Sorry, this isn't the place for discussion, just bugs. http://discuss.px4.io
