### ISSUE TITLE
qgroundcontrol's app problem

### ISSUE THREAD

**Issue by waterflyfish** [mavlink/qgroundcontrol#4200]
When I used the android mobile phone to communicate with  the px4 through  serial port ,about twenty minutes later ,the qgroundcontrol will crash.Is there anybody meet this problem,and how to solve it?

**Comment by dagar** [comment]
Is there any error message? Are you connected to a vehicle the entire time?

**Comment by waterflyfish** [comment]
Yes，I connected to the vehicle and use the Release V3.1.About twenty minutes later ,it will crash without any operation

**Comment by jilinggui** [comment]
what time about Version 3.1 release  ？I look forward to it.

**Comment by DonLakeFlyer** [comment]
@uavcam Are you having this problem as well? 

Are you connected to the vehicle the whole time? Does it crash when you are doing nothing with the tablet. Or are you clicking on something and then the crash.

**Comment by pynki** [comment]
@DonLakeFlyer see the gitter private message...

just wait 15 minutes and then it crashes. thats what i can say now. not sure about if the connection - i will find out for you.

**Comment by BrainyBeeLy** [comment]
I think the bug is caused by the serial port. When using the udp connection without this problem.

**Comment by DonLakeFlyer** [comment]
Whomever is seeing this problem, please make sure you are running a daily build and then report back if there is still a problem.

**Comment by waterflyfish** [comment]
It would report the error "eglSwapBuffers failed" when crashed.

**Comment by DonLakeFlyer** [comment]
Are you using a daily build?

**Comment by waterflyfish** [comment]
yes

**Comment by DonLakeFlyer** [comment]
I think I have a repro for this.

**Comment by DonLakeFlyer** [comment]
Should take a few hours for the fix to work it's way out into a daily build. Can you retest tomorrow with a new daily build?

**Comment by waterflyfish** [comment]
ok,I'll give you a reply as soon as possible.
