### ISSUE TITLE
Please show direction & distance to home

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4209]
Please see attached mockup
One green, one red suggestion for possible design that does the job, and is foolproof.

![screenshot from 2016-11-13 19-54-44](https://cloud.githubusercontent.com/assets/1468842/20248070/b496470e-a9dc-11e6-8de1-d1c8b14b4335.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Interested in playing around with visuals for this? I'e added Distance and Heading to Home in the Vehicle FactGroup.

**Comment by DonLakeFlyer** [comment]
You can turn on heading to home in application settings "show additional items in instruments" or something like that. Don't remember name exactly. Distance to home is a configurable value for the values panel.
