### ISSUE TITLE
Make android virtual joystick have option for snap back to center

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#4210]
https://github.com/mavlink/qgroundcontrol/blob/cbee0fb9aab043924b4c5df7bbc3d62685522ff1/src/FlightDisplay/VirtualJoystick.qml#L41

Similar to the gamepad, it would be nice to make the touch joystick interface also have a mode where it snaps back to zero for altitude control mode.

Or, intelligently switch to snap back to zero mode when in altittude control mode and make the interface disappear in auto mode.

**Comment by DonLakeFlyer** [comment]
The changes for auto-center throttle don't really fix this request.

**Comment by HTRamsey** [comment]
Closing in favor of #11590
