### ISSUE TITLE
Vehicle health no available once gone.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4229]
Reproduced by tlog playback:
When QGC loads, I can see 
![screenshot from 2016-11-21 10-44-49](https://cloud.githubusercontent.com/assets/1468842/20477978/858ef684-afd8-11e6-9626-fa1c7e0bf5b2.png)
Once clicked - it's gone:
![screenshot from 2016-11-21 10-46-01](https://cloud.githubusercontent.com/assets/1468842/20477983/8d935064-afd8-11e6-8e4a-e36b7a40e99d.png)

it seems like there is no way to get information about possible bad health from MAV_SYS_STATUS_SENSOR anymore..

**Comment by DonLakeFlyer** [comment]
What do you mean by once clicked? You should be able to swipe the center panel to the right to get it back. That isn't working?

I do see another bug in here which shows in the first image. Vehicle health is the second page, but the page indicator is showing the first page selected. That maybe part of the swipe bug as well if that's what is going wrong.

**Comment by AndKe** [comment]
Wow ! I misunderstood the UI.
Yes, I should have guessed the three dots below were "pages" - but given being on desktop os  , I never considered to use mouse drag on those - I did, however try to click them.  (clicking anywhere within loads "previous" page, usually the first tab (voltage , GS++)   - where I thought I was "stuck"  :)
Also - I did try to click those dots :)

Swiping is just less used on computers, and can be pretty hard on small area on laptop use.

Please make clicking on the "pages" not always load the previous page, but maybe rather "next page"  - and rollover to first from last page.   That would be very intuitive.

**Comment by DonLakeFlyer** [comment]
Yeah I can change that.

**Comment by DonLakeFlyer** [comment]
> Please make clicking on the "pages" not always load the previous page, but maybe rather "next page" - and rollover to first from last page.

Done.
