### ISSUE TITLE
ParameterFactMetaData.xml not updating with firmware

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#4236]
I can't get the parameter ParameterFactMetaData.xml  file to read into qgc. I have bumped the minor version and it is sitting in .config/QGroundControl.org/ParameterFactMetaData.xml I've also tried uploading the new firmware to a board and restarting like usual, but no luck.

**Comment by DonLakeFlyer** [comment]
Turn on ParameterManagerLog to find out which meta data it is pulling and why.

**Comment by jgoppert** [comment]
Logging wasn't working on 3.0.2 release, but ok on daily. The main issue was the minor version number needed to be bumped in Tools/px4params/xmlout.py
