### ISSUE TITLE
qCWarning on MAVLink log command failed

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4238]
Connect to ardupilot vehicle, arm get:
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.
MAVLinkLogManagerLog: Start MAVLink log command failed.

Also these are qCWarning which is bad as well since that will abort the app in debug mode. Isn't there a capability bit which says whether this is supported? Can't run these commands on all vehicles. Even old PX4 firmware will throw this.

**Comment by dogmaphobic** [comment]
Resolved (for the moment) with #4365. Maybe a new issue should be brought up requiring the firmware to announce ulog capabilities.
