### ISSUE TITLE
Grammatical errors: Identifier "FIRMWARE_VERSION_TYPE"

### ISSUE THREAD

**Issue by wx2016** [mavlink/qgroundcontrol#4251]
When I build this project, meet many wrong about FIRMWARE_VERSION_TYPE,for example Grammatical errors: Identifier "FIRMWARE_VERSION_TYPE",I dou't know how to solve it.Could you give me some suggestions.

**Comment by DonLakeFlyer** [comment]
You are getting this from where? I've never seen it before.

**Comment by wx2016** [comment]
When I download this project from git,this problem dad been solved.
