### ISSUE TITLE
Connection issue when QGC is started before USB connection

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4253]
Please see the contradicting information about connection status: (it is not connected)

To reproduce: 
-Start QGC
-connect Pixhawk to USB
result: ![screenshot from 2016-11-26 12-39-44](https://cloud.githubusercontent.com/assets/1468842/20640124/5b631b36-b3d6-11e6-981c-104a4d9c57e5.png)

Now: 
-connect Pixhawk to USB 
-start QGC 
= success

-disconnect Pixhawk
-reconnect Pixhawk to the still running QGC
= same failure.

(tested on Ubuntu, using ArduPlane)

**Comment by DonLakeFlyer** [comment]
I think you're running the version of ArduPlane that reports two different vehicle ids. At boot it sends on id, then eventually it sends the correct id. The connection list is from the bogus vehicle id, then the Vehicle 1 is from the real vehicle id which is eventually sent.

**Comment by DonLakeFlyer** [comment]
--logging:MultiVehicleManagerLog will tell you

**Comment by AndKe** [comment]
You are probably right, I used APM ArduPlane 3.7.0 for testing, last thing I did yesterday was to upgrade to AP 3.7.1 using QGC (which worked fine)

Anyway: the state QGC was in may need some attention, ("disconnect" button was not working, apparently no way to avoid a application restart)
- I am not aware of any way to choose between different systems (multiple vehicles/systems)  - that's not supported, right ?

**Comment by DonLakeFlyer** [comment]
Due to the ArduPilot bug you are now running into: https://github.com/mavlink/qgroundcontrol/pull/4259. Looks like I'm going to need to fix that sooner rather than later.

> I am not aware of any way to choose between different systems (multiple vehicles/systems) - that's not supported, right ?

Yes it is. If you have multiple vehicles you get a drop down to select between them. It's just that #4259 is preventing you from getting at it.

**Comment by DonLakeFlyer** [comment]
I believe tridge fixed the problem in 3.7.1
