### ISSUE TITLE
Replay Flight Data does not work well

### ISSUE THREAD

**Issue by jilinggui** [mavlink/qgroundcontrol#4268]
The log records saved by the qgc can not display the waypoint during playback, and some parameters are not fully loaded,someone can help me?Thanks!

**Comment by DonLakeFlyer** [comment]
At this point log playback only shows vehicle telemetry. Missions and parameters will be flaky.

**Comment by DonLakeFlyer** [comment]
We'll clean all this up on 3.3

**Comment by Antiheavy** [comment]
Missions and parameters would be super useful to have in the ground station log if that is technically feasible.

**Comment by DonLakeFlyer** [comment]
Saying the "Replay does not work well" is quite an understatement! It's pretty horrendous.

**Comment by DonLakeFlyer** [comment]
> Missions and parameters would be super useful to have in the ground station log if that is technically feasible.

Yes it is. And I've been meaning to do it for ages. Non-trivial coding-wise but great feature.

**Comment by DonLakeFlyer** [comment]
I tried support parameter and mission pulling from logs but it turned into a nightmare. For now Replay is working with recent changes.
