### ISSUE TITLE
RC RSSI / Battery Flickering

### ISSUE THREAD

**Issue by tops4u** [mavlink/qgroundcontrol#4288]
When only connected to USB Power and no RC is used the RSSI and/or the Battery Symbol are Flickering (OS X - 3.0.2). Battery is flickering from dark grey to light gray and flipping between 0.0V and N/A. 

Minor Problem - just reporting.

**Comment by DonLakeFlyer** [comment]
What firmware/vehicle?

**Comment by tops4u** [comment]
@DonLakeFlyer It is an AUAV-X2 (FMUv2) with 1.5.1 RC3 when connected via USB without Battery and RC TX switched off (and to note that it is a Spectrum Receiver with 7 single channels, which is connected to a PPM Encoder).

**Comment by DonLakeFlyer** [comment]
Great, thanks for the detail.

**Comment by tops4u** [comment]
Today I observed that when it is flickering there are very short readings of 100% followed by 116%  before showing that there is no RSSI available (which is true). I can't tell you where the Values are coming from. It could as well be a strange behaviour of my PPM Encoder?

**Comment by tops4u** [comment]
This is most probably related to this: https://github.com/PX4/Firmware/issues/6954

So I'm closing this here.
