### ISSUE TITLE
Multiple Video Feed Connections Crash

### ISSUE THREAD

**Issue by SteveJos** [mavlink/qgroundcontrol#4312]
Trying to show the video-feed window in another tab beside the flyview tab ends in crashing QGC with following error:

ASSERT: "m_materialType == MaterialTypeVideo" in file ../prodrone_qgc/src/VideoStreaming/gstqtvideosink/painters/videonode.cpp, line 55

The reason might be a second connection to the same video-feed, which is first created in the flyviewtab. If you disable the code that is showing the video-window in the flyviewtab, the custom video-feed window is working without the crash.

The code in file FlightDisplayView.qml is:

`    FlightDisplayViewVideo {
                anchors.fill:   parent
                visible:        QGroundControl.videoManager.isGStreamer
            }
            //-- UVC Video (USB Camera or Video Device)
            Loader {
                id:             cameraLoader
                anchors.fill:   parent
                visible:        !QGroundControl.videoManager.isGStreamer
                source:         QGroundControl.videoManager.uvcEnabled ? "qrc:/qml/FlightDisplayViewUVC.qml" : "qrc:/qml/FlightDisplayViewDummy.qml"
            }`

**Comment by aleixpol** [comment]
I ended up here because I'm having the same QtGStreamer crash. Good luck!

**Comment by DonLakeFlyer** [comment]
We can really debug crashes in custom code. If you have a crash while running regular QGC then please report it in a new issue.
