### ISSUE TITLE
searching in analyze view hangs QGC

### ISSUE THREAD

**Issue by v01d** [mavlink/qgroundcontrol#4318]
I'm using HIL with PX4 and X-Plane, and during the simulation, If I search a stream name on the analyze view, the search process seems to hang QGC seems I'm getting HIL disconnections.

**Comment by DonLakeFlyer** [comment]
When running HIL+Analyze a lot of stuff ends up on the main ui thread. So not too surprised. I've changed the way filter works such that it doesn't try to filter on every single character you type. It only filters are you stop typing. This should lower the cpu impact quite a bit. This is more a stopgap until we get a new analyze view.
