### ISSUE TITLE
Tile request error

### ISSUE THREAD

**Issue by yzzir** [mavlink/qgroundcontrol#4320]
On Kubuntu 16.04, when I launch QGC i get errors in terminal:

tile request error   "problem with tile image"

One thing to note, I am behind a company proxy, but I have the ca imported to trust the proxy. And i can access the internet with firefox, curl, git, wget.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Is the tile pulling code set up to work from behind a proxy. It doesn't come for free. See QGCFileDownload for proxy setup stuff.
