### ISSUE TITLE
Mavlink inspector widget shows incorrect PWM values for servo_output_raw

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#4321]
The analyze widget shows the correct values, but the inspector mostly shows 1500 for servos 1-4 (standard AERT plane). I have observed (rarely) the correct values displayed very briefly.
(recent PX4/Firmware master: FW git-hash: 8e8336a83f3ceda0e27c3980c2ec2a0f112a7f7b
FW version: v1.5.2-57-g8e8336a (1.5.2 0), 17105408)

**Comment by DonLakeFlyer** [comment]
Looks like a firmware problem:
* ArduPilot stack - good values
* PX4 stack - crap values (both inspector and analyze)

**Comment by kd0aij** [comment]
Do both the inspector and analyze widgets display the same data? If so, what would explain the observed difference in behavior?

**Comment by DonLakeFlyer** [comment]
They show the same data. If you are using an old build you may run into mavlink 2 problems with decoding which may be different between the two. But with latest daily it should be exactly the same. I can't repro the two things showing different values on daily build.

**Comment by kd0aij** [comment]
Thanks, I'll assume the original issue was a mavlink 2 problem on an old QGC build and close this.
