### ISSUE TITLE
Upload pixhawk firmware

### ISSUE THREAD

**Issue by danil2009** [mavlink/qgroundcontrol#4322]
Hi Lorenz,
I want to change my Flight control from APM2.5 to Pixhawk of my Quad-copter, but I had have confuse about select a firmware to upload on Pixhawk? my questions is;
1. What is the differences the firmware from ardupilot px4 [http://firmware.eu.ardupilot.org/Copter/2016-12/2016-12-14-10:12/PX4-quad/] **vs** https://github.com/PX4/Firmware/releases. Which one is stable?

Dida

**Comment by DonLakeFlyer** [comment]
An Issue is not the place to ask questions. Issues are for bugs.

https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/SetupView/Firmware.html
