### ISSUE TITLE
Android - Bluetooth will not connect through Dragon Link

### ISSUE THREAD

**Issue by wallbanger123** [mavlink/qgroundcontrol#4325]
Tower will connect to the flight controller through the Dragon Link v3 Bluetooth telemetry. QGroundControl will not connect.

What can I provide to help?

**Comment by DonLakeFlyer** [comment]
Are you using a Daily build? I think Bluetooth was just fixed.

**Comment by DonLakeFlyer** [comment]
@wallbanger123 Can you install the latest daily build?

**Comment by wallbanger123** [comment]
It works on the PC/Mac versions, but Android (tried on multiple devices) it just crashes.

**Comment by DonLakeFlyer** [comment]
Install the latest android daily build from here: https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.apk. Bluetooth should be working with that build.

The Google Play listing for daily builds is not working correctly and is out of date.
