### ISSUE TITLE
Crash on android when direct usb connection to board

### ISSUE THREAD

**Issue by icesword001** [mavlink/qgroundcontrol#4328]
On android, In the beginning，connection QGC is successful, everything is all right; 
However, after waiting for tens of seconds to minutes, the QGC would Crash; 
I found, debugging is a collapse in the "SerialLink::_readBytes()" class, but the reasons is unknown

[Fatal] 16:03:24.206 ASSERT: "size == 0 || offset < 0 || size_t(offset) >= sizeof(QArrayData)" in file E:\Qt\Qt5.5.1_android\5.5\android_armv7\include/QtCore/qarraydata.h, line 54 File:() Line:(0)
@LorenzMeier

**Comment by DonLakeFlyer** [comment]
Are you using an Android daily build? There was a crash after some amount of time was fixed in Daily.

**Comment by icesword001** [comment]
I use the QGroundControl v3.0.2  package（from github）; 
There are the same problems.

**Comment by DonLakeFlyer** [comment]
3.0.2 is a stable buid not a daily build. To get daily build you need to sign up for the android beta: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html

**Comment by DonLakeFlyer** [comment]
@icesword001 I'll re-open if it is still crashing on a Daily Build.

**Comment by DonLakeFlyer** [comment]
Retested on daily build. Working fine

**Comment by JonReacher** [comment]
@DonLakeFlyer I'm still having this issue on a stable build for months, even to the latest 3.2.2. Haven't ever been able to connect for more than a 10 seconds directly to the board.

**Comment by LorenzMeier** [comment]
@dogmaphobic maybe related to what you found?

**Comment by mhkabir** [comment]
Can confirm that this is still an issue.

**Comment by dogmaphobic** [comment]
I found a nasty bug when QGC receives a message with a message ID > 255. It causes buffer overrun and all things go haywire after that. The behavior is random as the affected places change based on the message and platform. I will push the fix shortly.

**Comment by DonLakeFlyer** [comment]
I can reproduce this. But I'm having probelsm with my tablet where I can't get it to go into wireless debugging mode to be able to catch the crash.

**Comment by birchera** [comment]
We are also experiencing this bug. I tracked it down to happen when clearing the QGCRingBuffer in the serial read functionality. Specifically it seems that [clearing](https://github.com/mavlink/qgroundcontrol/blob/master/libs/qtandroidserialport/src/qserialport_p.h#L194) the remaining first QByteArray in the buffers list produces the error. However, no attempt to guard it with the obvious checks solved the issue.

I attached the stack trace below.

[SerialStackTrace.txt](https://github.com/mavlink/qgroundcontrol/files/1231826/SerialStackTrace.txt)

**Comment by DonLakeFlyer** [comment]
@birchera I can repro this, but I haven't been able to get it into the debugger. Are you using QtCreator to debug?

**Comment by birchera** [comment]
Normally I do, but without the cable available, I also could not yet attach the debugger. So I only have the adb shell at hand.
