### ISSUE TITLE
3DR radio firmware: unable to put into command mode

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4335]
```Plug in your device via USB to start firmware upgrade.
Found device: SiK Radio
Putting radio into command mode
Error: Unable to put radio into command mode
Upgrade cancelled
------------------------------------------
If upgrade failed, make sure to connect directly to a powered USB port on your computer, not through a USB hub. Also make sure you are only powered via USB not battery.
```

tested with several radios, 3DR v2 radios, SiK 1.9.

The problem does not show on 3DR v1 radios, (using FTDI cable)  - very strange...

**Comment by AndKe** [comment]
unable to reproduce reliably anymore, closing for now

**Comment by DonLakeFlyer** [comment]
Radio upgrade can be a bit flaky. Something like 5-10% failure rate on getting the radio into the right mode. I was never able to figure out a 100% reliable way to make it work.

**Comment by AndKe** [comment]
in your experience, is there a difference between v1 and v2 radios (there
should not be)  , I did not reflash that many, simply because I am using
en/decrypting firmware, and need to flash back later.
-I might compare a few applications/methods using a logic analyzer, that
should reveal any difference.

**Comment by DonLakeFlyer** [comment]
Not sure. Never looked at it in that level of detail.

**Comment by blandry** [comment]
I know this is old but if someone stumbles on this, try turning off the other radio (ie the one probably on your drone).

**Comment by AndKe** [comment]
this has been fine for a long time now, the real remaining issue now is:
https://github.com/mavlink/qgroundcontrol/issues/4336

**Comment by blandry** [comment]
I believe you. But it just happened to me (perhaps on an old radio) so I'm documenting what worked for me

**Comment by DonLakeFlyer** [comment]
> I know this is old but if someone stumbles on this, try turning off the other radio (ie the one probably on your drone).

Interesting. I wonder if this really fixed the problem. I've found that flashing will fail to put into command mode intermittently at a low failure rate. I've never been able to make it work 100%. Did you have 100% failure until you did this?

**Comment by PaulStubbs** [comment]
I get this error in QGroundControl (Unable to put radio into command mode) when one of the 2 radios is already plugged in. Make sure both radios are unplugged before upgrading the firmware.

**Comment by myself248** [comment]
Just a data point for anyone else reading this: Flashing the drone-side radio may succeed or fail depending on which USB-UART adapter you're using! 

I had nothing but frustration with both CP2102 and CY7C6521x adapters, despite confirming with an oscilloscope that everything seemed to be talking appropriately. Got the "unable..command mode" error every time. Switched to a name-brand FTDI, and it just worked.

I'm not sure if QGC is doing something weird with the UART, but if there's interest I could try to narrow it down. (QGC 4.0.6 on Ubuntu 18.04.4)

**Comment by danylevskyi** [comment]
I just switched TX and RX pins and it worked for FT232RL.
RX -> RX
TX -> TX

**Comment by MiangChen** [comment]
> I just switched TX and RX pins and it worked for FT232RL. RX -> RX TX -> TX

This is helpful， thanks
