### ISSUE TITLE
Clicking on QGC icon twice displays an empty white screen

### ISSUE THREAD

**Issue by samacumen** [mavlink/qgroundcontrol#4344]
I thought to report this issue as well. Clicking on the top-left QGC (Q) Application settings icon twice makes the screen go white/blank and non-responsive. The user needs to click on some other icon (e.g. Navigation map icon) and then go back to the (Q) Application settings.  Don't know what this means, but guess it is an issue, even though minor it may be.

Click on the (Q) Application settings icon:
![normal_screen](https://cloud.githubusercontent.com/assets/1699546/21464617/995378d4-c982-11e6-960c-4132352d261c.png)

Click again on the (Q) Application settings icon:
![white_screen](https://cloud.githubusercontent.com/assets/1699546/21464592/98fb9624-c981-11e6-8f67-f1957b1edd7d.png)

I haven't tested this on a tablet which may be more sensitive to this happening, but this occurs on Linux (Ubuntu). But guess its' a general issue.

**Comment by DonLakeFlyer** [comment]
Should already fixed in latest daily builds.

**Comment by DonLakeFlyer** [comment]
Reopen if not

**Comment by samacumen** [comment]
Sure, thanks. I will check it with the latest build and get back if not.
