### ISSUE TITLE
QGC says found device Pixhawk when flashing Pixracer

### ISSUE THREAD

**Issue by CarlOlsson** [mavlink/qgroundcontrol#4348]
Just flashed my Pixracer and QGC tells me that it found device "pixhawk"
![screenshot from 2016-12-25 23 10 40](https://cloud.githubusercontent.com/assets/7795133/21473049/a8631836-caf7-11e6-97a8-510325fad662.png)

**Comment by DonLakeFlyer** [comment]
Pixhawk is the generic name for all Pixhawk open-hardware spec boards. The manufacturer naming varies quite a bit: Pixhawk, Pixhawk 2, Pixracer, Pixhack, HKPilot32, AeroCore, ... They are all Pixhawk style boards.
