### ISSUE TITLE
Compass calibration ArduPilot

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4371]
Latest QGC build on MacOS. ArduPilot Copter 3.4.3 running on PixRacer with external GPS+Compass unit.

Onboard calibration doesn't appear as option

Only 2 compasses available (not 3)

adding the QGC log when I tried to run the compass cal.

No display, but was beeping like it was using the onboard routine.

<img width="1177" alt="screen shot 2016-12-31 at 00 55 55" src="https://cloud.githubusercontent.com/assets/3130363/21575006/d01f4a90-cef6-11e6-9fc1-ba79ff7cbe3b.png">
<img width="1029" alt="screen shot 2016-12-31 at 00 58 42" src="https://cloud.githubusercontent.com/assets/3130363/21575007/d04f1bc6-cef6-11e6-9c4a-0068589677b2.png">
[pixracer_compass_cal_apm343.mavlink.zip](https://github.com/mavlink/qgroundcontrol/files/679389/pixracer_compass_cal_apm343.mavlink.zip)

**Comment by DonLakeFlyer** [comment]
There aren't options to do onboard or offboard. It's automatic based on what the vehicle supports. Let me try mine again.

**Comment by DonLakeFlyer** [comment]
![screen shot 2016-12-30 at 5 29 12 pm](https://cloud.githubusercontent.com/assets/5876851/21575064/813d4d46-ceb5-11e6-9f46-955e0b7930c6.png)

That looks like 3 compasses. The numbering is wrong though. Should be 1, 2, 3.

**Comment by DonLakeFlyer** [comment]
Works for me. When you click Ok you get this:
![screen shot 2016-12-30 at 5 29 50 pm](https://cloud.githubusercontent.com/assets/5876851/21575072/b546cb30-ceb5-11e6-8613-39c338f3a832.png)

No fancy images. Just tells you to rotate randomly.

**Comment by lvale** [comment]
ok. Same thing here, except that mine doesn't show the 3rd compass :)

**Comment by DonLakeFlyer** [comment]
Yeah I only saw two at first as well!
