### ISSUE TITLE
Android tablet & phone differences & issues:

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4385]
On phone:

![phone](https://cloud.githubusercontent.com/assets/1468842/21595208/985ca3be-d12b-11e6-8f0b-b26be5112e58.png)

1:  there is no "gear" for configuring the widgets, whole Altitude, Ground speed, area triggers that, (easy to touch by accident) 

2: given the limited screen area, maybe Ardupilot logo should be smaller, and the top bar used for something else - like half the height of AHI and compass.

3: there is no "vibe" , or , more importantly (?) vehicle health data:   tablet got it:

![tablet health](https://cloud.githubusercontent.com/assets/1468842/21595256/55265cec-d12c-11e6-9098-d2be8d1bf574.jpg)

4: on tablet;  vibe is showing, but clipped:
![tablet vibe](https://cloud.githubusercontent.com/assets/1468842/21595268/712d3794-d12c-11e6-898e-ddb0bf51370a.jpg)

5: on tablet;  the configuration "gear" is visible, but does nothing, there is no way to display additional data.

6: maybe the best solution is to let phone have tablet's layout - after all, the text color is not always readable based on background. 

7: in both cases, the white area, text area , could be more translucent.

**Comment by DonLakeFlyer** [comment]
Just bugs and unfinished work. Functionality is now the same.
