### ISSUE TITLE
Multi-vehicle: disconnect from selected vehicle, selector disappears

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#4392]
When connected to 2 vehicles (A and B) and having vehicle A active.
if vehicle A disconnects the vehicle selector disappears and there is no way to switch to vehicle B

**Comment by DonLakeFlyer** [comment]
Are you running a daily build? Should already be fixed.

**Comment by DonLakeFlyer** [comment]
Wait this is different. When Vehicle A disconnects it will automatically switch to Vehicle B and the selector will go away because there is only one vehicle. Just tested this and it is doing the right thing?

**Comment by sanderux** [comment]
`when it looses connection it doesnt. It shows the connection lost screen with a disconnect button.

**Comment by sanderux** [comment]
It might be an older version, its a daily but not todays :)

**Comment by DonLakeFlyer** [comment]
Should have been fixed on Nov 30: https://github.com/mavlink/qgroundcontrol/pull/4265

**Comment by sanderux** [comment]
I'll check, maybe my version is old. Sorry

**Comment by DonLakeFlyer** [comment]
Daily builds will have date in title bar.

On Jan 4, 2017, at 11:32 AM, Sander Smeets <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll check, maybe my version is old. Sorry
