### ISSUE TITLE
basic companion (rPi) gpio commands from qgroundcontrol?

### ISSUE THREAD

**Issue by mrdown11** [mavlink/qgroundcontrol#4396]
I would like to see the option in qgroundcontrol to control the gpio pins of the companion rpi (say, I want gpio4 to be output, and be set to high). I think this allows for a lot of control over additional hardware on any vehicle with a companion rPi. This way all control is integrated in qgroundcontrol, so you don't need something separate to for instance turn on a light..

**Comment by DonLakeFlyer** [comment]
That's need to be done by the firmware on the vehicle doesn't it? QGC isn't in control of that sort of thing.

**Comment by mrdown11** [comment]
You are probably right, closing the issue
