### ISSUE TITLE
iOS: QGC crashes when connecting through wifi

### ISSUE THREAD

**Issue by CarlOlsson** [mavlink/qgroundcontrol#4406]
After updating to the latest QGC for iOS the app crashes as soon as you connect a vehicle to a pixracer over wifi.
I have tried with an iphone 6 and an ipad 4 both running iOS 10

**Comment by DonLakeFlyer** [comment]
Thanks for the report. Let me take a look.

**Comment by DonLakeFlyer** [comment]
Damn, I can repro as well.

**Comment by dogmaphobic** [comment]
It runs here. I assume this is the "release" version (not the TestFlight)?

**Comment by DonLakeFlyer** [comment]
I found it.

**Comment by dogmaphobic** [comment]
Where?

**Comment by DonLakeFlyer** [comment]
Vehicle::_updatePriorityLink is fully #ifdef'ed out on iOS due to NO_SERIAL_LINK. But only the serial link part of that should be out. Fallback to first link should still be in.

**Comment by dogmaphobic** [comment]
Are you fixing it or should I? How to add it back to Stable_V3.1?

**Comment by DonLakeFlyer** [comment]
Once master goes through I'll move it to Stable_V3.1 and I'll move the tag and you'll need to drop Stable and TestFlight again.

**Comment by dogmaphobic** [comment]
Yeah, that came in with #4349. That whole multiple link is voodoo to me :P

**Comment by DonLakeFlyer** [comment]
Yeah I knew I'd break something with that one. Way too much change to come clean.

**Comment by CarlOlsson** [comment]
Awesome now it works, thanks!

**Comment by DonLakeFlyer** [comment]
Thanks for the quick bug report @CarlOlsson
