### ISSUE TITLE
HDOP/VDOP values not updated in QGC MainToolBar: GPS Status

### ISSUE THREAD

**Issue by samacumen** [mavlink/qgroundcontrol#4412]
I would like to bring to your notice that the hdop/vdop is not getting updated in QGC in MainToolBar display
I checked that in the stable branch v.3.1.1 the GPS based changes were moved from MainToolBar.qml to MainToolBarIndicators.qml, and also some re-arrangement and code clean up has occured.

Tried to simulate this using HIL mode, did not seem to update.

Please see the image below:

![hdop](https://cloud.githubusercontent.com/assets/1699546/21771648/781f9edc-d688-11e6-902a-8787330eb42f.png)

**Comment by DonLakeFlyer** [comment]
Tested using a real vehicle with both 3.1.1 and master and it's working fine. If you are getting 0's then most likely the vehicle is not sending the values across. Check using mavlink inspector (Widgets/mavlink inspector). You should see this:
![screen shot 2017-01-09 at 10 19 07 am](https://cloud.githubusercontent.com/assets/5876851/21777806/6543ba1a-d655-11e6-8a49-d02ac6600c64.png)

hdop and vdop are in the eph and epv values.

**Comment by samacumen** [comment]
Thanks @DonLakeFlyer for testing this. I did not seem to have the latest firmware for the pixhawk. It works now, you may close the issue.
