### ISSUE TITLE
Increase Geotag Accuracy

### ISSUE THREAD

**Issue by saitej09** [mavlink/qgroundcontrol#4416]
Hi I have tried using the ExifParser. There is a loss in accuracy of about 100 cm in conversion from decimal lat/lon to dms and writing to imagebuffer.

Can you explain how to increase the accuracy?

Relevant code:

`
gpsData.readable.extendedData.gpsLat[0] = abs(static_cast<int>(coordinate.latitude()));
    gpsData.readable.extendedData.gpsLat[1] = 1;
    gpsData.readable.extendedData.gpsLat[2] = static_cast<int>((fabs(coordinate.latitude()) - floor(fabs(coordinate.latitude()))) * 60000.0);//gives lat min
    gpsData.readable.extendedData.gpsLat[3] = 1000;
    gpsData.readable.extendedData.gpsLat[4] = 0;
    gpsData.readable.extendedData.gpsLat[5] = 1;
    gpsData.readable.extendedData.gpsLon[0] = abs(static_cast<int>(coordinate.longitude()));
    gpsData.readable.extendedData.gpsLon[1] = 1;
    gpsData.readable.extendedData.gpsLon[2] = static_cast<int>((fabs(coordinate.longitude()) - floor(fabs(coordinate.longitude()))) * 60000.0);
    gpsData.readable.extendedData.gpsLon[3] = 1000;
    gpsData.readable.extendedData.gpsLon[4] = 0;
    gpsData.readable.extendedData.gpsLon[5] = 1;
`

Thanks!!

**Comment by DonLakeFlyer** [comment]
@birchera Andreas?

**Comment by birchera** [comment]
The current rational format is (ddd/1,mmmm/1000,0/1) and has an accuracy in the order of <2m

If we want to increase accuracy we could go for (ddd/1,mm/1,ssss/1000). This would bring us to sub cm accuracy. Such accuracy is only beneficial if you have a PPK/RTK device.

@saitej09 what are your requirements?

**Comment by saitej09** [comment]
@birchera 

Hi ..
We have the exact same requirements. RTK/PPK device

**Comment by birchera** [comment]
I can propose a patch. This week will be difficult, but next week should be possible.

**Comment by saitej09** [comment]
@birchera 

Sure!! Thanks. It will be great if u can give some hints and I too can try from my side.

**Comment by saitej09** [comment]
@birchera  any update on the patch ?
Thanks!
