### ISSUE TITLE
Support GPS_FIX_TYPE enum

### ISSUE THREAD

**Issue by WickedShell** [mavlink/qgroundcontrol#4419]
Ardupilot is moving to reporting fix types as per the mavlink GPS_FIX_TYPE enum, which means GPS status of 5 which was RTK is now RTK Float, 6 is RTK Fixed, and 7 is static. I'm not sure if any of the UI needs to change to reflect that support.

**Comment by DonLakeFlyer** [comment]
Missing 7:Static
```
{
    "name":             "lock",
    "shortDescription": "GPS Lock",
    "type":             "uint32",
    "enumStrings":      "None,None,2D Lock,3D Lock,3D DGPS Lock,3D RTK GPS Lock (float),3D RTK GPS Lock (fixed)",
    "enumValues":       "0,1,2,3,4,5,6",
    "decimalPlaces":    0
},
```
