### ISSUE TITLE
QT Build error on ubuntu 16.04

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#4423]
After following instructions:
> error: Unknown module(s) in QT: location positioning qml quick quickwidgets svg serialport location-private positioning-private

**Comment by sanderux** [comment]
@DonLakeFlyer do you know how to solve this so i can update the docs?

**Comment by DonLakeFlyer** [comment]
YOu installed your own copy of 5.5.1? Seems like you are building with the Ubuntu version of Qt.

**Comment by sanderux** [comment]
Hm, i did download QT 5.5.1 as per the manual but i think i might have overwritten it with an apt-get i did to solve another problem resulting from an older version being present on my machine.
I'll try again.
