### ISSUE TITLE
Adding support for px4fmu-v4pro

### ISSUE THREAD

**Issue by klopezal** [mavlink/qgroundcontrol#4433]
Hello, could you add support for the upcoming px4fmu-v4pro? So we can get the very nice automatic connection feature.  New PID/VID as in Nuttx config are : USB\VID_26AC&PID_0013. Thanks!

**Comment by DonLakeFlyer** [comment]
Does this run the exact same firmware as other V4 boards? Or is there a different set of firmware builds for it?

**Comment by DonLakeFlyer** [comment]
Does the bootloader return this for board id:
    static const int boardIDPX4FMUV4 = 11;   ///< PX4 V4 board, as from USB PID

**Comment by klopezal** [comment]
No it is a different firmware (the processor is STM32F469), the target is px4fmu-v4pro. Board ID is  [13](https://github.com/PX4/Bootloader/blob/master/hw_config.h#L229), but is different from USB PID (0x0013)!
