### ISSUE TITLE
PlayUAVOSD: Persistent problem.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#4449]
Hello,

We had flown our PlayUAVOSD with older versions of QGC and PX4. We connect the telemetry to the TELEM 2 port and the system param sys_companion to OSD 57600
But when we connected to the QGC 3.1.1 and px4 1.5.3 it gives continues errors:

![osd problem 1](https://cloud.githubusercontent.com/assets/12617619/22033752/64646164-dcf2-11e6-84af-0c359ab56b09.png)

![osd problem 2](https://cloud.githubusercontent.com/assets/12617619/22033761/6b011bde-dcf2-11e6-8b8f-799085fa90c8.png)

The Telemetry on the OSD is working perfect. The horizon the data is on the video. So the PlayUAVOSD is receiving the data.

May be it is on the QGC side.

Here is the log I get with DebugView++ making a --logging:full while receiving this error.

https://drive.google.com/file/d/0B5qO0rf9mnFPaXNPSlk4R1EtTUE/view?usp=sharing

**Comment by tubeme** [comment]
I saw this from Dec 2016.

http://en.playuav.com/question/45

**Comment by NaterGator** [comment]
Fixed in PX4 firmware: https://github.com/PX4/Firmware/commit/1c42cea28e6e09c75ed2c8ab5c012ee4465f9ffb

**Comment by tubeme** [comment]
Thanks @NaterGator Maybe it has something to do with the OSD functionality. The OSD reads the mission from the px4 and then has a map for the mission. So probably they did not follow some Mavlink rules or sth.?

What can I write to them in order to fix the problem? They can make correction to their code as well.
