### ISSUE TITLE
Qgroundcontrol 3.1.2 will not replay telemetry log files

### ISSUE THREAD

**Issue by Kjkinney** [mavlink/qgroundcontrol#4464]
https://drive.google.com/file/d/0ByGQI8gP4hzqYjZQWGg2VHZ1aHc/view?usp=sharing

here is a link to the file I am trying to play. For some reason it shows a very large amount of time. I have tested this file on older versions of qgroundcontrol and it works just fine.

![screenshot](https://cloud.githubusercontent.com/assets/24501673/22230214/ef7faa0c-e1a1-11e6-83c6-1ec8cfa69cd3.PNG)

**Comment by Kynos** [comment]
Same here with 3.1.3, .mavlink file attached. 

Just a wild guess: might be caused by a non-valid GPS time (this ia a short indoor flight).

[disarmed.zip](https://github.com/mavlink/qgroundcontrol/files/842574/disarmed.zip)

**Comment by DonLakeFlyer** [comment]
This is working now
