### ISSUE TITLE
Custom widget value

### ISSUE THREAD

**Issue by altodrone** [mavlink/qgroundcontrol#4475]
I've build mavlink for a custom message, following your tutorial everything works well. Now I would read that value using a gauge in a widget. I've edited a exsiting qml dashboard and I have loaded through custom command loading widget with no problem. The last step is to read mavlink message and transfer value to widget. In my qml file there is the "value:" parameter setting it to a fixed value the qgrondcontrol widget indicates correctly, how can i set qml to read the value from mavlink. 
Thanks

**Comment by DonLakeFlyer** [comment]
Custom command widgets only have access to parameters. They don't have access to mavlink message data. So this is not possible using a custom command widget. It would only be possible with some non-trivial modifications to the QGC code.
