### ISSUE TITLE
Sensors show green but preflight fails

### ISSUE THREAD

**Issue by CarlOlsson** [mavlink/qgroundcontrol#4478]
Daily build on Linux.
The sensor tab shows all green but I get critical messages that preflight fails due to sensors. Is this as it should be?

![screenshot from 2017-01-28 12 46 07](https://cloud.githubusercontent.com/assets/7795133/22396362/11558412-e558-11e6-9e82-c47a8cd4476c.png)

**Comment by DonLakeFlyer** [comment]
QGC can only tell you if you have calibrated your sensors or not. There are many other problems which can cause you to not be able to fly with respect to complaints about the sensors even after they have been calibrated. Unfortunately QGC doesn't really have access to that information so the best you get I'm those cases is error message from the vehicle which QGC shows you.
