### ISSUE TITLE
MAVLink 2.0 messages appearing in inspector but not analyze view

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#4479]
![image](https://cloud.githubusercontent.com/assets/473772/22396428/5d800730-e527-11e6-90b3-6fbcc4536008.png)

This doesn't make mush sense to me. I must be missing something obvious.

**Comment by mhkabir** [comment]
I can confirm this. The messages in the v2 space aren't coming up in plots.

**Comment by mhkabir** [comment]
Fixed here : https://github.com/jgoppert/qgroundcontrol/commit/ff3b9727c9077fb1777d218eff02c4352187f738
