### ISSUE TITLE
Same version firmware update should overwrite existing meta

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#4485]
When developing firmware we are changing params a lot. It seems we have to delete ~.config/QGroundcontrol* each time so it will upload the new data. If the version numbers match it seems it won't update. The behavior  I think should be that if the uploaded version number is >= current it should update.

**Comment by jgoppert** [comment]
I think the related logic is here: https://github.com/mavlink/qgroundcontrol/blob/master/src/FactSystem/ParameterManager.cc#L1095

We maybe need to invalidate the cache if a firmware file is uploaded with a the same version as a file in cache.

**Comment by DonLakeFlyer** [comment]
On the surface this seems like an ok change. Need to think a little more to make sure,

**Comment by DonLakeFlyer** [comment]
Supported now. But will be replaced by COMPONENT_INFORMATION support
