### ISSUE TITLE
Analyze view MAVLinkDecoder only supports MAVLink 2.0 msgid's <= 512

### ISSUE THREAD

**Issue by jgoppert** [mavlink/qgroundcontrol#4489]
Currently ui/MavlinkDecoder.cc, which is used for  Analyze view represents the mavlink messages space using an array. Messages are decoded and inserted into the array index that matches the msgid. What we need to switch to in order to support all mavlink msgids, which go into the 10,000's, is a dictionary instead of an array.  To be Qt friendly I think we should use QMap: http://doc.qt.io/qt-4.8/qmap.html.

**Comment by DonLakeFlyer** [comment]
Fixed
