### ISSUE TITLE
auto file name for datalog

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4494]
Feature request:

When Qgc prompts to save Flight Data Log it would be neat to populate a default file name based on the system clock similar to this format:
QGCdatalog-YYYY-MM-DD-HH-MM-SS-xx.mavlink

This way a lazy user can just hit save (or Enter) and is less likely to hit cancel (..looks at self..).

![image](https://cloud.githubusercontent.com/assets/12117027/22485968/343fcaf6-e7cd-11e6-873f-2c5972a9e992.png)

**Comment by dagar** [comment]
And optionally always save them. https://github.com/mavlink/qgroundcontrol/issues/3112

**Comment by NaterGator** [comment]
Would be even more appropriate to try and scan the logfile for a valid time signature and use _that_ time to set the filename.

**Comment by Antiheavy** [comment]
Optionally always save them would be best!  Although I would choose to start the log upon autopilot connection not just upon arm.  There is often lots of important pre-flight data recorded prior to arming when trying to troubleshoot a problem remotely.
