### ISSUE TITLE
Parameter non default color

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#4500]
![qgc_color_non_default](https://cloud.githubusercontent.com/assets/14769636/22508048/8835b308-e888-11e6-8378-dfd77e1f984f.png)
I don't think that black on dark grey is a very good choice ;)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Most likely related to your recent palette changes?

**Comment by dogmaphobic** [comment]
I only changed one color. The yellow of the "Active Button" is now more subdued. I will check this and see what's going on...

**Comment by DonLakeFlyer** [comment]
Hmm, looking at code this should be warningText color from palette which is unrelated.
