### ISSUE TITLE
Flight mode menu pops up in wrong place on Android

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#4509]
Current master has the flight mode menu popping up on the bottom of the screen instead of where you touched the QGCLabel with the current mode:

![screen](https://cloud.githubusercontent.com/assets/749243/22593757/251c06ca-e9ee-11e6-892d-3faa789221c9.png)

**Comment by DonLakeFlyer** [comment]
Very strange. I thought I had screwed this up with some other toolbar stuff I did. But I don' think I touched this part. Works fine on Mac which is so odd.

**Comment by DonLakeFlyer** [comment]
As far as I can tell this is a Qt android bug. All Menu qml element show up in the wrong place. They are supposed to show up right where you clicked. There is no control to position them. All you do is call Menu.popup().

**Comment by DonLakeFlyer** [comment]
Qt bug: https://bugreports.qt.io/browse/QTBUG-60151

**Comment by DonLakeFlyer** [comment]
Qt will fix it when they fix it
