### ISSUE TITLE
landing waypoint default altitudes

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#4522]
For PX4 default landing altitudes should currently be 0m relative for FW, MC, VTOL (including VTOL_LAND). I believe this is the case for Ardupilot as well.

https://github.com/mavlink/qgroundcontrol/pull/4471#issuecomment-277574248

**Comment by DonLakeFlyer** [comment]
This exposes a larger issue in that when you change an item from one command to another the defaults for the new command are not applied.

**Comment by DonLakeFlyer** [comment]
This is fixed now
