### ISSUE TITLE
Issue with same system id as QGroundControl

### ISSUE THREAD

**Issue by abencomo** [mavlink/qgroundcontrol#4523]
I recently installed [QGC v3.1.2](https://github.com/mavlink/qgroundcontrol/releases/tag/) and used it to upload the [PX4 v1.6.0rc1](https://github.com/PX4/Firmware/releases/tag/v1.6.0rc1) into the [Pixhawk](https://store.mrobotics.io/Genuine-PixHawk-Flight-Controller-p/mro-pixhawk1-minkit-mr.htm). Then today, I installed QGC v3.1.2 in a different machine, changed the SYS_COMPANION parameter to 921600 to enable MAVLink output, saved it, and reboot the Pixhawk.  After that, every time I tried to connect to the Pixhawk; I got this warning message:

"[Warning: A vehicle is using the same system id as QGroundControl: 255](https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/MultiVehicleManager.cc#L86)"

Even when I went back to the original laptop used to upload the firmware, I still was getting the same message above.

QGC connects to the Pixhawk, but the left side menu doesn't show the Parameters option;  it behaves like it is brand new Pixhawk without firmware.  I never experienced this problem with previous released.  I had to reset the Pixhawk and reinstall the firmware again.

Does anyone know what could have caused this or how can it be fixed or at least prevent it from happening again?

<img width="192" alt="screen shot 2017-02-07 at 7 23 57 am" src="https://cloud.githubusercontent.com/assets/7515273/22697502/72bc7f52-ed06-11e6-91b1-884eb1b9a116.png">

**Comment by DonLakeFlyer** [comment]
Are you running a companion computer which has a mavlink id of 255? If so, change the id for the companion computer. Or use a daily build which disregards companion computers.

**Comment by abencomo** [comment]
Yes, I'm using a companion computer with ROS and MAVROS.  Where do I change the mavlink id that you are referring to?  And, where are the QGC daily build located?

**Comment by samacumen** [comment]
Usually applications (like qgroundcontrol) assume a default MAVLINK_ID - which can be changed in the settings. It is very much possible that MAVROS may have this id hardcoded (not sure) - but you certainly should be able to change it. Look for it in the code, also have a look at [this issue](https://github.com/mavlink/mavros/pull/256).
:

**Comment by DonLakeFlyer** [comment]
Daily build links at the bottom: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html

**Comment by abencomo** [comment]
That did it.  Thanks everyone.
