### ISSUE TITLE
Heli parameters with Multicopter frame - ArduPilot 3.5dev

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4528]
I've closed the issue on ArduPilot, because the problem appears to be with QGC

https://github.com/ArduPilot/ardupilot/issues/5690

When selecting master firmware the top dialog box switches to heli by itself

**Comment by DonLakeFlyer** [comment]
Can you detail out some repro steps. I'm not getting it.

**Comment by DonLakeFlyer** [comment]
@lvale ?

**Comment by lvale** [comment]
Managed to sort things on latest master. The refreshing of parameters when changing frames was the "bad guy". 
Sorry for not closing sooner.

**Comment by DonLakeFlyer** [comment]
To me those frame params should have a "reboot required" on their meta data (firmware change). All sort of strange things happen when you change them on the fly.

**Comment by lvale** [comment]
@DonLakeFlyer Just retested on the latest master and the issue of changing frame is there:

better see the video https://www.youtube.com/watch?v=RKxgJ4YO_Wo

**Comment by DonLakeFlyer** [comment]
This is because of the firmware change in ArduCopter where the newer rc versions doesn't have separate firmwares for each vehicle type. Once ArduCopter releases 3.5 this will go away since all versions will use this new scheme. Has 3.5 been released yet?

**Comment by lvale** [comment]
3.5 not yet, still RC.. 
I believe the behaviour is that when you change something on the bottom dropdown box, it will reset the top dropdown box to the first element.

**Comment by DonLakeFlyer** [comment]
The two lists are different so you can't really preserve selection when you switch. Once the lists are the same I can preserver selection.

**Comment by DonLakeFlyer** [comment]
@lvale Is 3.5 out yet?

**Comment by lvale** [comment]
@DonLakeFlyer Still at RC5

**Comment by DonLakeFlyer** [comment]
I looked at the code for this yet again. Trying to maintain the selection vehicle firmware type when you change firmware type (stable, beta, ...) is a pile of changes. All to change something which will go away once 3.5 goes out. So I'm closing this since it's not going to get changed.
