### ISSUE TITLE
Qgroundcontrol 3.1.2 video corruption

### ISSUE THREAD

**Issue by svpcom** [mavlink/qgroundcontrol#4532]
I've got periodic video corruption (see screenshots attached) with test video stream on localhost.
Host system is a Linux x86-64.

Video source:  ```gst-launch-1.0 videotestsrc ! videoconvert ! clockoverlay ! x264enc tune=zerolatency key-int-max=32 ! video/x-h264,width=800,height=600,framerate=30/1 ! rtph264pay ! udpsink host=localhost port=5600```

If i receive video using gstreamer (without qgroundcontrol) i haven't got any corruptions:  ```gst-launch-1.0 udpsrc port=5600 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' ! rtph264depay ! avdec_h264 ! clockoverlay valignment=bottom ! autovideosink sync=true```

CPU is not saturated - i.e. it seems not a frame drop.

![normal video screenshot](https://cloud.githubusercontent.com/assets/503830/22782685/be1fc544-eee1-11e6-86f6-370cabe1c3b1.png)

![corrupted video screenshot](https://cloud.githubusercontent.com/assets/503830/22782677/b613f028-eee1-11e6-8801-317f4f40a9ef.png)

**Comment by svpcom** [comment]
@DonLakeFlyer  Do you need any additional details to reproduce it? How difficult to fix this?

**Comment by DonLakeFlyer** [comment]
Haven't look at it. @dogmaphobic Will have to look.

**Comment by dogmaphobic** [comment]
The screen grab above doesn't have the recording button. That would indicate it's an older version? I'm having some issues with RTSP (unrelated to this) but I just tried UDP and it's working fine.

<img width="1229" alt="screen shot 2017-02-22 at 12 50 26 am" src="https://cloud.githubusercontent.com/assets/749243/23199000/581cfaa2-f899-11e6-9bd4-c1e70d6010d3.png">

**Comment by svpcom** [comment]
@dogmaphobic I've retest it with latest master (a56a153d2b8a9dede579058b2c59fd71428a6805) and the issue is fixed there.  But it exists in latest stable release 3.1.3

**Comment by dogmaphobic** [comment]
Is it then safe to close this issue?

**Comment by svpcom** [comment]
Yes, but I think we need to identify and backport fix to stable branch.

**Comment by DonLakeFlyer** [comment]
Not sure what would have changed from stable to master for video? I think only the recording stuff was added. The mainline video code didn't change I think.

**Comment by NaterGator** [comment]
I am surprised we have latency set to 0 for RTSP sources and no jitterbuffer for udp sources. In my experience the network is very very rarely good enough to deliver the packets in order and without issues... even a buffer of 1 frame period is usually long enough.

**Comment by DonLakeFlyer** [comment]
Closing since daily is working. Not going to back port to stable.
