### ISSUE TITLE
RTK GPS on QGC - won't connect again once disconnected - need to restart QGC! (Reproducible)

### ISSUE THREAD

**Issue by samacumen** [mavlink/qgroundcontrol#4533]
I have an RTK ublox chip connected to QGC on a serial connection. The connection is detected by QGC however, once I disconnect the RTK it does not connect again. This is a bug, my explanation is as follows: 

In LinkManager.cpp: We autodetect links and RTK case is as follows:
```
case QGCSerialPortInfo::BoardTypeRTKGPS:
    if (_autoconnectRTKGPS && !_toolbox->gpsManager()->connected()) 
    {
        qCDebug(LinkManagerLog) << "RTK GPS auto-connected";
        _toolbox->gpsManager()->connectGPS(portInfo.systemLocation());
    }

```
The function, gpsManager()->connected() "always returns true once the instance of gpsProvider is created".
`bool connected(void) const { return _gpsProvider != nullptr; }`

Exiting the gpsProvider thread does not mean the instance of gpsManager will become NULL. So, I find this might have been overlooked? As a user, one must be able to connect and disconnect a zillion times and still  get the connection working!

**Proposed solution:**
GPSProvider inherits from QThread, so why not make use of it? 

`bool connected(void) const { return _gpsProvider && _gpsProvider->isRunning(); }`

If you can fix it that's great else I can send a pull request. Tested to work! Let me know.

**Comment by DonLakeFlyer** [comment]
Works perfectly, thanks.
