### ISSUE TITLE
Allow override of enumerated parameter values

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#4534]
Can we add an additional field to manually enter parameter values for those parameters that only present a dropdown list of choices? For example, ATC_ACCEL_Y_MAX in Copter. If there is concern about making this feature available to general users, maybe we could have an option for it in the Application Settings?

**Comment by DonLakeFlyer** [comment]
Make sense

**Comment by jaxxzer** [comment]
Done!
