### ISSUE TITLE
connecting via serial port with  QGC 3.0  ( on OSX)....

### ISSUE THREAD

**Issue by davidbuzz** [mavlink/qgroundcontrol#4535]
repeatable error:
open qgroundcotrol, click the Q logo in the top-left corner, click the "comm links" button, and in the screen that shows up, "add" a SERIAL connection to a pixhawk... be sure to select the correct serial port name for your pixhawk, baud rate here doesn't seem to matter, but 57600 is common, press "OK" to save the connection, highlight the new serial connection with a single click, and then press "connect" at the bottom of the screen..... error appears.

reported error is:
"Link Error" "Error on link /dev/cu.usbmodem1. Error connecting: Could not create port. Permission error while locking the device"
hardware is: usb serial cable to a pixhawk2 running ArduCopter

work around:    repeat the process above but don't press the "connect" in that screen at all, instead exit that screen entirely, go to one of the other screens ( eg, click the little aeroplane ), then unplug and re-plug the USB cable, so the auto-connection code can be triggered.    aircraft is now connected OK. 

( Also, Mission Planner ( in a VM on the same PC), and  "APM Planner 2.0" for OSX also seems to be able to connect ok first try, so it's not a hardware thing. )

**Comment by DonLakeFlyer** [comment]
This is because it is conflicting with the autoconnect link. As you probably already know there is no need to add a connection and Connect through Comm Links if autoconnect works. Still there should be a better way to let the user know what is going on.
