### ISSUE TITLE
graphical anomalies with survey waypoints

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4548]
When planning larger survey points and zooming in/out the white and brown lines in the survey mission get messed up.  Pretty easy to recreate on my machine running windows 7 64-bit.

![image](https://cloud.githubusercontent.com/assets/12117027/22953644/b7302374-f2d7-11e6-8b54-117012219127.png)

**Comment by DonLakeFlyer** [comment]
These are most likely the same as #3853. Should go away when we move to new Qt. Good to have more test cases to verify though.

**Comment by DonLakeFlyer** [comment]
I think this is fixed now with the move to Qt 5.7. I least I can't repro. Can you try again?

**Comment by Antiheavy** [comment]
Seems to be working correctly now with more recent daily builds.  thanks!
