### ISSUE TITLE
Land start marker in wrong spot when placed after a Survey waypoint

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4549]
The "Land start" marker seems to get attached to the start of the survey point instead of the end.  Is this working correctly?  Seems confusing to me either way.
![image](https://cloud.githubusercontent.com/assets/12117027/22954046/d3914168-f2d9-11e6-9c9b-4fbcfd30c3af.png)

**Comment by DonLakeFlyer** [comment]
Complex Mission Item bug.
