### ISSUE TITLE
attitude indicator not responding

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#4559]
QGC master and PX4 master. I still see ATTITUDE and ATTITUDE_QUATERNION updating in the mavlink inspector.

**Comment by DonLakeFlyer** [comment]
Working fine for me on master+master. I had to assign an airframe first.

**Comment by dagar** [comment]
This was PX4 SITL last week. I'll try again.

**Comment by DonLakeFlyer** [comment]
I used a real board and it was fine

**Comment by dagar** [comment]
Verified it's working with QGC master and PX4 master.
