### ISSUE TITLE
Climb out altitude for MAV_CMD_DO_GO_AROUND hardcoded

### ISSUE THREAD

**Issue by dkschrad** [mavlink/qgroundcontrol#4562]
The climb out altitude for MAV_CMD_DO_GO_AROUND is currently hardcoded to 50 m.  Something needs to be implemented to properly set that altitude.

**Comment by DonLakeFlyer** [comment]
This is use the altitude slider from the guided bar with an appropriate default on the slider.

**Comment by DonLakeFlyer** [comment]
I can't find a reference to this command anywhere in the code. So no idea what this is.

**Comment by dagar** [comment]
MAV_CMD_DO_GO_AROUND is what we send to abort a landing. It's 1 and only param is an altitude.

**Comment by DonLakeFlyer** [comment]
Ah, I wasn't look for the mavlink method correctly. Duh

**Comment by DonLakeFlyer** [comment]
I assume this isn't critical for 3.2 stable?

**Comment by dagar** [comment]
I'm not sure if we actually need it at all. Aborting a FW landing needs to happy quickly, but after it's safely climbing out you could adjust altitude the normal way.

**Comment by DonLakeFlyer** [comment]
That makes sense. You don't want to be confused by extra stuff. We can look at this again in 3.3.

**Comment by DonLakeFlyer** [comment]
Going to live with this until more complaints
