### ISSUE TITLE
Low Resolution Map

### ISSUE THREAD

**Issue by KeeyenPang** [mavlink/qgroundcontrol#4579]
As per suggested, I raise the issue here. The original post was on ArduPilot [http://discuss.ardupilot.org/t/low-resolution-map/14920](url)

I've tried install in three difference computer, running on Win 8 and Win 10 with the same result.

**Comment by dogmaphobic** [comment]
The link above returns a 404. What is this about?

**Comment by DonLakeFlyer** [comment]
@KeeyenPang Can you repost you images and details here instead of linking to ArduPilot forum?

**Comment by KeeyenPang** [comment]
Dear Don

I've found the culprit, it is Bing Map issue. Once I change to Google, all went well. For the benefit of those who want to use Bing map, I re post the map here. Thanks

Keeyen
![qgc](https://cloud.githubusercontent.com/assets/25891910/23248914/bfa56f9e-f9dc-11e6-9cf0-b785d79d08ea.jpg)
