### ISSUE TITLE
Request a dead zone setting for joystick

### ISSUE THREAD

**Issue by ghost** [mavlink/qgroundcontrol#458]
I am using a Xbox Controller to control my AR Drone. However, the center of the bottom shifts randomly. Also, I cannot set a dead zone in default controller settings.

**Comment by nanthony21** [comment]
I second this.

**Comment by DonLakeFlyer** [comment]
Seems like a reasonable request. @rjehangir Rusty you're the king of joystick code. Do you hit the need for this as well?

**Comment by rjehangir** [comment]
@DonLakeFlyer @nanthony21 @NASA33 

In ArduPilot, this can be adjusted in firmware by setting the `RCx_DZ` to a higher value. Since the joystick just overrides the RC channels, the deadzone will apply to the joystick as well.

I'm not sure how this works in PX4. If this doesn't work in PX4 then I'd be happy to add a deadzone, particularly for the Xbox controller.

**Comment by DonLakeFlyer** [comment]
In PX4 joystick doesn't override RC it's separate. In ArduPilot you're still the only one that has joystick support :)

**Comment by rjehangir** [comment]
@DonLakeFlyer Ahh, okay. In that case, I think it's a good idea and I'll be happy to work on that. It would be helpful for us as well if this was taken care of in QGC. 

For simplicity, I would probably have a checkbox that turns deadband on/off, but keep a hardcoded value that is appropriate for most controllers like the Xbox controller. Is that okay with you?

**Comment by DonLakeFlyer** [comment]
I agree on just a checkbox.

**Comment by nanthony21** [comment]
Would there be a checkbox for each channel? The Xbox needs deadband on the channels associated with the sticks, but not on the triggers. Other controllers will have their own specific channels which do/don't need deadband.

**Comment by Williangalvani** [comment]
I believe this should have been closed by https://github.com/mavlink/qgroundcontrol/pull/4123

**Comment by mortenfyhn** [comment]
> I believe this should have been closed by #4123

I also think this should be closed. I've used QGC joystick deadzones a lot.
