### ISSUE TITLE
Compile error occurs  using new branch in windows

### ISSUE THREAD

**Issue by winszenYoung** [mavlink/qgroundcontrol#4586]
Hi, I have a few prbolem  compile QGC in windows.

I try to compile QGC in windows. 
It works  your StableV3.1 branch.

but i make a new branch or commit StableV3.1 branch.
It  occurs in error.

error message is
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /OPT:REF /INCREMENTAL:NO /OPT:ICF /LTCG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /VERSION:59f89483e /MANIFEST:embed /OUT:release\QGroundControl.exe @C:\Users\KDY\AppData\Local\Temp\QGroundControl.exe.5924.144957.jom
LINK : fatal error LNK1117: syntax error in option 'VERSION:59f89483e'
jom: C:\Users\KDY\build-qgroundcontrol-Desktop_Qt_5_5_1_MSVC2013_32bit-Release\Makefile.Release [release\QGroundControl.exe] Error 1117
jom: C:\Users\KDY\build-qgroundcontrol-Desktop_Qt_5_5_1_MSVC2013_32bit-Release\Makefile [release] Error 2
18:00:44: The process "C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe" exited with code 2.

How to solve this problem?

**Comment by HomeLH** [comment]
Delete the “/VERSION:59f89483e” in file: Makefile.Debug.
