### ISSUE TITLE
Android daily builds not working

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4593]
I see this:
![screen shot 2017-02-21 at 11 37 24 am](https://cloud.githubusercontent.com/assets/5876851/23181531/2818ac62-f82a-11e6-84c1-f2c9e67fd3cc.png)

I'm not quite sure how the daily side works so not sure how to fix it myself.

**Comment by dagar** [comment]
I'll look at this tonight. Need to drop something in master for versioning.
Maybe a dev tag? `v3.2-dev`

**Comment by DonLakeFlyer** [comment]
Thanks Daniel.

**Comment by dagar** [comment]
Hmm, might be easier to have a completely separate play store entry for QGC Beta. 
Any objection?
It would be nice if the dev version had a slightly different icon, but that's optional.
![image](https://cloud.githubusercontent.com/assets/84712/23264853/cd813b1a-f9b0-11e6-8c9a-a0c369c47e7d.png)

The upside is that we'll be able to install and use stable and dev side by side on the same device.

**Comment by DonLakeFlyer** [comment]
Perfectly fine by me. If you update can you update the docs as well which has links to the android beta stuff.

**Comment by DonLakeFlyer** [comment]
You could ask the icon man: @dogmaphobic for a beta icon for the site.

**Comment by dagar** [comment]
Going off the grid for a few days, and I don't think I'll have this working before I leave. I'm going to create a new Play Store entry for "QGroundControl Beta" and it needs a few more things than I initially realized. Changes in the build system to update the package name, deploy permissions, etc.
@dogmaphobic could you do a quick icon like the chrome example above?

In the meantime Android users can directly install the master build. https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.apk

**Comment by dagar** [comment]
https://github.com/mavlink/qgroundcontrol/pull/4947
