### ISSUE TITLE
qgroundcontrol build error (  Error: C2440: "Initialization": Can not convert from "initializer-list" to "QMap <int, QString>" The constructor for "QMap <int, QString>" is declared as "explicit")

### ISSUE THREAD

**Issue by goodman110110110** [mavlink/qgroundcontrol#4622]
hi, when i try to compile the qgroundcontrol3.0.0 source code with qt5.5.1 ctreator, an error appear.

 Error: C2440: "Initialization": Can not convert from "initializer-list" to "QMap <int, QString>" The constructor for "QMap <int, QString>" is declared as "explicit"

i followed the readme.md to download the qt version 5.5.1 and to build the code.

please help me . Thankyou. 
![default](https://cloud.githubusercontent.com/assets/18226775/23328451/3c8d45ce-fb5c-11e6-8a64-13d15f957774.png)

**Comment by DonLakeFlyer** [comment]
Are you using VS 2015 to build. QGC only support VS 2013 at the moment.

**Comment by goodman110110110** [comment]
I used vs2013， I followed the readme.md to complie the code.
but it can not work.

**Comment by 18911847946** [comment]
i have met the same trouble

**Comment by 18911847946** [comment]
![qq 20170227003833](https://cloud.githubusercontent.com/assets/25566729/23341573/1bac11f8-fc85-11e6-97d2-951ed0aed98f.png)

**Comment by DonLakeFlyer** [comment]
Do you have the same problem when you build latest master?

**Comment by goodman110110110** [comment]
yes, we have the same problem. there have many mistakes when qt creator was used.

**Comment by goodman110110110** [comment]
Yes, we have the same problem, following the readme.md to build the latest
code, but the qt creator comes out many mistakes. please help me!
Thank you!

2017-02-28 1:32 GMT+08:00 Don Gagne <notifications@github.com>:

**Comment by booo** [comment]
Does not concern newer versions of the software. Closing therefore.
