### ISSUE TITLE
Initial loading of parameters extremely slow-ArduPilot master

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4643]
After flashing the PixRacer the initial loading of parameters takes forever and eventually QGC crashes

https://www.youtube.com/watch?v=UFfJoiQ61Bo

[crash.mavlink.zip](https://github.com/mavlink/qgroundcontrol/files/802443/crash.mavlink.zip)

**Comment by DonLakeFlyer** [comment]
The problem was triggered by a change in copter which makes some parameters be missing at boot. Talked to tridge about it a week or so ago it and he changed it to delay reponse to param_request_list until all params are available. But this in turn causes QGC to timeout and drops to a slow fallback mechanism to get params. 

I need to figure out how to either not hit the fallback mechanism or to speed up the fall back mechanism.

I've never seen the crash before, but not entirely suprising since it's being forced into a strange codepath which doesn't happen often. I can't see the video to see which version of QGC you are using. I assume a new daily?

**Comment by DonLakeFlyer** [comment]
Nope I was wrong. ArduPilot is just not working correctly on initial request. It sends one param and then it stops.

**Comment by DonLakeFlyer** [comment]
And that wasn't it either. Just more strangeness with ArduPilot and the param protocol. I still can't get the crash though. Can you retry one this goes throuhg?

**Comment by lvale** [comment]
@DonLakeFlyer As far as I can see the issue is solved (connected on USB) when we flash the firmware for the first time on a "blank" PixRacer
latest buid of QGC
https://youtu.be/RmTm06rza_0

**Comment by DonLakeFlyer** [comment]
Awesome, thanks for verifying @lvale

**Comment by lvale** [comment]
ok. Via WiFi I had to give up after a few minutes waiting. No parameters downloaded. 

Tested again with APM Planner and downloaded 752 parameters (ouch!!) in about a minute

Adding QGC log - tested with 

<img width="604" alt="screen shot 2017-03-06 at 20 28 23" src="https://cloud.githubusercontent.com/assets/3130363/23628205/7f9c4eea-02ab-11e7-83a5-5de4433a072c.png">


[qgc_no_parameter_download_via_wifi.txt](https://github.com/mavlink/qgroundcontrol/files/822402/qgc_no_parameter_download_via_wifi.txt)

**Comment by DonLakeFlyer** [comment]
Fixed in latest master: https://github.com/mavlink/qgroundcontrol/pull/4723

**Comment by lvale** [comment]
Just retested with #4723 - Still here :(
[latest master of qgc.txt](https://github.com/mavlink/qgroundcontrol/files/822522/latest.master.of.qgc.txt)
<img width="569" alt="screen shot 2017-03-06 at 21 03 40" src="https://cloud.githubusercontent.com/assets/3130363/23629838/d7920c5c-02b0-11e7-9c4f-5ed3be712a12.png">

**Comment by DonLakeFlyer** [comment]
Can you get output from ParameterManagerLog?

**Comment by lvale** [comment]
@DonLakeFlyer We've discussed this problem today on the dev call and hopefully the solution is this https://github.com/ArduPilot/ardupilot/commit/e4c9255cb908ffbac329d6e3f728c16a68b340f2

**Comment by DonLakeFlyer** [comment]
The log doesn't match what the output should be from the newest builds which have #4723 in it. What OS are you using. Maybe there is a daily update problem.

**Comment by lvale** [comment]
I'm pulling and compiling locally on OSX with QT5.8, and that had #4723.

<img width="907" alt="screen shot 2017-03-07 at 20 57 15" src="https://cloud.githubusercontent.com/assets/3130363/23677599/b3775eda-0378-11e7-8dc2-a8437e00c033.png">

**Comment by lvale** [comment]
I'm compiling ArduPilot master with the changes from Peter Barker and Tridge for the UART/DMA issue that might be the problem here, and we'll let you know how it goes.

**Comment by lvale** [comment]
@DonLakeFlyer @peterbarker 

So I compiled ArduPilot Copter with the latest commit from Peter and flashed the PixRacer (using the USB cable).

Also pulled the latest QGC from master and compiled with QT5.8

Disconnected the USB cable, rebooted the PixRacer and set up the WiFi connection to the PixRacer via  WiFi (Mac OSX 10.12.3).

QGC connected via WiFi and began the initial downloading of parameters - however sometimes it gets "locked" when just a few parameters (5/6) 

Restarted the process and the downloading of parameters restarted , BUT when the parameter download finishes QGC crashes.... see crash1.rtf

When restarting QGC I managed to save the tlog - crash_log.mavlink
[crash1.rtf.zip](https://github.com/mavlink/qgroundcontrol/files/825943/crash1.rtf.zip)
[crash_log.mavlink.zip](https://github.com/mavlink/qgroundcontrol/files/825944/crash_log.mavlink.zip)

**Comment by lvale** [comment]
Retried again and managed to save a piece of the log while downloading the parameters, but still crashes when it finishes

[1.txt](https://github.com/mavlink/qgroundcontrol/files/825958/1.txt)

**Comment by lvale** [comment]
Just adding an App Log from a USB connection. Same board, same firmware and same QGC
[usb_log.txt](https://github.com/mavlink/qgroundcontrol/files/825974/usb_log.txt)

**Comment by peterbarker** [comment]
On Tue, 7 Mar 2017, Luis Vale Gonçalves wrote:

> Restarted the process and the downloading of parameters restarted , BUT when
> the parameter download finishes QGC crashes.... see crash1.rtf

Yes yes - but you haven't told us whether the parameter download was fast 
or not!  :-)

**Comment by lvale** [comment]
@peterbarker it is fast :) until it crashes :)

**Comment by DonLakeFlyer** [comment]
I have to see if it will repro for me on direct USB connection. My pixracer wifi is toast.

**Comment by DonLakeFlyer** [comment]
> It is fast :) until it crashes :)

Story of my life...

**Comment by lvale** [comment]
@DonLakeFlyer On USB everything is fine and dandy :)

**Comment by NaterGator** [comment]
Are we blindly trusting data coming over the link to index into an array or list somewhere? Sounds like corrupted data over the WiFi link triggering a segfault from out of bounds access. 

Slow is smooth and smooth is fast!

**Comment by DonLakeFlyer** [comment]
> Are we blindly trusting data coming over the link to index into an array or list somewhere?

Really?

**Comment by NaterGator** [comment]
I reviewed it and couldn't find anywhere that corrupted data over the link would index randomly into a vector-style data structure. Worst case we'd get a miss in a hashtable and qt would create a default value for us.

**Comment by DonLakeFlyer** [comment]
It's a wierd Qml thing (big surprise there) which I haven't figure out yet.

**Comment by DonLakeFlyer** [comment]
Hmm, from looking at the last text log it may be declaring load complete incorrectly. Let me look at the debug output and see if I can add some better logging. 

@lvale What OS are you running on?

**Comment by DonLakeFlyer** [comment]
@lvale Can you do another run with only ParameterManagerLog? Don't turn on the other more verbose parameter logs.

**Comment by DonLakeFlyer** [comment]
This has been a real pain. I can't seem to get toolset set up to re-flash my own ESP 8266's for testing. So instead Gus is sending me on of his so I can make forward progress...

**Comment by lvale** [comment]
Just tested after clearing the preferences from .config and fresh from master QGC

Parameter downloading completed without major issues although some retries occurred

Here's the app log

[log_ok.txt](https://github.com/mavlink/qgroundcontrol/files/866503/log_ok.txt)

**Comment by DonLakeFlyer** [comment]
Ah, good news finally. Your connection is really lossy though!

**Comment by lvale** [comment]
@DonLakeFlyer Well the drone is at 30cm from the Macbook :)

![img_20170324_113728](https://cloud.githubusercontent.com/assets/3130363/24292715/6e0a7ee8-1086-11e7-9a67-fa6f71d490ab.jpg)
