### ISSUE TITLE
QGeoCoordinates used in debug output need to output 7 digits of precision

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#4666]
Would be nice for this to be handled app-wide.

**Comment by DonLakeFlyer** [comment]
This needs to be a Qt bug. We don't have control over qDebug() << QGeoCoordiante(...) output as far as I know.

**Comment by NaterGator** [comment]
I actually think we can do this on our own. Working on it now...

**Comment by DonLakeFlyer** [comment]
Awesome, thanks Nate

**Comment by NaterGator** [comment]
I've played around with this on and off, and while I have been able to come up with app-wide fixes they are decidedly inelegant and abuse platform specific behaviors. It simply isn't worth the headache, so upstream this goes: https://bugreports.qt.io/browse/QTBUG-59259

**Comment by DonLakeFlyer** [comment]
Thanks for trying Nate

**Comment by jakehewitt** [comment]
Thank you Nate. Is there any temporary hacky way I could log the full numbers?

**Comment by dogmaphobic** [comment]
If I'm reading this correctly, you could have a function that takes a `QGeoCoordinate` and spits out a `QString`. You can format it any way you want it.

```
QString QGCApplication::qGeoCoordinateToString(QGeoCoordinate& geo)
{
    QString txt;
    txt.sprintf("%f %f %f", geo.latitude(), geo.longitude(), geo.altitude());
    return txt;
}
```

In the code you would use it instead of feeding it directly to `qDebug`:

```
qDebug() << qgcApp()->qGeoCoordinateToString(_homePosition);
```

**Comment by NaterGator** [comment]
There's a few approaches to attacking this... you could also just shift the [qSetRealNumberPrecision](http://doc.qt.io/qt-5/qtextstream.html#qSetRealNumberPrecision) manipulator right after calling qDebug() and not need to dereference the qgcApp pointer. 

I played around with replacing the stream operator at the linker, manipulating the debug macros, etc. There's not one silver bullet to solve this across all platforms transparently.

**Comment by DonLakeFlyer** [comment]
Many different way to hack in one-off changes. No way to do it without having to change all references in code.
