### ISSUE TITLE
Laptop Display Issue

### ISSUE THREAD

**Issue by ldsanders2807** [mavlink/qgroundcontrol#4668]
QGC 3.1.3: It appears that for some reason, the mouse does not function on the center part of the airframe selection screen.  I can't select ANY airframe.  I can't select any airframe's selection list.  Or use the mouse roller to scroll down the screen. The mouse does work on the outside panels of the airframe screen. And everywhere else on QGC.  The laptop is an HP Elitebook 8540p with Windows 10.  It works fine on my desktop.

**Comment by DonLakeFlyer** [comment]
Does this still happen to you using a daily build?

**Comment by ldsanders2807** [comment]
I have not tried any version other than v3.1.3.   What is the link for the daily build?

**Comment by DonLakeFlyer** [comment]
Daily build links at bottom of page: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/en/download_and_install.html

**Comment by ldsanders2807** [comment]
The frame selection drop down menus work and the mouse roller will scroll the screen with the daily build version.

 

Thanks for checking back on this!!

 

LaVerne Sanders

**Comment by DonLakeFlyer** [comment]
Perfect. Thanks for reporting back.
