### ISSUE TITLE
Can HILstar xplane airframe not be applied to HIL fixed-wing simulation with QGC and flightgear？

### ISSUE THREAD

**Issue by goodman110110110** [mavlink/qgroundcontrol#4682]
I want to do the HIL fix-wing simulation with QGC 3.1.3, pixhawk(pix4) and flightgear 3.4.
But I can not find the simulation airframe for flightgear but the HILstar (xplane), so I choose the HILstar (xplane) and apply.
When start the simulation, the QGC ui can receive the data from the flightgear, but flightgear can not receive the data from QGC, the plane in the flightgear can not be controlled by QGC.
So I think, can the  HILstar (xplane) firmware not be used to the HIL fix-wing simulation with flightgear (only Xplane)?
So where is the flightgear simulation firmware for fix-wing?
Please help me.
![2](https://cloud.githubusercontent.com/assets/18226775/23514260/c86c4664-ffa1-11e6-8d78-77548e400ec4.png)

**Comment by DonLakeFlyer** [comment]
This is a question for the firmware folks. I'm not sure which airframe you are supposed to use with FlightGear. If you find that that is the correct airframe from firmware devs and it is not working I'll re-open.
