### ISSUE TITLE
Change compass heading display to 3 digits

### ISSUE THREAD

**Issue by marinesimulation** [mavlink/qgroundcontrol#4691]
The heading indicator numbers from 1-99 degrees are in a two digit format, can we chance these to three digits where we have a zero in front? ("045") This would bring it inline with aircraft and vessel displays.

![qgc-heading](https://cloud.githubusercontent.com/assets/17232608/23534637/4664a9fa-ff87-11e6-851f-26f7ab8b2ea7.png)

**Comment by Antiheavy** [comment]
I will second this request!

**Comment by DonLakeFlyer** [comment]
Is such a big compass display critical? We were thinking of moving to something more like this:
![screen shot 2017-03-02 at 3 08 45 pm](https://cloud.githubusercontent.com/assets/5876851/23536312/dc5f1a44-ff78-11e6-8eee-f6d61d70d149.png)
Which has the compass and hud combined.

**Comment by jaxxzer** [comment]
I am in favor of reducing the overall size of the display.

**Comment by DonLakeFlyer** [comment]
Not that specific image necessarily. Just the concept of compass around attitude.

**Comment by KevinKW87** [comment]
Combining the compass and the attitude I think would work out well. If that's the case, can we still get a three digit compass reading in the Widget Value area? It makes navigation easier for me when I do quick glances at the widget values. I have a rough idea what my heading is just by glancing at the first digit (0-1-2-3).
![qgc heading](https://cloud.githubusercontent.com/assets/9004033/23537258/b86aa6a6-ff7f-11e6-979c-ad2dd15ea773.png)

**Comment by Antiheavy** [comment]
I like the idea of combined compass and horizon as long as the pitch/roll and heading are clearly visible from a couple/few meters away from the screen.  We don't have to read the numbers from that far, but need to see the orientation by tilting and turning your aircraft during pre-flight checks.  For UAVs I like circular compasses compared tape style.

I also support the original request to display heading as a 3 digit number where shown.

**Comment by DonLakeFlyer** [comment]
> If that's the case, can we still get a three digit compass reading in the Widget Value area?

Unfortunately that would be way more difficult since that is all generic code which at the point it's being displayed doesn't know it's a heading. It would require formatting meta data support in the internal FactSystem. Doable but non-trivial.

**Comment by DonLakeFlyer** [comment]
Maybe if the compass goes around this:
<img width="178" alt="screen shot 2017-03-02 at 8 17 58 pm" src="https://cloud.githubusercontent.com/assets/5876851/23538085/6a2c51a0-ff85-11e6-90a2-6bfc7c3c31a9.png">
We could put three digit heading in big text towards the bottom center part of the attitude indicator.

**Comment by DonLakeFlyer** [comment]
Quick Qml hacking:
<img width="178" alt="screen shot 2017-03-02 at 8 48 49 pm" src="https://cloud.githubusercontent.com/assets/5876851/23538643/b3c95a2a-ff89-11e6-9828-940b68b45328.png">

**Comment by jaxxzer** [comment]
@DonLakeFlyer In the intermediary term (at least), can we make this new style an option?

**Comment by DonLakeFlyer** [comment]
I tend to think options are evil. 5% of the user base ever finds anything beyond the default setting.

**Comment by DonLakeFlyer** [comment]
An image of it working for real:
<img width="190" alt="screen shot 2017-03-02 at 9 03 48 pm" src="https://cloud.githubusercontent.com/assets/5876851/23538892/cd202858-ff8b-11e6-846b-d5eef0c7d72b.png">

**Comment by jaxxzer** [comment]
@rjehangir Has reservations about this. Almost all of Sub navigation is done by heading, and it may be unclear/less wieldy for operators. Even if the option is not exposed, something that we could default to with firmware?

**Comment by DonLakeFlyer** [comment]
That's a good argument. 

You can't default with firmware. But you can default with your own custom version of QGC using your own core plugin. This allows you to change the default on settings as well as hide settings among a whole pile of other things which allow you to create a third party branded version of QGC targeted to a specific vehicle.

**Comment by DonLakeFlyer** [comment]
With your own QGCCorePlugin you can even go so far as replace the instrument panel entirely with something custom created by you.

**Comment by DonLakeFlyer** [comment]
Ok, one more. You can even change the vehicle icon throughout QGC from the core plugin to be a sub looking thingy instead of a plane looking thingy.

**Comment by DonLakeFlyer** [comment]
Here is a full screen shot. It leaves a lot of room for lots of values to show in the page control below. Implementing as a second variant. So old one is still usable if you want.
<img width="1084" alt="screen shot 2017-03-02 at 9 35 02 pm" src="https://cloud.githubusercontent.com/assets/5876851/23539449/5b9838a6-ff90-11e6-8057-f35c4afb21a2.png">

**Comment by marinesimulation** [comment]
Here's one vote against combining the attitude and compass displays.  When operating an ROV we really don't use the attitude display all that much.  In fact, the BlueROV2 is the only mini sized ROV that includes an attitude display.  It may help in some rare situations but our primary focus, especially when operating in poor visibility, is the compass heading.  Unlike aerial drones, ROVs frequently operate in water that may have almost zero visibility.  Having a large, easily read compass display is critical for this type of operation.  The current compass heading display is just about perfect.  It's a good size and it's easily read.  I think removing it and combining it with another, less used display would be a big mistake and would make QGC much less functional for ROV operators.

**Comment by DonLakeFlyer** [comment]
I'm putting it on an option. But I'm defaulting to combined. We'll see how it goes. Easy to back off after it's through.

**Comment by DonLakeFlyer** [comment]
Fixed
