### ISSUE TITLE
ParameterManager.h line 201 uses 'constexpr'

### ISSUE THREAD

**Issue by jimdgit** [mavlink/qgroundcontrol#4720]
First let me thank you for providing a clear path to building this project.
Great job on that!

This is the only issue I found.
constexpr is not available in msvc2013 compiler that downloads with QT 5.5.1 for some reason.
Changed it to const and all builds fine.

"Microsoft publishes a C++11 compatibility table, under which constexpr is clearly marked as not being available in Visual Studio 2013."
Rumor has it that it is supported in a later version.

**Comment by DonLakeFlyer** [comment]
There is no longer a constexpr in there.

Also FYI: We are moving to VS 2015. So you can use that as well now.

**Comment by jimdgit** [comment]
Thanks!
