### ISSUE TITLE
FW Landing complex mission item loiter/land overlap

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#4737]
Spuriously the loiter and land positions will be dropped on exactly the same coordinate.  See #4706

**Comment by DonLakeFlyer** [comment]
Anyone know if this is touch only?

**Comment by Antiheavy** [comment]
I found a use case/bug in Windows build (KB/mouse, not touch) to cause this to happen repeatably:

1. Place a Landing pattern
2. Drag components around until "--.--" shows up in the Landing distance and Landing heading fields (bug).
               It seems random where this may actually occur so I end up just dragging Land point around randomly until I find a place that --.-- shows up.  I haven't been able to make --.-- show up by dragging the Loiter.
3. Hit [Enter] key.  "Invalid Value" pops up on the right side menu.
4. Press [Reset to default] button
Walla, the Loiter point jumps on top of the Land point.

**Comment by DonLakeFlyer** [comment]
I think I'm going to change the landing pattern item to automatically add the pattern when you add the item. Then you just drag to repostion. This removes the strange user model and will likely make this problem go away as well.

**Comment by DonLakeFlyer** [comment]
Also with this https://github.com/mavlink/qgroundcontrol/pull/4770 the --.-- should be gone now

**Comment by DonLakeFlyer** [comment]
@Antiheavy I haven't seen this problem lately. I think it's gone now?

**Comment by Antiheavy** [comment]
I've been using daily builds for the past month.  I have not seen this issue in a long time.   probably gone now?

**Comment by DonLakeFlyer** [comment]
That's what I thought.
