### ISSUE TITLE
Segmentation fault (core dumped) when pressing on Radio tab

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#4738]
I'm running latest QGC master and using a Snapdragon Flight Board (latest master). I start PX4 on the Snapdragon and the parameters are loading. As soon as I click on Radio it crashes (every time, doesn't matter if the RC is turned on or not). The connected RC is a Spektrum DXe.

Here's the extended log
[QGC_crash.txt](https://github.com/mavlink/qgroundcontrol/files/833299/QGC_crash.txt)

**Comment by ChristophTobler** [comment]
This `Unknown: 123...` is the reason for the crash
![rc_map_issue](https://cloud.githubusercontent.com/assets/14769636/23902775/8cbf4a88-08c2-11e7-8d48-f6e305a8ffe8.png)

If I map all `Unknown: 123...` to a channel, I can select the Radio tab

**Comment by DonLakeFlyer** [comment]
Awesome thanks. I think that should be enough of a hint to find it.
