### ISSUE TITLE
Reducing visual complexity

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#4752]
Some of the menus have title bars which consume screen real estate (I'm running out of screen space on a 13" MacBook, so its not like we would have excessive space). Here is an example for a before and after version of a UI element with title bars removed.

Before:

<img width="467" alt="screen shot 2017-03-12 at 11 45 25" src="https://cloud.githubusercontent.com/assets/1208119/23832693/373fad8e-073a-11e7-86f1-c31cbf9e79c6.png">

After cleanup (not resized, since I did this just in the screenshot):

<img width="467" alt="screen shot 2017-03-12 at 11 45 25-edited" src="https://cloud.githubusercontent.com/assets/1208119/23832686/0c5c7a52-073a-11e7-897d-888719aed2bf.png">

**Comment by DonLakeFlyer** [comment]
The right side editors scroll up and down and they automatically position themselves to the selected waypoint when you click on them in the map. Not sure what this accomplishes other than removing helpful information?

**Comment by DonLakeFlyer** [comment]
Some tweaks still can be done though without using the helpfulness. For example when you are actually connected to a vehicle there is no need to tell the user what Firmware and Vehicle they have. That is mostly for offline editing. I'll change.

**Comment by DonLakeFlyer** [comment]
Here is what it looks like now:

Offline Editing mobile (I figure nobody is going to type on lat/lon on mobile):
![screen shot 2017-03-12 at 11 54 35 am](https://cloud.githubusercontent.com/assets/5876851/23834878/d5573aac-071a-11e7-9876-20a1aec5b79b.png)

Offline Editing desktop (same as before):
![screen shot 2017-03-12 at 11 50 47 am](https://cloud.githubusercontent.com/assets/5876851/23834857/6f4a1194-071a-11e7-8a84-531dc221c064.png)

Vehicle connected editing mobile (no need to show firmware/vehicle):
![screen shot 2017-03-12 at 11 54 48 am](https://cloud.githubusercontent.com/assets/5876851/23834873/b9d58b8a-071a-11e7-8648-0fbf0f312228.png)

Vehicle connected desktop (no need to show firmware/vehicle):
![screen shot 2017-03-12 at 11 51 04 am](https://cloud.githubusercontent.com/assets/5876851/23834888/f190ed6c-071a-11e7-8de8-8cc9abc04127.png)

**Comment by DonLakeFlyer** [comment]
There also is not enough "air" in these editors. Everything is right next to each other vertically which leads to looking more complex. We could chose to add more seperation and use more vertical real estate. Survey is a possible good example of this.

**Comment by DonLakeFlyer** [comment]
I'll keep this open as a work in progress. The current pull optimizes for vertical real estate which I think in reality is a mistake.

**Comment by DonLakeFlyer** [comment]
It's better now. Not necessarily great. But good.
