### ISSUE TITLE
After removing all items from a mission, view centers at min zoom level (it should center at max)

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#4753]
As visible below. The other entering tools are also not zooming in.

I would propose the following: If zoom level is already close to max (which is a hint the user is seeing the vehicle sufficiently well), leave as is. If the zoom level is however not set or very high, zoom in so the user can see the local context.

If this happens to you in the field you're busy for the next 20 seconds zooming in with two fingers.

<img width="1120" alt="screen shot 2017-03-12 at 16 12 25" src="https://cloud.githubusercontent.com/assets/1208119/23832942/c7c31388-073e-11e7-8cd1-967076ebffbe.png">

**Comment by DonLakeFlyer** [comment]
There is still a Center tool zoom problem which happens but I can't seem to find the repro for right now.

**Comment by DonLakeFlyer** [comment]
This is all different code now
