### ISSUE TITLE
Temperature is -1 , yellow popup display old waypoint

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4758]
Feel free to close this issue, or request more data.
There are two possible issues here: 
1: temperature in the primary flight display area is displayed as "-1"
2: the yellow popup , gets stuck displaying one "reached waypoint..."  message, 

Please note that this is a arduplane .tlog playback, not truly live data. (so QGC does not have duplex communication.)

![screenshot from 2017-03-12 21-22-51](https://cloud.githubusercontent.com/assets/1468842/23836327/b0b20dce-0776-11e7-8b7d-6586774ea06e.png)

**Comment by jaxxzer** [comment]
I can't see what the temperature says, but can you provide a method of reproducing the issue? What firmware version of APM and what QGC commit? Also does the temperature issue happen when actually connected to a live ap, or only when doing log playback?

**Comment by AndKe** [comment]
Just checked with the log in the screenshot, and current 3.7.1 tlog , unable to reproduce anymore.
