### ISSUE TITLE
Survey - camera orientation flipped for overlap calculation?

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4765]
I think the Landscape vs Portrait camera options might be reversed when calculating the overlap for a Survey.  At least is looks reversed for the side-lap calculation at least, I can't tell about the frontal-lap.

![image](https://cloud.githubusercontent.com/assets/12117027/23883934/dd473cee-0837-11e7-8a75-5674ba5fc0f4.png)

edit:
Additional bug that might be related: 
https://github.com/mavlink/qgroundcontrol/issues/4767

**Comment by DonLakeFlyer** [comment]
Pull doesn't fix this.
