### ISSUE TITLE
Bug - application crashes when clicking on Console then Offline maps

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4780]
QGC application crashes (hangs) when clicking on Console and then Offline maps.  Repeatable in Windows 7 64-bit.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you look at this one? If repros for me on OSX and of course it's deep inside Qt somewhere.

**Comment by dogmaphobic** [comment]
I can't reproduce this (Mac OS). I tried all possible combinations and it never crashed. I used current master for testing. I'm not sure I'm setup for building a Windows version. Let me check...

**Comment by DonLakeFlyer** [comment]
Strange. I'll try again on my side.

**Comment by DonLakeFlyer** [comment]
Fixed
