### ISSUE TITLE
Spontaneous crash in Map tile code

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4801]
I wasn't doing anything in QGC. I think I may have done to Offline Maps.

```
//-----------------------------------------------------------------------------
void
QGeoTiledMapReplyQGC::timeout()
{
    if(_reply) {
        _reply->abort();
    }
}
```

Crashed on ```_reply->abort();```. _reply probably null but could get it to show up in the debugger.

**Comment by DonLakeFlyer** [comment]
I believe it is caused by offline maps. Most likely some sort of bad shutdown sequence through the controller of something? You move away from offline maps and things are shutdown right?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Did you fix this already?

**Comment by dogmaphobic** [comment]
Yes, it went in in f0007592761fabab278577ef6a498f2d12d72a5a
