### ISSUE TITLE
Linux AppImage builds don't seem to work with gstreamer

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4803]
Tested on both 14 and 16 Ubuntu. Both spit this out
```
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed
Map Cache in: "/home/parallels/.cache/QGCMapCache300" / "qgcMapCache.db"
Orphaned log file count 0
LinkManager mavlinkStatus:channel:flags 0xfc0ac8 1 2
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed
VideoReceiver::start() failed. Error with gst_element_factory_make('h264parse')
VideoReceiver::start() failed
```

**Comment by DonLakeFlyer** [comment]
@jaxxzer Says this is working fine now

**Comment by dharma-kc** [comment]
I am still getting the same error on Ubuntu 16.04. Any suggestion will be appreciated.

**Comment by jaxxzer** [comment]
@dharma-kc Can you try:

`apt install gstreamer1.0-plugins-bad gstreamer1.0-libav`

and let us know if it works after installing these two packages?

See also [here](https://github.com/mavlink/qgroundcontrol/issues/4303#issuecomment-315445212).

**Comment by dharma-kc** [comment]
Great. It works. Thank you.

**Comment by petmonkey** [comment]
Worked for me too! Thx!!!

**Comment by PavanMadushanka** [comment]
This solved it! Thanks..
