### ISSUE TITLE
question: what is the difference between Camera Setup under Vehicle setup and Camera settings in Plan view

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#4812]
question: what is the difference between Camera Setup under Vehicle setup
![image](https://cloud.githubusercontent.com/assets/12117027/24159434/0dc77172-0e2d-11e7-9add-5c407a1aab95.png)
and Camera settings in Plan view
![image](https://cloud.githubusercontent.com/assets/12117027/24159460/190f447e-0e2d-11e7-8588-dfc25c5d5e3f.png)
?

**Comment by DonLakeFlyer** [comment]
Camera setup page sets global trigger settinsg for the vehicle. So they work even when not flying a mission.

Camera settings in plan view are for the mission only.
