### ISSUE TITLE
Jeti DC 16 as USB Joystick won't configure or calibrate correctly. 

### ISSUE THREAD

**Issue by anton-rothwell** [mavlink/qgroundcontrol#4826]
For comparison QGC 2.97 will allow this joystick to be used correctly with the first 4 axis.

In master build, the roll axis (mode 2 right stick) will move axis 5 and 6. Pitch axis can't be calibrated correctly and sits waiting for the final down position indefinitely.

Note: this is a Windows build.

**Comment by DonLakeFlyer** [comment]
QGC Issues should go here: https://github.com/mavlink/qgroundcontrol/issues
