### ISSUE TITLE
Plan: center map on mission should ignore home

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#4843]
Please observe that home, is often 0 LAT 0 LON , regardless of plan, it's not being read back when loading mission from AP.
Loading a plan , centering map on "mission" , looks then like this:
![screenshot from 2017-03-24 18-06-28](https://cloud.githubusercontent.com/assets/1468842/24305267/a57378b8-10bc-11e7-9a89-88b81e59ba91.png)

Please ignore "home" when centering on mission.

**Comment by DonLakeFlyer** [comment]
Planned home position is all different now. It show no longer end up in the ocean at random points.
