### ISSUE TITLE
mouse doesn't work in some context menus

### ISSUE THREAD

**Issue by lovettchris** [mavlink/qgroundcontrol#4852]
on the [latest bits ](https://github.com/mavlink/qgroundcontrol/commit/1e0e8d4dedc82611e48165bef34e032993e49a13) on windows something is wrong with your context menus, the mouse cannot select the items.  The keyboard can.  This happens on the menus for selecting which flight modes is associated with which rc channel value.

**Comment by DonLakeFlyer** [comment]
What firmware?

**Comment by DonLakeFlyer** [comment]
@lovettchris Firmware? Still happens on latest daily builds?

**Comment by lovettchris** [comment]
I tested the latest bits, it seems to be fixed.  I was using latest PX4 firmware for px4fmu_v2-default.
