### ISSUE TITLE
Latest official build doesn't receive generic MAVLink telemetry

### ISSUE THREAD

**Issue by digitalentity** [mavlink/qgroundcontrol#4857]
I have a custom MAVLink-capable vehicle based on INAV firmware which talks MAVLink 1.0. QGroundControl 3.1.3 seems to open the connection correctly, but doesn't display any telemetry. MAVLink inspector widget also doesn't show any data. 

Vehicle is sending data correctly - verified with APM Mission Planner application.

**Comment by DonLakeFlyer** [comment]
Save me a telemetry log from Mission Planner and attach here so I can replay.
