### ISSUE TITLE
Latest nightlies not running on MacOS

### ISSUE THREAD

**Issue by vshie** [mavlink/qgroundcontrol#4872]
Crash report available at: 
https://pastebin.com/78ZDr8mn

Running 2015 Mac pro
Download nightly, mount, copy to applications folder, launch, immediate crash with details available in report, shared above.

**Comment by DonLakeFlyer** [comment]
Hmm, looks like a plugin is missing. Thanks for the report. Likely broken by the move to 5.8

**Comment by DonLakeFlyer** [comment]
Fixed
