### ISSUE TITLE
Why are daily builds tagged as 3.1.2?

### ISSUE THREAD

**Issue by abencomo** [mavlink/qgroundcontrol#4882]
The latest [QGC release is 3.1.3](https://github.com/mavlink/qgroundcontrol/releases/tag/v3.1.3).  However, the [daily builds](https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html) are labeled 3.1.2. Why is that?

**Comment by DonLakeFlyer** [comment]
Where are you seeing a version number on daily builds? The title should just be a git commit number on daily builds.

**Comment by abencomo** [comment]
The first screenshot shows 3.1.2 a the version for the daily build I just downloaded today.  The second one is the official release build, and it says version 3.1.3 in the Info screen.  However, the top title does show the git commit number as you pointed out so I guess is not a big deal.  I close this.

<img width="395" alt="screen shot 2017-03-29 at 9 54 08 am" src="https://cloud.githubusercontent.com/assets/7515273/24466489/e94c02d8-1465-11e7-83d8-877dc4c8c3e0.png">
<img width="403" alt="screen shot 2017-03-29 at 9 54 29 am" src="https://cloud.githubusercontent.com/assets/7515273/24466496/ef50e234-1465-11e7-8686-64a3f7b8841e.png">

<img width="724" alt="screen shot 2017-03-29 at 9 57 16 am" src="https://cloud.githubusercontent.com/assets/7515273/24466605/4d7318be-1466-11e7-80a1-b35912694300.png">

**Comment by DonLakeFlyer** [comment]
Ah, I see. Just a build wierdness. Going to re-open since worthwhile fixing at some point.
