### ISSUE TITLE
AnalyzeView controller lifetime tied to current page

### ISSUE THREAD

**Issue by NaterGator** [mavlink/qgroundcontrol#4909]
The controller backing AnalyzePages is created when the page is loaded and destroyed when it is replaced in the loader. For example, with a log download in progress you cannot switch to GeoTag Images or your log download will terminate.

@DonLakeFlyer if you're okay with it, I'll submit a PR to instantiate the controllers for each AnalyzePage on the AnalyzeView. When loaded the AnalyzePage can access its controller from the view.

**Comment by DonLakeFlyer** [comment]
Yeah these should stay live once you go there.

**Comment by NaterGator** [comment]
Ok. I'm cooking up a mavlink console page as well, which is how I came across this. I'll have a PR in just a bit.

**Comment by DonLakeFlyer** [comment]
Fixed
