### ISSUE TITLE
Fly Screen - cosmetic issue

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4949]
When flying a mission the red line behaves like the snake game, ie like a trail but does not extend to all the previous points

Moment 1
<img width="603" alt="screen shot 2017-04-09 at 11 48 35" src="https://cloud.githubusercontent.com/assets/3130363/24836707/ed87d13e-1d1a-11e7-9f6a-837b948063dc.png">

Moment 2
<img width="497" alt="screen shot 2017-04-09 at 11 49 30" src="https://cloud.githubusercontent.com/assets/3130363/24836708/fa69b138-1d1a-11e7-9a27-3296068c1112.png">

If the intention of the red line is to indicate what has been done, shouldn't it be from where the path began instead of "following" ?

**Comment by DonLakeFlyer** [comment]
There is a limit on the length of the trail due to performance.

**Comment by DonLakeFlyer** [comment]
This was mainly to fix a perf problem on mobile. I'll take a look at it again to possibly set longer trails on desktop.
