### ISSUE TITLE
Mission Planning - Economic route

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#4950]
On this test, I drew a mission and then checked the option for the 90 degrees.

The resulting mission is not very "economic".

See the case of WP27,28,29 where the vehicle will have to cross the entire survey grid, to then do the 90 degress pattern, and end the mission at the furthest of home.

<img width="959" alt="screen shot 2017-04-09 at 12 01 04" src="https://cloud.githubusercontent.com/assets/3130363/24836774/d695a922-1d1c-11e7-8575-8971829e8b52.png">

[test_mission1.mission.txt](https://github.com/mavlink/qgroundcontrol/files/908142/test_mission1.mission.txt)

IMHO, would be better to start the 90 degrees at the bottom and work the way up, and that would result in a more "economic" route.

Perhaps, also, adding, an option for editing  "entry" and "exit" points would be helpful.

**Comment by lvale** [comment]
Also. Shouldn't WP28 be more "close" to WP3 ?

**Comment by Antiheavy** [comment]
have you tried 270 degrees instead of 90 degrees?  sometimes that helps put the start and end points at better locations.  I don't know if that fixes your problem in this instance or not.

**Comment by DonLakeFlyer** [comment]
Yup, known problem. Not fixed yet.

**Comment by DonLakeFlyer** [comment]
> Also. Shouldn't WP28 be more "close" to WP3 ?

Not really. It looks like it is at the right point. Which you can verify that the distance from the transect to waypoint 16 equals half the distance between transects. So it's in the right place to get the coverage needed.

**Comment by DonLakeFlyer** [comment]
Hover and Capture will now connect the refly section using the most economic route.
