### ISSUE TITLE
Build error (typo?) with current master

### ISSUE THREAD

**Issue by AZOM** [mavlink/qgroundcontrol#4959]
I am getting following output when trying to build the current master:

> linking debug\libQGroundControl.so 
arm-linux-androideabi-g++: error: obj\moc_RadioComponentController.oj: No such file or directory
Makefile:1189: recipe for target 'debug\libQGroundControl.so' failed
mingw32-make: *** [debug\libQGroundControl.so] Error 1
13:45:17: The process "C:\Qt\Qt5.7.1\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.7.1))
When executing step "Make"

Seems to me like there is a type somewhere, since I think it should be "obj\moc_RadioComponentController.o**b**j", no?

PS: I did not change anything at the code yet, just added "gstreamer-1.0-android-armv7-1.5.2" to the root folder of the project.

**Comment by DonLakeFlyer** [comment]
Your Qt Creator project is likely not set up corretly. QGC builds fine on android. You can look at any pull request travis result to see exactly how the CI system builds android.
