### ISSUE TITLE
Add support for testing PX4 camera trigger

### ISSUE THREAD

**Issue by mhkabir** [mavlink/qgroundcontrol#4973]
@dogmaphobic @LorenzMeier 

For users to test PX4 camera triggering, we need to send a `DO_DIGICAM_CONTROL` command, with Param 5 > 0. It would go on to the existing "Camera" page in QGC as a **button**, which would fire the trigger one-off.

![image](https://cloud.githubusercontent.com/assets/5557676/25004069/c0bb3f0c-2052-11e7-9f91-4abc14aa2f53.png)

There is a pending pull request (https://github.com/PX4/Firmware/pull/6973) which fixes triggering and makes sure that the command is handled properly.

**Comment by DonLakeFlyer** [comment]
It's already there. Swithch to the camera page in the center instrument panel.

**Comment by mhkabir** [comment]
![image](https://cloud.githubusercontent.com/assets/5557676/25012838/f64677ee-2071-11e7-85e1-5089c86234cf.png)
Where?

**Comment by DonLakeFlyer** [comment]
> Swithch to the camera page in the center instrument panel.

**Comment by DonLakeFlyer** [comment]
> Swithch to the camera page in the center instrument panel.

![screen shot 2017-04-13 at 8 55 17 am](https://cloud.githubusercontent.com/assets/5876851/25012987/f7c1481a-2026-11e7-85f2-75d55a8858bd.png)

But now I see you want it on the setup page as well. Makes sense.

**Comment by mhkabir** [comment]
Thanks! 

Yes, it would make sense to have it in setup. I don't think that anyone would want to do one-off triggering from the instrument cluster.

**Comment by mhkabir** [comment]
@DonLakeFlyer I can't find the camera page in the center instrument panel. Is that in master? I'm running the latest daily.

![image](https://cloud.githubusercontent.com/assets/5557676/25013681/e1f4716c-2074-11e7-966f-31610ec492bc.png)

**Comment by DonLakeFlyer** [comment]
It's been in master for about a month now

**Comment by mhkabir** [comment]
Maybe it's only enabled for APM ?

**Comment by DonLakeFlyer** [comment]
Nope. You aren't running the latest osx daily build. If you were it would crash, since it's broken right now.

**Comment by mhkabir** [comment]
Eugh, sorry about that. Didn't read :P

**Comment by mhkabir** [comment]
@DonLakeFlyer The "trigger camera" button does not seem to be actually sending anything to the vehicle. I'm checking for commands on the PX4 side, but no DIGICAM_CONTROL command comes through.

**Comment by LorenzMeier** [comment]
@mhkabir Your testing must be bad. It does arrive in Firmware.

**Comment by LorenzMeier** [comment]
The command sent is this: ```    sendMavCommand(FactSystem::defaultComponentId,
                   MAV_CMD_DO_DIGICAM_CONTROL,
                   true,                            // show errors
                   0.0, 0.0, 0.0, 0.0,              // param 1-4 unused
                   1.0);                            // trigger camera```

**Comment by LorenzMeier** [comment]
The root cause is this issue: https://github.com/mavlink/qgroundcontrol/issues/5045

**Comment by DonLakeFlyer** [comment]
Bad component id for command fixed here: https://github.com/mavlink/qgroundcontrol/pull/5048

**Comment by DonLakeFlyer** [comment]
@mhkabir This setup page is pretty out of whack. The TRIG_INTERFACE parameter doesn't seem to been the latest master firmware. Do you know what is going on there?

**Comment by mhkabir** [comment]
Hi @DonLakeFlyer It should be working just fine. I tested it multiple times over the last few days. 

Just in case, please use this branch, which includes many fixes : https://github.com/PX4/Firmware/pull/7201
