### ISSUE TITLE
Survey tool polygon glitch

### ISSUE THREAD

**Issue by feemi** [mavlink/qgroundcontrol#4996]
![survey tool glitch](https://cloud.githubusercontent.com/assets/1747208/25068208/86ce298a-2264-11e7-9d41-20a9b1801237.png)

When randomly editing polygon edges. Survey tool is failed.

**Comment by DonLakeFlyer** [comment]
I've been chasing that one for a while. Would be awesome if you could figure out a set of concrete repro steps for it.

**Comment by DonLakeFlyer** [comment]
Do you remember if you were just moving edges? Or if you also zoomed the map as well.

**Comment by tops4u** [comment]
I have had this Problem too recently. AFAIR this happened while paning and zooming around.

**Comment by DonLakeFlyer** [comment]
Closing since there are no concrete steps to reproduce. I believe there is a Qt bug somewhere causing this. Fingers crossed that 3.3 moe to 5.9 will fix.
