### ISSUE TITLE
unable to build current HEAD

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5025]
../src/MissionManager/MissionManager.cc:917:45: error: ‘MAV_MISSION_TYPE_MISSION’ was not declared in this scope
                                             MAV_MISSION_TYPE_MISSION);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~
Makefile:79438: recipe for target 'obj/MissionManager.o' failed

**Comment by dogmaphobic** [comment]
When was the last time you updated the submodules?
```
git submodule update
```

**Comment by AndKe** [comment]
oh, that's embarrassing ..   once i read "submodule" I knew you were right..
I'll close the issue and sit still in silent shame now.   :)
Thank you
