### ISSUE TITLE
Solo video not working

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5026]
iPad instead shows camera from iPad. Not sure if I just need to flip a setting. Haven't looked yet. Some discussion in #4513.

**Comment by dogmaphobic** [comment]
UVC video should be disabled for iPad. You will never be able to plug an UVC device to an iOS device.

**Comment by DonLakeFlyer** [comment]
It shows the video from my iPad camera whatever that means.

**Comment by dogmaphobic** [comment]
I just looked it up. UVC is actually enabled for iOS builds. That should not happen. I will create a separate issue for that.

**Comment by DonLakeFlyer** [comment]
Looks like it a problem with my Solo. I can't get video in the Solo app either.

**Comment by hamishwillee** [comment]
I tested this on Solo on daily build last week and it worked fine.
