### ISSUE TITLE
window map Delay very much

### ISSUE THREAD

**Issue by icesword001** [mavlink/qgroundcontrol#5036]
Today, I pull out the whole project from github, using qt5.8.0_windows  compiled to run it, when I quickly drag the map, map and the main program appear obvious delay,please tell me why?

**Comment by icesword001** [comment]
not offline map

**Comment by dogmaphobic** [comment]
Because you are using Qt 5.8, which is known to have this problem. That's why we use 5.7.1.

**Comment by DonLakeFlyer** [comment]
You need to use the supported version of Qt as specified in the readme. If it still happens let us know. The map needs to pull tiles from the internet so when you use it for the first time there will be lag.
