### ISSUE TITLE
Default component ID for PX4 incorrect (should be 0 for broadcast or 1 for param value, not 255)

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#5045]
@DonLakeFlyer This command is sent with system ID 1 (correct) and component ID 255 (why?)

```
sendMavCommand(FactSystem::defaultComponentId, MAV_CMD_DO_DIGICAM_CONTROL, true, // show errors 0.0, 0.0, 0.0, 0.0, // param 1-4 unused 1.0); // trigger camera
```

**Comment by DonLakeFlyer** [comment]
> sendMavCommand(FactSystem::defaultComponentId

Bug. sendMavCommand isn't translating FactSystem::defaultComponentIdto actual default component id.

**Comment by DonLakeFlyer** [comment]
Fixed in here: https://github.com/mavlink/qgroundcontrol/pull/5048
