### ISSUE TITLE
Bug in takeoff map item

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#5056]
A .plan that contaminate others QGroundControl with a bug:
The takeoff appear as 1 and not T
[.plan](https://files.gitter.im/mavlink/qgroundcontrol/LSB2/horus_mission.plan)

**Comment by patrickelectric** [comment]
![image](https://cloud.githubusercontent.com/assets/1215497/25400618/87cf1526-29c9-11e7-81b8-a715792e8ebb.png)

**Comment by booo** [comment]
I think that is fixed in newer versions.
