### ISSUE TITLE
Upload failure still shows mission in Fly view

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5060]
Test survey created
(latest today build)
<img width="1259" alt="screen shot 2017-04-26 at 02 59 36" src="https://cloud.githubusercontent.com/assets/3130363/25414961/aaa3eaf0-2a2c-11e7-952c-66640817cd2c.png">
<img width="1238" alt="screen shot 2017-04-26 at 02 58 39" src="https://cloud.githubusercontent.com/assets/3130363/25414963/aacaf762-2a2c-11e7-93da-d7998fcf49d6.png">
<img width="1266" alt="screen shot 2017-04-26 at 02 58 15" src="https://cloud.githubusercontent.com/assets/3130363/25414962/aac76aca-2a2c-11e7-97c1-89e7d47128ee.png">

This survey generates several thousand WP's

[t2.plan.txt](https://github.com/mavlink/qgroundcontrol/files/957008/t2.plan.txt)

Also, the Fly screen should show the mission as "retrieved" from the vehicle and not from the generated Planning screen

**Comment by DonLakeFlyer** [comment]
You have Hover and Capture turned on. That will generate waypoints to stop and take a picture at each interval.

> Also, the Fly screen should show the mission as "retrieved" from the vehicle and not from the generated Planning screen

Don't kow what you mean by that?

**Comment by lvale** [comment]
On those screenshots above on the FLY screen the waypoints shown (the orange ones) are the ones generated by the Planning screen, and not the ones that the drone has (in this case it had none). If there is a mission on the drone that should be the one shown on the FLY screen.

**Comment by DonLakeFlyer** [comment]
Can you give me the repro steps for that? Also I fixed a bunch of stuff around this two days ago. So make sure you are running latest.

**Comment by lvale** [comment]
Just generate a mission like the one above. Try to upload it to vehicle. It throws out an error about too big. Switch to Fly screen and the waypoints are there, although none is on the vehicle.

**Comment by DonLakeFlyer** [comment]
Oh, yeah. I had that one on my list of things to do. I'll fix it.

**Comment by DonLakeFlyer** [comment]
Fixed
