### ISSUE TITLE
Altitude change pop-up very short range and heading random change

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5062]
Latest QGC master, latest ArduPilot Copter master

Clicking on the Action to change altitude the elevator on the right only allows very small increments (10m ?)

<img width="1261" alt="screen shot 2017-04-26 at 03 13 05" src="https://cloud.githubusercontent.com/assets/3130363/25415319/d9cd2a38-2a2e-11e7-8857-33036710a263.png">
<img width="976" alt="screen shot 2017-04-26 at 03 12 24" src="https://cloud.githubusercontent.com/assets/3130363/25415320/d9efd272-2a2e-11e7-9111-e64a09008afa.png">

Also changing altitude is changing also the heading for some undetermined heading

**Comment by DonLakeFlyer** [comment]
Willing to consider new range. Any opinions?

**Comment by lvale** [comment]
I would go for a log slider, meter by meter on the first half, then tens of meters, and maximum range below 400ft (120m), and/or the possibility of inputting a number.

On a usability, and I know it's not easy, we have to move from the extreme left to the bottom middle to the extreme right of the screen for a single process. Couldn't we have these elements to be closer from one another ?

**Comment by DonLakeFlyer** [comment]
Log slider is way too much work for now. Also don't think I'll go back to allowing numeric entry. Just trying to close things out with major usability problems.

**Comment by pritamghanghas** [comment]
heading change is Ardupilot problem. It doesn't honor SET_POSITION_TARGET_GLOBAL_INT yaw parameter. There are several holes in arducopter mavlink implimentation. It is like anytime I use a command something is not implimented especailly when you have anything to do with yaw. Another day I was trying to specify rate of yaw change in a yaw change command, arducopter ignores that as well.

**Comment by amilcarlucas** [comment]
@pritamghanghas I did a couple of PRs for missing YAW implementations in Arducopter. Those PRs did not get accepted in the master branch, but if you apply them localy it might help you.

**Comment by pritamghanghas** [comment]
@amilcarlucas thank you for that. I generally stay away from touching flight code. But it is a pity that those didn't get accepted. QGC can't really use something that is not in mainline. Though I can use them personally.

**Comment by DonLakeFlyer** [comment]
I'm going to stay away from guided heading change for now. Depending on vehicle settings you can sort of achieve it with goto location. May consider at some point.
