### ISSUE TITLE
Takeoff action should allow height to takeoff

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5063]
Latest QGC master, latest ArduPilot Copter master

I understand the current behaviour mimics what DJI does, but I believe it should allow to change the takeoff height
<img width="477" alt="screen shot 2017-04-26 at 03 12 06" src="https://cloud.githubusercontent.com/assets/3130363/25415377/2ede9250-2a2f-11e7-8772-e1cd99a693b6.png">

**Comment by DonLakeFlyer** [comment]
And I've heard the exact opposite feedback to that as well. Trying to keep things as simple as possible. I think I'll keep it this way unless you can desribe an important use case where this is just bad behavior. The current use for this is just to get the vehicle off the ground so you can then fly manually.

**Comment by lvale** [comment]
Let's just say that a powerful hexa/octo at the default take off height is extremely affected by ground effect...

**Comment by DonLakeFlyer** [comment]
Hmm...

**Comment by sparky002** [comment]
Likewise with powerful quads. Please don't remove features for simplicity sake. This is something that could cause a massive safety issue. At least put an option there to do so. That way it still remains simplified but adjustable for different users.

**Comment by hamishwillee** [comment]
Maybe:
- UI element configurable based on type of vehicle or on an advanced mode selector in settings? 
- Link to param setting that configures takeoff height?

**Comment by lvale** [comment]
@DonLakeFlyer @hamishwillee 

At least in ArduPilot, I think PILOT_TKOFF_ALT http://ardupilot.org/copter/docs/parameters.html#pilot-tkoff-alt-pilot-takeoff-altitude is not being used

**Comment by hamishwillee** [comment]
I'm just updating the PX4 docs now. It uses [MIS_TAKEOFF_ALT](https://dev.px4.io/en/advanced/parameter_reference.html#MIS_TAKEOFF_ALT)

**Comment by DonLakeFlyer** [comment]
Unfortunately PILOT_TKOFF_ALT defaults to 0!

**Comment by Antiheavy** [comment]
I realize this is an old issue, but the current QGC documentation makes it look as if the request feature is now implemented?  https://docs.qgroundcontrol.com/en/FlyView/FlyView.html

**Comment by DonLakeFlyer** [comment]
Yup it is
