### ISSUE TITLE
Camera icons from Mission don't refresh

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5065]
Executed mission and the camera icons don't get removed, even after removing mission, and redoing new mission

Latest QGC and ArduPilot Copter

<img width="1256" alt="screen shot 2017-04-26 at 17 56 50" src="https://cloud.githubusercontent.com/assets/3130363/25447012/6022bb44-2aab-11e7-962c-6526b1dc2799.png">

**Comment by DonLakeFlyer** [comment]
Trajectory line removal is not quite correct either. Thought I had an issue for that already can't find it now.

**Comment by lvale** [comment]
Also curiously running twice the same mission, the camera icons get placed near but not at the same locations (running SITL)

**Comment by DonLakeFlyer** [comment]
That would be a firmware thing.

**Comment by DonLakeFlyer** [comment]
Fixed now
