### ISSUE TITLE
Camera gimbal setup changing wrong parameters

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#5078]
After the RC/Servo input/output split in APM (and subsequent changes in QGC to support this), the servo limits and reverse options in the camera setup tab are applying to the RCn_ input parameters, instead of the SERVOn_ output parameters.

**Comment by DonLakeFlyer** [comment]
Have you verified this? QGC has parameter remapping. Is that not working?

**Comment by jaxxzer** [comment]
Yes, I've verified this. The RCn_FUNCTION -> SERVOn_FUNCTION parameter remapping is working, but the limits and reverse are still applied to the RCn_ group.
