### ISSUE TITLE
QGC does not allow disarm before landed even in completely manual modes

### ISSUE THREAD

**Issue by MaEtUgR** [mavlink/qgroundcontrol#5118]
I curretly use the daily build from 25.04.17 on the PC and it does not let me disarm per QGC UI while I'm not landed even in manual modes.

I don't know if that's intended but I would let this kind of logic be handeled by the autopilot firmware. You can still send the disarm command and it will get rejected if it's not appropriate. Otherwise you always need to adapt for new use cases in the logic on both sides which get's unmaintainable.

**Comment by DonLakeFlyer** [comment]
That is intended. The fact is that the whole way a ground station needs to implement guided actions: Takeoff, Land and so forth is pretty much unmaintainable. This example is just the tip of the iceberg with regards to the state machine on the ground station side to support this stuff. Lorenz and I have been in discussion about standardizing a mavlink spec for it which will fix this.

My plan has been to have Disarm while not landed instead confirm an emergency stop if the vehicle is not landed.

**Comment by MaEtUgR** [comment]
> This example is just the tip of the iceberg...

>  ...have been in discussion about standardizing a mavlink spec for it which will fix this.

This is only a symptom of a well known bigger problem that requires restructuring to fix but this issue does not help anymore.
