### ISSUE TITLE
Plan AutoLoad not working.

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#5140]
QGC finds the file and calls `PlanMasterController::sendPlanToVehicle()` with it but nothing happens. It seems a new instance of `PlanMasterController` is created, the file is loaded and then the instance is deleted without doing anything with it.

**Comment by DonLakeFlyer** [comment]
Oops. It's missing the sendToVehicle call after the loadFromFile.

**Comment by DonLakeFlyer** [comment]
A bit more screwed up than that. Working on it.
