### ISSUE TITLE
Windows daily builds are not getting pushed to S3

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5161]
@dagar Can you take a look?

**Comment by dagar** [comment]
This is weird, according to many appveyor builds it's still successfully deploying QGroundControl-Installer.exe

**Comment by dagar** [comment]
Made a couple changes at the appveyor settings level. Test build https://ci.appveyor.com/project/mavlink/qgroundcontrol/build/master-5035

**Comment by DonLakeFlyer** [comment]
Still not working as far as I can tell

**Comment by tubeme** [comment]
Not working yet...

**Comment by dagar** [comment]
I'm really at a loss here. Nothing has changed in the appveyor config since it stopped working.
Trying again https://ci.appveyor.com/project/mavlink/qgroundcontrol

**Comment by tubeme** [comment]
I get this error right now:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B1A7F1D762F084D3</RequestId>
<HostId>
GW2W8HIG7olBZ0KhLqCxImwlxNA1paq4PpliBUvmw3klUKDuEdojhnkYC6/B46bNZo96vpWdPes=
</HostId>
</Error>

**Comment by DonLakeFlyer** [comment]
Fixed
