### ISSUE TITLE
Intrument panel overlaps multi-vehicle radios

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5163]
![screen shot 2017-05-16 at 11 55 33 am](https://cloud.githubusercontent.com/assets/5876851/26123115/9f739bf0-3a2e-11e7-90bb-506c8549230c.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you take this one. The code here seems different from last I looked. Things used to be top anchored to the bottom of these radios. Now the instrument stuff seemds to be anchored to the bottom. Don't want to screw anything up here with plugin and so forth.

**Comment by dogmaphobic** [comment]
Gazebo is broken. That's the only way I know how to test multiple vehicles (other than actually starting multiple vehicles, which is a bit of a pain :P ) I will take a look when that gets fixed.

**Comment by DonLakeFlyer** [comment]
Start up two MockLink vehicles

**Comment by hamishwillee** [comment]
And just should anyone find this in future, there is information about [Mock Link here](https://dev.qgroundcontrol.com/en/tools/mock_link.html)
