### ISSUE TITLE
ArduPilot: Look into flow support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5212]

**Comment by proficnc** [comment]
Thanks Don

**Comment by DonLakeFlyer** [comment]
@proficnc What's the URL for the ArduPilot flow firmware?

**Comment by proficnc** [comment]
http://download.ardupilot.org/downloads/wiki/advanced_user_tools/px4flow-klt-06Dec2014.zip

**Comment by proficnc** [comment]
Thanks for looking at this

**Comment by DonLakeFlyer** [comment]
How it will work. QGC remembers the last firmware type you flashed and uses that to prime the firmware type selection for the PX4 Flow as well:
![screen shot 2018-05-25 at 6 37 40 pm](https://user-images.githubusercontent.com/5876851/40571275-ea590216-604a-11e8-853e-f12ce9347fb1.png)

So in a lot of cases this should by default end up matching what you want.

**Comment by DonLakeFlyer** [comment]
@proficnc I need a url to .px4 file for the PX4 Flow. A zip file won't work.

**Comment by DonLakeFlyer** [comment]
I'll ask the dev folks.

**Comment by DonLakeFlyer** [comment]
This is all done and ready to go. I just need a url to download from.

**Comment by proficnc** [comment]
I will ask @Tridge to put it somewhere better.

**Comment by proficnc** [comment]
Thanks to Tridge...

http://firmware.ardupilot.org/Tools/PX4Flow/
