### ISSUE TITLE
Some Functions are not working with Arducopter 3.2.1 on an APM

### ISSUE THREAD

**Issue by Idefix0496** [mavlink/qgroundcontrol#5222]
It shows me always -1 mAh for the Already Consumed mAh
I can't set Rally Points
There are some Pop-Ups which say that some Parameters are missing, therefore one thing which is restricted is the Auto_Takeoff

**Comment by DonLakeFlyer** [comment]
Can you tell me which parameters is says are missing?

**Comment by Idefix0496** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/28847697/26561286/6bb9a7a2-44bd-11e7-85bc-92935c8b17b0.png)
Hi
I've attached the Errors I could reproduce. The Upload of Missions is sometimes working.

**Comment by DonLakeFlyer** [comment]
I took a look at this. 3.2 is just too old with too many differences. The best QGC can support for ArduCopter is 3.3.

**Comment by hamishwillee** [comment]
Hi Don, 

how about  [here](https://docs.qgroundcontrol.com/en/) we change:
> Full setup/configuration of ArduPilot and PX4 Pro powered vehicles.
to
>Full setup/configuration of ArduPilot (3.3.3+) and PX4 Pro powered vehicles.

If reasonable, we could also publish the last QGC version that supports ArduCopter 3.3?
