### ISSUE TITLE
QGC tries to install wrong PX4 firmware version on Pixhawk2.1 

### ISSUE THREAD

**Issue by tstellanova** [mavlink/qgroundcontrol#5227]
QGC 3.1.3 by default wants to load px4fmu-v2_default onto the Pixhawk2.1 (ProfiCNC / Hex):

"From: http://px4-travis.s3.amazonaws.com/Firmware/stable/px4fmu-v2_default.px4"

Instead it should load px4fmu-v3

**Comment by dagar** [comment]
Thanks for reporting. It's actually this issue - https://github.com/mavlink/qgroundcontrol/issues/4440

Pixhawk 1, 2, 2.1 all report the same id, but we can select the binary based on the available flash size reported by the bootloader.

**Comment by DonLakeFlyer** [comment]
Closing to use #4440 instead
