### ISSUE TITLE
It's so strange about UDP for Video Stream

### ISSUE THREAD

**Issue by HTaeHyeon** [mavlink/qgroundcontrol#5238]
![default](https://cloud.githubusercontent.com/assets/11404394/26762662/f6ee26e6-4980-11e7-928d-3cb8c207c0e3.png)
![gstreamer](https://cloud.githubusercontent.com/assets/11404394/26762663/f6f7ab44-4980-11e7-8946-1743e8d7f095.png)

I have Some Problems about Video Stream.
My computer's System is Windows.
And I use Gstream for windows,  but I can't use Video Stream for UDP.
Display always display the picture which attached image.
So I can't display my video. How do I do?

**Comment by jaxxzer** [comment]
When launching in 'GPU compatability mode' on windows machine, I see the ArduSub image in the video window, sort of like this. The ArduSub image also appears red when this happens.

**Comment by HTaeHyeon** [comment]
Thank you so much.
I got a problem. I've forgotten that I didn't install Graphic Driver.
After installing Graphic Driver, and then It works very well. Thank you.
