### ISSUE TITLE
Current Master crashes on Mac

### ISSUE THREAD

**Issue by tops4u** [mavlink/qgroundcontrol#5262]
Downloaded Current Master yesterday and it crashes immediately at Startup on a Mac on OS X Sierra.

**Comment by jaxxzer** [comment]
Likely a duplicate of https://github.com/mavlink/qgroundcontrol/issues/5240

**Comment by tops4u** [comment]
@jaxxer yes this is most probably the case. Sorry I haven't seen the other issue. So I'll close here.
