### ISSUE TITLE
Talk to Gus about 500000 baud rate

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5280]
From pull #5279

**Comment by dogmaphobic** [comment]
Regular drivers Windows don't support arbitrary baud rates.

**Comment by DonLakeFlyer** [comment]
@antiheavy Hmm. This worked for you didn't it?

**Comment by Antiheavy** [comment]
Yep.

**Comment by DonLakeFlyer** [comment]
I guess since it worked it's ok.
