### ISSUE TITLE
ArduPIlot: Pre-Flight baro help text update

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5282]
From @wickedshell: "I know it's really annoying and verbose but for the plane one I would consider adding a note that trys to explain that you want to block the tube from the wind without sealing any of the holes on the probe"

Need to come up with something better.

**Comment by DonLakeFlyer** [comment]
For docs: "To calibrate the airspeed sensor shield it from the wind, without blocking any of the holes on the airspeed sensor."

**Comment by DonLakeFlyer** [comment]
PX4 text should change as well to be better.

**Comment by hamishwillee** [comment]
How about: "You must not touch the sensor or obstruct any holes during the calibration.' OR "Do not touch the sensor or obstruct any holes during the calibration."
