### ISSUE TITLE
Takeoff in flow simulation

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#5283]
Is it correct that QGC sends a `Loiter` if you press the takeoff button? Why does it not send a `Takeoff`?

It seems to have a weird behavior on the flow simulation -> `make posix_sitl_ekf2 gazebo_iris_opt_flow`. When pressing takeoff, the output is `INFO  [tone_alarm] negative` three times until the quad takes off. The reason seems to be that the command is Loiter and not takeoff.

**Comment by DonLakeFlyer** [comment]
> Is it correct that QGC sends a Loiter if you press the takeoff button?

No, that is not correct. It:
* Arms
* Sets mode to Guided (ArduPilot only)
* Send a MAV_CMD_NAV_TAKEOFF command
