### ISSUE TITLE
Hardware UART not working on Android

### ISSUE THREAD

**Issue by gigorvd** [mavlink/qgroundcontrol#5287]
I use QGROUNDCONTROL under Android.
Tested on ASUS tinker board Android 6 and raspberry pi Android 7.
If I connect the pixhawk via USB-UART Adapter, the connection is good.
But I do not connect pixhawk to QGC via hardware GPIO-UART (GPIO 14 txd0, GPIO 15 rxd0 to telem2 port in pixhawk).
Do QgroundControl can run on Android with a hardware uart (not usb)?

**Comment by DonLakeFlyer** [comment]
Questions should go here: http://discuss.px4.io/c/qgroundcontrol. Issues are for bugs.
