### ISSUE TITLE
Toolbar is too large in daily build.

### ISSUE THREAD

**Issue by sh83** [mavlink/qgroundcontrol#5294]
Main toolbar buttons consume too much space on phone screen. Appears only in daily build. Latest release is ok. See screenshots for detail.
![screenshot_2017-06-14-12-14-04](https://user-images.githubusercontent.com/28092124/27125250-5c169d32-50fc-11e7-9c26-452f5ab0e24a.png)
![screenshot_2017-06-14-12-16-07](https://user-images.githubusercontent.com/28092124/27125251-5c18951a-50fc-11e7-8ed5-150e2f3ef3d0.png)

**Comment by DonLakeFlyer** [comment]
What type/size device?

**Comment by sh83** [comment]
It is andrid smartphone: oneplus one, 1920×1080 px, 5.5'.

**Comment by alpha-numericon** [comment]
Same issue: 1920x1080, 4.95" Android phone. Looks like it was introduced in 1f77b2f7113891bf395c07d410607f3068531db5.

**Comment by sh83** [comment]
Fixed in last build. Thank you.

**Comment by DonLakeFlyer** [comment]
Great, thanks for verifying.
