### ISSUE TITLE
QGC 3.1.3: bounding box shown for offline map tile set is incorrect

### ISSUE THREAD

**Issue by tstellanova** [mavlink/qgroundcontrol#5295]
Here's how I encountered this:
- add a new tile set in Offline Maps
- select an area less than a mile wide in each dimension
- select Bing Maps Hybrid
- click Download
- Return to list of offline tile sets
- select the tile set you just created
- a map of the entire world is presented. If you zoom in on the region you selected for the tile site, a long narrow, half-world-wide red bounding box is presented as the bounding box of your tile set.
- zoom in further on the tile set region, and the red bounding box extends off to (Japan) from your actual tile set region.  A maybe 10% alpha red overlay indicates your actual tile set region.
- See attached image.
- Tested on Mac OSX 10.11.16

![offline-maps-bounding-qgc_3_1_3](https://user-images.githubusercontent.com/1440229/27141096-240a6ef2-50dc-11e7-8266-5834205f0741.jpg)

**Comment by dogmaphobic** [comment]
I repeated the steps to the letter. Twice. Could not reproduce it.

<img width="1120" alt="screen shot 2017-06-26 at 10 59 40 pm" src="https://user-images.githubusercontent.com/749243/27569012-3bc850e0-5ac3-11e7-8732-f5dd6a2488d1.png">

**Comment by DonLakeFlyer** [comment]
@tstellanova Can you try to reproduce your steps using a daily build?

**Comment by dogmaphobic** [comment]
Bing "Hybrid" (not that it would make any difference)
Also, I'm running maxOS 10.12.5 but I can't think of a reason for the to be an issue either.

<img width="1120" alt="screen shot 2017-06-26 at 11 06 28 pm" src="https://user-images.githubusercontent.com/749243/27569187-29cc2690-5ac4-11e7-88bf-87f2906824b9.png">

**Comment by NaterGator** [comment]
I've reproduced this once or twice. I'll see if I can get a consistent
repro on Windows.

**Comment by DonLakeFlyer** [comment]
This smells like a Qml MapQuickItem bug. This sort of thing happens with mission planner Survey items every once in a while as well. I've never been able to nail it down.

**Comment by DonLakeFlyer** [comment]
Does anyone have a consistent repro case?

**Comment by DonLakeFlyer** [comment]
Without a reproducible case not much we can do here
