### ISSUE TITLE
Cannot control PX4 SITL using virtual joystick

### ISSUE THREAD

**Issue by AStudentProgrammer** [mavlink/qgroundcontrol#5304]
![screenshot from 2017-06-17 17 49 49](https://user-images.githubusercontent.com/29500788/27252039-d35b5afe-5386-11e7-9170-e5698b16cfb2.png)
I'm using Qgroundcontrol 3.1.3 as my ground station and I want to use the virtual joystick without a real RC or joystick radio by setting COM_RC_IN_MODE to 'Joystick/No RC Checks'. I can arm motors using the Qgroundcontrol software. However, an error message in my terminal as seen from the picture below kept appearing and I do not know how to solve this error. Also, I can't seem to manually control my PX4 SITL drone using the virtual joysticks to. Also, many times, the error message 'ERROR [sensors] Accel #0 fail: TOUT!' and 'ERROR [sensors] Gyro #0 fail: TOUT!' appears constantly. Does anyone know how to solve this?

**Comment by DonLakeFlyer** [comment]
These are all firmware question both from a setup standpoint and an error message standpoint. If after you get everything setup correctly with no errors and it is still not working please post on the QGC forum to start: http://discuss.px4.io/c/qgroundcontrol
