### ISSUE TITLE
Font szies too small on Linux

### ISSUE THREAD

**Issue by smafaith** [mavlink/qgroundcontrol#5306]
I' m using Qt creator to build qgroundcontrol source code, and the version is development master. The fonts and images are too small for my laptop and I' m wondering if I'm able to make some changes to source code to fix the display error. Thank you. 
![desktop](https://user-images.githubusercontent.com/22068211/27261482-6bfcaade-5476-11e7-94ff-63176fd51913.png)

**Comment by DonLakeFlyer** [comment]
I'll check Linux font sizes.

Till then: Settings/General page - change font size

**Comment by smafaith** [comment]
I have to say, that really works. Maybe large size font is a must for coding.
