### ISSUE TITLE
RTK toolbar indicator needs new icon

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5324]

**Comment by dogmaphobic** [comment]
Is there a way to have this to show up even if I don't have the hardware?

**Comment by DonLakeFlyer** [comment]
Hmm, not really. Switch out the regular gps one for testing instead? Or just send it to me and I can try it.

**Comment by DonLakeFlyer** [comment]
Done

**Comment by Francklin2** [comment]
Hi there is some icon found on the net , the second one upper left showing a ground base could be good for the RTK groundstation

I found them here 
https://previews.123rf.com/images/tul/tul1505/tul150500002/40031487-antenne-satellite-et-ic-nes-symboles-de-vecteur-de-mono-Banque-d'images.jpg

![image](https://user-images.githubusercontent.com/17847024/32693078-a266a63a-c724-11e7-9ace-cc2bdd90e087.png)
