### ISSUE TITLE
VTOL Mission landing not correct.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#5336]
Given the frame is a VTOL, when you create mission the take off is VTOL take off by default. But the landing is airplane landing by default. So you have to go to the menus to choose VTOL landing.

**Comment by DonLakeFlyer** [comment]
Not sure what you are talking about. There is no automatic adding of a landing item?

**Comment by sanderux** [comment]
@tubeme NAV_FORCE_VT is enabled by default. This means even a regular LAND mission item will perform a VTOL_LAND
