### ISSUE TITLE
VTOL: Transition action or menu item

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#5337]
@DonLakeFlyer managing a VTOL solely through QGC is missing one important feature;
The user must be able to set the flight mode (Hover or Forward flight)
Ideally it is shown next to Arm status by showing the current mode and clicking it to change mode.

Getting state: https://pixhawk.ethz.ch/mavlink/#MAV_VTOL_STATE
Switching state: https://pixhawk.ethz.ch/mavlink/#MAV_CMD_DO_VTOL_TRANSITION

**Comment by DonLakeFlyer** [comment]
I'll take a lot at that in 3.3

**Comment by sanderux** [comment]
Hi @DonLakeFlyer 
Do you have any progress on this? It is a highly requested feature for clients

**Comment by DonLakeFlyer** [comment]
@sanderux Can you test this once it gets through the build system. I tested with SITL but it seems like the VTOL gazebo support may be strange/buggy? When I transition to forward flight, it sticks for a few seconds then just switches back.

**Comment by sanderux** [comment]
i'm not getting any action when switching with the current daily

**Comment by DonLakeFlyer** [comment]
Do you get the slider?

**Comment by sanderux** [comment]
yes, it seems to be missing sending the actual command in the pr

**Comment by DonLakeFlyer** [comment]
Crap there are some changes missing...
