### ISSUE TITLE
Survey: having a survey with specified camera does not take photos

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5369]
Create a survey, check the mission items, there is no cam_trig_dist items, no photos would be taken.

**Comment by AndKe** [comment]
sorry, it does, it's just that downloading a mission from the vehicle, I expected to see those commands , but they are integrated into waypoints and presented together.

**Comment by DonLakeFlyer** [comment]
Yeha, that's new in 3.2. Same for flight speed changes in waypoint
