### ISSUE TITLE
Solo: Mission upload stuck

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5370]
Uploading a mission to 3DR Solo, works well, it ends with the yellow "flight plan received" message.
the sync button, however, continue to rotate. there is no way to reset, download/upload or load/save until QGC is restarted.

**Comment by AndKe** [comment]
Re-tested that a lot today. (using Solo only, as it and RX100 camera was the testing object) 
It's perfectly reproducible.

- Start QGC (master)  (in this case Ubuntu desktop)
-load, or create a survey
-connect 3DR solo (latest original Solo firmware, not based on fresh ArduCopter)
-in upper right corner, there will be a button that urges to upload, use that *OR* the "Sync/upload" button
-observe a huge DONE / and "flight plan received" 
-the sync button spinning animation continues, the button is now useless.
-the "flight view" does not display the uploaded mission.

-close/open application
-flight view displays correctly the complete mission that was uploaded.
-same problem will spawn again if anything is attempted uploaded to solo.

**Comment by DonLakeFlyer** [comment]
Thanks, hopefully I can repro on my Solo.

**Comment by AndKe** [comment]
if not, I'll send you tlogs, there is most likely a difference in what the AP say at the end of transmission.

**Comment by DonLakeFlyer** [comment]
It repros for me

**Comment by DonLakeFlyer** [comment]
GeoFence bug. Also the likely reason why the Fly view isn't showing mission correctly some times.

**Comment by AndKe** [comment]
I can still reproduce it at master b682031e7  
to reproduce: 
-connect to a Solo with a mission on board
-in planning view, download mission
-upload mission
-the spinning animation will not stop.
![screenshot from 2017-07-04 09-50-59](https://user-images.githubusercontent.com/1468842/27821484-b32a77aa-60a2-11e7-97bd-fac778bd571e.png)

**Comment by Otusbubo** [comment]
Did some in-office testing yesterday, and experienced this problem on both an iPad and an Android tablet.  Worked around it by uploading, experiencing the "sticking," closing qGC, reopening, then downloading the mission from the Solo.  Will flight test later today.

**Comment by DonLakeFlyer** [comment]
I tried this on latest daily build and it is working fine for me now. Can you folks retest with latest daily and I'll reopen if still there.
