### ISSUE TITLE
QGC allow max 75% of overlap when planning survey

### ISSUE THREAD

**Issue by FPVflyer** [mavlink/qgroundcontrol#5377]
Hi Guys,
I noticed that QGC doesn't allow a frontal picture overlap higher than 75% when planning a survey. When I do mapping of mountains and forest, I need to go for 80-85% of frontal overlap, but the system give an alert as maximum value allowed is 75%. Please can you increase that value?

Best Regards

**Comment by mhkabir** [comment]
Ok this is already done. @FPVflyer had been using an old build.

![image](https://user-images.githubusercontent.com/5557676/27760100-dd3158b8-5e5c-11e7-9041-6734c4bb6df9.png)

**Comment by DonLakeFlyer** [comment]
This pointed me to another bug, which is that the overlap values should have a min of 0, which I just fixed.
