### ISSUE TITLE
Current master enables isight on MacBook Pro by default, which is irritating

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#5380]
@dogmaphobic We should not enable the standard webcam by default.

**Comment by DonLakeFlyer** [comment]
I've noticed the same thing with my android tablet. The video always shows the camera from the tablet which is odd.

**Comment by dogmaphobic** [comment]
This should not be this way. UVC is supposed to be an option (disabled by default). I'll take a look.

**Comment by DonLakeFlyer** [comment]
I think the problem is if it finds a valid UVC device it automatically switches to it.
