### ISSUE TITLE
DJI F450 Frame - Airspeed is missing.

### ISSUE THREAD

**Issue by andylamp** [mavlink/qgroundcontrol#5387]
Hello,

 I've got couple of DJI 450 frames hooked up with Pixhawk and everything works jolly fine. There is a slight problem though, although I have installed an Airspeed sensor (looks like this [one](https://www.3dxr.co.uk/product/digital-air-speed-sensor-pixhawk-1-2-i2c-df13-connector/)) on the frame it does not show anywhere in the UI so... I don't know if it's working or something else is happening. I've tested both with an I2C bridge and without... pins on both ends read the correct voltage so am sure it's powered on and works (I've tried with two sensors with no luck on showing up...). The I2C connection is fine as I can see the Magnetometer from the ublox GPS module. I don't think anything is kaput as I've tried with different sensors/pixhawks etc.

Any idea as to what might be going on?

**Comment by LorenzMeier** [comment]
There is no airspeed support on multicopter on any flight stack QGC supports as far as I know.
