### ISSUE TITLE
Plan view: please allow clicking on the lower mission items

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5398]
It would be nice if clicking on the lower set of mission items highlighted the correct mission item, or - behaved as if the one in the map were clicked. (that would also workaround the "Z-problem")

![screenshot from 2017-07-04 09-49-46](https://user-images.githubusercontent.com/1468842/27821205-c6b3bc56-60a1-11e7-9520-cbe64fb05485.png)

**Comment by DonLakeFlyer** [comment]
Hmm, I'll have to look. I thought that was already working. Maybe it broke somewhere along the way.

**Comment by DonLakeFlyer** [comment]
No it doesn't work. I'll make it work in 3.3. For now you can click on something in the map to get close and then scroll the right hand mission item list to get to way you want and click there.

**Comment by DonLakeFlyer** [comment]
Supported now
