### ISSUE TITLE
What causes different primary instrument design. 

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5399]
In both case same version, but looks very different. both displayed on HD displays, so it cannot be due to display resolution ?

![20170704_224032](https://user-images.githubusercontent.com/1468842/27842454-8e8b20d0-610a-11e7-9eff-9f3d8a3f3836.jpg)

**Comment by jaxxzer** [comment]
Click the gear icon next to the artificial horizon, click 'Show large compass'.

**Comment by AndKe** [comment]
thanks, that was embarrassingly easy :)
