### ISSUE TITLE
Mission speed displayed differently

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#5404]
When changing the the flight speed in mission start the whole mission will have this flight speed (see flight plot) but the it is not displayed this way (current master)
![qgc_mission_speed_1](https://user-images.githubusercontent.com/14769636/27912968-e7d04864-625e-11e7-8804-d867c93edbb7.png)
![qgc_mission_speed_2](https://user-images.githubusercontent.com/14769636/27912973-ee9f89de-625e-11e7-8062-e58559a30389.png)
![mission_flight_speed_same](https://user-images.githubusercontent.com/14769636/27913106-52be504e-625f-11e7-9db4-04158b9d3b80.png)

So changing/updating the displayed value for future waypoints fixes this.

**Comment by DonLakeFlyer** [comment]
Are you talking about the grayed out flight speed values in subsequent waypoint items? Those are just the default flight speed. Not meant to  indicate the flight speed you may have set before that waypoint. But still if that's it, it is confusing and would be better if it showed the previous flight speed set.

**Comment by ChristophTobler** [comment]
Yup, that's what I meant.

**Comment by DonLakeFlyer** [comment]
Fixed

**Comment by estherpolie** [comment]
hi Don , where is the source code for flight speed
