### ISSUE TITLE
"Simple" control mode selectable while in PX4

### ISSUE THREAD

**Issue by nkhoit** [mavlink/qgroundcontrol#5411]
The "Simple" flight mode from Ardupilot in the mode selection drop-down is selectable while you're flying a PX4 drone.

**Comment by DonLakeFlyer** [comment]
There is a "Simple" flight mode in PX4 as well.

**Comment by dagar** [comment]
Actually there isn't. https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h#L45

I've copied this header into QGC to try and keep them straight. https://github.com/mavlink/qgroundcontrol/blob/348949d3755d70682a94b2996eb931196fb4cff5/src/FirmwarePlugin/PX4/px4_custom_mode.h

**Comment by DonLakeFlyer** [comment]
@LorenzMeier What's up with Simple? I put it in ages ago when you told me to. Did this disappear?

**Comment by LorenzMeier** [comment]
It did. I'm wondering if I should quickly add it or not.

**Comment by LorenzMeier** [comment]
Fixed here: https://github.com/mavlink/qgroundcontrol/pull/5422
