### ISSUE TITLE
Missing topics in analyzer

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#5432]
I pulled master and now I don't see all the topics anymore in the analyzer. I just see the ones in the image.
![qgc_analyze](https://user-images.githubusercontent.com/14769636/28164879-b31403fe-67d1-11e7-90ef-822ce64beba8.png)
It still worked with https://github.com/mavlink/qgroundcontrol/commit/b682031e7b17ec10a92fc65af29f6bbf93939ba7

**Comment by jgoppert** [comment]
I can confirm.

**Comment by DonLakeFlyer** [comment]
Most likely broken by this: https://github.com/mavlink/qgroundcontrol/pull/5420

**Comment by DonLakeFlyer** [comment]
I just tried QGC master against px4 firmware master SITL using both a V1 and V2 connection and it all worked fine?

**Comment by DonLakeFlyer** [comment]
Ok, master seems to work for me but Stable 3.2 does not. Hmm?

**Comment by DonLakeFlyer** [comment]
This is in master and stable 3.2 now, but will require point release on Stable. Will do that in a few days to collect other fixes.

**Comment by ChristophTobler** [comment]
Works in master. Thanks!
