### ISSUE TITLE
UDP video stream (GStreamer) not working

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#5447]
I can run the instructions from here successfully:
https://github.com/mavlink/qgroundcontrol/tree/master/src/VideoStreaming

And I can use the PX4 SITL stream with those. But it never shows up in QGC. Did the addition of RTSP and other sources break the interface?

<img width="1001" alt="screen shot 2017-07-16 at 19 23 56" src="https://user-images.githubusercontent.com/1208119/28249783-89f75bfa-6a5c-11e7-9cb7-a433afc073a8.png">

**Comment by jaxxzer** [comment]
Have you selected UDP stream in the 'General' Settings? Do you see any video related errors in the Console?
