### ISSUE TITLE
Build apk failed in qtcreator, ubuntu 16.04 x64 with AS 2.3.1 SDK

### ISSUE THREAD

**Issue by roger-zhao** [mavlink/qgroundcontrol#5453]
Here is the error msg:
Building Android package using ant.
Using ant: /home/zyj/Work/QGC-build-env/apache-ant-1.9.9/bin/ant
Buildfile: build.xml does not exist!
Build failed
Building the android package failed!
14:27:10: The process "/home/zyj/Qt5.7.1/5.7/android_armv7/bin/androiddeployqt" exited with code 14.
Error while building/deploying project qgroundcontrol (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.7.1))
When executing step "Build Android APK"

**Comment by DonLakeFlyer** [comment]
GitHub issues are for bugs. For dev setup problems use forums or gitter.
