### ISSUE TITLE
Ubuntu: libQt5QuickTemplates2.so.5 missing from appimage

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#5454]
The power screen is doesnt render on ubuntu.
tested on 3.2 and latest master

The log shows "QGCGroupBox unavailable" in PowerComponent.qml, saving the log also fails.

![image](https://user-images.githubusercontent.com/14801663/28259717-e59dd65c-6ad7-11e7-8295-68f3545c491c.png)

![image](https://user-images.githubusercontent.com/14801663/28259804-5a31ba74-6ad8-11e7-8971-a4ce8f0f5ddb.png)

**Comment by sanderux** [comment]
PS: this is the appImage

**Comment by DonLakeFlyer** [comment]
I just downloaded 3.2 AppImage onto Ubuntu 14.04 and ran without problem. Hmm?

**Comment by kd0aij** [comment]
can't reproduce on Ubuntu 16.04 either

**Comment by sanderux** [comment]
perhaps you guys have some other version of qt5quick ?

**Comment by DonLakeFlyer** [comment]
I can reproduce on a clean 16.04

**Comment by DonLakeFlyer** [comment]
@dagar @peterbarker Could any of the Linux folks out there take a look at this? I know nothing about AppImage.

**Comment by peterbarker** [comment]
@DonLakeFlyer This is the first time I've heard the term "AppImage", sorry!

**Comment by sanderux** [comment]
According to @dagar this is where to look: https://github.com/mavlink/qgroundcontrol/blob/master/QGCSetup.pri#L104

**Comment by DonLakeFlyer** [comment]
Sorry @peterbarker I thought you had added the AppImage support. Got that wrong!

**Comment by DonLakeFlyer** [comment]
@sanderux Can you try the latest daily build?

**Comment by sanderux** [comment]
I tried latest daily (2017-07-19 18:23:39 -07.00) and still have the same issue.
i saw you added  libQt5QuickControls2.so.5
I think this should be libQt5QuickTemplates2.so.5

**Comment by DonLakeFlyer** [comment]
Trying again. I have a feeling it needs both.

**Comment by kd0aij** [comment]
confirmed: adding libQt5QuickTemplates2.so.5 fixes the PX4 "Power" menu page (not needed for ArduPilot)

**Comment by DonLakeFlyer** [comment]
@sanderux Can you try as well? Want to make doubly sure before I announce 3.2 ready

**Comment by sanderux** [comment]
I can do that in a few hours

**Comment by sanderux** [comment]
Confirmed, works
![image](https://user-images.githubusercontent.com/14801663/28437577-6973dc54-6d9b-11e7-83e5-39953cfa30e8.png)

**Comment by DonLakeFlyer** [comment]
Thanks everyone

**Comment by barchstien** [comment]
Hi guys
Thanks for the fix
Thought it still is failing when running the archive
The AppImage is just fine
So I guess it's only an update of the archive missing

**Comment by DonLakeFlyer** [comment]
Ok, I guess that must be in a different place. I'll look.

**Comment by DonLakeFlyer** [comment]
Doesn't the archive version require you to install Qt yourself?

**Comment by DonLakeFlyer** [comment]
@dagar Isn't this the case?

**Comment by dagar** [comment]
I believe it was able to run entirely from the contents of the archive at one point. I wouldn't mind dropping the archive and only having the appimage. Anything more than that should be a package.

**Comment by DonLakeFlyer** [comment]
I would like to drop the archive as well. Too many things to keep up to date. Only one thing to keep running would be great.

**Comment by DonLakeFlyer** [comment]
I'm going to drop the archive from the docs for now and see if anyone complains.
