### ISSUE TITLE
Voice reads "m" as minutes rather than meters

### ISSUE THREAD

**Issue by jliphard** [mavlink/qgroundcontrol#5455]
For some error messages, the message contains distances in units of meters. E.g. "Mission not accepted - move landing approach 3m further" (or similar). The voice reads this as "3 minutes" rather than "3 meters".

**Comment by dagar** [comment]
Interesting, I had no idea it was expanding units. I wonder if that's intentional.

These error messages are coming from the firmware. For the proper fix long term this goes back to our favorite topic - http://discuss.px4.io/t/event-interface/2318/11
