### ISSUE TITLE
Custom Command Widget issues

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#5462]
A few issues arising from creation of [docs](https://dev.qgroundcontrol.com/en/tools/custom_command_widget.html). Tested on 3.2

1. Changing the value of a parameter field (as in example) is fiddly
   * Clicking Enter does not save the value/change focus. 
   * Clicking outside the editor in the dialog does not save value/change focus.
    * You have to actually click outside the whole widget dialog to get value to save
2. When in focus there is a question mark on the right of the text field that doesn't appear to do anything
3. There is some sort of odd caching going on. If you connect to a vehicle and load a dialog it stays active even after the vehicle is disconnected. I'd expected if you can't interact with a vehicle that the whole dialog should be greyed out.

As an aside, ... 
This functionality makes it easy for developers to quickly test custom commands. However I'd see it as even more useful if it could be used for "products". E.g. an easy way to add new messages/UI in products, possibly even as an "after-market plugin". You could do this by defining a location where QML files would be loaded, and a mechanism within the file for them to define their menu text/location. Just a thought.

**Comment by DonLakeFlyer** [comment]
This is pretty majorly screwed up right now. Trying to figure out how to fix.
