### ISSUE TITLE
Problem import project in QT

### ISSUE THREAD

**Issue by miguelfervi** [mavlink/qgroundcontrol#5468]
I have a problem when I try to go to Design Menu in Qt

In my case QGroundControl.Controls and QGroundControl.ScreenTools do not found, How I can solve this trouble.

The screen that appears me is the following
![captura de pantalla 2017-07-18 a las 12 39 13](https://user-images.githubusercontent.com/14984189/28313183-365e8882-6bb6-11e7-93e6-8493cf968b49.png)

**Comment by DonLakeFlyer** [comment]
You cannot edit QGC Qml in the Designer, only a text editor

**Comment by josephchan0122** [comment]
Was it disabled from QGroundControl team?
