### ISSUE TITLE
Android: Video & Action button on top of eachother.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5483]
This is how the freshly updated QGC 3.2.1 look on android 6.0.1 (Note 4)

![screenshot_20170721-175322](https://user-images.githubusercontent.com/1468842/28471754-7ca99536-6e3e-11e7-91e7-aba763bab419.jpg)

**Comment by AndKe** [comment]
Also, please observe how the vertical left side menu appear to be truncated on the bottom.  (both Fly and Plan view)

**Comment by DonLakeFlyer** [comment]
Yeah, we're not super focused on small screens right now.
