### ISSUE TITLE
Android: (not an)issue about numpad out of view:

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5485]
@dagar you are the one that reply to feedback:

The issue below deserves an reply:
Samsung numpad has been buggy for years. Please try a better keyboard alternative like Gboard , it will works just fine. QGC is not the only application that samsung keyboard fails to work on. 

![smartselectimage_2017-07-21-13-29-23](https://user-images.githubusercontent.com/1468842/28473697-072ae154-6e46-11e7-8787-fdd6025d2657.png)

**Comment by DonLakeFlyer** [comment]
Done
