### ISSUE TITLE
I'm trying to setup video streaming  using RTSP in v3.2.2

### ISSUE THREAD

**Issue by ryancall** [mavlink/qgroundcontrol#5487]
I'm trying to setup video streaming using RTSP.  I am using qgroundcontrol v3.2.2 and I have installed the complete versions of:
•gstreamer-1.0-devel-1.5.2-x86_64.pkg
•gstreamer-1.0-1.5.2-x86_64.pkg
I am able to view the video stream using VLC player.  
The URL is: rtsp://192.168.168.1:554/user=admin&password=&channel=1&stream=0.sdp?real_stream
Qgroundcontrol just continues to say "waiting for video"
I have tried reseting my computer, connecting the autopilot, reopening qgroundcontrol.  Please Help!

**Comment by DonLakeFlyer** [comment]
Support: http://qgroundcontrol.com/#resources
