### ISSUE TITLE
Battery percentage stuck at 100%

### ISSUE THREAD

**Issue by wallbanger123** [mavlink/qgroundcontrol#5536]
Tested on OS X and Android. Stable and Daily. 

Running Pixhawk Lite, 3DR power module. Voltage is display correctly, but percentage never changes from 100.

**Comment by DonLakeFlyer** [comment]
I believe this value comes directly from the vehicle. Are you sure your Power setup is correct?

**Comment by wallbanger123** [comment]
Looks like I have a clone power module, and it needed manual setup. This is resolved. Thanks for the help.
