### ISSUE TITLE
Why we have to install Qt 5.7.1 otherwise 5.8.X ect???

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#5547]
Why we have to install Qt 5.7.1

**Comment by NaterGator** [comment]
That is the current officially supported version of Qt for this project. YMMV but I do not have issues when building using Qt 5.9.1 LTS and we do generally work towards supporting the next major long term release when there aren't show stopping bugs. 

Anything _other_ than the current official library should be handled with care and treated like beta, nor do we provide support for building here. You should check out the [chat room](https://gitter.im/mavlink/qgroundcontrol) or [discussion forum](http://discuss.px4.io/c/qgroundcontrol/qgroundcontrol-developers) if you run into issues building with an unofficial Qt release.

**Comment by MyOnlyOnlySunshine** [comment]
thanks
