### ISSUE TITLE
Problem of  connecting px4flow with QGC 3.2.4 

### ISSUE THREAD

**Issue by meteor0530** [mavlink/qgroundcontrol#5550]
Hi
I connect the px4flow and open the QGC, and there is no response. I try it both on windows and OSX, the version of QGC is 3.2.4.
Then I download v3.1.3 and try it again, it works well.
So I think this is the problem of v3.2 of the QGC.
Here is the v3.2.4 QGC log output:
[px4flow.txt](https://github.com/mavlink/qgroundcontrol/files/1216772/px4flow.txt)

**Comment by AlexisTM** [comment]
Same here

**Comment by kintzlr** [comment]
Me too.
