### ISSUE TITLE
 i can not delete waypoint when in the mocklink.

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#5552]
I  can not delete waypoint when in the mocklink.

**Comment by DonLakeFlyer** [comment]
Are you talking about individual awaypoint using the Delete command? Or are you talking about the Remove All command from the Synce button. If Remove All this was fixed recently and is in master.

**Comment by MyOnlyOnlySunshine** [comment]
yeah, thanks!
