### ISSUE TITLE
Offline Maps: Maps pluging added twice in FlightMap

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5570]
@dogmaphobic It worked for me to remove. Can you try again?

**Comment by DonLakeFlyer** [comment]
I have the pull but want to figure out why crashing.

**Comment by dogmaphobic** [comment]
It works fine. I must have done something else when I tried it (mixed branches most likely).

**Comment by DonLakeFlyer** [comment]
Fixed
