### ISSUE TITLE
LevelhHorizon calibration

### ISSUE THREAD

**Issue by enginc** [mavlink/qgroundcontrol#5571]
Hello,

In SensorsComponent.qml page line 394 is :  

sens_board_x_off.value != 0 || sens_board_y_off != 0 | sens_board_z_off != 0

value property of y_off and z_off is not called and | operator is used also.  Could they be forgotten? 

Best regards.

**Comment by DonLakeFlyer** [comment]
Yup this is a bug. If you could submit a pull request for the fix against Stable_V3.2 branch that would be awesome.

**Comment by enginc** [comment]
Submitted.

**Comment by DonLakeFlyer** [comment]
Fixed
