### ISSUE TITLE
waypoint attitude

### ISSUE THREAD

**Issue by lyt13080649017** [mavlink/qgroundcontrol#5583]
when you change waypoint's attitude without press Enter or Return key,then the attitude of the newly added waypoint is inconsistent with the previous one.

**Comment by DonLakeFlyer** [comment]
Are you using QGC version 3.2?

**Comment by lyt13080649017** [comment]
yes

**Comment by DonLakeFlyer** [comment]
A number of these cases have been fixed. So should be better now
