### ISSUE TITLE
can not connect the optical flow

### ISSUE THREAD

**Issue by feilongfl** [mavlink/qgroundcontrol#5591]
i use the QGC v3.2.2,it can not work with PX4 Flow.then i use v3.1.1 it works well.

![2017-08-18 19-17-32](https://user-images.githubusercontent.com/10269596/29458606-83f5f0bc-8452-11e7-87b4-4cdd3f5a221a.png)

**Comment by DonLakeFlyer** [comment]
Ok, I can repro this. The fix isn't simple so I'll take care of it in 3.3.

**Comment by DonLakeFlyer** [comment]
Dup of #5550
