### ISSUE TITLE
libespeak.so.1 missing in AppImage

### ISSUE THREAD

**Issue by probonopd** [mavlink/qgroundcontrol#5593]
`QGroundControl: error while loading shared libraries: libespeak.so.1: cannot open shared object file: No such file or directory`

Solution:
Bundle libespeak inside the AppImage

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266234023#L556

**Comment by dogmaphobic** [comment]
There is a branch ready to merge that moves away from individual speech engines and uses Qt's own. It needs Qt 5.9 or greater so it's waiting until we update. Maybe it's time?

**Comment by heschlie** [comment]
Is there an ETA on this landing, not able to launch this on Ubuntu 17.10.

**Comment by DonLakeFlyer** [comment]
New daily builds are not working?

**Comment by heschlie** [comment]
Ah missed the daily build link, those seem to work, thanks.

**Comment by probonopd** [comment]
I am referring to those on https://github.com/mavlink/qgroundcontrol/releases - any chance the fix will land there anytime soon? Thanks.
