### ISSUE TITLE
Problems with survey 

### ISSUE THREAD

**Issue by juvinski** [mavlink/qgroundcontrol#5613]
Hi,

drawing an irregular area on Survey is causing erroneous flight lines.
on the image irregular_90_degrees if you change from 0 to 90 degrees area of interest, the lanes are not enough to complete the survey.
On the lanes_greather_than_necessary image the lanes are larger than necessary - the lines are far from the area of interest.

![irregular_90_degrees](https://user-images.githubusercontent.com/6621479/29798060-127b4a86-8c31-11e7-9d3a-f44b8a647d87.png)
![lanes_greather_than_necessary](https://user-images.githubusercontent.com/6621479/29798061-127d741e-8c31-11e7-982b-c51febf8ba4f.jpg)

Regards

**Comment by DonLakeFlyer** [comment]
Can you attach the .plan file for the first survey here and I'll take a look. Just zip it up and attach. Something is going wrong there.

The second survey is a concave polygon which QGC does not support. It will turn it into a convex polygon and create a survey around that.

**Comment by juvinski** [comment]
Hi @DonLakeFlyer ,

for sure, I'm attaching the 2 files:
Can I help you ?
[mission_90_degrees.plan.zip](https://github.com/mavlink/qgroundcontrol/files/1259013/mission_90_degrees.plan.zip)

**Comment by zorandragan** [comment]
Hi @DonLakeFlyer 

> The second survey is a concave polygon which QGC does not support.

Why is this the case with QGC?

**Comment by DonLakeFlyer** [comment]
Fixed:
![screen shot 2017-11-09 at 1 00 23 pm](https://user-images.githubusercontent.com/5876851/32629514-59689dd0-c54e-11e7-8990-518614f43429.png)

> Why is this the case with QGC?

It is not supported because the code for survey generation is not currently capable of generating correct surveys for concave polygons.

**Comment by DonLakeFlyer** [comment]
I added a separate issue for convex polygons: https://github.com/mavlink/qgroundcontrol/issues/5830
