### ISSUE TITLE
unaligned pointer value warning

### ISSUE THREAD

**Issue by cas2406** [mavlink/qgroundcontrol#5614]
When trying to build to build QGC i get the following error message:

warning: taking address of packed member 'checksum' of class or structure '__mavlink_message' may result in an unaligned pointer value [-Waddress-of-packed-member]
        crc_accumulate_buffer(&msg->checksum, _MAV_PAYLOAD(msg), msg->len);

Can someone please help me solve this warning?

I tried building it on QT 5.7.0, 5.7.1, 5.9.1

**Comment by DonLakeFlyer** [comment]
That sounds like it is coming from mavlink headers so the problem is with mavlink not QGC. Also I would assume that for now you can just ignore it. You must be using a newer compiler version than we currently do.
