### ISSUE TITLE
Analysis of qgroundcontrol logs leads to immediate freeze/lockup.

### ISSUE THREAD

**Issue by sparky002** [mavlink/qgroundcontrol#5615]
Using latest daily build of qgroundcontrol, with a log created by the latest daily build of qgroundcontrol.
Ubuntu 14.04

A little over half way of loading some parameters, 
![qgroundcontrol_freeze](https://user-images.githubusercontent.com/11220787/29838336-e91c514c-8cc8-11e7-8f19-869eb066dea2.png)

A popup of a mavlink version mismatch dealing with the radios I used shows. I have to use xkill to forcefully close the program.

I attached the log file I tried to play back. The pixhawk did not save our most recent crash flight in a log so this is the only method I have to understand what went wrong. Impossible to fly it again due to how expensive and time consuming it is to fly such a large vehicle without looking over the log somehow.

Also, on playback of previous logs that don't cause QGroundControl to freeze, it is impossible to scrub through the timeline precisely. It either jumps to the front or end, and sometimes rarely allows me to scrub 25%ish in from the beginning and 25%ish in from the end. Otherwise I have to let it play back to get to the spot I want it too. Sometimes I have to sit and wait for an hour for the playback to reach the flight. If I want to play that specific part back again, I have to wait another hour for example. This alone has been happening for months, both on stable and daily builds.

Thanks for any help you can offer in this matter.

**Comment by DonLakeFlyer** [comment]
Lots of work has gone into log replay for 3.3 release. Should be much better now
