### ISSUE TITLE
QGroundConrtorl3.2.4 for Android  crash on startup

### ISSUE THREAD

**Issue by crossa** [mavlink/qgroundcontrol#5617]
QGrondContorl 3.2.4 for android crashed when startup.
 My copter connect to the QGC via udp , the qgc crashed after finished connection.

OS  Android 6.0.1
Type of mobile phone:  china mobile N2 M836

**Comment by chinanewer** [comment]
我也遇到这个问题了，我用的华为的平板，并且是有时候会有时候不会

**Comment by jaxxzer** [comment]
Can we close this?
