### ISSUE TITLE
Show large compass does nothing

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#5620]
Introduced here I think: https://github.com/mavlink/qgroundcontrol/commit/ea06f65e

The setting is used in InstrumentWidget.qml, but not InstrumentWidgetAlternate.qml.

**Comment by DonLakeFlyer** [comment]
Correct. Daily builds basically don't support large compass any more. Trying to see if that is ok.

**Comment by jaxxzer** [comment]
I gathered as much from the comments, left this here as a reminder to take out the option at some point if you keep it this way.

**Comment by DonLakeFlyer** [comment]
I have a feeling I"m going to have to put it back

**Comment by DonLakeFlyer** [comment]
Removed
