### ISSUE TITLE
QGC 3.2.2 and 3.2.4: Not able to calibrate thte ESCs.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#5622]
Foloowing the procedure after battery power we get this:

![esc calibration problem](https://user-images.githubusercontent.com/12617619/29909206-75351320-8e2d-11e7-96d0-77af231d6782.png)

We tried about 10 times each QGC version.

**Comment by tubeme** [comment]
This might be related somehow to this #5621

**Comment by DonLakeFlyer** [comment]
Most likely a firmware problem as opposed to QGC. QGC doesn't really do much here.

**Comment by DonLakeFlyer** [comment]
This needs to be debugged from the firmware side
