### ISSUE TITLE
Expected behavior?

### ISSUE THREAD

**Issue by chodjo** [mavlink/qgroundcontrol#5630]
Hello, is this an expected behavior?

1) Switch into Setup View
2) Select Firmware tab
3) Go into Settings View
4) Select Mock Link
5) Select a vehicle

You get a exception message: "Connect not allowed: Connect not allowed during Firmware Upgrade".

I havent even started a firmware upgrade. In order to remove the message, I have to go back to Setup view and change firmware tab for another one.

**Comment by DonLakeFlyer** [comment]
Yes this is working as expected although confusing. We'll take a look at making it better.
