### ISSUE TITLE
QGroundControl keeps crushing when using APM ArduSub Vehicle mock link.

### ISSUE THREAD

**Issue by chodjo** [mavlink/qgroundcontrol#5631]
Hello, QGroundControl keeps crushing when using APM ArduSub Vehicle mock link. Debbuger console prints

qrc:/qml/APMLightsComponentSummary.qml:9.1:QML APMLightsComponentSummary: Binding loop detected for property "_rcXXFunction" as XX a number between 5 and 14

Error message prompts "ârameters are missing from firmware. You may be running a version of firmware QGC does not work correctly with or your firmware has a bug in it. Missing params: -1:FS_PILOT_INPUT, -1:FS_PILOT_TIMEOUT, etc

**Comment by DonLakeFlyer** [comment]
@jaxxzer

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/5619 @chodjo @DonLakeFlyer
