### ISSUE TITLE
PlanElemementMasterController

### ISSUE THREAD

**Issue by julio-guillen** [mavlink/qgroundcontrol#5633]
Not exactly a bug, but may help readability. Just changing _PlanElemementMasterController_ with _PlanElementMasterController_ . In QGCApplication.cc we register it:

qmlRegisterType<PlanMasterController> ("QGroundControl.Controllers", 1, 0, "PlanElemementMasterController");

And later we use it just in FlightDisplayView.qml and PlanView.qml

Still learning the code, so not confident about submitting code yet.

**Comment by DonLakeFlyer** [comment]
Not sure what this means? Also this code is different now in master. Can you explain?
