### ISSUE TITLE
FlightDisplayView not showing PlanElemementMasterController

### ISSUE THREAD

**Issue by chodjo** [mavlink/qgroundcontrol#5634]
When selecting an APM ArduPlane vehicle mock link, FlightDisplayView doesnt show PlanElemementMasterController menu.

**Comment by DonLakeFlyer** [comment]
Not sure what part of the UI your are talking about?

**Comment by chodjo** [comment]
The FLY menu, with Takeoff, RTL, Pause and Action options is not displayed when using an APM ArduPlane mock link.

**Comment by DonLakeFlyer** [comment]
Do you mean disabled? Or are they missing from the screen? ArduPlane guided commands are not fully supported yet. So most will be disabled.

**Comment by chodjo** [comment]
Missing from screen.

**Comment by DonLakeFlyer** [comment]
What OS and what version of QGC. It's all working fine for me.

**Comment by chodjo** [comment]
OS Linux, and development version downloaded 2017-08-01. Maybe my fault then, as Im trying to understand the code and may have changed something then. Sorry for the inconvenience.

**Comment by DonLakeFlyer** [comment]
If you can reproduce this with a pre-buit AppImage version let me know,.
