### ISSUE TITLE
AR.Drone 2.0 support broken between QGroundControl 3.1.3 and 3.2.0

### ISSUE THREAD

**Issue by ivucica** [mavlink/qgroundcontrol#5635]
A few days ago, I've installed QGroundControl 3.2.4 on OS X Sierra, and I was unable to make it work.

I've just went through a bunch of versions of QGroundControl between 2.9.7 and 3.2.4. From what I can tell, the first version where QGroundControl stays in "Waiting For Vehicle Connection" is 3.2.0; 3.1.3 still works.

Observing traffic with Wireshark, I can see that packets are flowing in both directions on ports 14550 and 14551, even on 3.2.x; it just seems like QGroundControl is ignoring them.

Did something significant change in the UDP protocol? Is there a switch I can flip, or is this an actual bug? Would Wireshark traffic capture help with debugging?

(As a different bug, I was also unable to find a UI element to make the drone execute the uploaded mission with any of the versions I tried. Someone online recommended 2.3.0; I'll try with in the coming days.)

**Comment by DonLakeFlyer** [comment]
Dup of #5606
