### ISSUE TITLE
Add joystick buttons support

### ISSUE THREAD

**Issue by kikislater** [mavlink/qgroundcontrol#5646]
Hi, 
Since this PR https://github.com/ArduPilot/ardupilot/pull/6927 Qgroundcontrol could handle joystick. 
It's working well but buttons are not supported. Is it possible to add button support for Ardupilot firmware with joystick? Idea is to arm/disarm, change flight mode with joystick buttons.
I have only this message : 
Buttons 0-15 reserved for firmware use

![joystick_qgroundcontrol](https://user-images.githubusercontent.com/13238064/30334335-95b098d4-97df-11e7-80b7-a88c57d7e634.png)

**Comment by jaxxzer** [comment]
This needs to be implemented in the autopilot firmware first. Which autopilot firmware (and version) are you using?

**Comment by kikislater** [comment]
Ok didn't think it was a fw issue ! 
I'm running ardupilot fw :  arduplane 3.8.2

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/issues/5644

**Comment by gigorvd** [comment]
I tested the firmware on ArduPlane and ArduCopter and it does not work => Buttons are not supported. But on ArduSub working correctly.

**Comment by JAR4x4** [comment]
Any update on this matter?

**Comment by DonLakeFlyer** [comment]
@jaxxzer Any update on what the status of this is supposed to be for other ArduPilot firmware types?

**Comment by JAR4x4** [comment]
I've got the four control axis working, but I'm not able to map any buttons. I'm running ArduCopter 3.5 on a Navio2

**Comment by jaxxzer** [comment]
All of the ardupilot vehicles support MANUAL_CONTROL for r,p,y,throttle input. Only ArduSub supports the use of buttons for other inputs.

**Comment by JAR4x4** [comment]
@jaxxzer thanks for the reply! Any chance to get buttons to work with ArduCopter?

**Comment by jaxxzer** [comment]
No issue in QGC. @JAR4x4 this would need to be added as a feature request in the ardupilot repository. I don't think this will happen any time soon as arducopter is built around the concept of RC transmitter switches which have fundamentally different operation (latching) than momentary buttons.

**Comment by DonLakeFlyer** [comment]
Closing this then
