### ISSUE TITLE
Source code file line endings, is there a standard?

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#565]
@Susurrus Looks like the editor you are using allows for mixed format line endings. So files which were all CRLF are now mixed with some LF only lines. I'm running into problems with this because Xcode can't deal with mixed format line endings and flips the whole file back to the prevalent format which is CRLF in the cases I've seen. Is there a setting you can change to keep existing format?

@LorenzMeier Is there supposed to be a line ending standard for the source files? Looks like there is a mix of CRLF and LF. So I'm assuming not.

**Comment by DonLakeFlyer** [comment]
Updated coding guidelines for line ending to be LF only. Already have tabs/spaces and links to new coding guidelines examples.

**Comment by Susurrus** [comment]
So now that there are guidelines for it, should there be 1 commit where all files are finally normalized?

**Comment by DonLakeFlyer** [comment]
I'd rather just leave it alone instead of pushing a bunch of changes that don't do anything. They'll get cleaned up as people hit them.

**Comment by dogmaphobic** [comment]
It wouldn't hurt to run a global *uncrustify* pass on all files and make one single commit.

**Comment by DonLakeFlyer** [comment]
Problem I have with that is that is trashes Blame usage which can be handy.

**Comment by dogmaphobic** [comment]
I just blame you :)

**Comment by DonLakeFlyer** [comment]
That always works
