### ISSUE TITLE
Crashing the waypoints of multi vehicles

### ISSUE THREAD

**Issue by gizemsungu** [mavlink/qgroundcontrol#5664]
I have a problem with managing multi-uavs. Using SITL simulator, I managed to connect 2 vehicles with different SYSTEM ID's from different TCP ports. While planes are on the fly and in auto mode, I load a new mission with waypoints to plane 1 to go somewhere else. But suddenly,  a part of the same mission is also load to plane 2 or plane 3 etc. I can't manage every plane distincty.
For example:
Vehicle 1 has the waypoints at left side of the image and Vehicle 2 has the waypoints at the right side. 
![screenshot from 2017-09-18 13-36-32](https://user-images.githubusercontent.com/3133000/30538590-5cc91a90-9c77-11e7-921d-3ee2d6b028c6.png)

When these two vehicles start their missions, two of them go to the second waypoint of Vehicle 2. 
![screenshot from 2017-09-18 13-38-28](https://user-images.githubusercontent.com/3133000/30538603-78bace24-9c77-11e7-9107-69368b787a89.png)

Is there any solution for this problem?
Thanks

**Comment by DonLakeFlyer** [comment]
What SITL simulator are you using?

**Comment by gizemsungu** [comment]
ardupilot SITL simulator http://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html

**Comment by DonLakeFlyer** [comment]
I've had problems before with ArduPilot SITL multi-instance before where messages get routed to the wrong place. That sounds like the same problem you may be having not sure. Also keep in mind that when Planning mission the Plan view is interacting with the currently active vehicle (selected in toolbar). It can get confusing and if you switch active vehicles you have to manually sync the Plan view with the newly selecteed vehicle.

I'll try some steps to reproduce myself. But I'm not sure this is a QGC side problem yet.

**Comment by gizemsungu** [comment]
Which SITL simulator do you suggest to use with QGC?

**Comment by DonLakeFlyer** [comment]
There isn't really a choice. If you are using ArduPilot you need to use their simulator.

**Comment by DonLakeFlyer** [comment]
This the the MAVProxy multi-vehicle problem. If you run ArduPilot SITL without MAVProxy it will work fine.
