### ISSUE TITLE
Swap Waypoint not work with survey, just waypoint added manually

### ISSUE THREAD

**Issue by rsribas** [mavlink/qgroundcontrol#5692]
when created  a survey "swap waypoint" not update , only if waypoint add manually.

- follow survey created with 153 waypoints
![swapwaypoint0](https://user-images.githubusercontent.com/4690579/30758492-073e6e60-9fa9-11e7-95f1-11260809a9ab.png)

**Comment by DonLakeFlyer** [comment]
This was completely broken and removed from the ui
