### ISSUE TITLE
Pixhawk and QGroundControl

### ISSUE THREAD

**Issue by DmitriVeksler** [mavlink/qgroundcontrol#5706]
I cannot get my Pixhawk to connect to QGC. The Pixhawk is flashing yellow which indicates radio failsafe. I am trying to update the Pixhawk and it is "not responding". The upgrade stops as soon as it starts due to timeout waiting for bytes to be available. I can not find a cause or solution. Please help.

**Comment by DonLakeFlyer** [comment]
You seem to have deleted the following text from the issue without reading it:

Note: GitHub Issues are for bugs or feature requests only. Do not enter Issues for questions regarding usage or problems building QGC yourself. 
Use the appropriate support channel instead: http://qgroundcontrol.com/#resources.

Delete all of this text when create a real bug Issue.
