### ISSUE TITLE
(QGround Control.exe:10088):GLib-ERROR **:

### ISSUE THREAD

**Issue by HanJIk** [mavlink/qgroundcontrol#5717]
Hi.
I write once more.
When using QGC, the program is abnormally terminated with the following message.

![1](https://user-images.githubusercontent.com/30041641/31002253-74906c5e-a524-11e7-88a5-b5c553faad48.jpg)
![2](https://user-images.githubusercontent.com/30041641/31002254-76b3b5ea-a524-11e7-8f43-7db5dc0434d5.jpg)

Information
QGC Version : 3.2.1
Fireware version : ArduSub 3.4.1
Windows 8.1 64bit

please

**Comment by DonLakeFlyer** [comment]
Please don't enter duplicates of issues you have already entered! Your original issue #5670 is still there and was responded to 10 days ago with something you need to try.
