### ISSUE TITLE
Latest daily doesnt run on ubuntu

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#5744]
From the compressed image:
```sander@dl01:~/QGC/qgroundcontrol$ ./qgroundcontrol-start.sh 
/home/sander/QGC/qgroundcontrol/QGroundControl: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /home/sander/QGC/qgroundcontrol/QGroundControl)
```
From the appimage:
```
/tmp/.mount_UXmoDs/QGroundControl: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /tmp/.mount_UXmoDs/QGroundControl)
```

**Comment by sanderux** [comment]
Ubuntu 16.04
QT 5.9.1 installed (also issue when not installed)

**Comment by Breaknus** [comment]
Same problem

**Comment by DonLakeFlyer** [comment]
Hmm, when I build the AppImage myself it works. But the travis built one doesn't. Strange.

**Comment by DonLakeFlyer** [comment]
@dagar Do you have any ideas here?

**Comment by sanderux** [comment]
@DonLakeFlyer can you attach an appimage for latest daily? i have some stuff to report but want to test on latest first

**Comment by DonLakeFlyer** [comment]
Here is the one I built for testing: https://s3-us-west-2.amazonaws.com/qgroundcontrol/DonLakeFlyer/QGroundControl.AppImage

**Comment by sanderux** [comment]
I get the same issue on that:
```
sander@dl01:~/Downloads$ ./QGroundControl\ \(5\).AppImage 
/tmp/.mount_R9USgL/QGroundControl: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /tmp/.mount_R9USgL/QGroundControl)
```

**Comment by DonLakeFlyer** [comment]
I guess that's good. I must need to try running from a virgin Ubuntu with no Qt 5.9.1 installed.

**Comment by sanderux** [comment]
I have QT 5.9.1 installed, but upgraded from an older version.

**Comment by DonLakeFlyer** [comment]
Can you download and try again from https://s3-us-west-2.amazonaws.com/qgroundcontrol/DonLakeFlyer/QGroundControl.AppImage. There is a new version up there.

**Comment by DonLakeFlyer** [comment]
Can someone retry the build I posted?

**Comment by sanderux** [comment]
still the same
```
sander@dl01:~/Downloads$ chmod +x QGroundControl.AppImage 
sander@dl01:~/Downloads$ ./QGroundControl.AppImage 
/tmp/.mount_FgqF6C/QGroundControl: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by /tmp/.mount_FgqF6C/QGroundControl)
```

**Comment by dagar** [comment]
I'll be looking at this shortly. I'm trying to push the dependencies for Linux and Android builds into docker containers.

**Comment by DonLakeFlyer** [comment]
Thanks Daniel. I seem to be out of my Linux capabilities.

**Comment by DonLakeFlyer** [comment]
This is fixed now. TTS still not working though.
