### ISSUE TITLE
Camera config does not handle AP3.7.1  (is older firmware expected to be handled)

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5766]
I am not sure whatever older firmware versions are expected to be detected and supported, but opening camera config fails when looking for a lot of SERVO*_FUNCTION parameters, which obviously are not there.

**Comment by DonLakeFlyer** [comment]
Parameter redirection is broken.

**Comment by DonLakeFlyer** [comment]
QGC should support ArduPilot fixed wing back to 3.4. Testing now but I can't seem to get a 3.7.1 firmware. When I select that from Mission Planner I still get 3.6. I think that's probably good enough though.

**Comment by DonLakeFlyer** [comment]
@AndKe Could you test just to be sure once new daily is out
