### ISSUE TITLE
Parameter progress bar visibility in daylight.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5769]
The thin green progress bar is very hard to see when in difficult viewing conditions. 
When at >95% , it's even hard to see if it IS there (as in 95% ), or disappeared - as in 100%.
please consider adding a plain , smaller, progress bar with numeric count, something like:
             [|||||||| 120/770        ]

or a significantly thicker green line

**Comment by Antiheavy** [comment]
I agree the current thin bar is too hard to see.  Especially when it gets hung up at ~95% and you're squinting and asking yourself "is that still going? or did it complete?...."
