### ISSUE TITLE
Planned mission disappears when entering a guided go-to location 

### ISSUE THREAD

**Issue by fredrikfalkman** [mavlink/qgroundcontrol#5775]
When flying a mission in auto, if I enter a go-to location (Guided), the mission disappears from the chart screen. If I go back to Auto, the plane reverts to following the planned mission, but the waypoints and route lines are still not showing.

Other than that, the new ability to use go-to locations seems to work nicely. Much appreciated!

3.8 (Development add505fa7 2+17-09-17)
RPi3/Navio2; Arduplane 3.8.1

**Comment by DonLakeFlyer** [comment]
Can you try a new daily build? New one should show up in a couple hours.

**Comment by fredrikfalkman** [comment]
011fe913d 2017-10-25 doesn't seem to fix this. Also, sometimes an old goto marker would persist (graphically) even after loading a new mission.

**Comment by DonLakeFlyer** [comment]
If you are using Android the daily builds aren't updating right now so they are old. If no, can you try a newer daily. I think you may have just missed the fix.

**Comment by fredrikfalkman** [comment]
I’m using the Mac version, but I’ll try a new download non the less. Sometime next week. thanks!

**Comment by fredrikfalkman** [comment]
Today I had a chance to test again, this time with the Mac version ff3ee095c of 2017-11-04. Still the same thing. 

When I set a Go-to, the missions disappears:
<img width="1440" alt="screen shot 2017-11-08 at 14 20 13" src="https://user-images.githubusercontent.com/23034586/32560572-45f0ef18-c4aa-11e7-952b-a91da8781c4f.png">

When I return to auto the plane flies the mission happily but the waypoints aren't showing (but the goto still is:
<img width="1440" alt="screen shot 2017-11-08 at 14 23 40" src="https://user-images.githubusercontent.com/23034586/32560581-4b678204-c4aa-11e7-8a41-508de74b48d0.png">

**Comment by DonLakeFlyer** [comment]
I think I fixed it for real this time!

**Comment by fredrikfalkman** [comment]
@DonLakeFlyer you’re awesome! Will give it a go next week. Thanks!
