### ISSUE TITLE
Android daily builds are not updating

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5787]

**Comment by tve** [comment]
Looks like the problem is:
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/upload/androidpublisher/v2/applications/org.mavlink.qgroundcontrolbeta/edits/17445856360346861245/apks?uploadType=media&alt=json returned "APK is marked as debuggable.">
```
but you probably already saw that...

**Comment by tve** [comment]
I'm trying to download the latest Android daily from the S3 bucket. Is there a reason listing the S3 bucket files is not allowed? That makes it hard to locate anything...

**Comment by DonLakeFlyer** [comment]
@dagar Not sure where you are at on getting dailies updating again. Should we just post the S3 link in the docs?

**Comment by dagar** [comment]
We can list the S3 link if people want. I still want to get the Play store fixed. I was working on pushing the pieces into a docker container to remove some of the complexity.

**Comment by dagar** [comment]
Did you see my message in slack? This commit broke the google play deploy. https://github.com/mavlink/qgroundcontrol/commit/cc1fa95942fdc31a8445275b75ec88b19dba0b88

**Comment by DonLakeFlyer** [comment]
No I missed that. If I remember I was having problems debugging on one of my devices. I think you can revert that without problem.

**Comment by DonLakeFlyer** [comment]
Awesome, thanks!
