### ISSUE TITLE
COM Port is not re-establishing after Reboot command through QGC

### ISSUE THREAD

**Issue by sujiv0** [mavlink/qgroundcontrol#5791]
I'm using QGC V3.2.4 in Windows 7. After giving reboot command from Settings --> Parameters --> Tools --> Reboot Vehicle, Pixhawk 2.1 (with cube) is not connecting to QGC and showing "Link Error". I'm using latest PX4 firmware.

![image](https://user-images.githubusercontent.com/24405056/32034791-7a0ab734-ba32-11e7-9e9c-f6fc07cbfa7a.png)

@DonLakeFlyer Please have a look.

**Comment by DonLakeFlyer** [comment]
Ah, windows ... sigh

**Comment by sujiv0** [comment]
I sit okay now??? @DonLakeFlyer

**Comment by DonLakeFlyer** [comment]
I would assume not.

**Comment by DonLakeFlyer** [comment]
@sujiv0 Can you try this again using latest daily build? Lorenz just put through a fix that might take are of this.

**Comment by DonLakeFlyer** [comment]
Just tested with latest daily and working fine
