### ISSUE TITLE
"Go to Location" should contain altitude.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5794]
Screenshot says all:
"Goto Location" should display, and offer the slider to the right to change altitude.  - those two actions are very often used together.

![screenshot from 2017-10-26 22-24-28](https://user-images.githubusercontent.com/1468842/32075591-9433c6da-ba9d-11e7-91d6-02d3b159796c.png)

**Comment by DonLakeFlyer** [comment]
Yeah, makes a ton of sense.

**Comment by DonLakeFlyer** [comment]
Same thing for takeoff

**Comment by AndKe** [comment]
Unable to verify, - the "takeoff altitude" is still missing
Guided is impossible to use (current master)  - any left/right click pan map in a .. inverse way.
https://youtu.be/RPfuwqN4blk

**Comment by DonLakeFlyer** [comment]
This should not have been closed. The other scrolling thing is quite bizarre!

**Comment by DonLakeFlyer** [comment]
Can you enter a separate issue for the click thing?

**Comment by AndKe** [comment]
Done: https://github.com/mavlink/qgroundcontrol/issues/6625   :)
