### ISSUE TITLE
Strange characters on location access dialog

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5820]
When starting QGC (latest master) on MacOS 10.13.1 (also 10.13) the permission dialog to access the location appears with some strange chars.

<img width="1238" alt="screen shot 2017-11-02 at 16 15 04" src="https://user-images.githubusercontent.com/3130363/32337311-8b99dc84-bfe9-11e7-829a-44edf4de0c9a.png">

**Comment by DonLakeFlyer** [comment]
Fixed by Qt 5.10

**Comment by lvale** [comment]
Also fixed on QT 5.93
