### ISSUE TITLE
At initial Connection Mode is not updated

### ISSUE THREAD

**Issue by tops4u** [mavlink/qgroundcontrol#5833]
Running QGroundcontrol Master (about 2 Weeks old from today), running on MacOS HighSierra with AUAV-X2 connected via USB running on current Master.

When Booting Up and RC TX is already on and Flightmode is set to PosCtl for example. This is not reflected in the Top Bar:

![qgcmodeupdate](https://user-images.githubusercontent.com/6877067/32660479-50f50de8-c623-11e7-89ad-3cddc56c0e24.jpg)

In this case, the FlightMode Switch was in PosCtl Mode when Powering up. FC denied PosCTL as there are checks failing (like missing GPS) in reality the FC fell back to Alt Hold Mode, while the Status Bar showed Stabilized.

**Comment by DonLakeFlyer** [comment]
QGC is just displaying whatever it gets back in the HEARTBEAT message for flight mode. WHen you are in this state where you think QGC is displaying something wrong can you open the mavink inspector and take a screen shot of the HEARTBEAT message so I can check which is coming back from there.

**Comment by tops4u** [comment]
I think this may be a Firmware Issue. It works fine if TX is switched on after the Aircraft, but if it is the other way round Stabilized or Manual Mode is assumed. Shall I open an Issue on the Firmware Side?

Situation when Aircraft is powered after TX was on and FlightMode PosCtrl was selected:
![flightmodeafterboot](https://user-images.githubusercontent.com/6877067/32970509-953ee836-cbe9-11e7-8e08-05e0c09c2dd2.png)

Situation after toggling Flight Mode Switch -> Stabilized & back -> PosCTL
![flightmodeaftertoggling](https://user-images.githubusercontent.com/6877067/32970523-a290e75a-cbe9-11e7-9bc5-19e2e735be79.png)

**Comment by DonLakeFlyer** [comment]
Yup. Nothing QGC can do about it.
