### ISSUE TITLE
Moving a waypoint cause its altitude to be reset

### ISSUE THREAD

**Issue by Depfrost** [mavlink/qgroundcontrol#5844]
Ground station operating system: Windows.
QGroundControl version: Development master:909dd828a 2017-11-16 05:20:28 +0000
Autopilot board: i don't know
Autopilot firmware: PX4

Steps to reproduce:
1) Go in plan view and place the takeoff
![image](https://user-images.githubusercontent.com/33738256/32923934-7fafda66-cb3a-11e7-855a-e54b6bd6235b.png)

2) Move the takeoff somewhere else by draging it with the mouse
![image](https://user-images.githubusercontent.com/33738256/32923972-b8bf1a10-cb3a-11e7-9fe8-c0c55b8382c7.png)

3) Set an altitude in the top right box and press Enter
![image](https://user-images.githubusercontent.com/33738256/32924034-02ae240e-cb3b-11e7-8e1b-cf264768c052.png)

4) Move the takeoff somewhere else and notice that the altitude in the box has been reset to its previous value
![image](https://user-images.githubusercontent.com/33738256/32924115-6a485ec2-cb3b-11e7-8806-9a98977f4e85.png)

It also happen with waypoints not only with the takeoff, it may be because the property "itemCoordinate" in MissionItemIndicator.qml does not get updated when we set the altitude in the box.

**Comment by DonLakeFlyer** [comment]
More FocusScope problems. Wayoints needs to take focus on click in order to force editing to finish.
