### ISSUE TITLE
New Guided Action - Set ROI

### ISSUE THREAD

**Issue by fredrikfalkman** [mavlink/qgroundcontrol#5846]
This is a feature request for an added funktionality for the Guided Go-to by clicking in the map.

Clicking in the map might give multiple choices aside from the current Go-to:

- Go-to location
- Go-to location and set as ROI
- Set as ROI

**Comment by DonLakeFlyer** [comment]
This will be implemented in 3.6

**Comment by dogmaphobic** [comment]
Done in https://github.com/mavlink/qgroundcontrol/pull/8109
