### ISSUE TITLE
Android / Parameters / Load from file... / No files visible

### ISSUE THREAD

**Issue by ThorstenDP** [mavlink/qgroundcontrol#5847]
Hi all,

it is possible to save a "*.params" file but it is not possible to "Load from file...". Eventhough the files are there, the list is empty and shows "No files". 

- OS: Android
- QGroundControl: 3.2.5
- Autopilot board: Pixracer
- ArduPilot: 3.5.4rc2

Best regards,
Thorsten

**Comment by ChristopherOlson** [comment]
I have noticed this as well. I think it has something to do with where it is looking for the files on Android. If you go to the settings where it says File Save Path: /storage/emulated/0/QGroundControl and click on Browse it can't find any other path there either. That seems to be hard-wired into the code and it knows where to save but not where to find.
