### ISSUE TITLE
Feature Request: Option to display lat/lon in instrument panel

### ISSUE THREAD

**Issue by njoubert** [mavlink/qgroundcontrol#5853]
Our users often need to read the vehicle's current latitude and longitude. The instrument panel widget (which contains the artificial horizon and compass) currently displays vehicle attitude, gps health, etc.

It would be hugely helpful if this panel can also display the current vehicle latitude and longitude.

This should be a relatively easy add for anyone that knows the codebase! Thank you!

-Niels Joubert
FlightWave Aero

**Comment by DonLakeFlyer** [comment]
It's already there. Customise you instrument panel by clicking the gear icon and add Lat/Lon to it.
