### ISSUE TITLE
Error in build qgroundcontrol 

### ISSUE THREAD

**Issue by soshianet** [mavlink/qgroundcontrol#5856]
Hello all,
I have a problem with building qgroundcontrol source code from github (https://github.com/mavlink/qgroundcontrol),
my operating system is windows7-64 bit and I downloaded qt qreator (qt-opensource-windows-x86-5.9.1.exe) and checkmarked mscv2015, mscv2017-64bit, mscv2017-32bit,... during install,
and installed visual studio 2017 (64bit).
I set kit  MSVC2015 32bit, compiler: Microsoft Visual C++ Compiler 15.0 (x86), Debugger: C:\Qt\Qt5.9.1\Tools\mingw530_32\bin\gdb.exe and Cmake: C:\Qt\Qt5.9.1\5.9.1\msvc2015\bin\qmake.exe (this path also is defined as environment variable)
I get error, when I compile the project: compile output

It's very necessary to solve this, please help me
Thanks in advance for your assistance....

---------------------------------------- compile output -------------------------------
15:29:08: Running steps for project qgroundcontrol...
15:29:08: Configuration unchanged, skipping qmake step.
15:29:08: Starting: "C:\Qt\Qt5.9.1\Tools\QtCreator\bin\jom.exe" 
	C:\Qt\Qt5.9.1\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\qgroundcontrol.vc.pdb -DUNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I..\qgroundcontrol -I. -I..\qgroundcontrol -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtWidgets -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtGui -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtANGLE -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtPositioning -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtCore -Idebug -I. -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\mkspecs\win32-msvc -Fodebug\ @C:\Users\win8.1\AppData\Local\Temp\CodingStyle.obj.3556.937.jom
CodingStyle.cc
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\qgroundcontrol.vc.pdb -DUNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I..\qgroundcontrol -I. -I..\qgroundcontrol -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtWidgets -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtGui -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtANGLE -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtPositioning -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtCore -Idebug -I. -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\mkspecs\win32-msvc -Fodebug\ @C:\Users\win8.1\AppData\Local\Temp\MobileScreenMgr.obj.3556.953.jom
MobileScreenMgr.cc
..\qgroundcontrol\src\MobileScreenMgr.cc(14): fatal error C1083: Cannot open include file: 'QtAndroidExtras/QtAndroidExtras': No such file or directory
QGCApplication.cc
d:\8-ground station\qgroundcontrol\src\QGCApplication.h(24): fatal error C1083: Cannot open include file: 'QQmlApplicationEngine': No such file or directory
QGCFileDownload.cc
d:\8-ground station\qgroundcontrol\src\QGCFileDownload.h(14): fatal error C1083: Cannot open include file: 'QNetworkReply': No such file or directory
Generating Code...
d:\8-ground station\qgroundcontrol\src\qgcunittest\UnitTest.h(21): fatal error C1083: Cannot open include file: 'QtTest': No such file or directory
jom: D:\8-GROUND STATION\build-qgroundcontrol-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\Makefile.Debug [debug\CodingStyle.obj] Error 2
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\qgroundcontrol.vc.pdb -DUNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I..\qgroundcontrol -I. -I..\qgroundcontrol -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtWidgets -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtGui -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtANGLE -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtPositioning -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtCore -Idebug -I. -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\mkspecs\win32-msvc -Fodebug\ @C:\Users\win8.1\AppData\Local\Temp\JsonHelper.obj.3556.953.jom
JsonHelper.cc
d:\8-ground station\qgroundcontrol\src\QGCQGeoCoordinate.h(14): fatal error C1083: Cannot open include file: 'QQmlEngine': No such file or directory
LogCompressor.cc
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\qgroundcontrol.vc.pdb -DUNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I..\qgroundcontrol -I. -I..\qgroundcontrol -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtWidgets -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtGui -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtANGLE -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtPositioning -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\include\QtCore -Idebug -I. -IC:\Qt\Qt5.9.1\5.9.1\msvc2015\mkspecs\win32-msvc -Fodebug\ @C:\Users\win8.1\AppData\Local\Temp\QGCPalette.obj.3556.953.jom
QGCPalette.cc
d:\8-ground station\qgroundcontrol\src\QGCApplication.h(24): fatal error C1083: Cannot open include file: 'QQmlApplicationEngine': No such file or directory
QGCQFileDialog.cc
d:\8-ground station\qgroundcontrol\src\QGCApplication.h(24): fatal error C1083: Cannot open include file: 'QQmlApplicationEngine': No such file or directory
main.cc
d:\8-ground station\qgroundcontrol\src\QGCApplication.h(24): fatal error C1083: Cannot open include file: 'QQmlApplicationEngine': No such file or directory
QGCQGeoCoordinate.cc
..\qgroundcontrol\src\main.cc(21): fatal error C1083: Cannot open include file: 'QSslSocket': No such file or directory
Generating Code...
jom: D:\8-GROUND STATION\build-qgroundcontrol-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\Makefile.Debug [debug\JsonHelper.obj] Error 2
d:\8-ground station\qgroundcontrol\src\QGCQGeoCoordinate.h(14): fatal error C1083: Cannot open include file: 'QQmlEngine': No such file or directory
Generating Code...
jom: D:\8-GROUND STATION\build-qgroundcontrol-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\Makefile.Debug [debug\QGCPalette.obj] Error 2
jom: D:\8-GROUND STATION\build-qgroundcontrol-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\Makefile.Debug [debug\MobileScreenMgr.obj] Error 2
jom: D:\8-GROUND STATION\build-qgroundcontrol-Desktop_Qt_5_9_1_MSVC2015_32bit-Debug\Makefile [debug] Error 2
15:29:13: The process "C:\Qt\Qt5.9.1\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Desktop Qt 5.9.1 MSVC2015 32bit)
The kit Desktop Qt 5.9.1 MSVC2015 32bit has configuration issues which might be the root cause for this problem.
When executing step "Make"
15:29:13: Elapsed time: 00:04.

**Comment by dogmaphobic** [comment]
This system is for posting bugs or feature requests ONLY. For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources
