### ISSUE TITLE
Switching video from RTSP feed to disabled doesnt actually stop video

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#5857]
When switching from RTSP feed to disabled it only hides the video screen, it doesnt stop the video feed in the background. When setting it from RTSP to UDP it does actually stop the video.

over 4G / WiFi this is useful for bandwidth control

**Comment by dogmaphobic** [comment]
The "Surface" and the "Receiver" are separate entities. Either way, this is solved by #5859
