### ISSUE TITLE
Feature request: Survey missions option to first fly all even lines then fly all odd lines on the way back

### ISSUE THREAD

**Issue by deonblaauw** [mavlink/qgroundcontrol#5866]
We fly missions using a fixed-wing drone, and would really find it useful if the survey missions could be setup such that the drone flies all the even paths on the first pass, then all the odd paths on the way back. Doing this means that the aircraft would be able to settle back onto the path quicker, making for more efficient missions (currently we lose some image quality on the mission edges due to "back to the path" settling time). This is especially relevant when high image overlap is required which leads to tightly spaced lines.

**Comment by sanderux** [comment]
And the vehicle would be back where it started when it finishes the mission.
@DonLakeFlyer @dogmaphobic

**Comment by JonReacher** [comment]
I agree. Especially useful in areas sensitive to flying extended turnarounds over nearby property/ airspace.

**Comment by DonLakeFlyer** [comment]
Using a turnaround distance doesn't fix the problem of cleaning up the pat to entera transect ?

**Comment by sanderux** [comment]
That could almost double the mission distance

**Comment by DonLakeFlyer** [comment]
Sure, but don't you still need to use some amount of turnaround anyway? Without turnaround fixed-wing entry will almost always be off. Seems like this would only be needed if the FW min turning radius is larger than the transect spacing? Does that happen often?

Not agruing against supporting this. I want to make sure I understand various FW survey problems correctly.

**Comment by sanderux** [comment]
The turn radius on our vehicle is 100m, doing a half circle it will be fully level at the end. Generally the line distance is between 20 and 50 meters, so even 3 or 4 passes would be nice to have.

**Comment by sanderux** [comment]
If you set max bank angle in sitl to about 30 degrees you will see what happens

**Comment by JonReacher** [comment]
@DonLakeFlyer To answer your question I'll give you a typical scenario for myself. A transect width of 200' wide is common for a 400' altitude survey @ 70% side lap w/ an APS-C sized sensor. Very common.
 Our AV takes about a 3-400' wide turn in the turnarounds, which means 3-400' long turnarounds just to be level by the time we hit the new transect. Eats up a lot of mission time. An odd/ even arrangement would be perfect for doing a large reduction in turnaround space needed.
Sander's comment about limiting bank is probably pretty common as well. We have a limit set.

**Comment by DonLakeFlyer** [comment]
Got it. Thanks everyone for the detailed information. Want to make sure I'm educated on all this stuff.

**Comment by Antiheavy** [comment]
+1 for a feature like this.  Very useful for certain fixed wing survey applications.  For those of us who live in the frozen north, we call this a zamboni pattern.

**Comment by ThorstenDP** [comment]
+1 not only for fixed wing surveys. This might also have positive effects for generating orthomosaics. Some discussion at: https://github.com/DroidPlanner/Tower/issues/1474

**Comment by Antiheavy** [comment]
check out recent QGC daily builds.  We flight tested this yesterday on a fixed wing and it works pretty awesome.

**Comment by DonLakeFlyer** [comment]
Ah, I new there was an issue on this somewhere. So  this is implemented now. What is not is discussion on how to handle the turnaround between between the two passes. That is discussed in #6451
