### ISSUE TITLE
No GPS lock reported by QGC for Intel Aero RTF

### ISSUE THREAD

**Issue by RohanKurane** [mavlink/qgroundcontrol#5871]
Hello,

I have seen this problem been reported before and the suggestion was to talk to the firmware team for the issue. When I arm the vehicle from QGC and try to TakeOff, I get a No GPS lock from QGC. This is not a QGC issue as I understand.

Can someone put me in touch with the firmware team or if there is a solution for this already please point me to it? 

Thanks!

**Comment by DonLakeFlyer** [comment]
https://discuss.ardupilot.org
http://discuss.px4.io
