### ISSUE TITLE
Feature Request: Simplified Airspeed Zeroing function.

### ISSUE THREAD

**Issue by raygamero** [mavlink/qgroundcontrol#5880]
The current Airspeed sensor calibration is a bit cumbersome for daily zeroing of the sensor.
I feel silly blowing in my pitot tube every day. Can we make a quick zero option where we bag the pitot, zero and then press? The current calibration can be used for new builds.

I prefer to zero the airspeed shortly before launch (to let the sensor settle to the current temp).  Blowing on the tube while the aircraft is on the launcher is silly/dangerous.  The last step of blowing in pitot tube should be bypassable or optional.

**Comment by DonLakeFlyer** [comment]
QGC isn't in control of airspeed calibration. Firmware implements this. Need to talk with them
