### ISSUE TITLE
UVC not working neither in Win10 nor Android

### ISSUE THREAD

**Issue by GlidLov** [mavlink/qgroundcontrol#5908]
Hi, 

i'm experimenting with UVC devices like the "USV5.8" (white covered little board which you can find on aliexpress). I can open his video stream with VLC in windows 10, selecting "open device", selecting the right device which is seen as a HD webcam and have to set to PAL-I to make it work properly.

Then, i want to have the video feed into QGC video window. In my win10 laptop, i can select the device but once back to fly screen, i get my laptop camera video feed.

with my android smartphone (Samsung S8+) the UVC camera option doesn't even came out of the options avaiable (front, back, RTSP, UDP and disabled).

Am i missing something or there's a bug?

Thanks for helping

**Comment by niemand23** [comment]
Hey, 

I'm having the same problem. I cannot get QGC to show the video input from my USB webcam. Unfortunately I am pretty new to QGC and QT itself but I've tried to find the cause of the problem and this is what I found so far. Please excuse if I'm completely on the wrong track.. 

In FlightDisplayViewUVC.qml the deviceId is specified as    QGroundControl.videoManager.videoSourceID. Apparently this ID is only set once in VideoManager::setToolbox which itself only seems to be called once in QGCToolbox::setChildToolboxes. As far as I can see it is therefore not updated when a new source is selected through the FactComboBox for videoSource in the GeneralSettings.qml. 

Also it seems to me that when the video sources are detected in videoSettings constructor the cameraInfo.description() is saved to the video source factMetaData as QstringList in enumStrings and also as QVariantList in enumValues. I would have expected that enumValues holds the cameraInfo.deviceName(). 

I would be very grateful if one of the members of the development team could comment on this issue and maybe also explain to me why there is another videoSourceID in the videoManager besides the fact video source. Couldn't the fact directly be accessed in the FlightDisplayViewUVC? 

Thanks
Andreas
