### ISSUE TITLE
Qt 5.10 wil break file dialogs

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#5924]
Using QGC master compiled with QT 5.10

Using Map provider Bing

Create a Structure scan and export to KML

Resulting file is empty, as no data inside the file

edit: also tested with GGL map provider, although maps don't show, and same empty kml export

**Comment by DonLakeFlyer** [comment]
@patrickelectric Can you look at this?

**Comment by patrickelectric** [comment]
@DonLakeFlyer I'll try to look on it.

**Comment by DonLakeFlyer** [comment]
@lvale I just tried a simple example and it worked. Do you have a .plan file that fails? I fixed a few things with KML last week so this may be good now.

**Comment by patrickelectric** [comment]
@DonLakeFlyer sorry for not taking care of this, I work with underwater now, no more missions to take care

**Comment by lvale** [comment]
Sorry Don
Latest build
<img width="500" alt="screen shot 2018-03-22 at 22 23 13" src="https://user-images.githubusercontent.com/3130363/37801743-a78ccb8c-2e1f-11e8-8b3c-968644522341.png">

Doesn't save either to file or to kml. When choosing save no dialog comes up

<img width="1098" alt="screen shot 2018-03-22 at 22 24 22" src="https://user-images.githubusercontent.com/3130363/37801790-cff69350-2e1f-11e8-8fb1-acdeacdbc71d.png">

**Comment by DonLakeFlyer** [comment]
What OS?

**Comment by DonLakeFlyer** [comment]
Using a pre-built daily build?

**Comment by DonLakeFlyer** [comment]
Oh, wait you built it yourself with Qt 5.10. We are only on Qt 5.9.3. 5.10 is likely broken.

**Comment by lvale** [comment]
ok. Just re-tested master with QT5.9.4 and it is now working

**Comment by DonLakeFlyer** [comment]
All working fine
