### ISSUE TITLE
QGC doesn't notice telemetry loss when SiK radio link dies

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5933]
( QGC 3.2.7 / macOS 10.13.1 / PX4 Mini firmware 1.7.2 / SiK radio firmware 2.0 )

When communicating using SiK radios with MAVlink enabled, QGC doesn't notice that telemetry has been lost when the remote is powered down.

**Comment by DonLakeFlyer** [comment]
Radio ping message likely breaking timeout.

**Comment by DonLakeFlyer** [comment]
Can you try a daily build. I think this was fixed.

**Comment by DonLakeFlyer** [comment]
I verified that this is working correctly in daily builds.
