### ISSUE TITLE
QGC doesn't say anything when telemetry radio is unplugged from the host

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5934]
( QGC 3.2.7 / macOS 10.13.1 / PX4 Mini firmware 1.7.2 / SiK radio firmware 2.0 )

When the telemetry radio is unplugged, perhaps accidentally, QGC silently reverts to "not connected" mode without telling the user that the link has been lost.

**Comment by DonLakeFlyer** [comment]
This is kind of on purpose. But I get the accidental aspect of it like you say. let me see.

**Comment by DonLakeFlyer** [comment]
YOu'll get comm list with this now
