### ISSUE TITLE
Compass calibration dialog asks about autopilot orientation

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#5938]
This here is very confusing: When setting up the compass QGC asks about the compass orientation. If you do not CAREFULLY read the (tons of) text you are likely to choose the compass orientation there.

<img width="1120" alt="screen shot 2017-12-31 at 16 27 33" src="https://user-images.githubusercontent.com/1208119/34462604-b46dd160-ee47-11e7-9b78-c1216d3e03e7.png">

**Comment by DonLakeFlyer** [comment]
![screen shot 2018-01-03 at 12 17 25 pm](https://user-images.githubusercontent.com/5876851/34538652-0e6b1826-f082-11e7-8012-ac6f3ec114b0.png)
