### ISSUE TITLE
Airspeed cal instructions say "blow across the front", but to generate enough pressure you have to blow *into* the front of the pitot tube

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5940]
(QGC 3.2.7)

As the title says; airspeed sensor cal instructions lead to calibration failure.

**Comment by LorenzMeier** [comment]
That sounds like there is something wrong with it. No need to blow into it.

**Comment by DonLakeFlyer** [comment]
If I remember correct "across" was to prevent anything getting into the pitot which will screw i tup.
