### ISSUE TITLE
Selecting a new airframe doesn't force "Level Horizon" calibration

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5941]
( QGC 3.2.7 )

Selecting a new airframe forces much setup to be re-done, which helps avoid re-using stale cal/config from a previous application.

Unfortunately, the Level Horizon cal is not cleared, so for a new or forgetful user it can be missed / skipped with predictably bad results.

**Comment by LorenzMeier** [comment]
This is pretty sure a QGC / param caching problem. The parameters are not preserved on the vehicle, so I suspect that QGC is not re-loading the complete vehicle state.

@DonLakeFlyer I can reproduce this here locally.
