### ISSUE TITLE
PWM reversing parameter set help says reset required, but takes effect immediately

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5944]
( QGC 3.2.7, Firmware 1.7.2, PX4 Mini)

When changing the PWM reversing parameter, the help text says that a reset is required for the change to take effect, but observing the servo channel it's clear that it takes effect immediately.

**Comment by LorenzMeier** [comment]
Fixed here: https://github.com/PX4/Firmware/commit/92540fc6d803f980263b6665146dde1c191fb084
