### ISSUE TITLE
Modal dialogs during e.g. setup are not visually obvious

### ISSUE THREAD

**Issue by px4dev** [mavlink/qgroundcontrol#5947]
( QGC 3.2.7 )

The modal dialogs used by the default QGC theme (popovers from the right side of the screen) are visually indistinct from the rest of the layout, and it's much too easy to fail to notice them and become confused by the fact that none of the rest of the UI is responsive.

The user's eye should be drawn directly to a modal dialog; perhaps selecting a contrasting and more urgent color scheme, or dropping the saturation of the rest of the UI would help, or shaping / skinning the dialogs so that they are more clearly overlays...

**Comment by DonLakeFlyer** [comment]
If you use a daily build you'll see that the center portion of the ui now goes opaque so you realize you need to respond to the dialog.
