### ISSUE TITLE
Log-Download Timed Out?

### ISSUE THREAD

**Issue by Marcusqjumpfxu** [mavlink/qgroundcontrol#5950]
Hi there,

I use QGroundControl quite often and I've discovered an issue with the download of Log-Files.

First the download is way to much than the size of the actual Log. Second the download timed out.

I've been connected via USB to my Pixhawk. OS: Ubuntu. QGroundControl: Nightly 2017-12-25.
![1](https://user-images.githubusercontent.com/35077586/34536130-85d4e1ca-f0c4-11e7-9d85-59f1ed04858b.png)
![3](https://user-images.githubusercontent.com/35077586/34536136-8a84ca0a-f0c4-11e7-89a1-79e4d3c4e586.png)
![2](https://user-images.githubusercontent.com/35077586/34536178-a83e7244-f0c4-11e7-9905-4b852961561d.png)

I've used an USB extension cable, but even without the extension cable it time out.
I use the newest stable firmware 3.5.4 ArduCopter.

The terminal gives me the following output if I try to download a log file:

```
LogDownloadLog: Request log data (id: 41 offset: 551880 size: 1080 )
LogDownloadLog: Request log data (id: 41 offset: 551880 size: 1080 )
LogDownloadLog: Request log data (id: 41 offset: 551880 size: 1080 )
LogDownloadLog: Request log data (id: 41 offset: 551880 size: 1080 )
LogDownloadLog: Request log data (id: 41 offset: 552960 size: 46080 )
LogDownloadLog: Request log data (id: 41 offset: 552960 size: 46080 )
LogDownloadLog: Request log data (id: 41 offset: 552960 size: 46080 )
LogDownloadLog: Request log data (id: 41 offset: 552960 size: 46080 )
Too many errors retreiving log data. Giving up.
```
In APM Planner 2.0.24 it works flawless.

I've posted this also on the [ardupilot discussion page](https://discuss.ardupilot.org/t/log-download-timed-out/24326).

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do the size requests from the log make sense. Can't remember how that works. It suddenly bumps to a large size.

**Comment by DonLakeFlyer** [comment]
I tried downloading some logs through SITL and it of course worked every time.

**Comment by NaterGator** [comment]
@DonLakeFlyer if the segment the long downloader was working on had gaps (likely over any kind of less-than-perfect link) the smaller size can make sense (it would be the size of the missing contiguous gap).

**Comment by DonLakeFlyer** [comment]
From my testing it looks like the 1080 are filling in gaps whereas as 46080 is the normal request size. So I'd guess there is something going wrong on the link losing data. Even over usb would be strange though.

**Comment by NaterGator** [comment]
Yeah that sounds about right. I've seen the CDC-ACM interface have some loss; I'm guessing it comes from dropped transfers on the micro side but I haven't actually verified that.

**Comment by DonLakeFlyer** [comment]
When you get a failed download. Do you get a status text message from the vehicle which says "Log download in progress"?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Have you looked at the ArduPilot firmware which implements this? It's a bit strange. It streams out a certain number of packets them stops. While it is in the middle of streaming those packets it drops any incoming LOG_REQUEST_DATA requests from the ground station. So if the ground station asks to fill in missing gaps before while ArduPIlot is still streaming this could crap out. Not really sure how the log download code in GGC works. So not sure if this is a problem.

**Comment by aklink** [comment]
Any solution? I am trying to download a 88.8 MB logfile from PX4, but always get a time out after some time. Logfiles up to 40MB in size can be downloaded flawlessly.

**Comment by dimon777** [comment]
Same problem here on 71MB log. With logs bit smaller always downloaded successfully. My download speed is 165KB/s

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I'm not sure that this one raises to Stable but I've heard the log timeout problem multiple times along the way. Seems like this needs to be figured out if it's QGC or Firmware bug. Should the code be change to never timeout and keep retrying until the user gives up?

**Comment by fredowski** [comment]
Hi, Alexey tried the log download with ardupilot over the ESP8266 wifi bridge and saw timeout problems there. The discussion is here:

https://discuss.ardupilot.org/t/pixracer-esp8266-arduplane-log-download-timeout/51850

So finally he could do the download via Missionplanner but it did not work with QGC.

**Comment by DonLakeFlyer** [comment]
Hoping this is finally fixed now

**Comment by fredowski** [comment]
Hi, I reported some test results in #8312

**Comment by DonLakeFlyer** [comment]
@fredowski Thanks so much for testing. I created a new Issue for this at #8325
