### ISSUE TITLE
Parameter hash code response to _HASH_CHECK at any time

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#5953]
It's should only do it during a param_request_list sequence. If the firmware sends one of these out of band strange things could happen. Need to look.

Related to: https://github.com/PX4/Firmware/pull/8569

**Comment by LorenzMeier** [comment]
I'm aware that this would be an extension of the protocol, but adding that async capability would help to resolve a number of stale Firmware state issues that we ran into recently during vehicle setup and calibration.

**Comment by DonLakeFlyer** [comment]
Fixed
