### ISSUE TITLE
Missing parts in a survey mission using the current daily build (12.01.2018) on Android

### ISSUE THREAD

**Issue by ThorstenDP** [mavlink/qgroundcontrol#6007]
Hi all,

I just came across this:

![screenshot_20180112-230010](https://user-images.githubusercontent.com/5606072/34897191-1f83ffd4-f7ed-11e7-975a-ac29ee8d40e5.jpg)

**Comment by DonLakeFlyer** [comment]
Need the .plan file. Zip it and attach here.

**Comment by ThorstenDP** [comment]
Will do tomorrow. Where is it located? The mission folder is empty. I'll check again tomorrow...

**Comment by DonLakeFlyer** [comment]
You have to save it yourself and it should be in the misison folder.

**Comment by ThorstenDP** [comment]
This should be it: [Missions.zip](https://github.com/mavlink/qgroundcontrol/files/1627670/Missions.zip)
