### ISSUE TITLE
Proxy settings ignored

### ISSUE THREAD

**Issue by WillRam** [mavlink/qgroundcontrol#601]
qgroundcontrol fails to download maps/firmware when the internet is behind a proxy server. Fails on both windows and linux (xubuntu). Using proxycap (windows) does work around the problem

**Comment by munna1996** [comment]
groundcontrol fails to download maps/firmware when the internet is behind a proxy server in ubuntu.

**Comment by marianobianchi** [comment]
I have this problem too

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you look a this? No idea how proxy settings affect network access.

**Comment by NaterGator** [comment]
http://doc.qt.io/qt-5/qnetworkproxyfactory.html#systemProxyForQuery ?
