### ISSUE TITLE
Sizing issue with NMEA settings

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6010]
![screen shot 2018-01-12 at 3 25 39 pm](https://user-images.githubusercontent.com/5876851/34899308-eb99ffce-f7ac-11e7-990a-4cf0e44d8597.png)

**Comment by DonLakeFlyer** [comment]
@jaxxzer FYI

**Comment by DonLakeFlyer** [comment]
@jaxxzer Can you fix this?

**Comment by jaxxzer** [comment]
Yes
