### ISSUE TITLE
Qt Creator reports "No valid kits found."

### ISSUE THREAD

**Issue by pieter-pozyx** [mavlink/qgroundcontrol#6019]
- Operating System: Lubuntu 17.04 Zesty
- QGroundControl version: Latest version ([commit 8e16b264cd208c74e3bb03ce3dd462dee9307e33](https://github.com/mavlink/qgroundcontrol/tree/8e16b264cd208c74e3bb03ce3dd462dee9307e33))

**Steps to reproduce the issue:**
Follow the [readme](https://github.com/mavlink/qgroundcontrol/tree/8e16b264cd208c74e3bb03ce3dd462dee9307e33):
- Download the Qt installer
- Install additional packages: `sudo apt-get install speech-dispatcher libudev-dev libsdl2-dev`
- Clone from git: `git clone --recursive https://github.com/mavlink/qgroundcontrol.git`
- Launch Qt Creator and open the qgroundcontrol.pro project

The readme states that you should "Select the appropriate kit for your needs", but no kits are found:

![2018-01-15-110406_724x458_scrot](https://user-images.githubusercontent.com/29226260/34937137-fa553266-f9e3-11e7-9c08-2f4696a63cc6.png)

**Comment by DonLakeFlyer** [comment]
Here is what the text says that you deleted from the issue!

This system is for posting bugs or feature requests ONLY. **For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources**
