### ISSUE TITLE
Feature Request: Show RTK status when no vehicle connected

### ISSUE THREAD

**Issue by ndepal** [mavlink/qgroundcontrol#6021]
Since RTK survey-in takes a while, I prefer to do the survey-in before powering my vehicle. However, without a vehicle connected, QGC does not show the RTK status and thus it's not clear when the survey-in has finished.

I am currently working around this by plugging in the GPS, then I plug in the vehicle, wait for it to connect via telemetry, click on the RTK symbol to show the detailed RTK info bubble and power down the vehicle again. The RTK info bubble remains visible and is updated if I don't click anything else.

**Comment by DonLakeFlyer** [comment]
Dup of #5319
