### ISSUE TITLE
Display and Edit Polygon PX4 Geofence in QGC

### ISSUE THREAD

**Issue by deonblaauw** [mavlink/qgroundcontrol#6039]
I followed the instructions described [here](https://pixhawk.org/users/geofence) to setup a polygon geofence for PX4. I've been testing it using Gazebo in HITL and it works great. When I try to add waypoints outside of the geofence, PX4 does not allow it. During a flight, when the vehicle violates the geofence, it also works really well.

The only thing I'm missing, is actually seeing the geofence visually in QGC. It would be great if we could not only view, but also edit the polygon PX4 geofence using QGC.

Looking at the PX4 code, it supports MAV_MISSION_TYPE_FENCE as well as MAV_CMD_NAV_FENCE_POLYGON_VERTEX_INCLUSION / MAV_CMD_NAV_FENCE_POLYGON_VERTEX_EXCLUSION, so I think it should be able to create polygon geofences in QGC for PX4 ?

I'm using QGC v3.2.7 and PX4 v1.7.0.

**Comment by DonLakeFlyer** [comment]
Already supported. Use a daily build instead of a stable build. Doc: https://docs.qgroundcontrol.com/en/releases/daily_build_new_features.html

**Comment by deonblaauw** [comment]
Nice, thanks! Will give it a try!
