### ISSUE TITLE
We  can not use GoogleSatellite Map.

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6060]
GoogleSatellite Map can not be used in qgroundControl.  It shows  have no statellite data .  But in china   now  ,we can use google map.

**Comment by DonLakeFlyer** [comment]
This is working fine for me. My guess would be problems with you internet provider.

**Comment by MyOnlyOnlySunshine** [comment]
we will try ,thanks
