### ISSUE TITLE
Feature request: Allowing the use of a known location for RTK's base module

### ISSUE THREAD

**Issue by valentinipanini** [mavlink/qgroundcontrol#6082]
Hi guys,

I could not find this option in QGC, but I think it would be great if it was possible to **use RTK without the survey-in option**. The M8P chips allow the setting of a known location for the base's position, but QGC doesn't seem to offer the choice and only allows the survey-in option.

I don't feel it is such a hard feature to implement, and would provide a very good option for RTK and QGC users.

**Comment by driosc** [comment]
Hi valentin, I agree with you. Skipping the survey would allow us to save a lot of time every time we start the RTK in known positions. It would be a really good improvement.

**Comment by DonLakeFlyer** [comment]
Supported now
