### ISSUE TITLE
Similar issue with #5816

### ISSUE THREAD

**Issue by Jdiesel666** [mavlink/qgroundcontrol#6083]
Firmware halted at "programming new version" forever when trying to update on Ubuntu 16.04.
I'm using PixHawk http://ardupilot.org/copter/docs/common-pixhawk-overview.html
The QGround version is 3.2.7 right from the website https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html
The version I had before doesn't have the rover airframe on it. 
I just need qgroundcontrol for the calibration to be able to use it with VINS-Mono.
I'm not sure if I have to install mavros in order to get it to work.

**Comment by DonLakeFlyer** [comment]
Use a new daily build.

**Comment by Jdiesel666** [comment]
@DonLakeFlyer What is the optimal choice of airframe for Ground Vehicle? The daily build doesn't have a Rover and the compass setup kept failing.

**Comment by DonLakeFlyer** [comment]
You'll have to ask firmware folks about that. I assume you are using PX4. Not sure if they support Rover.

**Comment by hamishwillee** [comment]
PX4 only has basic Rover support, but the build and link to frames is here: https://docs.px4.io/en/frames_rover/

**Comment by DonLakeFlyer** [comment]
But that is not in the airframe metadata in QGC hence no Rover shows up. @LorenzMeier Is the airframe meta data out of whack?
