### ISSUE TITLE
/dev/tty.SLAB_USBtoUART Open failed. Resource busy

### ISSUE THREAD

**Issue by RonildoBragaJunior** [mavlink/qgroundcontrol#6095]
Connection between the QGroundControl and Pixracer 1.4 through UART(FPV Radio Telemetry Air Module) is not working.

Discussion:
http://discuss.px4.io/t/how-to-connect-qgroundcontrol-to-pixracer-1-4-through-uart-radio/5597

Hardware:
Pixracer 1.4 

Software:
MacOs High Sierra Version 10.13.3
Firmware v1.7.3 Stable Release
QGroundControl Daily Build

Driver was obtained from here:
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by DonLakeFlyer** [comment]
Can you pull across the log output to here as well?

**Comment by RonildoBragaJunior** [comment]
Thanks... please have a look on the log below.

[log.txt](https://github.com/mavlink/qgroundcontrol/files/1691057/log.txt)

**Comment by DonLakeFlyer** [comment]
Looks like more of a driver problem than a QGC problem. @dogmaphobic Do you know anything about these sorts ofr boards?

**Comment by dogmaphobic** [comment]
SiLabs? That's different. Those are always nasty to get working as they have lousy drivers. See here:

https://www.silabs.com/community/interface/forum.topic.html/cp120x_vcp_driverno-G1Bu

I had the same issue with something completely different, not related to QGC but using one of their USB/UART chips.

**Comment by RonildoBragaJunior** [comment]
It is solved. I believe it was a problem with the driver which I fixed. Thank you.
