### ISSUE TITLE
RC calibration process "hangs" at the end of the process

### ISSUE THREAD

**Issue by jstrebel** [mavlink/qgroundcontrol#6099]
Hi,
I am trying to calibrate my RC. I can do all the steps until to the Point “move the Pitch stick down and hold it there” It seems to me the process does not finish. (only the cancel button is solid) 
Using QGC 3.2.7 stable on Ubuntu Linux, RC is mode 1. Pixhawk SW 1.7.3 I have done this process sucessfully some months ago using a older version on QGC and pixhawk

Jakob

**Comment by jstrebel** [comment]
Same happens doing it with OSX. Jakob

**Comment by jstrebel** [comment]
Solved: It seems the time window to move pitch up and down plus moving throttle down is somehow critical (respective small).

**Comment by DonLakeFlyer** [comment]
> It seems the time window to move pitch up and down plus moving throttle down is somehow critical (respective small).

Can yoy explain in detail what you mean by that? I don't understand.

**Comment by jstrebel** [comment]
Don, pls give me some time. Need to get the pixhawk back in my hands and do the steps again and describe the last 3 steps. Mainly it is the allowed time to move the stick in the desired position.

**Comment by DonLakeFlyer** [comment]
> Mainly it is the allowed time to move the stick in the desired position.

That's the part I don't understand. There is no "allowed" time, the allowed time is forever.

**Comment by jstrebel** [comment]
Don,
Attached is the description of the problem described as good as I can. In my setup it's reproducible. I hope my graphic helps you. If I am not fast enough in step 8, the setup jumps immediatly to step 9. Then exit is only possible by clicking the cancel button.
[QGC_RC_CAL.pdf](https://github.com/mavlink/qgroundcontrol/files/1720040/QGC_RC_CAL.pdf)
Jakob

**Comment by DonLakeFlyer** [comment]
Now I understand. The image for roll right for Mode 1 is incorrect. It shows the throttle as being centered.. The throttle should stay down while you do this. That is confusing the system. Can you try calibration with keeping the throttle down at this step and see if it works. After you complete the steps for throttle up/down the rest of the calibration should be done with throttle all the way down.

**Comment by jstrebel** [comment]
Don, if I follow the steps marked in yellow then it works.
[QGC_RC_CAL.pdf](https://github.com/mavlink/qgroundcontrol/files/1722821/QGC_RC_CAL.pdf)

**Comment by jstrebel** [comment]
Don, I am willing do some testing in case you are going to fix this. 
(Platforms available: OSX or Ubuntu Linux) Jakob

**Comment by ashirsat** [comment]
Hi @DonLakeFlyer I am getting the same issue the process freezes on after calibration with only cancel button activated. I am running the latest version of QGroundControl on Ubuntu 18.04.

Please let me know if you have any suggestions?

Thanks,
Aniket

**Comment by DonLakeFlyer** [comment]
"Latest version" meaning what? Stable or Daily Build? Take a screen shot of the version info which is shown at the bottom of the General Settings page and include here.
