### ISSUE TITLE
Mac Build 2.0.1 does not open on OS X 10.6.8

### ISSUE THREAD

**Issue by bmav** [mavlink/qgroundcontrol#610]
Downloaded the "2.0.1 (build 08) for Mac Os X 10.6+ (x64)" and put it in Applications. When I try to open the app, I get the error message:
qgroundcontrol cannot be opened because of a problem.
Check with the developer to make sure qgroundcontrol works with this version of Mac OS X. You may need to reinstall the application.

The following is available in the crash report:
Process:         qgroundcontrol [17466]
Path:            /Applications/qgroundcontrol.app/Contents/MacOS/qgroundcontrol
Identifier:      org.qgroundcontrol.qgroundcontrol
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [114]

Date/Time:       2014-04-01 14:16:55.320 -0700
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          9133693 sec
Crashes Since Last Report:           15
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      2C47D8BA-B338-4DD3-9646-602E8B96FB90

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Applications/qgroundcontrol.app/Contents/MacOS/../Frameworks/QtDeclarative.framework/Versions/4/QtDeclarative
  Reason: image not found

**Comment by RunnnnWang** [comment]
Hi, I am running into this question too. 
“QGroundControl” cannot be opened because the developer cannot be verified.

**Comment by San-Vu** [comment]
https://stackoverflow.com/questions/27563544/cant-be-opened-because-the-identity-of-the-developer-cannot-be-confirmed

Check this out. It worked for me
