### ISSUE TITLE
Crash in terrain code (Stable 3.3)

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#6103]
I've been getting crashes randomly and today I was able to tell where (but not why). The crash occurs here:

https://github.com/mavlink/qgroundcontrol/blob/master/src/Terrain.cc#L149

Adding it here to keep track.

**Comment by DonLakeFlyer** [comment]
Yeah, I hit that last night as well then forgot about it. I know what it is.
