### ISSUE TITLE
Feature request: search for a specific point on earth on offline maps

### ISSUE THREAD

**Issue by juvinski** [mavlink/qgroundcontrol#6106]
I wish to propose a feature, on the offline function, a way to manually insert a gps coordinate. I'm constantly going to places where there is no internet, so I need to search the map previously - looking and searching until find the correct place I will flight or I'm creating a location on ardusim, start this location and I can center on vehicle position and them download the maps. If there is a textbox or something for input the latitude and longitude to be positioned on the location would be a very welcome feature I think

**Comment by DonLakeFlyer** [comment]
Available in daily builds
