### ISSUE TITLE
cosmetic request: small round corners on "Values" widget

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6132]
Would adding small round corners to the "Values" box be more consistent with the Guided toolbar?
![image](https://user-images.githubusercontent.com/12117027/36108150-bcc1d40e-0fe1-11e8-8b77-7cf039da7bc0.png)

**Comment by dogmaphobic** [comment]
I'm planning on a complete redesign of that control widget. It will be there by 3.4.

**Comment by Antiheavy** [comment]
sounds good.  I'll close this then.
