### ISSUE TITLE
Mavlink Shell support for Mobile

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#6133]
@dogmaphobic It would be great to have the Mavlink shell on Mobile (e.g. tablets). This will simplify outdoor testing.
Hiding it by default and enabling it via a 'Developer Mode' option would be fine for me.

**Comment by DonLakeFlyer** [comment]
Not sure why that is off for Mobile. Don't see any reason for it not to be on.

**Comment by DonLakeFlyer** [comment]
Closing this one since #6375 has more info
