### ISSUE TITLE
PREFLIGHT_STORAGE command should not be sent to all component ids

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6142]
It should only be sent to component ids for which a parameter write was done.

Also while looking at this I found that the command is not sent if a single parameter update is in the queue. The question is whether these problems should be fixed or whether the whole thing should just be removed. ArduPilot doesn't support it and PX4 saves params by default. Not sure if you can turn that off.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Is there any reason to not just remove this code?

**Comment by LorenzMeier** [comment]
Today I think we can really remove it. All systems I know of have double-buffered storage making this obsolete.

**Comment by DonLakeFlyer** [comment]
Awesome thanks.
