### ISSUE TITLE
LogDownload - Erase all logs failing on Windows Environment

### ISSUE THREAD

**Issue by juvinski** [mavlink/qgroundcontrol#6143]
Hi,

I'm using the master version of QGround Compiled build and running on Windows 10, and after downloading the logs, when selecting the button Erase All, the Button Yes is grayed and nothing happens.
Looking at QT debug windows I can see this message:

qrc:qml/LogDownloadPage.qml:189: TypeError: Property 'hideDialog' of object LogDownloadPage_QMLTYPE_320(0x9eb72f0) is not a function

If, even the button Yes is grayes I can select the button No, and the confirmation screen will hide.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you take a look at this? May need a fix to go into 3.3 stable.
