### ISSUE TITLE
Request: Android phone UI

### ISSUE THREAD

**Issue by P43YM** [mavlink/qgroundcontrol#6162]
Can you activate the fullscreen immersive mode on the android and get rid of the navigation bar? 
Here guys here discussed it http://grokbase.com/t/gg/android-qt/13c9try9xt/how-to-activate-immersive-full-screen-mode-in-android-4-4
And definitely there is a problem with the scaling of the interface on the phone: the top panel and the panel on the left are just huge. They can be smaller and possibly even transparent. 
Here's my screenshot from 5.5" full hd android 7 smartphone https://drive.google.com/open?id=1cwqg_rg6eDMcUi_mCXxxHOVPhKrjQVij

**Comment by dogmaphobic** [comment]
QGC UI's is not really meant to be used on small screens. 

For full screen video, just double click/touch the screen.
