### ISSUE TITLE
About  Google satellite map in China；

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6163]
![553c94e5f532d8ff85d6d6209db01891](https://user-images.githubusercontent.com/17830375/36716418-43c4572a-1bd5-11e8-8bec-c6054134d21c.png)

Click Google satellite map failed to load the following print log information, but other types of Google maps normal, may I ask what is the reason, thank you!

**Comment by dogmaphobic** [comment]
Do they work from a regular browser? That is, if you where to launch a browser and go to:

https://www.google.com/maps/@31.1279242,121.4893596,525m/data=!3m1!1e3

Do you see the map?

**Comment by MyOnlyOnlySunshine** [comment]
yes ， I can see the map from the link that you support .

**Comment by dogmaphobic** [comment]
I have no way to work on this. If someone in China can take a look, great. Otherwise, I'm closing it.
