### ISSUE TITLE
Control Drone over wifi usig QGC app?

### ISSUE THREAD

**Issue by SaiKrishnaTheGreat** [mavlink/qgroundcontrol#6164]
Hi,

Making drone with snapdragon flight board. Here I want to control drone using android app(QGC) over wifi. Configuring for different sensors like compass, gyro and accelerometer has been done. 

Here My question is Do I need to configure QGC app with Radio? And how to Radio setup if I don't want to use remote control transmitter?. 
Note : I require drone can controlled through app. It should not depend on any machine/RC.

Thanks,
Krishna

**Comment by hamishwillee** [comment]
Probably better to raise this in the PX4 discussion forum. 

My understanding though is that you need to set [COM_RC_IN_MODE](https://docs.px4.io/en/advanced_config/parameter_reference.html#COM_RC_IN_MODE) to 1

YOu shouldn't need to do any other RC setup.
