### ISSUE TITLE
Bad user experience on windows touch screen tablet

### ISSUE THREAD

**Issue by feemi** [mavlink/qgroundcontrol#6167]
Panasonic tough pad touch screen is working pretty good normally. But in app tappings pinchings and slidings are not working smoothly. 

Survey planning is almost impossible. 
Sliding to confirm is really hard to achieve.
Dropdowns needs long tap or double tap to open.

----
General Information
- Panasonic ToughPad FZ-G1 Windows 10 Pro
- v3.3.0
- Pixhawk 2
- PX4

**Comment by DonLakeFlyer** [comment]
@NaterGator Do you have any touch screen windows devices? I don't have anything to test whether this is a general problem or not.

**Comment by NaterGator** [comment]
I have a Surface Pro 3 I can try it out on. If memory serves I have been a bit unimpressed with Qt's multitouch gesture handling on Windows before.

**Comment by feemi** [comment]
I realised that experience got worse when i update windows 10. It was almost impossible to use it.  When i reverted the windows updates experience is acceptable with pen. But still moving survey plan polygons with finger is frustrating.

**Comment by feemi** [comment]
Hi Don, The experience got better after qt update. We have still some issues with dropdown tapping. but pinching map is way better now.

**Comment by DonLakeFlyer** [comment]
> We have still some issues with dropdown tapping. but pinching map is way better now.

Can you give a specific example?

**Comment by DonLakeFlyer** [comment]
I'll make a swing prior to 3.5 stable with windows touchscreen. If you have a specific dropdown case I can look at can you create a new issue.
