### ISSUE TITLE
Problem - flash firmware to pixhawk

### ISSUE THREAD

**Issue by jjkjrpe** [mavlink/qgroundcontrol#617]
get the following loop after clicking scan button in config:

Starting uploader to read bootloader
Found PX4 on Com 7
Scanning for bootloader
bootloader not responding (attempt to reset)
attempting reboot

please help

**Comment by dayinthepark** [comment]
I've been working on this exact issue almost two months. Qgroundcontrol occasionally sees the pixhawk, but when asked to unplug then replug, it ignores me.  Connecting via telemetry is fine.  When I try configuring the quad drone, QGC tells me it's missing parameters, that usually means new firmware is needed.  But same problem again and again.  QGC cannot see the Pixhawk via USB.  If insanity is trying the same thing over and over expecting different results, I'm getting very close to insane. I don't know what else to try.  and apparently you cannot load firmware using a Windows system or AMP, I'm really stuck.
