### ISSUE TITLE
Elevation/Terrain data not working anymore

### ISSUE THREAD

**Issue by philipoe** [mavlink/qgroundcontrol#6170]
The elevation/terrain data retrieval process does not work anymore.

OS: Ubuntu 16.04 (actually tested on mine and a colleague's computer on which it still worked in January)
QGC: Master, 6711810 (February 24th 2018)
Autopilot: Pixhawk (but tested in SITL or when the autopilot was not even connected)
How to reproduce: Set a number of waypoints. No terrain data is shown anymore (there is just a white line).

Debugging: I don't know the AIRMAP api and the respective code in QGC well, but tried to debug and at least got the following: The request sent to the airmap servers looks as follows:

![screenshot from 2018-03-01 15-23-00](https://user-images.githubusercontent.com/2565608/36851942-d646a530-1d6a-11e8-8970-347b9cc52a6b.png)

The response from the airmap servers is then a html document that has the content "Error, cannot GET SRTM1 ele". So I assume something in the airmap API changed (although i could not find good documentation on how to retrieve elevation data from their APIs).

@DonLakeFlyer @birchera You definitely have a much better insight into the airmap API.

_Edit: Just verified that the same problem exists on Windows 10 with both the stable (v3.3) build and the Daily build from today (44d33ceaa)._

**Comment by birchera** [comment]
The elevation API seems broken. I contacted Airmap and will update here once I get a response.

**Comment by DonLakeFlyer** [comment]
Thanks folks for looking into this.

**Comment by DonLakeFlyer** [comment]
Any updates?

**Comment by birchera** [comment]
No response yet.

**Comment by DonLakeFlyer** [comment]
I"ve pinged them on a direct slack channel that I have to them. They've ackknowledged but no solution yet.

On Mar 14, 2018, at 11:57 PM, Andreas Bircher <notifications@github.com<mailto:notifications@github.com>> wrote:


No response yet.

**Comment by birchera** [comment]
Thanks for fixing. Will push the necessary changes for offline elevation data shortly.

**Comment by DonLakeFlyer** [comment]
FYI: I'm having to rework the correct Terrain.h/cc code. So you should wait until I push that through. Current code was a mess with respect to adding additional query types. Like heights along a path for example.
