### ISSUE TITLE
Graph/Export: .kml export success, then segfault

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#6181]
```
Thread 1 "apmplanner2" received signal SIGSEGV, Segmentation fault.
0x00007ffff5d33728 in QDialog::accept() () from /home/andre/Qt/5.9.4/gcc_64/lib/libQt5Widgets.so.5

```
- the exported file is fine. AP2 crashes once I click "OK" inside the "success" messagebox.
- I am not sure whatever the file I attached is required to reproduce. 
- 100% reproducible every time here.
- could somehow be related to Qt5.9.4 , which is otherwise working perfectly (?)

[2018-03-02 14-29-16.zip](https://github.com/mavlink/qgroundcontrol/files/1786195/2018-03-02.14-29-16.zip)

**Comment by dogmaphobic** [comment]
>apmplanner2

?

**Comment by AndKe** [comment]
ooops :)
