### ISSUE TITLE
Auto-Connects to all saved Comm links

### ISSUE THREAD

**Issue by ryanjAA** [mavlink/qgroundcontrol#6189]
Using QGC 3.3.0 release on a mac, once started QGC tries to connect to every comm device that is saved (and that has auto-connect enabled), even if they are not plugged in. Doesn't do this with previous versions. I have 7 different comm links saved. Does it with serial and tcp links.

**Comment by ryanjAA** [comment]
@dagar

**Comment by DonLakeFlyer** [comment]
What exactly is the bad behavior? Errors popping up you didn't get before?

**Comment by ryanjAA** [comment]
Automatically connects to every saved comm-link (ones that are not plugged in)


![qgc](https://user-images.githubusercontent.com/31726584/37357343-2ec68ea6-26b6-11e8-9c61-43eb58778594.gif)

**Comment by DonLakeFlyer** [comment]
@ryanjAA I'm trying to remember how it worked before. If auto-connect was checked what did that mean in previous builds?

**Comment by ryanjAA** [comment]
Autoconnect is present in the previous builds in the Preferences -> General, then there is a box for choosing which type you want it to auto connect to. Previous to this version even if they were all selected to connect to and you had 10 serial links saved, it would only connect to ones that were plugged in. I just loaded up QGC 292 and all my links are still saved but it doesn't try to connect to them unless I plug one in. Conversely, I just loaded up todays daily build and it still tried to connect to all of them.

**Comment by DonLakeFlyer** [comment]
Ah, ok. I was looking at the wrong autoconnect setting.

**Comment by DonLakeFlyer** [comment]
Hmm, I can't repro on Daily or Stable.

**Comment by DonLakeFlyer** [comment]
Is this still happeing in latest daily builds

**Comment by DonLakeFlyer** [comment]
Reopen if still problems
