### ISSUE TITLE
Set RC to Param not working in QGC v3.3.0

### ISSUE THREAD

**Issue by larryyonge** [mavlink/qgroundcontrol#6191]
Selecting "Advanced settings" -> "Set RC to Param..." in Parameter Editor is not working in QGC 3.3.0 with PX4 v1.7.3 on Pixhawk, tested on Ubuntu 16.04.  In the Set RC to Param Dialog window, "Center value" and "OK" are grayed out and "Waiting for parameter refresh..." is displayed.  "Set RC to Param" works correctly in QGC v3.2.7.

![image](https://user-images.githubusercontent.com/18093088/37294396-193d170a-25ec-11e8-8033-a4059c749d82.png)

**Comment by BazookaJoe1900** [comment]
Has this been fixed on 3.3.2?
not for me, in windows

**Comment by DonLakeFlyer** [comment]
It is fixed in daily builds. It will not be fixed in 3.3.2

**Comment by Molecuman** [comment]
Is not working for me on the 3.5 version

**Comment by DonLakeFlyer** [comment]
> Is not working for me on the 3.5 version

@Molecuman Please open a new issue with some useful details as to how exactly it is "not working"

**Comment by Molecuman** [comment]
The same thing of this thread

**Comment by DonLakeFlyer** [comment]
> In the Set RC to Param Dialog window, "Center value" and "OK" are grayed out and "Waiting for parameter refresh..." is displayed.

This is what you are seeing?

**Comment by Molecuman** [comment]
No. The RC to parameter function is not showing up

**Comment by DonLakeFlyer** [comment]
I just tried 3.5.4 and it's working fine for me:
![Screen Shot 2019-09-04 at 1 19 12 PM](https://user-images.githubusercontent.com/5876851/64288312-a53d5100-cf16-11e9-8479-bbc5a78e35dc.png)

**Comment by Molecuman** [comment]
Maybe is my system or the QGC Windows version. The button is there, is not
gray. The screenshot just shows the button highlighted but after pushing
it, nothing happens

[image: image.png]

**Comment by WhiteBearSpirit** [comment]
Same problem: pressing 'Set RC to Param' is now showing any dialog box. QGroundControl 4.0.5, Windows 10.

**Comment by DonLakeFlyer** [comment]
> pressing 'Set RC to Param' is now showing any dialog box. QGroundControl 4.0.5, Windows 10.

This feature is missing from the 4.0 releases. I'll add it back soon.

**Comment by Molecuman** [comment]
Thank you!

**Comment by DonLakeFlyer** [comment]
Also until then Set RC to Param just sets up a number of parameters with a nice ui. It all can be done manually through the parameter editor.

**Comment by DonLakeFlyer** [comment]
> Also until then Set RC to Param just sets up a number of parameters with a nice ui. It all can be done manually through the parameter editor.

Sorry. That is incorrect. This is a command not parameters. So no way to do it without GCS support.

**Comment by DonLakeFlyer** [comment]
@Molecuman I added it back: https://github.com/mavlink/qgroundcontrol/pull/8657. Can you help with testing it out
