### ISSUE TITLE
Customized map(Google) for QGC

### ISSUE THREAD

**Issue by arun2204** [mavlink/qgroundcontrol#6199]

**Comment by arun2204** [comment]
Hi All, Is it possible to customize or change theme of map used in QGC, precisely want to change theme of Google map used for QGC. Google is providing javascript based api but don't know how to use that with C++ based code as used in QGC.

**Comment by DonLakeFlyer** [comment]
QGC uses URL based map tile query. Changing to javascript would be a huge undertaking.
