### ISSUE TITLE
Survey options not viewable/ editable on tablet

### ISSUE THREAD

**Issue by JonReacher** [mavlink/qgroundcontrol#6208]
Samsung Galaxy Tab A 10.1"
QGC 3.3.0

Only workaround for survey altitude is to enter desired altitude as mission altitude, which changes all waypoints and surveys, then manually change other waypoints as needed.

![screenshot_20180313-170048](https://user-images.githubusercontent.com/22160410/37370884-f9bea710-26e3-11e8-9082-75ad48349e9d.png)

**Comment by DonLakeFlyer** [comment]
Behold the compass rose from hell!

**Comment by JonReacher** [comment]
I thought it was a bold move.

**Comment by DonLakeFlyer** [comment]
I can repro this on my tablet

**Comment by DonLakeFlyer** [comment]
This fix is available in daily builds now. I'll mark a new Stable in the new few days and it will show in there as well then.
