### ISSUE TITLE
menu icon not shown correctly

### ISSUE THREAD

**Issue by lijieamd** [mavlink/qgroundcontrol#6230]
![screenshot from 2018-03-17 11-36-13](https://user-images.githubusercontent.com/4757414/37551316-a278bd9a-29d8-11e8-99f1-ba915d9644cb.png)

the top menu icons are not shown

i'm using the latest QGroundControl.AppImage from here:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGroundControl.AppImage

OS: ubuntu16.04LTS

**Comment by DonLakeFlyer** [comment]
Working fine for me on same Ubuntu version. My guess would be something with your OpenGL driver.

@dagar Do you run Ubuntu? Could you double check a daily build?

**Comment by DonLakeFlyer** [comment]
@lijieamd Are you still seeing this? have you look at updating your OpenGL driver?

**Comment by lijieamd** [comment]
@DonLakeFlyer I found that all worked fine after connected to px4 board a few days ago, so i guess if there something wrong in qgroundcontrol initialization process?

ok, i'll updating my opengl driver and try again

**Comment by lijieamd** [comment]
sorry, it's just my guess.
this problem has not happen again after i connected to px4 board hardware.

**Comment by DonLakeFlyer** [comment]
Ok, closing since working correctly nopw.
