### ISSUE TITLE
Add "return to launch" command waypoint to mission planning

### ISSUE THREAD

**Issue by sashan13** [mavlink/qgroundcontrol#6236]
There's a MAV command called "mav_cmd_nav_return_to_launch". I propose that it is added as a possible "waypoint" so that we can simply trigger RTL at the end of a mission. Tower app for Android already does that.

**Comment by DonLakeFlyer** [comment]
You can turn on "RTL at mission end" from the Mission Start item. I know, doing it from Mission Start is strange. Looking at new naming.
