### ISSUE TITLE
Library tests should use link tests, not checking hardcoded paths

### ISSUE THREAD

**Issue by koenkooi** [mavlink/qgroundcontrol#624]
QGCExternalLibs.pri contains broken constucts like:
  exists(/usr/include/espeak) | exists(/usr/local/include/espeak)
This breaks cross-compilation and installs where external libs might be in /opt or /lib.

The second problem is that the header being present doesn't mean that the lib works or is the correct version.

**Comment by DonLakeFlyer** [comment]
Going to leave this as is. Too much other work to do to make this more flexible.
