### ISSUE TITLE
terrain information not downloading

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6255]
I'm having problems getting the terrain data to download or work on recent daily builds.  Tried several daily builds over the last week, most recent on 2018-03-23.  Tried this on several windows PCs and several different internet connections with similar results.

waypoints planned in a golf course with hills, no terrain shown:
![image](https://user-images.githubusercontent.com/12117027/37869653-8c142f06-2f89-11e8-99cc-918c6288f2d4.png)

"UnknownNetworkError" in console each time I place a waypoint:
![image](https://user-images.githubusercontent.com/12117027/37869663-b7fa3d40-2f89-11e8-8b87-c4ec768eb044.png)

also,
![image](https://user-images.githubusercontent.com/12117027/37870851-71909928-2fa5-11e8-8e65-ca4504d9ec65.png)

am I doing something wrong?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Any idea what QNetworkReply::UnknownNetworkError might mean? Todd was saying he isn't behind a proxy but he is behind a firewall.

**Comment by DonLakeFlyer** [comment]
I've added better logging which hopefully will help figure this out. New build should be available in couple hours.

**Comment by DonLakeFlyer** [comment]
@Antiheavy Have to tried very latest daily builds. It should hae additional TerrainQueryLog logging for these errors which will help me.

**Comment by Antiheavy** [comment]
using 2018-03-27 daily build - this is what is says when I try to place waypoints.  same thing on 2 different PC's on 2 different internet connections (home and office).  see screenshot and also attached AppLog (zip file).
![image](https://user-images.githubusercontent.com/12117027/38054124-a1015320-329b-11e8-8447-b81950c63f89.png)
[terrain-not-working.zip](https://github.com/mavlink/qgroundcontrol/files/1857605/terrain-not-working.zip)

**Comment by DonLakeFlyer** [comment]
Hmm, it's like it can't resolve the domain. It's not getting anything back.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you have any ideas how to debug this?

**Comment by DonLakeFlyer** [comment]
@NaterGator Nate could you see if terrain information downloads for you on Windows?

**Comment by DonLakeFlyer** [comment]
This should be working now
