### ISSUE TITLE
"Upload Required" button flashes once then reverts to plain old "Upload" button.  Sync button does not flash.

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6256]
In QGC Daily (2018-03-23), when the mission is changed,  the "Upload Required" button only flashes once and then it changes back to the normal "Upload" button.  The "Sync" button also reverts to the normal look, not the flashing (!) look.  this seems like a bug?

![image](https://user-images.githubusercontent.com/12117027/37870605-d99a9b8c-2f9f-11e8-81eb-595d8299fed5.png)

**Comment by DonLakeFlyer** [comment]
Is there something specific to landing pattern here? I can't get this to reproduce. Will need more detailed steps.

**Comment by Antiheavy** [comment]
Here is a video of the Upload Required button and sync button auto-disappearing:
https://youtu.be/9zoTc0jsft4

**Comment by DonLakeFlyer** [comment]
I think this may have been related to the various terrain download issues which have been fixed. Can you try to repro in new daily?

**Comment by Antiheavy** [comment]
Yep! seems to be back to working in the new daily (tested on Windows 2018-04-29).  The Upload Required still disappears in our custom branch though, but I think the terrain fixes haven't been rolled into that custom branch properly so your hypothesis might make sense.  Anyway, closing this.

**Comment by Antiheavy** [comment]
wait a second!  it's broke again when I switch to Feet measurement units (feet, acres, mph, F).  Both the altitude bars are broken and also the Upload Required button.... err....

**Comment by Antiheavy** [comment]
okay, working in both feet and meters now with the latest Daily (maybe there was a scaling issue or something?).
