### ISSUE TITLE
corridor scan stability and "bad vertex" console spam

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6257]
I'm seeing stability issues playing around with Corridor Scan in the 2018-03-23 Daily. 

When I draw or adjust a corridor scan I see a lot of these message spam in console:
![image](https://user-images.githubusercontent.com/12117027/37870862-e47e5e2a-2fa5-11e8-8bce-8d014e028989.png)

also QGC crashes sometimes when creating or editing Corridor Scans (windows 10):
![image](https://user-images.githubusercontent.com/12117027/37870876-789da30e-2fa6-11e8-8b6e-51eaf8a0c99c.png)

**Comment by Antiheavy** [comment]
also, not sure if it is related, but the terrain data was also not working for me:
https://github.com/mavlink/qgroundcontrol/issues/6255

**Comment by DonLakeFlyer** [comment]
> QGC crashes sometimes when creating

It crashes right after you click the Corridor Scan button?

**Comment by DonLakeFlyer** [comment]
> editing Corridor Scans

Editing how. While you are dragging a point around or while you can changing a value?

**Comment by DonLakeFlyer** [comment]
Found at least one of them. But sure if all yet. You can try new build in a bit and then if still crash need more specifics on repro steps.

**Comment by Antiheavy** [comment]
> It crashes right after you click the Corridor Scan button?

sometimes, it is very intermittent.



> While you are dragging a point around

yes, sometimes, very intermittent.



> You can try new build in a bit and then if still crash

will do.

**Comment by Antiheavy** [comment]
Still crashing on Daily 2018-03-25.  Application crash happens most often with clicking on the Corridor Scan button from the Pattern Toolbar.  

It seems to be 100% repeatable if I check the Console, see that I'm getting "NetworkError" messages related to TerrainQuery.  then go back to Plan screen, press the Corridor Scan button, ... crash.
Still happening on Daily 2018-03-25.

**Comment by Antiheavy** [comment]
and if I wait until it starts showing ...."Downloading" 2 2" etc, it will still often crash when trying to create a Corridor Scan, but not always:
![image](https://user-images.githubusercontent.com/12117027/37881427-8c742652-305d-11e8-8321-8905bf38e8c8.png)

**Comment by DonLakeFlyer** [comment]
The "bad vertext requested" log output are all gone now?

**Comment by DonLakeFlyer** [comment]
I'd say it's a 75% chance I found and fixed it now!

**Comment by Antiheavy** [comment]
> The "bad vertex requested" log output are all gone now?

i didn't notice them in the 2018-03-25 daily.  



> I'd say it's a 75% chance I found and fixed it now!

I'll try testing the next daily once it is out.

**Comment by DonLakeFlyer** [comment]
New daily is available

**Comment by Antiheavy** [comment]
I have not been able to repeat the crash using the 2018-03-27 daily build.  Seems you might have fixed it.

I still get "...UnknownNetworkError...." type message every time I place a waypoint or create a new vertex, but that must be a different problem.
![image](https://user-images.githubusercontent.com/12117027/38009324-502bcd0e-3219-11e8-94fe-59381090cabc.png)
