### ISSUE TITLE
QGC 3.3 Joystick: Pitch and Roll reversed.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#6261]
PX4 1.7.3
QGC 3.3
Joystick: Mad Catz F.L.Y.5
Flying Wing. (VTOL)

The pitch and roll are reversed, i.e. on a Pitch movement of the joystick I move the roll of the plane and on a Roll movement of the joystick I move the pitch of the plane.

**Comment by DonLakeFlyer** [comment]
Are you sure you calibrated correctly. Pitch/Roll working fine for me testing in SITL. Yaw/Rudder doesn't seem to be working though.

**Comment by tubeme** [comment]
I'm sure I calibrated correctly because I see the movement of the slider in QGC and it is correct. I re-calibrated couple of times thinking it is the calibration.
