### ISSUE TITLE
QGC 3.3 Joystick: Joystick/ No RC Checks Error after arming

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#6263]
PX4 1.7.3
QGC 3.3
Joystick: Mad Catz F.L.Y.5
Flying Wing. (VTOL)

When Joystick/ No RC Checks is used. After arming with the button, and then arm with joystick switch i receive the following error and cannot arm. It does it all the time without any problems to the HW.

![173 error on arming after button joystick no rc](https://user-images.githubusercontent.com/12617619/37880451-38e3bc08-3091-11e8-9428-3cce77c240ac.png)

**Comment by DonLakeFlyer** [comment]
QGC isn't in control of that. Some sort of firmware problem.
