### ISSUE TITLE
QGC 3.3 Joystick: Virtual RC by Joystick - RC fights joystick all the time.

### ISSUE THREAD

**Issue by tubeme** [mavlink/qgroundcontrol#6265]
PX4 1.7.3
QGC 3.3
Joystick: Mad Catz F.L.Y.5
Flying Wing. (VTOL)

When you arm in Virtual RC by Joystick mode and you have your RC switched on there is no way you can control the plane because the elevons jitter between the RC and joystick commands. Only if you switch off the RC you can control the plane with the joystick.

**Comment by DonLakeFlyer** [comment]
That would be a firmware issue.
