### ISSUE TITLE
Can we plan strip line or framework route？

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6267]
Hello ,we want to  plan strip line and framework route, but we haven't seen the function now .Can you tell us  these ,thanks.

**Comment by DonLakeFlyer** [comment]
Are you talking about this: #5695 or something else?

**Comment by MyOnlyOnlySunshine** [comment]
Yeah, thanks. These  functions are what we want to use for reference,but I don't know wheather you have  finished these functions or develop git branch.

**Comment by DonLakeFlyer** [comment]
Corridor Scan is available in Daily Builds. It is a new feature though so it requires a high level of being careful with usage to make sure you don't hit bugs.
