### ISSUE TITLE
Joystick inputs no longer visible unless calibrating

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6269]
You used to be able to move joysticks around and seem the results in the Joystick window. Now you can only see that when calibrating. This was broken by a recent change. Not sure if this is broken in 3.3 stable as well. I think the change that broke was related to the wierd tri-state is calibrating flag that was changed to a bool maybe.

@jaxxzer Did you make that state change? This is broken now.

**Comment by DonLakeFlyer** [comment]
@jaxxzer Do you remember this change?

**Comment by jaxxzer** [comment]
I don't think this was me.

I can try to help find the problem, though.

**Comment by DonLakeFlyer** [comment]
Ok, thanks. Let me dig into the source a little to figure out who. Give me a day to do that before looking.

**Comment by jaxxzer** [comment]
ok

**Comment by DonLakeFlyer** [comment]
@nanthony21 Your change here: https://github.com/mavlink/qgroundcontrol/commit/02a8b5b1d0fc9551f319553bd4f36e7257fdfbf8#diff-7179de35ff534916a12fd2e757566fe8 has broken the ability to see joystick movement while you aren't calibrating. Could you fix that?

**Comment by nanthony21** [comment]
@DonLakeFlyer I'm not seeing the issue you described on the current master branch. From what I see it always shows the joystick inputs on the right side of the page and the only time that it doesn't show the joystick values on the left side of the page is when joystick input is disabled. Do you have any advice on how to reproduce the issue?

**Comment by DonLakeFlyer** [comment]
Let me try it again myself. Was getting a number of report from folks on this. That doesn't seem to match what I was seeing.

**Comment by DonLakeFlyer** [comment]
Hmm, not sure what I was doing/seeing. Now I don't see it either. All working fun. @nanthony21 Sorry for the false alarm. Thanks for helping out.
