### ISSUE TITLE
Speech is garbled after recent update

### ISSUE THREAD

**Issue by estechnical** [mavlink/qgroundcontrol#6282]
Ubuntu 16.04
Qgroundcontrol 3.3.1 appimage

The speech is garbled and used to be fine. A male unintelligible voice replaced the clear female speech that was working before I updated.

Have I missed an installation step?
Thanks :)

**Comment by DonLakeFlyer** [comment]
No extra installation needed.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you take a look at this?

**Comment by DonLakeFlyer** [comment]
@dagar Are you getting bad speech as well?

**Comment by DonLakeFlyer** [comment]
As far as we can tell this is working fine
