### ISSUE TITLE
setting.json does not change.

### ISSUE THREAD

**Issue by simba155** [mavlink/qgroundcontrol#6290]
I'm a beginner about arisim.
I want to use the computer vision mode and am trying to modify the settings.json.
If I play my PROJECT of UE4 after changing, setting.json returns to original state like the photo below.
![1](https://user-images.githubusercontent.com/37922172/38167960-0a91a632-357b-11e8-9c67-47a7e35422a7.png)

What should I do?? Please help me..

**Comment by DonLakeFlyer** [comment]
I think you are in the wrong place. This is not AirSim
