### ISSUE TITLE
Typo? - Parameters-Sensors-MaxBotix Soanr (mb12xx)

### ISSUE THREAD

**Issue by igalloway** [mavlink/qgroundcontrol#6294]
QGC V3.3.1 For parameter:
SENS_EN_MB12XX  the text is "Maxbotix Soanr(mb12xx)"
Should "Soanr" be "Sonar"?

**Comment by DonLakeFlyer** [comment]
Parameter metadata comes from the firmware. So you need to post and issue there.

**Comment by hamishwillee** [comment]
I created PR for this: https://github.com/PX4/Firmware/pull/9225
