### ISSUE TITLE
Add Qt Charts to S3 Qt Images

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6296]
Tuning page now uses charts. So broken on published daily builds since no Charts module.

**Comment by dogmaphobic** [comment]
Qt Charts, as far as I know doesn't work with QML on Qt Widget. It used to require a "real" QML app. Has this changed?

**Comment by dogmaphobic** [comment]
Oh, that would be the QML version of charts...

**Comment by DonLakeFlyer** [comment]
It's working on desktop version fine. I'm finding it doesn't work on Android!

**Comment by DonLakeFlyer** [comment]
Which I just found out a few seconds ago. Not sure what is going on with Android.

**Comment by DonLakeFlyer** [comment]
Do you remember the deal with QGuiApplication on mobile? It seems to work fine with QGuiApplication.

**Comment by DonLakeFlyer** [comment]
Done
