### ISSUE TITLE
can we have Joystick rate as parameter

### ISSUE THREAD

**Issue by barzanisar** [mavlink/qgroundcontrol#6297]
Hi,
I am using crazyflie flashed with PX4 and crazyradio PA which works better with joystick rate of 5-15 Hz rather than 25Hz.
Joystick rate is hard coded as 25 Hz in [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/Joystick/Joystick.cc#L546).
Can somebody please make it as a parameter to change in QGC?
Thank you.

**Comment by dogmaphobic** [comment]
Done in #6304
