### ISSUE TITLE
Support PING protocol

### ISSUE THREAD

**Issue by mhkabir** [mavlink/qgroundcontrol#6329]
@DonLakeFlyer We need QGC support for returning the mavlink `PING` message (http://mavlink.org/messages/common#PING). 

I implemented the PX4 side here : https://github.com/PX4/Firmware/tree/pr-ping-protocol. It now needs QGC to return the ping messages (filled with sysid and compid of the system QGC received the ping from) so that we have a working test case.

It would be great if you could look into this. Thanks!

See also : https://github.com/PX4/Firmware/issues/9233

**Comment by DonLakeFlyer** [comment]
This doesn't make sense to me:
```
Unix timestamp in microseconds or since system boot if smaller than MAVLink epoch (1.1.2009)
```

What should time value be?

**Comment by dogmaphobic** [comment]
Boot time is usually only for micro controllers. QGC would return `QDateTime::currentMSecsSinceEpoch() * 1000)`

**Comment by DonLakeFlyer** [comment]
> if smaller than MAVLink epoch (1.1.2009)

This seems to indicate there is a different time format it wants.

**Comment by mhkabir** [comment]
> This seems to indicate there is a different time format it wants.

The time should be in microseconds since UNIX epoch. We just use 1.1.2009 as a check for validity of the system's current RTC time.

**Comment by DonLakeFlyer** [comment]
The mavlink spec needs a whole bucket of updating! So QGC is supposed to respond with a PING message which:
* Has the timestamp from the original message
* What does it do with the seq field?

**Comment by mhkabir** [comment]
@DonLakeFlyer 
> Has the timestamp from the original message
Yes. (left untouched)
> What does it do with the seq field?
This is set from original message. (left untouched)

For the other two fields, sysid and compid : 
These will be set to the sysid and compid of the system which sent the original message to QGC.

**Comment by mhkabir** [comment]
@DonLakeFlyer Any updates on this? Thanks!

**Comment by DonLakeFlyer** [comment]
None. I just got back from being out of town for two weeks.

**Comment by mhkabir** [comment]
This is done. Thanks a lot Don!
