### ISSUE TITLE
QGC Failure to download params with RFD900 radios

### ISSUE THREAD

**Issue by ChristopherOlson** [mavlink/qgroundcontrol#6330]
QGC 3.3.0 on both Windows and Mac fails to download the full parameter list and halts with RFD900 radios. Did not try it with Android. Pixhawk 2.1 with Copter 3.5.5.

QGC works fine with standard 3DR radios or USB connection (verified here on all platforms).

Tried the same RFD900 with MP and it seemed to work ok on Windows.

**Comment by DonLakeFlyer** [comment]
I'm working to get a repro of this. Hopefully I have it on on windows. But won't get to it until I get back in town., Gone for a couple weeks.

**Comment by ChristopherOlson** [comment]
Thanks Don. Finding folks that can test with RFD900's is a little hard.

**Comment by DonLakeFlyer** [comment]
I had thought that maybe there was some commonality to the problems we were having on UDP. Turns out those were specific to UDP. So still at a loss as to what is going on here. After parameter download fails wondering if all traffic to the vehicle is failing. Can you do things like arm with QGC? Can you upload a mission?

**Comment by DonLakeFlyer** [comment]
So that would indicate the QGC->Vehicle traffic is pretty much dead. Which sounds more like radio setup problems. Other wild guess may be mavlink 2 protocol switching of the QGC->Vehicle link. You could force mavlink 1 only to try that.

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I got it to work. The problem was the multipoint firmware in the radios. I went to the point to point v1 firmware and then worked. So the problem was not in QGC at all. So closing this. Thanks for looking at it, but glad I found the issue.

**Comment by kikislater** [comment]
Should warn about this also : 
https://diydrones.com/forum/topics/rfd900-new-long-range-radio-modem?commentId=705844%3AComment%3A2443000&xg_source=msg_com_forum

Adding delay to telemetry radio
