### ISSUE TITLE
[Improvement] Calibration result texts of airspeed sensor disappear abruptly when finishing

### ISSUE THREAD

**Issue by bigbellmercy** [mavlink/qgroundcontrol#6333]
Problem:
While in airspeed calibration, text results of the airspeed calibration screen disappear abruptly right after blowing the sensor. So users cannot assure the calibration result succeeded or not.

Environment:
Ubutu 14.04, QGC v3.3.1

Thanks for excellent QGC!

**Comment by DonLakeFlyer** [comment]
What type and version of firmware? Can you take a screenshot of the end result where you can't see the results any more.

**Comment by bigbellmercy** [comment]
Firmware: v1.7.3 in Pixhawk2.1

Screen shot after finishing calibration of airspeed sensor:
![qgc after airspeed calibration](https://user-images.githubusercontent.com/20110695/38589081-08b94cca-3d64-11e8-9d72-914bf269ff89.png)

**Comment by Antiheavy** [comment]
> Problem:
> While in airspeed calibration, text results of the airspeed calibration screen disappear abruptly right after blowing the sensor. So users cannot assure the calibration result succeeded or not.

yes, this is annoying.  I don't know if it is a QGC thing or a firmware thing.  it seems like the text should persist as long as the view is open, even after completing the test, there should be a "success" type message left onscreen as the most recent message.   if the view is changed out of the Sensors tab, then it might still be nice if the calibration display zeroed out or whatver the term would be...

**Comment by DonLakeFlyer** [comment]
My guess is the firmware started sending an airspeed cal finished text or something that wasn't there before. I believe the text used to stay up.

**Comment by Antiheavy** [comment]
> My guess is the firmware started sending an airspeed cal finished text or something that wasn't there before. I believe the text used to stay up.

@dagar any insight here?

**Comment by DonLakeFlyer** [comment]
I can fix from QGC side.

**Comment by DonLakeFlyer** [comment]
> My guess is the firmware started sending an airspeed cal finished text or something that wasn't there before. I believe the text used to stay up.

Nope. They always disappeared. Level horizon has the same problem.
