### ISSUE TITLE
MAV_FRAME_GLOBAL_TERRAIN_ALT not showing as Show all values

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#6342]
I tried to use current master profesionally today.
QGC detected and handled RTK great.
I drew a mission , all waypoints were terrain relative, 1.5m above (by LIDAR).
When trying to upload I QGC denied to do so because of missing /fetching terrain data 
(I have a screenshot with the exact wording, not here.) 

I did get map tiles, so even with only GPRS link, we did had internet connection, but QGC would stop the show.  (if I did not had other GCS systems to choose from)

in any case:
fetching terrain data should NOT be enforced that hard, especially when we fly with LIDAR as primary data source.

This is rather serious, it would stop the operation.

**Comment by AndKe** [comment]
Err I would disagree.
Ehen EKF is set to use Lidar as primary altitude source, a mission with *no* elevation data will/does work just fine, in fact, the elevation data is irrelevant/not used as the lidar will define the altitude for those points.

So this mission is a valid one, perfectly working with apmplanner/mavproxy etc, but QGC decide to enforce the requirement of terrain elevation.  - which apparently failed (and does not have a progess bare or other visual indicators.)

the area covered were less than 200x100 meters, so it was not a lot of data, to day the least. :)

In any case: I would think it was nice to warn me about missing elevation data, but denying operation is overkill for any user that know ArduPilot.

**Comment by DonLakeFlyer** [comment]
I think you are missing the point. This feature does not support ArduPilot terrain following. It just is setting absolute heights (MAV_FRAME_GLOBAL) into mission items. It is not setting the MAV_FRAME on mission items to MAV_FRAMEGLOBAL_TERRAIN_ALT.

I think in mission planner there is a thing called "check heights" or something like that which adjust the mission items heights. It is like that.

**Comment by AndKe** [comment]
I do not know about mission planner, can run it in mono as a test, but it's a windows thingy :)

So I used a test mission linke:
```

QGC WPL 110
0	1	0	16	0	0	0	0	69.7561874389648438	18.8628387451171875	241.979995727539063	1
1	0	10	16	0	0	0	0	69.7556915283203125	18.8636550903320313	1.5	1
2	0	10	16	0	0	0	0	69.7549414195638349	18.8628494739532471	1.5	1
3	0	10	16	0	0	0	0	69.7550082456289431	18.8623988628387451	1.5	1
4	0	10	16	0	0	0	0	69.7556616449082583	18.8632464408874512	1.5	1
....
```

it's generated using ApmPlanner2 , and worked fine - low loading this file into:
AP2 - displays the WP altitude as "Ter.Alt"
MavProxy (misseditor module)  , displays the WP altitude as "AGL" 
QGC: Displays the WP altitude as "AMSL" (!)
MissionPlanner: displays the WP alt as "Terrain"    (I don't even know why it shows only one frame for all the mission)

So, given my mission file, the second digit says the frame (0) is MAV_FRAME_GLOBAL , AMSL,   
in such case, all of them , except of QGC, have an issue.  ?

How would you say QGC should be used to do that flight ?  - what kind of altitude selection  is needed to do the job ?

**Comment by DonLakeFlyer** [comment]
MAV_FRAME is the 3rd column. 10 = MAV_FRAME_GLOBAL_TERRAIN_ALT. QGC cannot currently create/write these missions (unless you go into Show all values mode). For reading it should have reverted the items to "Show all values" mode since MAV_FRAME_GLOBAL_TERRAIN_ALT cannot be represented in the simple editor. That is a bug. I'll fix that.

**Comment by DonLakeFlyer** [comment]
I also need to find some way to distinguish this QGC feature from MAV_FRAME_GLOBAL_TERRAIN_ALT usage somehow to remove confusion.

**Comment by AndKe** [comment]
is there a way to do this mission using QGC now ? (draw it in QGC then upload, fly , w/o elevation data ?)

**Comment by DonLakeFlyer** [comment]
In reality the answer is no. You could use show all values, but that is a nightmare.

**Comment by AndKe** [comment]
thanks, please keep that in mind and think of a solution. :)

**Comment by AndKe** [comment]
btw: just now, while testing things, I got:

```
Fetch tile error: "Error transferring https://api.airmap.com/elevation/v1/ele/carpet?points=69.77,19.54,69.78,19.55 - server replied: Not Found"
Done

```

this time on a perfect fiber connection, - four time, for that coordinate.

**Comment by AndKe** [comment]
QGC should have another, clearly different name for the "Above terrain" coordinate frame.

this is the current state of GCS's names for different altitude types:
![screenshot from 2018-04-25 13-09-55](https://user-images.githubusercontent.com/1468842/39242335-ff7830dc-4889-11e8-93a9-d009b75ff023.png)


1:
I suggest QGC change AMSL to ABS . AMSL would imply that we do geoid correction for altitude, which we do not - so GPS altitude, remain an ellipsoid with old WGS84 correction, that can be very far from real AMSL.

2: AP2 and mission planner is referring to  MAV_FRAME_GLOBAL_TERRAIN_ALT as "TER or "Terrain" 
mission planner is an unholy mess anyway, as it for some reason assumes all mission items are in only one, and the same coordinate frame.

Still - QGC should most likely fix "Terrain" to be MAV_FRAME_GLOBAL_TERRAIN_ALT , and make it's internal "above terrain" be named something like "GCS calculated above terrain model"  - or otherwise communicate that it's really a absolute altitude + elevation model data processed before upload.

**Comment by DonLakeFlyer** [comment]
> Fetch tile error: "Error transferring https://api.airmap.com/elevation/v1/ele/carpet?points=69.77,19.54,69.78,19.55 - server replied: Not Found"
> Done

AirMap seems to have holes in there data. They recently fixed the other one you reported. Looks like another. I'll test and report it.

**Comment by DonLakeFlyer** [comment]
Also @AndKe Thanks a ton for all the research/info you've posted. Helps a ton to set me in the right direction.

**Comment by DonLakeFlyer** [comment]
All done, except for warning is using terrain frame, which is covered in another issue
