### ISSUE TITLE
Detected Radio version - popup inconsistency 

### ISSUE THREAD

**Issue by ryanjAA** [mavlink/qgroundcontrol#6345]
Im replaying some telem logs from a flight last week on PX4 1.73 stable and yesterdays QGC daily. Flight was with a foam plane and some generic SIK telem radios and the log replay is telling me via QGC popup that the “Detected Radio still using mavlink 1.0 on a link with Mavlink 2.0 enabled. Please upgrade the the radio firmware.” It didn't tell me that at the time, only during replay. Haven't changed anything so wondering if this is an actual error or if should be more prevalent during use.

[2018-03-27 16-59-02.tlog.zip](https://github.com/mavlink/qgroundcontrol/files/1908299/2018-03-27.16-59-02.tlog.zip)

<img width="735" alt="screen shot 2018-04-13 at 12 02 39 pm" src="https://user-images.githubusercontent.com/31726584/38748389-83a583f8-3f13-11e8-8cf3-54832e491b2d.png">

**Comment by DonLakeFlyer** [comment]
Have you upgraded the firmware on the radios? Only newer readio firmware supports mavlink 2.

**Comment by ryanjAA** [comment]
50/50 on the actual version. I’ll have to track back to the specific radios that were used but besides the version aspect of it. What is the concern is that I only saw this during the flight replay and not during the actual flight.

**Comment by DonLakeFlyer** [comment]
Were you using the same version of QGC for both? That check is new.

**Comment by edsellar** [comment]
That makes sense now. Let's close this. I was using 3.3.0 stable to fly and was replaying this with v331 and daily from when i posted this.

**Comment by edsellar** [comment]
That makes sense now. Let's close this. I was using 3.3.0 stable to fly and was replaying this with v331 and daily from when i posted this.

**Comment by DonLakeFlyer** [comment]
Yup. I think that's it. Which would indicate you radio firmware is old. You should re-flash them,.

**Comment by ryanjAA** [comment]
Thanks Ed - exactly.

**Comment by ryanjAA** [comment]
Yep - will get them re-flashed.
