### ISSUE TITLE
recent QGC dailies, UDP connection list not always shown

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6356]
in recent QGC dailies (Windows 10), the connection list doesn't always show properly when adding new UDP connections:

E.g. here is a list of connections:
![image](https://user-images.githubusercontent.com/12117027/38781137-a6bba0e0-40a6-11e8-9553-2a6cdcdb83fd.png)

but when i leave this screen, and then come back to "edit" it again, the list is not displayed anymore:
![image](https://user-images.githubusercontent.com/12117027/38781148-c3ed86ce-40a6-11e8-8cbc-8849e908abf2.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you look at this? Also would be good to remove to WIP.
