### ISSUE TITLE
QGC could not save downloaded file to tmp

### ISSUE THREAD

**Issue by FaboNo** [mavlink/qgroundcontrol#6357]
When posting bug reports, include the following informaiton:
- Ground station operating system ubuntu 16.04
- QGroundControl version V3.2.7
- Autopilot board: Pixhawk 
- Autopilot firmware px4fmu-v4_default.px4
- When I want to update the firmware I got the following error "could not save file on /tmp" (see screenshot below). It is the first time it happens. Actually last friday, I tried to update the firmware but the pixracer was stuck (boatloader issue?) So today I connect with Mission Planner in order to reset the pixracer, but APM was installed per default. And then when I connected with QGC, I got this error.
If somebody can give me a hint? Thank you very much 
Fabrice

![qgroundcontrol px4fmu-v4_default px4](https://user-images.githubusercontent.com/31440972/38801726-f0b867ae-416a-11e8-9813-0d9c218c7a7e.png)

**Comment by DonLakeFlyer** [comment]
Can you translate "est un dossier"?

**Comment by DonLakeFlyer** [comment]
Also just seeing now you are running 3.2.7. You need to running a newer build Stable or Daily. I believe the loactions to ArduPilot firmware has changed since then. Reopen if new build doesn't work for you.
