### ISSUE TITLE
Mistype of the description for the parameter VT_FW_ALT_ERR

### ISSUE THREAD

**Issue by bigbellmercy** [mavlink/qgroundcontrol#6362]
In QGroundControl v3.3.1,
the description for the parameter VT_FW_ALT_ERR,
it'd rather to be changed from 'copared' to 'compared'. Thanks!

**Comment by DonLakeFlyer** [comment]
This comes from the firmware. Can you add an issue there for this?

**Comment by bigbellmercy** [comment]
Okay~
