### ISSUE TITLE
Radio channels 1-4 dead after connecting to QGC under Linux

### ISSUE THREAD

**Issue by mkunzBGC** [mavlink/qgroundcontrol#6370]
With the following system
- Ground station operating system: Ubuntu 16.04.1, kernel 4.13.0-38-generic
- QGroundControl 3.3.2 downloaded from [here](https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGroundControl.tar.bz2)
- Autopilot board: Pixhawk 2 The Cube
- Autopilot firmware: ArduPilot:Copter 3.5.5
- RC transmitter: FrSky Taranis running OpenTx 2.2.1, XJT module runs  XJT_EU_V20_build170317.hex.frk
- RC receiver: X8R running X8R_EU_build1702102.frk
- _Edit: RC receiver and transmitter are bound in D16 mode, channels 1 - 8 are transmitted._

starting QGC seems to disturb the autopilot such that the RC channels 1 through 4 are no longer received.

**This is how I can reliably reproduce the problem:**
1. Turn on transmitter and Pixhawk, wait until startup complete
2. Try to arm (throttle min, yaw right for 2 s) -> buzzer indicates that arming is not possible (no GPS because I am in the basement). This tells me that RC channels 3 (throttle) and 4 (yaw) are being received correctly by the autopilot.
3. Start QGC via USB cable, wait until parameters have been received
4. Under Radio Setup - Channel Monitor, channels 1 through 4 do not react on stick inputs (1 and 4 are centered, 2 and 3 are constantly at minimum). HOWEVER, channels 5 and 6 still work correctly!
5. When trying to arm now, the buzzer stays quiet and there is no message on the QGC screen.
6. Close QGC, confirm vehicle disconnect in the window that's popping up.
7. When trying to arm now, the buzzer is still quiet.

I have to restart the autopilot to make it respond to the arming attempt again.

**This problem also occurs when...**
- using telemetry radios instead of an USB cable between ground station and autopilot _or_
- running ArduPilot:Copter 3.6-dev _or_
- running QGroundControl 3.3.0

**This problem does not occur when...**
- running QGroundControl 3.3.2 on Windows 10 in a virtual box on the very same laptop _or_
- running Mission Planner 1.3.52 under Ubuntu on the very same laptop using Mono _or_
- running ArduPilot:Copter 3.4.6 (but this has other problems in the interplay with QGC, e.g. missing parameters)

At the moment I fly using QGC on the virtual Win10 machine, but would very much prefer do use the GNU/Linux version. I am happy to provide more input in order to resolve this issue.

**Comment by DonLakeFlyer** [comment]
My guess is that ArduPilot has made some changes to start supporting MAV_CMD_PREFLIGHT_CALIBRATION for radio calibration. When you go into the radio setup this will be sent to the vehicle. QGC has always worked this way. It is supposed to tell the vehicle that stick movements should not do things like arm the vehicle when in this mode. 

Then there is in turn some sort of bug which relates to this in the ArduPIlot firmware implementation of this command which causes it to go haywire.

If you are getting other missing parameters problems with an ArduPilot rev please put in another issue and I'll fix them.

**Comment by DonLakeFlyer** [comment]
> Close QGC, confirm vehicle disconnect in the window that's popping up.

There could be a bug where QGC is not turning of radio cal mode when you exit. Let me check that.

**Comment by DonLakeFlyer** [comment]
I just tried loaded ArduCopter 3.5.5 onto my Iris and ran into the same problem. Channel 1-4 changes are not reported, 5+ are. You can see this using Mavlink Inspector and the RC_CHANNELS message. You don't need to go into Radio setup to see this. You just need to connect and look at RC_CHANNELS in mavlink inspector.

Just to make doubly sure there wasn't something wrong with the receiver/transmitter connection. I tried the same thing with PX4 Pro and it worked fine send all channels correctly in RC_CHANNELS message.

So this is an ArduPilot firmware bug. Not sure what release it started happening in. But somewhere between 3.4.6 and 3.5.5. Can you enter an Issue again ArduCopter and reference the discussion here?

**Comment by DonLakeFlyer** [comment]
Closing this, since nothing QGC can do if it doesn't get correct data from vehicle.

**Comment by mkunzBGC** [comment]
Posted this on the [ArduCopter issue tracker](https://github.com/ArduPilot/ardupilot/issues/8318).

**Comment by mkunzBGC** [comment]
Cause of the problem was to have the joystick enabled in QGC. Unchecking "Virtual joystick" in QGroundControl's "General" settings fixed made radio channels 1-4 behave correctly.

**Comment by DonLakeFlyer** [comment]
Thanks Michael for the hint.  User error :)
