### ISSUE TITLE
Why mobile has no Mavlink Console Page ？

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6375]
<img width="388" alt="f54ec5eb-7874-4f8b-bc7a-cfb9a549ad00" src="https://user-images.githubusercontent.com/17830375/39224733-596a2d7a-487b-11e8-8ec5-49eaff8067c8.png">

Hello,I use qgroundcontrol on iPad, but I haven't found Mavlink Console Page on iPad.Then i check the source code ,it doesn't built MavlinkConsoleController on iPad,Coule anyone tell me why mobile doesn't contains that page. I want to check gps status on that page. Thanks.

**Comment by DonLakeFlyer** [comment]
@NaterGator Can't quite remember the reason for this?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Or is it because Mobile just tosses whole Analyze view?

**Comment by dogmaphobic** [comment]
I don't remember ever touching that code. It seems the entire Analyze view is disabled on mobile. Geotagging doesn't seem it makes sense on mobile. Log Download has dubious benefits on mobile as well. I guess MAVLink console, which was added way later got stuck in a menu that is only present on desktop builds.

**Comment by DonLakeFlyer** [comment]
Yeah I think that's pretty much it.

**Comment by DonLakeFlyer** [comment]
Dup of #6133
