### ISSUE TITLE
Version in filename of daily builds?

### ISSUE THREAD

**Issue by estechnical** [mavlink/qgroundcontrol#6379]
Is it possible that the daily builds output versioned file names instead of everything being called just "QGroundControl.appimage"?

Is there an archive for daily builds, like the tagged releases?

I have now collected many versions of qgroundcontrol daily builds, having the date appended to the filename would help massively when switching versions to check out new features.

Symlinking to eg "latest" for the people right on the bleeding edge is pretty common but being able to point at a specific version for others to try is also helpful.

(corridor scan looks awesome, I will try this out soon!)

**Comment by DonLakeFlyer** [comment]
That would require some sort of special work in travis uploads in order to keep doc links from breaking. Somewhat useful but not worth the effort at the moment given all the other things to work on. For now you'll just have to manage renaming yourself.
