### ISSUE TITLE
*Daily build* - Rel.Abs.AGL. in Waypoint editor lose sync

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6387]
testing Daily build 2018-04-29

three screenshots with the AGL, Abs, Rel radio selectors, notice the altitude preview pane in the lower left.  There is no change between AGL and Abs (should be a very noticable change) and there is a strangely  large change between Abs and Rel. (wrongly).  Seems to depend on which order you click/switch between the different altitude modes.
![image](https://user-images.githubusercontent.com/12117027/39413213-c259464e-4bec-11e8-9a0f-0978ffaffd2a.png)
![image](https://user-images.githubusercontent.com/12117027/39413217-d3da9102-4bec-11e8-90fa-7bbb687fc5cc.png)
![image](https://user-images.githubusercontent.com/12117027/39413221-df83e68e-4bec-11e8-8d1b-d2f370557ec5.png)

**Comment by DonLakeFlyer** [comment]
Ah, I knew I'd miss something. This is all new, like 10 minutes old new! Some signalling is missing somewhere.

**Comment by DonLakeFlyer** [comment]
Fixed
