### ISSUE TITLE
Terrain info doesn’t work with English units 

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6391]
Terrain info doesn’t work and other bugs (upload button no flash) when using English units.   (Got something against the size of the kings shoes?)

**Comment by DonLakeFlyer** [comment]
I think I may have just fixed that here: https://github.com/mavlink/qgroundcontrol/pull/6389. The home altitude was using the wrong units for altitude. Not sure if new daily with that is out yet.

**Comment by DonLakeFlyer** [comment]
Are you talking about the terrain height display at the bottom shows wrong heights for waypoints? Or something else?

**Comment by Antiheavy** [comment]
Shows no height for waypoints in the lower left at all.  and also the Upload Required button disappears without clicking on it to Upload.

**Comment by Antiheavy** [comment]
Works fine with meters. Nothing with feet.

**Comment by DonLakeFlyer** [comment]
Can you try again with latest daily? It's all working for me now. Still can't repro the upload button thing though.

**Comment by Antiheavy** [comment]
Now I'm trying it from a hotel and I can't get any terrain to work at all, regardless of meters or feet units.  I've tried both the hotel Wi-Fi (pretty terrible) and tethered to my phone's LTE (better).   Trying both the daily from a few days ago and today's 2018-04-30 daily.  same results which look like this in the console:
![image](https://user-images.githubusercontent.com/12117027/39458918-ddb12ad4-4cbd-11e8-9ce5-9314d64ed1b8.png)

**Comment by DonLakeFlyer** [comment]
Looks like the whole internet connection is bonkers since map tiles aren't downloading either.

**Comment by Antiheavy** [comment]
working in both feet and meters now with the latest daily.  I'm not sure what is wrong with my internet connection to airmaps on the laptop I am using, very flaky.  tried on another machine and it seems to work correctly.
