### ISSUE TITLE
Android 7: no bluetooth devices

### ISSUE THREAD

**Issue by githubtd01** [mavlink/qgroundcontrol#6400]
Hi,

I'm running lineageOS 14 (Android 7) on my Galaxy S4 mini and I cannot find any bluetooth devices inside the app. Other apps like Tower do work via bluetooth with the same setup. The setup also flawlessly works with an old Android 4 tablet and qgroundcontrol.

THX,
Tobisd

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you still have bluetooth thingies to test this with?

**Comment by githubtd01** [comment]
Anything I can do?

**Comment by githubtd01** [comment]
I use a rc timer bluetooth module
https://drotek.com/shop/en/bluetooth/356-bluetooth-module.html
which is connected to a 3dr 433Mhz telemetry module.

But I cannot discover any bluetooth devices inside the app.

**Comment by dogmaphobic** [comment]
> Do you still have bluetooth thingies to test this with?

Yes, I have the TBS one (Crossfire?)

>But I cannot discover any bluetooth devices from inside the app.

Did you pair the device within Android's BT settings? QGC won't do that for you.

**Comment by githubtd01** [comment]
Yes, I did pair the device and I also didn't have problems to use the device with Tower and another app. QGC does not discover all other paired bluetooth devices too (turning all other devices off did not help).
