### ISSUE TITLE
Issue: Survay Parameter not Loaded from .plan file

### ISSUE THREAD

**Issue by b14ckyy** [mavlink/qgroundcontrol#6421]
QGC Version: 3.3.2 Stable
OS: Windows 10 1803 x64
Autopilot: Pixhawk 2.4.8, Arducopter 3.5.5

Steps to reproduce:
- Plan Mission
- insert survey
- change any survey parameter (spacing, cam trigger and so on)
- add RTL
- save mission as .plan file
- load .plan file
Result: all survey parameters reset to default value
- check .plan file in editor > correct values are stored so it seems they are just ignored on load

Screenshots and .plan file added

[Survey Test.zip](https://github.com/mavlink/qgroundcontrol/files/1976459/Survey.Test.zip)

![screenshot 42](https://user-images.githubusercontent.com/33039058/39661258-d47fde6c-504e-11e8-8d73-92362edaa76f.png)
![screenshot 41](https://user-images.githubusercontent.com/33039058/39661259-d49fece8-504e-11e8-8c5f-701eddee67dd.png)

**Comment by b14ckyy** [comment]
Just also tested with latest Daily Build and there this seems to be fixed. Loaded same .plan file and all fine here. Will test now and if this version does not cause major issues, I will keep this for now till next release.

**Comment by DonLakeFlyer** [comment]
Fixed in Stable 3.3. New code in Daily doesn't have this bug.

Thanks so much for the detailed bug report.
