### ISSUE TITLE
Terrain data download progress bar

### ISSUE THREAD

**Issue by dgorissen** [mavlink/qgroundcontrol#6423]
Migrating from #6404

Give user feedback through a progress bar or similar as to how far along the terrain data download is. An ability to cancel would also be useful.

**Comment by Antiheavy** [comment]
Clear user feedback for if no terrain data is available (eg no internet and no cache) is also important.

**Comment by DonLakeFlyer** [comment]
This: https://github.com/mavlink/qgroundcontrol/pull/6463 shows progress.
