### ISSUE TITLE
Segfault when navigating from logging to flight plan pane

### ISSUE THREAD

**Issue by dgorissen** [mavlink/qgroundcontrol#6424]
Migrated from #6404 

While testing a daily build from a few days ago (1d10b2ad3) I found a fairly reproducible crash:
- Start QGC
- I load the following survey: [surveytest.plan.txt](https://github.com/mavlink/qgroundcontrol/files/1974033/surveytest.plan.txt)
- Go to the console view, scroll around a bit
- Click back on the flight-plan icon
- Segfault

![image](https://user-images.githubusercontent.com/644951/39618893-98508bac-4f7d-11e8-83cb-86e9290d0581.png)

Im on OSX El Capitan. And gad enabled logging for terrain related things (2 items) and set the debug level to 4 (if that matters).

**Comment by DonLakeFlyer** [comment]
Fixed
