### ISSUE TITLE
Rounded survey corners

### ISSUE THREAD

**Issue by dgorissen** [mavlink/qgroundcontrol#6427]
Maybe there is an option for this but I havent found it so far.

When flying surveys with a multirotor the drone goes through a lot of acceleration/decelerations as it tries to follow the corners exactly, pretty much coming to a complete standstill on each turn. 

Especially when flying at a reasonably high speed this reduces battery life. An option to connect the survey lines with semi-circles (or similar) instead of hard corners would be nice.

**Comment by DonLakeFlyer** [comment]
I believe that is a flight dynamic of the firmware implemenation. There isn't really a generic way to get the vehicle to do the semi-circle. ArduPilot has splines but PX4 does not. But still not sure what thay would fly like. The transistions from one waypoint to the next are all handled by the firmware.

What firmware are you flying?

**Comment by dgorissen** [comment]
Mmm thinking about it, you are right. Googling around seems this is the key issue: https://github.com/ArduPilot/ardupilot/issues/6757 and other than fiddling with WPNAV_RADIUS and accel/speed limits looks like there is no direct way to control this.
