### ISSUE TITLE
makefile:197013: recipe for target 'obj/qrc_qgcresources.o' failed

### ISSUE THREAD

**Issue by yzhatsy** [mavlink/qgroundcontrol#6433]
cc1plus: out of memory allocating 327560104 bytes after a total of 47394816 bytes
Makefile:197013: recipe for target 'obj/qrc_qgcresources.o' failed
make: *** [obj/qrc_qgcresources.o] Error 1

**Comment by DonLakeFlyer** [comment]
Something must be wrong with your setup. CI builds on master are working fine. Are you trying to run too man jobs at once (-j)?
