### ISSUE TITLE
Increase the frequency of IMU

### ISSUE THREAD

**Issue by Jdiesel666** [mavlink/qgroundcontrol#6447]
I'm using pixHawk to experiment of visual inertial state estimation. The frequency of the IMU should be a least 200Hz. I'm wondering if different airframe give you different frequency setup during the initial configuration? I've tried a couple but it seems it doesn't do the trick. 
Does anyone know if the frequency issue is not related to the frames or not? My experience tells me no. 
If you can point me a direction to how to bump up the frequency it would be highly appreciated. 

I launch px4 and do "hz  /mavros/imu/data_raw"

**Comment by DonLakeFlyer** [comment]
You should ask this question on the firmware forums.
