### ISSUE TITLE
missing DLL error after installing Daily Build on an old Windows 7 machine

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6466]
I get "api-ms-win-crt-runtime-l1-1-0.dll missing" when trying to install today's daily build on an old window's 7 machine.  Am I expected to have Visual C++ installed on my own.. or how else should this be remedied?

![untitled](https://user-images.githubusercontent.com/12117027/40263221-d7cf9fc2-5ad4-11e8-88fa-1837cbef63ae.jpg)

**Comment by DonLakeFlyer** [comment]
Hmm, strange. You shouldn't need to install anything extra.

**Comment by Antiheavy** [comment]
It looks like this old PC has a number of issues as other software is also not installing properly. Not a QGC thing is seems which is good.

**Comment by DonLakeFlyer** [comment]
Maybe someone uninstalled something they shouldn't have.
