### ISSUE TITLE
Center to specific position

### ISSUE THREAD

**Issue by dgorissen** [mavlink/qgroundcontrol#6485]
When planning a flight mission without connected to a vehicle it would be easier if the "Center" menu also had an option for: input specific lat/lon. This is particularly useful in an offline context where you cant use the map to scroll to the position or find the small patch of offline tiles you downloaded.

This is equally useful when planning a flight over a very featureless environment (e.g, forest), again the visuals of the map do not really help you to get the position right.

The current way around is to drop an arbitrary marker and then edit its position.

**Comment by DonLakeFlyer** [comment]
Hmm, I thought I had added that ages ago.
