### ISSUE TITLE
Weird flight path after editing an imported KML

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#6489]
Changing an imported KML causes some funky paths:

![screenshot-1](https://user-images.githubusercontent.com/749243/40432333-70d727f8-5e77-11e8-8422-4ae714fab73a.png)

![screenshot-2](https://user-images.githubusercontent.com/749243/40432383-9035205a-5e77-11e8-866f-2a9d0aeb6fc3.png)

**Comment by DonLakeFlyer** [comment]
Hmm, I had though that was mostly working better now. Guess not. Can you attach a KML or .plan which fails?

**Comment by thomasgubler** [comment]
[testpolygon.kml.zip](https://github.com/mavlink/qgroundcontrol/files/2034353/testpolygon.kml.zip)

Here is a zip of the kml file. (github does not support uploading kml files apparently)

**Comment by DonLakeFlyer** [comment]
From master:
![screen shot 2018-06-01 at 11 37 04 am](https://user-images.githubusercontent.com/5876851/40857536-4fb45c24-6590-11e8-8cef-3c91427887c1.png)

This is correct. Could be specific to your plan survey settings. Attach a plan file which fails.

**Comment by DonLakeFlyer** [comment]
Plan file?

**Comment by DonLakeFlyer** [comment]
Reopen is you can get master to no work like I've shown above.
