### ISSUE TITLE
Prepare for AC3.6

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#6503]
AC release candidate for 3.6 produces a lot of errors, it may be time to adapt to AC3.6 ..
These errors (the yellow box)  should be logged to console, or somewhere, or be possible to recall later on.

![screenshot from 2018-05-25 15-52-24](https://user-images.githubusercontent.com/1468842/40548221-63015bd0-6034-11e8-90d8-6c260d8aca62.png)
![screenshot from 2018-05-25 15-53-00](https://user-images.githubusercontent.com/1468842/40548222-63274854-6034-11e8-94f6-18e7bc5d34cf.png)
![screenshot from 2018-05-25 15-52-51](https://user-images.githubusercontent.com/1468842/40548240-6e269cfa-6034-11e8-961d-7b88067ef77d.png)

**Comment by DonLakeFlyer** [comment]
Thanks for checking this @AndKe. It's hard for me to keep up with multiple firmwares. There are a bunch of parameter name changes I need to put into the parameter name remapping system.

**Comment by kikislater** [comment]
Concern Rover 3.3 and Plane 3.9 also : https://github.com/ArduPilot/MissionPlanner/issues/1843

**Comment by DonLakeFlyer** [comment]
Coming in another pull

**Comment by DonLakeFlyer** [comment]
I think I finally have this finished up!
