### ISSUE TITLE
REQUEST: Option to always center map on vehicle

### ISSUE THREAD

**Issue by Jmelz** [mavlink/qgroundcontrol#6508]
I installed qgc a few weeks ago, and was flying this past weekend. I am flying a fpv plane with an eagletree vector flight controller. It interfaces with a dragonlink receiver using open telemetry, which gets converted to a minimal mavlink stream. I noticed on the PC, I don't seem to have a moving map... Am I doing something wrong? I can't find a map center option to pan the map as the plane moves...

It seems like this was possible in a previous version...

https://docs.qgroundcontrol.com/en/FlyView/FlyView.html

But with the eagletree vector, I cannot 'arm' , so if this is now a prerequisite, I cannot make this happen...

**Comment by DonLakeFlyer** [comment]
Should happen automatically. What version of QGC on what OS?

**Comment by Jmelz** [comment]
I'll double check the qgc version, but the is is windows 10.

And I remember this working before, however I think it stopped with my last qgc upgrade.

Android seems okay still

**Comment by Jmelz** [comment]
Looks like Android is also not centering. PC is running 3.3.2 on win 10.

**Comment by DonLakeFlyer** [comment]
When you say "centering" do you mean that the vehicle always stays exactly in the middle of the map? If so, that is not the way it works now. The map will only move when the vehicle moves outside the current visible area. Only then will it recenter to the vehicle position.

**Comment by Jmelz** [comment]
Thanks! Yes, that is exactly what I meant. I had not ever let it get out of my sight, because I kept panning the map manually. I like this functionality as you describe it - because for short flights the map isn't panning all over - but I do wish it was an option that could be turned on or off. What is the threshold before it centers on vehicle position? 50 pixels, 100? or literally outside of the visible area?

**Comment by DonLakeFlyer** [comment]
> I like this functionality as you describe it - because for short flights the map isn't panning all over

In general users like it working this way much better. It centers when it goes outside the visible area. Option is interesting, but would rather not add yet another option.

**Comment by Jmelz** [comment]
Understood - I'll center my map on my 'in close' flying area, and that should do well for me.

As a side note, if declutter is the goal (which I agree with), perhaps an auto connect to a plane/copter on app opening? Maybe if there is only 1 craft? Would save a little time :)

**Comment by DonLakeFlyer** [comment]
> perhaps an auto connect to a plane/copter on app opening?

YOu can set your link to autoconnect and it should work.

**Comment by Jmelz** [comment]
Ah -  might be a bridge too far for me... I don't have a pixhawk, sik radio, px4 flow, librepilot, udp or rtk gps device.

My dragonlink shows up as a serial bluetooth link.

**Comment by Jmelz** [comment]
Hrm, after using for a few flights, I still would like the option to constantly center on vehicle...

If a plane goes down, it is tough to see where it went down if it is at the edge of the screen. I think this should be an option in the menu, personally.

**Comment by DonLakeFlyer** [comment]
Using the Center tool on the right you can center the map on the vehicle.

**Comment by Jmelz** [comment]
Thanks Don - I am unfamiliar with that tool... but this would be a '1 time' center- not tracking the vehicle in the center I would assume... I am hoping to track vehicle in center via an option.

**Comment by DonLakeFlyer** [comment]
One time center. I try not to add too many options to QGC since it just confuses users. So far I haven't gotten any other requests for going back to an option to always center. Hence I'd rather not add yet another thing to settings.

**Comment by Jmelz** [comment]
Sure, understood - There is a community of FPV pilots using dragonlink as a radio system, who, until recently, were advised to use tower. 

I think QGC is better, due to offline maps, and many other features. This is an option that we've talked about in our community, so I'm just relaying information that not only I'd like to see, but some others would as well.

I understand your reluctance to add another option, but this is something I think has value for us that fly long distance missions. If a plane goes down, it's good to see the surrounding area at all times to help in locating it.

I changed my title to a request, just in case you change your mind.

**Comment by Jmelz** [comment]
Flew again yesterday, and noticed that when the plane flies to the edges of the screen, there are periods of time that it is invisible because it is behind the widgets on the right, and the "takeoff/land/pause/play" controls on the left (remembering that I'm not arming the eagletree vector, as it's not possible).

I also don't see any way to click a button to center the display on PC or Android :(

**Comment by DonLakeFlyer** [comment]
Recenter is fixed now. Sorry I was thinking wrong. There isn't a re-center button on the Fly View.

**Comment by Jmelz** [comment]
Thanks Don... What does this mean exactly?

**Comment by DonLakeFlyer** [comment]
It means the vehicle won't go under the tools on the left/right.

**Comment by DonLakeFlyer** [comment]
Correct

**Comment by Jmelz** [comment]
Thanks, I will try to grab daily build to test today.

**Comment by Jmelz** [comment]
I guess since I didn't join the qgroundcontrol game until recently, I was unaware of the documentation:

https://docs.qgroundcontrol.com/en/FlyView/FlyView.html

`Fly Tools
On the left edge of the screen you will see the Fly Tools. The order of tools from top to bottom is:
Center map
Map Type
Zoom In/Out
Center Map
The Center Map tool allow you to center the map around various points such as home position, vehicle and so forth.
`

Kinda matches up with what I was thinking - "center map around vehicle... and so forth"

**Comment by DonLakeFlyer** [comment]
Those docs are pretty out date with respect to where things are now. But should still be somewhat helpful.

**Comment by Jmelz** [comment]
So for me, that tool doesn't appear (to center map)… but is it gone for good? or does it only show when vehicle is armed? In tower, you have a similar tool... you single press to center "for now" and press and hold to 'follow' vehicle. I was thinking that this was how it used to be for qgroundcontrol based on what you've said...

**Comment by DonLakeFlyer** [comment]
It's been gone for a while. With the new automatic re-centering it isn't needed since the vehicle is always in view.

**Comment by DonLakeFlyer** [comment]
Also should have thought about this a while ago. But if you want the vehicle to be forced to recenter you can just pan the map such that the vehicle is no longer in view. Wait a few seconds, and it will automatically pop back to the center.

**Comment by Jmelz** [comment]
Sure, but it still won't stay centered...

This is what made me create this past

**Comment by Jmelz** [comment]
So does this mean it's being planned for next minor version now?
