### ISSUE TITLE
Opening mission plan files fails

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#6519]
I cannot open mission plan files with latest master (f1e2638cad24b07b1b). It fails with:
```
qrc:qml/PlanView.qml:826: ReferenceError: masterController is not defined
```

This is on Desktop Linux.

**Comment by DonLakeFlyer** [comment]
Did you build yourself with something other than Qt 5.9.4? Qt 5.10 does not work with QGC.

**Comment by bkueng** [comment]
Ah ok. Yes I'm using 5.10.1. I assume it works with 5.9.4 then, so I'm closing this.

**Comment by DonLakeFlyer** [comment]
I you want to use a newer Qt we are working towards moving to Qt 5.11 which at this point seems to work.
