### ISSUE TITLE
Cannot run UDP link on build

### ISSUE THREAD

**Issue by kane111** [mavlink/qgroundcontrol#6520]
Build: Master
OS: Windows 8.1

I am unable to run UDP streams on the latest builds. The problem occurs when I compile the build myself, while the UDP works on the precompiled builds available on the QGC website. I have both Bonjour and Bonjour SDK installed on my computer. Please Guide me through.

**Comment by dogmaphobic** [comment]
Are you using Qt < 5.9.4? UDP is broken on Windows and was only fixed in Qt 5.9.4.

**Comment by kane111** [comment]
@dogmaphobic thank you so much, I was using QT5.9.3, upgraded to 5.9.4, and it works!

**Comment by dogmaphobic** [comment]
I thought that was the case :P
