### ISSUE TITLE
Scan with terrain data: "Waiting on Terrain Data from Server"

### ISSUE THREAD

**Issue by hitimo** [mavlink/qgroundcontrol#6534]
I'm trying to export a scan pattern with terrain data, but I cannot save the plan or KML. Error message: "Unable to Save/Upload. Plan is waiting on terrain data from server for correct altitude values". Nothing seems to be downloaded though. Can I force the download somehow? It does work for areas nearby. Thanks!
![qgc](https://user-images.githubusercontent.com/5558652/40771833-b1ca03be-64be-11e8-8181-aee898584748.png)

**Comment by DonLakeFlyer** [comment]
If terrain data is working in other areas. My guess woule be that this area is missing data. If you can give me the lat/lon of a rect which covers the area I can ask the terrain folks if they have data there.

**Comment by hitimo** [comment]
Thanks @DonLakeFlyer for your reply. The corners of the scan area are (UTM):
```
570688, 5174392
570045, 5174028
570854, 5172812
571306, 5173381
```

**Comment by DonLakeFlyer** [comment]
Can you do this? Turn off Terrain and then save the Plan. Rename to .plan.txt and attach here.

**Comment by hitimo** [comment]
Hi @DonLakeFlyer I attached the plan to my last post.

**Comment by DonLakeFlyer** [comment]
@birchera Can you take a look at this? It fails to complete the TerrainPolyPathQuery send by Survey. It should be 48 segments, but after the 5th or so it needs to request a tile and then it never responds from that.

**Comment by hitimo** [comment]
>  It should be 48 segments, but after the 5th or so it needs to request a tile and then it never responds from that.

@DonLakeFlyer @birchera Any ideas what could be the reason for that and how I could fix it? Thanks

**Comment by birchera** [comment]
@DonLakeFlyer you added some more logging (https://github.com/mavlink/qgroundcontrol/pull/6542) did that reveal anything?

**Comment by DonLakeFlyer** [comment]
Nope. That just told me that the PolyPathQuery never completes.

**Comment by DonLakeFlyer** [comment]
@birchera Also if I change TerrainPathQuery to use TerringAirMapQuery instead of the offline system it works.

**Comment by hitimo** [comment]
@DonLakeFlyer Could you please push the changes that made it work for you in a temp. branch? Thanks!

**Comment by DonLakeFlyer** [comment]
Those changes are just for testing. QGC now always runs against the offline cache.

**Comment by DonLakeFlyer** [comment]
Should be fixed now
