### ISSUE TITLE
QGC incompatible with Android 8.1.0 on Pixel C

### ISSUE THREAD

**Issue by bradwilkinson** [mavlink/qgroundcontrol#6549]
OS: Android 8.1.0
Device: Google Pixel C tablet
QGC version: stable, latest on Google Play Store, June 2, 2018
Autopilot: n/a - couldn't get QGC

I tried to install the QGC app for Android from the Google Play Store, but there was a message: "Your device isn't compatible with this version." The Pixel C is always updated with the latest Android system, but the device itself is a couple of years old. The QGC app works great on my new Pixel 2 phone.

Here is a shot of the tablet's info:
![screenshot_20180603-085900](https://user-images.githubusercontent.com/35172993/40886808-a1d4c2fa-670c-11e8-9b5f-75b5ebb040a9.png)

**Comment by bradwilkinson** [comment]
After posting this, I think I have answered my own question and figured out the issue - the PixelC doesn't have a GPS receiver! I run Bluetooth GPS, getting the output from my phone, and this works great for geology ion with mapping in the field. But it isn't native GPS on the tablet. Interestingly, the Tower app installs and functions normally using WiFi location, and the Bluetooth GPS.

**Comment by DonLakeFlyer** [comment]
The app manifest doesn't regiter itself correctly for supporting devices with no GPS. I'll fix that.

**Comment by DonLakeFlyer** [comment]
Can you try a latest daily build. Should not say it is not compatible any more.

**Comment by bradwilkinson** [comment]
@DonLakeFlyer , I just tried the daily build on Google Play at 18:00EDT. It still says not compatible. The date there is April 7, 2017. Is there a different way or location for the daily build?

**Comment by DonLakeFlyer** [comment]
Install from here: https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrolbeta. That said, the daily builds seem to be trailing behind by a few days so soemthing is wrong.

**Comment by DonLakeFlyer** [comment]
You can also get latest android daily build from here: https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.apk

**Comment by bradwilkinson** [comment]
Yes, that's what I tried before, same answer.

**Comment by bradwilkinson** [comment]
Second link worked great! Installed with no issues. That's wonderful, thanks for your help with this!!

**Comment by DonLakeFlyer** [comment]
Good news. We're fixing up the store stuff soon. So you should be able to go back to install from there hopefully in a couple days and then you'll get updates.
