### ISSUE TITLE
v3.4.0 Changelog scratchpad

### ISSUE THREAD

**Issue by mrpollo** [mavlink/qgroundcontrol#6556]
Hey @dogmaphobic, as discussed in the Dronecode Platform & Strategy weekly meeting, here's the automated changelog for the upcoming release, please review it and let me know if this output makes sense to you, you can see an example here https://github.com/PX4/Firmware/releases/tag/v1.7.0

---
# Change Log

## [v3.4.0](https://github.com/mavlink/qgroundcontrol/tree/v3.4.0) (2018-06-04)

[Full Changelog](https://github.com/mavlink/qgroundcontrol/compare/v3.3.2...v3.4.0)

**Fixed bugs:**

- Boot QGC on Stable 3.3 branch gives UDP port error [\#6393](https://github.com/mavlink/qgroundcontrol/issues/6393)
- Terrain info doesn’t work with English units  [\#6391](https://github.com/mavlink/qgroundcontrol/issues/6391)
- Radio channels 1-4 dead after connecting to QGC under Linux [\#6370](https://github.com/mavlink/qgroundcontrol/issues/6370)
- Latest daily doesnt connect to SITL [\#6363](https://github.com/mavlink/qgroundcontrol/issues/6363)
- Terrain: Dragging WP which is using terrain alt doesn't update actual AMSL alt value [\#6344](https://github.com/mavlink/qgroundcontrol/issues/6344)
- Terrain: Download single items back from vehicle doesn't show terrain correctly [\#6244](https://github.com/mavlink/qgroundcontrol/issues/6244)
- menu icon not shown correctly [\#6230](https://github.com/mavlink/qgroundcontrol/issues/6230)
- QGC 3.3: GeoTagging does not work. [\#6171](https://github.com/mavlink/qgroundcontrol/issues/6171)

**Closed issues:**

- Is QGC already switching to Qt 5.11? [\#6554](https://github.com/mavlink/qgroundcontrol/issues/6554)
- UVC Device not working in android app [\#6541](https://github.com/mavlink/qgroundcontrol/issues/6541)
- New french regulations imacting ground stations [\#6535](https://github.com/mavlink/qgroundcontrol/issues/6535)
- Cannot run UDP link on build [\#6520](https://github.com/mavlink/qgroundcontrol/issues/6520)
- Opening mission plan files fails [\#6519](https://github.com/mavlink/qgroundcontrol/issues/6519)
- REQUEST: Option to always center map on vehicle [\#6508](https://github.com/mavlink/qgroundcontrol/issues/6508)
- First or last flight path within a survey [\#6492](https://github.com/mavlink/qgroundcontrol/issues/6492)
- ROI Waypoint causes wrong mission distance [\#6477](https://github.com/mavlink/qgroundcontrol/issues/6477)
- Something Wrong with Multiple Joysticks Like Logitech X56  [\#6476](https://github.com/mavlink/qgroundcontrol/issues/6476)
- missing DLL error after installing Daily Build on an old Windows 7 machine [\#6466](https://github.com/mavlink/qgroundcontrol/issues/6466)
- Battery Parameters Visualisation not working in  simulation [\#6460](https://github.com/mavlink/qgroundcontrol/issues/6460)
- UI: malfunction button [\#6454](https://github.com/mavlink/qgroundcontrol/issues/6454)
- RTK GPS rover gps sat count 0 [\#6450](https://github.com/mavlink/qgroundcontrol/issues/6450)
- change to "wp altitude" does not affect displayed waypoints [\#6449](https://github.com/mavlink/qgroundcontrol/issues/6449)
- Increase the frequency of IMU [\#6447](https://github.com/mavlink/qgroundcontrol/issues/6447)
- It is unclear how "start mission" is supposed to work. [\#6446](https://github.com/mavlink/qgroundcontrol/issues/6446)
- Survey: Custom builds can no longer default to specific camera [\#6440](https://github.com/mavlink/qgroundcontrol/issues/6440)
- GeoFence: Not being save in Plan files [\#6439](https://github.com/mavlink/qgroundcontrol/issues/6439)
- Plan View \> Mission Start \> Waypoint alt does not reset altitudes [\#6437](https://github.com/mavlink/qgroundcontrol/issues/6437)
- Feature Request Custom Widget to read MAVLink Messages [\#6434](https://github.com/mavlink/qgroundcontrol/issues/6434)
- makefile:197013: recipe for target 'obj/qrc\_qgcresources.o' failed [\#6433](https://github.com/mavlink/qgroundcontrol/issues/6433)
- NAV\_RCL\_LT option missing from Safety view [\#6428](https://github.com/mavlink/qgroundcontrol/issues/6428)
- Rounded survey corners [\#6427](https://github.com/mavlink/qgroundcontrol/issues/6427)
- Segfault when navigating from logging to flight plan pane [\#6424](https://github.com/mavlink/qgroundcontrol/issues/6424)
- Terrain data download progress bar [\#6423](https://github.com/mavlink/qgroundcontrol/issues/6423)
- Querying large number of terrain values [\#6422](https://github.com/mavlink/qgroundcontrol/issues/6422)
- Issue: Survay Parameter not Loaded from .plan file [\#6421](https://github.com/mavlink/qgroundcontrol/issues/6421)
- QGroundControl not reacting to heartbeat message [\#6413](https://github.com/mavlink/qgroundcontrol/issues/6413)
- \*Daily build\* - Rel.Abs.AGL. in Waypoint editor lose sync [\#6387](https://github.com/mavlink/qgroundcontrol/issues/6387)
- VT\_FW\_MIN\_ALT units do not follow preference [\#6384](https://github.com/mavlink/qgroundcontrol/issues/6384)
- Version in filename of daily builds? [\#6379](https://github.com/mavlink/qgroundcontrol/issues/6379)
- How QBluetoothSocket works in QGC [\#6373](https://github.com/mavlink/qgroundcontrol/issues/6373)
- Planned Home Position command incorrectly showing up as selectable [\#6371](https://github.com/mavlink/qgroundcontrol/issues/6371)
- Mistype of the description for the parameter VT\_FW\_ALT\_ERR [\#6362](https://github.com/mavlink/qgroundcontrol/issues/6362)
- QGC could not save downloaded file to tmp [\#6357](https://github.com/mavlink/qgroundcontrol/issues/6357)
- Offline Terrain: Crashing on Windows [\#6352](https://github.com/mavlink/qgroundcontrol/issues/6352)
- Android; layout deny features [\#6347](https://github.com/mavlink/qgroundcontrol/issues/6347)
- Detected Radio version - popup inconsistency  [\#6345](https://github.com/mavlink/qgroundcontrol/issues/6345)
- \[Improvement\] Calibration result texts of airspeed sensor disappear abruptly when finishing [\#6333](https://github.com/mavlink/qgroundcontrol/issues/6333)
- QGC Failure to download params with RFD900 radios [\#6330](https://github.com/mavlink/qgroundcontrol/issues/6330)
- Support PING protocol [\#6329](https://github.com/mavlink/qgroundcontrol/issues/6329)
- QGC daily build 04/05/2018 unable to display full user interface [\#6318](https://github.com/mavlink/qgroundcontrol/issues/6318)
- Repeating "not enough bandwidth for log streaming" messages [\#6289](https://github.com/mavlink/qgroundcontrol/issues/6289)
- Resume Mission Not Working Fixed Wing [\#6286](https://github.com/mavlink/qgroundcontrol/issues/6286)
- "Upload Required" button flashes once then reverts to plain old "Upload" button.  Sync button does not flash. [\#6256](https://github.com/mavlink/qgroundcontrol/issues/6256)
- terrain information not downloading [\#6255](https://github.com/mavlink/qgroundcontrol/issues/6255)
- Needing Translations for this platform? [\#6161](https://github.com/mavlink/qgroundcontrol/issues/6161)
- QGC doesn't play well with other Follow Me sources \(DroneCore\) [\#6141](https://github.com/mavlink/qgroundcontrol/issues/6141)
- Mavlink Shell support for Mobile [\#6133](https://github.com/mavlink/qgroundcontrol/issues/6133)
- Request: improved Safety summary pane [\#6062](https://github.com/mavlink/qgroundcontrol/issues/6062)

**Merged pull requests:**

- Even more PreFlight reorg/support [\#6555](https://github.com/mavlink/qgroundcontrol/pull/6555) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Android: Allow devices without gps [\#6552](https://github.com/mavlink/qgroundcontrol/pull/6552) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Travis: Fix parse problems [\#6551](https://github.com/mavlink/qgroundcontrol/pull/6551) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- More PreFlight control reorganization [\#6550](https://github.com/mavlink/qgroundcontrol/pull/6550) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Add missing libraries to Linux build [\#6547](https://github.com/mavlink/qgroundcontrol/pull/6547) ([dogmaphobic](https://github.com/dogmaphobic))
- Remove QtMultimedia import when not needed [\#6546](https://github.com/mavlink/qgroundcontrol/pull/6546) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Support for simple MissionStart item [\#6543](https://github.com/mavlink/qgroundcontrol/pull/6543) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Add more logging [\#6542](https://github.com/mavlink/qgroundcontrol/pull/6542) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Support for Sync - Load KML [\#6539](https://github.com/mavlink/qgroundcontrol/pull/6539) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fix ArduCopter Start Mission support [\#6538](https://github.com/mavlink/qgroundcontrol/pull/6538) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Put back support for ATTITUDE since ArduPilot needs it [\#6537](https://github.com/mavlink/qgroundcontrol/pull/6537) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Vagrant: use Qt5.11.0 deps [\#6536](https://github.com/mavlink/qgroundcontrol/pull/6536) ([peterbarker](https://github.com/peterbarker))
- Remove unused \(and non-existing\) library [\#6533](https://github.com/mavlink/qgroundcontrol/pull/6533) ([dogmaphobic](https://github.com/dogmaphobic))
- jenkins: agent fix [\#6532](https://github.com/mavlink/qgroundcontrol/pull/6532) ([lamping7](https://github.com/lamping7))
- cameraMinTriggerInterval now comes from CameraCalc [\#6531](https://github.com/mavlink/qgroundcontrol/pull/6531) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Use a menu to delete a vertex [\#6530](https://github.com/mavlink/qgroundcontrol/pull/6530) ([dogmaphobic](https://github.com/dogmaphobic))
- Move Linux/Android to Qt 5.11.0 [\#6529](https://github.com/mavlink/qgroundcontrol/pull/6529) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Remove usage of ATTITUDE in favor of ATTITUDE\_QUATERNION [\#6528](https://github.com/mavlink/qgroundcontrol/pull/6528) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Switch OSX build to Qt 5.11.0 [\#6527](https://github.com/mavlink/qgroundcontrol/pull/6527) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- UnitsSettings: Use \_settingsGroup for SettingsFact creation [\#6526](https://github.com/mavlink/qgroundcontrol/pull/6526) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Firmware Upgrade: Make default firmware more prominent [\#6525](https://github.com/mavlink/qgroundcontrol/pull/6525) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fixed Wing Landing Pattern: Relative alt checkbox override [\#6524](https://github.com/mavlink/qgroundcontrol/pull/6524) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Clean up SettingsGroup name and settingsGroup [\#6523](https://github.com/mavlink/qgroundcontrol/pull/6523) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Survey: Allow VTOL vehicles to fly alternat transects [\#6522](https://github.com/mavlink/qgroundcontrol/pull/6522) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Add settingsGroup qualifer to settings override [\#6521](https://github.com/mavlink/qgroundcontrol/pull/6521) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Update ArduPilot flow URL [\#6517](https://github.com/mavlink/qgroundcontrol/pull/6517) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Camera/Transects unit tests and fixes [\#6516](https://github.com/mavlink/qgroundcontrol/pull/6516) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- PX4 Optical Flow fixes [\#6514](https://github.com/mavlink/qgroundcontrol/pull/6514) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Transect alt mode fixes [\#6513](https://github.com/mavlink/qgroundcontrol/pull/6513) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- ArduCopter 3.6 tuning page fixes [\#6512](https://github.com/mavlink/qgroundcontrol/pull/6512) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Mavlink Console Improvements [\#6511](https://github.com/mavlink/qgroundcontrol/pull/6511) ([bkueng](https://github.com/bkueng))
- Sensor Cal: Handle case where no mag present \[continued\] [\#6510](https://github.com/mavlink/qgroundcontrol/pull/6510) ([bkueng](https://github.com/bkueng))
- Adjust to new parameters in Copter 3.6 [\#6507](https://github.com/mavlink/qgroundcontrol/pull/6507) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Cleanup layout issues throughout QGC [\#6506](https://github.com/mavlink/qgroundcontrol/pull/6506) ([dogmaphobic](https://github.com/dogmaphobic))
- Simplify PreFlightCheckButton implementation [\#6504](https://github.com/mavlink/qgroundcontrol/pull/6504) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- PreFlight: Style cleanup and changes [\#6501](https://github.com/mavlink/qgroundcontrol/pull/6501) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Create standalone controls for PreFlight CheckList [\#6500](https://github.com/mavlink/qgroundcontrol/pull/6500) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- CameraCalc: Image Density -\> Ground Res [\#6499](https://github.com/mavlink/qgroundcontrol/pull/6499) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- PreFlight Check List: Control renaming [\#6498](https://github.com/mavlink/qgroundcontrol/pull/6498) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Survey: Support for flying alternate transects \(fixed wing only\) [\#6497](https://github.com/mavlink/qgroundcontrol/pull/6497) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Pre-Flight Checklist: Coding style cleanup [\#6496](https://github.com/mavlink/qgroundcontrol/pull/6496) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Plan: Large progress bar in Outdoor theme [\#6495](https://github.com/mavlink/qgroundcontrol/pull/6495) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Better help for alt mode [\#6494](https://github.com/mavlink/qgroundcontrol/pull/6494) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Update mavlink v2.0 submodule Tue May 22 20:47:41 EDT 2018 [\#6487](https://github.com/mavlink/qgroundcontrol/pull/6487) ([dagar](https://github.com/dagar))
- Update PX4 Firmware metadata Wed May 23 00:37:06 EDT 2018 [\#6486](https://github.com/mavlink/qgroundcontrol/pull/6486) ([dagar](https://github.com/dagar))
- Generic PID tuning support [\#6483](https://github.com/mavlink/qgroundcontrol/pull/6483) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Allow custom build to hide Absolute Altitude in mission planning [\#6482](https://github.com/mavlink/qgroundcontrol/pull/6482) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- CameraCalc: Add missing update triggers [\#6481](https://github.com/mavlink/qgroundcontrol/pull/6481) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fixed Wing Landing Pattern: Visualize landing area [\#6479](https://github.com/mavlink/qgroundcontrol/pull/6479) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fix standalone coords affecting time/distance [\#6478](https://github.com/mavlink/qgroundcontrol/pull/6478) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Update camera specs on creation [\#6475](https://github.com/mavlink/qgroundcontrol/pull/6475) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Battery2 work: Support in FactGroups and ArduPilot Power page [\#6474](https://github.com/mavlink/qgroundcontrol/pull/6474) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Use FW Landing visuals in Fly View [\#6473](https://github.com/mavlink/qgroundcontrol/pull/6473) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fix action list showing empty [\#6472](https://github.com/mavlink/qgroundcontrol/pull/6472) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Survey: Rotate survey entry [\#6469](https://github.com/mavlink/qgroundcontrol/pull/6469) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Don't go into Hold before takeoff [\#6468](https://github.com/mavlink/qgroundcontrol/pull/6468) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Save fact settings for new Transect code [\#6464](https://github.com/mavlink/qgroundcontrol/pull/6464) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Show indicator for mission terrain data [\#6463](https://github.com/mavlink/qgroundcontrol/pull/6463) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Allow DropPanel dynamic sizing [\#6462](https://github.com/mavlink/qgroundcontrol/pull/6462) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Single bool to debug guided actions [\#6461](https://github.com/mavlink/qgroundcontrol/pull/6461) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Appveyor only has Qt 5.9.5 [\#6458](https://github.com/mavlink/qgroundcontrol/pull/6458) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- FactValueSlider: Fix crash when empty [\#6456](https://github.com/mavlink/qgroundcontrol/pull/6456) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- minor typo fix [\#6453](https://github.com/mavlink/qgroundcontrol/pull/6453) ([barzanisar](https://github.com/barzanisar))
- Update mavlink v2.0 submodule Thu May 10 20:39:36 EDT 2018 [\#6444](https://github.com/mavlink/qgroundcontrol/pull/6444) ([dagar](https://github.com/dagar))
- Update PX4 Firmware metadata Fri May 11 00:37:05 EDT 2018 [\#6443](https://github.com/mavlink/qgroundcontrol/pull/6443) ([dagar](https://github.com/dagar))
- Implement GeoFence persistence [\#6442](https://github.com/mavlink/qgroundcontrol/pull/6442) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fix altitude change signalling [\#6441](https://github.com/mavlink/qgroundcontrol/pull/6441) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Simplify README with links to devguide [\#6432](https://github.com/mavlink/qgroundcontrol/pull/6432) ([hamishwillee](https://github.com/hamishwillee))
- Vehicle. Expose sensor status to Qml [\#6431](https://github.com/mavlink/qgroundcontrol/pull/6431) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- ArduPilot: Start possible Solo video [\#6430](https://github.com/mavlink/qgroundcontrol/pull/6430) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Don't recalc for manual grid [\#6426](https://github.com/mavlink/qgroundcontrol/pull/6426) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Don't query terrain from Fly View mission items [\#6420](https://github.com/mavlink/qgroundcontrol/pull/6420) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Terrain batch fix, transect style generation fix [\#6418](https://github.com/mavlink/qgroundcontrol/pull/6418) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Add missing final [\#6417](https://github.com/mavlink/qgroundcontrol/pull/6417) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Remove debug logging [\#6416](https://github.com/mavlink/qgroundcontrol/pull/6416) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Refly and camera shot count support [\#6415](https://github.com/mavlink/qgroundcontrol/pull/6415) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Slightly better Log Replay [\#6414](https://github.com/mavlink/qgroundcontrol/pull/6414) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- modify android build repo [\#6412](https://github.com/mavlink/qgroundcontrol/pull/6412) ([jinchengde](https://github.com/jinchengde))
- Update PX4 Firmware metadata Thu May  3 00:38:00 EDT 2018 [\#6411](https://github.com/mavlink/qgroundcontrol/pull/6411) ([dagar](https://github.com/dagar))
- README: Add unit tests information [\#6410](https://github.com/mavlink/qgroundcontrol/pull/6410) ([patrickelectric](https://github.com/patrickelectric))
- Handle EKF and 4.2m correctly [\#6409](https://github.com/mavlink/qgroundcontrol/pull/6409) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Large parameter progress on outdoor theme [\#6408](https://github.com/mavlink/qgroundcontrol/pull/6408) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Don't clear results for airspeed/level calibration [\#6406](https://github.com/mavlink/qgroundcontrol/pull/6406) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Some random corrections around the code [\#6405](https://github.com/mavlink/qgroundcontrol/pull/6405) ([patrickelectric](https://github.com/patrickelectric))
- Convert Survey complex item to use TransectStyleComplexItem [\#6404](https://github.com/mavlink/qgroundcontrol/pull/6404) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Fix bug in terrain transect adjustment [\#6402](https://github.com/mavlink/qgroundcontrol/pull/6402) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- APM Sub: default attitude streamrate to 20Hz [\#6401](https://github.com/mavlink/qgroundcontrol/pull/6401) ([jaxxzer](https://github.com/jaxxzer))
- APM Sub: update parameter metadata for Sub-3.5.3 [\#6399](https://github.com/mavlink/qgroundcontrol/pull/6399) ([jaxxzer](https://github.com/jaxxzer))
- SurveyMissionItem -\> SurveyComplexItem [\#6398](https://github.com/mavlink/qgroundcontrol/pull/6398) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Safety summary: Rework to better match Safety Page [\#6397](https://github.com/mavlink/qgroundcontrol/pull/6397) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Support PING response [\#6396](https://github.com/mavlink/qgroundcontrol/pull/6396) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Update terrain alts when user drags mission item [\#6395](https://github.com/mavlink/qgroundcontrol/pull/6395) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- FactCheckBox: New value is not being set correctly [\#6394](https://github.com/mavlink/qgroundcontrol/pull/6394) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Don't allow user to add settings item command [\#6392](https://github.com/mavlink/qgroundcontrol/pull/6392) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Different visuals for Planned Home in Plan View [\#6390](https://github.com/mavlink/qgroundcontrol/pull/6390) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Mission Item: Mavlink MAV\_FRAME\_GLOBAL\_TERRAIN\_ALT support [\#6389](https://github.com/mavlink/qgroundcontrol/pull/6389) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- UnitsSettings: rework/bugfix metadata translators setup [\#6388](https://github.com/mavlink/qgroundcontrol/pull/6388) ([jaxxzer](https://github.com/jaxxzer))
- Use new FactValueSlider control for simple mission item altitudes [\#6385](https://github.com/mavlink/qgroundcontrol/pull/6385) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Allow manual control of when to send FOLLOW\_TARGET messages. [\#6380](https://github.com/mavlink/qgroundcontrol/pull/6380) ([dogmaphobic](https://github.com/dogmaphobic))
- Limit output of camera and lights using brd\_pwm\_count [\#6378](https://github.com/mavlink/qgroundcontrol/pull/6378) ([patrickelectric](https://github.com/patrickelectric))
- Support for multiple links to a single vehicle [\#6377](https://github.com/mavlink/qgroundcontrol/pull/6377) ([acfloria](https://github.com/acfloria))
- Fixed checked state logic  [\#6376](https://github.com/mavlink/qgroundcontrol/pull/6376) ([dogmaphobic](https://github.com/dogmaphobic))
- USBBoardInfo.json: add Omnibus F4 SD [\#6372](https://github.com/mavlink/qgroundcontrol/pull/6372) ([bkueng](https://github.com/bkueng))
- Fix video popup on windows [\#6368](https://github.com/mavlink/qgroundcontrol/pull/6368) ([patrickelectric](https://github.com/patrickelectric))
- UDP Fixes [\#6366](https://github.com/mavlink/qgroundcontrol/pull/6366) ([dogmaphobic](https://github.com/dogmaphobic))
- \[WIP\] videonode: Do not finish if material is different [\#6365](https://github.com/mavlink/qgroundcontrol/pull/6365) ([patrickelectric](https://github.com/patrickelectric))
- Automated preflight checklists [\#6364](https://github.com/mavlink/qgroundcontrol/pull/6364) ([philipoe](https://github.com/philipoe))
- Don't signal if coordinate is the same [\#6361](https://github.com/mavlink/qgroundcontrol/pull/6361) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Upstream stable merge [\#6360](https://github.com/mavlink/qgroundcontrol/pull/6360) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Skip host lookup on Android [\#6359](https://github.com/mavlink/qgroundcontrol/pull/6359) ([dogmaphobic](https://github.com/dogmaphobic))
- Separate terrain from tile maps within cached tile request system. [\#6358](https://github.com/mavlink/qgroundcontrol/pull/6358) ([dogmaphobic](https://github.com/dogmaphobic))
- Guard terrain tile from reading beyond the bytearray end [\#6355](https://github.com/mavlink/qgroundcontrol/pull/6355) ([birchera](https://github.com/birchera))
- Fix OpenSSL for Windows [\#6354](https://github.com/mavlink/qgroundcontrol/pull/6354) ([birchera](https://github.com/birchera))
- Update mavlink v2.0 submodule Sun Apr 15 00:39:11 UTC 2018 [\#6353](https://github.com/mavlink/qgroundcontrol/pull/6353) ([dagar](https://github.com/dagar))
- Back out bad pull: \#6155 [\#6351](https://github.com/mavlink/qgroundcontrol/pull/6351) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
-  Jenkins add Android release build [\#6350](https://github.com/mavlink/qgroundcontrol/pull/6350) ([dagar](https://github.com/dagar))
-  Jenkins OSX installer build and archive [\#6349](https://github.com/mavlink/qgroundcontrol/pull/6349) ([dagar](https://github.com/dagar))
- Jenkins update to linux and android docker 2018-04-12 [\#6348](https://github.com/mavlink/qgroundcontrol/pull/6348) ([dagar](https://github.com/dagar))
- Update PX4 Firmware metadata Sat Apr 14 00:37:06 EDT 2018 [\#6346](https://github.com/mavlink/qgroundcontrol/pull/6346) ([dagar](https://github.com/dagar))
- maps: Statkart update to v4 [\#6343](https://github.com/mavlink/qgroundcontrol/pull/6343) ([AndKe](https://github.com/AndKe))
- Link read/write: Better guarding against crashes [\#6341](https://github.com/mavlink/qgroundcontrol/pull/6341) ([DonLakeFlyer](https://github.com/DonLakeFlyer))
- Added clickable link and ScrollView to CustomCommandWidget [\#6319](https://github.com/mavlink/qgroundcontrol/pull/6319) ([Rogni](https://github.com/Rogni))
- Support for low battery state \(and remaining time\) [\#6316](https://github.com/mavlink/qgroundcontrol/pull/6316) ([dogmaphobic](https://github.com/dogmaphobic))

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by dogmaphobic** [comment]
If anything, it shows we need to better tag these issues (or remove erroneous tags for that matter.) The list itself is great but its content is only as good as the tagging for the issues. The old _garbage in/garbage out_. I assume if I go through them and fix the tags the list would be regenerated at some point? 

Also, there are tons of _non issues_, which get filed on a daily basis and are promptly closed. Is there a way to exclude those? Create a new "Bogus" tag? :)

**Comment by dogmaphobic** [comment]
Ancient history
