### ISSUE TITLE
Snyc button stucks disabled when rotating

### ISSUE THREAD

**Issue by feemi** [mavlink/qgroundcontrol#6582]
Steps to reproduce issue:
Connect Vehicle
Wait for  parameter download
Try to upload mission when mission downloading from vehicle

MissionControllerLog: MissionControllerLog::sendToVehicle called while syncInProgress
Sync button stucks in disabled state and keeps rotating.

Should we consider this as a bug? 
Maybe we should prevent user to use sync button when mission is downloading from vehicle?

**Comment by DonLakeFlyer** [comment]
Cam you verify once a new daily comes out? Wait till tomorrow to be sure.
