### ISSUE TITLE
QGC on iOS connection issue

### ISSUE THREAD

**Issue by myeabhishek** [mavlink/qgroundcontrol#6584]
I want to use my iPad to fly my vehicle using QGC. However, I am not able to connect to the vehicle using 3DR radio telemetry. I plugged the telemetry on Ipad using a lightning port converter but it didn't work. The same thing works in case of android tablets.

There isn't sufficient documentation on how to connect your drone using iPad. Please help!

**Comment by dogmaphobic** [comment]
iOS has no serial communication support. There is no "official" USB/UART adapter supported by Apple. What is a `lightning port converter`? That doesn't sound right. Convert to what? USB? Only Apple "approved" devices are supported. It's extremely unlikely anything would work.
