### ISSUE TITLE
 When we plan this kind of flight, we fly a lot of useless routes.

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6585]
Hello，when we plan this kind of flight, we fly a lot of useless routes.  
How should we plan this graphic flight area so that we can not fly so many useless routes?
Thanks

![img_0078](https://user-images.githubusercontent.com/17830375/41281271-8d234120-6e63-11e8-995b-29ea22a48f69.PNG)

**Comment by kikislater** [comment]
Same as https://github.com/mavlink/qgroundcontrol/issues/6490
Is this a real flight over this kind of polygon ? More reasonable is like that : https://github.com/mavlink/qgroundcontrol/issues/6489

**Comment by MyOnlyOnlySunshine** [comment]
Do you mean that we should cut into multiple convex polygons to fly? 
When we plan irregular navigation, it is easy to cause many routes to fly.

**Comment by DonLakeFlyer** [comment]
First step is to use a newer daily build (assuming this is android) which will do a much better job at this. If iOs then you are kind of stuck for now until we figure out how to get working again.

**Comment by DonLakeFlyer** [comment]
A similar pattern using daily build:
![screen shot 2018-06-18 at 12 11 33 pm](https://user-images.githubusercontent.com/5876851/41556864-c6d23a84-72f0-11e8-852c-e98e76e94d64.png)

It's not going to get much better than that without some really sophisticated path generation which is unlikely to happen.

**Comment by MyOnlyOnlySunshine** [comment]
Could you help me find which C++ or qml files changes if i want to plan that routes ,i can not find the file of source code to learn about it . Thanks

**Comment by MyOnlyOnlySunshine** [comment]
Amazing, too complex . Thanks
