### ISSUE TITLE
Store Android maps cache in external storage directory, not app data directory

### ISSUE THREAD

**Issue by jacobsenmd** [mavlink/qgroundcontrol#6588]
Request for QGC Android to cache maps in the external storage directory rather than the app's data directory. This would have two benefits:

1. The external storage directory typically has more space, allowing a user to store larger cached tile sets or even swap SD cards as necessary.

2. This would allow users to generate tilesets on external devices and copy them onto the Android device. This is not possible under the current architecture, because the data/ directory is not accessible by the file system unless the phone is rooted. This may not be a common use case, but it does exist; I represent government users who need completely offline devices and cannot build tilesets within QGC itself.

**Comment by DonLakeFlyer** [comment]
Using Import/Export this should all be doable. let me know if something is missing.
