### ISSUE TITLE
Distance Sensor data on value widget

### ISSUE THREAD

**Issue by lacondro** [mavlink/qgroundcontrol#6620]
Hi, I want to add a custom widget that shows the distance_sensor.current data, but I'm not sure if it is possible.

So I am wondering if you have any plan to add mavlink data visible on default value widget? 

Thanks!

**Comment by DonLakeFlyer** [comment]
Distance sensor information is available to the Instrument Widget:
![screen shot 2018-06-22 at 10 14 38 am](https://user-images.githubusercontent.com/5876851/41789725-19b2f434-7605-11e8-84de-da95962af1f1.png)

It is also available from the Vehicle.distanceSensor FactGroup in Qml.

**Comment by lacondro** [comment]
Where can I find instrument widget? Can you give more specific instruction?
![image](https://user-images.githubusercontent.com/39759482/41828657-810154c8-7871-11e8-9418-a7d6a3b43af9.png)

This is the only similar window I can find.

Thank you

**Comment by DonLakeFlyer** [comment]
That is it. The distance sensor values are available in daily builds.

**Comment by lacondro** [comment]
Oh it was in daily builds! Thank you!
