### ISSUE TITLE
Go to command issue

### ISSUE THREAD

**Issue by feemi** [mavlink/qgroundcontrol#6622]
I am not sure we can achieve this from px4 or qgc.
If we give go to command from fly map to opposite direction while vehicle is moving with normal speed. It tries to brake immediately which cause unstable flight. Is it possible to wait for a bit slow down and have a smooth transition to reposition command ?

**Steps To Reproduce**
Send Vehicle to one direction.
Tap a point from map which is exaclty opposite direction while vehicle moving.
Send Go to command to new point.

----
**Enviroments**
- Daily QGC or stable version
- Autopilot board: Pixhawk 2
- Autopilot firmware: 1.7.3 or 1.8.0

**Comment by DonLakeFlyer** [comment]
That would be a firmware change.
