### ISSUE TITLE
Wrong default altitude in new altitude selector

### ISSUE THREAD

**Issue by okalachev** [mavlink/qgroundcontrol#6629]
In the `master` branch version of QGC the altitude of a Land waypoint defaults to the flight altitude: 

<img width="260" alt="2018-06-21 23 35 55" src="https://user-images.githubusercontent.com/1683279/41744392-5021161c-75ac-11e8-8dda-8f58b0e592d5.png">

But [MAVLink specifies](http://mavlink.org/messages/common#MAV_CMD_NAV_LAND) that this is the ground altitude, so I think, that it should default to 0, as the 3.3.2 version does:

<img width="245" alt="2018-06-21 23 39 51" src="https://user-images.githubusercontent.com/1683279/41744441-6dd9d338-75ac-11e8-9fff-977a34ea8921.png">

**Comment by DonLakeFlyer** [comment]
This UI isn't updating correctly. The actual value send to vehicle is 0.

**Comment by DonLakeFlyer** [comment]
Both _LAND and _VTOL_AND are forced back to Relative:0.

**Comment by DonLakeFlyer** [comment]
Thanks for the bug report.
