### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by swizzlr** [mavlink/qgroundcontrol#665]
Right now I'm having to redownload the daily builds. It would be great if we could have an auto update, ideally as a patch file to reduce d/l times.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer we seem to have managed this for Ubuntu, how hard is the path for Mac OS and Windows?

**Comment by DonLakeFlyer** [comment]
Ubuntu package mgmt is built into the os. We'd have to go into the stores to get similar support on Mac and Window and that's a whole other can of worms. Otherwise we need to implement fully ourselves.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer It might make sense looking at this solution:
http://www.updatenode.com

**Comment by LorenzMeier** [comment]
@DonLakeFlyer The opposite approach would be to go with the platform specific mechanism, e.g. the Mac and Windows app stores.
https://developer.apple.com/osx/distribution/
and here for Windows:
https://dev.windows.com/en-us/publish

Aside from the initial set-up overhead, these might work best long term.

**Comment by dagar** [comment]
https://github.com/pypt/fervor - Not as nice as being in an app store or the way an app like chrome auto installs updates, but it's easy to include and would provide a prompt with a link to the latest download.

![687474703a2f2f707970742e6769746875622e636f6d2f666572766f722f73637265656e73686f742d322e706e67](https://cloud.githubusercontent.com/assets/84712/9705429/382abdd0-5492-11e5-9b6e-dbe9c21ffe11.png)

**Comment by dagar** [comment]
Android - done

**TODO**
 - iOS - several possible services that could help here (buddybuild or bitrise)
 - OSX - circleci? (https://github.com/mavlink/qgroundcontrol/issues/3973)
 - Windows - stable builds to the Windows store (https://github.com/mavlink/qgroundcontrol/issues/3651)
 - Ubuntu - launchpad (https://github.com/mavlink/qgroundcontrol/issues/4031)
 - Linux other?

Main difficulty for iOS/OSX automation will be enabling the commercial version of Qt on these services.

**Comment by DonLakeFlyer** [comment]
* iOS and OSX will be done through store and is available. OSX coming in a few days.
* Windows will be available through store. We'll do through with 3.1 release.

**Comment by DonLakeFlyer** [comment]
Windows/OSX is going to push off to 3.2 release.

**Comment by LorenzMeier** [comment]
Closing as stale.
