### ISSUE TITLE
PreFlight checklist lockdown for Stable

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6661]
This needs to be cleaned up. Current state is more of a fixed wing list.

**Comment by philipoe** [comment]
@DonLakeFlyer I assume you intend to make this configurable per vehicle, and _not_ make it so generic that it fits every kind of vehicle (which would be quite useless, i guess you agree with that)?

**Comment by DonLakeFlyer** [comment]
Yup. I haven't put much thought into that though. Have you?

**Comment by philipoe** [comment]
Not yet, no. I need to look into the new checklist structure (given the quite extensive changes you did) first in any case, but am gone for a project demonstration for the next ~3 weeks.
________________________________
Von: Don Gagne [notifications@github.com]
Gesendet: Donnerstag, 28. Juni 2018 19:30
An: mavlink/qgroundcontrol
Cc: Oettershagen Philipp; Comment
Betreff: Re: [mavlink/qgroundcontrol] PreFlight checklist lockdown for Stable (#6661)


Yup. I haven't put much thought into that though. Have you?

**Comment by Antiheavy** [comment]
@DonLakeFlyer this issue seems overcome by events?

**Comment by DonLakeFlyer** [comment]
I think what @dogmaphobic is good enough for now
