### ISSUE TITLE
QGC's video framerate is very low

### ISSUE THREAD

**Issue by waterflyfish** [mavlink/qgroundcontrol#6669]
We complied the source code v3.3.2 downloaded from github in windows ,found that when connected the network with wifi ,it's video framerate was rather low.However,the exe file we downloaded works well.Once I thought the Qt5.9.1 caused this problem, and changed it to qt5.9.3,this problem still exits. Anybody have this experience ?

**Comment by Vavooon** [comment]
Do you mean user interface framerate or video streamed from drone?
