### ISSUE TITLE
QML Module Not found  In Qt 5.11.0.

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6675]
Hello, when I use qt5.11.0 to open the source code compiler, the compiler reported an error, but can successfully compile, but can not use those who complained qml, also ask why the source of the source will be more Come out three temporary compilation files, what is that? Thank you

<img width="987" alt="2018-07-02 2 22 10" src="https://user-images.githubusercontent.com/17830375/42148317-528a307c-7e04-11e8-997f-871eb59d2c34.png">
<img width="779" alt="2018-07-02 2 16 54" src="https://user-images.githubusercontent.com/17830375/42148319-5423ef54-7e04-11e8-877f-f1e14cce3ec0.png">

**Comment by DonLakeFlyer** [comment]
No quite sure what you are asking. But you cannot edit QGC qml files in the designer. They can only be edited using the text editor. Those warnings you show for module not found can be ignored.

**Comment by LimEunji** [comment]
Why can't I edit QGC qml files in the designer?
