### ISSUE TITLE
Plan is waiting on terrain data

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#6676]
When using AGL features (including a terrain following survey mission) QGC remains in the state of waiting for terrain data. Up to now for one hour and i assume it will never finish. (Today's daily on ubuntu)

![image](https://user-images.githubusercontent.com/14801663/42152309-01d29814-7de0-11e8-896f-781d3fc40674.png)

**Comment by DonLakeFlyer** [comment]
Can you attach the plan file? Turn off terrain to save. Also let me know what settinsg you are using for terrain adjustment.

**Comment by DonLakeFlyer** [comment]
Related to #6534

**Comment by DonLakeFlyer** [comment]
Should be fixed now
