### ISSUE TITLE
Add NXPHlite V3

### ISSUE THREAD

**Issue by davids5** [mavlink/qgroundcontrol#6679]
@DonLakeFlyer 

Would you please add the USB auto connect for PX4 NXPHlite v3.x

CONFIG_CDCACM_VENDORID=0x1FC9
CONFIG_CDCACM_VENDORSTR="NXP"
 CONFIG_CDCACM_PRODUCTSTR="PX4 NXPHlite v3.x"
CONFIG_CDCACM_PRODUCTID=0x001c

The firmware will be under development for a bit but will be in nxphlite-v3_default.px4 when released.

**Comment by davids5** [comment]
I should have also mentioned the board_id is 28 decimal (0x1c). It is the same as the product id.

**Comment by davids5** [comment]
@dogmaphobic would you be able to add this?

**Comment by dogmaphobic** [comment]
> @dogmaphobic would you be able to add this?

Sure! Blindly but you can let me know if it works...

**Comment by DonLakeFlyer** [comment]
What is the board id from the bootloader for this board?

**Comment by davids5** [comment]
board_id is 28 decimal (0x1c). It is the same as the product id

**Comment by LorenzMeier** [comment]
A pull request with those extensions would be most appreciated. It has probably reached the point where board support should be factored out of the code and into an XML file or equivalent. I'm closing this as it is not a real issue and something that could be easily contributed. Thanks for submitting the PR and I'm closing this here.
