### ISSUE TITLE
ArduPilot: Add support for flashing Chibios firmwares to Pixhawk style boards

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6693]
From Tridge:

"I'd like to discuss how the new ChibiOS based boards are detected and
correct firmware chosen from the firmware.ardupilot.org website.

Up to now we've used the board IDs from the bootloader, but that didn't
give a good way to know the board type when the bootloader is not
running.

For the ChibiOS builds we've made the USB IDs contain the firmware type
in the USB strings. So for fmuv5 I see this on Linux:

 /dev/serial/by-id/usb-ArduPilot_fmuv5_2A001E000151373137393536-if00

where "fmuv5" is the build type.

On windows it shows the "Bus reported device description" as fmuv5.

 http://uav.tridgell.net/tmp/fmuv5.png"

**Comment by DonLakeFlyer** [comment]
@tridge So for boards which have not been flashed yet. Should the Chibios builds be allowed to flash onto boards which report the bootloader boardid as:

```    static const int boardIDPX4FMUV5 = 50;      ///< PX4 V5 board, as from USB PID```

**Comment by DonLakeFlyer** [comment]
And then in that case the user has two firmware options?
* Chibios version
* Old NuttX version

Or should it only allow Chibios?

**Comment by Hwurzburg** [comment]
This may or may not be related, but Qgroundcontrol does not connect to my OmnibusF4pro using ChiBios firmware..neither does Tower....Tower does recognize the F4light HAL firmware on the board...Qgroundcontrol did not...

**Comment by LorenzMeier** [comment]
@rmackay9 You can continue the discussion here.

**Comment by DonLakeFlyer** [comment]
> This may or may not be related, but Qgroundcontrol does not connect to my OmnibusF4pro using ChiBios firmware..neither does Tower....Tower does recognize the F4light HAL firmware on the board...Qgroundcontrol did not...

You need to manual connect to the board using a manual connection. It will not autoconnect

**Comment by Hwurzburg** [comment]
This is an Android USB connection,not PC...how do you manually connect?...the USB port is not listed as a comm port when in Android looking under manual connections

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 13, 2018 at 5:16 PM, Don Gagne<notifications@github.com> wrote:   

This may or may not be related, but Qgroundcontrol does not connect to my OmnibusF4pro using ChiBios firmware..neither does Tower....Tower does recognize the F4light HAL firmware on the board...Qgroundcontrol did not...


You need to manual connect to the board using a manual connection. It will not autoconnect

**Comment by DonLakeFlyer** [comment]
This is implemented now

**Comment by Hwurzburg** [comment]
MUCH APPRECIATED! just tested on Omnibus and a WingFC10....thanks!

**Comment by DonLakeFlyer** [comment]
QGC should connect if you are running ArduPilot ChibiOS firmware on it.

**Comment by DonLakeFlyer** [comment]
Are you running a daily build?

**Comment by Hwurzburg** [comment]
yes.....1/18

**Comment by DonLakeFlyer** [comment]
Ok, let me figure out where my test board has gone to and I'll take a look.

**Comment by DonLakeFlyer** [comment]
ChibiOS working now. DragonLink still not working but that will be a separate issue.

**Comment by DonLakeFlyer** [comment]
DragonLink is covered in #7175
