### ISSUE TITLE
 Altitude information missing on QGC

### ISSUE THREAD

**Issue by Pauloledes** [mavlink/qgroundcontrol#6702]
Hi, I am currently using Intel Aero Drone with Pixhawk and PX4 with the help of QGroundControl.
I connected the drone to my computer and I am able to see through the drone's camera via QGC.
I also have access to the 3 angles of the drone in live that are the heading, the pitch and the roll. Unfortunately, the place where I should be reading the altitude is left blank and I can not figure out why. I have taken a screenshot of what it looks like, I previously realised calibration of the sensors.
![parameters qgc](https://user-images.githubusercontent.com/40398982/42513251-72333fe2-8424-11e8-9ed3-d6e7adba3b66.png)
I have also another problem, maybe they are linked. When I tried to setup a flight mission for the drone, I can not upload it to the drone so it can follow the path. I do not know where the problem comes from because the error message is not really explicit as you can see below... I have do the calibration well though.
Thanks for your help,
Best regards,
Paul. #
![error](https://user-images.githubusercontent.com/40398982/42513271-7ffe2420-8424-11e8-95d9-37863111dc2b.png)

**Comment by DonLakeFlyer** [comment]
Relative altitude is taken from the GLOBAL_POSITION_INT mavlink message. You can check that QGC is getting that message from the mavlink inspector. Mission transfer failures usually indicate a noisy communication link. Other thing to double check is that you are running latest firmware. Anyway, all of which are vehicle side problems.
