### ISSUE TITLE
Create new official App Store Stable Version

### ISSUE THREAD

**Issue by J1100** [mavlink/qgroundcontrol#6707]
Daily builds are changing rapidly and the only official release is 3.2 which is full of bugs and lacking features. It would be very much appreciated if QGC could get a new official App Store release up and running for us to point customers to. We would love to use QGC as our default app when selling new drones as well but this is the primary issue holding us back.
Thank you!

**Comment by DonLakeFlyer** [comment]
I assume you are talking about iOS?

**Comment by J1100** [comment]
Android, actually. I see the version up is 3.3.2 not 3.2 as I stated (3.2 release notes are the latest shown) but my issues still remain, it's not very reliable and is missing features of the newer builds. Thanks

**Comment by DonLakeFlyer** [comment]
3.4 Stable will be out in a few weeks.
