### ISSUE TITLE
QGC will not save custom camera settings

### ISSUE THREAD

**Issue by J1100** [mavlink/qgroundcontrol#6708]
After entering all new custom camera settings QGC forgets them before planning the next mission which requires the settings to be re-entered again. Previous versions remembered custom camera settings.

----
Ground station operating system: Samsung Galaxy Tab E Android 7.1.1
QGroundControl version and build: 3.3.0-570 and later
Autopilot board: Pixhawk
Autopilot firmware: ArduPlane 3.7.1

**Comment by DonLakeFlyer** [comment]
Yeah I broke this. I'll fix before 3.4 goes to Stable.
