### ISSUE TITLE
Feature Request: use the Orbit graphics and draggable control for Fixed Wing Loiter waypoints

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6721]
The Orbit graphics and controls look nice (WIP at time of this request).  The same (similar) graphics and draggable edit controls could be used to better show fixed wing Loiter waypoints in Plan screen as well as Fly screen (without the edit controls).

Reference this PR:
https://github.com/mavlink/qgroundcontrol/pull/6610
![image](https://user-images.githubusercontent.com/12117027/42729820-018ccedc-87aa-11e8-8f20-0f99f734e7e2.png)

**Comment by DonLakeFlyer** [comment]
Yup, all doable.

**Comment by Hunter522** [comment]
With https://github.com/mavlink/qgroundcontrol/pull/9580 now merged, should this issue be closed?

**Comment by Antiheavy** [comment]
Neat!
