### ISSUE TITLE
Map Polygon: Set Radius broken

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#6725]
Broken by changes here: https://github.com/mavlink/qgroundcontrol/commit/ffe65c58e712682f668989b354d0efe34a6cd07a#diff-40322e39a2f6afdb3924c5d06cf80f56 which moves the menu up the hiearchy causing the menu item for set radius to not have visibility to the items with the center component.

**Comment by GlidLov** [comment]
any news? still broken in the last build...

**Comment by DonLakeFlyer** [comment]
I just tested both Stable and Daily on OSX it it works fine. Please provide exact steps to reproduce and OS and I'll reopen.

**Comment by GlidLov** [comment]
platform was Android, just tested last 3.5 and it works ok, you can close
