### ISSUE TITLE
QGroundControl.AppImage has 228M in master branch

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#6727]
The AppImage appears to be a bit bigger, downloaded from:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.AppImage

**Comment by DonLakeFlyer** [comment]
@dagar Not sure what happened here. Maybe new Qt 5.10 pulls more than it needs?

**Comment by DonLakeFlyer** [comment]
New Qt includes debug libs. When plugins/qml directory is copied it copies across thesee debug versions as well increasing size.

**Comment by patrickelectric** [comment]
Well, you can create a normal appveyor and a debug library appveyor. Does not make sense to have debug libraries on a normal release.

**Comment by DonLakeFlyer** [comment]
Fixed by pushing up new Qt image for Linux
