### ISSUE TITLE
PX4 Voltage Divider Calculator unresponsive

### ISSUE THREAD

**Issue by George-Lu-1997** [mavlink/qgroundcontrol#6732]
- Ground station operating system: Windows 10
- QGroundControl version 3.3.2
- Autopilot board: Pixhawk
- Autopilot firmware: PX4, version and build is the one featuring the LPE at http://px4-travis.s3.amazonaws.com/Firmware/stable/px4fmu-v2_lpe.px4 (don't know the exact details, this was linked to me, but maybe it's familiar? Firmware version with LPE support)

I have been having bad luck getting a quadcopter to work, so I've been redoing everything from scratch. I flashed the quadcopter with the version of PX4 linked, performed all the airframe, sensor, and radio calibration steps, then prepared to calibrate the ESC. I set the number of cells to 4, full voltage per cell to 3.7, and empty voltage to 3.5. I then clicked on calculate voltage divider and input 16.38 and pressed calculate, but there was no change in the voltage divider. I experimented with various values and there was still no change.

**Comment by DonLakeFlyer** [comment]
I believe this has already been fixed in daily builds. Please give that a try.
