### ISSUE TITLE
ArduPilot-Flashing Chibios builds

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#6760]
At the moment QGC is only aware of px4 type firmware, and ArduPilot is moving away from these. Currently the newer firmware builds (apj) can+t even be selected as a custom firmware.

**Comment by DonLakeFlyer** [comment]
Yup. I'll get this going once I get Stable 3.4 out the door.

**Comment by DonLakeFlyer** [comment]
Also new bootloader and board detection from com port naming.

**Comment by lvale** [comment]
Thanks @DonLakeFlyer 
If you could "squeeze" this to the 3.4 release would be great :)

**Comment by DonLakeFlyer** [comment]
Maybe in a point release after the first one goes out. Not sure. Depends on how big of a change.
