### ISSUE TITLE
"Set Radius..." on circle survey's is in meters only.  does not change with change of distance units.

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#6764]
"Set Radius" on circle survey's is in meters only.  It does not change with change of distance units.  Today's QGC daily build.

To reproduce:

1) change distance units to "Feet".
2) create a Survey Pattern in the Plan screen.
3) change it to a "Circle".
4) select "Set Radius..."
5) notice that the text entry has no units associated with it, but that the radius drawn on-screen is in meters.

**Comment by DonLakeFlyer** [comment]
Oopsie. I'll fix in Stable.
