### ISSUE TITLE
Weird KML

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#6770]
[testpolygon.kml.txt](https://github.com/mavlink/qgroundcontrol/files/2264744/testpolygon.kml.txt)

If you open this KML (renamed to kml.txt so I could attach) and move the indicated vertex, things seem to go haywire.

<img width="1203" alt="screen shot 2018-08-06 at 10 30 18 pm" src="https://user-images.githubusercontent.com/749243/43751043-2f5da7ce-99c9-11e8-93bd-3d053282d2c0.png">

<img width="1203" alt="screen shot 2018-08-06 at 10 30 42 pm" src="https://user-images.githubusercontent.com/749243/43751048-341d3be4-99c9-11e8-8f65-214fb90643a5.png">

**Comment by DonLakeFlyer** [comment]
I'll take a look at some point. But not too concerned with really strange shapes working. More concerned that theoretically this case should work fine.

**Comment by thomasgubler** [comment]
I had a quick look. The _polygonModel object that is used internally for the polygon in the transects generation seems to stay correct. (That can be seen from the screenshot: the white lines follow the correct polygon). I have yet to take a closer look at the _polygonPath object that (I assume) gets picked up in qml for display.

**Comment by DonLakeFlyer** [comment]
Ah, interesting. They could be out of sync. The other thing is possibly a Qt bug where the UI is not updating correctly to _polygonPath changes. That wouldn't suprise me at all either.

**Comment by thomasgubler** [comment]
PR with possible fix here: https://github.com/mavlink/qgroundcontrol/pull/6838
