### ISSUE TITLE
Crash bug in Plan View

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#6771]
In Plan View, if you have any pattern and select _Change Command_, QGC crashes. A call is being made to `MissionCommandTree::_collapseHierarchy` with `vehicle` set to NULL and things don't go too well from there :P

Note that this is in Stable_V3.4.

https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/MissionCommandTree.cc#L99

<img width="1449" alt="screen shot 2018-08-07 at 11 02 52 am" src="https://user-images.githubusercontent.com/749243/43784391-0e92a99a-9a32-11e8-881c-0207204cf80d.png">

**Comment by DonLakeFlyer** [comment]
It's ok for _activeVehicle to be NULL. The system handles that and uses the offline vehicle. The problem is that dialog only works for simple items, not complex items. The dialog initialize was expecting to be able to get a command category for a complex item which does not exist.
