### ISSUE TITLE
SSL error with Terrain on Android QGC 3.4

### ISSUE THREAD

**Issue by kikislater** [mavlink/qgroundcontrol#6780]
Ground station operating system : Android 7

    QGroundControl version and build : latest release from playstore : 3.4

    Autopilot board: not required

    Autopilot firmware : not required.

    Exact steps to reproduce the problem :
    Plan survey mission, add terrain

Same as here : https://github.com/mavlink/qgroundcontrol/issues/6681 but in Android. Could post log 

![screenshot_2018-08-08-09-24-03-342_org mavlink qgroundcontrol](https://user-images.githubusercontent.com/13238064/43819123-b88f9654-9af2-11e8-9264-3ea8646d2190.png)

**Comment by kikislater** [comment]
It works on my old Tablet with Android 4.4 but not in my phone with Android 7

**Comment by DonLakeFlyer** [comment]
Possibly related to #6337

**Comment by DonLakeFlyer** [comment]
This should be fixed now
