### ISSUE TITLE
Tailsitter VTOL orientation change after transition

### ISSUE THREAD

**Issue by abdulmajid92** [mavlink/qgroundcontrol#6793]
I have developed quad tailsitter vtol. The aircraft orientations have an issue when the aircraft transition from MC mode to FW mode, the aircraft orientation was showed that the aircraft has pitched 90 degree down (still MC orientation, it should be change to FW orientation). Anybody can help this issue?

Thanks

**Comment by DonLakeFlyer** [comment]
You should talk with the firmware folks about this. I don't think it makes sense for QGC to understand VTOL state and futz with HUD display.
