### ISSUE TITLE
ios xcode  Assertion failed: (buffer->content_type == HB_BUFFER_CONTENT_TYPE_UNICODE), function hb_shape_full, file hb-shape.cc, line 358.

### ISSUE THREAD

**Issue by francisyao** [mavlink/qgroundcontrol#6805]
2018-08-16 14:20:17.753949+0800 QGroundControl[317:13162] Filter rules "*Log.debug=false\n"
Could not open log file '/gstreamer-log.txt' for writing: Operation not permitted
Assertion failed: (buffer->content_type == HB_BUFFER_CONTENT_TYPE_UNICODE), function hb_shape_full, file hb-shape.cc, line 358.

Qt5.11.0
xcode Version 9.4
GQC 4.3.0

I can't build it  on my iphone or ios simulator...

**Comment by DonLakeFlyer** [comment]
Dup of #6605
