### ISSUE TITLE
Integrate Tick Marks & Slider with Numerical Value in Tuning Page

### ISSUE THREAD

**Issue by rollysing** [mavlink/qgroundcontrol#6808]
I'm a hobbyist and have no coding/programming experience so when it comes to tuning a new setup, the slider was more relateable than numerical values. It would be ideal that the tick marks and slider from the previous versions, be integrated with the numerical values above them. This would be akin to the radio dial of the FM radio. One could put the slider to a general area that would make the setup functional and stable, then use the numerical values to fine tune it. I think that would serve a wide range of experience levels and make tuning more intuitive, regardless of whether you're a beginner that has no understanding of PIDs to the most experienced developers.

Thanks.

**Comment by DonLakeFlyer** [comment]
I switched back to regular sliders like it was before.
