### ISSUE TITLE
Stop forwarding joystick input when calibrating joystick.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#6820]
Current master:
when joystick is enabled, copter is disarmed, user can calibrate joystick.
The calibration instructions instruct user to do "arm/disarm" input on the joystick.
Those commands are performed by arducopter during the calibration routine.

It would be safer to not forward that data...

**Comment by DonLakeFlyer** [comment]
Hmm, I think something may have broken. I thought that was how it worked.

**Comment by DonLakeFlyer** [comment]
I just tested this on Stable and commands were not sent to the vehicle during calibration?

**Comment by AndKe** [comment]
you are right, I must have confused joystick calibration with RC calibration (that happened before) - apparently my head went to the icon looking like a RC radio because the "joystick"  is an Interlink elite device. 
-my bad.
