### ISSUE TITLE
Waypoint altitude not set correctly

### ISSUE THREAD

**Issue by sjd69** [mavlink/qgroundcontrol#6823]
QGroundControl release 3.4.1
Windows 10

QGroundControl does not properly set the altitudes of waypoints on 3.4.1. Each waypoints altitude is set to 0.0m. Toggling between relative and absolute altitudes for each waypoint fixes the problem.

Here's a sample mission:
![qgc_30m_rel_alt](https://user-images.githubusercontent.com/25107560/44613432-30deb680-a7c8-11e8-9ca5-05b373242999.png)

Here's what is received by QGC:
![waypoint_details_rd](https://user-images.githubusercontent.com/25107560/44613434-3805c480-a7c8-11e8-8bf6-ae4495e2c93e.png)

**Comment by DonLakeFlyer** [comment]
You changed the first waypoint from Takeoff to Waypoint right? I believe that is what causes it. Really bad bad all the same. Thanks.

**Comment by DonLakeFlyer** [comment]
Hmm, it doesn't reroduce for me. Can you detail out the exact steps. And also save the .plan file which has the bad altitude in it even though the UI shows good altitudes?

**Comment by DonLakeFlyer** [comment]
@antiheavy This theoretically doesn't affect you that much since you would always have the Takeoff command at the start. But there may be other cases which hit this which I haven't figured out yet. So to be safe, I think this fix means a new Stable for you.

**Comment by Antiheavy** [comment]
I'm able to reproduce even with a Takeoff waypoint.

**Comment by DonLakeFlyer** [comment]
@sjd69 Can you test the new version a bit. The installers are here:
* https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/Stable_V3.4/QGroundControl-installer.exe
* https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/Stable_V3.4/QGroundControl.AppImage
* https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/Stable_V3.4/QGroundControl.dmg

**Comment by DonLakeFlyer** [comment]
@Antiheavy Can you try the new build as well?

**Comment by DonLakeFlyer** [comment]
Sorry, old doesn't matter. Any plans. And double check altitudes and round trip values.

**Comment by Antiheavy** [comment]
Something is wrong with "vehicle follows terrain" though.  the altitudes seems wrong, but I havent figured out exactly what is up yet - notice the "normal" waypoints 3,4,5 in this screenshot, the "follow terrain" waypoints that follow should not be that different in altitude:
![image](https://user-images.githubusercontent.com/12117027/44632175-0ada2300-a93c-11e8-9dab-5b97d51ffa0c.png)

**Comment by Antiheavy** [comment]
and when you switch a normal waypoint to AGL mode it actually changes to the wrong altitude too.
notice slight increasing ground height under these waypoints:
![image](https://user-images.githubusercontent.com/12117027/44632283-753f9300-a93d-11e8-8298-a8f08dd5e80b.png)

then change the last one to AGL, you'd expect it to increase altitude slightly, but it actually goes to some lower altitude:
![image](https://user-images.githubusercontent.com/12117027/44632288-9607e880-a93d-11e8-902e-da1b6c3f826e.png)

something is wrong.

**Comment by Antiheavy** [comment]
i just noticed the "planned home position" seems to be at the wrong altitude too..  I can't seem to fix that...

**Comment by DonLakeFlyer** [comment]
Ah, crap. I'm going to have to go back to drawing board on this one.

**Comment by DonLakeFlyer** [comment]
@Antiheavy All the problems you are seeing are caused by the strange planned home position altitude. Is this Gazebo or a real vehicle connection. The actual height of the terrain based item should be the height difference from "P" to "T". If you eyeball it you can see that "6" looks about right. Same thing for the survey. So in reality this is working correctly.

If this is a real vehicle connection then it mainly shows the difference between the terrain data and your vehicle's actual altitude.

**Comment by DonLakeFlyer** [comment]
When I test his on Gazebo it both cases are working fine for me.

**Comment by Antiheavy** [comment]
> If this is a real vehicle connection then it mainly shows the difference between the terrain data and your vehicle's actual altitude.

Ahhh, this makes sense...  I was testing with a "real" vehicle (autopilot on a stick).  However, I'm indoors so my GPS solution and therefore actual altitude estimate was pretty bad.  If I unplug my GPS and re-do then things seem to work as expected.
![image](https://user-images.githubusercontent.com/12117027/44633043-2bf64000-a94b-11e8-9394-6b9671ad769b.png)

The whole difference between terrain database and GPS reported altitude thing has been on my mind recently too, but that is a different issue.

**Comment by DonLakeFlyer** [comment]
Yeah, it should clean itself up by round-tripping through QGC. Can you also load some correct real plans that you have have saved and just quick sanity check on load and round trip through vehicle.

**Comment by DonLakeFlyer** [comment]
Thanks Todd. So far so good then.

**Comment by DonLakeFlyer** [comment]
I"m going to mark 3.4.2 now and call it good.
