### ISSUE TITLE
Qgroundcontrol wants all connections for itself :)

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#6830]
for more features and flexibility, I wanted MAVProxy before QGC.
so I started MAVProxy , let it connect to /dev/ttyUSB0 (SiK radio) and output to localhost udp 14550.
starting QGC:

QGC gets all grabby, and somehow disconnects mavproxy , and grabs the device for itself.
![screenshot from 2018-08-27 15-24-31](https://user-images.githubusercontent.com/1468842/44664935-fb7ad880-aa14-11e8-9cd6-4b20c22cc3d1.png)

there is no option to disconnect...

**Comment by DonLakeFlyer** [comment]
Turn off autoconnect for SiK radios in QGC.
