### ISSUE TITLE
Tuning screen reports missing parameters from beta version, firmware is stable version

### ISSUE THREAD

**Issue by dposea** [mavlink/qgroundcontrol#6832]
Firmware is Arducopter3.5.7, tuning screen reports missing PSC_ACCZ_*  parameters.  Those were released in 3.6 , changing the older ACCEL_Z_*  parameters.

**Comment by DonLakeFlyer** [comment]
Can you check in vehicle summary page what version of firmware is being reported in there? It seems like QGC thinks the firmware is 3.6 or above.

**Comment by dposea** [comment]
3.5.7

**Comment by dposea** [comment]
I tried apm2 and it now has red values for two of the four standard tuning sliders. I dont know if that helps you find the problem. I'm going to use 3.6 for now and hope I dont have issues. This is for a bare bones hexa I'm using for fishing. No rangefinder, lidar, camera.

**Comment by DonLakeFlyer** [comment]
This should all be cleaned up now.

**Comment by MaEtUgR** [comment]
@DonLakeFlyer You might want to close this since there was no reaction.
