### ISSUE TITLE
Loading KML is not updating map position

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#6834]
It seems when loading a KML file, its location is not being updated. The map doesn't move to where it is. This was worked on #6216 but the bug is either still there or something else came up.

**Comment by DonLakeFlyer** [comment]
Getting the map to move correctly is incredibly flaky and loaded with Qt bugs. It may or may not be fixable. I've found cases where there is no way to make it work.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic You fixed this right?

**Comment by DonLakeFlyer** [comment]
Seems to be working in 5.12.6
