### ISSUE TITLE
**BUG** Timed Loiter running indefinitely 

### ISSUE THREAD

**Issue by JonReacher** [mavlink/qgroundcontrol#6841]
PX4 1.8.0 - QGC 3.3.2 Android

A timed (30 sec.) loiter was planned just before the landing pattern. The loiter was entered and continued for 4 minutes before I had to manually select the next waypoint to go to. I don't currently have master on my Android tablet to test. I wasn't sure if this was a known issue and/or had been addressed.
https://logs.px4.io/plot_app?log=3ceb70c2-c26b-4c48-818c-0c1c7d310443

**Comment by DonLakeFlyer** [comment]
That would be a firmware bug not QGC.
