### ISSUE TITLE
add support for Geofence/Rally with Ardupilot (Mavlink 2.0)

### ISSUE THREAD

**Issue by GlidLov** [mavlink/qgroundcontrol#6842]
Hi,

it seems that Geofence / Rally points is not implemented with Arducopter firmware. From what i can understand from code, QGC queries the FC with a mav command MAV_CMD_REQUEST_PROTOCOL_VERSION which Ardupilot replies with an error 3 (MAV_RESULT_UNSUPPORTED) and sets to Mavlink 1.0, which don't support Geofence and rally commands. 

Seems to be a protocol handshake mismatch.

EDIT: i just found it's a known issue
https://github.com/mavlink/qgroundcontrol/pull/5548

**Comment by DonLakeFlyer** [comment]
It's all working as it is supposed to from the QGC side. ArduPilot firmware just doesn't support it yet. I believe @tridge may be working on it though.
