### ISSUE TITLE
Elevation data not available sets NaN into Planned Home Position altitude

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#6846]
If there is a problem with networking, or even no network available, defining a mission makes override the terrain height defined by the user and Mission Upload to vehicle sends a NaN which the flight stack does not support.

![hnimfjdfefamachh](https://user-images.githubusercontent.com/3130363/45045890-58f1d380-b06c-11e8-8fc5-5b663039a7c9.png)
![glgfjpbgmmgkboio](https://user-images.githubusercontent.com/3130363/45045891-58f1d380-b06c-11e8-9ba1-c235c57abfa8.png)

**Comment by ChristopherOlson** [comment]
Would like to add that Android seems to work fine. The above screenshots are from my linux machine. The AirMap elevation data is cached fine with Android. The Linux version fails to get it. Also same problem noted on Windows version.

![screenshot_2018-09-04-12-23-30](https://user-images.githubusercontent.com/22397132/45047153-db16d380-b03d-11e8-88d2-be1531fcd2bb.png)

![screenshot_2018-09-04-12-29-56](https://user-images.githubusercontent.com/22397132/45047340-6728fb00-b03e-11e8-9979-f35eec06fd7f.png)

**Comment by DonLakeFlyer** [comment]
What OS @lvale? Some versions of Android have problems with SSL libs. As do some versions of ArchLinux.

**Comment by DonLakeFlyer** [comment]
That said I think there is an error path here where if the home position height query fails the NaN flows through to the top.

**Comment by DonLakeFlyer** [comment]
@ChristopherOlson Are you using the latest version of QGC? Windows should be working fine.

**Comment by lvale** [comment]
@DonLakeFlyer if i disable networking it happens on all OS's, But the biggest issue here is really the NaN coming up, and then that "kills" uploading missions

**Comment by lvale** [comment]
latest build of QGC

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I just referenced a related issue where it is happening on Windows. I don't actually use Windows, don't have a computer with Windows, have no need for a computer with Windows. On my Android tablet it works fine and fetches and caches the tiles for the AirMap elevation data within seconds. it is failing on two different linux machines even with internet connection.

Using the daily build on one and 3.4.2 on the other. Using 3.4.2 on the Android tablet.

**Comment by DonLakeFlyer** [comment]
@ChristopherOlson What flavor/version of Linux?

**Comment by ChristopherOlson** [comment]
Is there maybe a setting or library I'm missing? There shouldn't be any on the 18.04LTS machine because I build QGC daily build on that from source. But it has both Qt 5.9 (distro version), and 5.11.1 in it (to build QGC.

**Comment by DonLakeFlyer** [comment]
To detail out the one case exactly:
* No network connection or SSL failures for query of terrain data
* Terrain height for Planned Home Position is **not** already in the terrain cache
* When you create a Plan the altitude for Planned Home Position will end up as NaN
* This will prevent you from uploading the Plan to the Vehicle

**Comment by DonLakeFlyer** [comment]
@antiheavy FYI

**Comment by DonLakeFlyer** [comment]
> Is there maybe a setting or library I'm missing?

It's a version problem with the SSL libs Qt wants. You should get console output from Qt about the failure.

**Comment by DonLakeFlyer** [comment]
@ChristopherOlson Can you enter a seperate Issue for the problems you are having with terrain query failing?

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I had a theory I had to check out. I'm on my Ubuntu 16.04LTS machine right now and I had QGC installed in ~/Documents/QGroundControl

I moved the installation to ~/QGroundControl, started it up and changed the setting for the path. Shut it down, restarted it, and voila! It got the terrain data instantly. I can't explain it. But when I get home I'm going to try this on the 18.04LTS machine and see if I get the same results.

**Comment by DonLakeFlyer** [comment]
> I'm on my Ubuntu 16.04LTS machine right now and I had QGC installed in ~/Documents/QGroundControl

That's very strange. No idea why that would cause a problem.

**Comment by DonLakeFlyer** [comment]
New daily builds with the fix should be up in about 1/2 hour.

**Comment by DonLakeFlyer** [comment]
Just marked Stable 3.4.3 which has this fix in it.
