### ISSUE TITLE
IOS build: why it's not updated ?

### ISSUE THREAD

**Issue by GlidLov** [mavlink/qgroundcontrol#6853]
Hi,

i see the IOS is not being updated like the other win/android versions. Currently, it's the only version with RTSP video streaming which is working properly (at least for me). May i ask why it's not updated to last versions?

**Comment by dogmaphobic** [comment]
Lack of time. Uploading the app to the App Store is still a manual process and it can take me half a day to get it there. It's in my to do list though...
