### ISSUE TITLE
Qgroundcontrol showing wrong Amps/Volt factor

### ISSUE THREAD

**Issue by mebj** [mavlink/qgroundcontrol#6877]
I calibrated the Amps/Volt factor (under Power Setup) and saved this. Then I had to change PC so I shut the drone down, opened QGC on a second PC and connected the drone again. 

Now, under Power Setup, the Amps/Volt factor shows a remarkably different value and this erroneous value became the base for any new calculation. 

To me it seems that under Power Setup the Amps/Volt factor was not set from the value stored on the drone, instead what showed up was the last calculated value on the currently connected computer.

This behaviour of course led to very odd power alarms because the Amps/Volt factor was totally wrong.

Versions of QGC were 3.4.0 on first computer and 3.4.3 on second. Problem was overcome by saving settings and restore them to second computer,

**Comment by DonLakeFlyer** [comment]
This values comes from a parameter on the vehicle. So the value would have been wrong on the vehicle.

> Problem was overcome by saving settings and restore them to second computer,

Saving what settings?

**Comment by mebj** [comment]
The parameter on the drone was OK but this never updated the value i QGC when switching to second PC. An old value from an an earlier calibration appeared there.
When I restored parameters earlier saved to a file then all values at QGC did update correctly as well.

**Comment by DonLakeFlyer** [comment]
QGC does not store parameter values anywhere. They are requested from the vehicle each time you connect. Hence the value shown in QGC will be whatever is on the vehicle.

The only possibility is that the original parameter change was not saved on the vehicle or possibly not sent to the vehicle. Then when you rebooted the vehicle and connected QGC again it still had the old value.

If you can reproduce it this way, then it is a real problem:
* Change amps/volt using QGC on one computer
* Shutdown QGC
* Retart QGC and connect on same computer. Verify that amps/volt is still what you set it to.
* Shutdown QGC
* Start QGC on another computer and connect to same vehicle. Verify that amps/volt is correct.

If anything goes wrong in that sequence then there is a bug somewhere and I will reopen. Possibly on the vehicle side.

**Comment by mebj** [comment]
I am aware that the values are stored on the flight controller and recalled. When trying to recall the sequence which occured I do think that the second computer may have had QGC running from an earlier session. 

I can guess that in such a case there is no new download from the drone when connecting again, QGC just continues on what is already internally stored even though there are updated parameters stored at the drone. Is that a possible explanation?

I will anyhow test this again.
Thank's a lot for taking the time to look at this.

**Comment by DonLakeFlyer** [comment]
> I can guess that in such a case there is no new download from the drone when connecting again, QGC just continues on what is already internally stored even though there are updated parameters stored at the drone. Is that a possible explanation?

Yes. If you didn't click Disconnect on the first computer. And then modified on the second computer. The first computer would be out of date.

**Comment by mebj** [comment]
I am sure a missing disconnect caused the problem. Without knowing I assumed that at any connect all the parameters were refreshed from the drone again.

Is it a bad idea to always refresh parameters upon reconnect?

Again, thank's for your assistance in finding what caused the problem.

**Comment by DonLakeFlyer** [comment]
> Is it a bad idea to always refresh parameters upon reconnect?

That is what QGC does. But when talking over a radio link QGC only knows when it loses heartbeat and then it pops "communication lost" and you need to click Disconnect yourself. This is because there is not way for QGC to know if this is a temporary communication loss. If a vehicle shows up again on that same link QGC thinks it's the same vehicle showing up again. Hence it's just a temporary comm lost as opposed to a vehicle reconnect scenario.

**Comment by mebj** [comment]
I only thought about the USB connection, did not think about the other possible scenario.
