### ISSUE TITLE
How to get tlog from iPad?

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6888]
On iOS. device ,I can not get tlog，could anyone tell me the way to get it ? Thanks

**Comment by hamishwillee** [comment]
If it isn't accessible from [Analyze > Log Download](https://docs.qgroundcontrol.com/en/analyze_view/log_download.html) then it probably is only possible to download logs from QGC on desktop builds. 

You can extract the memory card from the vehicle and read it on your computer.

**Comment by MyOnlyOnlySunshine** [comment]
yeah，but it's tlog or ulog ？

**Comment by hamishwillee** [comment]
It doesn't matter, since if the log download isn't supported it isn't supported.
If you're working on PX4 then a TLOG won't even be generated.

**Comment by DonLakeFlyer** [comment]
> If it isn't accessible from [Analyze > Log Download](https://docs.qgroundcontrol.com/en/analyze_view/log_download.html) then it probably is only possible to download logs from QGC on desktop builds.

That is correct. None of the Analyze options are available on Mobile builds. Some of them may show up at some point but not sure when (there is an issue feature request in for that already). That said, even if they did, on iOS downloading over a WiFi connection would take forever.

**Comment by MyOnlyOnlySunshine** [comment]
Thanks
