### ISSUE TITLE
ArduSub Safety page has some bad visual artifacts

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#6889]
See the text behind the "Safety Setup" heading:

![image](https://user-images.githubusercontent.com/5368500/46059041-ea9ebd80-c1a0-11e8-8392-2e8613979f81.png)

This is QGC 3.4.3 build on Ubuntu Linux 16.04 talking to ArduPilot master.

The missing params were also mentioned by QGC as a warning note when connecting

**Comment by DonLakeFlyer** [comment]
@jaxxzer Looks like Sub is not up to date with latest battery parameter name changes.

**Comment by jaxxzer** [comment]
On it.
