### ISSUE TITLE
Swarm + Lights 

### ISSUE THREAD

**Issue by mattyra** [mavlink/qgroundcontrol#6892]
Hey,

Im looking at how to control multiple drones on a set path for a light show using a wifi link, can we do this using QGC

Please use [the forums](http://discuss.px4.io/c/qgroundcontrol) for new feature requests. You can cross-link the thread in a new issue. However, due to the high amount of user feedback expect the QGC maintainer team to close feature requests that can't be implemented relatively quickly.

**Comment by DonLakeFlyer** [comment]
Issue are not the place to ask questions.
