### ISSUE TITLE
Mavlink version mismatch error on MacOS

### ISSUE THREAD

**Issue by asimonov** [mavlink/qgroundcontrol#6910]
- Ground station operating system: MACOS 10.13.6
- QGroundControl version and build: 3.4.3
- Autopilot board: Pixhawk 2.1
- Autopilot firmware (e.g. PX4, ArduPilot, custom): PX4 1.8.0
- Exact steps to reproduce the problem: use TELEM2 to connect to NUC via USB, start mavros node on on-board NUC computer with gcs_url parameter pointing to MAC_IP (UDP protocol, default port). 

BUG: See the "Detected radio still using Mavlink v1.0..." (message from https://github.com/mavlink/qgroundcontrol/blob/master/src/comm/MAVLinkProtocol.cc#L298) in qgc in rapid succession.

The only way to stop these spurious pop-ups is this is to kill QGroundCountrol.

I see in the code that the message should not 'stick', implemented by increasing the counter. But it is not what happens.

**Comment by DonLakeFlyer** [comment]
Can you turn on logging for MultiVehicleManager and attach the output here: https://docs.qgroundcontrol.com/en/SettingsView/console_logging.html

**Comment by asimonov** [comment]
hi! sorry for late reply. did not have chance to re-run it on Mac. 

but seen this happen on Ubuntu version of qgroundcontrol v3.3.2 today. 
version 3.2.7 does not seem to have this problem. 

will keep the logging on and report when this happens again

**Comment by asimonov** [comment]
[qgc-343-mavlink-error.txt](https://github.com/mavlink/qgroundcontrol/files/2469099/qgc-343-mavlink-error.txt)

![screen shot 2018-10-11 at 14 27 43](https://user-images.githubusercontent.com/240630/46807524-050c9580-cd62-11e8-9b42-c826b7aa7b29.png)
![screen shot 2018-10-11 at 14 27 52](https://user-images.githubusercontent.com/240630/46807534-0a69e000-cd62-11e8-8161-b049caec43c8.png)

**Comment by asimonov** [comment]
the above if from MacOS version

**Comment by asimonov** [comment]
just tried v3.2.7 and it definitely does not have this bug

**Comment by asimonov** [comment]
just built latest master on MacOS and it definitely has the problem described above
attaching the screenshot of what the message looks like
![screen shot 2018-10-11 at 14 57 46](https://user-images.githubusercontent.com/240630/46809378-3c7d4100-cd66-11e8-8515-8f720d209c83.png)

**Comment by DonLakeFlyer** [comment]
@asimonov Can you try building with this diff: 
[mavlink.diff.txt](https://github.com/mavlink/qgroundcontrol/files/2560146/mavlink.diff.txt)

I think the counter might be wrapping.

**Comment by asimonov** [comment]
unfortunately I have moved jobs, so do not have access to reproduce
