### ISSUE TITLE
Airframe Setup (Disabled while the vehicle is flying)

### ISSUE THREAD

**Issue by blevien** [mavlink/qgroundcontrol#6917]
Just flashed px4 FMUv5 and QGroundControl v3.4.4 on MacOS

Cannot choose airframe, calibrate sensors, calibrate radio or flight modes, always getting the message below eventhough vehicle is disarmed and on the ground.

I installed QGroundControl a few versions old and was able to configure.

Still having issues with Auto Missions rejected, but will file separately if it is not related to a configuration issue.

![screen shot 2018-10-09 at 10 35 00 am](https://user-images.githubusercontent.com/2374590/46696936-26795000-cbaf-11e8-8f8b-cf62aa109b5d.png)

**Comment by DonLakeFlyer** [comment]
What version of Firmware and can you get me a screenshot of the EXTENDED_SYS_STATE mavlink message from the mavlink inspector.

**Comment by Jetpackaviation** [comment]
It is happening to me as well. I am using px4fmu-v2_default for the hardware and QGC version 3.4 daily 10/26/18 daily build

**Comment by DonLakeFlyer** [comment]
> can you get me a screenshot of the EXTENDED_SYS_STATE mavlink message from the mavlink inspector.

Need this.

**Comment by DonLakeFlyer** [comment]
Can't do anything here without further information.

**Comment by masz106** [comment]
I have the same problem:
![grafik](https://user-images.githubusercontent.com/8720784/48249795-6aed4b00-e3fc-11e8-9f8d-cb0d78f4d9bf.png)
