### ISSUE TITLE
Param loading issue with new mRo Pixracer MAVESP8266 WiFi

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#6918]
We got new Pixracers from mRo and there's a problem with param loading via WiFi. The WiFi seems to come with a new Firmware (http://firmware.ardupilot.org/Tools/MAVESP8266/latest/), easily noticeable with the changed WiFi SSID named ArduPilot.

The parameters load and show up on the parameter tab, but the Airframe shows as unconfigured, even though it's set.
This error message shows up, even at the beginning of loading params (the green progress bar for param loading starts at the same time the error message pops up):
![qgc_pixracer_wifi_param_issue](https://user-images.githubusercontent.com/281593/46740518-54d85780-cca3-11e8-9a82-81e3b6922336.png)

I don't have this problem with an older MAVESP8266.
This is based off recent QGC master (around 6163ce95e3915edacb18bfc084d9285668266ba2).

Here are 2 QGC logs, the second one with the preflashed APM firmware (same issue):
[log.txt](https://github.com/mavlink/qgroundcontrol/files/2464902/log.txt)
[log_apm.txt](https://github.com/mavlink/qgroundcontrol/files/2464903/log_apm.txt)

**Comment by dagar** [comment]
Any ideas @dogmaphobic?

**Comment by dogmaphobic** [comment]
> Any ideas @dogmaphobic?

Not really, given that I've never heard of it. Where are the sources for this (ESP8266) firmware?

**Comment by dagar** [comment]
@pkocmoud FYI

**Comment by pkocmoud** [comment]
Thanks @dagar / Hi @dogmaphobic - I know Ardupilot has their own version of ESP01 firmware. I will test this out today.

**Comment by DonLakeFlyer** [comment]
It seems like somehow param load was reported as complete while it was still trying to load parameters. Can someone send me one of these and I can debug.

**Comment by pkocmoud** [comment]
They will be in the mail today. Thank you!

**Comment by DonLakeFlyer** [comment]
There is a bug in QGC with respect to multi-component parameter fetch: If all the subsidiary components finish parameter download prior to QGC getting a single parameter from the main/default component then it will think download is finished. The new ESP8266 firmware moves around the ordering of parameter fetch such that this shows up for the first time with the ESP8266.

**Comment by DonLakeFlyer** [comment]
While fixing this I discovered that the parameter editor is broken with respect to editing parameters from components other than the default component. I'll enter a separate issue on that. This won't be fixed on stable since it is too large a fix.
