### ISSUE TITLE
QGroundControl connection with ROS node

### ISSUE THREAD

**Issue by AfshinMr** [mavlink/qgroundcontrol#6919]
Is there any way to send the way-points from the QGC directly to a ROS node using the MAVROS package? 
Now, I can receive the way-points (that are sent by the QGC to the autopilot) by my ROS node using MAVROS! But I want to know if I can send the way-points to my ROS node directly and modify the way-points and then send them to the autopilot. If yes, Please explain me. 
I appreciate your answers.  
@Shokman

**Comment by DonLakeFlyer** [comment]
You should use an appropriate forum to ask questions like this. Then you'll get other users who may know the answer,.
