### ISSUE TITLE
Unable to reconnect to simulator

### ISSUE THREAD

**Issue by achambers16** [mavlink/qgroundcontrol#693]
OSX build from 2 June 2014

If I connect and then disconnect from the X-Plane 10 simulator, I cannot connect again.

Step to recreate:
1. In QGC, connect to Pixhawk and switch to Simulation view
2. Press Connect  to connect to the simulator under the HIL Config MAV 001 window. System confirms that it is in manual mode using HIL simulation.
3. Press disconnect for the HIL simulator in QGC. 

I get the audio message "Not switching off HIL. Safety" and a written message in QGC that says "REJECTING invalid hil state transition".

I cannot connect the the HIL simulation again. Only solution is to quit QGC and start it again.

**Comment by LorenzMeier** [comment]
Closing as stale.
