### ISSUE TITLE
I want to load a new parameter file

### ISSUE THREAD

**Issue by demiryalin** [mavlink/qgroundcontrol#6945]
Hi friends,
i am very newbie at QGroundControl and px4 things. I want to load a new parameter file to QGroundControl v3.4.4, which contains new parameters and new value of some parameters that are already exist. After i load this new parameter file to QGroundControl, i get errors about that some parameters don't exist. I am not sure if it is bug or not, but i cannot find it in internet what i am looking for. 
it would be very good if the new declared parameters would be generated automatically and the already  existed parameters would be overwritten with the new values.

**Comment by DonLakeFlyer** [comment]
This is a dup. I'll find it later.
