### ISSUE TITLE
EZ-wifibroadcast support for new Settings Feature

### ISSUE THREAD

**Issue by htcohio** [mavlink/qgroundcontrol#6954]
Hello,

First off, I love the new features on the app.  I recently switched from Tower to Q Ground Control and it has a lot of great functionality.

My question is, would you guys support the implementation of a settings tab specifically for EZ wifibroadcast?
EZ-wifibroadcast github page.
https://github.com/bortek/EZ-WifiBroadcast/wiki

The video and Telemetry stream work flawlessly with qgroundcontrol and we have a working app based on the FPV_VR app which allows synchronized setting changes for frequency and video settings. 

Here is a video demonstrating the layout of the settings.  If we were to implement code that could be integrated with qgroundcontrol, would you consider merging it with the main so that the functionality would be available on ios and android?  At the moment, video/telemetry and settings can only be accessed or changed with 2 separate apps.  It would be a tremendous advantage to have video, Telemetry and settings combined with your qgc.  It would be an ideal all-in-one HD GCS solution.

https://youtu.be/cLuNi1d_bMo

Here is a video of qgroundcontrol with wfb video and Telemetry.
https://youtu.be/pD5k5h0G8SI

Thanks!

**Comment by DonLakeFlyer** [comment]
At some point possibly if user demand gets high enough. But for now the best solution is for components which haven't reached that demand level to expose settings as parameters which can be changed from the standard parameter editor.
