### ISSUE TITLE
Can QGC be deployed to a remote server on the web?

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6967]
Hello，Can QGC be deployed to a remote server on the web? We want to use qgc from web instead of application. Can this be achieved?  Thanks

**Comment by MyOnlyOnlySunshine** [comment]
Just like  flight review

**Comment by DonLakeFlyer** [comment]
No

**Comment by MyOnlyOnlySunshine** [comment]
Thanks
