### ISSUE TITLE
Show all ArduPilot flight modes for Rover and Boat

### ISSUE THREAD

**Issue by rmackay9** [mavlink/qgroundcontrol#6968]
A user of QGC with ArduPilot's Rover (or Boat) firmware has noticed that not all of the flight modes are available.  QGC's list seems to be out of date for some reason.

I suppose it's possible that there is a discrepancy in the mavlink files..

**Comment by DonLakeFlyer** [comment]
Unfortunately flight modes are a hard coded thing. Hence whenever new ones are added gcs needs to change.
