### ISSUE TITLE
ADSBVehicle flag check problem

### ISSUE THREAD

**Issue by zoltanpillio** [mavlink/qgroundcontrol#6977]
I found in the source code that there is a bug how mavlink_adsb_vehicle_t.flag is checked in src/Vehicle/ADSBVehicle.cc. E.g.: `adsbVehicle.flags | ADSB_FLAGS_VALID_COORDS` has to be `adsbVehicle.flags & ADSB_FLAGS_VALID_COORDS`.

These are the problematic lines I found:
https://github.com/mavlink/qgroundcontrol/blob/77a65e6005412b61cb0b7b59aefe1e9d01be2261/src/Vehicle/ADSBVehicle.cc#L23
https://github.com/mavlink/qgroundcontrol/blob/77a65e6005412b61cb0b7b59aefe1e9d01be2261/src/Vehicle/ADSBVehicle.cc#L58
https://github.com/mavlink/qgroundcontrol/blob/77a65e6005412b61cb0b7b59aefe1e9d01be2261/src/Vehicle/ADSBVehicle.cc#L76
https://github.com/mavlink/qgroundcontrol/blob/77a65e6005412b61cb0b7b59aefe1e9d01be2261/src/Vehicle/ADSBVehicle.cc#L85

**Comment by DonLakeFlyer** [comment]
Yup thanks

**Comment by zoltanpillio** [comment]
I'm sorry I did it in this way, and not created a pull request, but I'm really busy now, and that was the easiest way.

**Comment by DonLakeFlyer** [comment]
No problem. Thanks for the bug report.
