### ISSUE TITLE
Guided settings not visible

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#6980]
On PX4 SITL VTOL (at least) the guided settings group is not visible
Therefor there is no way to change the min/max altitude for altitude change commands

/cc @dagar @DonLakeFlyer

**Comment by DonLakeFlyer** [comment]
Not sure what you are talking about? Parameters?

**Comment by sanderux** [comment]
https://github.com/mavlink/qgroundcontrol/blob/master/src/Settings/GuidedSettings.cc

**Comment by sanderux** [comment]
![image](https://user-images.githubusercontent.com/14801663/47889551-d3f82000-de4a-11e8-858a-1ebe328f20fa.png)

**Comment by DonLakeFlyer** [comment]
Ah, I had completely forgotten about those. They aren't exposed anywhere.
