### ISSUE TITLE
can not compile qgc on 5.9.7, Is there  something wrong ?

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [mavlink/qgroundcontrol#6989]
Hello, we are doing secondary development of qgc, the project compiles the iOS version in qt5.7.1 normally, but on 5.9.7, it can compile normally, but after the completion of the compilation, it stops directly here, and then reports the following error, may I ask this? What caused it, thank you!

<img width="1104" alt="2018-11-07 5 38 04" src="https://user-images.githubusercontent.com/17830375/48123165-35d5e100-e2b4-11e8-806a-22afe9361a43.png">

**Comment by DonLakeFlyer** [comment]
If you've modified the QGC code then it could be just about anything. We can't help debug custom code.
