### ISSUE TITLE
Make serial rate requests optional

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#7014]
QGC is setting datarates at two places:

https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/APM/APMFirmwarePlugin.cc#L590
https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/APM/ArduSubFirmwarePlugin.cc#L172

Doing so on slow links (apparently Dragonlink or Iridium) would saturate the link. 
Arduplanner does send some telemetry by default, dictated by the SR*_ parameters, in case it does not , it may be convenient for the user to have an alternative way to set them:

 I suggest that these functions are never called automatically, but placed in [Applicaterion settings]->[Comm Links]  as a button , "request telemetry at preset rates"  - or: see what APMPlanner2 does,:
![screenshot from 2018-11-16 23-09-16](https://user-images.githubusercontent.com/1468842/48650345-029efa80-e9f6-11e8-9f65-fe41d2a8334e.png)

**Comment by DonLakeFlyer** [comment]
Still could use configurable rates
