### ISSUE TITLE
rover flying flag

### ISSUE THREAD

**Issue by masz106** [mavlink/qgroundcontrol#7021]
QGC 3.4.4
FW:Rover 1.8.1
Pixhawk 4

Sensor Setup (Disabled while the vehicle is flying)
No setup possible
extended_sys_state: vtol_state 0   landed_state 2

**Comment by DonLakeFlyer** [comment]
The point is to disallow some parts of setup while the Rover is actively doing something. Can you create an Issue on firmware side and add me and then I'll talk through what QGC does there.

**Comment by masz106** [comment]
But it works with the Mission Planner 1.3.59

**Comment by DonLakeFlyer** [comment]
Mission Planner and QGC are very different things and haev very different UI support.

**Comment by DonLakeFlyer** [comment]
This needs to move to a discussion on the Firmware side as to how to handle Rover sending MAV_LANDED_STATE_IN_AIR at appropriate times.
