### ISSUE TITLE
QGC does not load the latest px4 Firmware (1.8.2)

### ISSUE THREAD

**Issue by jstrebel** [mavlink/qgroundcontrol#7044]
Hi, If I try to flash the latest released px4 software 1.8.2 QGC flashes 1.81.
Required px4 firmware is: px4fmu-v2
I use QGC 3.4.4
Jakob

**Comment by Williangalvani** [comment]
This might be related to this:
https://github.com/PX4/Firmware/issues/10625

**Comment by DonLakeFlyer** [comment]
This is a firmware build bug.

**Comment by tecdee** [comment]
I have the same issue. I have not been able to log data to sd card. So I did a quick search and found recommendations to update to latest firmware. But QGC loads 1.8.1 still. 

Please how do I solve this issue? Thanks
