### ISSUE TITLE
Builds but does not run on Windows 10

### ISSUE THREAD

**Issue by kossumov** [mavlink/qgroundcontrol#7046]
I'm on Windows 10 x64
- I've installed: 
  - Qt Creator, 
  - Visual Studio 2015 (with c++ compilers), 
  - Windows SDK
- Cloned the project
- Did everything according to https://dev.qgroundcontrol.com/en/getting_started/

Builds fine
Now, I want to run the project

## Expected Behavior
Runs fine and I see qgroundcontroll UI

## Current Behavior
Crashes  (doesn't run)
Error in C:\Qt\5.11.0\msvc2015\include\QtCore\qobject.h (line 250)

## Steps to Reproduce:
1. Take a clean computer with Windows 10
2. Do everything according to https://dev.qgroundcontrol.com/en/getting_started/
3. Build the project
4. Run the project

## System Information
- Operating System: Windows 10
- QGC Version: 3.4.4
- QGC build: self-built from source

## Detailed Description
Here is a screenshot
![untitled](https://user-images.githubusercontent.com/8853887/49245944-c8d1e900-f424-11e8-95c0-2860a7db79a4.png)

## Log Files and Screenshots
Here is a dump file: 
https://drive.google.com/file/d/1YFJ6XHGyes1ZtMxnDMhIa3xmLB-znMva/view?usp=sharing

## Extra
I have tried to build and run QGC on 3 different machines with Windows 10. All of them have the same issue

**Comment by DonLakeFlyer** [comment]
I think this and #7032 are the same bug.

**Comment by dogmaphobic** [comment]
I've seen this several times on Windows only. It happens immediately on boot when creating a `Fact`. I haven't been able to figure out where it's coming from and it doesn't happen every time.

**Comment by kossumov** [comment]
Tried on 3 different machines. Many times. 
Happens every time

**Comment by kossumov** [comment]
The last commit by @DonLakeFlyer fixed the problem.
Thanks ;)

**Comment by DonLakeFlyer** [comment]
@kossumov Thanks for the detailed report.
