### ISSUE TITLE
Instrument panel on Fly Screen lost process to configure

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#7050]
Gear icon to setup values on Instrument panel disappeared, so unable to configure it

latest build of QGC on MacOS 10.14

<img width="972" alt="screenshot 2018-11-30 at 09 19 14" src="https://user-images.githubusercontent.com/3130363/49280684-b7b7c500-f482-11e8-8fb8-d9e13f6a3866.png">

**Comment by DonLakeFlyer** [comment]
It's still there just now drawing correctly for some strange reason.
