### ISSUE TITLE
periodic resets and QGC relinks to FC and lands back on the Setup summary page

### ISSUE THREAD

**Issue by dlarue** [mavlink/qgroundcontrol#7062]
Kubuntu 18.04.1  daily build appimage

Running QGC in the nav window and about 5 times over 30 minutes it looks like there's a mixup on the link and then QGC will resync connectivity( progress bar goes across the top like on startup ) and it'll land back on the default Setup page showing the Summary.

Terminal window only shows these lines each time:

Temp log "/tmp/FlightData627217.mavlink749869"
qrc:/qml/APMSafetyComponentSummary.qml:54: TypeError: Cannot read property 'enumStringValue' of null
qrc:/qml/APMSafetyComponentSummary.qml:128: TypeError: Cannot read property 'value' of null
qrc:/qml/APMSafetyComponentSummary.qml:136: TypeError: Cannot read property 'value' of null

**Comment by DonLakeFlyer** [comment]
What kind of connection are you using? Sounds like it is full disconnecting from the Vehicle and then reconnecting instead of just going into a comm lost state and then coming back.

**Comment by DonLakeFlyer** [comment]
Use console logging for LinkManagerLog (https://docs.qgroundcontrol.com/en/SettingsView/console_logging.html) and it will tell you whether the USB connection is really dropping in and out from a hardware perspective.

**Comment by dlarue** [comment]
I deleted the INI file even thought there was not ttyACM1 reference and now it will load to completion and show the settings page.  I see repeated restarts and saved the log. will investigate when I get back.

**Comment by dlarue** [comment]
[gqc-applog2.log](https://github.com/mavlink/qgroundcontrol/files/2650724/gqc-applog2.log)

**Comment by dlarue** [comment]
without anything running, ttyACM0 is created when the FC is plugged in and starts flashing the blue LED. But when the flashing LED stops, ttyACM0 is dropped and ttyACM1 is created.  Something seems up with the firmware but it doesn't seem to glitch after the shift to ttyACM1 but I will keep monitoring.  I will start ROS and see if it resets any more or less dealing with MAVROS/MavLink messaging.

**Comment by DonLakeFlyer** [comment]
I would talk with the firmware folks. Doesn't look like anything QGC is in control of is going wrong here. The repeated "Skipping existing autoconnect" is normal behavior since it is already connected to ttyACM1.
