### ISSUE TITLE
Can't find serial config in parameters list

### ISSUE THREAD

**Issue by bys1123** [mavlink/qgroundcontrol#7075]
I'm trying enable GPS2 follow this link
https://docs.px4.io/en/peripherals/serial_configuration.html
but can't find serial tab

Firmware: PX4 1.8.1
QGC: 3.4.4

![image](https://user-images.githubusercontent.com/4748411/49687318-388a5700-fb3c-11e8-9f9b-b870501029ad.png)

**Comment by DonLakeFlyer** [comment]
You'll have to ask the firmware folks about that.

**Comment by hamishwillee** [comment]
This PARAM is in master, but not 1.8.1 or 2. The docs reflect master, not a particular version. We're hoping to have versioned builds of the docs in the near future, which will fix this sort of problem.
