### ISSUE TITLE
Goto point and Orbit circle stay on cancel

### ISSUE THREAD

**Issue by MaEtUgR** [mavlink/qgroundcontrol#7093]
Version: QGC Daily https://github.com/mavlink/qgroundcontrol/commit/5e63260bd4b40f66d433ac62b2f6d55e4de6d136

To reproduce:
1. Takeoff
1. As soon as the drone is in Hold mode press on the map
1. Choose to do a goto or an orbit
1. Cancel with the cross above the slider
1. **The planned goto point or movable circle stays present on the map until the next goto/orbit is invoked.**

<img width="808" alt="goto_bug" src="https://user-images.githubusercontent.com/4668506/50081622-3d5fa280-01ef-11e9-89fb-e30e02afd114.PNG">

**Comment by Antiheavy** [comment]
old related issue: https://github.com/mavlink/qgroundcontrol/issues/6720

**Comment by DonLakeFlyer** [comment]
Closing this one to keep #6720.

**Comment by MaEtUgR** [comment]
👍
