### ISSUE TITLE
LAND command triggers unintended RTL on arducopter 3.6.3 and earlier

### ISSUE THREAD

**Issue by maciek01** [mavlink/qgroundcontrol#7098]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

## Expected Behavior
Please tell us what should happen as detailed as possible.

LAND waypoint (the last one in a mission) should land copter in the specified position (in the waypoint). The mission is NOT setup for RTL at the end.

## Current Behavior
Please describe what happens instead of the expected behavior.

copter instead ignores the last LAND sommand, switches to RTL mode and goes back to home and lands. I use FLIGHTDECK sofrtware on TARANIS so i can tell from the TARANIS that copter switched to RTL.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior

1. upodate frimware with arducopter 3.6.3
1. create a non-RTL mission with LAND as last step and upload
1. Start the mission
1. Observe copter execute all steps of the mission ignoring the last (LAND) one and going back to RTL.

## System Information
When posting bug reports, include the following information

* Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]

uname -a
Darwin us-gn-51034 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov 2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

* QGC Version: [e.g. 3.4.4]

3.4.4

* QGC build: [e.g., daily, stable, self-built from source, etc...]

stable

* Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]

Cube black - (pixhawk 2.1)

* Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

Arducopter 3.6.3 - symptoms observed also on 3.6.2 and earlier.

## Detailed Description
Provide further details about your issue/bug.

The issue does not happen on MIssion Planned designed and uploaded missions.
So i expect something wrong with the way QGC missions are submitted to arucopter firmwares.

will include mission plan

## Log Files and Screenshots

* [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
* Autopilot logs when available (post a link).
* Screenshots of QGC to help identify the current issue/bug behavior.

{
 "fileType": "Plan",
 "geoFence": {
 "circles": [
 ],
 "polygons": [
 ],
 "version": 2
 },
 "groundStation": "QGroundControl",
 "mission": {
 "cruiseSpeed": 15,
 "firmwareType": 12,
 "hoverSpeed": 5,
 "items": [
 {
 "autoContinue": true,
 "command": 178,
 "doJumpId": 1,
 "frame": 2,
 "params": [
 1,
 15,
 -1,
 0,
 0,
 0,
 0
 ],
 "type": "SimpleItem"
 },
 {
 "AMSLAltAboveTerrain": 107,
 "Altitude": 50,
 "AltitudeMode": 2,
 "autoContinue": true,
 "command": 22,
 "doJumpId": 2,
 "frame": 0,
 "params": [
 15,
 0,
 0,
 null,
 42.53025961267092,
 -71.18843363002793,
 107
 ],
 "type": "SimpleItem"
 },
 {
 "AMSLAltAboveTerrain": 111,
 "Altitude": 50,
 "AltitudeMode": 2,
 "autoContinue": true,
 "command": 16,
 "doJumpId": 3,
 "frame": 0,
 "params": [
 0,
 0,
 0,
 null,
 42.529383975539865,
 -71.18710058529803,
 111
 ],
 "type": "SimpleItem"
 },
 {
 "AMSLAltAboveTerrain": 108,
 "Altitude": 50,
 "AltitudeMode": 2,
 "autoContinue": true,
 "command": 16,
 "doJumpId": 4,
 "frame": 0,
 "params": [
 0,
 0,
 0,
 null,
 42.53011445124338,
 -71.18809077188926,
 108
 ],
 "type": "SimpleItem"
 },
 {
 "AMSLAltAboveTerrain": null,
 "Altitude": 0,
 "AltitudeMode": 0,
 "autoContinue": true,
 "command": 21,
 "doJumpId": 5,
 "frame": 3,
 "params": [
 25,
 0,
 0,
 null,
 42.530187023810726,
 -71.1880863711289,
 0
 ],
 "type": "SimpleItem"
 }
 ],
 "plannedHomePosition": [
 42.530332817113575,
 -71.18843696938863,
 57
 ],
 "vehicleType": 2,
 "version": 2
 },
 "rallyPoints": {
 "points": [
 ],
 "version": 2
 },
 "version": 1
}

**Comment by maciek01** [comment]
[log_1_2018-12-22-11-31-52.bin.log](https://github.com/mavlink/qgroundcontrol/files/2706078/log_1_2018-12-22-11-31-52.bin.log)

**Comment by DonLakeFlyer** [comment]
I'm not seeing anything wrong with that Plan or the fields of the LAND item. When you load it back from the vehicle does the LAND item come back with correct values? If that looks ok, then this looks like a firmware problem with the LAND command.

**Comment by maciek01** [comment]
when i load it back from the vehicle the mission looks exactly as designed.
The only reason i  say this might not be the firmware problem is that a mission designed in MP with exact same sequence executes as expected, i.e. LAND is executed and the vehicle does not change mode to RTL.

**Comment by DonLakeFlyer** [comment]
Can you save that same mission from MP and attach here?

**Comment by maciek01** [comment]
i will - not earlier than jan 3rd, as my kid left my personal laptop (with all my mission files) at school. All i have is my clean work mac with only QGC on it.

**Comment by maciek01** [comment]
[foxhilland.txt](https://github.com/mavlink/qgroundcontrol/files/2713346/foxhilland.txt)


here is an APM 2.0 mission that lands as expected at designate position.

**Comment by maciek01** [comment]
work as expected - log attached - i ran it a few times. The last run is probably the cleanest.
[log_0_2018-12-31-14-50-26.bin.txt](https://github.com/mavlink/qgroundcontrol/files/2718864/log_0_2018-12-31-14-50-26.bin.txt)

**Comment by DonLakeFlyer** [comment]
Great, thanks. I'll fix this up.

**Comment by DonLakeFlyer** [comment]
@maciek01 Could you verify the fix in tomorrow's daily?

**Comment by maciek01** [comment]
i will.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Thanks for pointing out https://github.com/mavlink/qgroundcontrol/issues/7098#issuecomment-452104308 . Let's fix in https://github.com/mavlink/mavlink/pull/1054.

Note that creating an issue in mavlink/mavlink is a more reliable way of making sure I don't miss things.

**Comment by maciek01** [comment]
> @maciek01 Could you verify the fix in tomorrow's daily?

@DonLakeFlyer tested - works as expected.

Side note - the mission wasn't holding altitude well. copter was climbing during leg then descending back to requested alt after arriving at WP. This may be firmware related.
