### ISSUE TITLE
landing pattern graphics not showing up in Fly screen in recent Daily build

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7107]
Plan screen:
![image](https://user-images.githubusercontent.com/12117027/50541578-75ab9d00-0b6e-11e9-8a88-5b676f82c45a.png)

Fly screen:  (I think the landing loiter graphics are supposed to be showing up?)
![image](https://user-images.githubusercontent.com/12117027/50541583-8cea8a80-0b6e-11e9-8cb7-8876226771e7.png)

**Comment by Antiheavy** [comment]
Hmmmm. This seems intermittent. I’ll try to find a reproducible order of operations.

**Comment by DonLakeFlyer** [comment]
Code inspection didn't find anything. Could possibly be related to "Stop taking photos/videos" settings which are the newest changes.

**Comment by Antiheavy** [comment]
i tried a couple times and couldn't figure out how to reproduce.

**Comment by DonLakeFlyer** [comment]
Ok, bummer

**Comment by Antiheavy** [comment]
thinking back on it I wonder if I was changing QGC and Firmware SITL versions and ran into an inconsistency.  When I tried to repo with normal QGC and normal Firmware I couldn't.
