### ISSUE TITLE
Problem install on Android 

### ISSUE THREAD

**Issue by yeechongyeung** [mavlink/qgroundcontrol#7147]
## System Information
When posting bug reports, include the following information
- Operating System: [ Windows 10, Qt5.11.0   for Android  ]
- QGC Version: [lastest]
- QGC build: [ self-built from source]

## Detailed Description
after install the compile result apk, only show the logo window, and white block.  

## Log Files and Screenshots
![buildforandroid](https://user-images.githubusercontent.com/20177799/51306868-4a371680-1a79-11e9-8d85-0c4cd5ce4470.PNG)

W QGroundControl: (null):0 ((null)): QQmlApplicationEngine failed to load component
W QGroundControl: (null):0 ((null)): qrc:/qml/MainWindowNative.qml:12 module "QtQuick.Window" is not installed
W QGroundControl: qrc:/qml/MainWindowNative.qml:13 module "QtQuick.Dialogs" is not installed
W QGroundControl: qrc:/qml/MainWindowNative.qml:12 module "QtQuick.Window" is not installed
W QGroundControl: qrc:/qml/MainWindowNative.qml:13 module "QtQuick.Dialogs" is not installed

**Comment by DonLakeFlyer** [comment]
This could be just about anything. First step is I would try to build/install android examples from Qt using your setup.

**Comment by DonLakeFlyer** [comment]
My other comment would be that I haven't heard anyone get android builds to work on Windows yet. QGC devs for android is mostly done in OSX. And the CI build system uses Linux to build.
