### ISSUE TITLE
The android project won't build

### ISSUE THREAD

**Issue by Nodjo** [mavlink/qgroundcontrol#7150]
Hi,

I need to compile the Android ground control app and I'm totally new to qt.

I'm struggling and can't get the project to compile.

I'm running Ubuntu 18.04.1 LTS, I've followed the installation steps described here (https://dev.qgroundcontrol.com/en/getting_started/) and here (http://doc.qt.io/qt-5/android-getting-started.html). My computer was already set up for Android development as this is what I usually do with it, using Android Studio.

I can't get the two android projects to compile (as a matter of fact, I can't compile the Desktop project either, but I don't think I need that one). When using the latest NDK, I've got qt complaining right away about a file that it can't find inside the NDK. I've tried to set the environment variables CC and CXX as described here (https://developer.android.com/ndk/guides/standalone_toolchain#working_with_clang) with no luck.

I assume I've missed a step in the setup, which is what is suggested in the error message, but I can't find what it is. Any help would be greatly appreciated.

Thank you!

Branch: Stable_V3.4

Project: Android for x86
sh: 1: /home/nodjo/dev/android-sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++: not found
Project ERROR: Cannot run target compiler '/home/nodjo/dev/android-sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++'. Output:
===================
sh: 1: /home/nodjo/dev/android-sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++: not found
===================
Maybe you forgot to setup the environment?

Project: Android for armeabi-v7a
sh: 1: /home/nodjo/dev/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++: not found
Project ERROR: Cannot run target compiler '/home/nodjo/dev/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++'. Output:
===================
sh: 1: /home/nodjo/dev/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++: not found
===================
Maybe you forgot to setup the environment?

(BTW, at some point I also tried to compile using NDK version r10e and the code did compile (with warning) but in the end, it said no apk file had been built as an android .pro file was missing and I couldn't fix that error either)

Project: Desktop Qt 5.11.0 GCC 64bit

Tons of warning, and this error:

RCC: Error in '/home/nodjo/dev/git/qgroundcontrol/qgroundcontrol_qmlcache.qrc': Cannot find file 'src/Settings/FlyView.SettingsGroup.json'
Makefile:3225: recipe for target 'rcc/qrc_qgroundcontrol_qmlcache.cpp' failed
make: *** [rcc/qrc_qgroundcontrol_qmlcache.cpp] Error 1
make: *** Waiting for unfinished jobs....
18:56:56: Le processus "/usr/bin/make" s'est terminé avec le code 2.

**Comment by DonLakeFlyer** [comment]
Look at .travis.yml to see what version an andoird linux things QGC uses. In general getting android to build takes a lot of tweaking of things and internet searching for solutions.
