### ISSUE TITLE
Allow to flash last uploaded firmware directly from hlash side menu

### ISSUE THREAD

**Issue by roman-dvorak** [mavlink/qgroundcontrol#7179]
Autopilot firmware development workflow could be speeded up with the button in flash menu, that would automatically upload last used (custom) firmware. Choosing firmware in a not well-done file browser is so slow.

**Comment by DonLakeFlyer** [comment]
Interesting but custom firmware flash is a rarely use feature. Also we don't have any control over the file brower code in order to make it any faster. Not something I think we would ever get around to doing.
