### ISSUE TITLE
RTL in Mission End causes the vehicle to go away from home position and crash.

### ISSUE THREAD

**Issue by tanazj** [mavlink/qgroundcontrol#7191]
Issue details
selecting RTL in Mission End causes the vehicle to go back to home position, change altitude to 15 m and then decreases altitude while goes away from home position and then crashes

i run sitl arducopter_iris_demo.
vehicle info: ardupilot multi-rotor.
firmware version 3.6.0dev

**Comment by DonLakeFlyer** [comment]
QGC doesn't have any control over what the MAV_CMD_NAV_RETURN_TO_LAUNCH command actually does with the vehicle. You should report this to the firmware folks. Include the flight plan as well as telemetry and/or vehicle logs if possible.
