### ISSUE TITLE
RTSP video stream option is not showing in build but shows in installed QGC

### ISSUE THREAD

**Issue by Rhonins** [mavlink/qgroundcontrol#7211]
Hi,
When I am running the QGC I have installed with setup, RTSP video stream is popping in video stream options. I can see my video stream.
[https://imgur.com/a/A5DILvt](http://url)

But when I run my own build Taisync option pops-up and RTSP video stream is not showing in drop down menu. Also I am not able to see rtsp video stream under TaiSync.
[https://imgur.com/a/lAzrNgd](http://url)
[https://imgur.com/a/pr1KoRY](http://url)
Is that a bug?
or
How can I figure that out?

**Comment by dogmaphobic** [comment]
None of the images above are working. Just place them directly to the issue instead of a link.

I'm not sure I fully understand the problems you are having. Keep in mind that when you enable Taisync, video streaming is handled automatically. That's why the video stream settings are not available.

**Comment by roseyangyu** [comment]
I have same issues

**Comment by roseyangyu** [comment]
![default](https://user-images.githubusercontent.com/40378941/53385835-cf87e200-39ba-11e9-8f6d-5322da956c65.png)
this is QGC.AppImage download from https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html. RTSP video stream is popping in video stream options. But I have build that with same version.It only has video stream disabled and easycamera.
![default](https://user-images.githubusercontent.com/40378941/53389488-745deb80-39ca-11e9-8331-d56ccb98dc77.png)
Please help me to kown this is bug or errors during me buildding

**Comment by dogmaphobic** [comment]
You don't have GStreamer installed.

**Comment by roseyangyu** [comment]
thanks for your advice.I should install GStreamer [follow here](https://github.com/mavlink/qgroundcontrol/tree/master/src/VideoStreaming)

**Comment by NejatRmz** [comment]
I have followed the instructions [here](https://github.com/mavlink/qgroundcontrol/tree/master/src/VideoStreaming). When i run the code it works fine for windows but in the android build i get only "No Video Available" option. you can see capture [here](https://imgur.com/Ji3IUjs)

**Comment by Sathiyanarayanan18** [comment]
Iam Also facing Same Issue, Can you please help to solve this issue

**Comment by bismahA** [comment]
Same issue
Did someone find any solution?

**Comment by orca741** [comment]
Same issue!
Please advice
