### ISSUE TITLE
Add option to select language

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#7217]
QGC currently sets the language based on what the OS reports. There is no way for the user to select a different language. A user might have the OS set to their native language but would prefer QGC in English (or some other combination).

QGC should ask the user what language to use (on first boot) and also provide an option to change within its settings.

**Comment by dogmaphobic** [comment]
This is now in master.

**Comment by evexoio** [comment]
@dogmaphobic I just installed qgroundcontrol v3.5.0 and I got turkish as a default language,
I'm in turkey but I don't have turkish as system language, and none of my keyboard layouts are turkish as well.

I can't find an option to change the language to english.

Where can I find the language option?

**Comment by dogmaphobic** [comment]
It's on the daily builds: https://github.com/mavlink/qgroundcontrol/pull/7300

**Comment by evexoio** [comment]
@dogmaphobic I just went to the settings and searched for it as in the screenshot on the PR, couldn't find the language setting...

![Screen Shot 2019-04-10 at 4 46 07 PM](https://user-images.githubusercontent.com/12014839/55884187-474b4e00-5bb0-11e9-87df-77cb54d9627b.png)

**Comment by dogmaphobic** [comment]
>It's on the daily builds

You are running the _stable_ build.

**Comment by zhangxh2000** [comment]
> This is now in master.

I used the latest Master，but when I change to another language,nothing happened, and I found this log "QGCApplication.cc:437-"Error loading Qt localication for "zh_CN“",I builded the QGC myself，Does I missed something when building?

**Comment by datwwe** [comment]
> > This is now in master.
> 
> I used the latest Master，but when I change to another language,nothing happened, and I found this log "QGCApplication.cc:437-"Error loading Qt localication for "zh_CN“",I builded the QGC myself，Does I missed something when building?

Is your problem solved yet? I'm having just the same problem when build QGC by Qt5.6.12. Thanks for your reply!
