### ISSUE TITLE
QGC thinks vehicle is "flying" and won't allow sensor setup

### ISSUE THREAD

**Issue by zlite** [mavlink/qgroundcontrol#7238]
QGC won't allow sensor setup because it thinks vehicle is already "flying".  All other setup options are likewise disabled, including ability to switch to a different vehicle type. Connecting and disconnecting makes no difference, nor does closing and restarting QGC. 

As you can see in the screenshot, the vehicle is disarmed, so it can't be in motion. Nevertheless QGC thinks it's flying (I guess that should be "moving", since rovers don't fly)
![capture](https://user-images.githubusercontent.com/18071/52974276-cfae2f00-3375-11e9-832e-23b2eae162c1.PNG)

Tested on Windows, QGC 3.4, Rover vehicle type , Pixhawk 4

**Comment by DonLakeFlyer** [comment]
Fixed in 3.5
