### ISSUE TITLE
Why  the compiled software does not has " udp video stream"?

### ISSUE THREAD

**Issue by dayhee** [mavlink/qgroundcontrol#7242]
Hi， i am using source code to build a apk for android,  but the builded apk has a problem , In general ->video-> video source ,there doesn't has the choose ''UDP Video Stream '', but the apk which is download with google play  has this choose, and both these is v3.4.4. I don't know why

**Comment by DonLakeFlyer** [comment]
Follow the instructions for installing gstreamer on android: https://github.com/mavlink/qgroundcontrol/tree/master/src/VideoStreaming
