### ISSUE TITLE
Plan is waiting on terrain data endlessly

### ISSUE THREAD

**Issue by nsteele** [mavlink/qgroundcontrol#7249]
## Expected Behavior
Successful upload of missions where the waypoints' altitudes are specified "Above Terrain"

## Current Behavior
When clicking "Upload Required", I see "Unable to Save/Upload ... Plan is waiting on terrain data from server for correct altitude values"

## Steps to Reproduce:

1. Open QGroundControl with "UDP" as chosen in the "AutoConnect to the following devices" section of the "General" application settings.
2. In a shell, navigate to the px4 firmware workspace and run the following
```
export PX4_HOME_LAT=40.44977
export PX4_HOME_LON=-79.8999
make px4_sitl_default jmavsim
```

3. Once QGroundControl connects to the simulation, plan a waypoint mission where at least one of the waypoints' altitudes is specified as "Above Terrain"

4. Click "Upload Required"

## System Information
- Operating System: Ubuntu 18.04
- QGC Version: v3.5.5
- QGC build: stable
- Flight Controller: px4 jmavsim simulation
- Autopilot (with version): PX4 1.8.0

## Log Files and Screenshots

Here is an example waypoint with altitude specified "Above Terrain"
![screenshot from 2019-02-25 14-32-55](https://user-images.githubusercontent.com/1399452/53363460-84ae9180-390a-11e9-99a2-39b1d409a550.png)

Here is the error message
![screenshot from 2019-02-25 14-32-37](https://user-images.githubusercontent.com/1399452/53363463-8710eb80-390a-11e9-9391-5bcb9d749944.png)

Here is the QGC console log. It keeps printing the same thing.

![screenshot from 2019-02-25 14-33-27](https://user-images.githubusercontent.com/1399452/53363466-8b3d0900-390a-11e9-8ee0-c24d21f1f782.png)

**Comment by DonLakeFlyer** [comment]
Looks like some sort of AirMap problem...

**Comment by nsteele** [comment]
Is there anyway to confirm this is an AirMap problem? I'd be satisfied closing this if that were the case. I'm wondering if the QGC url or token or something is incorrect.

As a workaround for me, is there a facility in QGC for using a different terrain map server?

**Comment by DonLakeFlyer** [comment]
> Is there anyway to confirm this is an AirMap problem?

Working on it. Don't close the issue. You can't use a different terrain server.

**Comment by DonLakeFlyer** [comment]
AirMap is figure out how to fix it.

**Comment by kikislater** [comment]
Agree with @nsteele : Airmap is crap and does not help drone industry... Making money with non requiring authorisation !!! 
Why choosing this platform ? And Airmap uses SRTM90 which is not accurate. SRTM30 is now available.

**Comment by DonLakeFlyer** [comment]
@kikislater You are certainly welcome to submit a pull request to QGC to add support for any terrain sever you would like.

**Comment by kikislater** [comment]
Or forking the project

**Comment by nsteele** [comment]
Do I need to set an API key and Client ID in the AirMap section of the Application Settings to enable waypoints with altitudes relative to terrain?

<img width="1552" alt="screen shot 2019-02-26 at 3 41 01 pm" src="https://user-images.githubusercontent.com/1399452/53444845-34ecca80-39dd-11e9-9da1-28097b63326b.png">

**Comment by dogmaphobic** [comment]
> Do I need to set an API key and Client ID in the AirMap section of the Application Settings to enable waypoints with altitudes relative to terrain?

No, that's for something else. The elevation API didn't require any authentication. Airmap shutdown that (open) API and we are waiting for them to tell us how to access it.

**Comment by DonLakeFlyer** [comment]
Unless something goes horribly wrong AirMap will turn the support back on. There was a misunderstanding as to what api we were using for what in QGC. Hopfully won't take too long.

**Comment by Antiheavy** [comment]
I tested this 2 days ago and elevation download was not working.  I just tested now and elevation download is working again.

**Comment by DonLakeFlyer** [comment]
It's all working again now.
