### ISSUE TITLE
Mission transfer failed

### ISSUE THREAD

**Issue by Polarbeargo** [mavlink/qgroundcontrol#7254]
## Expected Behavior
Hello everyone, I'm trying to upload mission plan to Intel aero both on Yocto and Ubuntu.

## Current Behavior
Both OS have the same problem when I upload mission as following screenshots:
![screenshot 22](https://user-images.githubusercontent.com/8589224/53470619-236af780-3a9d-11e9-97fb-900ef913f750.png)

## System Information
![screenshot 25](https://user-images.githubusercontent.com/8589224/53470580-0afadd00-3a9d-11e9-8524-178a6a394dde.png)

## Detailed Description
As I upload the mission plan got "Mission transfer failed. Retry transfer. Error: Vehicle didn't request all items from the ground station: Mission request. Can anyone give me the advice to resolve this mission transfer failed?

**Comment by DonLakeFlyer** [comment]
This looks like a really noisy comm link. You can see loss rates in Settings/Mavlink page. You can turn on logging for mission upload/download: https://docs.qgroundcontrol.com/en/SettingsView/console_logging.html to see exactly which is happening. Doubtful it's a QGC side problem so closing. I'll reopen if the problem can be pointed at QGC.

**Comment by DonLakeFlyer** [comment]
@hamishwillee This is another candidate for a troubleshooting section in the docs. Happens a lot.

**Comment by hamishwillee** [comment]
@DonLakeFlyer You already did that: https://docs.qgroundcontrol.com/en/Support/PlanUploadDownload.html :-)

The fact that this user did not find that tells me that we need to make it more visible. So what I have done is moved this into the Plan page (cross linked from common problems). I also added the actual message text - so this information would show up in search. 

Please review: https://github.com/mavlink/qgc-user-guide/pull/200

**Comment by Polarbeargo** [comment]
Thank you @DonLakeFlyer , now I'm able to see what happen during mission transfer fail 👍 , like start MAVLink log command fail, no internet access, network not available. My RTSP Video streaming and telemetry data is working great and i can remote ssh to Intel aero. Anyone can help me about how to trouble shooting further to solve mission transfer fail?
![screenshot 28](https://user-images.githubusercontent.com/8589224/53534404-af326180-3b39-11e9-8037-d3cbd6772ab4.png)
![screenshot 29](https://user-images.githubusercontent.com/8589224/53534417-b9ecf680-3b39-11e9-824c-c2392025ecbf.png)

**Comment by hamishwillee** [comment]
@Polarbeargo What is the loss rate on this dialog: https://docs.qgroundcontrol.com/en/SettingsView/MAVLink.html#link-status

**Comment by Polarbeargo** [comment]
Thank you @hamishwillee, I got the log with the document instruction :) but as I try to find link status QGroundControl appear like the screen shots not sure what I am missing.
[mission.txt](https://github.com/mavlink/qgroundcontrol/files/2913081/mission.txt)
![screenshot 30](https://user-images.githubusercontent.com/8589224/53536363-156eb280-3b41-11e9-86d3-ba245d7f262f.png)

**Comment by dogmaphobic** [comment]
It looks like you are running a very old version of QGC. It's missing a great deal of features added to that panel in the past several months:

<img width="1003" alt="screen shot 2019-02-27 at 9 26 54 pm" src="https://user-images.githubusercontent.com/749243/53537078-b8d6ad80-3ad6-11e9-8b77-149e5d36cd89.png">

**Comment by Polarbeargo** [comment]
@dogmaphobic Thank you :)! I will also upgrade my QGroundControl.

**Comment by hamishwillee** [comment]
QGC 3.5 (current) has the section.

**Comment by Polarbeargo** [comment]
Here is my  loss rate and newest log.
[mission transfer fail.txt](https://github.com/mavlink/qgroundcontrol/files/2913186/mission.transfer.fail.txt)
![screenshot 32](https://user-images.githubusercontent.com/8589224/53537875-62a15300-3b46-11e9-80f8-5cb1b58b583d.png)

**Comment by hamishwillee** [comment]
There you are then. As it says in the docs, if you are in the high single digits (ie around 9) you will get intermittent failures, and too much higher the chance of fail gets to 100%.  Why is the environment you are in so noisy? Can you get the vehicle closer to the ground station before uploading a mission?
You might need a better antenna or radio. The software can't really help you in this case - the messages just aren't getting through.

**Comment by Polarbeargo** [comment]
@hamishwillee, The Drone is near me about 5 cm, I'll try to test in another environment very appreciate your guiding, thanks 👍 !

**Comment by dogmaphobic** [comment]
That's an awful lot of messages (~180k) How long it took to get that many messages? If it was a short time, the data rate may be saturating the link.
