### ISSUE TITLE
Feature request - Headless Mode for multi-rotor (eg. Quadrotor) airframe type.

### ISSUE THREAD

**Issue by minerran1** [mavlink/qgroundcontrol#7260]
- Ground station operating system:  Windows 7 Ultimate x64   24Gb Ram  i7 CPU   2.67Ghz
- QGroundControl version: 3.5.0
- Autopilot board: Pixracer R15
- Autopilot firmware PX4 1.8.2

Suggest adding a new flight mode called "headfree", same as what cleanflight and INAV have.
Since not everyone (especially fixed wing pilots) will know what this is, I will explain.   When a multirotor (quadcopter) is far enough away, the pilot might not be able to see where the front of the aircraft is to know which way to move the controls.  Moving the pitch right on the controller might cause the craft to pitch left if the orientation has changed since takeoff.  Getting it wrong can mean losing control and crashing as i have done several times.   Headfree mode corrects this.  See the following link, INAV developers explain it far better than I can.   [Headfree flight mode INAV](https://github.com/iNavFlight/inav/wiki/Modes#headfree)  Basically the multirotor knows its orientation relative to the RC controller (eg. Taranis).   In headfree mode, the aircraft is put on the ground facing away from the pilot.  Hence, regardless of whatever yaw is performed after takeoff, pulling the pitch towards the pilot will cause the craft to fly towards the pilot, etc.  Make sense?

This would be very useful for flying without fpv displays or goggles, flying from a distance.  Fixed wing pilots won't really have this problem since airplanes don't fly like quadcopters.

I'm posting this to QGroundControl but obviously the feature would have to also be added to the PX4 firmware as well.  Not sure where to go to request it for the firmware.

Thanks!!!

**Comment by DonLakeFlyer** [comment]
Firmware repository is here: https://github.com/PX4/Firmware. That is where this should go.
