### ISSUE TITLE
This is a bug to not find xxx.px4 file.

### ISSUE THREAD

**Issue by roseyangyu** [mavlink/qgroundcontrol#7265]
This is a bug.I have download QGC-v3.4.0 and v3.4.0+.When I upload firmware by QGC,I can't find the that Firmware download from github.It's hidden.I can input its name to upload in QGC.But version 3.3 is different,I can find FW in QGC-v3.3

**Comment by roseyangyu** [comment]
![default](https://user-images.githubusercontent.com/40378941/53793218-595e1f00-3f68-11e9-8099-ef8d6ffb91d6.png)
![default](https://user-images.githubusercontent.com/40378941/53793242-65e27780-3f68-11e9-876c-20676beab5a3.png)
This is V3.5.0 and in same folder.
3.3 is normal.

**Comment by DonLakeFlyer** [comment]
Hmm, this doesn't reproduce for me. I wonder if it only happens in the translated version.

**Comment by bys1123** [comment]
@DonLakeFlyer I think maybe translation team use the wrong  brackets "（）"，I updated it.

**Comment by DonLakeFlyer** [comment]
Ah, that would make sense. @dogmaphobic How do translated builds flwo through the system. Will a new daily just pick this up?

**Comment by dogmaphobic** [comment]
> Will a new daily just pick this up?

No, the process is quite manual. Once the translation is fixed, it must be "built" (within Crowdin), downloaded, compiled (.ts to .qm) and a new PR made with the changes.

**Comment by DonLakeFlyer** [comment]
Can anyone verified this is working with latest daily build translations?

**Comment by bys1123** [comment]
@DonLakeFlyer This is already fixed long time ago on stable release.

**Comment by DonLakeFlyer** [comment]
Thanks for letting me know
