### ISSUE TITLE
QGC behaves as a spam from the 90s in mac after opening a log file

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#7277]
## Expected Behavior
Behaves as a normal window.

## Current Behavior
ITS FREAKING JUMPING AROUND.

## Steps to Reproduce:
1. Open QGC 3.5.0 dmg file in mac
2. Open a log file
3. Have fun.

## System Information
- macOS 10.14.3
- QGC Version: 3.5.0
- QGC build: release
- Flight Controller: log file of ArduSub stable

Video:
![qgc_spam](https://user-images.githubusercontent.com/1215497/53973635-fa0e2500-40b5-11e9-91b4-6863acb2fafe.gif)

Log:
[2019-03-06 18-27-10.tlog.zip](https://github.com/mavlink/qgroundcontrol/files/2942354/2019-03-06.18-27-10.tlog.zip)

**Comment by DonLakeFlyer** [comment]
Wow, that's an interesting one!

**Comment by DonLakeFlyer** [comment]
This is a different in daily builds. Working fine now.
