### ISSUE TITLE
Add telemetry overlay to saved video

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#7286]
This is one of the most highly requested features of sub users. The idea is to have telemetry such as depth, location, time etc overlaid on the video file in order to produce and maintain better records and deliverables. The common standard in the industry is simple text overlay like this:
![image](https://user-images.githubusercontent.com/8315108/54228633-f1b05280-44d8-11e9-9f4a-2104950a5f47.png)

There are subtitle formats ([ssa](https://en.wikipedia.org/wiki/SubStation_Alpha)) that allow positioning and formatting of the text. Media players such as VLC have support for rendering these subtitle files. QGC could produce these subtitle files with the telemetry data synchronized to the video. In order to keep it simple, we recommend limiting the available telemetry overlay to a set of <=20 or so common values like gps coordinates, altitude, temperature etc. One thought was to just use the available 'vehicle values widget' (pictured below) and add a column like 'export' to choose to add a value to the subtitle file. We would like to force the text placement also, for example a title and date at the top right, and all telemetry values in the bottom left (no user configuration).

![image](https://user-images.githubusercontent.com/8315108/54227433-46060300-44d6-11e9-8a43-29e9f50ec47f.png)

We have considered several other approaches, but we favored the subtitle file for these reasons:
- The original video remains available without any 'burned in' overlay
- Media players already support rendering the subtitle files and burning them into the video file in post, we don't have to implement any of the rendering side ourselves
- As minimal as possible user configuration and intervention - easy for them!
- Implementation requires simply producing the subtitle file which is in ascii format - easy for us!

If you guys approve of the approach, @patrickelectric @Williangalvani and I can do the work to make it happen.

**Comment by hamishwillee** [comment]
FWIW I love the idea. @dogmaphobic ?

**Comment by dogmaphobic** [comment]
We've had this conversation in the past. I had done some research. I even still have the code. Adding it is quite simple. The issue was that you have no control over the layout of the text. The protocol is meant for subtitles, which means sentences at the bottom of the screen. It works for a few bits of data but nothing like the image above.

**Comment by patrickelectric** [comment]
@dogmaphobic 	we did some study around the available formats, SSA allows control of the text position and layout.

**Comment by dogmaphobic** [comment]
Ha! I have the code that loads the telemetry logs and parses each message. From there, you pick whatever you want and write it out to the subtitle file along with the time stamp. Let me see if I can find it and I can start the PR. You can pick it up from there.

**Comment by Williangalvani** [comment]
This is an example of what we can have using the SubStation Alpha format:
![Screenshot from 2019-03-14 13-41-34](https://user-images.githubusercontent.com/4013804/54379226-c445df00-4667-11e9-8899-5b8d58614994.png)

[This](https://gist.github.com/Williangalvani/e01dabb2f860c6831781eb4016f00b45) is the subtitle file used. You can use any of [these](https://en.wikipedia.org/wiki/SubStation_Alpha#Players_and_renderers) players to test it, Just use a random video and load this subtitles file.

**Comment by DonLakeFlyer** [comment]
Would be nice if this could be done in combination with a rework of the Values Widget UI. Why not make it work for both somehow?

**Comment by jaxxzer** [comment]
What else would you be interested in addressing regarding the values widget @DonLakeFlyer?

**Comment by jaxxzer** [comment]
Ping @DonLakeFlyer for details relating to reworking the values widget as we go at this.

**Comment by DonLakeFlyer** [comment]
Basically make this setup be a replacement for the values widget. Always have the values show up directly on the screen whether it be video or map.

**Comment by jaxxzer** [comment]
@DonLakeFlyer I think the function and implementation of the qml widgets vs the subtitle file may actually need to be quite separate.

I'm wondering if your underlying interest is in making making the values widgets less obstructive than they are today, or something else. Is there an open issue regarding this?

**Comment by DonLakeFlyer** [comment]
The point is to get rid of the values widget and instead allow the user to put the values overlayed directly on the screen. Whether that be map or video. Would need to be thought throug from a real estate standpoint though since the value page thing would still be there.

**Comment by jaxxzer** [comment]
Ok Don, I think that patch will be independent of this work, but may be done in conjunction.

Also @Williangalvani is closing in on a working branch for the feature described here: 
![image](https://user-images.githubusercontent.com/8315108/56435618-1b625380-62a7-11e9-8343-c5e982b15dd9.png)

**Comment by LPNautic** [comment]
Hi,
When can we have this function in Ardusub Stable ??
Thanks

**Comment by Williangalvani** [comment]
Hello, 
This was merged into QGC, but as QGC is going through a lot of changes right now  this isn't on any stable releases yet. You can try it with the [daily builds](https://docs.qgroundcontrol.com/en/releases/daily_builds.html) meanwhile.
