### ISSUE TITLE
Parameters missing

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#7289]
Alot of parameters are missing in qgroundcontrol.
They are in missionplanner.
E.g. RCXX_OPTION: RC input option

qgroundcontrol 3.5
arducopter-heli 3.7.0-dev

**Comment by giacomo892** [comment]
@DonLakeFlyer Regarding this issue, in general, would be possible to add an option to allow the user to suppress the "missing parameters" error? It's quite annoying.

**Comment by DonLakeFlyer** [comment]
@giacomo892  That is a real error. Either QGC it out of date with the firmware you are using or the reverse. It indicates some part of QGC ui will fail. Is this specific error still happening with latest QGC. If so, add details and I'll fix.

**Comment by giacomo892** [comment]
When you for instance disable some code in ardupilot then the parameters of that part will be missing and QGC will complain. That's it basically

**Comment by DonLakeFlyer** [comment]
That isn't something that QGC is setup to run against. QGC is built to run against standard released versions of ArduPilot. If you want a version of QGC that works against a custom version of Ardupilot you also need your own custom modified version of QGC which has had the features which correspond to be removed from QGC as well.

**Comment by giacomo892** [comment]
Well not really, Ardupilot is cutting a lot of features on F4 boards and the messages are a bit annoying.

**Comment by giacomo892** [comment]
Flash Plane 4.1beta official release on an F4 board and:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/20860004/123764542-2b354380-d8c5-11eb-8fdb-25180e0a1e27.png">

Also bare in mind that custom build server is coming soon to ardupilot, so sooner or later this should be addressed. At least having an option to disable the warnings.
