### ISSUE TITLE
Camera Microservice not supported with Ardupilot

### ISSUE THREAD

**Issue by tpwrules** [mavlink/qgroundcontrol#7292]
Support for the new [Camera microservice](https://mavlink.io/en/services/camera.html) is disabled when QGC connects to an Ardupilot-based vehicle. This is unfortunate, because it prevents using the service on any vehicle with an APM flight controller even if the camera messages do not pass through the flight controller, and independent of APM's future support for camera messages (which it does not need in order to route them to the ground station).

This is because the default action for FirmwarePlugin::createCameraManager() is to return null. The PX4 support overrides this in PX4FirmwarePlugin::createCameraManager() and returns a QGCCameraManager object, allowing the microservice to work fine on PX4 vehicles. Copying this method (and PX4FirmwarePlugin::createCameraControl) to the APMFirmwarePlugin class results in the Camera microservice working as expected. It really should be implemented in FirmwarePlugin to always return a camera manager; I see no reason why the firmware on the vehicle's autopilot has anything to do with potential support of the microservice.

**Comment by dogmaphobic** [comment]
> I see no reason why the firmware on the vehicle's autopilot has anything to do with potential support of the microservice.

Because until now, it didn't exist. It's a simple fix. I've pushed it here: https://github.com/mavlink/qgroundcontrol/pull/7293

It could use some testing as I don't have anything running Ardupilot.
