### ISSUE TITLE
No custom firmware flashing (.apj)

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#7298]
Quite easy to reproduce:

Either compile your own file of Ardupilot or download from firmware.ardupilot.org and try to flash as a custom firmware, but QGC won't let select the apj extension.

related to https://github.com/mavlink/qgroundcontrol/issues/6760

**Comment by lvale** [comment]
Closing, because https://github.com/mavlink/qgroundcontrol/issues/7296 is very similar, only difference is that I was testing on QGC beta

**Comment by lvale** [comment]
@DonLakeFlyer 

Apparently the other issue is different from this

**Comment by DonLakeFlyer** [comment]
Fixed by #7319
