### ISSUE TITLE
Ardupilot can't reset parameters to defaults

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#7299]
QGC 3.5.0 on ubuntu 16.04, ArduSub 3.5.3

There is no longer any option to reset the parameters to the vehicle defaults. It used to be present in this menu:

![image](https://user-images.githubusercontent.com/8315108/54709965-0a45eb80-4b1d-11e9-83c7-c2489612c34b.png)

**Comment by DonLakeFlyer** [comment]
That's because it's not support by ArduPilot.

**Comment by jaxxzer** [comment]
> That's because it's not supported by ArduPilot.

How do you figure? It certainly was working in the past.

**Comment by DonLakeFlyer** [comment]
I don't think ArduPilot supports the mavlink way of doing this:

```
    _vehicle->sendMavCommand(MAV_COMP_ID_ALL,
                             MAV_CMD_PREFLIGHT_STORAGE,
                             true,  // showError
                             2,     // Reset params to default
                             -1);   // Don't do anything with mission storage
```

**Comment by jaxxzer** [comment]
https://github.com/ArduPilot/ardupilot/blob/f8f591c7db6def816421588c97b0e32ef4901a52/libraries/GCS_MAVLink/GCS_Common.cpp#L3689

I can follow this up with a pr after confirming things.

**Comment by DonLakeFlyer** [comment]
I turned this on. Hope it doesn't break anything!
