### ISSUE TITLE
Feature: Add declination setup

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#7310]
Moved from: bluerobotics/qgroundcontrol#143
Original author: @jaxxzer

### Issue description
The autopilot has a declination lookup, but it won't use it without gps lock. We should have manual declination entry on sensors/compass setup.

**Comment by jaxxzer** [comment]
This should be a part of compass calibration step, selecting auto declination or manual declination + entry. The compass calibration will be affected if the declination currently used by the autopilot is not valid (ie if there is no gps, or gps does not have a lock).

**Comment by jaxxzer** [comment]
@Williangalvani

**Comment by jaxxzer** [comment]
@DonLakeFlyer Would it be acceptable to add a declination setup to the compass sensor calibration step?

In the right sidebar that appears we could have a choice of auto declination/manual declination, and if the user selects manual declination, provide a manual entry field. This is performed before the compass calibration sequence initiates.

**Comment by DonLakeFlyer** [comment]
My concern here is exposing something to all users for which 99% of them will never use and may just cause confusion. If I have it wrong in that most people will never use this, then fine. But if I have it right and maybe this is mainly a sub thing (whereas almost always all other vehicles have a gps) then I would bracket it for showing up only for subs.
