### ISSUE TITLE
Taking pictures crashes on cameras without video streams

### ISSUE THREAD

**Issue by tpwrules** [mavlink/qgroundcontrol#7323]
I am developing a camera but for various reasons it will not offer a stream preview in QGC. Unfortunately, this means that asking a picture to be taken by clicking on the red button crashes QGC. The issue appears to be these lines:
https://github.com/mavlink/qgroundcontrol/blob/6af7e8f2f40f390bb17f3b56e6c910010165787e/src/Camera/QGCCameraControl.cc#L366-L371

If no stream has been set up, something in line 370 ends up null (I would assume the return value of videoReceiver()) , so attempting to call a function on it crashes. Commenting out that line fixes the problem. This issue probably also happens on line 1477. There probably needs to be an option to disable local image capture, and enforce disabling it when the camera does not offer a video stream. This is already checked for in QGCCameraControl::_checkForVideoStreams().

Let me know if you need more analysis and I will be happy to dig a bit deeper.

**Comment by dogmaphobic** [comment]
Yup! That makes sense. No one has ever run into this because video has always been present. I'll look into it.
