### ISSUE TITLE
QGC Master: Unable to select vehicle type when choosing firmware

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#7337]
Unable to select Vehicle type on the dialog box when flashing firmware:

Current firmware on the board: Copter 3.7 master

<img width="1269" alt="Screenshot 2019-04-01 at 16 15 46" src="https://user-images.githubusercontent.com/3130363/55339084-e928b780-5499-11e9-982b-cdaf64939d98.png">

**Comment by DonLakeFlyer** [comment]
Hmm, all working fine for me. Can you log FirmwareUpgraderLog and attach?

**Comment by DonLakeFlyer** [comment]
ArduPilot firmware update is pretty different now. My guess is this ius gone now
