### ISSUE TITLE
QGC v3.5.0 Won't Open in Windows 10 Pro

### ISSUE THREAD

**Issue by rollysing** [mavlink/qgroundcontrol#7367]
Installed QGC v3.5.0 in Lenovo laptop running Windows 10 Pro v1803. QGC attempts to open but fails. While looking at Task Manager, the app starts to open but Status momentarily shows Suspended, then QGC disappears.

* Have disabled signature requirement during startup prior to installation.
* Have tried running Safe Mode and Compatibility versions but still no joy.
* Tried installing the latest Daily Build and am got the same result as described above.
* With some registry modifications, installed it in Windows Safe Mode. The app opened but because there's no network connection, it didn't download any maps. After rebooting to normal startup, QGC crashes as well.

Here is a short video of what happens in the Process tab of Task Manager:
https://youtu.be/HfB_WZuV08Q

The crash dumps can be downloaded here: https://1drv.ms/f/s!Ar66Lk6yrxscgjKW3SjU_oPLtz4p

Any ideas/ advise on how to resolve is highly appreciated.

**Comment by DonLakeFlyer** [comment]
Looks like a graphics driver crash. Have you tried to Windows QGC Graphics Compatability modes:

https://docs.qgroundcontrol.com/en/Support/troubleshooting_qgc.html

**Comment by rollysing** [comment]
Yes, all of them fail the same way. I've also tried the different options in Windows Compatibility and none of them worked.

**Comment by rollysing** [comment]
@DonLakeFlyer 

v3.5.1 Crash Dumps
https://1drv.ms/f/s!Ar66Lk6yrxscgjKW3SjU_oPLtz4p

**Comment by rollysing** [comment]
@DonLakeFlyer Thinking about some more of graphics driver crash. Here are the specs of the laptop/tablet display. FYI... Mission Planner installs and runs without any issue.

- Intel HD Graphics 515 Display adapter with Driver Date 2/7/2019 Driver Version 25.20.100.6576
- Resolution: 2160 x 1440
- Text size: 175%

Hope this helps to point to possible resolution.

Thanks.

**Comment by DonLakeFlyer** [comment]
Yeah Intel graphics cards are usually the ones which cause problems. Their OpenGL driver sucks. Which is why those additional statup modes were added. Which have always worked in the past. Can you capture crash dumps from those two additional startup modes as well. Maybe those broke somehow.

**Comment by rollysing** [comment]
@DonLakeFlyer Here are the Compatibility and Safe Mode crash dumps. Hope this points you to the right direction for the resolution.
https://1drv.ms/f/s!Ar66Lk6yrxscgjKW3SjU_oPLtz4p

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you have new qgc4 windows builds available? I'd be curious to see if full native qml works around these OpenGL windows crashes.

**Comment by dogmaphobic** [comment]
My Windows build system got hosed the last time I "upgraded" Qt. I need to get that fixed. I'll let you know...

**Comment by DonLakeFlyer** [comment]
If you could get an installer to @rollysing to try that would be great.

**Comment by dogmaphobic** [comment]
@rollysing, here we go: https://drive.google.com/file/d/1cqnzPrZfFnyiWgybXwaxQ7UQJ6ImCJtb/view?usp=sharing

Note that this is a new, under development branch. It matches master but certain things are missing (such as log replay, charting, etc.)

**Comment by rollysing** [comment]
@dogmaphobic @DonLakeFlyer Nope, it was the same as the regular install. Here are the crash dumps of all 3 program versions.
https://1drv.ms/f/s!Ar66Lk6yrxscgj9bneTfx42JAJiC

**Comment by rollysing** [comment]
Just following up to see if there's been any progress on this.

Thanks.

**Comment by DonLakeFlyer** [comment]
@rollysing Can you try this new version: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer.exe

**Comment by rollysing** [comment]
No joy. Tried all three startups.

Thanks.

**Comment by DonLakeFlyer** [comment]
Not sure we are going to be able to fix this until we move to 64 bit and Qt 12. Then we may need to get a fix out of Qt for it. Possibly has something to do with suspending. Not sure if there if a way to make that not happen by change the power settings on the laptop or not.

**Comment by rollysing** [comment]
Ok, thanks. So is that the difference of QGC vs Mission Planner? Just curious since MP installs, runs and upgrades without any issue.

Thanks for all the attention and assistance.

**Comment by DonLakeFlyer** [comment]
MP and QGC are radically different. MP is a native windows C# application. QGC is a cross platform C++ using a library (Qt) to provide the cross platform and ui support.

**Comment by DonLakeFlyer** [comment]
Also in general it's the Lenovo Thinkpads which cause the most problems in combination with the Intel integrated graphics driver which appears to be crap. If you do internet searches associated with the Intel drivers you'll find a wasteland of apps having problems with them.

**Comment by rollysing** [comment]
Just odd that I've been using Lenovo laptops for a better part of this decade and this is the first (and only) one that has run into this problem. Admittedly that this is the only one that has a 2160 x 1440 native resolution.

Thank you for all the help.

**Comment by jaxxzer** [comment]
@rollysing what is your laptop model?

**Comment by rollysing** [comment]
Lenovo Thinkpad X1 20GG001KUS

**Comment by DonLakeFlyer** [comment]
@antiheavy Is this similar to your folks laptops?

**Comment by DonLakeFlyer** [comment]
I want to try a few more things...

**Comment by DonLakeFlyer** [comment]
@rollysing Can you try this: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer.exe. It has gstreamer compiled out of it. If it still crashes attach the dump.

**Comment by rollysing** [comment]
@DonLakeFlyer No joy. CrashLogs here https://1drv.ms/f/s!Ar66Lk6yrxscgkj63lwFDT4-1xPp

**Comment by rollysing** [comment]
@DonLakeFlyer By the way, that installer was being blocked by Windows. Had to go Advanced.
![image](https://user-images.githubusercontent.com/20650795/60621119-dd0b0980-9daa-11e9-96b3-6430f9e0f83e.png)

**Comment by DonLakeFlyer** [comment]
@rollysing Are the three crash logs in there the three startup variants? Or just three crashes from regular boot? 

As far as the windows protection thing. It always does that since the installer is not signed. @hamishwillee May be worthwhile to include in the docs to steps to work around this. OSX has a similar thing where you need to right-click and select Open to be allowed to run for the first time since it's not signed.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic FYI...

So the stack trace is this:
![Screen Shot 2019-07-04 at 10 25 10 AM](https://user-images.githubusercontent.com/5876851/60681965-193f7800-9e46-11e9-859e-736fd4fee5e7.png)

From internet search dsengine.dll seems to be related to Qt QCameraInfo: https://stackoverflow.com/questions/56180327/which-dlls-are-needed-for-qt-multimedia-qcamerainfoavailablecameras-to-retu

The version @rollysing is testing has QStreamer compiled out by hacking the build files. Wondering if even though gstreamer is complied out whether QGC still cranks up the camera stuff where it tries to get list of cameras from OS? Which may be causing the crash.

**Comment by dogmaphobic** [comment]
> Wondering if even though gstreamer is complied out whether QGC still cranks up the camera stuff

Yes, UVC video is separate from GStreamer. UVC support is handled through Qt Multimedia, using a very different code path.

**Comment by DonLakeFlyer** [comment]
Ok, let me hack that out and see what happens.

**Comment by DonLakeFlyer** [comment]
@rollysing Can you try this one: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer-nogstuvc.exe? This has both gst and uvc compiled out.

**Comment by Antiheavy** [comment]
> @Antiheavy Is this similar to your folks laptops?

The Lenovo's that our internal folks are using and also many of our customers are using are various models in the Thinkpad P-series.  The application crashes we are experiencing for the most part sound different than the one @rollysing is reporting (although maybe all related somehow).  However, we recently had a customer who seemed to be having an issue similar to @rollysing - no idea what type of laptop they had.  They were reporting the application launching and immediately crashing, 100% repeatable.  They updated to a newer version of QGC with our custom plugin (Sentera v1.4.0 FWIW) and their app crashing problem went away.

**Comment by rollysing** [comment]
> @rollysing Can you try this one: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer-nogstuvc.exe? This has both gst and uvc compiled out.

Tally Ho! This one did it!

**Comment by DonLakeFlyer** [comment]
Ok, let me start putting things back one at a time and you can try them and then hopfully we can nail it down exactly.

**Comment by DonLakeFlyer** [comment]
@rollysing Let me know what happens with this one: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer-nouvc.exe

**Comment by rollysing** [comment]
@DonLakeFlyer That worked albeit, UVC device not showing in Video Source as the installer name indicated.

**Comment by DonLakeFlyer** [comment]
Are you actually trying to use a UVC device on this laptop with QGC? If so, didn't realize that.

**Comment by rollysing** [comment]
Yes, for OSD via FPV camera.

**Comment by rollysing** [comment]
@DonLakeFlyer Just following to see if there's an updated installer that would include UVC integration.

Thanks.

**Comment by rollysing** [comment]
Hello @DonLakeFlyer . Just following up to find out if there's been any progress on a version that will allow to use UVC input? Thanks.

**Comment by DonLakeFlyer** [comment]
The new gsstreamer work should fix the startup problems we hope.

**Comment by rollysing** [comment]
Would this be on the stable release or nightly build? I think I tried v3.5.6 and it still wouldn't open.

**Comment by DonLakeFlyer** [comment]
This is a WIP that should be coming soon in a daily: https://github.com/mavlink/qgroundcontrol/pull/8093

**Comment by DonLakeFlyer** [comment]
@rollysing You're working now right?
