### ISSUE TITLE
Linux: Speech output wrong, possible wrong or undefined language

### ISSUE THREAD

**Issue by sgofferj** [mavlink/qgroundcontrol#7387]
## Expected Behavior
Speech output should be pronounced correctly in English

## Current Behavior
Speech output sounds funny. E.g. "throttle below fa-il-sah-feh" or "Hard-wah-re sah-feh-tee switch".
[speech.zip](https://github.com/mavlink/qgroundcontrol/files/3124903/speech.zip)

It looks like QGC doesn't tell speech-dispatcher which language engine to use. I am in Finland, so it is possible that for some reason, speech-dispatcher uses the Finnish engine by default. That would kinda fit the sound of the output but I'm not sure about it.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Start QGC on Linux with speech-dispatcher

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04
- QGC Version: 3.5.1
- QGC build: stable
- Flight Controller: Pixhawk
- Autopilot (with version): Ardupilot Copter 3.6.8

## Log Files and Screenshots
- [QGC Console Logs][log.txt](https://github.com/mavlink/qgroundcontrol/files/3124899/log.txt)

**Comment by HTRamsey** [comment]
Not sure this is the best solution, but it's forced to en_US now
