### ISSUE TITLE
GeoFence crash on MacOS

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#7397]
I can let QGroundControl V3.5.1 crash every time performing the following steps:
1) Open QGroundControl
2) Open the Plan View
3) Open the Fence Planning window
4) Connect a Pixhawk board running PX4 1.8.2
5) Click on the Polygon Fence button
6) Click on one of the polygon edges. The UI shall pop up a menu.
7) Close the menu (Clicking back on the map)

The application output the error QObject::connect: invalid null parameter and crash.

I tested it on both MacOS and Windows machine and I can reproduce it ONLY on the MacOS one.
![Schermata 2019-04-30 alle 16 34 43](https://user-images.githubusercontent.com/9391950/56969750-197d7780-6b66-11e9-9ed5-6ac37b950494.png)

**Comment by DonLakeFlyer** [comment]
Crap, this looks to be a Qt bug with Menu qml.

**Comment by DonLakeFlyer** [comment]
Stable build updated. Will go out when I pull the trigger on 5.3.3. Daily Build fix should be available by tomorrow.

**Comment by DonLakeFlyer** [comment]
@FlavioTonelli And thank you for the bug report.
