### ISSUE TITLE
Improve scroll-ability of log replay slider

### ISSUE THREAD

**Issue by yutaoliu** [mavlink/qgroundcontrol#7412]
QGroundControl version 3.5.0 (stable) running in Ubuntu 18.04.

The slider for replaying tlog has very poor time resolution i.e. I can only drag it to start the log replay from a couple of locations. @DonLakeFlyer says this is a bug and it should be able to start from any location.

**Comment by DonLakeFlyer** [comment]
Can you give me a link to a telemetry log which shows this behavior? I just tried it myself and as able to set the slider all over the place.

**Comment by Antiheavy** [comment]
>  I just tried it myself and as able to set the slider all over the place.

really?  The slider has never worked properly for me, always as @yutaoliu describes above.  Might it behave differently in Windows (my OS) or other versions?

Hence this related feature request: https://github.com/mavlink/qgroundcontrol/issues/5730

**Comment by DonLakeFlyer** [comment]
> The slider has never worked properly for me

Even recently? I fixed a lot of stuff with time positioning in replay a while back. I also think there may be some issue with Mavlink 1 versus Mavlink 2 streams, but not surel. Hence I need a log which shows the problem. Just SITL logs work fine.

**Comment by Antiheavy** [comment]
Yes even recently. We are still using mavlink 1. Maybe it is time to change to 2. I’ll find a log and attach it here.

**Comment by Antiheavy** [comment]
[2019-04-29 15-15-17.zip](https://github.com/mavlink/qgroundcontrol/files/3145719/2019-04-29.15-15-17.zip)

short example log attached.  scanning and scrubbing is sort of weird even with the newest Daily build.

**Comment by DonLakeFlyer** [comment]
This should be fixed now in daily builds
