### ISSUE TITLE
Bug or Feature: CameraInfo is requested for any component, not only cameras

### ISSUE THREAD

**Issue by olliw42** [mavlink/qgroundcontrol#7433]
QGC appears to request the CameraInformation message from a component, irrespective of its type or ID, pl see the attached screenshot for a case there I had a component set to ID 152 (any other would work equally)
![GQC-requestCameraInfo](https://user-images.githubusercontent.com/6089567/57574749-f5ac1280-743e-11e9-9f28-07924949f01e.jpg)

From the MAVLink docs I would not have expected this to happen, since this protocol is part of the camera micro-service, and I actually think it somehow makes no sense to request this from every single component.

I thus would think that this is a bug, and that CameraInformation should only be requested if the component is identified as a camera.

If this behavior is a feature, I would think that the mavlink docs should be updated to make it clear that any component may be asked this request and hence may serve the camera micro-service, even if it's a servo or imu, i.e. that this is the official, documented behavior.

NOTE: in the above example I also had a camera component at ID 102, which didn't serve the camera information request, for this particular test. If I make the camera component to serve that request, QGC of course would handle 102 correctly. The point of this issue here is how QGC handles the 152 component. If there is any confusion about this I can provide a screenshot also for that (more realistic) case.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Gus?
