### ISSUE TITLE
Select language invalid on Daily build

### ISSUE THREAD

**Issue by bys1123** [mavlink/qgroundcontrol#7464]
## Expected Behavior
UI shows right language after language selection.

## Current Behavior
Nothing changed after language selection.

## System Information
When posting bug reports, include the following information
- Operating System: [Android, Windows]
- QGC Version: [master]
- QGC build: [daily]

## Detailed Description
I saw language support have lots of change these days, but I think language files are still on master, but is not valid.

## Log Files and Screenshots
![image](https://user-images.githubusercontent.com/4748411/58073151-7358e680-7bd4-11e9-806b-de128281e74f.png)

**Comment by dogmaphobic** [comment]
It must be a platform issue. It is working on macOS but I have not had a chance to try elsewhere.

<img width="1358" alt="Screen Shot 2019-05-21 at 8 31 53 AM" src="https://user-images.githubusercontent.com/749243/58073511-08db8280-7ba3-11e9-90ea-a29329cb49a7.png">

**Comment by tops4u** [comment]
Same here on MacOS. Switched to German, but nothing happened - still english.

**Comment by hamishwillee** [comment]
When was this build generated? If it is today, then only approved translations are being exported from QGC, so on some languages that would be "none".
