### ISSUE TITLE
Corrupted log file

### ISSUE THREAD

**Issue by kaklik** [mavlink/qgroundcontrol#7474]
I want to replay [attached log file](https://github.com/mavlink/qgroundcontrol/files/3219441/2019-05-22.18-20-20.zip) to view exact command sequence from QGC.   

## Expected Behavior
Open the log file and examine the situation by time slider. 

## Current Behavior
After click on Replay Flight Data button and select the log file. The following message  pops

```
Log Replay Error
The log file '2019-05-22 18-20-20.tlog' is corrupt. No valid timestamps were found at the end of the file.
```

![image](https://user-images.githubusercontent.com/1194177/58370703-cf3faa00-7f09-11e9-8177-bcf0da9aa195.png)

## Steps to Reproduce:

1. Proceed flight with PX4 UAV
2. Turn off UAV
3. Disconnect telemetry modem from USB
4. Close ground control's station laptop
5. Tranport everything to the workshop
6. Open laptop again and try to replay logged data. 

## System Information

- Operating System:  Ubuntu 18.04.2 LTS
- QGC build: Development HEAD:49ef8c141 2019-05-15
- Flight Controller: Pixhawk 3
- Autopilot (with version): PX4 v1.9.0 (RC)

**Comment by bigbellmercy** [comment]
This issue is important because when a drone is crashed far away and this bug happens we cannot find the drone since we don’t know its location. As a case, it happened to me.

**Comment by DonLakeFlyer** [comment]
@bigbellmercy Can you try the AppImage from here: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl.AppImage?

**Comment by DonLakeFlyer** [comment]
This should be fixed now. New daily builds will be available in a few hours. Stable will be updated as well but that won't happen for a bit.

**Comment by DonLakeFlyer** [comment]
@kaklik Flagged the wrong person. Can you try the new build posted above?

**Comment by kaklik** [comment]
@DonLakeFlyer  Yes, I could confirm that build from above is able to open the corrupted log file. Thanks for fixing the bug. :)

**Comment by DonLakeFlyer** [comment]
Great, thanks for verifying
