### ISSUE TITLE
Feature request: MAV_CMD_GET_HOME_POSITION

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#7475]
QGC does already support GPS on ground for RTK.
please add an option to send MAV_CMD_SET_HOME_POSITION and update home position during the flight.

**Comment by booo** [comment]
Implemented in https://github.com/mavlink/qgroundcontrol/commit/ac97ce43c24dc8d4ef9426a7045bcbf2ab1a923a

**Comment by AndKe** [comment]
@booo - thanks, but do we know if AC will update the target it while in RTC mode?  
I remember that AC , when entering RTL, navigated to the point configured at the time of RTL - ignoring further updates - unless switched out of, then into RTL.
