### ISSUE TITLE
Hover and capture during survey (PX4 autopilot) -> capture and forward flight at the same time

### ISSUE THREAD

**Issue by Stifael** [mavlink/qgroundcontrol#7488]
This issue is not necessarily only QGC related, but with my current state of knowledge, I think QGC is more suited to tackle the issue below.

### hover-and-capture distance-trigger
A `hover-and-capture` survey with distance-based trigger results in a waypoint grid with the following order:
First, a waypoint msg is sent (`MAV_CMD_NAV_WAYPOINT`). Each waypoint is followed by a camera-capture msg (`MAV_CMD_IMAGE_START_CAPTURE`). 

## issue
In PX4, the output of this msg-order is that the vehicle approaches first the waypoint (slowly), but once the waypoint is reached, the vehicle passes the `MAV_CMD_IMAGE_START_CAPTURE`-msg to the camera and one execution loop later the vehicle will continue to fly to the next hover-and-capture waypoint. Consequently, the camera captures a picture more or less at the same time the vehicle accelerates again towards the next waypoint. Moreover, a waypoint is considered reached once it is within some acceptance radius, which means that the vehicle might not even take the picture at the desired location.

## expected
The vehicle will fly to the hover-and-capture location. Once that waypoint is reached AND the vehicle has no more forward motion, then the vehicle should take a picture, then hover again for some time to take the time into account that is required to pass the mavlink-msg `MAV_CMD_IMAGE_START_CAPTURE` from the autopilot to the camera, and then continue the forward flight to the next waypoint. 

## possible solution
There are multiple solutions to this problem. One solution could be to force the vehicle to hover after `MAV_CMD_IMAGE_START_CAPTURE`, which could be achieved by finishing the hover-capture msg-sequence with an additional loiter msg.

**Comment by DonLakeFlyer** [comment]
There is more detail in #7486 to cover all that is needed. We should use that one.
