### ISSUE TITLE
Android app: add tracks.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#7491]
The flight path is not visible in Android app, flying over a feature-less area, like from a ship/over sea, makes it impossible have an understanding of past search-paths.

**Comment by DonLakeFlyer** [comment]
Wierd. Do you know is this started happening recently. Not much change in that code.

**Comment by AndKe** [comment]
Sorry, I do not know. It is unusual that I use QGC for those bigger things, especially at sea.
I have made an MAVProxy module that updates home point along with the ship, and discovered that AP2 did not display updated home location.
Just for fun, I tested QGC, which updated home just fine, and made a track, then connected my phone to the GCS computer over wifi, and discovered that there were no visible tracks on the screen.

**Comment by DonLakeFlyer** [comment]
I tried both daily and stable builds doing this:
* Takeoff
* GoTo Location

In both cases I got vehicle tracks.

**Comment by AndKe** [comment]
I think I know what happened.
Like I mentioned, this was a test, we did not flew, the ship(and UAV) was moving... It is likely that the tracks are only drawers while flying... Correct ?

**Comment by DonLakeFlyer** [comment]
Only when armed. Which I think still makes sense. So things are ok here.
