### ISSUE TITLE
"Parameters are missing from firmware" but doesn't identify which

### ISSUE THREAD

**Issue by lecw** [mavlink/qgroundcontrol#7494]
## Expected Behavior
If some parameters are actually missing (which I'm not sure of), the error message should say which

## Current Behavior
As in the screenshot error message, sometimes QGC complains about missing parameters, but doesn’t tell me which parameters are missing (other than “-1”). 

## Steps to Reproduce:
1. plug in the pixhawk, wait for it to boot
2. some messages appear (HIL is enabled, etc.), including this one

## System Information
- Ubuntu Mate 16.04
- QGC Version: 3.5.2
- QGC build : daily build
- Flight Controller: Pixhawk 4
- Autopilot (with version): PX4 1.8.2 with a few custom modifications.

## Detailed Description
The same firmware will _not_ trigger this warning on some other versions of QGC on different computers (such as on windows, or in the stable-vs-daily one).

## Log Files and Screenshots
- QGC Console Logs [to come]
![Screenshot](https://discuss.px4.io/uploads/default/original/2X/4/4f163b64ca7ed3f093ee3cebd93bfa2aad9df372.jpeg)

**Comment by DonLakeFlyer** [comment]
Do you have console logs? The link above goes to the docs? If not, can you attach them?

**Comment by lecw** [comment]
No I didn't have them, and now I can't reproduce it. Now I run into "Firmware is not latest stable version ! Firmware version is -1.-1.-1, latest stable is 1.9.0.".

![Screenshot from 2019-06-07 21-54-58](https://user-images.githubusercontent.com/49571610/59140687-f1f0aa80-896e-11e9-96fd-0413ad75c9e1.png)

We have two computers (both Ubuntu) that both pull our firmware from the same github and push it to the same pixhawk 4 (with `make px4fmu-v5_default upload`). In one case, the firmware is then recognized by QGC as 1.8.2.dev, but in the other case, firmware is "Unknown" and yields this "-1.-1.-1 version" warning. That seems related to me, tell me if not.

A console log for that is here :
[log-1-1-1.txt](https://github.com/mavlink/qgroundcontrol/files/3267991/log-1-1-1.txt)

**Comment by DonLakeFlyer** [comment]
> but in the other case, firmware is "Unknown" and yields this "-1.-1.-1 version" warning. That seems related to me, tell me if not.

Your firmware is not reporting correct version information in the AUTOPILOT_VERSION message.

**Comment by DonLakeFlyer** [comment]
Without a repro I'm closing this.
