### ISSUE TITLE
Toolbar logo calc is broken

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#7509]
Brand logo should hide if it overlaps the tools. I had fixed this a while back.

![Screen Shot 2019-06-09 at 9 54 20 AM](https://user-images.githubusercontent.com/5876851/59161868-9c1a2080-8a9c-11e9-9c6b-33396cd5ef8f.png)

**Comment by dogmaphobic** [comment]
It was a combination of the obscene size of the logo and the lack of code to handle its visibility if no available space.

**Comment by DonLakeFlyer** [comment]
Hah, ya that's bigger than it used to be isn't it
