### ISSUE TITLE
qgroundcontrol with gstreamer problem

### ISSUE THREAD

**Issue by focusonesoftware** [mavlink/qgroundcontrol#7524]
Hi,

I build groundcontrol w/o gstreamer on windows, It's OK.
I build qgroundcontrol with gstreamer on windows, I found "ASSERT failure in QSGNode::prependChildNode: "QSGGeometryNode is missing geometry", file scenegraph\coreapi\qsgnode.cpp, line 414 scenegraph\coreapi\qsgnode.cpp: 414".

windows 10
gstreamer version 1.14.4
qgroundcontrol master on 14/06/2019

Thank you.

**Comment by DonLakeFlyer** [comment]
If you want to see how QGC creates daily builds from master look at https://github.com/mavlink/qgroundcontrol/blob/master/.appveyor.yml. This sequence of steps has not problem creating a build that works.

**Comment by DonLakeFlyer** [comment]
Even though appveyor seems to be working. There is something strange going on here. Possibly only with debug builds. I can something similar to happen for me.

**Comment by DonLakeFlyer** [comment]
Verified that release builds work. Only debug builds fail.

**Comment by DonLakeFlyer** [comment]
Also Stable works fine. Also just realizing that appveyor has not been switched to 1.14.4. So it's using old version 1.5.2 installer. I've put up the 1.14.4 installers on to S3 for use. But I'll leave things as is for now. I'm switching Sentera stable to 1.14.4 though for testing.

**Comment by jaxxzer** [comment]
Worth noting there is a more recent stable release of gstreamer: [1.16](https://gstreamer.freedesktop.org/releases/1.16/)

**Comment by dogmaphobic** [comment]
> Worth noting there is a more recent stable release of gstreamer: [1.16](https://gstreamer.freedesktop.org/releases/1.16/)

Which, as far as I can tell, requires a 64-bit build of Windows. That is not working yet.

**Comment by jaxxzer** [comment]
Made a separate issue regarding updating the deployment here https://github.com/mavlink/qgroundcontrol/issues/7591

**Comment by DonLakeFlyer** [comment]
I think this is all good now. Windows has moved to 64 bit
