### ISSUE TITLE
Feature request 8 servos on heli setup page

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#7526]
currently only 4 servos are supported on the new (and great) heli setup page.
On my controller Matek F405-Wing the first 2 servo slots are reserved for ESCs.

So the servo mapping looks like this in MP:

![heli mp](https://user-images.githubusercontent.com/562809/59499283-5c39ab80-8e97-11e9-9e0d-f31785ec1bb7.JPG)

In qgroundcontrol it looks like this:

![heli2](https://user-images.githubusercontent.com/562809/59499345-85f2d280-8e97-11e9-9dae-5fca12c65222.JPG)

So motor3 and motor4 cannot be handled.

It would be great if the heli page could either handle 6 or 8 servos or figure out which servos are mapped to Motor1, Motor2, Motor3, Motor4 and show these.

**Comment by DonLakeFlyer** [comment]
@twistedwings Do you know if the SERVO5-8_* parameters are something only available in more recent firmwares?

**Comment by twistedwings** [comment]
My 1st ArduPilot was Copter 3.6.7.
But they should be there since Copter 3.4. 
[http://ardupilot.org/copter/docs/common-rcoutput-mapping.html](url)

**Comment by DonLakeFlyer** [comment]
Can you verify tomorrow from a new Daily?

**Comment by twistedwings** [comment]
I have tested this version:

![image](https://user-images.githubusercontent.com/562809/59552276-2d016800-8f85-11e9-8fd0-e624163e40c4.png)

I can't see any difference 

![image](https://user-images.githubusercontent.com/562809/59552293-4d312700-8f85-11e9-9b71-c4c6cf6f1167.png)

**Comment by DonLakeFlyer** [comment]
Sorry the change hadn't been merged in yet. New daily build should be available in an hour.

**Comment by twistedwings** [comment]
looks good, thanks alot!

![image](https://user-images.githubusercontent.com/562809/59555115-0d326a00-8fae-11e9-9d37-1c210e4f3066.png)
