### ISSUE TITLE
Daily: Parameter Screen Empty

### ISSUE THREAD

**Issue by MaEtUgR** [mavlink/qgroundcontrol#7547]
## Expected Behavior
Show all the synced parameters under the "Parameters" tab.

## Current Behavior
<img width="690" alt="Unbenannt" src="https://user-images.githubusercontent.com/4668506/60095425-ccc1b180-974e-11e9-939a-e71192009cae.PNG">

## Steps to Reproduce:
1. Download latest daily
2. Connect to pixhawk with latest stable PX4 1.9.1
3. Try to change a parameter in the UI

## System Information
- QGC Version:
<img width="229" alt="ver" src="https://user-images.githubusercontent.com/4668506/60095517-02669a80-974f-11e9-9fd5-52ff9acb7c26.PNG">

- Operating System: Windows 10 1809
- Flight Controller: pixhawk fmu-v5
- Autopilot: PX4 1.9.1 stable

## Additional Information
On 
<img width="203" alt="ver2" src="https://user-images.githubusercontent.com/4668506/60095746-946ea300-974f-11e9-9af8-1d1766376209.PNG">
the exact same setup without even replugging works fine.

**Comment by dogmaphobic** [comment]
Found it. On it...

**Comment by MaEtUgR** [comment]
I upgraded to latest daily again and now it's all fine, thanks!
