### ISSUE TITLE
Parameters missing entirely

### ISSUE THREAD

**Issue by Bosuwort** [mavlink/qgroundcontrol#7552]
I build and release the latest qgroundcontrol and connect the pixhawk board, but the parameters are not shown. I click the button of parameter and there's nothing. Could anyone help me solve it?

**Comment by Bosuwort** [comment]
I found the same problem#7547

**Comment by dogmaphobic** [comment]
> I found the same problem[#7547](https://github.com/mavlink/qgroundcontrol/issues/7547)

Which was fixed in #7548 as described in that (closed) issue.
