### ISSUE TITLE
Photo-triggering fails during autonomous missions

### ISSUE THREAD

**Issue by ATStahl** [mavlink/qgroundcontrol#7554]
I am using the current stable release of QGroundControl (v.3.5) on a Windows 10 laptop. The drone is a stock 3DR Solo (which I do not have permission to upgrade). It has a Pixhawk 2 and ArduPilot (stock Solo, modified version 3.3). QGroundControl communicates with the Solo, is able to upload and download and fly autonomous missions with waypoints. In the planned mission that was uploaded, "Take photo" was selected in the dropdown menu for the action at waypoint, but no photos were taken (GoPro Hero 4 Black). When the mission was downloaded afterward, the dropdown at waypoint was reset to "No change".

Using the 3DR Solo app, we were able to take photos during flight, so there is not a problem with the gimbal or the connection between the Solo and GoPro.

Is there a way to troubleshoot this?

**Comment by DonLakeFlyer** [comment]
I don't think ArduPilot+Solo supports these camera commands (take single photo). The fact that the command doesn't come back when you download from the vehicle kind of indicates that. You'd have to ask the ArduPilot folks about that. The mavlink command is MAV_CMD_IMAGE_START_CAPTURE with param3=1 to take a single picture. I think things like trigger distance do work.
