### ISSUE TITLE
QGC crash on IOS

### ISSUE THREAD

**Issue by Evanhahaha** [mavlink/qgroundcontrol#7561]
After building the ios release version, i tried to run it on XCode. However, it failed and i found "ASSERT failure in QSGNode::prependChildNode: "QSGGeometryNode is missing geometry", file scenegraph/coreapi/qsgnode.cpp, line 414". XCode reported that it found "QSGRenderThread (18): signal SIGABRT" at the 41 line of the AppMessages.cc file.

Botth gstreamer and QGC are of the latest version.

**Comment by DonLakeFlyer** [comment]
This is master right? @dogmaphobic This smells a lot like the windows crash on boot with master.

**Comment by wuuhii** [comment]
It will be occur on Windows. Please look over the issues 7578.
