### ISSUE TITLE
Android: Undesired popup on App start

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#7562]
QGC master shows an undesired window when the application start on an Android system.
The window contains the labels: "Survey","Corridon Scan","Structure Scan"(See attached Screenshot)
![Screenshot_20190619-084944](https://user-images.githubusercontent.com/9391950/60664219-9af0cf00-9e61-11e9-92bd-c56029ac072e.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic This is more craziness with the Qml 2 Menu implementation. I think we may need to make a QGCMenu which isolates itself to Qml 1 Menu control and then switch back to using the control 1 Menu thing. The v2 one is just to screwed up.
