### ISSUE TITLE
Feature request: Use android device GPS for ardupilot

### ISSUE THREAD

**Issue by Raviu8** [mavlink/qgroundcontrol#7563]
Hi,
I'd like to be able to use my built-in android device GPS receiver for ardupilot.
Ardupilot has a mavlink GPS driver, - also a nmea one - so it's be very good to add a feature to QGC-for-android to forward GPS from android to ardupilot.
QGC should take care of running this as a unkillable service not to stop on screen locking.

**Comment by DonLakeFlyer** [comment]
> QGC should take care of running this as a unkillable service not to stop on screen locking.

That is not currently possible.

> so it's be very good to add a feature to QGC-for-android to forward GPS from android to ardupilot.

To do what? As far as I know ArduPilot doesn't support such a thing either.
