### ISSUE TITLE
Parameter setting is not applied when reboot a vihicle

### ISSUE THREAD

**Issue by start0821** [mavlink/qgroundcontrol#7572]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
I need to set `SYS_COMPANION` in `SYSTEM PARAMETER` to Companion Link(921600) and reboot the vihicle to apply the setting. 

## Current Behavior
I need to set `SYS_COMPANION` in `SYSTEM PARAMETER` to Companion Link(921600) and reboot the vihicle to apply the setting. But when I reboot the vihicle, it come back to default value `disable`. 

## System Information
When posting bug reports, include the following information
- Operating System: window10
- QGC Version: 3.5.3
- QGC build: stable (maybe?)
- Flight Controller: Pixhawk1
- Autopilot (with version): PX4 1.9.2

## Detailed Description
I need to connect a pixhawk to raspberry pi using `TELEM2`, so I set `SYS_COMPANION` in `SYSTEM PARAMETER` to Companion Link(921600) and reboot the vihicle to apply the setting. But when I reboot the vihicle, it come back to default value `disable`. What can I do?  

other `SYSTEM` parameter does not have this problem. 

## Log Files and Screenshots
+ before rebooting the vihicle
![image](https://user-images.githubusercontent.com/26544022/60953004-4f459600-a337-11e9-80de-aa8b227c8e04.png)

+ after rebooting the vihicle ( parameter value comes back to default)
![image](https://user-images.githubusercontent.com/26544022/60952840-fb3ab180-a336-11e9-9f05-54c2f5a6126a.png)

**Comment by feemi** [comment]
Hi,

Sys_companion parameter is deprecated as it seen. So you should use mavlink parameters

There is MAV0_ and MAV1_ and MAV2_ options
Usually MAV0 is used for ground control station telemetry.

You can assign MAV1_ for onboard communication. You should select the interface on MAV1_CONFIG parameter. In your case i assume it would be TELEM2, then you can select MAV1_MODE to onboard.

<img width="892" alt="Screen Shot 2019-07-10 at 12 40 38" src="https://user-images.githubusercontent.com/1747208/60958928-f31b4b80-a30f-11e9-96f3-a9cbb5f04cfe.png">

Note: I guess you meant 1.9.2 i guess because there is no released version as 1.9.3.

**Comment by start0821** [comment]
> Hi,
> 
> Sys_companion parameter is deprecated as it seen. So you should use mavlink parameters
> 
> There is MAV0_ and MAV1_ and MAV2_ options
> Usually MAV0 is used for ground control station telemetry.
> 
> You can assign MAV1_ for onboard communication. You should select the interface on MAV1_CONFIG parameter. In your case i assume it would be TELEM2, then you can select MAV1_MODE to onboard.
> 
> <img alt="Screen Shot 2019-07-10 at 12 40 38" width="892" src="https://user-images.githubusercontent.com/1747208/60958928-f31b4b80-a30f-11e9-96f3-a9cbb5f04cfe.png">
> 
> Note: I guess you meant 1.9.2 i guess because there is no released version as 1.9.3.

Thank you for replying !!
I edit the QGC version to 1.9.2 and I'll try again!

**Comment by feemi** [comment]
Hi @DonLakeFlyer I guess you can close this issue.
