### ISSUE TITLE
QuadX image has screwed up font motor 3

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#7577]
See the old/fixed version provided in https://github.com/PX4/docs.px4.io/pull

![image](https://user-images.githubusercontent.com/5368500/61190390-e23b5300-a6de-11e9-995d-1d162907c72e.png)

I copied this into devguide/user guide, but I presume that you also need it in QGC?

**Comment by DonLakeFlyer** [comment]
QGC uses different images which don't have motor numbers on them.
