### ISSUE TITLE
Vehicle setup qml timers remain active after navigating to fly view

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#7585]
As noted in #7275 :
> There is another bug involved, and that is that the code/timers in the vehicle setup qml pages keeps running after the fly view is selected. So if motor test page is open in the background (while fly view is active), then it is sending motor test commands after you arm the vehicle. 

This is confirmed to occur on master for the motor setup page, I haven't investigated yet to see if any other setup pages are affected.

**Comment by DonLakeFlyer** [comment]
The pages from each view (Settings, Setup, Plan, Fly) continue to run even if they are not being shown.

**Comment by DonLakeFlyer** [comment]
The pull reference is the first step to providing a mechanism to fix this. When done it will provide a system for a page to prevent a view switch. Hence if you are in the middle of a calibration or an active motor test you won't be able to switch views. Preventing arming will be a little trickier. But view switch is a worse problem I think.

**Comment by DonLakeFlyer** [comment]
> I haven't investigated yet to see if any other setup pages are affected.

They are. Things which are say calibration relation with a start/stop to calibration will be affected.

**Comment by DonLakeFlyer** [comment]
@jaxxzer Once #8113 goes through you'll have the mechanism to fix your motor test page.

**Comment by jaxxzer** [comment]
ok! :clap:

**Comment by DonLakeFlyer** [comment]
@jaxxzer This should get fixed before I cut a stable which is soon

**Comment by DonLakeFlyer** [comment]
Time is running out to get this fix into stable.

**Comment by Williangalvani** [comment]
That was fixed in my latest PR, you can close it!
