### ISSUE TITLE
"Setup prior to flight" when it was actually done.

### ISSUE THREAD

**Issue by tuloski** [mavlink/qgroundcontrol#7588]
It happens sometimes that Qgroundcontrol reports the warning "WARNING your vehicle requires setup prior to flight ..." when actually the setup was already done.
All the sections related to Airframe, Sensors, Radio, Flight modes and Power are red and it says missing various parameters, but actually all the parameters are there.
I don't understand if it is a communication problem with the autopilot, where some parameters are not collected or it's a PX4 firmware issue (so this is the wrong issue location).
No matter what it doesn't go away until I power cycle the autopilot (PX4 1.9.2 stable). I can restart QGC and it doesn't go away.

**Comment by DonLakeFlyer** [comment]
> and it says missing various parameters

If the parameters are missing then there is now way for QGC to know whether vehicles setup is complete or not.

This would be a firmware side problem since the firmware didn't send the set of parameters to QGC which it needs to make vehicle setup work.
