### ISSUE TITLE
Landing pattern error with ardupilot

### ISSUE THREAD

**Issue by kikislater** [mavlink/qgroundcontrol#7589]
## Expected Behavior
Upload mission with landing pattern success to ardupilot fw

## Current Behavior
Upload mission with landing pattern to Pixhawk arduplane 3.9.8 fait with this error : MAV_MISSION_INVALID_PARAM5_X

![image](https://user-images.githubusercontent.com/13238064/61464034-a1fdfe00-a986-11e9-9bcc-a6119bf45834.png)

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Connect to arduplane 
2. Plan a landing pattern 
3. Upload to board
4. Watch error

## System Information
When posting bug reports, include the following information
- Operating System: Archlinux
- QGC Version: 3.5.3
- QGC build: stable
- Flight Controller: Pixhawk 1, SITL in Vagrant
- Autopilot (with version): Arduplane 3.9.8, Arduplane 3.10.0-dev

## Detailed Description
-

## Log Files and Screenshots
none

**Comment by DonLakeFlyer** [comment]
This should be fixed in daily builds. I had thought I brought it across to Stable as well. Let me looka gain.

**Comment by kikislater** [comment]
Yes ! Works fine. 
Out of curiosity, where is related PR ?

**Comment by DonLakeFlyer** [comment]
There are various fixes. Discussion is here with links: https://github.com/mavlink/qgroundcontrol/issues/6783

**Comment by holden-zenith** [comment]
This should be closed
