### ISSUE TITLE
Move from qtgst to gstreamer qmlglsink

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#7590]
The QtGStreamer C++ bindings are very out of date and unmaintained. The last release was in 2014.

There is a qml video sink inside of gstreamer plugins-good now. This is maintained and supported by gstreamer, we should use that.

**Comment by jaxxzer** [comment]
@dogmaphobic please let us know any input or advice here. @tcanabrava is helping.

**Comment by dogmaphobic** [comment]
I was under the impression @tcanabrava was already working on this. I have in my todo list adding runtime, binary plugins to handle video streaming. I decided to wait until this move to qmlglsink was done.

**Comment by tcanabrava** [comment]
I am, this is only a ticket to track the progress

Em qui, 18 de jul de 2019 às 23:14, Gus Grubba <notifications@github.com>
escreveu:

**Comment by patrickelectric** [comment]
Done in #8266
