### ISSUE TITLE
Windows: Update gstreamer packages in deployment

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#7591]
We are currently deploying with gstreamer 1.5.2

We should deploy with gstreamer 1.14 (the latest stable with 32 bit support).

**Comment by DonLakeFlyer** [comment]
Forgot to go back and fix that. Sentera has been running with 1.14 for a bit now.

**Comment by DonLakeFlyer** [comment]
I'll fix it. I'm trying to get organized for a new stable point release.

**Comment by DonLakeFlyer** [comment]
> Sentera has been running with 1.14 for a bit now.

That said, it didn't fix any of the crashing problems.
