### ISSUE TITLE
version 9fd5cbc: CameraManager VideoStop broken

### ISSUE THREAD

**Issue by olliw42** [mavlink/qgroundcontrol#7605]
title says it

**Comment by dogmaphobic** [comment]
Can you expand on that a bit? Is it not sending anything? Sending the wrong thing? Something else?

**Comment by olliw42** [comment]
when in video mode, pressing the red round button sends a startVideo() and the button goes square as usual, but the button gets GRAY and doesn't remain red, from then on it's not possible to get QGC emit a stopVideo() by clicking it. In photo mode it works.

Btw, unrelated, but just to have mentioned it, there are also plenty of gray transparent square widgets popping up all the time when using the camera manager gui.

**Comment by olliw42** [comment]
issue persists in 6ebae0a

**Comment by olliw42** [comment]
new issue raised to bring it up, so closed this
