### ISSUE TITLE
Wrong text color on close popup

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#7615]
On current master when QGC is closed with active connection the warning window has a wrong text color.
It plots black on black(see screenshot)
<img width="512" alt="Schermata 2019-07-24 alle 10 29 05" src="https://user-images.githubusercontent.com/9391950/61778063-57550980-adfe-11e9-8844-006855e8f64d.png">

**Comment by dogmaphobic** [comment]
That's a system dialog. Not something coming from QGC. That is, not something QGC is drawing on its own. That seems to be an issue with Qt and macOS' "Dark Mode".

**Comment by FlavioTonelli** [comment]
@dogmaphobic thank you for your feedback. I didn't notice it was created by macOS itself.
Isn't it fixable then?

**Comment by dogmaphobic** [comment]
I don't know yet. I need to do some research. I know Qt had issues with "dark mode" but it was supposed to have been fixed in Qt 5.12. I'm running 5.12 and I still can see the same issue.

**Comment by dogmaphobic** [comment]
This appears to have been fixed by Qt

<img width="1020" alt="Screen Shot 2019-12-26 at 4 33 05 PM" src="https://user-images.githubusercontent.com/749243/71491226-79174a00-27fd-11ea-9676-2c374d6c685c.png">
