### ISSUE TITLE
PX4 waypoint - Remove MIS_YAWMODE check(s)

### ISSUE THREAD

**Issue by bresch** [mavlink/qgroundcontrol#7621]
`MIS_YAWMODE` does not exist anymore on the firmware side and has been kind of replaced by `MPC_YAW_MODE`. I mean "kind of" because the waypoint heading will always override the behavior dictated by `MPC_YAW_MODE`.
This means that the "heading" option of a waypoint should only check for the type of vehicle (has to be a multorotor) and not for a specific parameter in order to show-hide the widget.

It might be that that parameter is also checked somewhere else and we should make sure to remove those checks.

## Expected Behavior
![Heading](https://user-images.githubusercontent.com/14822839/61942500-d5014c80-af99-11e9-9a8c-51dbd739e386.png)

## Current Behavior
![No_heading](https://user-images.githubusercontent.com/14822839/61942488-cd41a800-af99-11e9-9abe-f6d789c25cde.png)

## Steps to Reproduce:
- Open QGC
- Go to the mission planning tab
- Add a waypoint (it will show heading option)
- Connect to a vehicle (SITL or real one)
- Add a waypoint (it will not show the heading option)

## System Information
Tested on Ubuntu 16.04 and Andoid tablet with current QGC

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Are you working on this. If not I can do it.

**Comment by dogmaphobic** [comment]
I can do it quickly. I just finished the joystick stuff...

**Comment by bresch** [comment]
Thank you guys!
