### ISSUE TITLE
QGC daily build 201907326 top bar on Google Pixel 3

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#7636]
Top toolbar a bit screwed up. The stable build working fine:

![image](https://user-images.githubusercontent.com/5368500/62013896-061d8f00-b1dd-11e9-8c7c-0f724ded9013.png)

**Comment by DonLakeFlyer** [comment]
@hamishwillee Can you try this with latest daily. I think this is fixed now

**Comment by hamishwillee** [comment]
Yes, looks great.
