### ISSUE TITLE
Feature Request - A version for aarch64 architecture

### ISSUE THREAD

**Issue by sbaktha** [mavlink/qgroundcontrol#7637]
It will be great if there is a version that can be used on the Jetson devices which have aarch64 architecture. It will avoid the definite need for another laptop to configure pre-flight parameters rather than using the on-board companion computer itself, if possible.

**Comment by DonLakeFlyer** [comment]
Folks can likely build this themselves. But at this point we don't have the resources to add another supported build type to the mix.
