### ISSUE TITLE
master does not show action buttons

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#7642]
Current master 4b15d5bcf703ae9fa6ee0580e51871fdf976ad62 does not correctly show the action buttons(see screenshot)
<img width="651" alt="Schermata 2019-07-30 alle 14 53 56" src="https://user-images.githubusercontent.com/9391950/62130900-4b73b680-b2da-11e9-88c2-e0fc2e575033.png">

**Comment by DonLakeFlyer** [comment]
I think there is a disabled color theme problem where they are black on black.

**Comment by FlavioTonelli** [comment]
I can confirm they correctly show when active.

**Comment by DonLakeFlyer** [comment]
Also not sure why there is all that blank space between the toolbar and the toolstrip.

**Comment by dogmaphobic** [comment]
Stefan was working on the tool strip. Let me find out what's going on...

**Comment by FlavioTonelli** [comment]
I guess this has been fixed in the meantime. I can't reproduce anymore on master.
