### ISSUE TITLE
MAVLink Inspector awkward with multiple components.

### ISSUE THREAD

**Issue by edwinhayes** [mavlink/qgroundcontrol#7657]
If you have a system with multiple components connected, the MAVLink inspector screen looks like so:

![Screen Shot 2019-08-02 at 16 28 56](https://user-images.githubusercontent.com/15720644/62344608-c808ce00-b542-11e9-9c4c-eeae572ecc38.png)

Usability would be improved if each topic was prefixed by the sID & cID it's coming from, so you can tell the otherwise identical items apart.

And/or having some ability to filter the list.

**Comment by edwinhayes** [comment]
@tilaktilak - for reference.

**Comment by dogmaphobic** [comment]
Yup, this is in my todo list. Filter by compID...

**Comment by thomasgubler** [comment]
Is this fixed by https://github.com/mavlink/qgroundcontrol/pull/7984 ?

**Comment by DonLakeFlyer** [comment]
Believe so
