### ISSUE TITLE
Need help with adding Here+ RTK support for Android

### ISSUE THREAD

**Issue by myeabhishek** [mavlink/qgroundcontrol#7659]
Hello Team,

I want to use Here+ RTK with qgroundcontrol android application. Please tell me how I can go about it? 

I can also add the support myself but I would love if someone can point me in the right direction.

**Comment by DonLakeFlyer** [comment]
Not sure if it's possible given the way serial port code works in Android. Just follow the RTK code which is #ifdef'ed out in mobile builds.

**Comment by wattsinnovations** [comment]
Hello has there been any update with this since August? We would potentially be very interested in assisting with this as well. Thanks!

**Comment by DonLakeFlyer** [comment]
Someone was trying to get it to work but didn't succeed. Not sure where they ran into problems.

**Comment by DonLakeFlyer** [comment]
WIP was here: https://github.com/mavlink/qgroundcontrol/pull/8210

**Comment by DonLakeFlyer** [comment]
Not that I know of

**Comment by HTRamsey** [comment]
Android serial driver is being updated
