### ISSUE TITLE
qt5AndroidDir

### ISSUE THREAD

**Issue by Ayman-git** [mavlink/qgroundcontrol#7663]
Hello, I tried changing the compiledsdk and buildtoolsversion to my version and it solved one of the problems that I was facing, but I found this new error that idk how to solve...

![image](https://user-images.githubusercontent.com/53388390/62456088-c0d30180-b788-11e9-9931-5b8747dbb34e.png)

**Comment by Ayman-git** [comment]
I found out that there is a error in the Mainfest and I think it might be a reason

![image](https://user-images.githubusercontent.com/53388390/62514810-693ca080-b831-11e9-8ea4-fc6f6aa04874.png)

**Comment by dogmaphobic** [comment]
Please ask build questions using the [proper channels](https://app.slack.com/client/T0V5F863B/C629RE9H7)

Github issues are for bugs only. Not to mention it looks like you are using Android Studio?
