### ISSUE TITLE
V3.5 android problem

### ISSUE THREAD

**Issue by zhaolianggoods** [mavlink/qgroundcontrol#7672]
E/libTimUQS.so(23865): ..\TimUQS\src\VideoStreaming\VideoReceiver.cc:273 (void VideoReceiver::start()): VideoReceiver::start() failed. Error with data source for gst_element_factory_make()
E/libTimUQS.so(23865): ..\TimUQS\src\VideoStreaming\VideoReceiver.cc:381 (void VideoReceiver::start()): VideoReceiver::start() failed
The creation of TCP video stream returns to NULL in gst_element_factory_make("tcpclientsrc", "tcpclient-source") during Android debugging

**Comment by zhaolianggoods** [comment]
windows no problem

**Comment by DonLakeFlyer** [comment]
Is this happening on your own build or one of the QGC released builds?

**Comment by zhaolianggoods** [comment]
Is this happing on the QGC released builds,version3.5.0

**Comment by DonLakeFlyer** [comment]
Ok, so first step is to use the latest Stable build: https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html#android and verify it still happens there.

**Comment by zhaolianggoods** [comment]
The latest Stable build: https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html#android .there is a problem.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic @jaxxzer Is this just bad TCP values or some sort of bug?

**Comment by Williangalvani** [comment]
This is happening in the ["gst_element_factory_make"](https://github.com/mavlink/qgroundcontrol/blob/v3.5.3/src/VideoStreaming/VideoReceiver.cc#L288), before setting anything up. I'd guess it is a bug or something is missing.

**Comment by dogmaphobic** [comment]
That would imply a missing library. On Android builds, only a select few (static) libraries are included. I don't think anybody has ever tested this particular pipeline with Android before.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Sentera is having problems with TCP video on iOS as well. It's not working for them on Stable. So probably same thing?

**Comment by DonLakeFlyer** [comment]
Needs to be fixed in Stable.

**Comment by dogmaphobic** [comment]
No, iOS uses a _Framework_. It's all included. I did not add TCP. I don't have anything that sends video this way. Video streaming within QGC is completely out of hand. Things have just been added on top of each other. RTSP for me is so broken to the point of being useless. I don't have enough experience with GStreamer to debug all these issues. I am in the process of exposing the _VideoReceiver_ class so runtime, binary plugins can implement the various video options. That's where my focus is right now.

**Comment by DonLakeFlyer** [comment]
@jaxxzer Can't remember if it was your folks who added TCP support?

**Comment by Williangalvani** [comment]
We only use UDP for now, it looks like it was for Sentera:
https://github.com/mavlink/qgroundcontrol/blame/14d0b71a24676bbd1fe6d2dc1c2963be0558f0c7/src/VideoStreaming/VideoReceiver.cc#L287

**Comment by DonLakeFlyer** [comment]
Ok, so TCP for now is not supported on mobile. It might come back in the next Stable but maybe not.

**Comment by zhaolianggoods** [comment]
Problem solving，Gstream plugin needs to be loaded
