### ISSUE TITLE
Yes/No buttons reversed from common convention in "are you sure you want to close" pop-up

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7679]
The Yes and No buttons in this pop-up are reversed from common convention:
![image](https://user-images.githubusercontent.com/12117027/62989525-fe313200-be0d-11e9-886a-253c7d800ada.png)

Suggest **Yes** on the left and **No** on the right.

Google image search is a wonderful reference tool:
https://www.google.com/search?client=firefox-b-1-d&channel=tus&biw=1278&bih=964&tbm=isch&sa=1&ei=XWxTXZPjHfLrtQaj6L0g&q=no+%2F+yes+popup&oq=no+%2F+yes+popup&gs_l=img.3..0i8i30.23103.24829..25664...0.0..0.73.516.8......0....1..gws-wiz-img.......0i7i30j0i67j0i7i5i30j0i5i30j0i24j0i8i7i30.FukPWV0VTsw&ved=0ahUKEwjThZaCo4HkAhXydc0KHSN0DwQQ4dUDCAY&uact=5

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Some strangeness from the conversion to message boxes?

**Comment by dogmaphobic** [comment]
This is Qt's own message dialog. They determine the order of the buttons. Even the documentation shows a negative before the positive:

![qtlabsplatform-messagedialog-informative-android](https://user-images.githubusercontent.com/749243/63058880-dbf5ed80-bebb-11e9-9085-8a3a6fa2c2b0.png)


https://doc.qt.io/qt-5/qml-qt-labs-platform-messagedialog.html

**Comment by DonLakeFlyer** [comment]
Ick, that order is correct for OSX but incorrect for Windows.

**Comment by DonLakeFlyer** [comment]
Which means Qt bug

**Comment by Antiheavy** [comment]
The same warning popup is Positive then Negative in the Stable release of QGC (I'm using Windows):
![image](https://user-images.githubusercontent.com/12117027/63063995-be795180-bec4-11e9-9743-0ef09c4dcc77.png)

**Comment by dogmaphobic** [comment]
They use different versions of Qt.

**Comment by DonLakeFlyer** [comment]
Stable and Daily windows use the same version of Qt. Different version of Import between Stable/Daily? Maybe go back one (or whatever) to what Stable is using? Or maybe a QGCMessageDialog which isolates the import version usage?

**Comment by dogmaphobic** [comment]
Sorry, QtQuick 1.x versus QtQuick 2.x.

**Comment by DonLakeFlyer** [comment]
I'm not sure about that. MessageDialog (https://doc.qt.io/qt-5/qml-qtquick-dialogs-messagedialog.html) is ```import QtQuick.Dialogs 1.3``` which isn't part of the 2.0 stuff. Stable uses 1.3, Daily uses 1.2. I bet it's just broken in 1.3.

**Comment by dogmaphobic** [comment]
I tested a few variations and realized it makes no difference on macOS. Testing on something else is not that simple right now...

**Comment by DonLakeFlyer** [comment]
Import 1.2/1.3 make no difference on Windows.

**Comment by Antiheavy** [comment]
This seems resolved in the latest daily builds that are using newer version of Qt.  I think I can close this.
![image](https://user-images.githubusercontent.com/12117027/71029750-a402ef00-20d5-11ea-945c-89319fee9440.png)
