### ISSUE TITLE
elevation tile download almost always has errors

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7695]
The elevation tile downloading almost always has a handful of errors.  I suspect this could be fixed by having the map downloader more aggressively retry to download missing elevation tiles automatically.

This seems like a potential safety issue for users depending on terrain data for mission planning.  This has been happening at least since QGC 3.5.  Still happening on current daily builds.

Happens consistently with:
- multiple laptops (Windows)
- multiple internet connections 
- multiple people testing it

We have to almost always go back in and "resume download" to finish off the elevation tiles. I don't think users will actually remember to do this, especially since the elevation tile download is usually very slow.

Here are a number of screenshots showing the handful of "errors":

![image](https://user-images.githubusercontent.com/12117027/63202286-a0d7f380-c04e-11e9-926c-b09694fd2f12.png)

![image](https://user-images.githubusercontent.com/12117027/63202296-ab928880-c04e-11e9-8d41-cf470288fb9d.png)

![image](https://user-images.githubusercontent.com/12117027/63202308-b4835a00-c04e-11e9-9184-4f5d0a9330bd.png)

![image](https://user-images.githubusercontent.com/12117027/63202317-bc42fe80-c04e-11e9-82b4-e0598d74a9ac.png)

![image](https://user-images.githubusercontent.com/12117027/63202283-99184f00-c04e-11e9-9c95-844e577dfdaf.png)

**Comment by Antiheavy** [comment]
Here is a console log output.
[elevation-tile-download-errors_20190506-01.zip](https://github.com/mavlink/qgroundcontrol/files/3511332/elevation-tile-download-errors_20190506-01.zip)

**Comment by Antiheavy** [comment]
Elevation tile downloads seem more reliable in recent Daily Builds.  Has anything changed in the last couple months or so that would make this an expected improvement?

**Comment by DonLakeFlyer** [comment]
nope

**Comment by Antiheavy** [comment]
I haven't noticed this issue with terrain info downloading in a long time.  I'm going to close the issue.
