### ISSUE TITLE
"Done" shows at top of Plan screen for ~5 seconds every time you switch to Plan screen

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7696]
In recent Daily Builds, "Done" shows at top of Plan screen for ~5 seconds every time you switch to Plan screen.  Is this intentional?  seems weird.

![image](https://user-images.githubusercontent.com/12117027/63205627-edcac280-c06c-11e9-8a4b-1ec3b50b2df6.png)

**Comment by kosakwayne** [comment]
This bug still exists in today's Daily Build.

**Comment by stefandunca** [comment]
Please check it in the latest daily

**Comment by Antiheavy** [comment]
> Please check it in the latest daily

fixed!  thanks!
