### ISSUE TITLE
Android usb video 

### ISSUE THREAD

**Issue by pfz4** [mavlink/qgroundcontrol#7715]
Hey, 
please add a USB camera source. So its possible to use a USB 5.6Ghz FPV Receiver.
I think it's because the app doesn't request USB permission for camera devices.

Thanks Paul

**Comment by dogmaphobic** [comment]
Qt does not support UVC devices on Android.

**Comment by CamGenius** [comment]
I have a workaround that I thought I would post here. The Skydroid FPV app works as long as you turn on airplane mode before opening it (you can turn it off again once it is open) then you can press the button for PiP mode and then you can then go ahead and use qgroundcontrol with the video stream on top. Kind of a pain to do every time but at least it is a solution.
