### ISSUE TITLE
Fences shown on Flight Data screen but not on Flight Planner screen

### ISSUE THREAD

**Issue by rmackay9** [mavlink/qgroundcontrol#7760]
The next versions of ArduPilot Copter and Rover will support multiple inclusion and exclusion polygons and circles but I've noticed while testing with QGC that the Flight Planner screen (perhaps there's another name for the screen that users use to create waypoints) isn't correctly showing fences that it knows about if the flight controller has been rebooted.

The screen shots show that QGC knows about two inclusion polygons (they appear on the flight data screen) but they don't appear in the list of fences on the flight planner screen.
![inclusion-polygons-flight-data](https://user-images.githubusercontent.com/1498098/64225537-c0a85c00-cf16-11e9-88b6-f4c3944df392.png)

![inclusion-polygons-flight-planner](https://user-images.githubusercontent.com/1498098/64225540-c30ab600-cf16-11e9-9ce3-e68860e85c87.png)

**Comment by rmackay9** [comment]
This is using a very recent version of QGC "latest" from a week ago or so.

**Comment by DonLakeFlyer** [comment]
Must be some specific sequence problem. I tried this on master:
* Connect to PX4 SITL
* Add fence from Plan View, Upload
* Back to Fly View
* Kill SITL
* Communication Lost, Disconnect
* Restart SITL
* QGC connects, Fly view shows fence
* Switch to Plan View, shows fence

@rmackay9 Can you give me a specific set up steps?

**Comment by DonLakeFlyer** [comment]
Could also be ArduPilot specific but I kind of doubt that.

**Comment by rmackay9** [comment]
@DonLakeFlyer, ah, I guess my wording wasn't very clear at all.  It's actually not restarting the flight controller that causes the issue, it's restarting QGC.

- start up the flight controller
- in QGC connect and create a fence and upload to the flight controller
- restart QGC and you should see the issue

**Comment by rmackay9** [comment]
.. as a side note, on the flight planner screen the "Rally" label which is next to the "Fence" selection button (and below the Upload button) isn't visible.  This little issue is also visible in the screen shot above.

**Comment by DonLakeFlyer** [comment]
> as a side note, on the flight planner screen the "Rally" label which is next to the "Fence" selection button (and below the Upload button) isn't visible. This little issue is also visible in the screen shot above.

If you run latest master the ui for this is changed and should work now.

**Comment by DonLakeFlyer** [comment]
> It's actually not restarting the flight controller that causes the issue, it's restarting QGC.

@rmackay9 Perfect, thanks. I can repro.

**Comment by rmackay9** [comment]
yes, working now, thanks!
