### ISSUE TITLE
Remaining work items for completion of next Stable

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#7770]
Features which work correctly in Stable but are no longer working/missing in master:
* [x] Window size/position is no longer preserved as a setting. This makes testing on master a royal PITA. This used to be in MainWindow.cc. I think it's just gone now. Means you can't resize the window and have it show up that size next boot.
* [ ] Set RC to Param feature is missing
* [x] Allow Mavlink Inspector to float in seperate window (https://github.com/mavlink/qgroundcontrol/pull/8127)
* [X] Analyze Widget Graphing feature is missing
* [x] Plan/Fly buttons are duplicated in the Toolstrip. They need to be removed.
* [x] Multi-vehicle support in MAVLink Inspector is missing. Also filtering is missing: #7657 (Use the vehicle selector in the toolbar to select a different vehicle)

Maintenance work for master:
* [x] Move all builds to Qt 5.12.6
  * [x] Windows
  * [x] Mac
  * [x] Linux
  * [x] Android
* [x] Move windows to 64 bit only and Visual Studio 2017
* [x] Figure out how to get OpenSSL working in android 64 bit version. Currently airmap terrain and pairing are disabled.
* [ ] Update travis build for OSX to sign builds. OSX Catalina is going to prevent currently unsigned builds from running at all.

Extra Credit:
* [ ] Automate iOS release builds upload to Apple Store. So Gus doesn't have to do this manually every time.

**Comment by DonLakeFlyer** [comment]
* Window size/position is no longer preserved as a setting. This used to be in MainWindow.cc. I think it's just gone now. Mean you can't reszise the window and how it show up that size next boot.

**Comment by DonLakeFlyer** [comment]
* Plan/Fly buttons are duplicated in the Toolstrip. They need to be removed.

**Comment by DonLakeFlyer** [comment]
* Mavlink inspector does not support multi-vehicle

**Comment by DonLakeFlyer** [comment]
> * Window size/position is no longer preserved as a setting.

This one should be prioritized first. It makes testing things on master a royal PITA.

**Comment by DonLakeFlyer** [comment]
I merged all the comments into a single list and split into missing feature and maintenance.

**Comment by Antiheavy** [comment]
> Plan/Fly buttons are duplicated in the Toolstrip. They need to be removed.

You are talking about getting rid of these correct?  If so, hooray!
![image](https://user-images.githubusercontent.com/12117027/64490553-b098c100-d223-11e9-8ce0-d907a93a8b9b.png)
![image](https://user-images.githubusercontent.com/12117027/64490559-bbebec80-d223-11e9-8ceb-d15e8c3c2704.png)

**Comment by DonLakeFlyer** [comment]
> You are talking about getting rid of these correct?

Nope. The ones in the toolbar stay. The ones in the toolstrip on the left edge go away. Just like it was before.

**Comment by Antiheavy** [comment]
> The ones in the toolstrip on the left edge go away. Just like it was before.

Ah.  Too bad.  IMHO having them on the left-side toolbar is more intuitive and much better overall.  The look and feel could be adjusted, but switching between Fly and Plan views should feel like you are in the same "screen", but just switching context. Both Fly and Plan are the views that are used every time and should feel like you are interacting with the aircraft.  The top toolbar buttons like App settings, Vehicle setup, and Analyze are very different in they take you to screens "away" from the normal day-to-day interaction with the aircraft.

Anyway, I suppose there is risk of mutiny if you were to take away Plan and Fly from the top toolbar, but whoever moved them down to the left-side toolbar had the right idea IMHO.

**Comment by DonLakeFlyer** [comment]
> Anyway, I suppose there is risk of mutiny if you were to take away Plan and Fly from the top toolbar, but whoever moved them down to the left-side toolbar had the right idea IMHO.

They were duplicated temporarily to solve a custom build case where there was no toolbar items at all. Hence they needed to be somewhere. Not to solve the Fly/Plan really need to merge problem. That's a whole other bucket of complications.

**Comment by DonLakeFlyer** [comment]
@thomasgubler Can I get some sort of timeline from Auterion on fixing the first set of problems? A new Stable can't go out without these being fixed.

**Comment by bkueng** [comment]
The 'onboard files' dialog is also missing.

**Comment by mrpollo** [comment]
@DonLakeFlyer is this still an accurate representation of what's missing before the next stable release?

**Comment by DonLakeFlyer** [comment]
Yup

**Comment by DonLakeFlyer** [comment]
> * Move terrain backend to pulling from a directory of height (zipped .hgt format) file instead of airmap

I bailed out on this one. After doing a pile of work against it I realized I had on 3 arc-second data whereas in some places it looks like airpmap has 1 arc second data. So it ended up being a downgrade. I still have the pull and will get back to some variant of in the future.

**Comment by DonLakeFlyer** [comment]
Fly/Plan in toolstrip removed here: https://github.com/mavlink/qgroundcontrol/pull/8121

**Comment by DonLakeFlyer** [comment]
I'm going to release with these features missing:
* [ ] Set RC to Param feature is missing
* [ ] Allow Mavlink Inspector to float in seperate window
* [ ] Analyze Widget Graphing feature is missing

With details in the release notes as to why. I've waited 6+ months for them to be put back. Time is up.

**Comment by DonLakeFlyer** [comment]
Android OpenSSL stuff can come from here: https://github.com/Auterion/android_openssl.git

**Comment by thomasgubler** [comment]
I think "Analyze Widget Graphing feature is missing" is done through https://github.com/mavlink/qgroundcontrol/pull/8199

**Comment by DonLakeFlyer** [comment]
@dogmaphobic The only thing left here is Set RC to Param. Not sure what that status of that is. If done. You can close this whole thing out.

**Comment by DonLakeFlyer** [comment]
Closing this in favor of detailed individual issues
