### ISSUE TITLE
Error while moving PlannedHome Point

### ISSUE THREAD

**Issue by tilaktilak** [mavlink/qgroundcontrol#7778]
Discussed Here #7765 

If I create a 2 waypoints mission, the first is defined as PlannedHome, the other as WP2.
This error shows while moving the PlannedHome : 
```
DelegateModel::cancel: index out range 0 0
```
![image](https://user-images.githubusercontent.com/6662416/64295754-1e47b180-cfc6-11e9-960d-05cf95f22425.png)

**Comment by DonLakeFlyer** [comment]
A have a feeling this might be a bug in my new arrow stuff.

**Comment by DonLakeFlyer** [comment]
@tilaktilak I'll take alook at this one since it's likely new code I just added.
