### ISSUE TITLE
Flight Planner unable to save fences unless mission is also defined

### ISSUE THREAD

**Issue by rmackay9** [mavlink/qgroundcontrol#7780]
On the flight planner screen the "Plan" panel has a "File" selector button which opens up a window to "Save" the mission and fences to a file.  It seems the "Save" button is greyed out unless a mission is defined.  This means it isn't possible to save a file that only has fences defined.

**Comment by DonLakeFlyer** [comment]
@rmackay9 Latest master/daily build right? I did this:
* Booted QGC without a vehicle connected
* Plan View
* Added a fence polygon
* Click File, see that "Save As" is enabled.
* Do a "Save As".
* Click File, now both "Save" and "Save As" is enabled.

Also tried booting with a vehicle connection with no Plan on it. Same thing.

Maybe some detailed sequence problem again.

**Comment by DonLakeFlyer** [comment]
Trying some different ways to make it happen...

**Comment by DonLakeFlyer** [comment]
@rmackay9 Note the sequence of Save As -> Save. Was "Save As" disabled as well?

**Comment by DonLakeFlyer** [comment]
@rmackay9 Still happening?

**Comment by DonLakeFlyer** [comment]
@rmackay9 Any updates?

**Comment by rmackay9** [comment]
@DonLakeFlyer, ah, sorry, I didn't see the messages, I'll re-test.

**Comment by DonLakeFlyer** [comment]
I've tested and it looks fine. Going close unless we get some concrete repro steps.
