### ISSUE TITLE
Set RC to Param not working in QGC v3.5

### ISSUE THREAD

**Issue by Molecuman** [mavlink/qgroundcontrol#7784]
I have this issue: Selecting "Advanced settings" -> "Set RC to Param..." in Parameter Editor is not working in QGC 3.5 with PX4 v1.9 on Pixhawk, tested on Windows 10. 

![2019-09-06](https://user-images.githubusercontent.com/17263442/64470062-548a4b80-d102-11e9-8b2e-70b38c82f1c9.png)

**Comment by DonLakeFlyer** [comment]
It looks like you are using a Daily build not a Stable build. Set RC to Param is currently not supported in Daily builds. This is tracked here: https://github.com/mavlink/qgroundcontrol/issues/7770. Stable 3.5.4 build has been verified to work.

Are you using a Daily build?

**Comment by Molecuman** [comment]
Hi. Thank you! I downloaded again the QGC and now it works fine.
