### ISSUE TITLE
Label Takeoff waypoint (or indicate as special) in new Fly view visuals

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7796]
I think the Takeoff waypoint needs something special indicating it as Takeoff in the new Fly screen visuals.  When using auto takeoff, it is important for the user to visually confirm the "Takeoff" waypoint is there and in the correct location they plan to takeoff to before they "Start Mission".  Also, it just looks sort weird at the moment:
![image](https://user-images.githubusercontent.com/12117027/64496843-c2538600-d26e-11e9-91f6-ef1d6aab573a.png)

Here is the Plan view for reference: 
![image](https://user-images.githubusercontent.com/12117027/64496831-a223c700-d26e-11e9-86ca-1fdcfbdea437.png)

**Comment by DonLakeFlyer** [comment]
Yeah, I'm working all of this still. There are still multiple problems with it.

**Comment by DonLakeFlyer** [comment]
I think a better way to do this is to only hide the generic waypoing indicators. And show the more "special" items with an indicator.

**Comment by Antiheavy** [comment]
yep, better.  thanks.
![image](https://user-images.githubusercontent.com/12117027/64651520-59dbe480-d3e7-11e9-9bbe-69bba31c421e.png)
