### ISSUE TITLE
OpenSSL dependency issue

### ISSUE THREAD

**Issue by tilaktilak** [mavlink/qgroundcontrol#7798]
With the new master libssl needs to be installed.
Cannot run the AppImage without installing libssl on linux :
`QGroundControl: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
`

**Comment by tilaktilak** [comment]
Ok it might be because I am testing on Ubuntu 18.04 ? Can someone confirm that ?

**Comment by subakioinc** [comment]
OpenSSL is added to current master branch after V3.5.4. So you need to install libssl.

**Comment by DonLakeFlyer** [comment]
This is a dup I bellieve. The Auterion folks needs to fix this.

**Comment by DonLakeFlyer** [comment]
Related to #7743
