### ISSUE TITLE
 ArduPilot: Takeoff must be first mission command

### ISSUE THREAD

**Issue by tilaktilak** [mavlink/qgroundcontrol#7799]
Following #7773 and #6776 

There is no TakeOff added if we create a mission with a complex pattern.
Need to insure a takeoff is added at the beginning of every ArduPilot mission.

**Comment by edwinhayes** [comment]
Semi-related: has there been a change so that now the takeoff waypoint doesn't have a little circle with a "T" colocated with the preceding waypoint (which was usually planned home)?

**Comment by tilaktilak** [comment]
Yes I think it has been discussed here : https://github.com/mavlink/qgroundcontrol/issues/7796
and fixed here : https://github.com/mavlink/qgroundcontrol/pull/7797

**Comment by edwinhayes** [comment]
That discussion seems specific to the fly screen, whereas I'm talking about the plan screen?

**Comment by DonLakeFlyer** [comment]
Yes the Plan screen visuals with respect to Takeoff items without a lat/lon is out of whack right now.
