### ISSUE TITLE
Missing OpenSSL lib for Windows 10 Build

### ISSUE THREAD

**Issue by jeyong** [mavlink/qgroundcontrol#7801]
- Operating System: [Windows 10]
- QGC Version: [master branch]

I met compile error.

master branch build error :
Build error : "LNK1104: cannot open file 'crypto.lib' 

I guess that crypto.lib should be qgroundcontrol/libs/OpenSSL/Windows/x86/lib/ for Windows 10 build.

**Comment by tilaktilak** [comment]
Could probably be related to #7798

**Comment by DonLakeFlyer** [comment]
@jeyong Are you compiling without gstreamer?

**Comment by DonLakeFlyer** [comment]
Yup, the build randomly picks up crypto.lib from the gstreamer install which is incorrect. I think the same thing is happening on Ubuntu 18.04 where I can get it to compile either.

**Comment by DonLakeFlyer** [comment]
I've been having problems with it on Android as well. Maybe the same incorrect gstreamer connection there to. Don't know.

**Comment by jeyong** [comment]
@DonLakeFlyer I also try compiling with gstreamer on Windows 10. I got same error. But it compile on Ubuntu 18.04, it is successful.

**Comment by jeyong** [comment]
@DonLakeFlyer I tried to install gstreamer-1.0-devel-mingw-x86-1.16.0.msi and gstreamer-1.0-devel-msvc-x86_64-1.16.0.msi. Any recommended version or configuration?

**Comment by DonLakeFlyer** [comment]
Follow the instructions here: https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoStreaming/README.md

**Comment by jeyong** [comment]
@DonLakeFlyer Thanks. Now it works.
