### ISSUE TITLE
QGroundControl does not work with UDP broadcasting

### ISSUE THREAD

**Issue by eMrazSVK** [mavlink/qgroundcontrol#7816]
Hello,

I am trying to set up udp broadcasting, so the first connected GCS is being automatically discovered. Firstly, I introduce my setup:

- Pixhawk as a FCU
- Nvidia Jetson Nano as an Onboard computer
- ROS (Mavros) for taking care of communication between Pixhawk and Jetson (physically connected via USB cable)
- Jetson Nano creates a hotspot, to which I am connecting with GCS (laptop with QGround)

So, the UDP broadcasting is set-up on mavros side, with running mavros node like this:
`roslaunch mavros apm.launch gcs_url:=udp-b://10.42.0.255:14550@14550`
I used this based on [this reference](https://github.com/mavlink/mavros/blob/master/mavros/README.md#connection-url). 

The problem is - when I specify exact address of device which I want to connect with (laptop with QGround) it works fine (like this: `roslaunch mavros apm.launch gcs_url:=udp://@10.42.0.99`). When I run mavros with udp broadcast method, my GCS connects fine, gets detected, but gets stuck at downloading parameters from FCU and I get following error: 

> Vehicle 1 did not respond to request for parameters. This will cause QgroundControl to be unable to display its full user interface

I know that problem can be also on mavros's side, but please understand, that I have to start somewhere to find out the solution.

Thank your for your help!

**Comment by DonLakeFlyer** [comment]
That means that although the Vehicle->GCS comm direction is working. The GCS->Vehicle direction is not. Given the fact that there are no complaints on general udp not working you are going to have to debug this in the QGC code starting at UDPLink.* to figure out what is going on.
