### ISSUE TITLE
Current Daily: after placing a survey, Waypoint tool becomes active

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7835]
In the current daily build, after placing a Survey Pattern, the Waypoint button becomes active.  This means if the user clicks on the map a waypoint appears and kicks them out of the survey settings.  This is too easy to accidentally do and if the user doesn't notice the extra waypoint added this could lead to confusion and problems.
![image](https://user-images.githubusercontent.com/12117027/65809877-1fed3b00-e168-11e9-99ab-4229a1089257.png)

**Comment by Antiheavy** [comment]
This also happens in the new Plan Wizard and is very confusing for the user as disconnected waypoints start getting added after the Landing Pattern and it's unclear to the user why just clicking on the map started adding these.
![image](https://user-images.githubusercontent.com/12117027/66673101-81f87680-ec25-11e9-8fa2-99a55a1ee6de.png)

**Comment by DonLakeFlyer** [comment]
Should be fixed now
