### ISSUE TITLE
Modify QGCQmlWidgetHolder.ui

### ISSUE THREAD

**Issue by nmr86** [mavlink/qgroundcontrol#7851]
win 10 64
QGC 3.5
build for android

Hello, I would like to change the mobile UI, I placed a few more elements on the QGCQmlWidgetHolder, but qmlwidget takes all the place in full screen. I tried to make the qmlWidget properties fixed and corrected the qml file (set fixed size), but each time I get only qmlWidget in full screen. How and where can I fix the qmlWidget size so that there is room for my QPushButton and QLineEdit

**Comment by DonLakeFlyer** [comment]
As you've discovered you can't use QGCQmlWidgetHolder on mobile. There is no way to make it work. All mobile Windows are always fulls screen. Also in master this functionality no longer exists.
