### ISSUE TITLE
Missing Parameters mentioned multiple times

### ISSUE THREAD

**Issue by MaEtUgR** [mavlink/qgroundcontrol#7858]
## Expected Behavior
If parameters that are necessary are missing from what the autopilot exposes you get a warning with the list of parameters that are missing each mentioned only once.

## Current Behavior
I get the warning but one parameter is mentioned 10 times in a row.

## Steps to Reproduce
Please provide an unambiguous set of steps to reproduce the current behavior
1. Load SITL or a vehicle with some parameters missing e.g. built from https://github.com/PX4/Firmware/commit/c322f1d1568b73327916ce2363c80375e3b5485b
2. Connect QGC daily to the vehicle or SITL
3. See warning with repeated first parameter

## System Information
When posting bug reports, include the following information
- Operating System: Found on Windows 10 and Android
- QGC build: latest daily
<img width="217" alt="qgc-version" src="https://user-images.githubusercontent.com/4668506/66141844-b5734980-e604-11e9-99af-47e908a84887.PNG">

- Flight Controller: Pixhawk 4 mini, SITL
- Autopilot (with version): PX4 not exposing some commander parameters QGC is expecting

## Screenshot
<img width="432" alt="qgc multiparameter" src="https://user-images.githubusercontent.com/4668506/66141868-c02dde80-e604-11e9-9877-13d384afd5e7.PNG">

**Comment by MaEtUgR** [comment]
@DonLakeFlyer Thanks a lot for the fix! I tried to verify with my setup but couldn't because I ran into: https://github.com/mavlink/qgroundcontrol/issues/7878

**Comment by MaEtUgR** [comment]
Verified to be fixed 👍 
![qgc](https://user-images.githubusercontent.com/4668506/66368214-af2ff500-e997-11e9-8e43-076b913150d5.PNG)
Although I don't understand why it always says `-1` in front of the collon.

**Comment by DonLakeFlyer** [comment]
Reopening to fix the -1. That is an internal QGC things which means default component id.

**Comment by DonLakeFlyer** [comment]
-1 should be gone now as well

**Comment by MaEtUgR** [comment]
@DonLakeFlyer Now it shows 1 instead of -1. It's probably not what you expected because I still don't understand why:
<img width="455" alt="qgc" src="https://user-images.githubusercontent.com/4668506/66909304-d0828800-f00c-11e9-8cdd-c54a88f225a8.PNG">

**Comment by DonLakeFlyer** [comment]
That is correct behavior. The 1 is the component id. Parameters with the same name could come from different components: PX4 Flow, ESP8266, ...
