### ISSUE TITLE
Custom elevation data import

### ISSUE THREAD

**Issue by cosmarc** [mavlink/qgroundcontrol#7864]
Are there any plans to add the possibility of loading custom elevation data into QGC by loading 
 for example GeoTIFF, LAS, DEM, ASC, etc. files?
Related: #7818

**Comment by DonLakeFlyer** [comment]
Yes, someone is working their way towards that. But it is a large work item. Not sure when it will come in.

**Comment by tilaktilak** [comment]
I am on it at the moment, I expect sending a PR in couple of weeks for the second part of the job.

**Comment by cosmarc** [comment]
@tilaktilak Would you like to share more about what formats you want to support and how did you envision the solution? We're trying to implement something similar and therefore we can probably share some work/ideas.

**Comment by tilaktilak** [comment]
Oh sure,
my answer is here #7818 (to keep track of stuff at the same place).
I am definitively keen to share work/ideas with you guys :-) !
