### ISSUE TITLE
Survey Pattern: qground crashed when setting 0 value to spacing

### ISSUE THREAD

**Issue by SajyBug** [mavlink/qgroundcontrol#7870]
when i create new survey pattern and set 0 value to spacing the app get to slow and not working well 
![Screenshot from 2019-10-05 15-28-30](https://user-images.githubusercontent.com/21136372/66254732-78839000-e787-11e9-8487-77e5792bbaa1.png)

**Comment by hamishwillee** [comment]
@SajjadRahnama You do realise that a zero spacing means an infinitely dense grid right? Effectively you have created billions of waypoints to represent this line.

@DonLakeFlyer I guess this means enforcing minimum non-zero grid spacing?
