### ISSUE TITLE
Tag for last qt widget build is screwing up versioning of Play android

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#7874]
Version is displayed as the lastQtWidget tag instead of a version number

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Do you think you could changes this to a branch and remove to tag?

**Comment by dogmaphobic** [comment]
I did that way back when. The branch is here:
https://github.com/mavlink/qgroundcontrol/tree/LastQtWidgetBuild

I had also deleted the tag but it seems it's "stuck". I just tried deleting the tag again and even though it seems it goes through fine, when listing the tags, it is still there.

**Comment by DonLakeFlyer** [comment]
Thanks Gus. I'll try to fight with it then.

**Comment by DonLakeFlyer** [comment]
Hmm, it doesn't show up here any more: 
![Screen Shot 2019-10-06 at 10 19 53 AM](https://user-images.githubusercontent.com/5876851/66272784-e6c96080-e822-11e9-858c-eb1a4ae7b43f.png)

Confused...

**Comment by DonLakeFlyer** [comment]
Looks to be all good now. On to the next problem with Google Play...
