### ISSUE TITLE
Feature request: autorange ground speed for rovers (distance would be nice also)

### ISSUE THREAD

**Issue by Hwurzburg** [mavlink/qgroundcontrol#7887]
if ground speed <10 (whatever units), switch to %2.1d format to show tenths of unit....rovers, especially boats, move slow....(my boat's cruise speed is 1.6mph)
we do this in the OSD displays for speed and distance in Ardupilot...

**Comment by DonLakeFlyer** [comment]
What value is showing without a single decimal place and where?

**Comment by Hwurzburg** [comment]
ground speed in the instrument panel on the flight page
distances there would be nice to autorange also (ie distance to home)

**Comment by DonLakeFlyer** [comment]
This was a problem with decimal place conversion when there was unit conversion.

**Comment by Hwurzburg** [comment]
tested today...works great...thanks
