### ISSUE TITLE
New Plan Wizard(s): can't get the wizards back after "X"ing out

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7899]
After hitting the "X" in the upper right corner, you can't get the wizards back unless you exit the application and come back in.  I think if you exit Plan screen and come back to the Plan screen this should re-appear (unless there is an existing plan loaded).
![image](https://user-images.githubusercontent.com/12117027/66590209-da604300-eb55-11e9-9669-b4c7962681f2.png)

**Comment by Antiheavy** [comment]
Or maybe any time you select New the "Create Plan" box should show up, even if there is an existing mission onscreen (e.g. there is an old mission on vehicle that was downloaded upon connection):
![image](https://user-images.githubusercontent.com/12117027/66592808-66c13480-eb5b-11e9-8ee7-7140e4893932.png)

**Comment by Antiheavy** [comment]
Actually, if the "New..." button wasn't grayed out, I think this would fix the problem.

**Comment by DonLakeFlyer** [comment]
> Actually, if the "New..." button wasn't grayed out, I think this would fix the problem.

Yes, this is a great idea.
