### ISSUE TITLE
Plan Wizard: can't move survey polygons

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7900]
using the new Plan Wizards, the center dot of the polygon does not work for moving the shape - this is particularly required for circles..., but should work for all.:

edit: It seems to only be broken when in the "adjust survey" text is active in the Wizard Box.  it is able to move after you come back and make further edits.

![image](https://user-images.githubusercontent.com/12117027/66593833-69248e00-eb5d-11e9-9628-8163ef96d35d.png)

**Comment by tilaktilak** [comment]
Also, from today Daily, I am not able to split the sides of the polygons with : ![image](https://user-images.githubusercontent.com/6662416/67729368-b48fd500-fa55-11e9-9205-00cd4a244dc4.png)
