### ISSUE TITLE
Request: new Polygon Tools looks jarring

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7902]
weird looking menu with the title on the right side and lots of empty space on the right side.
![image](https://user-images.githubusercontent.com/12117027/66608796-07741c00-eb7d-11e9-9cd3-2a6ca82f664a.png)

Maybe a centered version with less empty space?
![image](https://user-images.githubusercontent.com/12117027/66608951-62a60e80-eb7d-11e9-9616-fad82b66234a.png)

**Comment by tilaktilak** [comment]
I am also concerned about this new toolbar. 
First of all it does not follow the theme colors, it could be confusing to find that now the left-hand toolbar is not the main one but this one is. 

Maybe this Basic/Circular/Polygon/Load KML/SHP can replace the left-hand toolbar during the time the polygon is defined ? And can then use a similar style (black and white icon based vertical toolbar).

**Comment by DonLakeFlyer** [comment]
Fixed
