### ISSUE TITLE
Request: add "Open saved mission" as a Create Plan option

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7904]
Lots of our users like to save missions and open them once they get to the field.  Seems like a natural place to put a "Open saved mission" option along-side the other create plan options:

![image](https://user-images.githubusercontent.com/12117027/66610351-e1e91180-eb80-11e9-9a17-b3d57170c9d3.png)

**Comment by DonLakeFlyer** [comment]
Already there with new File drop panel approach
