### ISSUE TITLE
`CameraCalc.qml` could not be found under PlanView

### ISSUE THREAD

**Issue by BriFuture** [mavlink/qgroundcontrol#7913]
Hi, I have encountered a problem when using QtCreator to build QGroundControl:

![image](https://user-images.githubusercontent.com/7582298/66711576-06333100-edc1-11e9-8560-57c861716da3.png)

As it says, `CameraCalc.qml` could not be found under PlanView.

And I checked the `PlanView` src directory, only `CameraCalcCamera.qml` or `CameraCalcGrid.qml` is found, while the CMakeLists.txt contains a file named `CameraCalc.qml`.

![image](https://user-images.githubusercontent.com/7582298/66711591-4e525380-edc1-11e9-9135-05d7bebde145.png)

Is That a Typo? How should I get rid of this error, rename `CameraCalc.qml` to `CameraCalcCamera.qml` or `CameraCaclGrid.qml`?

```
OS: Ubuntu 18.04
IDE: QtCreator  4.10  Qt 5.12.1
QGroudControl Version: 3.6.0 Daily Build
```

**Comment by DonLakeFlyer** [comment]
Use qmake not cmake. Cmake is not up to date.
