### ISSUE TITLE
Weird window movement when reviewing a .TLOG

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [mavlink/qgroundcontrol#7916]
- Ground station operating system -> MacOS Mojave 10.14.6 (Also tested on others MacOS)
- QGroundControl version and build -> v3.5.4
- Autopilot board -> mRo x2.1
- Autopilot firmware -> Arducopter 3.6.10
- Open QGroundControl > File > Replay Flight Data > Open any .TLOG file

Here is a quick Video:

[<img src="https://img.youtube.com/vi/HXnb3Ave8UA/maxresdefault.jpg" width="50%">](https://youtu.be/HXnb3Ave8UA)

**Comment by DonLakeFlyer** [comment]
I believe this is fixed in Daily Builds

**Comment by DonLakeFlyer** [comment]
Can you try to repro there?

**Comment by Alexandre-Mainardi** [comment]
> Can you try to repro there?

Sure

**Comment by Alexandre-Mainardi** [comment]
Fixed. Thanks @DonLakeFlyer

**Comment by DonLakeFlyer** [comment]
Thanks for verifying
