### ISSUE TITLE
Random map provider on daily?

### ISSUE THREAD

**Issue by MaEtUgR** [mavlink/qgroundcontrol#7920]
## Expected Behavior
QGC shows the map as usual, either there's a default map that has world wide coverage or there's a prompt to choose one to begin with.

## Current Behavior
I first notices the whole map view just being white 2 days ago on daily. Now I realized with that older version or todays daily it's basically random what map I get on any boot. And the map provider is always unselected in the settings:

## Log Files and Screenshots
<img width="1307" alt="qgc_map_provider" src="https://user-images.githubusercontent.com/4668506/66918444-a9818180-f01f-11e9-839b-b8bb6a2767bf.PNG">
<img width="1307" alt="qgc_map" src="https://user-images.githubusercontent.com/4668506/66918436-a4bccd80-f01f-11e9-9637-f7a04c81525a.PNG">
<img width="1308" alt="qgc1" src="https://user-images.githubusercontent.com/4668506/66919575-dc2c7980-f021-11e9-84cb-04d61850b0f9.PNG">
<img width="1308" alt="qgc2" src="https://user-images.githubusercontent.com/4668506/66921774-231c6e00-f026-11e9-9d82-fb767f0c688b.PNG">
<img width="1309" alt="qgc3" src="https://user-images.githubusercontent.com/4668506/66921783-27488b80-f026-11e9-9e26-5c22c9928059.PNG">

FYI @MatejFranceskin @DanielePettenuzzo

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10 and Manjaro 18 (up to date)
- QGC Version: 
<img width="904" alt="qgc_version" src="https://user-images.githubusercontent.com/4668506/66919476-b0a98f00-f021-11e9-993f-203b75bce105.PNG">
- Flight Controller: None/PX4 master SITL

**Comment by DonLakeFlyer** [comment]
@tilaktilak Is working on it

**Comment by MaEtUgR** [comment]
Thanks, it works again :+1:
