### ISSUE TITLE
Save survey polygon as kml

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#7951]
Hi

I need to save survey polygon in every flight for planing next flight planing.

Also it is be good that we can see a large kml borders in map and design survey polygon  manually.

**Comment by DonLakeFlyer** [comment]
> I need to save survey polygon in every flight for planing next flight planing.

Why not just save the Plan file, Reopen and edit as needed?

**Comment by DonLakeFlyer** [comment]
> Also it is be good that we can see a large kml borders in map and design survey polygon manually.

This is already in another feature request somewhere. I might be able to get to it in 4.1.

**Comment by DonLakeFlyer** [comment]
Closing since there is another workflow which would seem to work fine
