### ISSUE TITLE
Plan Wizard:  make unplanned wizard items more obvious and Warn/prevent Upload

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7957]
The little red question mark isn't a very obvious indicator that the wizard item is unplanned and needs finishing.

![image](https://user-images.githubusercontent.com/12117027/67720589-5524bd00-f9a2-11e9-8f5f-f48a89152297.png)

Maybe use much larger question marks?  or maybe highlight the entire box in red as well?  Or something else that makes it obvious and intuitive.
![image](https://user-images.githubusercontent.com/12117027/67720670-96b56800-f9a2-11e9-923d-f1aa90217407.png)

Also, should Upload be warned against or blocked if there are unfinished wizard items?
![image](https://user-images.githubusercontent.com/12117027/67720834-0fb4bf80-f9a3-11e9-96b8-1003509fe94b.png)

**Comment by DonLakeFlyer** [comment]
> Also, should Upload be warned against or blocked if there are unfinished wizard items?

Upload should error out in this case. If not, it's a bug. The button should be available though. Same for Save.
