### ISSUE TITLE
 kml saved file cannot be opened in Google earth

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#7967]
Msision waypoints that saved in kml file cannot be opened in Android Google earth . i find mistake in code and created a pull request .

https://github.com/mavlink/qgroundcontrol/pull/7953

**Comment by FlavioTonelli** [comment]
If you pushed a pull request, this is not an issue anymore. There is therefore no reason to open an issue here. 
I'm sure the maintainer of the code is going to evaluate your request as soon as he can.

**Comment by DonLakeFlyer** [comment]
Fixed
