### ISSUE TITLE
Version Check 4.0

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#7972]
![image](https://user-images.githubusercontent.com/562809/68047934-c71d3f00-fcdf-11e9-93d2-3e6473181f4c.png)

The german message means
“QGroundControl supports Version 3.4 and up. You are using an older Version…”

ArduPlane 4.0.0
QGC 3.5.5

**Comment by jaxxzer** [comment]
Confirmed 👍

**Comment by DonLakeFlyer** [comment]
Will do out once Stable has some additional build up of fixes
