### ISSUE TITLE
TAKEOFF Flight Mode not configurable

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#7973]
TAKEOFF (RCx_OPTION = 77) is not selectable in RCx_OPTION drop down.

ArduPlane 4.0.0
QGC daily 2019-10-29

**Comment by DonLakeFlyer** [comment]
This option does not exist in the Plane 4.0 parameter meta data. Asking ArduPilot folks why that is since it is listed in the docs.

**Comment by DonLakeFlyer** [comment]
This is a bug in Plane 4.0 metadata. Asking if I should just hack the value into QGC.

**Comment by twistedwings** [comment]
I don't think so. If it's a firmware bug it should be fixed in the firmware.
