### ISSUE TITLE
CameraManager, CameraPageWidget: spurios grey rectangle

### ISSUE THREAD

**Issue by olliw42** [mavlink/qgroundcontrol#7976]
When the camera page widget is opened I more often than not see a grey rectangle showing up. See pictures below for examples. (I've mentioned this issue sporadically in other places, but now think it should get it's own issue)

I have no idea where this coming from, so just can report some more observations:
* I'm on Win7. 
* I observe this since the change to QtQuick ca 3 months ago or so.
* I observe this for my own build as well as for all daily builds I've tested in the last 3 months.
* I could not identify any systematics. That is, the rectangle may show up as shown in the pic, it may also show up in other locations, sometime more to the left, sometimes more to the right, bottom or top. The exact time of showing up also varies. Sometimes it shows up immediately, sometimes when I hover a particular field. Also the duration varies. Sometimes it stays present once poped up, sometimes it may go away, and sometimes it may go away and come back.
* I always can only see it when the camera PageWidget is opened, and it always goes away when it is closed.
* It is located before the background flight view, but behind the camera page widget.
* This is NOT only happening for the CameraPageWidgets, but also for the ValuesPageWidget!

That's all I can report.

![qgc-grayspurions](https://user-images.githubusercontent.com/6089567/68161592-782d0f00-ff56-11e9-8c7a-c3f9285a7869.jpg)

![qgc-greyspurion-value](https://user-images.githubusercontent.com/6089567/68169022-feebe700-ff6a-11e9-9153-30c4d07d32bb.jpg)

**Comment by dogmaphobic** [comment]
I had noticed this behavior when using a `Menu` from QtQuick.Controls 2.x. That's why we moved all instances of `Menu` to `QGCMenu` to make sure they were from QtQuick.Controls 1.x. This only happened when using Menus over a map. Something else in PageView is causing this and I can't quite tell what it is.
