### ISSUE TITLE
Plan Wizard: Custom plan should not have wizard items, let user plan from scratch

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8004]
This could be just my opinion, but it seems like if someone selects "custom" they should be allowed to plan an entire mission from scratch, just like they always have been able to with QGC.  i.e. "custom" should launch them into the full blown traditional plan screen with no wizard helpers on the right side.

![image](https://user-images.githubusercontent.com/12117027/68537100-55b73f00-0324-11ea-96e7-cc29781c34ac.png)

Who knows if a takeoff an a couple normal waypoints are even what are intended in their custom mission.... could be something totally different, actually probably is something different in most cases.

**Comment by DonLakeFlyer** [comment]
Yeah, I agree. I was just trying some things out there.
