### ISSUE TITLE
Plan toolbar: Azimuth/Heading show same value

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8011]
Azimuth shoudl be change in heading

**Comment by hamishwillee** [comment]
Thanks. I understand heading is relative to north. Are you saying azimuth is relative to the line connecting the previous waypoint?

**Comment by DonLakeFlyer** [comment]
> Are you saying azimuth is relative to the line connecting the previous waypoint?

Correct

**Comment by DonLakeFlyer** [comment]
So this is working correctly. It just confusing:
* Azimuth - Angle from previous waypoint to current
* Heading - Angle from current waypoint to next

**Comment by hamishwillee** [comment]
@DonLakeFlyer Based on QGC 3.5.5 and your definition I still think this is "a little" broken. If the heading is angle is from current waypoint to next then surely it should be NA if you're creating a new waypoint and there is no next waypoint?

**Comment by DonLakeFlyer** [comment]
The heading value is a bit odd. It is the expected vehicle heading at the waypoint. If there is no next waypoint then the heading just keeps going in the current direction. If there is another waypoint, then the heading points to that next waypoint.

**Comment by hamishwillee** [comment]
OK, so:
- Azimuth - Heading from previous waypoint to current waypoint.
- Heading - Vehicle heading at waypoint (to next waypoint). For the final waypoint this is the expected heading (ie the path of the line to the current waypoint).

If that's reasonable docs this can be closed (and I'll update docs).

**Comment by DonLakeFlyer** [comment]
Correct. And all of which is so not memorable it makes me wonder why it's in there in the first place.
