### ISSUE TITLE
Autoconnect failures on OSX Catalina

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8012]
Users are reporting autoconnect not working over usb on Catalina.

**Comment by cosmarc** [comment]
@DonLakeFlyer OSX Catalina dropped support for 32bit binaries. Can this be the problem? Some usb-related stuff might got rewritten.

**Comment by DonLakeFlyer** [comment]
QGC OSX is 64 bit

**Comment by DonLakeFlyer** [comment]
Just tested and it's all working fine
