### ISSUE TITLE
'mavlink_types.h' file not found

### ISSUE THREAD

**Issue by devd77** [mavlink/qgroundcontrol#8016]
This system is for posting bugs or feature requests ONLY. For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

----
When posting bug reports, include the following informaiton:
- Ground station operating system.
- QGroundControl version and build (daily, stable, self-built from source, etc.)
- **If you are using a Stable build which is not the latest, first step is to install latest Stable build and try again prior to entering a bug report.**
- Autopilot board: Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.
- Autopilot firmware (e.g. PX4, ArduPilot, custom) and version.
- Exact steps to reproduce the problem. Starting from booting QGroundControl to when the problem occurs.

**All this template text should be deleted before creating your issue.**

**Comment by devd77** [comment]
--I have cloned this repository on my system by "git clone https://github.com/mavlink/qgroundcontrol.git --recursive"
--and then run command: git submodule update
--then it on QT Creator
--Build for iOS Simulator Debug
--Then i have found "mavlink_types.h' file not found" this issue.

It was working before, but in new clone i have found this issue
Anyone can tell me the solution
Thanks in Advance :)

**Comment by tilaktilak** [comment]
Not sure it's your problem but you can try ```git submodule update --init --recursive``` instead of ```git submodule update```

**Comment by devd77** [comment]
> git submodule update --init --recursive

Thanks, but its still showing same error

**Comment by devd77** [comment]
Same problem, not finding any solution

**Comment by DonLakeFlyer** [comment]
Delete and start over from scratch again

**Comment by devd77** [comment]
> Delete and start over from scratch again

I have tried but facing same problem
i am using QT 5.12.5 to build for iOS

**Comment by DonLakeFlyer** [comment]
Qt would have nothing to do with it although you should be using 5.12.6 which is the supported version. This is just git problems unrelated to QGC.

**Comment by devd77** [comment]
> Qt would have nothing to do with it although you should be using 5.12.6 which is the supported version. This is just git problems unrelated to QGC.

Thanks, will try from scratch again
