### ISSUE TITLE
ComboBoxes not sizing correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8021]
![Screen Shot 2019-11-12 at 9 05 12 AM](https://user-images.githubusercontent.com/5876851/68693126-97660680-052b-11ea-947d-3da97264be2e.png)

**Comment by olliw42** [comment]
IMHO they not only sometimes don't size properly, but also look ugly in general!

I don't like the double arrows
I don't like the arrows to have such a large gap from the right edge
I don't like the arrows to be that big
I don't like that the text has such a small gap from the left edge
I don't like its outline is so high, so much higher than a button or text field
I don't like that its dropdown is so spaceous, which such large spacing between the text
they just don't fit well into the overall design but stick out as odd
you get it, I don't like the new combo boxes, and would very much appreciate if some if not all of these points would be improved
but I also understand that design is highly subjective, so just my 2 cents :)

**Comment by DonLakeFlyer** [comment]
I agree with most of that. They were changed a while back and they are somewhat nasty looking.

**Comment by Antiheavy** [comment]
> somewhat nasty looking

/agree

**Comment by DonLakeFlyer** [comment]
I think this is good for now. I'll may come back to it.

**Comment by olliw42** [comment]
it indeed has MUCH improved !! 
Many thx.
