### ISSUE TITLE
Win10 Crash when enabling "Advanced" tuning

### ISSUE THREAD

**Issue by mwiatt** [mavlink/qgroundcontrol#8032]
## Expected Behavior
Advanced tuning screen displays

## Current Behavior
QGC crashes as soon as "Advanced" checkbox is ticked in the "Tuning" section

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Start QGC
2. Connect autopilot
3. Check "Advanced" box on "Tuning" page

## System Information
When posting bug reports, include the following information
- Operating System: Win10
- QGC Version: Daily (11/13/2019)
- QGC build: Daily
- Flight Controller: 2.1 Cube
- Autopilot (with version): PX4 1.9.2

I verified this does not happen with the current 3.5.5 release.

**Comment by DonLakeFlyer** [comment]
Dup #7962
