### ISSUE TITLE
Latest daily build closes after connection

### ISSUE THREAD

**Issue by highfreq** [mavlink/qgroundcontrol#8045]
Tried latest build today, it closes itself after 10-20 seconds.

Everythong works, it connects to vehicle and starts video but after a short while it closes with no errors.

I am still running 3.6.8, don’t know if it needs latest stable to work correctly.

It happens in compatibility and safe mode too.

It happens only if the uav is connected to the ground station, if i don’t connect it than QGroundcontrol never closes. As soon as i turn on the uav and it connects and finishes fetching the parameters than QGC closes.
I am running it on windows 10 64bit pc.

**Comment by DonLakeFlyer** [comment]
Instructions here: https://docs.qgroundcontrol.com/en/Support/Support.html will show you where to get the crash dump file for QGC. Zip up that file, put it someplace and link to it here.

**Comment by highfreq** [comment]
dump:

https://mshelisrl-my.sharepoint.com/:u:/g/personal/davide_monti_mshelisrl_onmicrosoft_com/EenVINRfYCNIg-gFbUdZW7kBKfKD7BBizqM7E1rW4vMTJA?e=Plo5dy

**Comment by DonLakeFlyer** [comment]
I can't seem to get that dump file to load correctly. Possible because the daily build has moved past the version you are using. Can you instead install this special daily build from here: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/QGroundControl-installer.exe. Get it to crash again and link to the new dump file.

**Comment by highfreq** [comment]
Here is the dump from the linked version. This version doesn't even start.

https://mshelisrl-my.sharepoint.com/:u:/g/personal/davide_monti_mshelisrl_onmicrosoft_com/EauqwOFdvs9Hhop9Q2TeQkIBvwJJXIvWsWfKB-PUWV7fKg?e=I0eiAz

**Comment by DonLakeFlyer** [comment]
Sorry my screw up. I was testing dmp file debugging with QGC and put in a forced crash for testing. Forgot to take it our before I built the installer! There is a new installer which doesn't crash (at least right away) at the same link.

**Comment by highfreq** [comment]
The one you linked doesn't crash, but i can't find where to use additional joystick axis for the gimbal and video looks like is not configurable.
Is it a special version to just find the crash problemù?

**Comment by DonLakeFlyer** [comment]
Should be fixed now in latest released daily builds. Could you verify?

**Comment by highfreq** [comment]
Ok thanks now it works.
It is sad it is useless for me because gimbal has no joystick assignment and no mount control on joystick. I would really love to use it but as it is now i have no gimbal control. Thank you anyway.
