### ISSUE TITLE
Plan Wizard: Takeoff text when no vehicle connected

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8070]
When not connected to a vehicle, add additional wizard text to the Takeoff item to move the Launch location as well as the Takeoff location.  Suggested text:

**When not connected to a vehicle with a Home location:**
"Move L 'Launch' near the planned launch location."
"Move T 'Takeoff' to the climbout location."
"Ensure clear of obstacles and into the wind."

**When connected to a vehicle with a Home location:**
"Move T 'Takeoff' to the climbout location."
"Ensure clear of obstacles and into the wind."

![image](https://user-images.githubusercontent.com/12117027/69497833-e22a3b80-0ea6-11ea-9344-57308fa405b6.png)

**Comment by DonLakeFlyer** [comment]
That is how it should already be working but I'll double check

**Comment by DonLakeFlyer** [comment]
So this works differently now when not connected. The Launch position is set by a click, and the T is then moved if needed. So I think this is all good.
