### ISSUE TITLE
UI - Vehicle Number selector only appears if more than one vehicle present?

### ISSUE THREAD

**Issue by igalloway** [mavlink/qgroundcontrol#8076]
The vehicle selector only appear when there is more than one vehicle. Why  not leave it in place? 
I ask because if i have for example three numbered vehicles and want to confirm which one i am connected to (when only one is powered on initially) i dont' see the vehicle number until a second one is powered up.

**Comment by DonLakeFlyer** [comment]
> The vehicle selector only appear when there is more than one vehicle. Why not leave it in place?

Because 99% of users never use multi-vehicle. If you need to see the vehicle id it is available from the Setup/Summary page.
