### ISSUE TITLE
Multiple ROIs can be created on a waypoint

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgroundcontrol#8079]
QGC Daily build 20191202, running on Ubuntu 18.04 in a VM.

The new ROI button allows you to create multiple ROI on the one waypoint, which while possible in the mission definition, does not make sense.

The expected model is that you create waypoints, then you press the "Add ROI" button and select the map to create the waypoint. The **Add ROI** button is immediately deselected, so you can move the ROI if you want on the map. Then you can add new waypoints.
However if you select the **Add ROI** button again you can add another ROI (and repeat as many times as you like).

IMO if an ROI exists for the currently selected waypoint then creating another should delete the existing waypoint and recreate another at the new point. 

The UI interaction could then be that after selecting **Add ROI** button it remains selected - if you click the map multiple times the ROI would then just appear to move to the new position (but would actually be deleted/recreated). 

Alternatively you might auto-select the add waypoint button after auto-deselecting the add Add ROI button - but I don't see that as quite as intuitive.

**Comment by DonLakeFlyer** [comment]
Fixed
