### ISSUE TITLE
Feature Request: Display Lat/Long/Alt of current cursor location

### ISSUE THREAD

**Issue by mwiatt** [mavlink/qgroundcontrol#8092]
When in "Plan" or "Fly" view, it would be useful to display the lat/long/alt of the current cursor location. An option to enable/disable this would be nice for size limited displays. Something similar to the "Scale" overlay in the bottom corner of the display would work well.

**Comment by Antiheavy** [comment]
This is a good request. At least for non-mobile builds.

**Comment by kevinjhur** [comment]
Any progress?

**Comment by rosiakpiotr** [comment]
Hello, I would love to bring back attention to the issue as it appears a little bit stale and there have been many times we could find  the feature very helpful.
