### ISSUE TITLE
RTK should be on MainToolbar so it shows without vehicle connected

### ISSUE THREAD

**Issue by dlwalter** [mavlink/qgroundcontrol#8094]
I believe RTK should be a part of the GCS, not the aircraft.  Looking through the project it appears that the philosophy follows GCS buttons and functionalities being on the MainToolbar and aircraft buttons being on the MainToolbarIndicator (Although the GCS buttons aren't indicators, are they...) that way aircraft dependent indicators only appear when the aircraft is connected.

The GPSRTKindicator could be moved from the Indicator Toolbar to the the Main Toolbar next to the Analyze button.

This would allow the operator to see the RTK Survey-In state without having an aircraft connected.

![Screenshot_20191206-154728](https://user-images.githubusercontent.com/6790455/70364156-38509480-1840-11ea-8a1b-711ff0c47551.png)

**Comment by DonLakeFlyer** [comment]
Fixed now
