### ISSUE TITLE
latest daily: can't connect to autopilot over USB

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8129]
I can't connect to an autopilot over USB using the latest daily build on Window's.  Tried on multiple window's machines with multiple autopilots running multiple versions of PX4 firmware.  Everything works fine with an older daily build from 2 weeks ago.

I wonder if it's a USB-serial driver issue with the change to 64-bit?  https://github.com/mavlink/qgroundcontrol/pull/8128

**Comment by DonLakeFlyer** [comment]
Ah Windows, how you love to make me crazy!

**Comment by DonLakeFlyer** [comment]
Ah, f'ing Qt. It all works fine in 64 bit 5.11.3 but fails with 5.12.5. Good thing 5.12 is LTS, piece of crap!

**Comment by DonLakeFlyer** [comment]
https://bugreports.qt.io/browse/QTBUG-78891

**Comment by DonLakeFlyer** [comment]
Verified that it works in 5.12.6 which of course is not available in appveyor yet.

**Comment by DonLakeFlyer** [comment]
Will need to install 5.12.6 on appveyor manually.

**Comment by DonLakeFlyer** [comment]
Should finally be working

**Comment by Antiheavy** [comment]
> Should finally be working

yep working in today's daily.  thanks!
