### ISSUE TITLE
Ground Control 2 distance sensor

### ISSUE THREAD

**Issue by robomoticchile** [mavlink/qgroundcontrol#8163]
## Expected Behavior

I have on my drone a front and down distance sensor, but on the tablet I only can see one (the one on rngfnd1), no matter wich one I sellect.

As you can see in the MP, I can see the front and down sensor, but in the Qground control only shows the down sensor.

http://190.100.113.54:16211/archivos/pictures/QGC1.jpg
http://190.100.113.54:16211/archivos/pictures/QGC2.jpg

The same happends with GQC on windows

## Current Behavior
See as much as distance sensor we have

Here is the Log with the rngfnd 1 and 2 info.

http://190.100.113.54:16211/archivos/logs/rngfnd/

**Comment by DonLakeFlyer** [comment]
@robomoticchile I need a gcs telemetry log not a binary vehicle log.

**Comment by robomoticchile** [comment]
Im sorry...
Here is it!

[distanceSEnsorsLog.zip](https://github.com/mavlink/qgroundcontrol/files/3995903/distanceSEnsorsLog.zip)

**Comment by DonLakeFlyer** [comment]
Thanks for the bug report

**Comment by robomoticchile** [comment]
Thansk Don!

Im very sorry to bother you again, but how can aply the fix? I need it to aply to the HereLink QGC.

I appreciate your help, thanks!

**Comment by DonLakeFlyer** [comment]
Sorry I'm not involved in HereLink. You'll need to talk with them about that. Not sure where you do that

**Comment by robomoticchile** [comment]
thanks, i understand. And if I want to aply to my androdi tablet?

**Comment by DonLakeFlyer** [comment]
You can download APKs from here: https://docs.qgroundcontrol.com/en/releases/daily_builds.html
