### ISSUE TITLE
MAV_MISSION_INVALID_PARAM4

### ISSUE THREAD

**Issue by kristoferahlqvist** [mavlink/qgroundcontrol#8187]
## Expected Behavior
It should upload mission

## Current Behavior
When I use camera photo in a mission I get param4 has an invalid value (MAV_MISSION_INVALID_PARAM4). Param4: NaN

Even if I manually set param4 to 0 on all waypoints I get the same error.

## Steps to Reproduce:
1. Make a simple mission with camera photo
2. Try to upload
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: MiuI 11.05
- QGC Version: 3.5.4-1597
- QGC build: daily but I tried stable as well
- Flight Controller: Pixhawk I
- Autopilot (with version): Ardupilot Copter 3.6.8

## Detailed Description
I've built a drone to drop a cargo with a servo that is triggered by take photo

If I use take photo command in mission I get that param4 NaN error even if I manually set param4 to 0.0

## Log Files and Screenshots
![Screenshot_2019-12-27-10-43-26-737_org mavlink qgroundcontrolbeta](https://user-images.githubusercontent.com/5821521/71513892-96e7bc00-289c-11ea-9d1c-069b7c2f791c.jpg)

**Comment by DonLakeFlyer** [comment]
Should be fixed in daily builds

**Comment by kristoferahlqvist** [comment]
> Should be fixed in daily builds

Well it ain't ☹️

**Comment by DonLakeFlyer** [comment]
Sorry I missed you listed daily builds as well

**Comment by DonLakeFlyer** [comment]
Can you attach a plan file that files?

**Comment by kristoferahlqvist** [comment]
[test.plan](https://gofile.io/?c=MMyUxe)

**Comment by kristoferahlqvist** [comment]
Tried daily build 1622 but now I another fault.
![Screenshot_2019-12-29-11-01-02-709_org mavlink qgroundcontrolbeta](https://user-images.githubusercontent.com/5821521/71555310-10adb000-2a2b-11ea-949d-43a3fd101ad1.jpg)

**Comment by DonLakeFlyer** [comment]
Looks like ArduPilot still doesn't support those commands. The camera commands were added to/updated ages ago (over a year ago if I remember correctly). You should file a report against ArduPilot if you want support for this.

**Comment by kristoferahlqvist** [comment]
Ok, weird. Cause it works if I use the "Trigger Camera" button in gqc, but not if I plan it in a mission

**Comment by DonLakeFlyer** [comment]
Trigger camera button uses the old mavlink MAV_CMD_DO_DIGICAM_CONTROL camera which I believe ArduPilot does support. You can add these manually into your mission as individual commands. But you won't be able to use the stuff that is intergrated into the waypoint editor.

**Comment by DonLakeFlyer** [comment]
I do think the trigger distance item is supported by ArduPilot. Just not take photo, start/stop video and camera mode.

**Comment by DonLakeFlyer** [comment]
I had entered an issue on these commands against ArduPilot ages ago. Let me find it and ask them for support again.
