### ISSUE TITLE
"Bat2 Voltaje" it is not displayed in the QGC sofware

### ISSUE THREAD

**Issue by dronercheliservice** [mavlink/qgroundcontrol#8190]
Hi,
Battery_voltage_2 do not show on the QGC screen, only show "-1.00". 
The same happens if I use the HereLink Beta2 GCS.

If I use Mission Planner software, voltage 2 appears correctly "49.60v".

- Operating System: Windows 10 (and also HereLink)
- QGC Version: e.g. 3.5.6
- QGC build: daily (and also stable)
- MP version: 1.3.68
- Flight Controller: Pixhawk 2 CUBE black
- Autopilot software: Arduplane 4.0.1

![a](https://user-images.githubusercontent.com/59360769/71578666-605aad00-2af9-11ea-9573-b04861885875.png)

![b](https://user-images.githubusercontent.com/59360769/71578669-6486ca80-2af9-11ea-9bd0-187aad06a2ee.jpeg)

![c](https://user-images.githubusercontent.com/59360769/71578680-68b2e800-2af9-11ea-8811-aae39514ad74.jpeg)

![d](https://user-images.githubusercontent.com/59360769/71578683-6c466f00-2af9-11ea-90cd-803985f6f49c.png)

GITHUB does not allow me to upload the datalog files: ***.BIN  or ***.PX4LOG

**Comment by DonLakeFlyer** [comment]
@dronercheliservice How come you close this?

> GITHUB does not allow me to upload the datalog files: ***.BIN or ***.PX4LOG

Just pu the file on whatever file sharing service you want to use and link to it. Also I need a telemetry log from QGC not a binary vehicle log.

**Comment by dronercheliservice** [comment]
Please see this Logs:

https://drive.google.com/open?id=1BbzCF5od6MGAz7E3ue-g-iaiSCGntvH8

**Comment by DonLakeFlyer** [comment]
I need a telemetry log. They are files which QGC saves to the QGroundControl/Telemetry direcotry and ends with an extension of .tlog. Not quite sure what a .px4log file is or where it comes from?

**Comment by dronercheliservice** [comment]
Telemetry directory is empty. 
I don´t have any *.tlog file

**Comment by DonLakeFlyer** [comment]
Sorry, telemetry logs by default are only saved if the vehicle is armed. Either arm the vehicle, or you can turn that option of from General settings.

**Comment by dronercheliservice** [comment]
the vehicle is armed, but the logs does not appear, the directory is empty.
BTWthe directory "Telemetry" only exist at Herelink unit but if i use QGC on Windows the TELEMETRY directory does not exist.

**Comment by DonLakeFlyer** [comment]
Do you see any of the QGroundControl directories. They should be under "My Documents" in windows.

**Comment by hamishwillee** [comment]
@DonLakeFlyer FMI, when did dual battery support go in, and does it work for both PX4 and ArduPilot? I'm looking at https://docs.qgroundcontrol.com/en/SetupView/Power.html and it doesn't mention this. Does the status icon for battery also display multiple batteries. Is it only 2 batteries supported or does this handle more, if more exist?

**Comment by DonLakeFlyer** [comment]
This is just about battery values available to the instrument panel. I added two battery support to that ages ago based on BATTERY_STATUS.id which is likely incorrect. Although there is ArduPilot multi-battery Power setup. This does not exist for PX4. And also toolbar status is not multi-battery.

**Comment by dronercheliservice** [comment]
Hi DonLakeFlyer, see link attached with TLOG files:
https://drive.google.com/open?id=1D0en4DMjrz4UX-HEbMrNfZ7KCm5CX7ee

**Comment by DonLakeFlyer** [comment]
Perfect thanks. I see the problem. Now I need to figure out how to fix it.

**Comment by DonLakeFlyer** [comment]
@dronercheliservice This should be fixed in latest daily. Can you verify?

**Comment by dronercheliservice** [comment]
Hi DonLakeFlyer,
now the battery2 value is shown on QGC software using windows 10, many thanks ;)
How can I update my Herelink with this latest version?

**Comment by DonLakeFlyer** [comment]
> How can I update my Herelink with this latest version?

Sorry I don't know much of anything about HereLink development. You'll have to talk to them about that.

**Comment by dronercheliservice** [comment]
ok, thanks.
