### ISSUE TITLE
QGC can't view gazebo video

### ISSUE THREAD

**Issue by liangpu597** [mavlink/qgroundcontrol#8194]
I want to view gazebo video in qgc.
I follow the instance in: https://dev.px4.io/v1.9.0/en/simulation/gazebo.html
 My Step is :
1. Enable the GStreamer Plugin (if disabled) by changing the BUILD_GSTREAMER_PLUGIN option to "ON" in <Firmware>/Tools/sitl_gazebo/CMakeLists.txt (as shown below):

option(BUILD_GSTREAMER_PLUGIN "enable gstreamer plugin" "ON")

2. 
make clean
make px4_sitl gazebo_typhoon_h480

3. I open qgc and in settings-> general -> video source
and its no video available. I can't find other choice.

my gazebo version is : 9.10
QGC version is : v3.5.4

**Comment by DonLakeFlyer** [comment]
You should aks support questions for gazebo in the firmware slack or forums.
