### ISSUE TITLE
Strange altitude sent in follow mode

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#8208]
I switched to follow mode and walked along a flat area.
This is the altitude ArduCopter got:

![image](https://user-images.githubusercontent.com/562809/72014950-23ad5500-3261-11ea-8c43-d3956f2fff3d.png)

see also [https://discuss.ardupilot.org/t/strange-altitude-in-follow-mode/50781/4](url)

ArduCopter 4.0.0
QGC Android daily 2020-01-03

**Comment by DonLakeFlyer** [comment]
I'm going to need to add some additional logging to the builds to figure out what is going on here. Hope to get that some in a day or so.

Thanks for the bug reports.

**Comment by Antiheavy** [comment]
I assume QGC is using the location services from the device (some android device in this case)?  Depending on the quality of your device's GPS signal, it could be possible that your device's altitude estimate is really that terrible...  or maybe its a bug...

**Comment by DonLakeFlyer** [comment]
> I assume QGC is using the location services from the device (some android device in this case)? Depending on the quality of your device's GPS signal, it could be possible that your device's altitude estimate is really that terrible... or maybe its a bug...

That is correct as is the comment on crap GPS Alt. I hope to have time soon to add logging of location info in QGC so that it can be verified to be that or some other problem.

**Comment by DonLakeFlyer** [comment]
@twistedwings New daily builds should be available in an hour. Can you use the new version. Turn on FollowMeLog console logging. Capture the output while moving around and attach here? This should tell me what is really being reported as altitude from the device.

**Comment by twistedwings** [comment]
may take a while as it's raining all day long.

**Comment by twistedwings** [comment]
Where do I enable FollowMeLog? I cannot find that option.

![image](https://user-images.githubusercontent.com/562809/72628506-bed3b800-394e-11ea-9520-d77706c70b61.png)

**Comment by dogmaphobic** [comment]
Under "Console" in _General Settings_:

<img width="1026" alt="Screen Shot 2020-01-17 at 1 24 22 PM" src="https://user-images.githubusercontent.com/749243/72632555-e580f700-392c-11ea-9d3b-49486360eb11.png">

**Comment by twistedwings** [comment]
I don't have that, do I need a newer version?

![image](https://user-images.githubusercontent.com/562809/72634500-ff393300-395a-11ea-9f6f-db6fcb8bb830.png)

**Comment by dogmaphobic** [comment]
It's in the current master (daily) build.

**Comment by twistedwings** [comment]
I've got the 64 bit APK from hier: [https://docs.qgroundcontrol.com/en/releases/daily_builds.html(url)
Option is not there.
Which version do you have?

**Comment by dogmaphobic** [comment]
I just built it myself. I'm not sure how frequently daily Android builds are run.

**Comment by twistedwings** [comment]
It's in the windows version but not in the android version.

**Comment by dogmaphobic** [comment]
You said "APK", which implies Android. That's what got me confused. Either way, the change went in two days ago. It should be in the current daily. If it isn't, we have to wait for @DonLakeFlyer.

**Comment by DonLakeFlyer** [comment]
Android daily builds should post with ever pull merged. Looks like something broke with Android on the 15th. Nothing has been posted since then.

**Comment by DonLakeFlyer** [comment]
As far as I can tell android builds just spontaneously combusted as opposed to some specified pull screwing them up. Will likely have to wait until I get back for me to figure out why.

**Comment by dogmaphobic** [comment]
He's using Windows. I only got confused by this:
>I've got the 64 bit APK from hier: 

As to the Android build, it looks like something changed with gradle. If you don't already have it, the build downloads it for you. We all have it so we are probably running an earlier version. As the CI build is always from scratch, it is downloading something new and that gradle seems to be messed up.

**Comment by twistedwings** [comment]
No, I am using Android. The whole issue is about Android.

**Comment by dogmaphobic** [comment]
>No, I am using Android. The whole issue is about Android.

>It's in the windows version but not in the android version.

That can be confusing :P

Yes, the daily Android build hasn't run in some time. We need to wait for @DonLakeFlyer.

**Comment by twistedwings** [comment]
Now the option appears in the daily.
I made a test with version 2020-01-24.
I don't see any FOLLOW logging in the telemetry log.

[2020-01-25 10-41-59.tlog.txt](https://github.com/mavlink/qgroundcontrol/files/4111941/2020-01-25.10-41-59.tlog.txt)

**Comment by DonLakeFlyer** [comment]
It's not a telemetry log, it's a console log which you can save from Settings/Console

**Comment by DonLakeFlyer** [comment]
@twistedwings Possible to get a console log for this? I'm trying to wrap up all the problems for a Stable release.

**Comment by twistedwings** [comment]
It may take a while until the rain and storm stops.

**Comment by twistedwings** [comment]
here it is, sorry for the delay.

[Follow2.txt](https://github.com/mavlink/qgroundcontrol/files/4208659/Follow2.txt)

**Comment by DonLakeFlyer** [comment]
So what I think this is showing is that the altitude value from a tablet gps can be total crap. Which in turn means using relateive mode heights will pretty much never work. Where as absolute should work fine. I"m going to change QGC to only support Absolute height.

**Comment by DonLakeFlyer** [comment]
FYI: I've tried the same thing with multiple devices and the altitudes are all over the map. With an iPhone being the closest. And for me most Android tablets showing negative altitudes for my test area which is way your tablet is doing as well.

**Comment by twistedwings** [comment]
Yes, I totally agree with that. Although I think disabling relative mode is not good as some users may want that. Is it possible to support baro if installed?

**Comment by DonLakeFlyer** [comment]
Working correctly now based on new home altitude only support
