### ISSUE TITLE
CameraTriggerIndicator not working for px4

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#8216]
Hi 

I work with px4 code for survey application. i can not see camera trigger indicator in qgc flight display menu but before when i was tested with ardupilot code it was working.
i checked tlog file of px4 code , The location of the camera triggers was saved , so there is a problem .

**Comment by Antiheavy** [comment]
I think mavlink 2 is required for PX4. Are you enabling mavlink 2 on your system?

**Comment by DonLakeFlyer** [comment]
> i checked tlog file of px4 code

@moreba1 So in your telemetry log file (not a vehicle binary log) you played it back in QGC and you can see the MAVLINK_MSG_ID_CAMERA_IMAGE_CAPTURED messages in the mavlink inspector sent from the vehicle to QGC? But the indicators still don't show up in the Fly View?

**Comment by moreba1** [comment]
i checked ma

**Comment by moreba1** [comment]
@DonLakeFlyer 
i checked mavlink inspector .

![ssss](https://user-images.githubusercontent.com/14200369/72500185-2dc6e900-3849-11ea-8e80-680e42b69c39.JPG)

**Comment by DonLakeFlyer** [comment]
QGC will only show image capture points if CAMERA_IMAGE_CAPTURED.capture_result == 1 which indicates a successful capture according to mavlink spec. In the screen shown above you can see that CAMERA_IMAGE_CAPTURED.capture_result equals -1 which isn't even a valid value for that field. So as far as I can tell QGC is working correctly.

https://mavlink.io/en/messages/common.html#CAMERA_IMAGE_CAPTURED

**Comment by moreba1** [comment]
Does it possible to display camera indicator with different color when result is 0?
