### ISSUE TITLE
Survey item terrain following: Max climb/descent rate not applied to turnaround waypoints

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#8220]
See https://validator.deltaquad.com/validator/3d.php?uid=5e1ecbf7bbfdb5e1ecbf7bc01d&flightdate=1579071600&localFlightdate=1579075200

When planning a survey on a hill with terrain following you can set a max climb/descent rate. This is only applied to the transects within the mapping mission. The turn-around waypoints do not consider this limitation as shown below:

![image](https://user-images.githubusercontent.com/14801663/72417823-f5a4a500-3779-11ea-9aff-6df633a8b0d9.png)

**Comment by moreba1** [comment]
fixedwings in turnaround must do a loiter to alt (next line alt) if needed .

**Comment by sanderux** [comment]
> fixedwings in turnaround must do a loiter to alt (next line alt) if needed .

That would completely screw up a clean entry into the next transect. Also, it defies the purpose of setting a max climb/descent rate as you might hit a mountain while circling up.

**Comment by sanderux** [comment]
@DonLakeFlyer actually setting a max/min gradient would be more use friendly

**Comment by DonLakeFlyer** [comment]
Ok, so this is a pretty hairy problem to solve. It won't make it into stable which is being rolled out now. But I'll pick it up right after that.

**Comment by moreba1** [comment]
@sanderux 
this type of mission can solve the issue and it is better for photogrammetry.


![image](https://user-images.githubusercontent.com/14200369/83148430-3213e480-a10e-11ea-9eee-cad74f88738f.png)

**Comment by DonLakeFlyer** [comment]
@sanderux I'm working on this new. Do you happen you have a good Plan file which I could use for testing which shows the usefulness of this?

**Comment by sanderux** [comment]
In the validator link on top there is a menu with an option to download the plan file.
does that help?

**Comment by sanderux** [comment]
You could even use the DQ validator to check if your modifications solve it

**Comment by sanderux** [comment]
@moreba1 we do not allow such behavior as the path is unvalidated and unpredictable

**Comment by moreba1** [comment]
> unpredictable

the plane can change more altitude during turning between lines, we can define max altitude change in turn.
when the distance between lines is low, setting Max climb/descent for turning is not appropriate because the turning trajectory for the plane is longer than waypoint lines and the plane can change more altitude.

**Comment by sanderux** [comment]
that all works nice if you are above flat land, but when given a max climb/descent it should be honored imo, you could crash into a mountain when loitering up/

**Comment by DonLakeFlyer** [comment]
> In the validator link on top there is a menu with an option to download the plan file.
> does that help?

@sanderux I was wondering if you already had some problematic plans for which this change would now make them work.

**Comment by sanderux** [comment]
@DonLakeFlyer yes, the plan in de main issue description is problematic. Thats why i refered to it. I'm traveling now so a little hard to upload it here but it is in the link on top

**Comment by DonLakeFlyer** [comment]
@sanderux The validator link for that is no longer valid. So I can't figure out where that is so I can replicate it.

**Comment by sanderux** [comment]
Ah, i see now, let me try and make you one in a few hours
