### ISSUE TITLE
CMake transition requirements

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#8240]
Let's collect all the requirements for a full transition to cmake. Starting with @DonLakeFlyer's points from https://github.com/mavlink/qgroundcontrol/pull/8218#issuecomment-574910104.

 - [ ] Build all OS versions in CI, travis and appveyor
   - [ ] Linux
      - [x] building
      - [ ] packaging (AppImage, Snap, deb)
      - [x] video
   - [ ] Mac
     - [x] building
     - [ ] packaging
     - [x] video
   - [ ] Windows
     - [x] building
     - [ ] packaging
     - [ ] video
   - [ ] Android
      - [ ] building
      - [ ] packaging
      - [ ] video
   - [ ] iOS
      - [ ] building
      - [ ] packaging
      - [ ] video
 - [ ] Can build both Auterion and Sentera custom build as test cases for custom support
 - [ ] Can build iOS and android builds which can be pushed to store
 - [ ] Android build should be push to store from CI
 - [ ] iOS build would still be some manual magic that Gus does. If cmake could automate that as well well even better. But were aren't there yet so that isn't a requirement.
 - [ ] Xcode build (Spit out by qmake) plus run QGC in the simulator all the time. So that support can't disappear either.
 - [ ] android debug/deploy cycle

**Comment by dagar** [comment]
@patrickelectric @tcanabrava

**Comment by patrickelectric** [comment]
I can confirm that video is working for both linux and mac

**Comment by alexeylysenko** [comment]
Take a look at #8472 it fixes cmake build issue

**Comment by DonLakeFlyer** [comment]
Just seeing this now. Good list.
