### ISSUE TITLE
Repeated popups from OS X firewall

### ISSUE THREAD

**Issue by blackbox-zz** [mavlink/qgroundcontrol#825]
Whenever UDP link is activated, OS X firewall pops up, asking the user to allow or deny the connection. Normally the popup should appear only once, but each time QGC is restarted the popup appears again. Manually adding qgroundcontrol.app to the list of firewall exceptions in system preferences doesn't help.

The root of the issue is that in order to avoid repeated prompts for the same application over and over, OS X uses code signing. If the app is unsigned (as QGC is), it signs it with an ad-hoc signature that is stored in /var/db/DetachedSignatures. However, signing fails:

```
$ codesign -s - /Applications/qgroundcontrol.app
/Applications/qgroundcontrol.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Applications/qgroundcontrol.app/Contents/Frameworks/QtConcurrent.framework
```

Search for that error message reveals that this is caused by macdeployqt not copying the framework's Info.plist into the bundle.
See [1] for more detailed explanation and a workaround. It should be noted that this is also a blocking issue for #664.

[1] http://stackoverflow.com/questions/19637131/sign-a-framework-for-osx-10-9

**Comment by LorenzMeier** [comment]
Closing as stale.
