### ISSUE TITLE
Why is libQt5X11Extras a new requirement for Linux?

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8279]
./QGroundControl.AppImage 
/tmp/.mount_t1h12I/QGroundControl: error while loading shared libraries: libQt5X11Extras.so.5: cannot open shared object file: No such file or directory

**Comment by DonLakeFlyer** [comment]
The travis CI build should use AppImage for debug testing that way it will verify AppImage is working as well.

**Comment by DonLakeFlyer** [comment]
I added the missing install lib. But I'd still like the video folks to comment/verify as to why this is a new things which is needed.

**Comment by DonLakeFlyer** [comment]
I've verified that AppImage builds are working now.

**Comment by andrewvoznytsa** [comment]
libQt5X11Extras is a qmlglsink dependence.
