### ISSUE TITLE
Follow Me settings garbled after setting FOLL_ALT_TYPE to absolute 

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#8291]
![image](https://user-images.githubusercontent.com/562809/74087092-845ec600-4a89-11ea-8466-dcdb00d07370.png)

![image](https://user-images.githubusercontent.com/562809/74087126-b96b1880-4a89-11ea-9ec0-8992dd72bdd2.png)

![image](https://user-images.githubusercontent.com/562809/74087137-d0116f80-4a89-11ea-8ce4-65bdec866568.png)

ArduCopter 4.0.1
![image](https://user-images.githubusercontent.com/562809/74087154-f46d4c00-4a89-11ea-9590-10aa236d4ad4.png)

**Comment by DonLakeFlyer** [comment]
@twistedwings This is because QGC currently only supports relative. Can you explain what the difference is with the two FOLL_ALT_TYPE modes? I don't see how they change anything with respect to the offsets. If you set to absolute which works differently?

**Comment by twistedwings** [comment]
In absolute mode the uav follows at fixed height.
In relative mode it follows relative to the leaders height.
If the leader climbs a mountain the uav will also ascend in relative mode,
in absolute mode it will crash against the mountain.

**Comment by DonLakeFlyer** [comment]
Duh, Why couldn't I understand that! That mean the fix I made should work fine.

**Comment by DonLakeFlyer** [comment]
Daily builds which spit out in an hour or so should have the fix. Can you verify?

**Comment by twistedwings** [comment]
verified in both windows and android version.
Thank you for the fix.

**Comment by DonLakeFlyer** [comment]
@twistedwings Thanks for beating on this new feature to wring it out
