### ISSUE TITLE
Charting is missing

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8308]
The charting button is no longer under analyze. I tried a download OSX daily and also my hand built linux doesn't show it either.

Related https://github.com/mavlink/qgc-user-guide/pull/237

**Comment by dogmaphobic** [comment]
There is no charting button. Charting is part of the MAVLink Inspector:

<img width="1159" alt="Screen Shot 2020-02-11 at 12 48 29 PM" src="https://user-images.githubusercontent.com/749243/74263555-11459180-4ccd-11ea-82ae-49191d48029b.png">
