### ISSUE TITLE
Cannot connect to flight controller

### ISSUE THREAD

**Issue by dakejahl** [mavlink/qgroundcontrol#8316]
I am using Qt 5.12.5 on Windows 10 compiling with MSVC 2017 64bit

**Issue**
Using a local build, the vehicle never "connects", instead I get the message "Your vehicle is not responding. If this continues...etc". Daily builds downloaded from the server do work however.

I added some `qDebug()` statements and discovered that QSerialPort **readyRead** signal is never emitted, and thus the **bytesReceived** signal is never emitted and thus the logic in LinkManager.cc fails. A quick google search reveals a known bug.
https://bugreports.qt.io/browse/QTBUG-78086

Is anyone else able to reproduce this on Windows? Are there any other developers actively developing on Windows?

**edit:** I am going to test a newer version of Qt and see if it helps

**Comment by dakejahl** [comment]
The problem is fixed by updating to Qt 5.12.7

**Comment by dakejahl** [comment]
FYI The docs still need to be updated to reflect this issue. I've been using 5.12.7 for Windows/Linux/Android, so it might be OK to just bump the version by 1 for all platforms. Someone on Mac would need to verify this is fine.

**Comment by DonLakeFlyer** [comment]
This was in 5.12.5 but I thought it was fixed in 5.12.6 which is the current spec'ed version to use.

**Comment by dakejahl** [comment]
Ahh okay, I misremembered the version number, I thought it was an issue with 6... it was still in the back of my mind as being "unresolved". Thanks!

**Comment by Duaa0901** [comment]
Hello, i have the same issue as yours, have the issue resolved when you have upgrade the QT?
