### ISSUE TITLE
Missing FRAME_CLASS parameter with ArduSub in frame setup page

### ISSUE THREAD

**Issue by Williangalvani** [mavlink/qgroundcontrol#8319]
Using QGC master and ArduSub 4.0.

![Screenshot from 2020-02-12 16-02-30](https://user-images.githubusercontent.com/4013804/74367724-1aa82a00-4db1-11ea-8f03-deeb7b5e0a23.png)

**Comment by DonLakeFlyer** [comment]
This says your code is referencing the FRAME_CLASS parameter but the vehicle didn't send FRAME_CLASS to QGC. Either your code is wrong or the vehicle side is screwing up somehow.
