### ISSUE TITLE
Problem "inserting" Takeoff pattern, puts it at the end of the mission

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8346]
In Plan View, the Takeoff mission item is grayed out (not available) unless "Mission Start" is selected on the right-hand list.  Presumably this is because Takeoff should be okay to "insert" after Mission Start, but not after any other mission items.  However, when you "insert" the Takeoff, it puts it at the end of the mission.  I think the correct behavior should be to insert the Takeoff right after Mission Start.  Tested on Recent Daily.

![image](https://user-images.githubusercontent.com/12117027/74611315-3452b580-50c0-11ea-9f96-764ca5f06614.png)

**Comment by DonLakeFlyer** [comment]
> Presumably this is because Takeoff should be okay to "insert" after Mission Start, but not after any other mission items.

Yup

> However, when you "insert" the Takeoff, it puts it at the end of the mission. I thin the correct behavior should be to insert the Takeoff right after Mission Start.

Whoopsy. Correct.
