### ISSUE TITLE
UI scaling on macOS

### ISSUE THREAD

**Issue by andrewvoznytsa** [mavlink/qgroundcontrol#8372]
If I switch macOS display settings like on attached screenshot 
![macOS-2020-02-20-19-04-13](https://user-images.githubusercontent.com/13932805/74960200-925f0000-5414-11ea-8ef1-1aa52283afc3.png)
 then QGC does not render its UI properly - see this attachment 
![macOS-2020-02-20-19-04-51](https://user-images.githubusercontent.com/13932805/74960267-b1f62880-5414-11ea-8f64-b4883e7748f9.png)
. Playing with variables described here https://doc.qt.io/qt-5/highdpi.html did not help.

macOS - Catalina
QGC - master

**Comment by DonLakeFlyer** [comment]
Is this scaling a new Catalina thing? I'm guessing it's a Qt problem which is dealt with in newer version.

**Comment by andrewvoznytsa** [comment]
No, scaling is old feature.

**Comment by dogmaphobic** [comment]
Something is peculiar about your setup. The (System Settings) UI looks different. It appears it is not able to collect all the information about the monitor. Is that running on a VM? I tested changing to all possible scaling options and it all works (Qt does get notified and repaints itself).

<img width="1794" alt="Screen Shot 2020-02-21 at 5 47 03 AM" src="https://user-images.githubusercontent.com/749243/75028320-0da0d000-546e-11ea-8b5e-9d5a8e49f650.png">
<img width="1241" alt="Screen Shot 2020-02-21 at 5 47 25 AM" src="https://user-images.githubusercontent.com/749243/75028324-0e396680-546e-11ea-8076-f3427fe81373.png">
<img width="1757" alt="Screen Shot 2020-02-21 at 5 47 38 AM" src="https://user-images.githubusercontent.com/749243/75028326-0e396680-546e-11ea-8a60-d80ddc06e63a.png">

**Comment by andrewvoznytsa** [comment]
Yes, it was VM. I'll try on real HW in a few days.

**Comment by DonLakeFlyer** [comment]
Reopen if happens in non-VM
