### ISSUE TITLE
Draft: QGroundControl Stable 4.0 available

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8374]
These are draft release notes for the upcoming stable. If you find anything major missing, please comment.

Here is a very high level and non-exhaustive list of new features added to QGroundControl in version 4.0. Not to mention the large number of bug fixes in this release and I'm sure we lost track on listing some new features which were added along the way!

**Note** The format for Settings in QGC had to change in this release. Which means all QGC settings will be reset to defaults.

* Settings
  * Language: Allow selection of language
  * ArduPilot
    * Mavlink: Configurable stream rate settings
* Setup
  * Joystick
    * New joystick setup ui
    * Ability to configure held button to single or repeated action
  * ArduPilot
    * Motor Test
* Plan
  * Create Plan from template with wizard like progression for completing full Plan.
  * Survey: Save commonly used settings as a Preset
  * Polygon editing
    * New editing tools ui
    * Support for tracing a polygon from map locations
  * ArduPilot
    * Support for GeoFence and Rally Points using latest firmwares and mavlink v2
* Fly
  * Click to ROI support
  * Added support for connecting to ADSB SBS server. Adds support for ADSB data from USB SDR Dongle running 'dump1090 --net' for example.
  * Ability to turn on Heading to home, COG and Next Waypoint heading indicators in Compass.
  * Video
    * Add support for h.265 video streams
  * Vehicle type specific pre-flight checklists. Turn on from Settings.
* Analyze
  * New Mavlink Inspector which includes charting support. Supported on all builds including Android and iOS.
* General
  * Released Windows build are now 64 bit only
  * Log Replay: Ability to specify replay speed
  * ArduPilot
    * Improved support for chibios firmwares and ArduPilot bootloader with respect to flashing and auto-connect.

Docs and Downloads here: http://qgroundcontrol.com

Important Note for OSX Catalina users: In order to run QGC you will need to right click and select Open. Then cancel. And then right click again and you will be presented with the option to run QGC even though it is not signed.

**Comment by qter188** [comment]
Wow, amazing!

**Comment by jsharpe** [comment]
The macOS build needs to be notarized as per instructions here: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution as it doesn't work on Catalina even with the instructions given.

**Comment by qter188** [comment]
Is it released? Why the the file is v3.5.6 still.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Any ideas on Catalina then? I can't test on my system since I've already turned it all off.

**Comment by dogmaphobic** [comment]
Just this morning I downloaded something (unsigned). It is as I described. You just need to insist. From Finder, right click on the .app bundle and select open. It will chastise you about it and the only option is _Cancel_. Do it again, this time you have an _Open_ button available. You only need to do this once.

**Comment by jsharpe** [comment]
Unfortunately this only works if your gatekeeper settings are configured to allow this.
We have our devices configured according to NCSC guidelines: https://www.ncsc.gov.uk/collection/mobile-device-guidance/platform-guides/macos which adds a policy to turn off the ability to run untrusted apps.

Is the issue that you don't have access to an apple developer certificate to do the signing?

**Comment by jsharpe** [comment]
> Just this morning I downloaded something (unsigned). It is as I described. You just need to insist. From Finder, right click on the .app bundle and select open. It will chastise you about it and the only option is _Cancel_. Do it again, this time you have an _Open_ button available. You only need to do this once.

Following this process with the MDM policy set to turn off the ability to run untrusted apps results in the following dialog instead of one that gives you an open button:
https://slack-files.com/T0V5F863B-FU3J63WDN-f98202bcca

**Comment by dogmaphobic** [comment]
> Is the issue that you don't have access to an apple developer certificate to do the signing?

It's more than just that. The only way right now to produce a signed binary is if I manually build it using my personal developer's account. The existing (automated) build system is not setup to do that. This is all volunteer work. We will gladly accept help in setting up a build system that produces signed binaries.

**Comment by DonLakeFlyer** [comment]
> Is it released?

Not yet

**Comment by DonLakeFlyer** [comment]
Note: I pulled ArduPilot follow me support from stable. It just wasn't ready.
