### ISSUE TITLE
Follow mode: absolute height does not work anymore

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#8392]
Setting FOLL_ALT_TYPE to 0 (absolute) leads to "not supported" message.
Most likely related to #8208.

**Comment by DonLakeFlyer** [comment]
This is correct behavior. Only relative is supported by the ui. With the altitude the follow is based on coming from the home position there is no need to have multiple altitude types. They all lead to the same thing. So it's simpler to force a specific known setup.
