### ISSUE TITLE
Corridor Wizard: [Trace] continues to trace in Corridor Scan too

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8395]
Similar to what was happening in Survey (https://github.com/mavlink/qgroundcontrol/issues/8344), Trace in Corridor Scan keeps active even when you are "Done" with the Corridor Scan and move on to Landing Pattern or other items.

The fix for Trace in Survey is effective https://github.com/mavlink/qgroundcontrol/pull/8373 as it grays out the [Done With Polygon] until you click [Done Tracing].  However,  it would be less annoying and easier to use if [Done With Polygon] and [Done With Polyline] also performed the [Done Tracing] function as well.  This way the user has the option to click either [Done Tracing] or [Done With Polygon]/[Done With Polyline] and the effect is the same, it stops the tracing and they move on to whichever their next thing is.

**Comment by DonLakeFlyer** [comment]
> Trace in Corridor Scan keeps active even when you are "Done" with the Corridor Scan

Ah, crap I should have none that!

**Comment by DonLakeFlyer** [comment]
> However, it would be less annoying and easier to use if [Done With Polygon] and [Done With Polyline] also performed the [Done Tracing] function as well.

Can you enter a separate feature request for that. I'm only fixing bug now. Don't want to break as much as I fix. I'll change that after stable goes out.
