### ISSUE TITLE
Were the "Fly" and "Plan" labels removed intentionally?

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8407]
I've noticed in recent Daily Builds (maybe going back a while) the "Fly" and "Plan" labels at the top of the left-hand toolbars are no longer there.  Where these removed intentionally?
![image](https://user-images.githubusercontent.com/12117027/75258054-888a2380-57ab-11ea-8e5b-3a2fe24154b3.png)

The documentation still talks about Fly and Plan views, which if there are no longer any labels in the software could be confusing:
https://docs.qgroundcontrol.com/en/FlyView/FlyView.html
https://docs.qgroundcontrol.com/en/PlanView/PlanView.html
FYI @hamishwillee

**Comment by hamishwillee** [comment]
Probably an improvement. Either way we should do a full scan through the docs and update quite a lot of the images. I'm hoping other people step up for some of that.

**Comment by DonLakeFlyer** [comment]
Hmm, let me look at when those got pulled out

**Comment by DonLakeFlyer** [comment]
No, these should not have been pulled out

**Comment by Antiheavy** [comment]
Looks like "Fly" and "Plan" are back in the latest Daily.  I agree, it is better to have the words there. Closing this issue.
![image](https://user-images.githubusercontent.com/12117027/75305537-0b42cb00-580c-11ea-86e2-95bdabafdd40.png)
