### ISSUE TITLE
Only mapbox's Hybrid "Failed to fetch tile error"

### ISSUE THREAD

**Issue by zk317** [mavlink/qgroundcontrol#8422]
Hey, I'm back

This time is new troble for mapbox api.

I compile last version fo V4.0.0

and then I tryed Hybrid of Mapbox.

but Hybird not open.

Map window is all White.

![스크린샷, 2020-02-26 20-22-02](https://user-images.githubusercontent.com/60177240/75340378-b9ff0e00-58d5-11ea-9375-e7c1e0cfb7ca.png)

however I tryed open qgroundcontrol-start.sh
so, cmd window  printed  error messege

That error is....

QGeoTileRequestManager: Failed to fetch tile (437,201,9) 5 times, giving up. Last error message was: 'Error transferring https://api.mapbox.com/v4/mapbox.hybrid/9/437/201.jpg80?access_token=pk.eyJ1IoimsTciLhIjoiYs1Z0dWMdgrhWWhejetjyHWBDyGZkZnnd9.pGcTOreRTftSmb_uKoM - server replied: Not Found'

Another Mapbox map style is woking good.

1. How can I fix this bug?

2. Why map is blurred little bit? (my map not sharpness, especily text) How can I perpect sharp (some zoom stage is look sharpness good)

(pls click Picture look detail)

![스크린샷, 2020-02-26 20-28-57](https://user-images.githubusercontent.com/60177240/75340963-cdf73f80-58d6-11ea-91d3-00bac7f21164.png)
![스크린샷, 2020-02-26 20-29-22](https://user-images.githubusercontent.com/60177240/75340970-cf286c80-58d6-11ea-8af0-d06601e9b3ec.png)

**Comment by dogmaphobic** [comment]
> Error transferring https://api.mapbox.com/v4/mapbox.hybrid/9/437/201.jpg80?access_token=pk.eyJ1IoimsTciLhIjoiYs1Z0dWMdgrhWWhejetjyHWBDyGZkZnnd9.pGcTOreRTftSmb_uKoM - server replied: Not Found'

That URL gives me an "invalid token" error. Is that token real or you just made something up to paste it here? If it is real, the issue seems to be with how you have your account setup.

**Comment by zk317** [comment]
I put random values in the token.
For security reasons

Also, the problem was solved by adding a personal editable api in Mapbox Studio.

Thanks for the reply
