### ISSUE TITLE
File menu no longer popping up when switching to a blank Plan view

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8429]
Starting with today's daily build (Master?) (edit: and Stable 4.0) the File menu isn't popping open automatically if switching to the Plan View with no mission yet created.  This was just working 2 days ago on Master.  This was a helpful feature, I hope it was an oversight and can come back.
![image](https://user-images.githubusercontent.com/12117027/75403805-5b826180-58ce-11ea-8f40-1e8da9af0354.png)

**Comment by DonLakeFlyer** [comment]
Same thing with Stable. Sigh!

**Comment by DonLakeFlyer** [comment]
I managed to break it when I put the Fly/Plan labels back.
