### ISSUE TITLE
Center on "Mission" and Center on "All items" zooms to world

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8462]
Testing a "Stable" build from appyveyor (Stable_V4.0-11852) I noticed that Plan view "Center map on:" "Mission" and "All items" cause the map to zoom out to the world centered on somewhere in Europe.  edit: ~~that looks suspiciously like Switzerland ;-)~~ it's somewhere else, more like the 'O' in EUROPE here.

![image](https://user-images.githubusercontent.com/12117027/75733877-12f6e980-5cbc-11ea-97d0-6a5a7c2780bd.png)

**Comment by dogmaphobic** [comment]
LOL

**Comment by DonLakeFlyer** [comment]
I found another bug in the mapFitFunctions today. Which I fixed this morning. My guess is this is good now. I'll take another look tomorrow to see if it works now.

**Comment by dogmaphobic** [comment]
As far as I know, only Mocklink has Zürich hardcoded. If this is indeed the case.

**Comment by DonLakeFlyer** [comment]
> Mocklink has Zürich hardcoded

yup. But you can make it be my house too if you change the ifdef :)

**Comment by kosakwayne** [comment]
This also happens when loading a KML/SHP for a survey

**Comment by DonLakeFlyer** [comment]
Can you test with latest stable: https://qgroundcontrol.s3-us-west-2.amazonaws.com/builds/Stable_V4.0/QGroundControl-installer.exe?

**Comment by DonLakeFlyer** [comment]
Daily builds aren't always fully up to date with the in progress stable point release.

**Comment by kosakwayne** [comment]
@DonLakeFlyer I'm seeing the same behavior when loading KML/SHP for survey in the latest stable you just linked.

**Comment by Antiheavy** [comment]
> I'm seeing the same behavior when loading KML/SHP for survey in the latest stable you just linked.

yep!  I'm seeing this too on Stable from 21 hours ago:
![image](https://user-images.githubusercontent.com/12117027/75809949-3b7bf380-5d4f-11ea-85f6-6bcca424a9e5.png)

I'll try the one @DonLakeFlyer linked above next.

**Comment by Antiheavy** [comment]
> Can you test with latest stable: https://qgroundcontrol.s3-us-west-2.amazonaws.com/builds/Stable_V4.0/QGroundControl-installer.exe?

still happening with this stable release too.

**Comment by DonLakeFlyer** [comment]
Can you try again. New build is there.

**Comment by Antiheavy** [comment]
> Can you try again. New build is there.

Fixed in the newest Appveyor build:  Stable_V4.0-11859

Thanks!
