### ISSUE TITLE
QGC v4.0.0 on Windows 10 - Downloads and installs but fails to execute

### ISSUE THREAD

**Issue by mcsauder** [mavlink/qgroundcontrol#8466]
Hi @DonLakeFlyer,

I am able to download and install the latest QGC v4.0.0 but the executable fails to run properly once installation is complete.  Below is a series of screenshots demonstrating the steps to reproduce and the result.  I have observed this same behavior on 2 Dell latitude ATG laptops with new windows 10 installations and all OS updates applied.  I have also observed this behavior on an Asus ZenBook pro with similar results.

I am able to install and run QGC v3.5.6 on each of the machines that v4.0.0 fails with.

Thanks for any advice you have!

![image](https://user-images.githubusercontent.com/2497951/75811339-7a0eaf80-5d49-11ea-957c-2951ec709c43.png)
![image](https://user-images.githubusercontent.com/2497951/75811371-86930800-5d49-11ea-9ab4-8d779b7a78f8.png)
![image](https://user-images.githubusercontent.com/2497951/75811397-927eca00-5d49-11ea-9876-44895d14239e.png)
![image](https://user-images.githubusercontent.com/2497951/75811435-a9252100-5d49-11ea-8881-850995ac5b25.png)
![image](https://user-images.githubusercontent.com/2497951/75811457-b215f280-5d49-11ea-8c94-03ad2df54339.png)
![image](https://user-images.githubusercontent.com/2497951/75811475-bb9f5a80-5d49-11ea-87a9-d10ddecdc3d0.png)
![image](https://user-images.githubusercontent.com/2497951/75811519-ce199400-5d49-11ea-9e61-1e2d6a7346fd.png)

(From the same machine as the screenshots above after uninstalling and reinstalling v3.5.6)
![image](https://user-images.githubusercontent.com/2497951/75812836-281b5900-5d4c-11ea-913d-760e1309df3c.png)

**Comment by DonLakeFlyer** [comment]
Follow the instructions here: https://docs.qgroundcontrol.com/en/Support/Support.html for finding the crash dump file. Zip that up, put it somewhere and link to it here.

**Comment by DonLakeFlyer** [comment]
Hmm, that might now be a crash. So you may not have any dumps generated.

**Comment by DonLakeFlyer** [comment]
It doesn't look like it but are you running 32 bit version of WIndows?

**Comment by DonLakeFlyer** [comment]
Don't worry about the crash dump. I figured out what is going wrong from the error code.

**Comment by DonLakeFlyer** [comment]
@mcsauder Can you install a new build from here: https://qgroundcontrol.s3-us-west-2.amazonaws.com/builds/Stable_V4.0/QGroundControl-installer.exe and let me know the results.

**Comment by mcsauder** [comment]
Hi @DonLakeFlyer, That one works!  It makes sense that the issue was hitting new computers that were missing parts of the .NET framework that other program installations could previously have installed on some machines.

Thanks so much for your help!

**Comment by DonLakeFlyer** [comment]
@mcsauder Thanks for reporting and testing
