### ISSUE TITLE
4.0 android/mobile qml issues

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#8484]
In each of these screenshots, some item or text is too wide and is being cropped

![image](https://user-images.githubusercontent.com/8315108/75944215-f7224d80-5e4b-11ea-80ac-3022a5f156d2.png)

![image](https://user-images.githubusercontent.com/8315108/75944230-ff7a8880-5e4b-11ea-9b00-1551d1488812.png)

![image](https://user-images.githubusercontent.com/8315108/75944239-030e0f80-5e4c-11ea-87c9-20001c2a3036.png)

![image](https://user-images.githubusercontent.com/8315108/75944252-073a2d00-5e4c-11ea-9091-08a3c2177441.png)

**Comment by tcanabrava** [comment]
some of those are also happening on desktop since 3.x

**Comment by DonLakeFlyer** [comment]
What size device. Target mobile is 10" tablet. Although things will sort of work below that we generally don't try to fix layout issues on smaller devices.

**Comment by jaxxzer** [comment]
> What size device. Target mobile is 10" tablet. Although things will sort of work below that we generally don't try to fix layout issues on smaller devices.

Oh, it's an 8" device. I did not know about the 10" thing.

**Comment by DonLakeFlyer** [comment]
There is some small amount of write up on it here: https://dev.qgroundcontrol.com/en/ui_design/multi_device_pattern.html

**Comment by jaxxzer** [comment]
noting here for @tcanabrava to check the font size options in the general settings menu, that can throw some of the layouts off too.

**Comment by jaxxzer** [comment]
@Williangalvani merged pull request has fixed the problem on linux. The problem persists on windows.
