### ISSUE TITLE
Improved Geo-Tagging

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#8488]
Current Geo Tagging does not process misfires.
Geotagging should be timestamp based (deltas, not straight)

This implementation would work much better: https://github.com/PX4/Firmware/blob/master/Tools/geotag_images_ulog.py

**Comment by Antiheavy** [comment]
we've used @sanderux 's python script linked above and it works much better than the currently implemented geotagger in QGC.   FYI @kosakwayne

**Comment by DonLakeFlyer** [comment]
So geotagging is another area which I pretty much know nothing about. The Wintra folks contributed the code for it. Would once of you folks be interested in fixing this up and contributing it back?
