### ISSUE TITLE
UI: Toggle Panel to show details of waypoints

### ISSUE THREAD

**Issue by Saijin-Naib** [mavlink/qgroundcontrol#8500]
Tell us a bit about the feature:
- What problem does it solve?
  - Understanding and verification of detailed parameters of plan
- What does it do?
  - Toggle-able panel that shows details for each aspect/waypoint of a plan (command, location (lat/long), altitude (rel/abs), grade (from previous), angle (from previous), distance (from previous), and azimuth (from home).
- What flight stacks must it work with? (All, PX4, ArduPilot)
  - All
- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
  - All
- Are there other systems that have this feature?
  - Mission Planner, Tower
- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
  - N/A
- Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
  - ![image](https://user-images.githubusercontent.com/19295950/76028425-97d24500-5f00-11ea-9b54-5252868c8a74.png)

**Comment by DonLakeFlyer** [comment]
Can you explan what you use this for in detail? What values you look at and why? For example what does looking at a long list of lat/lon values tell you?

**Comment by Saijin-Naib** [comment]
As with many of my other recent requests, verification is the primary function. Did the import work? Was the data shifted? Precision issues? CRS issues? I suppose I can save/export the plan and put it into a text editor to perform these assessments as a work-around...

The lat/lon themselves aren't the most critical, but verifying the general flow the plan via the grade and angle I find helpful as it also helps to confirm that things like terrain following are being set properly between waypoints.

**Comment by DonLakeFlyer** [comment]
> The lat/lon themselves aren't the most critical, but verifying the general flow the plan via the grade and angle I find helpful as it also helps to confirm that things like terrain following are being set properly between waypoints.

These are the sorts of thing I need to know. I wan't to understand the problems you are trying to solve. Splatting up a massive list of information in the users face 90% of it being just noise doesn't seem helpful. I'd would rather figure out simpler ways to solve problems.

**Comment by Saijin-Naib** [comment]
I appreciate that intent, truly. That's why I posited a toggleable panel (hidden by default) for those need or feel the need to know these things. Most users likely don't need the noise.

The problem I'm trying to solve is generally: Can I trust this plan? How do I ensure that the plan is correct, site-accurate, and safe to deploy when I get to the field? I'm trusting my plan and the sUAS to do exactly what I told it that it should via the plan so I can do my job as RPIC and focus on the safety of the environment.

That's all a lot easier if I don't have "shit, was that waypoint 130ft above home, mission default height, terrain... Did the units get botched on import/export (Tower is guilty of this 🙄 [130ft imported as/into m so more like 430ft waypoint]), did I have my terrian precision set correctly so the hillock got recognized", etc.

I may be more... fussy about this than most because I'm a GIS Analyst, so these are the kinds of details I obsess about in my daily work and am very, very accustomed to not only knowing at a glance, but being in intimate control over.

**Comment by DonLakeFlyer** [comment]
The point is how to get to what you want in a user friendly way. We are in discussion for the next major release to add a much better visual display of information as well as a validator for Plans. Which would in turn understand things about vehicle dynamics so for example it would automatically tell you if you had a gradient that was too high for the vehicle you are flying. Or if you are going to fly into the ground or too close to the ground and so forth.

This is why I want to understand the things you check for. I want to automate that so that everyone has access to it.

**Comment by Saijin-Naib** [comment]
This is a simple, but very fresh in my mind example of what's prompted me with all this obsession over verifying details of each waypoint/mission item:  
![image](https://user-images.githubusercontent.com/19295950/76108294-4d0c0800-5fa8-11ea-95e8-7aff12fd7783.png)

This is the site I was set to survey yesterday. There is a lot of terrain variation within my site, and further complicating that variation is the presence of trees which also varied in height.
