### ISSUE TITLE
Plan View has buggy first waypoints in 4.0

### ISSUE THREAD

**Issue by Mapleguy** [mavlink/qgroundcontrol#8508]
## Expected Behavior
When dragging or editing the first waypoint in a mission, the mission data should update immediately. The first mission item should also be visually connected to the mission start.

## Current Behavior
Mission data is not updated immediately in the plan view when editing or dragging the first waypoint. The waypoint is also not visually connected to the mission start.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Create a mission in the plan view
2. Add one or more waypoints
3. Drag or otherwise edit the first waypoint
4. Wait a couple seconds for data mission data to update

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04
- QGC Version: Release 4.0.1, Stable_V4.0
- QGC build: Stable, source
- Flight Controller: N/A
- Autopilot (with version): N/A

## Detailed Description
This only critical part of this for me is the first waypoint and mission start no longer being visually connected. This is a rather important feature for a modified version of QGroundControl I am creating. While instantaneous response of mission data is also important, it's not critical.

**Comment by DonLakeFlyer** [comment]
> The first mission item should also be visually connected to the mission start.

That is not correct with 4.0. If you do not have a Takeoff item in the Plan then the mission is assumed to start from the air. In this case it will not connect to Launch.

**Comment by DonLakeFlyer** [comment]
> When dragging or editing the first waypoint in a mission, the mission data should update immediately.

Since you have no Takeoff item. The mission does not connect back to Launch. Hence there are not stats to show since there is no previous item.

**Comment by DonLakeFlyer** [comment]
The other change you may notice is that QGC no longer automagically adds a Takeoff item instead of a waypoint as the first item. You now need to manage that yourself. The reason being QGC doesn't know where you want your mission to start. At this point I"m interested in feedback on all of this since it's new. It's possible that a setting for "All missions start from ground" which defaults to true may be something that would be helpful. It's unclear to me whether missions starting from the air are a 0.1% use case or more prominent.

**Comment by DonLakeFlyer** [comment]
> Since you have no Takeoff item. The mission does not connect back to Launch. Hence there are no stats to show since there is no previous item.

FYI: QGC has been like this pre 4.0. Most people probably never noticed since takeoff was added automatically.

**Comment by Antiheavy** [comment]
> It's unclear to me whether missions starting from the air are a 0.1% use case or more prominent.

In my experience starting a mission from the air is commonly done during system development and basically never done in a production/commercial system.  I might image some exceptions to that rule in film/video applications maybe, but I have less experience there.

**Comment by Mapleguy** [comment]
In my particular case, it doesn't matter what waypoint are called or what commands are attached to them. I just need them all connected with the launch being the first point. The plan view is being used purely for planning, which needs to be simple, the actual drone doesn't use them for anything. I liked that just adding a waypoint added a takeoff as well, and I'd either like a feature to enable this or a direction to changing it back for my own uses. That would be great.

**Comment by DonLakeFlyer** [comment]
I've discussed with some other folks as well and I"m going to add a setting for starting from the air.
