### ISSUE TITLE
How to get out of full screen in QGround contro

### ISSUE THREAD

**Issue by Sneha-hub115** [mavlink/qgroundcontrol#8524]
Hi,
I’m using ubuntu 18.04 to build the px4 code for gazebo and jmavsim using QGround control. I’m stuck with the following issue:

   1. How to get out of full screen in QGround control.

Thank you

**Comment by dogmaphobic** [comment]
Double-click within the toolbar. Same way you put it in full screen mode to begin with. It's a toggle function.
