### ISSUE TITLE
How to check real flight with simulated flight.

### ISSUE THREAD

**Issue by Sneha-hub115** [mavlink/qgroundcontrol#8526]
Hi,
I’m using ubuntu 18.04 to build the px4 code for gazebo and jmavsim using QGround control. I’m stuck with the following issues:

    1. How to check real flight with simulated flight using QGround control, gazebo, jmavsim.

Thank you

**Comment by DonLakeFlyer** [comment]
GitHub is for bugs and/or feature request. Please use the various forums or slack for usage questions.
