### ISSUE TITLE
Post Android daily after Stable merge happens

### ISSUE THREAD

**Issue by Saijin-Naib** [mavlink/qgroundcontrol#8539]
https://play.google.com/store/apps/details?id=org.mavlink.qgroundcontrolbeta
![image](https://user-images.githubusercontent.com/19295950/76356068-b616b700-62eb-11ea-9e72-b49429217a70.png)

**Comment by DonLakeFlyer** [comment]
This is correct. Android builds must be updated manually. We don't have great daily builds yet since all focus is on Stable. They are actually behind Stable at the moment. Hence there hasn't been a reason to post a new daily build yet.

**Comment by Saijin-Naib** [comment]
Close as N/A.

**Comment by DonLakeFlyer** [comment]
I'm going to use this as a reminder to myself to post a new Android in a few days.
