### ISSUE TITLE
windeployqt didn't create Chinese translation file "qt_zh_CN.qm"

### ISSUE THREAD

**Issue by bys1123** [mavlink/qgroundcontrol#8553]
![image](https://user-images.githubusercontent.com/4748411/76609081-bdd79500-6551-11ea-82d2-608739c65285.png)
This will makes Debug console shows 'Qt localization for "zh_CN" is not present'
I tried to build "qt_zh_CN.qm" with Qt Linguist, this will get a 251kb file. The auto build "qt_zh_TW.qm" only have 125KB, seems have a different encoding.

There are also few bugs about Chinese language.

Trying to fix this.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76678750-5b47cd00-6615-11ea-8133-f398ff20e61f.png)
All pre-build files looks no problem.

**Comment by bys1123** [comment]
This a bug of qt 5.12.6

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76707365-976c5200-6729-11ea-9d3f-6fc93009f256.png)
Tried to build a micro project, nothing goes wrong.

**Comment by DonLakeFlyer** [comment]
Adding Gus...

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76707611-9e945f80-672b-11ea-90f9-2517a929def4.png)
Try to copy qgc localization files to new project, works fine.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76707910-ef0cbc80-672d-11ea-9c1f-f584d0640983.png)
Copy all the localization files to new project, then build, nothing wrong, but no translation folder created, and not changed the prefix.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76708019-b5888100-672e-11ea-9d5d-f6a2a187c00d.png)
Then must someting wrong in here.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/76776593-ea094500-67e1-11ea-8848-308efe380d5d.png)
Tried run windeployqt in my project, then I only have zh_TW now.

**Comment by bys1123** [comment]
5.12.7 has the same problem

**Comment by bys1123** [comment]
Tried to created a qgc_zh_TW.ts file see what will happen. Still only have qt_zh_TW.qm. Seems windeployqt didn't handle qgc_zh_CN.qm at all.

**Comment by DonLakeFlyer** [comment]
I think this is all working now

**Comment by magicjiuwen** [comment]
> Tried to created a qgc_zh_TW.ts file see what will happen. Still only have qt_zh_TW.qm. Seems windeployqt didn't handle qgc_zh_CN.qm at all.

Hi @bys1123 , 我也遇到了同样的问题，请问你是怎么解决的呢？感谢不吝赐教！

**Comment by 2528238270** [comment]
@magicjiuwen  参考这里的解释 https://lists.qt-project.org/pipermail/interest/2016-October/024845.html
Qt只会复制有qtbase_xx.ts的翻译，所以创建一个空的qtbase_zh_CN.qm可以解决问题。另外此问题只存在于Qt5，Qt6貌似正常。
