### ISSUE TITLE
Can't select waypoints above mission item 256

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8558]
User reported being unable to select waypoints with a mission index >256.  Attempting to do so would cause the vehicle to fly back to ~~the start of the mission~~ somewhere earlier in the mission.  User sent me their .plan file and I can see a difference in selecting animations for waypoints 256 and below compared to waypoints >256.

I've been able to recreate this with other large survey missions with >256 mission items.  Tested with today's daily build.

Here is a short video showing what I see on the ground:
https://youtu.be/H9Oysp6oGZo

**Comment by Antiheavy** [comment]
Looks like the waypoint index sometimes rolls over.  e.g. selecting 260 might roll over and actually select 4.

**Comment by DonLakeFlyer** [comment]
Just shows how many people do this with large numbers of waypoints. This bug has been there for ages.

**Comment by Antiheavy** [comment]
https://github.com/mavlink/qgroundcontrol/pull/8566  fixes the issue in our build!
