### ISSUE TITLE
I met the error "(command line):1: error: Assignment needs exactly one word on the left hand side."

### ISSUE THREAD

**Issue by AvadaX** [mavlink/qgroundcontrol#8561]
When I tried to build the project, I met the error 
`(command line):1: error: Assignment needs exactly one word on the left hand side.`

I am using Windows 10 bits, and I followed the tutorial https://dev.qgroundcontrol.com/en/getting_started/

**Comment by DonLakeFlyer** [comment]
As stated in the text you deleted to enter this:

"The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources"
