### ISSUE TITLE
[Bug] UI Error, unable to bind spektrum receivers after QGC v4.0.0

### ISSUE THREAD

**Issue by SwiftGust** [mavlink/qgroundcontrol#8571]
## Expected Behavior
QGC should be able to bind spektrum receiver without an issue.

## Current Behavior
Please describe what happens instead of the expected behavior.
QGC cannot bind to spektrum radio,
Ok button in the screenshot doesn't respond and displays the following message.
`qrc:/qml/RadioComponent.qml: ReferenceError: radioGroup is not defined`
![Screenshot from 2020-03-17 19-44-21](https://user-images.githubusercontent.com/13569579/76849048-05c72680-6888-11ea-842e-93da194e9223.png)

## Steps to Reproduce:
1. Connect to any vehicle
2. Go to Radio pane
3. Click Spektrum Bind button
4. Select any of receiver types and press Ok
5. You will get `qrc:/qml/RadioComponent.qml: ReferenceError: radioGroup is not defined`

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04
- QGC Version: QGC v4.0.0 & v4.0.3
- QGC build: stable release
- Autopilot (with version): PX4 1.9.0 dev

**Comment by DonLakeFlyer** [comment]
@SwiftGust Could you verify in a daily build from tomorrow that this is working for you now?

**Comment by SwiftGust** [comment]
@DonLakeFlyer I just tested spektrum bind and it's working well. Thank you.

**Comment by DonLakeFlyer** [comment]
@SwiftGust Thanks so much for reporting the problem and testing the fix
