### ISSUE TITLE
Mobile saves missions as name.plan.plan

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8574]
On mobile, the missions are saved as name.plan.plan files. Seems wrong to double the extension . They open fine though.

**Comment by Antiheavy** [comment]
thanks.  I assume this really has nothing to do with the other file access problem we are seeing in iOS right?  The branch we are on doesn't have the fix for this (yet)

**Comment by DonLakeFlyer** [comment]
> I assume this really has nothing to do with the other file access problem we are seeing in iOS right?

Don't think so
