### ISSUE TITLE
Not able to get live plotting

### ISSUE THREAD

**Issue by TSC21** [mavlink/qgroundcontrol#860]
Hi there,

I'm having a weird problem on QGS where I can't get any data being plotted on the Plot interface. Whatever data I choose (imu, attitude, flow data, etc), no line plot appears on screen. What can be the problem?

Thanks in advance!

**Comment by pmukherj** [comment]
+1 for having the same problem. 
Maybe the pixhawk time needs to be synced somehow?

**Comment by harristeague** [comment]
Now I'm having an issue where the autoscaling on the y-axis stopped working.
