### ISSUE TITLE
[Feature Request] Dragging landing location on map translates both landing location and landing loiter equally.

### ISSUE THREAD

**Issue by kosakwayne** [mavlink/qgroundcontrol#8623]
When speaking with users, they often find it complicated to fine tune the landing location after it has been initially placed on the map. Currently, when moving the landing location on the map the landing loiter stays in the same location and the glide slope angle changes. This current behavior when paired with locking the landing loiter map movement to only be rotational forces the user to change the landing location and adjusting the glide slope to translate the loiter location. 

What if we set it up so translating the landing location also translates the landing loiter. This gives the user the option of rotating landing direction by rotating the loiter, or translating the landing and loiter by simply translating the landing location. This also emphasizes locking the glide slope angle unless intentionally changing it by changing the specific value. 

![image](https://user-images.githubusercontent.com/33092810/77928114-a268cb80-726d-11ea-9967-38b09b14ec7c.png)

**Comment by DonLakeFlyer** [comment]
Make sense
