### ISSUE TITLE
Unable to download gps_helper.h, Qt creator fails build 

### ISSUE THREAD

**Issue by laxmanbobby** [mavlink/qgroundcontrol#8628]
Hello, 

I am trying to build QgroundControl using Qt Creator and am following the steps described in the online guide: https://dev.qgroundcontrol.com/en/getting_started/

I am using Ubuntu 16.04 on a virtual machine and trying to build QG from scratch without the video streaming feature so that I can use QGC on my Ubuntu 16.04 system with ROS. While downloading the necessary files, I run into an issue where items are not downloading from the github page resulting in a build error for Qt creator as files are missing. 

When I run the following command on my command line:
`git clone https://github.com/mavlink/qgroundcontrol.git --recursive`

The files begin downloading but eventually the download returns the following error: 
`fatal: reference is not a tree: 2bfc6ffb3ba74b60deab5aef8e34c2cb909c4edc
Unable to checkout '2bfc6ffb3ba74b60deab5aef8e34c2cb909c4edc' in submodule path 'src/GPS/Drivers'`

Additionally, the command:
`rhb@rhb-VirtualBox:~$ git submodule update  
fatal: Not a git repository (or any of the parent directories): .git`

does not return the desired result. As a result, when I build the qgroundcontrol.pro using Qt Creator 5.12.6, I receive the following build error: 
`/home/rhb/Desktop/qgroundcontrol/src/GPS/GPSProvider.h:21:36: fatal error: Drivers/src/gps_helper.h: No such file or directory`
because the download from the github page was incomplete. 

My questions are: 
1. How to remend the download failure issue?
2. In Qt creator, how do I disable building the parts in QGC that use video streaming features?

Thank you for your help!

**Comment by DonLakeFlyer** [comment]
From the text you deleted: "The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources"

**Comment by laxmanbobby** [comment]
Topic moved to: https://discuss.px4.io/t/unable-to-download-gps-helper-h-qt-creator-fails-build/16022
