### ISSUE TITLE
memory leak using qtquick2videosink 

### ISSUE THREAD

**Issue by miniboxhaha** [mavlink/qgroundcontrol#8650]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Please tell us what should happen as detailed as possible.

## Current Behavior
when use qtquick2videosink, everytime get a GST_MESSAGE_LATENCY, vedio will stuck for a moment,  and memory usage increase.
i run a pipeline with same element and same properties, only different is use autovideosink instead qtquick2videosink. stuck still happen, but mem not increased.
```
GstElement* VideoSurface::videoSink()
{
    if (_data->videoSink == NULL) {
        if ((_data->videoSink = gst_element_factory_make("qtquick2videosink", NULL)) == NULL) {
            //        if ((_data->videoSink = gst_element_factory_make("autovideosink", NULL)) == NULL) {
            qCritical("Failed to create qtquick2videosink. Make sure it is installed correctly");
            return NULL;
        }
        g_object_set(G_OBJECT(_data->videoSink), "sync", gboolean(false), NULL);
        g_signal_connect(_data->videoSink, "update", G_CALLBACK(onUpdateThunk), (void*)this);
        _refed = true;
    }

    return _data->videoSink;
}
```

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.
2.
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: 3.5.1
- QGC build: stable
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by andrewvoznytsa** [comment]
We have 4.0.x release already and video handling was changed a lot - we don't use qtquick2videosink anymore.
