### ISSUE TITLE
mavlink inspector SERVO_OUTPUT_RAW display error

### ISSUE THREAD

**Issue by vivienJ** [mavlink/qgroundcontrol#8688]
## Current Behavior
When the UAV has main and aux mixers it send two ORB actuator_outputs. These ORBS are displayed on the same plot on MAVLINK inspector -> SERVO_OUTPUT_RAW.

For exemple, on the screenshot, the main output 1 = 900 and the aux output 1 = 1500, QGC tries to display them both at the same time.

## System Information
- Operating System: Ubuntu 18
- QGC Version: 4.0.6
- QGC : build:stable
- Flight Controller: Pixhawk3Pro and Pixhawk4
- Autopilot (with version):  PX4 1.10.1

## Detailed Description
![bug_QGC](https://user-images.githubusercontent.com/12021517/80134468-15304280-859f-11ea-974f-68ec58661338.png)

**Comment by DonLakeFlyer** [comment]
It's just not possible to graph telemetry that works like that. And supporting it would be quite complex. So unlikely to happen anytime soon. You may need to go to vehicle logs to get that level of detail.

**Comment by JacobCrabill** [comment]
@DonLakeFlyer the previous QGC release (3.x) could do this (plot values from port "0" vs. port "1" independently); what changed?  Can we bring that back?

**Comment by DonLakeFlyer** [comment]
> what changed?

The old graphing code couldn't run in the new version of QGC. So it was completely rewritten from scratch. Along the way this feature was lost. At some point I'll try to get it back but it's unclear how much work it will take.

**Comment by KnightHawk06** [comment]
Is this still an issue in QGC v4.3.0 and PX4 1.14?

**Comment by ROSStargh** [comment]
> Is this still an issue in QGC v4.3.0 and PX4 1.14?

Confirmed still an issue.
