### ISSUE TITLE
[Feature request (or bug fix?)] Force Landing Pattern to be at the end of the mission

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#8691]
We've had a number of users get bitten by this recently.  At the moment it is possible to "insert" a landing pattern in the middle of a mission.  This tends to have all sort of bad effects when the user tries to fly this mission.

![image](https://user-images.githubusercontent.com/12117027/80266175-373dc980-8660-11ea-95c2-8fab397360ee.png)

QGC already only allows 1 landing pattern and it prevents you from adding new waypoints after a Landing Pattern.  However, it doesn't prevent you from inserting a landing pattern in the middle of a mission.  

It is nice to be able to add a Landing Pattern at any time.  Can we force the one and only Landing Pattern to always be at the end, no matter when or how it was added?

**Comment by DonLakeFlyer** [comment]
What Todd describes is exactly how it's "supposed" to work. Bug city.

**Comment by Antiheavy** [comment]
to repo:

1) start a Blank mission plan
2) plan takeoff
3) plan a survey or any number of waypoints
4) click on the takeoff or some waypoing/survey on the right-hand list (one that is NOT at the end of the mission)
5) plan a landing pattern, notice it is not at the end.

**Comment by DonLakeFlyer** [comment]
You have to add a Pattern to get it to screw up
