### ISSUE TITLE
QGC is opening a bunch of annoying popups

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/qgroundcontrol#8693]
branch master
![image](https://user-images.githubusercontent.com/1215497/80407758-8112f380-889c-11ea-89a9-7baab5dc09cd.png)

**Comment by patrickelectric** [comment]
![image](https://user-images.githubusercontent.com/1215497/80408585-c71c8700-889d-11ea-8e3e-7d9f5eba8f17.png)

**Comment by DonLakeFlyer** [comment]
OK, nice. Repro steps please?

**Comment by patrickelectric** [comment]
Connect a pixhawk in you pc, open mavproxy with the pixhawk as master and with a udp output for QGC
