### ISSUE TITLE
Load kml: Displacement error

### ISSUE THREAD

**Issue by Runge123** [mavlink/qgroundcontrol#8704]
## Expected Behavior
Load kml add correct position

## Current Behavior
When I load one kml in QGC, it is displayed in a incorrect position (shifted to the E)

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. I want to load this kml in Qgroundcontrol.
link to kml https://www.dropbox.com/s/0b5uccgp2uflm66/BertAOIpratDronica_epsg4326.kml?dl=0
2. This the kml as displayed by GE:
link to JPG https://www.dropbox.com/s/e30y886uvpsy78z/CorrectPositionPolygonKml_GoogleEarth.JPG?dl=0
3. In Qgroundcontrol I go to pattern > survey > load kml/shp
    The polygon (kml) loaded in Qgroundcontrol is shifted:
link to JPG https://www.dropbox.com/s/wtq07ki51jc5zkm/displacedPolygonkml_QGC.JPG?dl=0

## System Information
When posting bug reports, include the following information
- Operating System: windows 10
- QGC Version: 4.0.6

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
All files in dropbox link

**Comment by DonLakeFlyer** [comment]
Hmm it seems like a possible problem with the Bing (QGC default) map tiles being georeferenced incorrectly. If you switch the map provider to Google you'll see the polygon now shows up in the right place.

@dogmaphobic Is there a possibility this is a QGC problem. Or is it just bad tiles?

**Comment by Runge123** [comment]
I confirm that the above kml, as well as the following output kml created with QGC from it (https://www.dropbox.com/s/wa3imdfiufd1f9z/BertAOIpratDronica_epsg4326_v2.kml?dl=0), are correctly positioned in QGC if Google is selected as map provider. Also, the output kml is correctley positioned in GE and QGIS

**Comment by dogmaphobic** [comment]
Coordinate system mismatch? When you load it in QGIS, can you tell what is the coordinate system used? (it should also be within the kml file). I have no idea if Qt even has the notion of coordinate systems. I don't have the time now to look. I need to see the kml file and see how it is defined. I will do that when I have a chance.

**Comment by DonLakeFlyer** [comment]
Nope. The coordinates in the KML are all good. If you load it in Google Earth you can see where it goes. You can even load it in QGC, and then Save to KML and the load that back in Google Earth and see it goes back to the correct place. It's only screwed up if you are using Bing Maps. You can just switch map providers, go back to plan and see it move.

**Comment by DonLakeFlyer** [comment]
This problem has nothing to do with KML. Do this:
* Boot QGC
* Goto Plan
* Add a takeoff item next to some landmark. I used my own house.
* Change between Google/Bing. Note that the takeoff item stays at the same place
* Now change the takeoff item lat/lon to this:
![Screen Shot 2020-04-30 at 10 13 56 AM](https://user-images.githubusercontent.com/5876851/80739571-8e61f500-8acb-11ea-8717-319f57351863.png)
* Note the position visually change map provider look at again
* I get these differences. Can't remember which one is google or bing
![Screen Shot 2020-04-30 at 10 14 04 AM](https://user-images.githubusercontent.com/5876851/80739658-ac2f5a00-8acb-11ea-8a28-ce4f02f8064b.png)
![Screen Shot 2020-04-30 at 10 14 15 AM](https://user-images.githubusercontent.com/5876851/80739661-acc7f080-8acb-11ea-871e-2514e39ee786.png)

I think it just might be map provider georeference errors as opposed to anything QGC could b getting wrong.
