### ISSUE TITLE
QGC crashes when trying to click APMSubInfo in Values widget

### ISSUE THREAD

**Issue by Williangalvani** [mavlink/qgroundcontrol#8705]
Open ardusub SITL and try to change de displayed values.
![segfault](https://user-images.githubusercontent.com/4013804/80629509-52765380-8a29-11ea-8f03-ccbeffc05f95.gif)

It seems to be trying to access the fact group "aPMSubInfo" instead of "APMSubInfo"

**Comment by DonLakeFlyer** [comment]
That's another in inherent expectation in the code of fact group names being camelCase.
