### ISSUE TITLE
Custom application icon in custom build

### ISSUE THREAD

**Issue by akontsevich** [mavlink/qgroundcontrol#8711]
I see custom build is very flexible however still does not allow to specify custom icon for the application, I see `qgroundcontrol.png` still used everywhere:

- https://github.com/mavlink/qgroundcontrol/blob/master/QGCSetup.pri#L163-L165
- https://github.com/mavlink/qgroundcontrol/blob/master/debian/qgroundcontrol.install#L4
- https://github.com/mavlink/qgroundcontrol/blob/master/custom-example/deploy/qgroundcontrol-start.sh#L8
- https://github.com/mavlink/qgroundcontrol/blob/master/deploy/qgroundcontrol-start.sh#L8
- https://github.com/mavlink/qgroundcontrol/blob/master/deploy/qgroundcontrol.desktop#L6

Same thing for `qgroundcontrol-start.sh` and `qgroundcontrol.desktop`. Is it possible to cusomize their names and content? Or put their custom variants to `/custom` folder which will overwrite main variant? As it is not good to patch main QGC sources outside `/custom` folder. Thanks!

**Comment by DonLakeFlyer** [comment]
It is supported for Windows builds, but nothing else yet.

**Comment by akontsevich** [comment]
Fixed by  #8790.
