### ISSUE TITLE
iPad reports "QGroundControl fully supports Version 3.3 and above. ...."

### ISSUE THREAD

**Issue by Cattlebaron** [mavlink/qgroundcontrol#8713]
As this is my first report I apologies if it is in the wrong place. I assume the issue is with QGC running on an iPad as that is the source of the message. I have noticed that at present there is NO QGC for iOS operating system. The problem is:
I have upgraded to the latest version on my mac computer running Catalina OS. I think it maybe version 4.0.5 based on something that flashed across the screen but who knows. Subsequently I flashed the latest release of the firmware onto my Quadcopter and followed the setup routine. This was problem free. When I came to use my iPad to control the quad I got the  message "QGroundControl fully supports Version 3.3 and above. You are using a version prior to that.”
For me the issue is is the quad useable with my TX and forget about the iPad and 'missions' or do I pack the quad away until a new version of GQC is available for my iPad?

**Comment by DonLakeFlyer** [comment]
That's because iOS ios still running 3.5 versions. I'll try to get iOS updated at some point.
