### ISSUE TITLE
MAVLink inspector: show data that was only sent once

### ISSUE THREAD

**Issue by dayjaby** [mavlink/qgroundcontrol#8720]
## Expected Behavior
When I click on a mavlink message in "MAVLink Inspector", I expect to be able to see its data, even if it got sent only once.

## Current Behavior
If a message is sent before clicking on the MAVLink message but not afterwards, the fields are empty.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Click on "MAVLink Inspector"
2. Click on "COMMAND_ACK" (make sure that no COMMANDs are continously being sent)
3. See the fields empty

## System Information
When posting bug reports, include the following information
- Ubuntu 18.04
- QGC Version: 4.0.6
- QGC build: stable
- Flight Controller: PX4 sitl gazebo
- Autopilot (with version): PX4 master branch

## Log Files and Screenshots
![Screenshot from 2020-05-04 08-47-57](https://user-images.githubusercontent.com/164396/80942196-7c8e9380-8de4-11ea-8677-7dea66d65eaf.png)

**Comment by DonLakeFlyer** [comment]
The way it works now is on purpose. It doesn't start tracking values until you go to it. The reason for that is that it is CPU intensive to run which in turns kills your battery. QGC tries as best it can to not run your battery down like crazy while you are sitting at the field with no power.
