### ISSUE TITLE
Blinking airplanes on a map with ADS-B messages

### ISSUE THREAD

**Issue by theDimitron** [mavlink/qgroundcontrol#8771]
Hi everyone,

I have an issue with ADS-B massages (or with transponder_report topic). If there are more than one vehicle detected than both images of airplanes on the map star to blink. This all happens like in an antiphase with both vehicles. One of vehicles blinks very fast and is visible only for like a third of a second and then disappears for a second, so it cannot be seen properly. Another vehicle disappears from map for a third of a second and stays on the map a second long. Where does it come from and can it be adjust/controlled? 

- Operating System: Windows 10
- QGC Version: 4.0.6 and I’ve also built from master 
- Flight Controller: Pixhawk 4
- Autopilot: PX4 1.10.2dev

**Comment by DonLakeFlyer** [comment]
Are you sure each ADSB vehicle has a unique callsign? It sounds like you may have multiple vehicles reporting the same callsign and then as the new positions come in they bounce around to different positions.

**Comment by theDimitron** [comment]
I did some screenshots in Ubuntu.
In MAVlink Inspertor callsigns are different. The message also blinks, and shows first and second aircraft separately with same frequency as on the map. I’m using one fake aircraft with No 00004 and the other is a real FLARM-transmitter. The FLARM-device is attached to Pixhawk, driver is manually written and fake aircraft programmed within it (all INFO messages are for debug). But this blinking issue also comes out when FLARM detects a real aircraft (with no fake aircraft programmed).
I’ve also added Ubuntu-Terminal-output. 

![Screenshot from 2020-05-26 09-06-13](https://user-images.githubusercontent.com/29975181/82877289-4901dd80-9f3a-11ea-846a-9121c320dceb.png)
![Screenshot from 2020-05-26 09-06-31](https://user-images.githubusercontent.com/29975181/82877294-4a330a80-9f3a-11ea-9be6-778135078fbe.png)
![Screenshot from 2020-05-26 09-07-37](https://user-images.githubusercontent.com/29975181/82877298-4acba100-9f3a-11ea-9931-11962eecbb70.png)
![ICAO mismatch](https://user-images.githubusercontent.com/29975181/82877303-4b643780-9f3a-11ea-99f5-1cbecde5c189.png)

**Comment by DonLakeFlyer** [comment]
Should be fixed in both Stable and Daily builds.
