### ISSUE TITLE
ADS-B airplane traces

### ISSUE THREAD

**Issue by theDimitron** [mavlink/qgroundcontrol#8772]
Hi,
In my project I'm using FLARM device to track all airplanes above me in the sky. I publish the vehicles data thought transponder_report topic and airplane image appears on the map. The vehicle leaves some kind of “traces” of its images on a map, which disappear in 30-45 sec. I’m using QGC v4.0.6. Does anyone know why it happens?
The interesting part for me, when I build same version [4.0.6] of QCG with Qt the problem is no longer there. 
- Operating System: Windows 10
- QGC Version: 4.0.6 and I’ve also built from master 
- Flight Controller: Pixhawk 4
- Autopilot: PX4 1.10.2dev
![QGC_traces](https://user-images.githubusercontent.com/29975181/82821488-7e5bec00-9ea4-11ea-9fee-3482a712ee9b.png)

**Comment by DonLakeFlyer** [comment]
Attach a telemetry log which has the ADSB telemetry in it and I can take a look.

**Comment by theDimitron** [comment]
Can you please tell me how to do log for ADS-B messages? I can simply start a logging in QGC but I cannot find any useful information on ADS-B in it.

**Comment by DonLakeFlyer** [comment]
I need a telemetry log not a console log: https://docs.qgroundcontrol.com/en/SettingsView/General.html. Turn on  "save logs even if vehicle not armed". Run QGC with ADSB telemetry coming in. Close QGC. Attach/link the telemetry log here.

**Comment by theDimitron** [comment]
https://review.px4.io/plot_app?log=5c71628b-e44e-4641-8959-239723a6932c

**Comment by DonLakeFlyer** [comment]
This is a vehicle binary ulog not a QGC mavlink telemetry log.

**Comment by DonLakeFlyer** [comment]
Telemetry logs will be saved in your QGroundControl/Telemetry folder in your Documents folder which is in different places depending on OS.

**Comment by theDimitron** [comment]
Thank you for tip:) 

Here is the file:
[2020-05-26 21-35-15.zip](https://github.com/mavlink/qgroundcontrol/files/4685174/2020-05-26.21-35-15.zip)

**Comment by DonLakeFlyer** [comment]
QGC Bug. Working on a fix.

**Comment by DonLakeFlyer** [comment]
The fix is available in latest Stable. Daily will update some time today.

**Comment by smagellan** [comment]
@DonLakeFlyer, by the way: there are no callsigns on the initial screenshot; v4.13 has no callsigns, too. In the meantime, v3.3 had this feature: https://docs.qgroundcontrol.com/master/en/releases/stable_v3.3_long.html#ads-b-sensor-vehicle-display. Was it removed intentionally?

**Comment by smagellan** [comment]
@DonLakeFlyer, I may take a look at this, just let me know if it is ok for you

**Comment by smagellan** [comment]
@DonLakeFlyer, done: https://github.com/mavlink/qgroundcontrol/pull/9897
