### ISSUE TITLE
Anroid build error

### ISSUE THREAD

**Issue by akontsevich** [mavlink/qgroundcontrol#8778]
Android version builds and links fine, however fails on deployment step - building android package with following error:

```
Building the android package failed!
  -- For more information, run this command with --verbose.
  -- Skipping /home/aleksey/Qt/5.12.8/android_arm64_v8a/plugins/position/libqtposition_serialnmea.so. It has unmet dependencies: lib/libQt5SerialPort.so.
```

Seems `libQt5SerialPort.so` is missed in `QT_LIB_LIST` for Android. And `QT_LIB_LIST` is not specified for Android at all.

**Comment by DonLakeFlyer** [comment]
This seems to be working fine in CI. So it may have something to do with using 5.12.8 versus 5.12.6 which is the current supported version of Qt.

**Comment by akontsevich** [comment]
> This seems to be working fine in CI. So it may have something to do with using 5.12.8 versus 5.12.6 which is the current supported version of Qt.

No, same bug there:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Building the android package failed!
  -- For more information, run this command with --verbose.
  -- Skipping /home/aleksey/Qt/5.12.6/android_arm64_v8a/plugins/position/libqtposition_serialnmea.so. It has unmet dependencies: lib/libQt5SerialPort.so.
```

Any other ideas?

**Comment by akontsevich** [comment]
Success! Solved, could be wrong symbol in build dir name. Sorry.
