### ISSUE TITLE
Install multiple instances of QGC on Android

### ISSUE THREAD

**Issue by matthewgkerr** [mavlink/qgroundcontrol#8791]
I have created a custom version of QGC using the custom-example as a starting point.
I have applied custom branding in the custom project.
I would like to be able to install QGC from the app store and also deploy my custom application.
I would like to have both installed, but only intend to run one at a time.
With my application already deployed, when I go to the app store it says QGC is already installed.
What needs to be done for me to be able to do this?
I'm new to Android, but i'm thinking I need to modify something in the Android project, such as the Android Manifest file?

**Comment by DonLakeFlyer** [comment]
You need to change the package name: https://github.com/mavlink/qgroundcontrol/blob/master/android/AndroidManifest.xml#L2 if you want to deploy to the store.
