### ISSUE TITLE
Unsupported Windows toolchain, only Visual Studio 2017 64 bit is supported

### ISSUE THREAD

**Issue by kkingsbe** [mavlink/qgroundcontrol#8792]
## Expected Behavior
QGroundControl should build with no issues if Visual Studio 2017 is installed

## Current Behavior
Even though I installed Visual Studio 2017 as was described in the documentation, I am getting the above error. I was able to build with no issues when I was using the free trial of the enterprise edition of QT Creator, but I am now on the Open Source version

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Install QT Open Source and follow the steps in the documentation for setting up the environment
2. Clone QGC
3. Attempt to build

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: 4.0
- QGC build: Stable
- Flight Controller: N/A
- Autopilot (with version): N/A

## Detailed Description
As stated above, I was able to build with no issues on the QT Creator Enterprise Edition, but when I attempt to build on the Open Source edition I am given the above error. I have Visual Studio 2017 installed

**Comment by DonLakeFlyer** [comment]
Most like you are trying to build with a 32 bit compiler isntead of 64 bit.

**Comment by kkingsbe** [comment]
Where would I go to make sure I have a 64 bit compiler?

**Comment by tjwark-thunderbolt** [comment]
i'm getting this issue right now as well, it should be noted I already have visual studio 2019 installed previously for other work. I ADDITIONALLY installed vs2017 for this project, but i am still getting the same error.

i am building on a 64 bit machine, and have not modified any of the project files in any way.

**Comment by yizhilvmaoqiaozhi** [comment]
> 

i am same with you , could you tell me how to sovle it?

**Comment by bismahA** [comment]
I was having the same issue for 2 days
The problem with me was that I installed the QTcreator first and then the visual studio in this case the QTCreator does not recognize the visual studio and keeps on giving the same error
So i uninstalled both the things and did the following:

1. installed the 2019 community edition of visual studio(64 bit)
2. installed the 5.15.2 version of QTCreator
3. Cloned the qgroundcontrol repo from the official site
4. build the project
This worked in my case

**Comment by laiba1510** [comment]
Thanks Bismah 

It worked for me . but now I am facing this issue after Project build :-1: error: LNK1104: cannot open file 'QGCMapEngine.obj'.
Please tell what to do .

**Comment by laiba1510** [comment]
Thanks Bismah

It worked for me . but now I am facing this issue after Project build  error: LNK1104: cannot open file 'QGCMapEngine.obj'.
Please tell what to do .

**Comment by Daxdy01** [comment]
> I was having the same issue for 2 days The problem with me was that I installed the QTcreator first and then the visual studio in this case the QTCreator does not recognize the visual studio and keeps on giving the same error So i uninstalled both the things and did the following:
> 
> 1. installed the 2019 community edition of visual studio(64 bit)
> 2. installed the 5.15.2 version of QTCreator
> 3. Cloned the qgroundcontrol repo from the official site
> 4. build the project
>    This worked in my case

I'm getting the following error :
:-1: error: Unsupported Windows toolchain, only Visual Studio 2017 64 bit is supported.
Can you please help me with it ? 
Have you found out how can I resolve this issue ?

**Comment by Daxdy01** [comment]
> Thanks Bismah
> 
> It worked for me . but now I am facing this issue after Project build error: LNK1104: cannot open file 'QGCMapEngine.obj'. Please tell what to do .

Did your qgroundcontrol build fine afterwards ?

**Comment by bismahA** [comment]
> Can anyone please tell me how can I resolve this error ? 👎 error: Unsupported Windows toolchain, only Visual Studio 2017 64 bit is supported. I'm trying to run qgroundcontrol

Did you install the VisualStudio first and then the QT creator?
