### ISSUE TITLE
"Unsupported Windows Toolchain" when attempting to configure Android build

### ISSUE THREAD

**Issue by kkingsbe** [mavlink/qgroundcontrol#8809]
## Current Behavior
When I attempt to build for android I get an error that states "Unsupported Windows toolchain, only Visual Studio 2017 64 bit is supported

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.  Specify Android SDK and NDK locations inside of Tools > Options
2. Navigate to Projects > Android > Build
3. Choose SDK (none showed up even though I had already entered the path to mine)
4. Build for android

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: 4.0
- QGC build: Stable
- Flight Controller: N/A
- Autopilot (with version): N/A

## Detailed Description
I am trying to configure QT Creator to build for android, but when I build I get the above error. Along with this error, inside of Tools > Options > Android it does not save my Android NDK location, and inside of Projects > Android > Build > Android build SDK my SDK is not there to select, even though I had specified it inside of the options page. I was getting the same error last week when I was inadvertently trying to do a 32 bit build instead of a 64 bit build. Could a similar issue be occurring now?

**Comment by DonLakeFlyer** [comment]
Build support is on the forums or slack
