### ISSUE TITLE
"Error connecting: File exists" on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by tstellanova** [mavlink/qgroundcontrol#881]
Tried updating to the latest OSX 64 bit dmg today, and got this error when trying to connect via the same serial link I have used with previous versions of QGC.

"usbserial-A501LMZP Error connecting: File exists"

Tried Preferences -> Reset Settings and restarted, with the same result. 

The build date provided was: Sat Oct  4 01:07:26 PDT 2014

**Comment by Toffe87** [comment]
I also have this problem, on my OSX 

http://cl.ly/ZLQr

**Comment by Toffe87** [comment]
Edit: Fixed.

/var/lock had an file "LCK..usbmodemfa131" which locked the use of usbmodemfa131. 

rm -fR /var/lock/LCK..usbmodemfa131 

This command in terminal fixed it! :)
