### ISSUE TITLE
Altitude is coming from the wrong mavlink message(s)

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8851]
Details here: https://discuss.px4.io/t/wrong-altitude-display-on-qgc/17261

Need to figure out what is the right way.

**Comment by DonLakeFlyer** [comment]
I seem to remember some strange issues with VFR_HUD and ArduPilot.

**Comment by DonLakeFlyer** [comment]
From discussion it seems to me that since GLOBAL_POSITION_INT is a "fused" message it should always be sent. I've verified with ArduPIlot this is the case. With PX4 the answer still seems a bit unclear but it's my opinion that SIM_GPS_BLOCK is buggy in PX4.

**Comment by LorenzMeier** [comment]
It is a fused message in every case.
