### ISSUE TITLE
Compass calibration tab missing for Holybro Kakute F7 FC

### ISSUE THREAD

**Issue by bys1123** [mavlink/qgroundcontrol#8859]
1. Drone Configuration below, I'm sure it wired properly
![image](https://user-images.githubusercontent.com/4748411/85542388-9feaf780-b64b-11ea-9926-2a5db161cc70.png)
2. QGC 4.0.7 Shows Compass “Setup required“ on overview page
![image](https://user-images.githubusercontent.com/4748411/85542645-df194880-b64b-11ea-84fd-a9b1bc88574a.png)
3. But compass calibration tab is missing
![image](https://user-images.githubusercontent.com/4748411/85543260-78e0f580-b64c-11ea-9b88-c2ef11864561.png)
only shows:
- gyro
- accel
- horizon
4. 
![image](https://user-images.githubusercontent.com/4748411/85547056-15f15d80-b650-11ea-8cb9-a43ac8ff9646.png)
CLI shows compass is running well
5. QGC 3.2 works fine

**Comment by DonLakeFlyer** [comment]
Whether the Compass button shows up or not is controlled by the SYS_HAS_MAG parameter. If that param exists and is set to 1 but there is no Compass button then it is a QGC problem. If the param is missing or not set to 1 then it is a firmware/hardware problem.

**Comment by bys1123** [comment]
@DonLakeFlyer Thanks, SYS_HAS_MAG was 0, I will try to fix the firmware or document.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/85853053-6ac5dd00-b7e4-11ea-81f8-ec4c9193182c.png)
![image](https://user-images.githubusercontent.com/4748411/85853063-6f8a9100-b7e4-11ea-985c-0a8621eaedb2.png)
@DonLakeFlyer Do you have any suggestion to fix the altitude output? The baro is runing, but can't get alt information.

**Comment by DonLakeFlyer** [comment]
This is related to this: https://github.com/mavlink/qgroundcontrol/issues/8851. So far I haven't heard anything from the mavlink folks.
