### ISSUE TITLE
Unable to upgrade firmware on my Pixhawk 2.4.8 quads

### ISSUE THREAD

**Issue by Cattlebaron** [mavlink/qgroundcontrol#8883]
I find that I can't upgrade to the latest version of the firmware. Please note that I have read the manual re the upgrade procedure  many times, further I have not had problems with firmware upgrades previously.
Equipment;
iMac running OS version 10.15.5
QGroundControl version 4.0.8 (shows this version when installing the firmware)
The GUI works as expected but refuses to download the firmware the pixhawk flashes continually but the screen 'greys' out. Click the cancel button and all seems to return to normal. I find if I start QGroundControl first, select the firmware tab and then connect the Pixhawk I get the following error message:-
Error: Sync: Send Command: Invalid sync response: 0x53x 0x75
It is important to note this problem has occurred only after I upgraded the operating system on my Mac.
![Screen Shot 2020-07-06 at 1 56 02 pm](https://user-images.githubusercontent.com/33048669/86554508-2c24e500-bf91-11ea-8dbc-bddb8245844f.png)

**Comment by DonLakeFlyer** [comment]
What kind of a board is this?

**Comment by Cattlebaron** [comment]
Sorry about that, the flight controller is a PIXHAWK 2.4.8

**Comment by DonLakeFlyer** [comment]
Can you try a daily build. That has firmware upgrade changes with retries to get sync.

**Comment by bys1123** [comment]
Did you try to change the USB cable?

**Comment by Cattlebaron** [comment]
Thank's. I will try bys1123 solution first as it is the simplest and then I will tread in uncharted territory for me.

**Comment by Cattlebaron** [comment]
Won't have rime to follow up for at least two weeks so I will close the issue.

**Comment by Cattlebaron** [comment]
Quick update, I tried a brand new cable to no avail.
