### ISSUE TITLE
No telemetry after updating PX4 with QGC

### ISSUE THREAD

**Issue by DiegoHerrera1890** [mavlink/qgroundcontrol#8904]
Hello, Dear community.
I updated the firmware version to the latest version of PX4.
Then, I opened the QGC and is not recognizing the PX4. I’ve seen the device manager and the driver is correctly installed.
There is a way to select the correct port in QGC?
also, I’m receiving “Error on link SIK Radio on COM3(autoconnect). Error connecting: Could not create port. The semaphore timeout period has expired”

Thank you so much

**Comment by DonLakeFlyer** [comment]
Reboot your computer

**Comment by DiegoHerrera1890** [comment]
I did it but doesn't work... Any suggestions?

**Comment by DonLakeFlyer** [comment]
You could try turning off AutoConnect from settings and creating a manual link for it. Doesn't seem like more can be done from the QGC side. Since the error is more like a hardware problem.

**Comment by DiegoHerrera1890** [comment]
Bro I've connected the PX4 to my laptop and tablet and is the same problem...

**Comment by DiegoHerrera1890** [comment]
I got the answer here [updating firmware](https://nxp.gitbook.io/hovergames/userguide/qgroundcontrol/firmware#updating-the-telemetry-radio-firmware)
