### ISSUE TITLE
Master Crash on Takeoff deletion

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#8908]
QGC Master crash when I try to delete a Takeoff mission item while other waypoint are still planned.
To reproduce:

Start a Blank Plan mission:
Add a takeoff point 
Add a waypoint
Add another waypoint
Delete the takeoff item

The crash is related to the TerrainProfile feature. QGC is trying to access _amslTerrainHeight list when the list is empty.

**Comment by DonLakeFlyer** [comment]
Need some more info:
* What is the "All Altitudes" set to
* What firmware/vehicle type in Vehicle Info?

**Comment by FlavioTonelli** [comment]
I just reproduced with that configuration:
<img width="251" alt="Schermata 2020-07-12 alle 18 36 49" src="https://user-images.githubusercontent.com/9391950/87251817-c8a62600-c46e-11ea-9340-1744cf63a225.png">
Just clicking the bin icon let QGC crash:
<img width="1275" alt="Schermata 2020-07-12 alle 18 38 59" src="https://user-images.githubusercontent.com/9391950/87251876-1fabfb00-c46f-11ea-88c6-5b0fa5de3796.png">

**Comment by DonLakeFlyer** [comment]
Hmm, that's what I was trying as well.

**Comment by FlavioTonelli** [comment]
I gave a try to QGC daily and I can still reproduce the problem. It seems it doesn't trigger 100 % of time but it's still quite easy to let it crash.

**Comment by DonLakeFlyer** [comment]
I should be able to figure it out by inspection. There have been a bunch of crashes similar to this which I've already fixed. So I'm pretty familiar with what goes wrong. Eventually closer to stable I'll guard against these in the terrain profile code. But for now a crash is better for collected bugs.

**Comment by DonLakeFlyer** [comment]
@FlavioTonelli Can you try out this change?

**Comment by FlavioTonelli** [comment]
Seems promising. I can not have QGC crash on my laptop right now.
Tomorrow I will give a try on my linux workstation as well.

**Comment by DonLakeFlyer** [comment]
Thanks for testing. I was able to reproduce the crash. It was caused by a stale pointer on the first item which I fixed.

**Comment by FlavioTonelli** [comment]
Nice catch with that pointer!
As far as I can say the issue seems fix to me.

**Comment by DonLakeFlyer** [comment]
@FlavioTonelli Thanks so much for the report
