### ISSUE TITLE
Master: Survey Camera Trigger is not planned correctly on non-standard area

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#8909]
When planning a Survey mission with option "Hover and capture image" flagged, all the waypoints have a camera trigger associated whit them( QGC is asking for a shoot every time the drone reach a waypoint).
This is the correct behavior if the polygon is a square or a rectangle but it is not when the area to survey is a non standard one.
You can see attached an example of what I mean with non standard area.
<img width="706" alt="Schermata 2020-07-12 alle 17 51 03" src="https://user-images.githubusercontent.com/9391950/87251095-757da480-c469-11ea-8b71-99e8b93ee66e.png">
QGC shall ask for camera shooting only inside the green area, but it is instead planning shoot all over the drone path.

**Comment by DonLakeFlyer** [comment]
QGC does not support surveys over concave polygonal areas, only convex. There are other issues in the system about adding support for this. But I wouldn't expect it any time soon.
