### ISSUE TITLE
Master: Wrong Mission Item frame when Terrain following

### ISSUE THREAD

**Issue by FlavioTonelli** [mavlink/qgroundcontrol#8910]
When Planning a mission with "All altitude" set to "Above Terrain" the Mission Item's frame field is set to MAV_FRAME_GLOBAL_RELATIVE_ALT.
It shall instead be set to MAV_FRAME_GLOBAL since the altitude is expressed in meter over the sea.

**Comment by FlavioTonelli** [comment]
I did some investigation on that issue and it seems the frame is set correctly at a first stage but then is overrided before exiting the void SimpleMissionItem:_setDefaultsForCommand(void) function.

**Comment by DonLakeFlyer** [comment]
Wow, this is majorly screwed up. Not sure how I tested this in the first place!

**Comment by DonLakeFlyer** [comment]
Thanks for the report and digging into it
