### ISSUE TITLE
not able to build qgroundcontrol.pro in qt because of some error in vehicle.h

### ISSUE THREAD

**Issue by dhanusrikar** [mavlink/qgroundcontrol#8916]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Please tell us what should happen as detailed as possible.

## Current Behavior
Please describe what happens instead of the expected behavior.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.
2.
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: v4.0.9
- QGC build: stable
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.
**D:\software\qgroundcontrol-source_code\qgroundcontrol\src\Vehicle\Vehicle.h:1584: warning: C5208:** unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

![Screenshot (40)](https://user-images.githubusercontent.com/42804008/87529582-d5b05880-c6ac-11ea-8a8f-d3d6714cad0c.png)

**Comment by dhanusrikar** [comment]
i am new to both qt and qgroundcontrol, so anyways when i am trying to build the qgroundcontrol.pro i am getting the following errors. 
Thank You

**Comment by DonLakeFlyer** [comment]
Are you using VS 2017? That is the only supported compiler.

**Comment by dhanusrikar** [comment]
YES
![Screenshot (41)_LI](https://user-images.githubusercontent.com/42804008/87871187-f8ec4800-c9cb-11ea-9161-1b98e37a7e5c.jpg)

**Comment by DonLakeFlyer** [comment]
Hmm, that is a newer compiler than I have even though I just updated. What flavor of VS 2017 are you using? Enterprise/Community/...?

**Comment by dhanusrikar** [comment]
It is community

**Comment by DonLakeFlyer** [comment]
Looks like 16.6 is still in preview as far as I can tell. I don't get it when I update. How did you get 16.6?

**Comment by DonLakeFlyer** [comment]
The problem is discussed here: https://developercommunity.visualstudio.com/content/problem/1034754/warning-c5208-a-c20-feature-occurs-when-compiling-1.html
