### ISSUE TITLE
IOS will not connect to telemetry radio

### ISSUE THREAD

**Issue by jimdgit** [mavlink/qgroundcontrol#8917]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Using a lighting to USB adaptor when you connect the holybro telemetry radio it should connect to the PX4

## Current Behavior
Nothing happens.

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]
- QGC Version: 3.3.4 ios
- QGC build: from app store
- Flight Controller:px4 
- Autopilot (with version): 1.11 beta 2

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by dogmaphobic** [comment]
iOS does not support serial connections (lighting to USB adaptors are mostly bogus). QGC for iOS only supports TCP/IP connections.
