### ISSUE TITLE
Advanced Tuning for VTOL airframe (in Multirotor mode)

### ISSUE THREAD

**Issue by saengphet** [mavlink/qgroundcontrol#8932]
Hello, I have experienced tuning multirotor attitude controller using Advanced Tuning before (using graph and adjust PID gains). This feature reduces time-consuming in tuning multirotor sinificantly. However, It could not be used to tune VTOL in multirotor mode because there are no Advanced Tuning Tab. Is it possible to implement Advanced Tuning for VTOL airframe using graph and adjust PID gains in the same way as multirotor airframe?

reference page:
https://docs.qgroundcontrol.com/en/SetupView/tuning_px4.html

**Comment by saengphet** [comment]
I have already implemented this feature (VTOL in MC mode PID tuning) by myself. Thanks

**Comment by DonLakeFlyer** [comment]
Submit a pull!

**Comment by saengphet** [comment]
> Submit a pull!
Hi, we are testing this feature to ensure that everything is ok after that I will submit PR as your recommedation. Thank you !!
