### ISSUE TITLE
Plan: Transition from existing plan to different vehicle does not work correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#8940]
Example problem:
* Start QGC 
* Connect to a vehicle with a Plan on it
* Disconnect that vehicle
* Connect to another vehicle with a different or no Plan (this could even be the same vehicle which had the plan on it futzed with in between connects)
* Plan view shows stale plan from original vehicle connect

There are many different incarnations of cases where things are incorrect. Above is just one example. The question is what to do when the Plan being shown is stale with respect to either the vehicle it was associated with disconnecting or a new active vehicle coming into play.

**Comment by DonLakeFlyer** [comment]
Note that this changes the following user model sequence which may currently be in use:
* Create an plan while offline (not connected to vehicle)
* Connect to a vehicle
* Upload the plan you created to the vehicle

Not sure how important that is. Maybe @antiheavy should comment.

**Comment by DonLakeFlyer** [comment]
All of this always ends up being way more complicated than you think it is.

**Comment by DonLakeFlyer** [comment]
I need to put some more though into this. My proposal above I think is going to be too annoying for some use cases.

**Comment by DonLakeFlyer** [comment]
I removed the here is how it should work section from the first comment since I realized it was crap once I started working on this. I'll have a detailed post on how it works soon as I'm done.

**Comment by DonLakeFlyer** [comment]
> All of this always ends up being way more complicated than you think it is.

And yes, this statement ended up being truer than I originally thought.

**Comment by DonLakeFlyer** [comment]
To explain how it will work you need to understand the concept of the Plan View running "online" or "offline". Online means that the Plan View has a real vehicle associated with it, you can save/load to disk or upload/download to the vehicle. Offline means that the Plan View does not have a connected vehicle associated with it. You can only save/load from disk. 

The transitions from offline to online and back are what cause all the complexity with the user model. The contents of the Plan View itself also add to the various states to manage. It can be: empty, clean plan, dirty plan. Dirty means the plan have changed since last load/save/download/upload. Clean means there is a plan but there are no unsaved changes.

So here is how it works explained against these states:

* Offline -> Online
  * Plan view empty or clean - Plan view will change to show the Plan from the new vehicle
  * Plan view dirty - Plan view will show prompt asking the user what to do
* Online -> Offline
  * Plan view empty or clean - Plan view will be cleared
  * Plan view dirty - Plan view will show prompt asking the user what to do
* Online -> Online (active vehicle change)
  * Plan view empty or clean - Plan view will change to the plan from the new active vehicle
  * Plan view dirty - Plan view will show prompt asking the user what to do

The two prompts you get are based on whether the end state of the transition is online or offline:
![Screen Shot 2020-07-27 at 3 55 45 PM](https://user-images.githubusercontent.com/5876851/88601141-df2eae80-d024-11ea-8a15-7a0213ef7778.png)

![Screen Shot 2020-07-27 at 3 56 13 PM](https://user-images.githubusercontent.com/5876851/88601143-e05fdb80-d024-11ea-8f93-4e38f3bdde18.png)

**Comment by DonLakeFlyer** [comment]
@hamishwillee You might want to look at the wording here to see what you think.

**Comment by DonLakeFlyer** [comment]
The other quirkiness with this is that those popups show up in the current view you are in. Not just in the Plan view. We don't currently have a mechanism for dialogs which are parented to a specific view. I figure since this only happen in certain cases that it's good enough. If it's determined to be a real problem I can put some more effort into it to support parenting to the Plan View only.

**Comment by Antiheavy** [comment]
Sorry for the delayed reply. My view on this is pretty much what you’ve been discovering. It’s complicated and hard. The approach I’ve seen work best in many other ground station softwares is when the onboard mission is shown as a ghost (translucent) or different color. CRC or other methods of knowing if the vehicle and ground are out of sync are typically used.
