### ISSUE TITLE
Android text to speech audio output problem 

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#8942]
Hi

There is an issue in audio output of QGC. My android phone and tablet have no audio output in QGC . so in my opinion qgc dont't work  properly with some android devices.

similar problem: 
https://discuss.px4.io/t/qgc-have-no-audio-output-in-android/9315
https://discuss.ardupilot.org/t/help-needed-on-qgc-audio-speech-alerts-for-android/58205

**Comment by DonLakeFlyer** [comment]
Not sure. I think I've heard people say they tweaked some settings on their devices and got it to work.

**Comment by moreba1** [comment]
> settings

wich settings ? diong media sound setting ?

**Comment by DonLakeFlyer** [comment]
No idea. I'd ask on slack and/or qgc forums.

**Comment by DonLakeFlyer** [comment]
Let me know if you figure out any details

**Comment by moreba1** [comment]
I realized the problem
English must be selected for the text-to-speech language.
