### ISSUE TITLE
Build Android APK Failed

### ISSUE THREAD

**Issue by SpringSmell** [mavlink/qgroundcontrol#8979]
The API level set for the APK is less than the minimum required by the kit.
The minimum API level required by the kit is 21.
Error while building/deploying project qgroundcontrol (kit: Android for armeabi-v7a,arm64-v8a,x86,x86_64 (Clang Qt 5.14.2 for Android))
When executing step "Build Android APK"

**Comment by SpringSmell** [comment]
My new project installation was a normal success.

**Comment by DonLakeFlyer** [comment]
As stated when creating issues. This is not for reporting build problems.
