### ISSUE TITLE
[Bug] Plan tab altitude plot only plots in Meters

### ISSUE THREAD

**Issue by kosakwayne** [mavlink/qgroundcontrol#8981]
Using DailyBuild from August 12th

It seems that the plan tab "Height AMSL()" values are plotted in meters, regardless of the axis label or unit set in Qgroundcontrol settings

mission planned in Bozemon Montana with base units in meters
![2020-08-12 10_48_27-](https://user-images.githubusercontent.com/33092810/90038998-b1d03a80-dc8b-11ea-9792-44c2209749c0.png)

Changed units in Qgroundcontrol to feet. Restarted application
Same location for mission planning: Bozemon montana with base units in feet
![2020-08-12 10_46_55-QGroundControl Daily](https://user-images.githubusercontent.com/33092810/90039093-cf050900-dc8b-11ea-9c21-4a28575ad077.png)

The plot values are very similar, but should be different by a factor of 3.3. Bozeman's alttitude is ~1460m, showing that using the base units of Meters yields correct results

**Comment by DonLakeFlyer** [comment]
@kosakwayne There should be a new daily in about an hour. Can you verify the fix?

**Comment by DonLakeFlyer** [comment]
Hold off on that. I found another problem.

**Comment by DonLakeFlyer** [comment]
This should be fixed now
