### ISSUE TITLE
Seeking help on sending and receiving data through XBee

### ISSUE THREAD

**Issue by baileyqbb** [mavlink/qgroundcontrol#899]
Hi All,

I am new in this MAVlink, and trying to develop my own control panel which could be integrated to QGC. The mission is mainly to send some MAVLink commands to my quad through usb-based XBee. How could I use the existing links to send and receive the data to and from the quad?

Right now, I am thinking about using the "sendMessage" function in MAVLinkProtocal class to send command data. However, it somehow doesn't work. Specifically, I first create a MAVLinkProtocal pointer, say 
MAVLinkProtocal *plink = new MAVLinkProtocal;
 Then call 
plink->sendMessage(&msg);
 in which the msg is the mavlink message. The XBee has been connected to the QGC previousely.

Any suggestions? Some examples or clues on the implementation would be greatly appreciated. 

Thanks a lot.

**Comment by canaydinn** [comment]
Hi, baileyqbb 
I want to send my own value with xbee to the arducopter with using mavlink. Do you know how can ı use mavlink library with arducopter

Best regards
