### ISSUE TITLE
Is fine position adjustment by button a possibility?

### ISSUE THREAD

**Issue by Sextant** [mavlink/qgroundcontrol#9004]
Hi all,

I have this posted over at discuss.px4.io and jimdgit there, suggested I post it here...

What I am trying to understand is if there is functionality available in QGC, or some sort of plugin, that would enable predefined small movements activated by touchscreen buttons when flying and utilizing FPV?

To better explain, here is an example. Imaging I flew the drone to a point and then initiated a position hold 100 feet up and a couple of feet off and facing, a tall structure such as smokestack or radio tower. I’m viewing it through my FPV and what I want to be able to do is make slight adjustments to the drone’s position, say a couple of inches at a time, by pressing buttons on the touch screen of my controller. 6 buttons, one each for right, left, up, down, back, or forward.

Is this possible?

My current build: PX4, Pixhawk2 Black Cube, Herelink Air Unit / Controller, Here2, ArduPilot Copter. I have the latest firmware updates.

Thanks in advance for any replies.

Cheers…

**Comment by DonLakeFlyer** [comment]
That is not supported. Kind of a too specific use case to be added to QGC. Also dubious as to how it would work since most GPS won't give you that kind of positioning accuracy.
