### ISSUE TITLE
MOTOR CALIBRATION

### ISSUE THREAD

**Issue by zeynepzelal** [mavlink/qgroundcontrol#9031]
We are having an issue with motor calibration. Eventhough it had been working properly, we had lost the control after an hour. The error says “FAILED: CHECK THE THRUSTER 1 AND FRAME SETUP.” We are 100% that connections are proper. We have no time please help us...
Regards,
Zelal

**Comment by DonLakeFlyer** [comment]
This doesn't have much to do with QGC. You should ask this question on the appropriate firmware forum.
