### ISSUE TITLE
Option to hide the instrument panel, info panel, camera recording panel, etc

### ISSUE THREAD

**Issue by RhinoAus** [mavlink/qgroundcontrol#9040]
Tell us a bit about the feature:
- What problem does it solve?
Currently the information boxes on the right hand side of the screen take up significant amount of screen space despite often not being needed. Adding the ability to hide those panels (just as per the camera view) would declutter the screen, especially when viewing video

- What does it do?
Adds a button similar to that to hide the camera view for the instrument panel and other panels shown on the right hand side of the screen

- What flight stacks must it work with? (All, PX4, ArduPilot)
All

- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
All

- Are there other systems that have this feature?
No

- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
None

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
Basic mockup:
![Open](https://user-images.githubusercontent.com/6235811/91302447-e09cf380-e7e9-11ea-8503-00524af5d777.jpg)
![Closed](https://user-images.githubusercontent.com/6235811/91302449-e2ff4d80-e7e9-11ea-9daf-fd52a499bd6b.jpg)

**Comment by DonLakeFlyer** [comment]
* Use a Daily Build
* Switch to video filling the window
* Double-click the video and all widgets are hidden
* Double-click again and they will come back
