### ISSUE TITLE
Follow Me gone

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#9058]
Follow Me has disappeared under Vehicle Setup.
If I switch to Follow Mode via RC QGC says "unknown flight mode".

QGC android daily 2020-09-05

**Comment by DonLakeFlyer** [comment]
If you are talking about ArduPilot, Follow Me is not yet supported for ArduPilot. Requires ArduPilot support to make it work. Detailed in an issue here: https://github.com/ArduPilot/ardupilot/issues/15098
