### ISSUE TITLE
Feature Request: Dronie

### ISSUE THREAD

**Issue by twistedwings** [mavlink/qgroundcontrol#9066]
I would like to see Dronie like in Mission Planner for Ardupilot (aka Tower).

[https://www.youtube.com/watch?v=LszjUnfbHt4](url)

Description from 3dr

Introducing the One-Touch Dronie

DECEMBER 10, 2014
COMPANY, UNCATEGORIZED
Get the ultimate selfie with one simple touch on your tablet. We’ve updated our dronie feature
in DroidPlanner to make it easier than ever for you to see your world from above — with you
at the center of it.

How it works

To set up the dronie, place the drone 8m away, facing you, and make sure that the path
you’re facing has at least 100m of clearance (about a football field).
The copter will automatically take off and go back 50m and up 30m from its initial location.

Turn on your controller and keep the throttle stick down; this is in case of an emergency.
When your copter and camera are ready, connect the 3DR radio to your Android device and
open Droidplanner. Hit Connect. Next you’ll see two buttons: Dronie and Arm. Press Dronie
to set up the flight path. The map will update with the path plan and a warning to stand
back from the drone. Now hit Arm.

When you’re ready to go, press Auto. The drone will take off, turn the camera towards
you and fly back and up. When it reaches its peak at 50m out and 30m up, it will
return to land and disarm.

You can modify the dronie as you would any other mission. Go into the Editor after pressing
Dronie and you should see a path you can modify. The first waypoint is its take off height.
The second point is the ROI (which should where you’re standing). The third waypoint is
the peak altitude; you can set this to be as high and as far out as you want. The fourth
waypoint is a slow down point when it gets near you on descent.

What you get

For half a minute, you get to be the center of the world. But this selfie doesn’t scream vanity.
This selfie tells a story: You’re part of something immense. As the drone pulls up and back,
it enacts a narrative, so you and your friends not only see you, but see you in a
new context — a pioneer, discoverer of something bigger. It’s a self-portrait and a
landscape at once. And it looks so very cool.

Check out this epic dronie story below, made with IRIS+. Then get out make your own!

**Comment by DonLakeFlyer** [comment]
Something that fancy requires firmware support.

**Comment by twistedwings** [comment]
I don't think so.
It works (or has worked) in Tower with the standard firmware.
All it does is to generate a mission with 8 waypoints.

**Comment by booo** [comment]
As far as I understand the request you would like to take selfie with the touch of a button.

I think this is possible in QGC with a properly planed mission. For convenience you can safe the mission and move it to a new location.

I don't see any ambitions from QGC to support such special cases. I guess there are quite a lot of other special flight plans people would like us to implement. Therefore I close this.
