### ISSUE TITLE
Wrong battery status

### ISSUE THREAD

**Issue by cuhome** [mavlink/qgroundcontrol#9079]
I am testing the qgc built daily and found several bugs in the battery status:
First: When the battery is not connected, the charge state displays OK, which will mislead the user that the battery connection has been completed.
Second: qgc cannot display uavcan battery voltage, because UAVCAN battery message does not include battery_cell.
qgc version：
![image](https://user-images.githubusercontent.com/31507501/93579246-d75e0b80-f9d0-11ea-8f0b-10e4ade2fca0.png)

![image](https://user-images.githubusercontent.com/31507501/93579452-0f654e80-f9d1-11ea-95bb-26cc50d331a8.png)

**Comment by DonLakeFlyer** [comment]
> qgc cannot display uavcan battery voltage, because UAVCAN battery message does not include battery_cell.

I don't know what this means? What exactly goes wrong?

**Comment by DonLakeFlyer** [comment]
> qgc cannot display uavcan battery voltage, because UAVCAN battery message does not include battery_cell.

If you mean the mavlink 'BATTERY_STATUS' message in this case does not include voltage data. Then isn't that a firmware bug?

**Comment by cuhome** [comment]
![image](https://user-images.githubusercontent.com/31507501/93662205-fe7c1200-fa90-11ea-802a-e8fe1e47bb4d.png)
The old version of the battery data reads this information, the new version reads this and the following information.
![image](https://user-images.githubusercontent.com/31507501/93662243-574baa80-fa91-11ea-9b38-2d75a20b899c.png)

![image](https://user-images.githubusercontent.com/31507501/93662618-fbceec00-fa93-11ea-8377-82189c359d35.png)

**Comment by cuhome** [comment]
If I modify the firmware of the flight controller, can I modify it like this?

**Comment by DonLakeFlyer** [comment]
You'd have to ask the firmware folks about that. Would be good the enter an issue against firmware on this for discussion.

**Comment by DonLakeFlyer** [comment]
> When the battery is not connected, the charge state displays OK, which will mislead the user that the battery connection has been completed.

How did you get in to this state. How can the battery not be connected yet the vehicle is still connected?

**Comment by cuhome** [comment]
I use usb to connect the flight controller to the computer. Another problem I described is the problem of the qgc and px4 firmware coordination. For the 1.11.0 firmware, run the daily build qgc and use uavcan battery, whatever This failure occurs on all boards. If it is repaired by modifying the firmware, the user will need to wait for half a year. Unfortunately, the CUAV X7 series flight controller cannot use the 4.0.10 qgc; so it must use the daily built qgc, and it uses uavcan batteries by default.

**Comment by DonLakeFlyer** [comment]
LIke I said this needs to move to a firmware issue and discussed there. QGC is doing things correctly with respect to mavlink spec as far as I can tell. Whereas firmware seems to have a significant bug in it. It's doesn't take 6 months to release point releases.

**Comment by DonLakeFlyer** [comment]
I'm closing the issue on the QGC side until someone can show that QGC is doing something wrong.
