### ISSUE TITLE
Language setting on Daily Builds

### ISSUE THREAD

**Issue by farid002** [mavlink/qgroundcontrol#9080]
Language remains same (system - english) although I am trying to switch it to Azerbaijani or Turkish (or any other language). Azerbaijani language is fully translated by me and my friend on Crowdin a few weeks ago.
-OS = Windows 10
-QGC= Daily Builds
![Screenshot (1)](https://user-images.githubusercontent.com/42000602/93627717-67627c00-f9f6-11ea-92b5-48b64cd693be.png)
![Screenshot (2)](https://user-images.githubusercontent.com/42000602/93627725-69c4d600-f9f6-11ea-862f-13fcaf578e50.png)

**Comment by farid002** [comment]
Additionally, we have checked on Android, language sources for Turkish and Azerbaijani can not be installed. Here are some screenshots @DonLakeFlyer 
![WhatsApp Image 2020-09-23 at 00 01 24](https://user-images.githubusercontent.com/42000602/94030212-9c901500-fdce-11ea-956f-bafbdbdc0193.jpeg)
![WhatsApp Image 2020-09-23 at 00 08 03](https://user-images.githubusercontent.com/42000602/94030217-9dc14200-fdce-11ea-9fb4-d12f30c8d300.jpeg)

**Comment by DonLakeFlyer** [comment]
![Screen Shot 2020-10-08 at 4 02 46 PM](https://user-images.githubusercontent.com/5876851/95522048-edcc0700-097f-11eb-93a5-c70d0cadfb9a.png)

Sorry for taking so long. Thanks for the translations.

**Comment by farid002** [comment]
Thank you @DonLakeFlyer !
