### ISSUE TITLE
Add customization for private application settings

### ISSUE THREAD

**Issue by tzuriel-spearuav** [mavlink/qgroundcontrol#9084]
I need to add a bunch of application settings and the process requires that I -
1. add new defines to AppSettings.h and .cc
2. add new default values in App.SettingsGroup.json

Suggested approach to have an App.CustomSettingsGroup.json for these custom values, and have an AppSettings plugable extension that can define those settings

**Comment by DonLakeFlyer** [comment]
There should be no need to add custom settings directly to the QGC settings objects. Just create your own settings group and reference it from your core plugin override.
