### ISSUE TITLE
Battery parameters not taking effect on PX4 latest stable (1.11.0)

### ISSUE THREAD

**Issue by WhiteBearSpirit** [mavlink/qgroundcontrol#9098]
PX4 have changed primary battery parameters from BAT_* to BAT1_*
However, while calibrating battery (Battery tab) QGC sets deprecated parameters BAT_* and leaves BAT1_* intact.
This leads to undefined battery readings during flight.
More details here: https://github.com/PX4/Firmware/issues/15701

My suggestion is to set both of these parameter groups while calibrating battery.

- QGC Version: any
- Autopilot: PX4 1.11.0 stable

**Comment by DonLakeFlyer** [comment]
QGC daily builds use the new numbered parameter set and should work fine with the newest PX4 firmwares. QGC stable builds do not and continue to use only the single battery unnumbered battery params. Either build should work fine if you are using only a single battery. Only daily builds support multiple batteries.

The firmware is responsible for mirroring the un-numbered versions of parameters to the new numbered versions. QGC is not responsible for that. If it isn't working then it sounds like there is a firmware bug. Firmware is responsible for back compat on these param name changes not QGC.

I'm closing this until there is additional detail that QGC is doing something wrong. If you have that information provide exacts steps to reproduce include the exact QGC build you are using.
