### ISSUE TITLE
Failed to build the QCD after cloning from GitHub

### ISSUE THREAD

**Issue by A-AEM** [mavlink/qgroundcontrol#9109]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
What happened as detailed as possible:
I have tried to run the QCD project, so I followed the following steps:
1. Cloned the repository from GitHub using GitHub GUI for windows.
2. I opened the project (.pro) file using Qt version 5.12.9
3. the project opened correctly and the folders hierarchy appeared correctly in the left pane in Qt creator.
4. I have tried to build the project using MSVC 32 bit, but an error appeared telling me that "the project will only be built using MSVC 64 bit".
5. I have turned the compiler to MSVC2017 64bit.
6. I have checked that the kit is correctly configured and checked that the compiler has a valid CDB, and all that was "ok":

![compilers](https://user-images.githubusercontent.com/42469239/95641715-18af7b80-0aa4-11eb-8a6f-edb6d502f140.PNG)

7. I have selected the x64 CDB debugger of the windows kit 10.
8. I tried to build the project and it gave me the following error :

![erroe in qt](https://user-images.githubusercontent.com/42469239/95640550-87d5a180-0a9d-11eb-9a88-165bc4e0a976.PNG)
9. I have commented the [[faultthroug]] throughout the code and try to build again, it was built with no errors.
10. I tired to run the project, but it gave me the following error:

![error when Run qt 5 12 9 ](https://user-images.githubusercontent.com/42469239/95641184-2c0d1780-0aa1-11eb-9fec-cf5adfc7eb6b.PNG)

11. I have changed the compilers, used MSVC 2015 64 bit , it gave me error.
12. I have changed the version of Qt, so I installed Qt 5.14.2, and try to build the project, it gave me no warnings.

13. I tried to run the project using Qt 5.14.2 using MSVC2017 64bit, it gave me the following error:

![error when Run qt 5 14 2 ](https://user-images.githubusercontent.com/42469239/95641380-367be100-0aa2-11eb-91c9-fbddfc7c087d.PNG)
```
01:40:03: Starting F:\work\Github\build-qgroundcontrol-Desktop_Qt_5_14_2_MSVC2017_64bit-Debug\staging\QGroundControl.exe ...
QML debugging is enabled. Only use this in a safe environment.
01:40:12: The program has unexpectedly finished.
01:40:12: The process was ended forcefully.
01:40:12: F:\work\Github\build-qgroundcontrol-Desktop_Qt_5_14_2_MSVC2017_64bit-Debug\staging\QGroundControl.exe crashed.
```
## Current Behavior
When I tried to run the project in debug mode to know where is the problem, I put a break point at the beginning of the Main() function but it did not stopped at it, but instead it stopped art the shown position:

![error when build qt 5 14 2 ](https://user-images.githubusercontent.com/42469239/95641546-4d6f0300-0aa3-11eb-8297-60beac391d01.PNG)

So I do not know what to do right now, I have spent a lot of time trying to adjust the kits, compilers, debugger, changing the Qt versions and even setting up a new windows 10 OS version and all that was useless. Any help is very appreciated. Thanks in advance.

## System Information
- Operating System: [windows10 64 bit]
- QGC Version: [v4.0.10]
- QGC build: [self-built from source]

**Comment by booo** [comment]
Please reopen if this is still a problem with newer versions of QGC.
