### ISSUE TITLE
iOS version not detecting PS4 controller

### ISSUE THREAD

**Issue by tadeuszk733** [mavlink/qgroundcontrol#9129]
## Expected Behavior
Detect PS4 controller as joystick

## Current Behavior
PS4 controller paired to iPhone, works in other apps, not detected in QGC

## Steps to Reproduce:
1. Pair with joystick
2. Open QGC
3. Controller not detected 

## System Information
When posting bug reports, include the following information
- Operating System: iOS 14.0.1
- QGC Version: v4.0.10
- QGC build: stable
- Flight Controller: raspberry Pi
- Autopilot (with version): Ardusub 4.1.0 dev

## Log Files and Screenshots
Logs say noting about controllers.
![image](https://user-images.githubusercontent.com/57900677/96620674-0b965600-1308-11eb-8ec7-8f4ca480f5f7.png)

**Comment by DonLakeFlyer** [comment]
iOS builds don't support joysticks.
