### ISSUE TITLE
Please reimplement support for sending MAV_CMD_DO_DIGICAM_CONTROL to interactively trigger "dumb" cameras

### ISSUE THREAD

**Issue by brad112358** [mavlink/qgroundcontrol#9131]
The 4.0 version of QGroundControl provides a way to send a MAV_CMD_DO_DIGICAM_CONTROL command to trigger a dumb camera from the flight map screen via MAVLink using the CameraPageWidget. But this functionality seems to have been lost as the current widget in master seems to support MAVLink cameras only.

The old code was in FlightMap/Widgets/CameraPageWidget.qml and Vehicle/Vehicle.cc.

It would be useful to have this basic interactive camera trigger capability back.  Since it won't be used by everyone, visibility could be configurable.  Perhaps, expand the TelemetryValuesBar to add a category for clickable simple commands such as this.  Or create an option to add it to the FlyView ToolStripAction List.  Or, perhaps add an option to force display of the PhotoVideoControl widget and merge it back with MAVLink cameras.

**Comment by DonLakeFlyer** [comment]
@brad112358 Daily builds have this support now. Can you give it a try?

https://github.com/mavlink/qgroundcontrol/pull/9216
