### ISSUE TITLE
Problems with Multi-Vehicle: disconnect from selected vehicle, selector disappears

### ISSUE THREAD

**Issue by Ranjanbehl** [mavlink/qgroundcontrol#9135]
## Expected Behavior
All the vehicles are connected to the same link, when one of the vehicles is disconnected, there are still other vehicles connected. The selector should be available to use.

## Current Behavior
Please describe what happens instead of the expected behavior.
When of the vehicles is disconnected the selector disappears, forcing me to restart the program to get access to the selector. 

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 20.04
- QGC Version: Version 4.0
- QGC build: stable
- Flight Controller: Pixhawk Mini
- Autopilot (with version): PX4 1.11.1

## Detailed Description
The vehicles are transmitting data packets through UDP. I also looked at issue #4392 and #3086 but they didn't really help.

**Comment by DonLakeFlyer** [comment]
Can you give this a try with tomorrows daily build to verify the fix?
