### ISSUE TITLE
Mission numbering on screen doesn't match jump numbering

### ISSUE THREAD

**Issue by dagar** [mavlink/qgroundcontrol#9137]
Likely due to the speed command hidden at the beginning of the mission?

**Comment by DonLakeFlyer** [comment]
I tested this in SITL:
* Create plan with a jump and ran it. It jumped to the right WP.
* Create plan with a flight speed change in mission start and a jump. Ran it. Jumped to the correct WP.

@dagar Do you have plan file where this shows it to be wrong?

**Comment by dagar** [comment]
It was reported by a user, I'll see if I can get more detail.

**Comment by DonLakeFlyer** [comment]
I"m going to close this until there is a repro case
