### ISSUE TITLE
Mission / Fence / Rally buttons missing text

### ISSUE THREAD

**Issue by tzuriel-spearuav** [mavlink/qgroundcontrol#9147]
## Expected Behavior
Tab buttons should have text shown on them

## Current Behavior
Seems like for all tab buttons text is missing, thus button height is short

## Steps to Reproduce:
1. Latest QGC nightly
2. Go into Plan view
3.Notice the right tab header, should have buttons "Mission", "Fence", "Rally"

## System Information
- QGC build: daily

## Analysis
Seems like a recent change in QGCTabButton.qml removed the text property set from contentItem (b87cc26a69c24a6a8d4a08cc7a70808fda18d6ed)

**Comment by DonLakeFlyer** [comment]
Thanks for the bug report
