### ISSUE TITLE
Does not show battery voltage on ardusub

### ISSUE THREAD

**Issue by maphstr** [mavlink/qgroundcontrol#9169]
## Expected Behavior
QGC should display battery voltage

## Current Behavior
QGC does not show battery voltage

## Steps to Reproduce:
1. Use QGC 4.0.11 on linux
2. Use with Ardusub vehichle
3. Battery voltage from SYS_STATUS message is not displayed
4.

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 20.04
- QGC Version: 4.0.11
- QGC build: Stable
- Flight Controller:Pixhawk 4
- Autopilot (with version): Ardusb 3.5.4

## Detailed Description
QGC 4.0.11 does not show battery voltage in HUD, even though mavlink message "SYS_STATUS" is there.

**Comment by DonLakeFlyer** [comment]
QGC no longer supports battery information from SYS_STATUS only from BATTERY_STATUS.
