### ISSUE TITLE
Issue running QGC missions

### ISSUE THREAD

**Issue by Agm2104** [mavlink/qgroundcontrol#9174]
I'm trying to flight a drone and get LIDAR data by using PX4 with Airsim as SITL. I try to launch a mission in QGC without the sensors enabled and I have no problem, but the moment I enable LIDAR I get 2 issues:

1. When I try to launch my 'default' mission after opening QGC, the drone seems to arm but never takes off and the mission ends.

2. When try to load/upload a different mission, I get the 'mission transfer failed' issue.

I have checked the loss rates (seems to be 0) and the messages on the console logging and I get the following:

![image](https://user-images.githubusercontent.com/74015104/99085142-233fc200-25c8-11eb-9dad-a644992f68c6.png)

Any idea of what the problem could be?
Here are screenshots of the settings.json file, which seems to be the problem, but I don't see how those parameters affect QGC

Works::
![image](https://user-images.githubusercontent.com/74015104/99085742-dc9e9780-25c8-11eb-912a-857818fce723.png)

Doesn't work:
![image](https://user-images.githubusercontent.com/74015104/99085596-acef8f80-25c8-11eb-99ed-7ac958e0b4c7.png)

Any input would be very welcome :)
Thanks in advance!

**Comment by DonLakeFlyer** [comment]
All I'm seeing are firmware problems which QGC has no control over. You'll need to talk with the AirSim folks. The console log information is for a download failure not an upload failure. It shows the vehicle not responding to requests for geofence and rally points.
