### ISSUE TITLE
Need Camera Gimbal  Setup UI like mission planner

### ISSUE THREAD

**Issue by mrnams** [mavlink/qgroundcontrol#9176]
Tell us a bit about the feature:
- What problem does it solve?
**User can configure camera gimbal, right now I could not find any way to configure gimbal.**

- What does it do?
It will setup camera gimbal.

- What flight stacks must it work with? (All, PX4, ArduPilot)
PX4 (ArduPilot has it already)

- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
Multirotor

- Are there other systems that have this feature?
Yes, MissionPlanner

- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
MAVLink commands

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)

**Please make Camera Gimbal configuration UI page like missionplanner**

**Comment by DonLakeFlyer** [comment]
There is no such thing supported by PX4 Firmware. If there is point me to it in the firmware parameter set or user doc.
