### ISSUE TITLE
Bring back dumb camera trigger support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#9185]
With the changes to the new camera widget the ability to trigger a dumb camera using `MAV_CMD_DO_DIGICAM_CONTROL` was lost. Need to figure out how to get that ability back. It's a little tricky from a user model standpoint since video streaming has camera trigger to capture a frame from the video feed as well even for camera which are not using the new mavlink camera protocol.

Related:   https://discuss.ardupilot.org/t/qgc-android-daily-how-to-hide-the-huge-cam-rec-control-widget/63813

**Comment by moreba1** [comment]
Do you can also add a button for start/stop camera triggering?
 it can be used during mission and for tests on the ground.

**Comment by DonLakeFlyer** [comment]
> Do you can also add a button for start/stop camera triggering?
> it can be used during mission and for tests on the ground.

I'd rather keep it simple. If you want something fancy you can fly a mission
