### ISSUE TITLE
Radio Calibration Usability issues

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#920]
- The step where you are asked to move the Pitch back to center is not really needed
- Completion of an automatic step can be non-obvious. Need better indicator.
- Possibly highlight stick name and direction in instructions to help.

**Comment by kd0aij** [comment]
I just ran through RC cal using airframe type DJI-F450 quad with my custom quad.
Although the RC_MAP_ROLL and YAW parameters are set correctly (to 4 and 1, respectively)
the radio calibration display shows roll and yaw sticks as swapped.

**Comment by DonLakeFlyer** [comment]
I assume that you mean the visuals are not correctly connected to the right channels. You can save me a parameter set to a file and email it to me at: don@thegagnes.com. Also what version of QGC are you running.

**Comment by kd0aij** [comment]
Hi Don. Running latest 2.3.0 dev build.
And yes, it was the slider display on the left side of the Radio cal display which was incorrect.
But when I returned to it after calibrating sensors and saving parameters to a file, the slider display was correct.

**Comment by DonLakeFlyer** [comment]
Thanks. That should help tracking it down. Don't need param file.

**Comment by DonLakeFlyer** [comment]
Just checking: My repro is that while you are calibrating the sticks the indicator are correct. After you are done and write calibration, but stay on screen, it is incorrect. If you move off radio cal and come back it is correct again.

**Comment by kd0aij** [comment]
That sounds like the behavior I observed


On Sun, Mar 1, 2015 at 11:57 AM, Don Gagne <notifications@github.com> wrote:

> Just checking: My repro is that while you are calibrating the sticks the
> indicator are correct. After you are done and write calibration, but stay
> on screen, it is incorrect. If you move off radio cal and come back it is
> correct again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/issues/920#issuecomment-76624024>
> .
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by DonLakeFlyer** [comment]
Moved bug to Issue #1297

**Comment by squilter** [comment]
The radio calibration is still very counter-intuitive, as compared to other calibrations. It never beeped when a step was complete, and it was not obvious when the text changed to provide new instructions. Sometimes it wanted me to click next, sometimes I was just supposed to wait. It was not always obvious what to do.

**Comment by LorenzMeier** [comment]
Closing as stale.
