### ISSUE TITLE
'mavlink_types.h' file not found

### ISSUE THREAD

**Issue by devd77** [mavlink/qgroundcontrol#9208]
--I have cloned this repository on my system by "git clone https://github.com/mavlink/qgroundcontrol.git --recursive"
--and then run command: git submodule update
--then it on QT Creator
--Build for iOS Simulator Debug
--Then i have found "mavlink_types.h' file not found" this issue.

It was working before, but in new clone i have found this issue
Anyone can tell me the solution
Thanks in Advance :)

please see the attachment image
![Screenshot 2020-11-24 at 3 47 16 PM](https://user-images.githubusercontent.com/19357696/100081064-98cf4c00-2e6c-11eb-9ae2-08eefd6e93cb.png)

**Comment by patrickelectric** [comment]
Try `git submodule update --init --recursive`

**Comment by devd77** [comment]
i have tried, not working...same problem

**Comment by DonLakeFlyer** [comment]
As stated in the issue template. This is not the place for build problems.
