### ISSUE TITLE
_sendGCSHeartbeat() race condition crash

### ISSUE THREAD

**Issue by dakejahl** [mavlink/qgroundcontrol#9210]
I believe there is a race condition between 
https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/MultiVehicleManager.cc#L49
and
https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/MultiVehicleManager.cc#L133
Which causes random crashes.

I will look into it more in a few days.

**Comment by DonLakeFlyer** [comment]
Google Play upload is working again so we should be able to get crash data from the store soon.

**Comment by DonLakeFlyer** [comment]
So far I'm no longer seeing this crash on Google Play. But it needs a bit more time I think to make sure.

**Comment by DonLakeFlyer** [comment]
I believe we are good here now:
![Screen Shot 2020-12-16 at 12 42 09 PM](https://user-images.githubusercontent.com/5876851/102404187-2ef22000-3f9c-11eb-8b05-75fbd36f79dd.png)
