### ISSUE TITLE
Cube Orange PX4 switch fails with "Unable to find specified firmware for board type"

### ISSUE THREAD

**Issue by dell640** [mavlink/qgroundcontrol#9215]
[As per discussion at px4.io](https://discuss.px4.io/t/cube-orange-px4-stack-issue/19754/7) with @DonLakeFlyer I'm rising this as issue:

I would like to upload PX4 stack to my Cube Orange, unfortunately without success.

When I upgrade my Cube to PX4 via MissionPlanner, upload is successful, however Cube hangs in bootloader and stack is never loaded and running.

When I try to upgrade to PX4 from QGC:
![image](https://user-images.githubusercontent.com/11704829/100325072-676b9300-2fc8-11eb-937b-d4430d9816df.png)
I’m getting this error:
![image](https://user-images.githubusercontent.com/11704829/100325096-70f4fb00-2fc8-11eb-8b45-704969d851a4.png)

I have two Cube Orange units here, both behaves the same.

Testing computer running W10.

Tried multiple QGC versions from 3.5.6 up to the latest and also daily build. All have the same “error”.

Also I tried to uninstall USB drivers via Device Manager, that does not help. Then reinstalled UAV drivers, but problem persist.
Tried another computer (also W10) with same results.

**Comment by DonLakeFlyer** [comment]
Turn on console logging for FirmwareUpgradeLog as described here and then attach the log so I can look at it.

**Comment by DonLakeFlyer** [comment]
Also wait a minute these screenshots are not from a Daily build. They are from Stable. You need to use a daily build to get Cube Orange fixes.

**Comment by DonLakeFlyer** [comment]
> Turn on console logging for FirmwareUpgradeLog as described here and then attach the log so I can look at it.

Never mind I can repro it myself.

**Comment by DonLakeFlyer** [comment]
This is because of the ArduPilot bootloader on the board returning a different board id. Trying to figure out how to make it work...

**Comment by dell640** [comment]
> 
> 
> This is because of the ArduPilot bootloader on the board returning a different board id. Trying to figure out how to make it work...

Thanks for checking that. As stated at first post, when proper PX4 firmware (v1.11.2 - cubepilot_cubeorange_default.px4) is uploaded via MissionPlanner (where is goes smoothly) Cube hangs in bootloader and PX4 stack is not running properly. So, maybe it is deeper incompatibility issue.
Looking forward to your discoveries.

**Comment by DonLakeFlyer** [comment]
> As stated at first post, when proper PX4 firmware (v1.11.2 - cubepilot_cubeorange_default.px4) is uploaded via MissionPlanner (where is goes smoothly) Cube hangs in bootloader and PX4 stack is not running properly. So, maybe it is deeper incompatibility issue.

You should report that as a firmware issue. Not here.

**Comment by Dule-sat** [comment]
[qgc issue cubeorange.txt](https://github.com/mavlink/qgroundcontrol/files/5611283/qgc.issue.cubeorange.txt)
Hi, I am uploading console log from QGC regarding the issue with Cube Orange. Like many, I have an issue when trying to flash Px4 via QGC.

Please help
Thanks

**Comment by sibujacob** [comment]
As far as I know Pixhawke Orange CUBE has manufacturing defects especially the ones from PROFICNC.                                            They are not quality testing the product  for any defects .

**Comment by FlyingPineapple** [comment]
> As far as I know Pixhawke Orange CUBE has manufacturing defects especially the ones from PROFICNC. They are not quality testing the product for any defects . There should be a program to test the product for all its port and POST functions before dispatch.

Do you have more information on this defects? Or where I can find more about it? 

I am also unable to get PX4 on a Cube Orange :( I tried both stable and daily builds and get the error message.

**Comment by sibujacob** [comment]
> > As far as I know Pixhawke Orange CUBE has manufacturing defects especially the ones from PROFICNC. They are not quality testing the product for any defects . There should be a program to test the product for all its port and POST functions before dispatch.
> 
> Do you have more information on this defects? Or where I can find more about it?
> 
> I am also unable to get PX4 on a Cube Orange :( I tried both stable and daily builds and get the error message.

I am waiting for my Pixhawke Orange with ADS-B receiver to arrive in India.

**Comment by DonLakeFlyer** [comment]
Fixed

**Comment by Dule-sat** [comment]
> Fixed

Can you please be more specific? Is it fixed with new daily build or master?

**Comment by sibujacob** [comment]
> Fixed

what was the issue ...

**Comment by Dule-sat** [comment]
It works with new daily release of QGC! All good now!

**Comment by sibujacob** [comment]
Please share the link here

**Comment by DonLakeFlyer** [comment]
A simple internet search on "qgroundcontrol daily build" will get you what you want

**Comment by arunabha42** [comment]
> I am having the same issue with Cube orange for PX4 firmware load. Qgroundcontrol Daily Build does not solve the issue. I even tried QGC daily build in windows and Linux both system. uploaded the firmware using `make` command but no luck. Seems like cube orange is stuck in the bootloader loop. Only works with Arducopter firmware.

Can confirm, I'm facing the same issue. I'm on Windows 10.

Initially I was getting the "Unable to find specified firmware for board type", but after a few tries of jumping around installing ArduPilot and trying out QGC & QGC daily builds it reached the firmware installation stage.

In my case as well the orange light on the Cube Orange is always solid when the PX4 stack is installed. This is not the case when the ArduPilot stack is installed, the light goes off once it's booted up.

Looks like the firmware is loading onto the board but is not booting up. However, this is the case only with the PX4 stack, not when ArduPilot is being installed.

Any help appreciated I'm adding more details in #9843, thanks!

**Comment by cph-devnet** [comment]
I was able to get my Cube Orange to flash with PX4, I just had to uninstall all windows drivers first.
