### ISSUE TITLE
APM Sub: enabling motor test induces hundreds of mavlink command error popups

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#9234]
After the 'enable motor test' switch is clicked on the motor test page, hundreds of popups appear with a message like
"unable to send mavlink command: previous command not acked"

The messages come so rapidly my desktop froze and I was unable to make a screenshot.

**Comment by jaxxzer** [comment]
This should be fixed for 4.1

**Comment by DonLakeFlyer** [comment]
Broken by the recent changes to not queue mavlink commands. The previous command still hasn't finished before the next one is sent.

**Comment by DonLakeFlyer** [comment]
@Williangalvani This is fixed right?

**Comment by Williangalvani** [comment]
Yes!
