### ISSUE TITLE
Segfault on vehicle reboot on master

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgroundcontrol#9260]
Happened to me once during a vehicle reboot connected via USB. I didn't try much to reproduce.
```
Temp log "/tmp/FlightData893795.mavlink"
LinkManager::sharedLinkInterfaceForLink returning nullptr
./staging/qgroundcontrol-start.sh: line 10: 50355 Segmentation fault      (core dumped) "${HERE}/QGroundControl" "$@"
```

**Comment by DonLakeFlyer** [comment]
Any more details? You rebooted how? From Parameter Editor? And then did nothing at all after and then it crashed?

**Comment by bkueng** [comment]
> From Parameter Editor?

Yes, and it crashed directly after, no other interaction.

**Comment by DonLakeFlyer** [comment]
What kind of board? Doubt it matters but I tried to repro and it worked fine of course.

**Comment by bkueng** [comment]
A Pixhawk 4
