### ISSUE TITLE
Crash referencing stale _activeVehicle in Joystick code

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#9263]
Crash is here: https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.cc#L3804 caused by referencing a stale _activeVehicle in the Joystick code.

It hit this using PX4 SITL:
* Start sitl with an iris
* Start QGC with joystick enabled
* Stop SITL
* QGC shows comm lost
* Click Disconnect
* Boom

It's some sort of race condition. I can't get it to reproduce now. But from looking at the joystick code _activeVehicle is set in Joystick::startPolling. But when a vehicle is being destructed I don't see how that _activeVehicle gets cleared. I'm not familiar with this code at all but something seems wrong here with respect to there not being a stopPolling in the Vehicle code.

**Comment by DonLakeFlyer** [comment]
@jaxxzer Can someone from your team look at this. Likely faster since I'm not familiar with the joystick code any more.

**Comment by jaxxzer** [comment]
@DonLakeFlyer  we are trying to replicate it here.

**Comment by DonLakeFlyer** [comment]
I can't make it happen again myself. Will likely need to be tracked down through code inspection. When looking through code myself something seemed fishy as I described above. But I don't know that code enough to say exactly what. Smells wrong through.
