### ISSUE TITLE
VTOL can not do vtol_land in landing pattern

### ISSUE THREAD

**Issue by moreba1** [mavlink/qgroundcontrol#9264]
In my SITL test with v1.11.1 px4 and standard VTOL airframe (weather wane enabled), VTOL can not do VTOL land in the landing pattern.

The reason of this issue is that param_4 of MAV_CMD_NAV_VTOL_LAND is 0 and should be Nan.

**Comment by DonLakeFlyer** [comment]
Did something change here on the firmware side I'm pretty sure that used to work? Without and altitude specified how do you land somewhere which is at a different alt than the home position?

**Comment by moreba1** [comment]
Param4 is for set Yaw not Alt.

**Comment by DonLakeFlyer** [comment]
Oops, yeah my bad.

**Comment by DonLakeFlyer** [comment]
@moreba1 A new daily should be out in an hour or so. Could you verify? I'm having problems with VTOL SITL for some reason I don't understand yet.

**Comment by moreba1** [comment]
yes, it is correct.
