### ISSUE TITLE
daily build: takeoff waypoint and transect line disconnected on Plan screen

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#9272]
today's daily:

![image](https://user-images.githubusercontent.com/12117027/103106777-fc7c9e80-45fd-11eb-852d-13e1d216036f.png)

saved mission:
[takeoff-disconnected.zip](https://github.com/mavlink/qgroundcontrol/files/5740552/takeoff-disconnected.zip)

**Comment by DonLakeFlyer** [comment]
Hmm of course loading this plan is working fine for me.

**Comment by Antiheavy** [comment]
> Hmm of course loading this plan is working fine for me.

try the following:

1) select the survey, drag some vertices around.
2) select the Takeoff waypoing, drag it around, observe it is disconnected
