### ISSUE TITLE
daily build: terrain intersect warning too sensitive for fixed wing takeoff

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#9273]
I suspect that the terrain intersect logic for the transect from Launch to Takeoff points needs some special handling to avoid terrain intersections being calculated very close to the Launch location.

Example:
this shows no terrain intersections:
![image](https://user-images.githubusercontent.com/12117027/103107359-0a80ee00-4603-11eb-8d6f-113eb49a64a4.png)

but moving takeoff slightly shows a terrain intersection (red line):
![image](https://user-images.githubusercontent.com/12117027/103107371-2e443400-4603-11eb-8fde-f4030f9cef51.png)

The actual terrain near the Launch location is relatively flat, but there is likely a tiny rise or step (less than 1 meter) in terrain elevation just to the north of the Launch.  If Launch is calculated to be exactly at whatever the terrain database says then there may easily be "false positive" terrain intersections very near to the Launch location.  I've run into this in the past when developing/testing other ground control station applications which is why I suspect something similar here.

Suggestions:   
- Ignore terrain intersections within a 10 meter radius "buffer" around the Launch location.  Document this somewhere.
- Or, assume "Launch" is 1 meter above terrain (seems more hacky)
- Or, some combinations of approaches

**Comment by DonLakeFlyer** [comment]
Hmm, yeah...

**Comment by DonLakeFlyer** [comment]
This was a bug in the collision detection code. You can still theoretically get a collision indication a the beginning on the takeoff segment on hilly terrain that may or may not be false. But with the current code I believe it should indicate an "iffy" situation to fly in as opposed to just being wrong. 

Will need some bake time to determine whether doing something special is still required as suggested above. If folks are seeing it giving misleading results we can update it then. For now I'd rather err to the side of caution in warning possibly incorrectly in extreme cases.
