### ISSUE TITLE
Tilting ,Field of View ,Bearing : of Maps

### ISSUE THREAD

**Issue by amulya30** [mavlink/qgroundcontrol#9294]
<h1>Help:</h1>
I want to change the field of view , and tilt the Flight Map but I am not able to even after adding the gestures controls in qml . Can anyone guide how to do it or enable it from the QGroundControl plugin ?

**Comment by DonLakeFlyer** [comment]
Issue are for bugs or feature requests. Use the forums or QGC slack channel for questions like this.
