### ISSUE TITLE
Facing Issues With FTP

### ISSUE THREAD

**Issue by kshitizgoyal5** [mavlink/qgroundcontrol#9306]
hey i am trying to ftp a file from my drone to gcs using FTPManager class in QGC-master. I am facing the following problem.

![image](https://user-images.githubusercontent.com/43859091/103763279-994c2c80-503f-11eb-91c4-c454cec2d71e.png)

In the logs it can be seen that, we are getting errno5 which indicates all available sessions are already in use. Can anyone Please tell the cause of this error. Thanks in advance.

![image](https://user-images.githubusercontent.com/43859091/103763700-3dce6e80-5040-11eb-84ad-c9bc543b1cff.png)

**Comment by DonLakeFlyer** [comment]
In looking at the FTPManager code I believe there is a bug where sessions are not being reset if the FTP download fails or errors out. The sessions are only reset if download succeeds. That could cause sessions to leak on the vehicle side.

**Comment by kshitizgoyal5** [comment]
Thanks for your reply @DonLakeFlyer , I have a doubt that if the session is already assigned for reading so why it is giving errno5 that from what i believe is NoSessionsAvailable. I printed the session id that i am receiving as in AckNak and it is printing 0. In the docs it shows the it has range from 0-255. Why is it giving this particular error cause I am Trying to read the file once.

**Comment by DonLakeFlyer** [comment]
Ah sorry. I thought you were getting the Nak from the Open File. It's in the middle of burst sequence! That's just completely wrong on the firmware side. That error makes no sense in the middle of a burst sequence. You should file a bug against ArduPilot. 

> In looking at the FTPManager code I believe there is a bug where sessions are not being reset if the FTP download fails or errors out. The sessions are only reset if download succeeds. That could cause sessions to leak on the vehicle side.

I will create a separate issues for this which is a real QGC problem. But just not what you are hitting.

**Comment by LorenzMeier** [comment]
Closing as stale.
