### ISSUE TITLE
External battery source (BAT1_SOURCE)

### ISSUE THREAD

**Issue by Igor-Misic** [mavlink/qgroundcontrol#9312]
There is an option in the **PX4** configuration **BAT1_SOURCE** that can be set to **External**. 

Documentation for this config (https://dev.px4.io/master/en/advanced/parameter_reference.html)

>  If the value is set to 'External' then the system expects to receive **mavlink battery status messages**. 

Currently, if this option is selected this error appears:
![image](https://user-images.githubusercontent.com/10188706/103945279-405ec000-5135-11eb-899a-587b11c0698a.png)

Looking for a proper solution to use an external battery source config with QGC.

**Comment by DonLakeFlyer** [comment]
Questions for PX4 firmware folks:
* Should `BAT#_SOURCE` parameter setup be added to the Power component ui?
* If so, what does that mean with respect to it being set to "External" or "ESCs"?
* Does it mean for those the only thing shown is `BAT#_SOURCE` combo and then no other UI is needed?

**Comment by DonLakeFlyer** [comment]
> * Should `BAT#_SOURCE` parameter setup be added to the Power component ui?

It's already there. It was added to QGC mainly to be able to disable batteries.

**Comment by DonLakeFlyer** [comment]
If think if external it means most of these settings are not there.

**Comment by Igor-Misic** [comment]
@DonLakeFlyer I wanted to close this issue because when I run the latest master PX4,  this error doesn't appear, but now I have another one:
QGC v4.1.1
![image](https://user-images.githubusercontent.com/10188706/106391302-ee841f80-63ec-11eb-8f45-7d8a2804264e.png)

**Comment by DonLakeFlyer** [comment]
> There is an option in the **PX4** configuration **BAT1_SOURCE** that can be set to **External**.

This problem hasn't been fixed yet and still exists in QGC. If you still have that setup you are still going to see problems. They can be ignored through since there is no additional setup needed for External.

**Comment by Igor-Misic** [comment]
So this is a known issue. 
Let me know if there is any PR so we can close this. Thanks!
