### ISSUE TITLE
updateqrc.py code python version

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgroundcontrol#9314]
fallowing line throws error in python 3, it is an easy fix, and error mesage itself show how to fix it and there are online converters avaliable.
Should we change it, or should we mention it anywhere ?
Error :
```
 File "updateqrc.py", line 28
    print 'Excluded:', line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Excluded:', line)?
```
line:
https://github.com/mavlink/qgroundcontrol/blob/44be3032b1f49ab0ea2dc540b522746eed7bf1b2/custom-example/updateqrc.py#L28
fix : 
`  print('Excluded:', line)`

**Comment by DonLakeFlyer** [comment]
It should be changed. Can you submit a pull? I just fixed the same exact thing in the localization python scripts.

**Comment by DonLakeFlyer** [comment]
I was already in the custom code for other reason so I'm fixing this myself.

**Comment by mnumanuyar** [comment]
I just saw your response, thank you for fixing it
