### ISSUE TITLE
connection loss when using qgroundcontrol

### ISSUE THREAD

**Issue by rong0004** [mavlink/qgroundcontrol#933]
I have the pixhawk for qgroundcontrol, and when I try to calibrate the sensors, it always shows' connection loss', and then the program(qgroundcontrol) is not responding any more. What problems can it be?
This pixhawk is good when using mission planner so I think it is not the problem of pixhawk itself
Thanks for any reply.

**Comment by xn365** [comment]
I have encountered the same problem.

**Comment by quentin1002** [comment]
Hello, 

I am facing the same problem: Firmware is upgraded via QGC but then the connection is lost and here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/15336020/12576836/7765dc9e-c451-11e5-983c-c44fd67a1f11.png)
The big blue light is switched on during a couple of seconds between the end of the firmware upgrading and the connection lost message. 

I am running QGC v2.9.1 on Ubuntu 14.02. My board is a pixhawk px4 by 3DR. I already tried using the different USB ports of my computer and using a different cable. Same error is coming...

How can I know whether it is a hardware or a software problem? 

Thanks in advance for your help

**Comment by LorenzMeier** [comment]
You have to click disconnect to make QGC reconnect.

**Comment by LorenzMeier** [comment]
I filed a new issue for this: https://github.com/mavlink/qgroundcontrol/issues/2695
