### ISSUE TITLE
Stable v4.1 release problems

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#9334]
* ~~Windows: Seems to be installing a daily build or possibly tagged builds are broken~~
* OSX: No app name in title bar. About shows correct versioning
* ~~Google Play upload broken~~

**Comment by AlexKlimaj** [comment]
I am seeing this same issue on windows.

**Comment by AlexKlimaj** [comment]
Also, when I connect to a com link, disconnect is not working.

**Comment by DonLakeFlyer** [comment]
Android 4.1 is available on play store now

**Comment by Radanz** [comment]
Same issue here it seems: Windows X64 v4.1 downloaded from website (Amazon bucket) and from github releases
Title bar shows "Daily"
Connects to flight controller but wont allow setup. Shows Telemetry ok and I can flash the firmware, just nothing fills in the setup screen.
Github release said it was only an hour old so must be a fresh update? or the daily is pushing to the stable for some reason?
Rolling back to previous version for now.

**Comment by DonLakeFlyer** [comment]
@Radanz Can you try the same thing with a Daily build and if still broken create a new issue with full details.

**Comment by DonLakeFlyer** [comment]
Windows build now correctly marked as Stable
