### ISSUE TITLE
Support for UAV-Based 4G and 5G measurements

### ISSUE THREAD

**Issue by Valle125** [mavlink/qgroundcontrol#9375]
Hello!

In the past time I have been working on a new mission item to aid UAV-bades mobile coverage measurements of 4G and 5G networks. Coverage measurements have the aim to produce maps of KPI's (Key Performance Indicators). An important KPI is for example the radio signal strength (RSRP) which influences data throughput a lot. Coverage measurements are especially important for mobile network providers to guarantee reliable networks. 
The mission item i created automatizes the measurement process. It is able to create a flight plan of optimal length according to a defined scenario. Additionally it updates the flight plan while the measurement progress increases. The mission item is design in a generic fashion, that means that it can be used for other types of measurements as well. In general it can be helpful for any application which benefits from a length optimized flight plan. An example of the mission item can be seen here
![Fig3_crop](https://user-images.githubusercontent.com/36841542/106001242-ffacf380-60af-11eb-8c28-605aafc66198.png)

In the case I have sparked your interest, have a look a the the introductory video and the Linux AppImage here: https://squid.nt.tuwien.ac.at/gitlab/platzgummer/uav_measurements_intro

If you like my mission item I would be delighted, if it was incorporated in to QGroundControl.

Best,
Valentin

**Comment by DonLakeFlyer** [comment]
Without more detail as to what this path generation algorithm is really doing and why it seems like a very special use case that is not broad enough to include for everyone. Hence closing for now unless there is more detail which clarifies as being interesting to a broader usage.
