### ISSUE TITLE
Menu appears over hamburger button in 4.1.1

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#9396]
## Expected Behavior
I want to click the hamburger button to have the side menu appear and disappear.

## Current Behavior
The menu appears on top of the button.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Press hamburger menu

## System Information
When posting bug reports, include the following information
- Operating System: Arch LInux
- QGC Version: 4.1.1
- Flight Controller: SITL
- Autopilot (with version): PX4 master

## Log Files and Screenshots

![Selection_002](https://user-images.githubusercontent.com/1419688/106923191-1dacd080-670e-11eb-8ce8-fc4ece913c87.png)

**Comment by Antiheavy** [comment]
I suspect if the list of menu items was shifted down one space it would have the effect you are looking for, although without the "hamburger" icon.
![image](https://user-images.githubusercontent.com/12117027/107152542-1f54df00-692e-11eb-88a2-b1ab94a6e3b6.png)

**Comment by julianoes** [comment]
> Are you looking for a "toggle" type function on that button?

Yes, and that's what I remember what it always was.
