### ISSUE TITLE
disconnect and connect buttons does not updated correctly

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgroundcontrol#9411]
## Expected Behavior
There is two issues, but I think they are related.
1. After succesfull connection when disconnect button clicked, if disconnect is sucsesfull, disconnect button should be disabled and connect button should be enabled
2. if connection failed, connect and disconnect button states should not changed
## Current Behavior
1. after succesfull connection when clicked disconnect, Disconnect button remains enabled. If users clicks to a different connection or goes to a different screen, and then comes back, button status is fixed
2. if connection refused, connect button becomes disabled, and disconnect button enabled. Clicking disconnect does nothing.

## Steps to Reproduce: 
1. open gcs,
2. go to appsettings -> CommLinks, chose a connection settings that would not refuse connection.
3. click disconnect 
4. Observe that how much you wait disconnect is not became disabled and connect does not become enabled.

1. open gcs
2. go to appsettings -> CommLinks, chose a connection settings that would refuse connection
3. observe that altough warning pop up appears, button states are changed (connect button becames disabled, disconnect button becomes enabled)
4.click disconnect
5. observe that nothing happens

## System Information
- Operating System: kubuntu 18.04 
- QGC Version: 4.1
- QGC build: daily. sha: 9589cc5f002d55099954428603413a6a00df20fa
- Flight Controller: ardupilot sitl
- Autopilot (with version): ardupilot sha: b113fe15ab30946b1b5105d1f8bd6df9d35696e6 

## Detailed Description
For first problem: A simple work around is simply choosing another connection or going to anoher screen and coming back.

For the second problem: As far as I am aware no workaround exist and only solution is quiting and re opening qgcs.

I am connecting to an sitl vehicle on TCP 127.0.0.1:5760 did not try other connection types.

## Log Files and Screenshots
first problem:
[DisconnectDoesNotUpdate.txt](https://github.com/mavlink/qgroundcontrol/files/5932835/DisconnectDoesNotUpdate.txt)
2nd problem:
[ConnectButtonChangesOnFail.txt](https://github.com/mavlink/qgroundcontrol/files/5932838/ConnectButtonChangesOnFail.txt)

**Comment by kschoelpple** [comment]
Hi,
also noticed same and in fact also applies to Edit button which does appear to not respond when clicked after a connection as been initiated. As the Disconnect button also doesn't respond as expected a change to connection can not be made. Only solution is to re-start Qgroundcontrol.
System in use:
Kubuntu 20.04
Plasma 5.18.5
Kernel 5.4.0-80
