### ISSUE TITLE
Unable to get a bigger attitude and heading indicator

### ISSUE THREAD

**Issue by dorovl** [mavlink/qgroundcontrol#9418]
Prior to the version v4.1.0, to get a bigger attitude and heading indicator, just check the "Use Vertical Instrument Panel". Now if "Use Vertical Instrument Panel" is checked, the attitude and heading indicator disappears... :cry:

Note: the attitude and heading indicator is not really a "vertical instrument" like a vertical speed or glide path indicator. Therefore I suggest to rename this indicator to "attitude and heading indicator".

**Comment by Antiheavy** [comment]
I just noticed this today as well while testing the newest stable release.  I know that some people really like the larger display of the Vertical Instrument Panel:
![image](https://user-images.githubusercontent.com/12117027/107151445-427c9000-6928-11eb-84d8-054b18d36e01.png)
![image](https://user-images.githubusercontent.com/12117027/107151466-5627f680-6928-11eb-8e54-4d1e199d3573.png)

**Comment by Antiheavy** [comment]
> Note: the attitude and heading indicator is not really a "vertical instrument" like a vertical speed or glide path indicator. Therefore I suggest to rename this indicator to "attitude and heading indicator".

or "Larger Instrument Panel"

**Comment by dorovl** [comment]
> or "Larger Instrument Panel"

Yes, just perfect!:+1:

**Comment by DonLakeFlyer** [comment]
Dup of #9405
