### ISSUE TITLE
Stable_V4.1: "Apply Preset" fails with error, missing keys

### ISSUE THREAD

**Issue by dakejahl** [mavlink/qgroundcontrol#9423]
When trying to "Apply Preset", I get an error about missing keys in the JSON object. I looked at the .json file for the preset, and it indeed has these keys it says are missing. This happens even after creating a fresh new preset from a Basic Survey as seen in the image below. I just created a preset called "test", saved it as a new preset, and then tried to load it. 

![image](https://user-images.githubusercontent.com/37091262/107283785-55b35c80-6a09-11eb-9ebe-32047642b3fd.png)

**Comment by dakejahl** [comment]
@patrickelectric 

Looks like this change broke it
https://github.com/mavlink/qgroundcontrol/commit/d111e78497c1f65d3f0f18c6250d14b852c83651

**Comment by patrickelectric** [comment]
Fix for reporting this, should be fixed on #9447
