### ISSUE TITLE
Sensor Status not scrollable therefore force-arm button not reachable

### ISSUE THREAD

**Issue by 0815Creeper** [mavlink/qgroundcontrol#9428]
Android:
tested with regular playstore version and daily test build playstore version

## Expected Behavior
The sensor status list should be scrollable, so that the Force-Arm button at the bottem (I think there should be one according to https://github.com/mavlink/qgroundcontrol/pull/8993) becomes visible

## Current Behavior
Scrolling not possible: some sensor states not visible and force-arm button not visible.

## Steps to Reproduce:
1. open App on Android-Phone with regular screen size (1080x1920-423ppi in my case), connect to any drone with a few sensors...

## System Information
- Operating System: Android 8.1.0
- QGC Version: v4.1.1 64bit
- QGC build: playstore version
- Flight Controller: Matek H743wing
- Autopilot (with version): Ardupilot v4.0.8
 
## Detailed Description
I do not know what would remain to be clarifyed.

## Log Files and Screenshots
![photo5269311495483797981](https://user-images.githubusercontent.com/43469235/107516210-59cbaf80-6bac-11eb-855e-03b307a8827e.jpg)

**Comment by DonLakeFlyer** [comment]
Yup

**Comment by 0815Creeper** [comment]
didnt make it to production, right?

**Comment by DonLakeFlyer** [comment]
It is bu Android store is not updating. APKs are available from the web site
