### ISSUE TITLE
When planning a mission, the "big ass alt mode ui on each item" doesn't work on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by rtrevellyan** [mavlink/qgroundcontrol#9445]
## Expected Behavior
According to #8839 regarding altitude modes in the waypoint editor, 'If you pick "Mixed Modes" [for the mission] you are back to the big ass alt mode ui on each item:'

## Current Behavior
On macOS Catalina 10.5.7/QGC 4.1.1, when I pick Mixed Modes in the Mission Start item, I'm unable to drop down the "big ass alt mode ui on each item" in order to pick the mode for each waypoint.

## Steps to Reproduce:
1. Create a new mission.
2. Choose Mixed Modes in the Mission Start item.
3. Add a Waypoint to the mission.
4. Attempt to drop down the "big ass alt mode ui".
5. Notice that there is no dropdown.

## System Information
- macOS Catalina 10.5.7
- QGC 4.1.1 stable

**Comment by DonLakeFlyer** [comment]
Oops sorry, just realized someone else had already entered this: #9410
