### ISSUE TITLE
Terrain collision detection too sensitive near the Landing Area and Launch (fixed wing patterns)

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#9466]
The terrain intersection calculation is too sensitive around the Land point (and Launch point too actually) when using typical fixed wing landing and takeoff patterns.  The landing pattern and takeoff line often show as red when they shouldn't.  

Terrain models such as the one QGC is using have all sorts of weird effects at polygon (or post) edges and they use who-knows-what styles of smoothing functions - they just aren't designed for ultra close-up inspection.  The accuracy and fidelity of the terrain model is fine for mission planning at altitude, but isn't appropriate to be trying to determine a terrain intersection such as a small bump that may or may-not actually be on the ground right near where the pilot is standing anyway.

**Suggested improvement:**  ignore terrain intersections within X meters horizontal distance of the Landing and Launch locations.  Might need to play around to determine X, but in past experience I've seen 3-10 meters used.

![terrain intersect calc too sensitive](https://user-images.githubusercontent.com/12117027/108599280-e49f6d80-7355-11eb-8f33-3e04fe9b126a.gif)

**Comment by DonLakeFlyer** [comment]
Yeah, I was concerned my last change to this wouldn't really cut it. So no surprise here.

**Comment by DonLakeFlyer** [comment]
This specific problem should be fixed now. But leaving this open since it's possibly related to #9495 as well.

**Comment by DonLakeFlyer** [comment]
As far as I can tell it's fixed by: https://github.com/mavlink/qgroundcontrol/pull/9547. There will be a new master today sometime you can test with. The Stable RC pointed to here: https://github.com/mavlink/qgroundcontrol/issues/9495 should have the fix in it as well.

**Comment by DonLakeFlyer** [comment]
Should be fixed now

**Comment by Antiheavy** [comment]
yep, looks like it based on latest daily build testing.
