### ISSUE TITLE
iOS don´t forget to update old 3.2 to 3.4.3 within the next iOS update 4.0.x to 4.1.x 

### ISSUE THREAD

**Issue by taileron** [mavlink/qgroundcontrol#9487]
QGC iOS: with Apples Configurator 2 it is now possible to save any IPA files available in the APP store locally and also upload them to any iOS device. It is still the case that only version 3.4.3 offers all the realtime features that are necessary for flight monitoring including low enough latency rtsp video feed.
Please do not forget to change the backwards compatibility version for old iOS from 3.2 to 3.4.3 in the next QGC iOS from 4.0.x to 4.1.x - I think this is extremely important !!!! 
To have a reasonable flightmonitoring/video solution available on iOS again, I also hope that the font display for previous QGC will be fixed with the next subrelease of iOS 14.x. 
Currently Apples App-Store offers QGC 4.0.10 and 3.2 for old devices which should be replaced by 3.4.3 which, in contrast to 3.2, is a version that is almost error-free.

**Comment by HTRamsey** [comment]
iOS
