### ISSUE TITLE
Support for new RTK make/model or more RTCM messages

### ISSUE THREAD

**Issue by bentcookie** [mavlink/qgroundcontrol#9506]
Hello,

I am looking to integrate a new RTK GNSS model that isn't M8P/F9P, Emlid, or Trimble based. 
For reference, [here](https://www.bynav.com/en/products/gnss-boards/c1.html) is the GNSS receiver I will be using as a base station, and [here](https://www.bynav.com/en/products/gnss-ins-integration/a1.html) is the INS/GNSS receiver I will be using on the rover.
The C1-8S supports the following: 

Constellation | Band
-- | --
GPS | L1CA/L1C,L2C, L2P
GLONASS | G1, G2
BDS | B1I, B2I 
BDS-3 | B1I/B1C, B2a/B2b
GALILEO | E1, E5b/E5a
QZSS | L1CA/L1C, L2C

And because of this, is by default configured to output RTCM3.x messages over UART which I would like to forward to my VTOL plane (running ardupilot) over the telemetry link: 
- rtcm1074
- rtcm1084
- rtcm1114
- rtcm1124
- rtcm1006
- rtcm1033 

I have tried poking around in this repo and in the PX4-GPSDrivers submodule for more information about how I might implement support or check what is needed to be done but no success. I found that the UBX drivers do not support any of those 6 RTCM messages.

I'm also not sure what I might need to do on the rover side for this to work well, if I manage to successfully integrate the base station into QGC then I presume the RTCM corrections will be stuffed into a GPS_RTCM_DATA MAVLink packet which is hardware agnostic(?) and therefore the reconstructed RTCM messages would simply be passed onto a GPS device connected to a GPS port. Worst case I'd be forwarding all telemetry MAVLink across to a companion computer to do parsing.

Please point me in the right direction, I think the community would welcome support for this cheap multi-constellation, multiband GNSS receiver.

**Comment by DonLakeFlyer** [comment]
You should talk with the PX4 Firmware folks since they are the ones that own the driver code. The PX4 slack channel might be a good place to start.
