### ISSUE TITLE
Fixed Wing Landing loiter flips when dragging (bug)

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#9514]
## Expected Behavior
Landing loiter should stay showing CW or CCW when dragging Land or Loiter point.

## Current Behavior
Landing Loiter flips direction with dragging Land or Loiter points.

## Steps to Reproduce

1. Plan a fixed wing landing pattern
2. uncheck "Loiter clockwise", observe loiter direction flip sides
3. drag Land waypoint, observe loiter direction flip
4. drag Loiter point, observe loiter direction flip again
5. repeat.
6. dance.

## System Information

- Operating System: Windows
- QGC Version: 4.1.x stable
- QGC build: stable from appveyor

## Log Files and Screenshots
![Landing Pattern Loiter Flip](https://user-images.githubusercontent.com/12117027/110045421-437ac480-7d10-11eb-83f8-b82cb60abd24.gif)

**Comment by DonLakeFlyer** [comment]
Should be fixed now

**Comment by Antiheavy** [comment]
yep, looks like it based on latest daily build testing.  no more flipping.
