### ISSUE TITLE
Unable to set Set servo mission item for index bigger than 5

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [mavlink/qgroundcontrol#9517]
## Expected Behavior
You should be able to use the "Set servo" mission item to configure servo outputs during a mission as configured in QGC mission plan

## Current Behavior
QGC returns a error message that the servo index should be between 0...5
However, this doesn't make much sense, especially given that the servos are usually connected to higher index numbers

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Add a Set servo mission item to the mission
2. Try to set a PWM value for servo 9
3. Upload mission to vehicle
4. QGC complains that the actuator index should be between 0-5

## System Information
- Operating System: Ubuntu 18.04 Bionic
- QGC Version: 4.1.1
- QGC build: stable
- Flight Controller: PX4 SITL
- Autopilot (with version): PX4 master(22abe1619b99dacc13c45767d41cc2e83ddb1fc8)

## Detailed Description
This was observed when trying to test https://github.com/PX4/PX4-Autopilot/pull/16758

## Log Files and Screenshots
![image](https://user-images.githubusercontent.com/5248102/110223971-f2b5c800-7ed7-11eb-86f3-aece3bd74f96.png)

**Comment by DonLakeFlyer** [comment]
That message is coming from the firmware. You'll need to talk with them.
