### ISSUE TITLE
Android File Saving/Opening

### ISSUE THREAD

**Issue by patricktnelson** [mavlink/qgroundcontrol#9537]
Installing QGC stable 4.1.1 on Android 10 won't allow proper file saving/opening if 4.1.1 is the first version of QGC to be installed on device. 4.1.1 doesn’t request permission to access files, only photos and media. A workaround for this is installing 4.0, which does work correctly, with file explorer opening on right, and then update to 4.1.1. This carries over the file saving permissions.

see:
https://discuss.px4.io/t/qgroundcontrol-android-file-sharing/9741/3

**Comment by LorenzMeier** [comment]
Thanks for reporting!

**Comment by DonLakeFlyer** [comment]
@patrickelectric Is your Documents location on an external SD card? Or is it using internal storage?

**Comment by patricktnelson** [comment]
My Documents location is on internal storage. I tried the whole, "create the correct QGC file save path" to fix problem, but it said I didn't have permission to save there.

**Comment by DonLakeFlyer** [comment]
Ok, I have one thing to try. I'm worried that this won't be fixable until I upgrade to a newer Qt which has better Android 10 support.

**Comment by DonLakeFlyer** [comment]
Can you try this apk: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/android-build-debug.apk. This is a stable build with some tweaks to try a fix.

**Comment by patricktnelson** [comment]
That did it. It correctly prompted me to obtain permission to access files. The file access to the right side didn't work the first time I ran QGC, but then I force stopped and relaunched. Then it worked as it should. I successfully saved and loaded missions.
