### ISSUE TITLE
Switch Firmware Upgrade to QSerialPort once there is unbuffered i/o support

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#955]
We currently have to use QExtSerialport for firmware upgrade. It has it's own set of problems such as lousy error reporting. But it does support unbuffered i/o. It would be nice to get rid of this and use the Qt supported apis.

**Comment by Susurrus** [comment]
https://bugreports.qt.io/browse/QTBUG-44699

**Comment by Susurrus** [comment]
@DonLakeFlyer Can you better explain the issues encountered when the buffered i/o mode and post them here so that I can forward them up to the linked Qt bug or can you make a Qt account and assist with explaining the reasoning to the Qt folks?

**Comment by DonLakeFlyer** [comment]
It's just too slow. Slows down flashing too much, especially on windows which is already crazy slow.

**Comment by Susurrus** [comment]
Can the buffer size be set or modified somehow with the underlying QDeviceIO object?

**Comment by Susurrus** [comment]
They just closed this issue upstream as Out of Scope. Is this something worth harassing them about because it's still a problem or does qextserialport work fine?

**Comment by DonLakeFlyer** [comment]
I don’t think this will ever happen on the QT side. It’s fine. At some point we may be able to switch to using buffered for flash as well. A lot of the buffered issue may have actually just bee the 1M+ plus limit thing causing false positives.

**Comment by LorenzMeier** [comment]
Closing as stale.
