### ISSUE TITLE
Make it easier/clearer to exit video fullscreen mode

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#9563]
When streaming video, if you double click the video surface, the video will grow to fullscreen mode. User reports it was unclear how to exit this mode (you have to double click the surface again).

User suggested something people would naturally try, like the escape key.

**Comment by DonLakeFlyer** [comment]
I think something like a simple message that says double-click to exit full screen or something which shows up if you have the mouse over the video might work nicely.

**Comment by Ljung323** [comment]
@jaxxzer @DonLakeFlyer 
I've just tried to implement this feature in #9612.
Could you have a check whether it's intended behavior?

**Comment by holden-zenith** [comment]
This should be closed
