### ISSUE TITLE
QGC v2.0.3. text to speech on Windows not working

### ISSUE THREAD

**Issue by philipoe** [mavlink/qgroundcontrol#957]
In QGC v2.0.3. there seems to be no audio outputs under Windows, although this is clearly supposed to work both from looking at the code and from discussions with other developers. In this case, audio output was not working on QGC v2.0.3 (via the standard-binaries) on Win7 64bit. The exact bug-report can be seen here:

https://groups.google.com/forum/#!topic/qgroundcontrol/YTFtHe6N87Y

Personally, if this bug is reproducable, I'd consider this a serious issue, as loosing the plane due to missing audio low-battery warnings etc. is a significant risk for every user!

**Comment by LorenzMeier** [comment]
Fixed.
