### ISSUE TITLE
It is no longer possible to see a list of all parameters in the Vehicle Setup page

### ISSUE THREAD

**Issue by dwiel** [mavlink/qgroundcontrol#9574]
## Expected Behavior
I used to be able to see a list of all parameters sorted alphabetically and scroll through them.

## Current Behavior
I must select a single parameter category and see only those.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Connect to flight controller
2. go to Parameter section of Vehicle Setup

## System Information
When posting bug reports, include the following information
- Operating System: Mac 10.14.6
- QGC Version: 4.1.1
- QGC build: stable
- Flight Controller: mRo x2.1
- Autopilot (with version): Ardupilot Copter 4.0.3

**Comment by booo** [comment]
Can you reproduce this with newer versions of QGC. I can't.
