### ISSUE TITLE
Some questions about using new hardware modules

### ISSUE THREAD

**Issue by DragonOnGit** [mavlink/qgroundcontrol#9577]
Greetings to all developers.

I am working on a subject that using xbee telementry modules to replace the 3DR radio. And I try to modefied the PX4 code and the QGC code, still have nothing connection. Is there anyone who doing the same work or have done the same thing? When I searching for XBEE and QGC I found only one blog said about it and he/she have done it, and pass the test.

And please tell me if this can work or not. Because I really work on it for a long time.

**Comment by DonLakeFlyer** [comment]
Issue are for bugs. You should ask on Slack discussions to see if anyone can help.
