### ISSUE TITLE
2D offline map integration with image files(png,jpeg,tif files) in QGC:

### ISSUE THREAD

**Issue by cnag-steven** [mavlink/qgroundcontrol#9583]
> Not possible. Although I think you can use mapbox to created your own hosted maps and then hook up that way.

Hi @DonLakeFlyer ,
Thanks for the reply. should i add external files(jpeg,png ,tif) in mapbox API and then call it in QGC? Is this how you are suggesting to integrate the 2D files(image files) in the existing map?
If it is possible 
please tell me how should i add external files in mapbox API .
Thank You

_Originally posted by @cnag-steven in https://github.com/mavlink/qgroundcontrol/issues/9576#issuecomment-814618097_

**Comment by jansvanda** [comment]
Hello, since i see the issue is completed and has been marked as FR, is there now some way to show own images on QGC? Or only through own mapbox API?
