### ISSUE TITLE
[Feature Request] return to moving QGC/home

### ISSUE THREAD

**Issue by booo** [mavlink/qgroundcontrol#9610]
We would like to use QGC on a moving vessel and would like the plane to return to a moving home as soon as we enter RTL or a similar mode. We can't work with a fixed home position because the vessel is moving while the plane is in the air.

As far as I can see there is already an option to stream the QGC position to the vehicle that can be enable in the Settings of QGC.

We would like this to work with ArduPilot/ArduPlane.

I guess we could solve this with an external script too but for ease of use we would like this to be part of QGC.

**Comment by DonLakeFlyer** [comment]
QGC doesn't have support for resetting the home position. The code you are referring to is for Follow Me support.

**Comment by booo** [comment]
I changed the subject of the issue to address the fact that this is a feature request.

**Comment by booo** [comment]
Resolved with ac97ce4
