### ISSUE TITLE
Sensor and Battery warning in HITL mode

### ISSUE THREAD

**Issue by RflySim** [mavlink/qgroundcontrol#9634]
![hil](https://user-images.githubusercontent.com/8308510/117546456-196db780-b05d-11eb-87de-4ac3b1f65991.png)
![111](https://user-images.githubusercontent.com/8308510/117546852-2c818700-b05f-11eb-8ac8-bbba430fd081.png)

Hello, 
   I found that the sensor calibration warning appears in QGC version 4.X.X, however, the calibration cannot be performed because there is no real sensor data in HITL mode. The sensor calibration tab was hidden in QGC version 3.X and below, which is OK for our team to do simulations in indoor simulation tests.
  Besides, I suggest that the battery parameters missing warnings should also be hidden, because the battery status is faked in HILT mode too.

sincerely

**Comment by DonLakeFlyer** [comment]
Sensors cal has been fixed. But the missing parameters is a firmware bug. Can you report there. Those should be available with HITL.
