### ISSUE TITLE
Set RC to Param - mismatch values

### ISSUE THREAD

**Issue by diablo1281** [mavlink/qgroundcontrol#9637]
I am testing "Set RC to Param" function in my custom autopilot firmware. It seems like values "Scale" and "Center value" are switched.

In version 3.5.6 it looks ok, but since version 4.x.x it doesn't work properly.

**Comment by DonLakeFlyer** [comment]
I looked at the code and as far as I can tell they are correct. Do you have some steps to reproduce which show the problem?

**Comment by diablo1281** [comment]
Here are some screenshots with the way we found it:
1. During debug of FCU firmware set breakpoints for message PARAM_MAP_RC.
2. Open QGroundControl 3.5.6 and set any param to RC. (screenshot below)
![QGC_3 5 6_rc_to_param](https://user-images.githubusercontent.com/11412336/119791515-2f8ccc00-bed5-11eb-959f-c71ea1d5f01d.png)
3. In debugger we hit a breakpoint and can check values for reviced message. (screenshot below) 
![QGC_3 5 6_rc_to_param_debug_marked](https://user-images.githubusercontent.com/11412336/119791545-3582ad00-bed5-11eb-9afe-8a2379b6aca2.jpg)
4. Next repeat steps above in QGC 4.1.0+. In screenshots below you can see values `scale` and `value0` are switched.
![QGC_4 1 0_rc_to_param](https://user-images.githubusercontent.com/11412336/119791531-3287bc80-bed5-11eb-9898-11857e94d707.png)
![QGC_4 1 0_rc_to_param_debug](https://user-images.githubusercontent.com/11412336/119791537-34518000-bed5-11eb-8a95-3a768d75d636.png)
