### ISSUE TITLE
Feature request - Crop sprayer

### ISSUE THREAD

**Issue by mohammada315** [mavlink/qgroundcontrol#9639]
![image](https://user-images.githubusercontent.com/29116372/117925983-4516c900-b30d-11eb-972d-6eca83c58bf5.png)
Is this supported?

**Comment by DonLakeFlyer** [comment]
Nope

**Comment by mohammada315** [comment]
@DonLakeFlyer  Will it be added in the future?

**Comment by DonLakeFlyer** [comment]
No plans at this point

**Comment by HTRamsey** [comment]
duplicate of #7263
