### ISSUE TITLE
Battery monitor doesn't get updated after changing the battery and restarting the flight controller

### ISSUE THREAD

**Issue by buckker** [mavlink/qgroundcontrol#9642]
Hi

I'm using QGC V4.1.2 on a Android device (CUAV H16) with a Nora flight controller (ardupilot, copter 4.0.7). I noticed that the battery monitor is stuck after changing the battery for a new flight. The only way to get correct values is to close the app and restart it. After that QGC shows the correct battery information. 

I normally use Mission Planner. If I restart the flight controller without closing Mission Planner, the battery information will be showed correcty. 

Many thanks in advance

Michael

**Comment by DonLakeFlyer** [comment]
This is a dup of #9209

**Comment by DonLakeFlyer** [comment]
There should be a new daily in a few hours. Can you test it out?
