### ISSUE TITLE
Px4FLOW can't get video stream

### ISSUE THREAD

**Issue by moralkerim** [mavlink/qgroundcontrol#9643]
Hello, i should have seen video stream from PX4Flow tab on the Qgroundcontrol after uploading px4flow firmware but i cant.

On the terminal, i get messages such as below:

`qrc:/qml/PX4FlowSensor.qml:26:5: QML Image: Failed to get image from provider: image://qgcimages/81/209`

![Screenshot from 2021-05-14 15-44-51](https://user-images.githubusercontent.com/44924953/118272975-0a0ec400-b4cc-11eb-99ce-2cb5cd675931.png)

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18.04
- QGC Version: 4.1.3
- QGC build: stable
- Flight Controller: PX4Flow
- Autopilot (with version):px4flow-klt-06Dec2014

Thanks in advance.

Edit: Works with version 3.1.2 in Ubuntu 18.04.

**Comment by DonLakeFlyer** [comment]
Fixed in daily builds
