### ISSUE TITLE
need support about MAV_PROTO_VER parameter

### ISSUE THREAD

**Issue by Cristian-wp** [mavlink/qgroundcontrol#9661]
Hello, sorry for the dummy question...I can not understand this parameter: [https://dev.px4.io/master/en/advanced/parameter_reference.html#MAV_PROTO_VER](url) .

If I have a camera that works with protocol 1 and a gimball with protocol 2, I have to set the value to 0?

"0: Default to 1, switch to 2 if GCS sends version 2" It means that it can convert messages between the two protocols?
Thanks in advance :slightly_smiling_face:

**Comment by DonLakeFlyer** [comment]
That would be a firmware question not QGC.
