### ISSUE TITLE
Microhard RSSI functions seem to mix between uplink and downlink values

### ISSUE THREAD

**Issue by tzuriel-spearuav** [mavlink/qgroundcontrol#9663]
MicrohardManager::uplinkRSSI should return the uplink rssi value https://github.com/mavlink/qgroundcontrol/blob/58610ba74238ea608669a6a856ce2410f931299a/src/Microhard/MicrohardManager.h#L49-L50

**Comment by DonLakeFlyer** [comment]
I'm not sure the MicrohardManager stuff was ever really finished. Not sure it's in a working state.

**Comment by HTRamsey** [comment]
microhard has been removed
