### ISSUE TITLE
How to build using container on windows 10

### ISSUE THREAD

**Issue by haiyu-zat** [mavlink/qgroundcontrol#9664]
Hi there,

I am hoping to build QGC using Docker on WSL2 on Windows 10. I am following the guide here:

https://dev.qgroundcontrol.com/master/en/getting_started/container.html

I am able to build the image but when I try to run it I get

```fatal: not a git repository: '/project/source/.git'```

Can somebody help me understand how to resolve above error or maybe where I should run the below commands?

```
mkdir build
docker run --rm -v $PWD./project/source -v $PWD/build./project/build qgc-linux-docker
```

**Comment by kistlin** [comment]
It looks like the documentation contains errors.

From https://docs.docker.com/storage/volumes/
```
-v or --volume: Consists of three fields, separated by colon characters (:). The fields must be in the correct order, and the meaning of each field is not immediately obvious.
```
=> `separated by colon characters (:)`

Therefore the right command should be
```
docker run --rm -v ${PWD}:/project/source -v ${PWD}/build:/project/build qgc-linux-docker
```
Don't bother about the `{}`.
