### ISSUE TITLE
RTSP Video Stream Problem !

### ISSUE THREAD

**Issue by texTa11** [mavlink/qgroundcontrol#9679]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## System Information
When posting bug reports, include the following information
- Operating System: [Windows10, Ubuntu 20.04]
- QGC build: [4.1.3]

## Detailed Description
RTSP Video stream works in version 4.0.11 but not in 4.1.0 ,4.1.1, 4.1.2, 4.1.3.  Will a solution be offered on this issue?

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by valbok** [comment]
It might be problem in decodebin3, you can update to latest version.
