### ISSUE TITLE
Building with docker, output missing SDL2 library

### ISSUE THREAD

**Issue by positron96** [mavlink/qgroundcontrol#9683]
I've just followed https://dev.qgroundcontrol.com/master/en/getting_started/container.html to build QGC with docker. 

The build succeeded and I have a binary in `build/staging` folder. However, I cannot run it due to the following error:

```
positron@xububox18:~/Downloads/qgroundcontrol/build/staging$ ./qgroundcontrol-start.sh 
/home/positron/Downloads/qgroundcontrol/build/staging/QGroundControl: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

Is this expected? I had the impression that the output of container build would be self-sufficient and required libraries are copied from container to `build` directory (as are Qt libraries and `libairmap-qt`). So it seems like a bug to me.

## Expected Behavior
The binary launches

## Current Behavior
The binary cannot be started due to missing library.

## Steps to Reproduce:
1. Build using docker as described https://dev.qgroundcontrol.com/master/en/getting_started/container.html
2. try to launch `build/staging/qgroundcontrol-start.sh`

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 18 x64 
- QGC Version: whatever is inside official container
- QGC build: self-built from source, commit 3b0d3b2341e1a40257c33bda77256d3f48862b68

**Comment by HTRamsey** [comment]
SDL is built automatically via cmake now
