### ISSUE TITLE
QGroundControl on first launch always starts with indoorPalette

### ISSUE THREAD

**Issue by akontsevich** [mavlink/qgroundcontrol#9688]
## Expected Behavior
QGC should start with `indoorPalette=0` (light mode) setting on first start as it set as the default in `App.SettingsGroup.json` file, ...

## Current Behavior
... however it always starts in dark mode (`indoorPalette=1`).

## Steps to Reproduce:
1. Clean up `~/.config/QGroundControl.org/QGroundControl Daily.ini` file
2. Start fresh daily build of QGroundControl
3. Started in dark mode while light is the default:

```
{
    "name":             "indoorPalette",
    "shortDesc": "Application color scheme",
    "longDesc":  "The color scheme for the user interface.",
    "type":             "uint32",
    "enumStrings":      "Indoor,Outdoor",
    "enumValues":       "1,0",
    "default":     0
},
```
## System Information
- Operating System: Ubuntu 20.04
- QGC Version: 2021-05-29
- QGC build: daily

## Log Files and Screenshots
Settings on the first start:

![Screenshot_20210601_173435](https://user-images.githubusercontent.com/3843657/120341561-a542ce80-c2ff-11eb-9f0e-1991ed56b044.png)

**Comment by DonLakeFlyer** [comment]
I don't think that initial value is respected. If I remember desktop builds start with indoor and mobile builds start with outdoor. Whether that continues to make any sense is debatable.

**Comment by akontsevich** [comment]
We wanted to control this parameter, however our fork always started with indoor, while outdoor is default. Forced to enable it explicitly. So definitely default `Fact` logic works incorrect (it is very strange initial value is not respected) which is confusing and sounds like a bug.
