### ISSUE TITLE
Missing Header Files

### ISSUE THREAD

**Issue by byrnesa2** [mavlink/qgroundcontrol#9689]
----
# Report Info
- OS: Ubuntu 18
- Build from source
- Exact steps to reproduce the problem: Follow instructions on https://dev.qgroundcontrol.com/master/en/getting_started/index.html to clone from git, install QT version 5.12.6, and build in QT Creator. 
---
# Issue:
Error appears:
`error: airmap/qt/client.h: No such file or directory`

**Comment by byrnesa2** [comment]
I believe the issue is that airmap has updated such that they are no longer reliant on qt.

**Comment by DonLakeFlyer** [comment]
Can you try running the commands manually the same as what the build system does and provide the output here?

**Comment by HTRamsey** [comment]
airmap was removed
