### ISSUE TITLE
In fullscreen mode, there's a large gap between the menubar and the menus 

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#969]
Between the Perspectives menu option and the menu itself there's a 10pixel gap or so:

![menu gap](https://cloud.githubusercontent.com/assets/206363/4983113/f6c69f00-6917-11e4-8530-8663495976fa.png)

**Comment by DonLakeFlyer** [comment]
As far as I know we don't really control that. It's a Qt thing.
