### ISSUE TITLE
Sensor Calibration Required in Hardware-In-The-Loop (HITL) simulation

### ISSUE THREAD

**Issue by dimikout3** [mavlink/qgroundcontrol#9695]
I am uploading the latestest PX4 firmware (v1.11.3 px4_fmu-v5_default.px4) to a holybro Pixahawk 4. I am selecting the HITL Quadcopter X air frame, to be used in Airsim. However, when the pixhawk reboots the sensors require calibration, more precisely
only the compass requires calibration the other sensors appear to be calibrated. I can connect to the Airsim simulator and control the UAV via the QgroundControl station, however, the orientation and compass do not function correctly (actually they are not functional at all.) 

Any ideas ?

**Comment by DonLakeFlyer** [comment]
The code to disable sensor cal for HITL mode needs to be put back: https://github.com/mavlink/qgroundcontrol/pull/8617/files
