### ISSUE TITLE
Custom commands on waypoint

### ISSUE THREAD

**Issue by gendebeat** [mavlink/qgroundcontrol#9697]
Hello, im triying to compile qgroundcontrol to have a custom command in the list of waypoint command in plan mode
I searched on internet but no find the answer (maybe github is not the correct way to post this, but i try on 
QGC support page and dont have any answer)   
I think have to add this command to mavlink header file . Then generate this headers for C language and add to QGC mavlink folder. 
After i edit MavCmdInfoCommon.json to add in json format, the "same" command i create on mavlik headers. 
After compile. This custom command dont appear. 
(i can edit other command like name and description, i think are in correct way)
i need to make a custom development to command a payload. i search too much on internet.
or there are other way for inject a command in mavlink flow when drone reach the waypoint.
thanks

**Comment by DonLakeFlyer** [comment]
You need to also update the appropriate FirmwarePlugin::supportedMissionCommands override to add your command there to tell QGC you vehicle supports it.
