### ISSUE TITLE
Stable V4.1 failing to compile due to warnings

### ISSUE THREAD

**Issue by arBalasquide** [mavlink/qgroundcontrol#9700]
## Expected Behavior
Windows Stable_4.1 branch to compile.

## Current Behavior
On Windows (MSVC2015) these warnings are treated as errors and thus compilation ends. However, no issues compiling on Linux with gcc.
```
FTPManager.h:77:19: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here
FTPManager.h:89:9: note: type is not C-compatible due to this member declaration
FTPManager.h:100:7: note: type is given name 'DownloadState_t' for linkage purposes by this typedef declaration
```

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Clone repo
2. git checkout Stable_V4.1
3. git submodule update --init --recursive
4. Use QT Creator to compile

This is the patch I applied to get it to work.
```
diff --git a/src/Vehicle/FTPManager.h b/src/Vehicle/FTPManager.h
index 00ee97c7b4..876b71bf8e 100644
--- a/src/Vehicle/FTPManager.h
+++ b/src/Vehicle/FTPManager.h
@@ -74,7 +74,7 @@ private slots:
         uint32_t cBytesMissing;
     } MissingData_t;
 
-    typedef struct {
+    typedef struct DownloadState_t {
         uint8_t                 sessionId;
         uint32_t                expectedOffset;         ///< offset which should be coming next
         uint32_t                bytesWritten;
```

So maybe we should also patch it for Stable_V4.1 to avoid this issue?

**Comment by booo** [comment]
I think that was fixed in 037569876363d34e78d3d5f5a9a75178d20540fa.
