### ISSUE TITLE
Channels flickering in radio calibration using Qgroundcontrol (Spektrum NX8 transmitter and AR8010T receiver)

### ISSUE THREAD

**Issue by karanjotsingh010** [mavlink/qgroundcontrol#9713]
Hello
I am trying to calibrate my Spektrum NX8 and AR8010T receiver using Qgroundcontrol in the radio setup. NX8 transmitter is already "bind" to the AR8010T receiver. However, during calibration the channels are flickering a lot which does not allow me to complete the calibration. Of course, the problem is bigger than calibration as I need stable channel input in Qgroundcontrol. As I am unable to post a short video, I have attached 2 consecutive screenshots for reference. Just to highlight the issue again, I am working with an 8 channel transmitter (NX8) while Qgorundcontrol sometimes shows more than 8 channels and the value in all 8 channels keep changing without radio controller input. Please let me know your suggestions.
Thank you.
![image](https://user-images.githubusercontent.com/58835285/122150606-9ed05d00-ce90-11eb-97b3-b77b8f3c6c66.png)
![image](https://user-images.githubusercontent.com/58835285/122150627-aa238880-ce90-11eb-9b96-fe71c08e574a.png)

**Comment by DonLakeFlyer** [comment]
That would be a vehicle side problem. QGC gets that data over mavlink. You need to talk with the firmware folks
