### ISSUE TITLE
Display non MAV vehicles on QGC via generated mavlink messages

### ISSUE THREAD

**Issue by 7dnaiel492** [mavlink/qgroundcontrol#9728]
I would like to be able to display a custom vehicle's location on QGC along with my other MAVs. Is there a way to publish udp mavlink messages (maybe pymavlink?) and a documented format of everything required for QGC to display the vehicle?

Not sure if this is feasible or already a feature. Any direction is appreciated. 

Thanks

**Comment by DonLakeFlyer** [comment]
Vehicle needs to send a heartbeat for it to show up. Look at MultiVehicleManager for the starting point
