### ISSUE TITLE
QtLocationPlugin using Qt's QML API

### ISSUE THREAD

**Issue by chobbs1** [mavlink/qgroundcontrol#9740]
Tell us a bit about the feature:
- What problem does it solve?

The QtLocationPlugin as it currently exists implements a version of the Qt Maps and Navigation (C++) API that was written by qgroundcontrol developers. 

This was a poor design decision. The Qt5 documentation explicitly states not to use it (https://doc.qt.io/qt-5/location-maps-cpp.html):
"Currently it is not possible to interact with maps via C++. Mapping applications must use the Maps and Navigation (QML) API"

I'm also surprised didn't see the following warning, which is in every private header:

---------------------------------------------------------------------------------------------------------------------
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
---------------------------------------------------------------------------------------------------------------------

My point is that having code dependent on private headers is not sustainable, bad practice and Qt will not provide long-term support. 

- What does it do?
I am requesting that developers upgrade the QtLocationPlugin to use the Qt Maps and Navigation (QML) API in the relevant places. It needs to implement the same functionality as currently exists.

This will increase the long term viability of the qgroundcontrol project.

- What flight stacks must it work with? (All, PX4, ArduPilot)
Flight stack agnostic

- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
N/A

- Are there other systems that have this feature?
n/a

- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
n/a

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
I think the source of the problem starts in:
QGeoServiceProviderPluginQGC.cpp:73, with the implementation of the function 
QGeoMappingManagerEngine* QGeoServiceProviderFactoryQGC::createMappingManagerEngine(const QVariantMap &parameters, QGeoServiceProvider::Error *error, QString *errorString)

**Comment by DonLakeFlyer** [comment]
So let's review:
* QGC's custom Qt map plugins supports things like: Offline map tile support, support for multiple map providers out of the box, ability to add custom map providers in a simple manner. None of which is directly supported by Qt.
* It's been in the codebase for around for 7+ years now
* Over those 7+ years we have updated Qt versions many, many times. All without problems and almost never having to touch the custom plugin code to change it when we move to a new Qt version.
* If you look here https://doc.qt.io/qt-5/qtlocation-geoservices.html you will see an explanation of how to get started implemented a custom map plugin. Which is exactly how QGC does it.

Yet somehow this was totally the wrong thing to do and was a poor design decision. I'm sorry but you seem to be very confused and as far as I can tell you don't know what you are talking about.
