### ISSUE TITLE
Please add change speed, climb/descend speed, and change altitude commands

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#9742]
Subject says it all, it would be nice to be able to change speed/altitude in an easy way.

**Comment by booo** [comment]
Please provide additional information. Two sentences do not provide enough information for a developer to implement your feature request.

If no additional information arrives I suggest we close this ticket.

**Comment by AndKe** [comment]
Basically: add some GUI for the important parts of:
https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED
https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_ALTITUDE

Both are typically used during auto-missions, and a basic part of any other GCS (MP,AP2,MAVProxy)

**Comment by HTRamsey** [comment]
They are under "Action" in the toolbar
