### ISSUE TITLE
Always the text to speech bug! 

### ISSUE THREAD

**Issue by Arianjalali1996** [mavlink/qgroundcontrol#9785]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
the code should run on QT Creator. The problem is that an error message is written. The module text to speech is missing.

## Current Behavior
after the error code, there comes nothing on it and i cant use the qgroundcontrol

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.
2.
3.
4.

## System Information
When posting bug reports, include the following information
- Operating System: [Ubunru 20.04 lts]
- QGC Version: [4.1.3]
- QGC build: [e.g., daily, stable, self-built from source, etc...]
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
- [QGC Console Logs](https://docs.qgroundcontrol.com/en/Support/Support.html#reporting-bugs)
- Autopilot logs when available (post a link).
- Screenshots of QGC to help identify the current issue/bug behavior.

**Comment by patrickelectric** [comment]
Do you have `libspeechd` installed ?
