### ISSUE TITLE
Comm Links at the main screen!

### ISSUE THREAD

**Issue by RMFPV** [mavlink/qgroundcontrol#9836]
Tell us a bit about the feature:

- What problem does it solve?

      Going each time through the three menus just to connect to the vehicle - is insane. I've never seen such an inconvenient connection interface ever. All progs have connection button at the main screen. 

- What does it do?

      It will make connection process easy as it should be.

- What flight stacks must it work with? (All, PX4, ArduPilot)

      ALL

**Comment by HTRamsey** [comment]
You can select comm links via the main tool bar
