### ISSUE TITLE
Edit position of survey

### ISSUE THREAD

**Issue by saandycc** [mavlink/qgroundcontrol#9845]
Dear team,
Using the "Edit position" function in the options of a survey, setting a new position to it seems to have no effect (unlike for waypoints).
May you have a look at that?
Thanks in advance!

**Comment by booo** [comment]
We are talking about the Edit Position option that works on waypoints but not on complex patterns:

![screenshot_20210901_115629](https://user-images.githubusercontent.com/424513/131651953-8d60c14f-4655-47e2-a4b6-3a1b48d64a1e.png)

**Comment by julled** [comment]
I am also in need for getting this bug fixed.

**Comment by julled** [comment]
i tried to fix this in https://github.com/mavlink/qgroundcontrol/pull/9865

**Comment by booo** [comment]
Even tough there was no proper commit body this was fixed by #9865 therefore I'm closing this issue.
