### ISSUE TITLE
No more .AppImage to download

### ISSUE THREAD

**Issue by Cristian-wp** [mavlink/qgroundcontrol#9859]
Where I can find the .AppImage for the 4.1.3,4.1.2, ecc...?
From the single version are not presents...

**Comment by booo** [comment]
Could you please provide us with a bit more information about your problem. Thanks a lot.

**Comment by Cristian-wp** [comment]
In the release page https://github.com/mavlink/qgroundcontrol/releases there are no more .AppImage to download for some QGC version. 
In particular from v4.1.0 to v4.1.3

**Comment by zdanek** [comment]
@Cristian-wp latest versions are present. Can we close this issue as 4.1.0-3 are very historic?

**Comment by booo** [comment]
I guess we can't do much about it. Please use the newer versions.
