### ISSUE TITLE
"disconnect" link button UI is broken

### ISSUE THREAD

**Issue by Williangalvani** [mavlink/qgroundcontrol#9866]
![disconnect-ui](https://user-images.githubusercontent.com/4013804/133170034-afee22e2-6125-46aa-8774-3666a2b20fdb.gif)

The errors start after the first click, apparently the UI is not updating after disconnecting. Switching pages updates the status (enables the connect button).

QGC 4.1.4

**Comment by HTRamsey** [comment]
This works better now in master
