### ISSUE TITLE
Stable 4.2: Work items

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#9871]
This is the list of remaining work to get Stable 4.2 out the door:
* Move to Qt 5.15
* Move fully to GitHub actions for all releases:
  * Main blocker at the moment is S3 upload

Issues marked for 4.2: https://github.com/mavlink/qgroundcontrol/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+V4.2%22. (Note I haven't yet had time to go through and clean up this list so there may be crap in here still. I'll get to that soon.)

Please add individual comments for missing things and I'll update the list. Also mark any issues as Release V4.2 if they need fixes prior to release.

**Comment by alexwien7** [comment]
Its just a minor fast issue: 
- update file "/ChangeLog.md" last entry is from V4.1.2, missing entries for v4.1.3, v4.1.4

**Comment by booo** [comment]
Are you sure we can tackle this massive lists of commits for V4.2? What is the time frame we are talking about?
