### ISSUE TITLE
MAVlink forwarding not available in v4.0.11?

### ISSUE THREAD

**Issue by evanatherton1** [mavlink/qgroundcontrol#9912]
I downloaded QGC v4.0.11 (latest version available for ubuntu 18.04). It doesn't appear to have MAVlink forwarding as an option in Application Settings > MAVlink > Ground Station. This was available in previous versions. If I want to forward MAVlink messages to  specific ip address over a UDP port, how do I specify those values?

**Comment by DonLakeFlyer** [comment]
You'll need to use the latest version which is 4.1
