### ISSUE TITLE
qgroundcontrol hangs when starting

### ISSUE THREAD

**Issue by tjscientist** [mavlink/qgroundcontrol#9926]
The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/Support/Support.html#github-issues

For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

If you are using an old stable release please upgrade first and verify your issue before reporting.
----

## Expected Behavior
Program should start

## Current Behavior
Program hangs

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Clicking on any of the three shortcuts causes the system to hang.
## System Information
When posting bug reports, include the following information
- Operating System: Windows 10
- QGC Version: Latest as of today (first time downloading)
- QGC build: Latest stable build
- Flight Controller: [e.g., Pixhawk I, Pixhawk Mini, Pixhawk 2, etc.]
- Autopilot (with version): [e.g., PX4 1.8.1, Ardupilot Copter 3.6.1]

## Detailed Description
Provide further details about your issue/bug.

## Log Files and Screenshots
Dump file: 
https://www.dropbox.com/s/kidyikvbc8bnotg/QGroundControl.DMP?dl=0

**Comment by tridge** [comment]
I also get this on win10. qgroundcontrol starts using lots of CPU, but no window displays. It will stay that way until killed with task manager. Happens on both stable release and latest daily from today.
qgc daily on linux works fine
