### ISSUE TITLE
How do I get the video stream in qground control in a separate application

### ISSUE THREAD

**Issue by hexbo** [mavlink/qgroundcontrol#9958]
This idea is based on the following scenario:

Alice, the operator, connects to the UAV through QGC and views the video. Bob, the logistics personnel, hopes to see the real-time UAV image through the app in the mobile phone or a web page without operating QGC

The question is, how do I separate the video stream in qground control and transmit it to？

**Comment by booo** [comment]
Please provide additional information about your UAS.

Normally the UAV will create a video stream and in the best case multiple parties can listen to this video stream. Please check how your UAV creates the video, where it is send to and how you can use gstreamer to e.g. duplicate this stream if it is a none broadcast stream.

I don't think this is a QGC problem therefore I close the issue. Please reopen or comment if you think this is a QGC related problem or a feature you are looking forward in QGC.
