### ISSUE TITLE
Wrong spelling of words in QGroundControl document

### ISSUE THREAD

**Issue by qiang-sir** [mavlink/qgroundcontrol#9975]
## Expected Behavior
Modify the spelling of the word "overries" which is shown in the attached picture.

## Current Behavior
The word "overrides" is spelled "overries".

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1.Locate to Top Level Views
2.Locate to Plan Views
3.Find the word position as shown in the picture
4.Modify the spelling of the word "overries"
![20211102102844](https://user-images.githubusercontent.com/88809699/139778266-8934dcf1-c925-4440-a9ee-3397ba98dcc0.png)

**Comment by cbjornram** [comment]
I created a PR for you:
https://github.com/mavlink/qgc-dev-guide/pull/138

**Comment by hamishwillee** [comment]
Thanks! Create a PR the right thing to do. Much appreciated.
