### ISSUE TITLE
Bump RC_CHANNELS stream rate while calibrating

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#999]
See https://github.com/PX4/Firmware/issues/995#issuecomment-62682367

**Comment by LorenzMeier** [comment]
The Firmware will accept these packets and configure a stream accordingly:
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1107-L1122

**Comment by DonLakeFlyer** [comment]
It's a little slow but pretty workable.
