### ISSUE TITLE
RTSP choppy video

### ISSUE THREAD

**Issue by highfreq** [mavlink/qgroundcontrol#9991]
I am using a ionodes board connected to a sony camera. The board runs an rtsp server to wich i connect.

Video is fine on windows and linux (around 20 fps). On android it is really choppy and fps is around 2-3.

Same stream played on same android device using vlc is fluid at 20fps.

Is there anywhere i can look to fix this?

It does the same on stable and daily.

This is the stream from ffplay:

Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 14.99 fps, 14.99 tbr, 90k tbn, 180k tbc

**Comment by booo** [comment]
Is there anyway you can test this with gstreamer alone on android?

**Comment by highfreq** [comment]
If i need root no.

**Comment by fredowski** [comment]
Hi, could you try the Android build from the PR: https://github.com/mavlink/qgroundcontrol/pull/10420 ? The gstreamer pipeline is changed there.
